### ISSUE TITLE
OpenMM installation problem

### ISSUE THREAD

**Issue by sshukla101** [pandegroup/openmm#1003]
I have been trying to install openMM in the linux cluster from the source code downloaded from the github. 

I ran 

"./install.sh"

But it is giving the following error:

"/home/sshukla4/project-cse/anaconda/bin/python: can't open file 'setup.py': [Errno 2] No such file or directory

INSTALLATION FAILED"

I have searched other forums for this error. They seem to suggest that setup.py is provided by the package and is not the part of python installation. I am not able to find this file anywhere. 

Any heads-up?

-Saurabh,
UIUC

**Comment by jchodera** [comment]
If you're using Anaconda python, it would be much easier for you to simply use `conda` to install OpenMM:
```
conda config --add channels http://conda.binstar.org/omnia
conda install openmm
```

**Comment by jchodera** [comment]
If you really want to build from the C++ source yourself, the build process (which does not use that `./install` file, which is only used in creating binary packages, I believe) is documented in the [user guide](http://docs.openmm.org/6.2.0/userguide/application.html#installing-openmm).  But I highly recommend you try the `conda` path first---it's really the quickest way to get up and running.

**Comment by jchodera** [comment]
There are also binary packages distributed here:
https://simtk.org/project/xml/downloads.xml?group_id=161

**Comment by rmcgibbo** [comment]
This file should not be in root directory of the source package though: https://github.com/pandegroup/openmm/blob/master/install.sh

**Comment by rmcgibbo** [comment]
That's the installer script we use with the binaries. It should live somewhere in `devtools/` in the source distribution.

**Comment by sshukla101** [comment]
Is installing from conda and installing from the source exactly the same?

PS: Conda seems to have worked. I still need to run some test simulations to check if it is installed correctly.

**Comment by rmcgibbo** [comment]
Installing from conda means that you're using precompiled binaries that we provide. Installing from source means that you're compiling yourself.

**Comment by jchodera** [comment]
> It should live somewhere in devtools/ in the source distribution.

Good call, @rmcgibbo.  Are you going to tackle this in a PR, or should I?

**Comment by rmcgibbo** [comment]
go for it. you know better than I how the non-conda packaging works.

**Comment by jchodera** [comment]
Will do!
