### ISSUE TITLE
Some CPU platform test failures

### ISSUE THREAD

**Issue by rmcgibbo** [pandegroup/openmm#1004]
Running on sherlock (CentOS 6.6, Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz) with a couple different compilers. All tests with 42c7781a84e2f828595bdf3c3d732bfb45532849. 

1) clang version 3.4 (tags/RELEASE_34/final). No failures :white_check_mark: 
2) gcc (GCC) 4.8.1 20130715 (Red Hat 4.8.1-4) TestCpuCustomGBForce fails
```
exception: Assertion failure at TestCpuCustomGBForce.cpp:150.   Expected [-117.436, 78.1114, -10.5441], found [-128.571, 44.9566, -8.68634]
```
3) gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11) TestCpuCustomGBForce fails
```
exception: Assertion failure at TestCpuCustomGBForce.cpp:150.   Expected [-117.436, 78.1114, -10.5441], found [-128.571, 44.9566, -8.68634]
```
4) icc (ICC) 15.0.0 20140723, although perhaps this isn't formally supported
```
exception: Assertion failure at TestCpuNeighborList.cpp:118
exception: Assertion failure at TestCpuGBSAOBCForce.cpp:226.  Expected 0, found 8.18476
exception: Assertion failure at TestCpuCustomNonbondedForce.cpp:843.   Expected [0, 0, 0], found [-94.193, -205.722, -94.83]
exception: Assertion failure at TestCpuCustomManyParticleForce.cpp:614.  Expected 3.3147e+07, found 3.29341e+07
exception: Assertion failure at TestCpuNonbondedForce.cpp:472.   Expected [-0.622213, -1.35938, -3.25274], found [-0.292664, -2.93669, -2.84411]
```

------

Running on vspm9 (Ubuntu 15.03, Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz) with ca200ea3eee2f4f0139afc057d7d8bf51315acd1

1) gcc (Ubuntu 4.9.2-10ubuntu13) 4.9.2, TestCpuCustomGBForce fails
```
exception: Assertion failure at TestCpuCustomGBForce.cpp:150.   Expected [-117.436, 78.1114, -10.5441], found [-128.571, 44.9566, -8.68634]
```
2) Ubuntu clang version 3.6.0-2ubuntu1 (tags/RELEASE_360/final) (based on LLVM 3.6.0)
TestCpuEwald, TestCpuNonbondedForce, TestCpuGBSAOBCForce, TestCpuCustomNonbondedForce failed.
```
exception: Assertion failure at TestCpuEwald.cpp:111.  Expected -382047, found -nan
exception: Assertion failure at TestCpuNonbondedForce.cpp:224.  Expected 79.9185, found -nan
exception: Assertion failure at TestCpuGBSAOBCForce.cpp:226.  Expected 0, found -nan
exception: Assertion failure at TestCpuCustomNonbondedForce.cpp:727.  Expected -nan, found -1609.16
```

**Comment by rmcgibbo** [comment]
All of these are now fixed except the linux-64 failures with clang 3.6.0.

**Comment by peastman** [comment]
Which of the above systems does "linux-64" refer to?  What are the current failures?

**Comment by rmcgibbo** [comment]
Current failures are only with clang 3.6.0. I've tried clang 3.6 only on Ubuntu 15.04 (64-bit). I think the problem is with clang 3.6.0's avx support, but I'm not 100% sure.

**Comment by rmcgibbo** [comment]
All of these are fixed now.
