### ISSUE TITLE
FATAL: Error inserting nvidia (/lib/modules/2.6.32-358.18.1.el6.x86_64/extra/nvidia.ko): No such device

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1006]
On our cluster head node (Linux CentOS 6) which has CUDA installed but no GPUs, I've run into this odd behavior when trying to create an OpenMM `Context`:
```
>>> import simtk.openmm as mm
>>> from openmmtools import testsystems
>>> testsystem = testsystems.HarmonicOscillator()
>>> integrator = mm.VerletIntegrator(1.0)
>>> context = mm.Context(testsystem.system, integrator)
FATAL: Error inserting nvidia (/lib/modules/2.6.32-358.18.1.el6.x86_64/extra/nvidia.ko): No such device
FATAL: Error inserting nvidia (/lib/modules/2.6.32-358.18.1.el6.x86_64/extra/nvidia.ko): No such device
FATAL: Error inserting nvidia (/lib/modules/2.6.32-358.18.1.el6.x86_64/extra/nvidia.ko): No such device
FATAL: Error inserting nvidia (/lib/modules/2.6.32-358.18.1.el6.x86_64/extra/nvidia.ko): No such device
>>>
```
This doesn't appear to cause program termination.  Is this expected normal behavior?

**Comment by rmcgibbo** [comment]
I think something like this ("No device found") is the expected behavior if you have CUDA installed, but no CUDA-capable GPU.

**Comment by jchodera** [comment]
OK, makes sense.  Is it possible to suppress this text and gracefully fall back to the next device, or is it impossible to do so because it is emitted by the driver?

**Comment by rmcgibbo** [comment]
I tried this on one of our clusters, on the head node w/ no GPU, and I get essentially the same thing, except that the error is printed only once.

**Comment by rmcgibbo** [comment]
Relevant: https://github.com/pandegroup/openmm/issues/257#issuecomment-31696442 may have become outdated with CUDA 7 or something.

**Comment by jchodera** [comment]
Can you clarify? Do you mean the fallback-to-next-fastest-platform may not be working as expected?

**Comment by rmcgibbo** [comment]
Maybe not. I thought that thread had to do with not using a platform if it didn't have an appropriate device.

**Comment by rmcgibbo** [comment]
Will file PR

**Comment by rmcgibbo** [comment]
Actually, nevermind. What is the problem here actually? What platform was actually chosen when you ran the script you posted?

**Comment by jchodera** [comment]
> What is the problem here actually? 

The printing of text like
```
FATAL: Error inserting nvidia (/lib/modules/2.6.32-358.18.1.el6.x86_64/extra/nvidia.ko): No such device
```
instead of gracefully falling back to another platform.  That's why I wondered
> Is it possible to suppress this text and gracefully fall back to the next fastest platform, or is it impossible to do so because it is emitted by the driver?

It ended up with the CPU platform:
```
FATAL: Error inserting nvidia (/lib/modules/2.6.32-358.18.1.el6.x86_64/extra/nvidia.ko): No such device
FATAL: Error inserting nvidia (/lib/modules/2.6.32-358.18.1.el6.x86_64/extra/nvidia.ko): No such device
FATAL: Error inserting nvidia (/lib/modules/2.6.32-358.18.1.el6.x86_64/extra/nvidia.ko): No such device
FATAL: Error inserting nvidia (/lib/modules/2.6.32-358.18.1.el6.x86_64/extra/nvidia.ko): No such device
CPU
```
This was my `test.py` script:
```
import simtk.openmm as mm
from openmmtools import testsystems
testsystem = testsystems.HarmonicOscillator()
integrator = mm.VerletIntegrator(1.0)
context = mm.Context(testsystem.system, integrator)
print context.getPlatform().getName()
```

**Comment by jchodera** [comment]
So it appears to be behaving correctly but a bit inelegantly.  It would be best if we didn't barf all over the user's terminal during the perfectly normal operation of a function unless there was no way to prevent it.

**Comment by rmcgibbo** [comment]
It would be nice if it didn't print, but I'm not sure if it can be prevented. Even this little program prints that 'FATAL ERROR'

```
$ cat test_device.c
#include <stdio.h>
#include <cuda_runtime.h>

int main() {
  int deviceCount;
  struct cudaDeviceProp properties;
  cudaError_t cudaResultCode = cudaGetDeviceCount(&deviceCount);
  if (cudaResultCode != cudaSuccess)
    deviceCount = 0;
  printf("%d GPU CUDA device(s) found\n", deviceCount);

}
rmcgibbo@sh-5-35  ~/projects/openmm/build2 (3.4.2) ‹icc*›
$ gcc test_device.c -I/share/sw/free/cuda/7.0/include -L/share/sw/free/cuda/7.0/lib64 -lcudart; ./a.out
FATAL: Error inserting nvidia (/lib/modules/2.6.32-504.16.2.el6.x86_64/extra/nvidia.ko): No such device
0 GPU CUDA device(s) found
```

**Comment by rmcgibbo** [comment]
Asked on SO: http://stackoverflow.com/questions/31214906/disable-printing-to-stderr-by-nvidia-driver

**Comment by jchodera** [comment]
Hm.  That's a shame.
