### ISSUE TITLE
Strict mode for device id

### ISSUE THREAD

**Issue by mpharrigan** [pandegroup/openmm#1034]
If the given device id isn't legit, openmm will silently select a device of its choosing. Can we add an option to raise an exception instead. 

I've run into this problem running simulations on multi-gpu clusters where I thought I was spreading jobs across gpus, but since I was outside the range of the number of devices, it was all getting assigned to gpu 0.

It's a pretty surprising behaviour from a moral/philosophical standpoint as well.

**Comment by jchodera** [comment]
+1: This would be a useful feature.

For your specific problem, are you able to select the GPU execution mode as part of the batch queue resources request?  Our cluster uses Torque/Moab, which allows us to easily select whether we want to put our NVIDIA GPUs in shared mode, thread-exclusive mode, or process-exclusive modes.  I believe the exclusive modes would also have the effect of terminating your processes should two different threads or processes (depending on the mode) try to use the same GPU device ID.

**Comment by jchodera** [comment]
> It's a pretty surprising behaviour from a moral/philosophical standpoint as well.

I definitely agree that this seems to violate the "principle of least surprise".

**Comment by peastman** [comment]
Sounds like a reasonable feature.
