### ISSUE TITLE
Update omnia conda recipe for OpenMM 6.3?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1043]
Is it time to update the conda recipe for OpenMM 6.3?

**Comment by peastman** [comment]
When it's released.  Not till then.

**Comment by jchodera** [comment]
I'm wondering if we should build a preview / test build or something, just
so we make sure not to release a broken conda package that is installed by
default when users request openmm.

**Comment by swails** [comment]
Doesn't `openmm-dev` serve this purpose?  I'm with @peastman on avoiding building a new package until we're certain it won't change.  It'd be best the conda build to have the same versioning as OpenMM proper, and for the conda build *not* to silently slip a different set of binaries in if any changes are needed b/w the preview beta and official release.

Going from broken -> not broken conda packages is not really problematic IMO, so correcting a "bad" conda build won't trip up many people without them realizing it.

**Comment by jchodera** [comment]
> Doesn't openmm-dev serve this purpose?

`openmm-dev` provides recent `linux` builds of the OpenMM master branch for use in testing new features.  This isn't quite identical to allowing us to test the release candidate recipe on multiple platforms to make sure we haven't screwed anything up.  

I was thinking that since `openmm` is so crucial to everything else in omnia, we might want to be a bit more careful not to release broken packages.  But if the risk is judged to be minimal, you're right that fixing a broken package may be less problematic. It's just that we use `openmm` packages in a bunch of production environments now, so there is some risk in breaking a bunch of things this way.   But I suppose that anything mission-critical should probably use a very specific version of the packages instead to avoid just this issue.

**Comment by peastman** [comment]
If we can do test builds, that would be great.  We should definitely be testing them before releasing them.  But until it's ready to release, anyone who types "conda install openmm" should get 6.2.

**Comment by jchodera** [comment]
This is done: https://github.com/omnia-md/conda-recipes/pull/268
