### ISSUE TITLE
[ENH] Migrate Travis environment to Container infrastructure

### ISSUE THREAD

**Issue by swails** [pandegroup/openmm#1045]
This is a reminder to look into porting the Travis build script to the new Container infrastructure, which will expand the available resources, cut build start times down to seconds, and cut build times roughly in half.

One of the principal challenges here is that `sudo` doesn't work, so you need to work around that.  The `addons` feature doesn't seem to support all of the packages that OpenMM requires (such as Gromacs), and the system Python is used (which means `make PythonInstall` needs to run as sudo).

What I plan to try when I get the time is to replace all of the `apt-get install` packages with `addons` (like what @rmcgibbo did with MDTraj [here](https://github.com/mdtraj/mdtraj/blob/master/.travis.yml#L3-L13)), and then set up the Python environment using conda instead of the system Python.  This will circumvent root privilege requirements for `make PythonInstall` *and* let us also test Python 3 very easily in an environment matrix.

**Comment by peastman** [comment]
I believe this was fixed by #1071, right?

**Comment by rmcgibbo** [comment]
Yes.
