### ISSUE TITLE
Compiler error in FFT

### ISSUE THREAD

**Issue by peastman** [pandegroup/openmm#1046]
I've found a bug we should decide whether to fix in 6.3.  The fix is quite easy, but it would still mean doing new builds, then retesting everything.  And it's a very rare situation with an easy workaround.

Under certain conditions, the CUDA FFT kernel asks for more shared memory than is actually available.  It then fails to compile, and throws an exception with the somewhat cryptic message, CUDA_ERROR_NO_BINARY_FOR_GPU.

This happens when both of the following are true:

1. You're running in double precision mode.  (It doesn't happen in single or mixed precision.)
2. The grid dimension is exactly a power of 7.  So in practice that means 7, 49, or 147.

The workaround is to modify the ewald error tolerance very slightly so the grid size changes and is no longer a power of 7.

**Comment by swails** [comment]
Unless I'm mistaken, powers of 7 are a bit slower than powers of smaller prime factors like 2, 3, and 5, right?

I'm personally +0 on punting until 6.4.  It doesn't silently give wrong answers and it's pretty rare, as you mentioned.

**Comment by peastman** [comment]
I suspect there's not much performance difference overall between grid sizes of 49 and 50.  The FFT will probably be faster, but the larger grid will make other operations (very slightly) slower.

**Comment by rmcgibbo** [comment]
FWIW, my preference would be to cut the 6.3 release now, and schedule this for 6.4.

**Comment by jchodera** [comment]
Campaigning for using the `Milestone` tagging once again!

**Comment by peastman** [comment]
What milestone are you suggesting tagging this with?  If we decide to fix it in 6.3, it will be closed right away.  If we decide to put it off, I'll commit the fix as soon as 6.3 is released.  Either way, this issue should be closed within days.

**Comment by jchodera** [comment]
I'm just suggesting that if we know we want to include something in the next release after 6.3, we should tag it as a 6.4 milestone so nothing gets lost.
