### ISSUE TITLE
Units for CMAPTorsionForce.getMapParameters?

### ISSUE THREAD

**Issue by rmcgibbo** [pandegroup/openmm#1052]
Should the energy return value of CMAPTorsionForce.getMapParameters be annotated with kJ/mol Currently there's no unit (https://github.com/pandegroup/openmm/blob/master/wrappers/python/src/swig_doxygen/swigInputConfig.py#L310)

https://github.com/pandegroup/openmm/blob/master/openmmapi/include/openmm/CMAPTorsionForce.h#L85-L94

**Comment by swails** [comment]
I vote yes.  All other non-custom force objects do to my knowledge (or have been made to recently; e.g., #953)

**Comment by rmcgibbo** [comment]
Kk. I'll file PR. I wasn't sure if it was left out on purpose.

**Comment by rmcgibbo** [comment]
And by file PR, I actually mean add to #1031.

**Comment by peastman** [comment]
Can this be closed?  #1031 was merged a while ago.
