### ISSUE TITLE
OpenMM 6.4 features of interest

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1053]
Now that OpenMM 6.3 is released, we're looking into which features the lab could really use in OpenMM 6.4.  Here's my preliminary list:
* Fast deep copy (#542) - @peastman would need to tackle this
* Faster energy minimizers (#970) - we could play with @rmcgibbo's [Nesterov gradient descent minimizer](https://github.com/rmcgibbo/openmm-cookbook/blob/master/02-nesterov-minimization.ipynb) by putting it into [openmmtools](https://github.com/choderalab/openmmtools), but a GPU version of L-BFGS might be awesome (if challenging)
* `CustomPMEForce` (#933) - I still owe you a theory document on this
* constant-pH simulation (#172 and #494) - we will tackle most of this, but may need the help of @peastman for C++ API extensions to make this efficient
* AmberTools15 forcefields (#503) - @rafwiewiora and I will tackle this
* CHARMM forcefields (#685) - @chayast will tackle this
* Multisite ions for Amber (#1032) - @rafwiewiora will tackle this
* Optimizations for large systems? (#753) - I wonder if there might be things that can be done to speed up large systems
* Better support for HMC and MTS integrators (#951) - The new `CustomIntegrator` extensions will help, but there may still be some optimizations to make HMC and MTS integrators really fast
* Deterministic force and energy computation (necessary for #916)
* Support for small molecules via `ForceField` and `ffxml` route, which needs better mix-and-match support for GB (#1168)

If @peastman agrees these are good things to include in 6.4, it would be great if @peastman could tag them with "enhancement", possibly "6.4 release target", and assign them to respective people.

**Comment by peastman** [comment]
Thanks!  I've also been looking into theory for CustomPMEForce a little bit.  It looks challenging, but might still be doable.

**Comment by peastman** [comment]
By the way, the next release may end up being called 7.0.  That's what Vijay has been talking about, anyway.

**Comment by jchodera** [comment]
No problem with that.  Maybe it makes sense to plan a paper corresponding to each major release milestone?

**Comment by jchodera** [comment]
You've probably already seen this, but the gromacs folks just released [a paper describing gromacs 5](http://www.sciencedirect.com/science/article/pii/S2352711015000059).

**Comment by peastman** [comment]
Is #753 actually an issue?  It just says "benchmark large systems".  Was the performance slower than you thought it should be?  Also, the linked files are no longer available.

**Comment by jchodera** [comment]
> Is #753 actually an issue? It just says "benchmark large systems". Was the performance slower than you thought it should be? Also, the linked files are no longer available.

Yes, it seemed to be much slower than expected for some reason.  Let me bump that thread and see if the files can be re-posted.

**Comment by jchodera** [comment]
Closing this since things still in flight are separate issues now.
