### ISSUE TITLE
"Fixed width overflow detected" in PDBFile.writeFile with keepIds=True

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1072]
We're trying to preserve original residue numberings in models generated by `simtk.openmm.app.Modeller` from constructs that match standard Uniprot numberings, but contain lots of solvent molecules. 

Writing out PDB files after the `Modeller` stage using 
```python2.7
        app.PDBFile.writeFile(fixer.topology, fixer.positions, outfile, keepIds=True)  
```
gives the error
```
Fixed width overflow detected
```
presumably because too many waters are included.

Complete input files here:
https://gist.github.com/jchodera/d4e967c29fb124d76d44

Example invocation (requires `pdbfixer-dev`):
```
python setup_mutations_ensembler.py --source_pdbfile='MTOR_HUMAN_D0-selected.pdb' --output_directory='MTOR_HUMAN_D0-mutations'
```

Is there some way we could have `writeFile` preserve numbering for non-water residues but do *something* to just not die on writing water residues (where we essentially *never* care about numbering being preserved)?

**Comment by jchodera** [comment]
@peastman suggests a long-term solution might be [to support PDBx/mmCIF](https://github.com/pandegroup/pdbfixer/issues/99#issuecomment-127754858):
> As a longer term solution, we should add support for writing PDBx/mmCIF files, since those don't have the restriction. That could be a good feature for OpenMM 7.0.

but it would still be super useful to have a practical short term solution.

**Comment by peastman** [comment]
Here's the output line triggering the error:

```
ATOM  34292  O   HOH 210000      44.203  47.142  82.114  1.00  0.00           O  
```

It's happening because the residue ID has hit 10000, and only four columns are allowed for that value.  If PDBFile is asked to generate its own residue IDs (the default), it takes them mod 10000 so this will never happen.  But if you specify keepIds=True, it doesn't.  That's explicitly specified in the documentation:

```
 - keepIds (bool=False) If True, keep the residue and chain IDs specified in the Topology rather than generating
   new ones.  Warning: It is up to the caller to make sure these are valid IDs that satisfy the requirements of
   the PDB format.  Otherwise, the output file will be invalid.
```

So you could argue the problem is in PDBFixer, and it shouldn't generate residue IDs greater than 9999.  I don't think that's a great solution either though.  Once we add support for PDBx output, larger IDs will be perfectly legitimate.

It's a bit of a hack, but you could have your script fix the IDs before writing the PDB file.

**Comment by jchodera** [comment]
Great idea---thanks!

**Comment by swails** [comment]
> Once we add support for PDBx output,

I can take a crack at that.  I already have that added to ParmEd.

@jchodera -- you *should* be able to use ParmEd to write a PDBx/mmCIF file:

```Python
import parmed as pmd

x = pmd.openmm.from_topology(openmm_topology)

x.write('file.cif', renumber=False)
```

**Comment by peastman** [comment]
How do you generate PDBx files?  Do you use the library from RCSB, or just write it out yourself?  We currently use their library for reading files, but I haven't looked at their API for writing to see whether it's flexible enough.  For example, can it write a series of frames that are generated one at a time by a simulation?

**Comment by swails** [comment]
> How do you generate PDBx files? Do you use the library from RCSB, or just write it out yourself? We currently use their library for reading files, but I haven't looked at their API for writing to see whether it's flexible enough. For example, can it write a series of frames that are generated one at a time by a simulation?

I use the RCSB library -- it's sufficiently flexible to write out a multi-frame CIF file.

You can see where I do the writing [here](https://github.com/ParmEd/ParmEd/blob/master/parmed/formats/pdb.py#L1197-L1389).  I write lots of things, though, including anisotropic B-factors and alternate locations if available.

If you give me a couple days, I'll add a writer to OpenMM as well (or you can handle it if you want).

**Comment by peastman** [comment]
It looks like you're building up a giant data structure in memory with every single frame, then you write all of them to disk at once?  I'm not sure that would work well for a reporter.  First, because the number of frames could be huge and could easily fill up memory.  And second, because if the job gets killed before it's finished you're left with nothing on disk.

**Comment by swails** [comment]
> It looks like you're building up a giant data structure in memory with every single frame, then you write all of them to disk at once? I'm not sure that would work well for a reporter.

Oh, I didn't think about using it as a reporter.  I was just thinking about it in the PDBFixer<->OpenMM workflow.  Yes, the RCSB library is a poor choice for using it as a reporter, for sure.  In that case writing "by hand" is the way to go.  I can use what ParmEd prints as a guide for a writer to OpenMM if you want.

**Comment by peastman** [comment]
That sounds like a good plan.  It might even be possible to use the RCSB library to generate the individual sections of the file, then chain them together ourselves.  (I haven't looked at the API, so I'm not sure whether it can do that or not.)

**Comment by swails** [comment]
> (I haven't looked at the API, so I'm not sure whether it can do that or not.)

I don't think it is set up to do that.

**Comment by jchodera** [comment]
Thanks!

**Comment by jchodera** [comment]
Just for the record, what would the equivalent of
```
 app.PDBFile.writeFile(fixer.topology, fixer.positions, outfile, keepIds=True)  
```
be now with PDBx?

**Comment by peastman** [comment]
Just change PDBFile to PDBxFile.
