### ISSUE TITLE
Add appveyor

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1084]

**Comment by jchodera** [comment]
It looks like https://github.com/pandegroup/openmm/pull/1082 may have accidentally broken win builds. Would be useful to add appveyor to ensure we can prevent this.

@rmcgibbo suggests (from https://github.com/omnia-md/openmm-dev/pull/11):
> I think we should prune down the matrix, maybe not use miniconda (use the preinstalled python on the build machines) and other stuff to make it as fast as possible. Previously, I think it got really annoying because it took so much longer than travis, and nobody paid attention because it just held up the PRs.

**Comment by rmcgibbo** [comment]
Done.
