### ISSUE TITLE
Problem with constraint triangles that are not water

### ISSUE THREAD

**Issue by jlmaccal** [pandegroup/openmm#1099]
I'm in the home stretch of implementing a parser and interaction function for gromacs-format Martini topologies in OpenMM. I can now run many systems with good agreement in energies between GROMACS and OpenMM, but I've run into a snag.

For some amino acids in Martini, like His, the ring contains three constraints that form a triangle. OpenMM detects this as a constraint system it can treat with SETTLE. However, this fails because two of the three distances are not the same, as required by the SETTLE algorithm.

My understanding is that these cases could be correctly treated with CCMA. It looks it shouldn't be too difficult to test if all three distances are different, in which case we would not add the settle constraint, leading to the constraint being handled by CCMA.

@peastman, I can take a stab at this, but I think you could make short work of this---not to mention do it correctly.

**Comment by peastman** [comment]
Can you provide a test case that demonstrates the problem?

**Comment by jlmaccal** [comment]
I will see if I can put something together that is independent of the Martini parser.

The exact error message is:
```
Exception: Two of the three distances constrained with SETTLE must be the same.
```

This happens because the existing code tries to use SETTLE for all cases where there are three isolated constraints in a triangle. But SETTLE is only applicable when two of the three constrained distances are equal.

I doubt this would ever be a problem with atomistic simulations, but Martini uses constraints for the rings in some side chains.

**Comment by jlmaccal** [comment]
I've created a minimal failing test:

https://gist.github.com/jlmaccal/8774f4a0917b973d5854
