### ISSUE TITLE
Energy discrepancies between platforms on large systems

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1108]
We've been working on debugging issues with Folding@home project 10492, a large (277K atom) system with a kinase+FAT domain running in explicit solvent with PME.  These simulations have been triggering lots of Bad State errors, which report on large discrepancies between energies or forces between `Reference` and `OpenCL` platforms.

While we are working toward harvesting the exact configurations that cause these issues, we've used a [variant of the platform energy comparison script found in openmmtools](https://github.com/choderalab/fah-tools/blob/master/openMM_testscript.py) to compare energies among platforms on the initial `system.xml` and `state.xml` files we use for these simulations.  (I'll try to get these posted shortly)

So far, it seems that the difference between the OpenCL single-precision platform and `Reference` is  surprisingly small (~0.4 kcal/mol), but seemingly large enough to trigger Bad State errors somewhere down the road. 

The majority of the error seems to be from the reciprocal-space contribution, but what is surprising is that this error does not diminish when `double` precision is used instead.  I wonder if this might be some indication of the issues that might be triggering Bad States?
```
RUN2 (277543 atoms)
       Reference          double   -856195.726334 kcal/mol         0.000000 kcal/mol       248.287692 kcal/mol/nm         0.000000 kcal/mol/nm
             CPU          single   -856196.162338 kcal/mol        -0.436004 kcal/mol       248.287627 kcal/mol/nm         0.012325 kcal/mol/nm
                                 WARNING: Potential energy error (-0.436004 kcal/mol) exceeds tolerance (0.060000 kcal/mol).  Test failed.
            CUDA          single   -856195.741576 kcal/mol        -0.015242 kcal/mol       248.287650 kcal/mol/nm         0.012029 kcal/mol/nm
            CUDA          double   -856196.097066 kcal/mol        -0.370732 kcal/mol       248.287682 kcal/mol/nm         0.012013 kcal/mol/nm
                                 WARNING: Potential energy error (-0.370732 kcal/mol) exceeds tolerance (0.060000 kcal/mol).  Test failed.
          OpenCL          single   -856195.721081 kcal/mol         0.005253 kcal/mol       248.287652 kcal/mol/nm         0.012029 kcal/mol/nm
          OpenCL          double   -856196.097613 kcal/mol        -0.371279 kcal/mol       248.287682 kcal/mol/nm         0.012013 kcal/mol/nm
                                 WARNING: Potential energy error (-0.371279 kcal/mol) exceeds tolerance (0.060000 kcal/mol).  Test failed.
Breakdown of discrepancies by Force component:
HarmonicBondForce
        platform       precision        potential                     error                 force mag                 rms error
       Reference          double      3755.199248 kcal/mol         0.000000 kcal/mol        63.392196 kcal/mol/nm         0.000000 kcal/mol/nm
             CPU          single      3755.199248 kcal/mol         0.000000 kcal/mol        63.392196 kcal/mol/nm         0.000000 kcal/mol/nm
            CUDA          single      3755.200820 kcal/mol         0.001573 kcal/mol        63.392197 kcal/mol/nm         0.000166 kcal/mol/nm
            CUDA          double      3755.199828 kcal/mol         0.000580 kcal/mol        63.392196 kcal/mol/nm         0.000079 kcal/mol/nm
          OpenCL          single      3755.200820 kcal/mol         0.001573 kcal/mol        63.392197 kcal/mol/nm         0.000166 kcal/mol/nm
          OpenCL          double      3755.199828 kcal/mol         0.000580 kcal/mol        63.392196 kcal/mol/nm         0.000079 kcal/mol/nm
HarmonicAngleForce
        platform       precision        potential                     error                 force mag                 rms error
       Reference          double     10244.931781 kcal/mol         0.000000 kcal/mol        51.559971 kcal/mol/nm         0.000000 kcal/mol/nm
             CPU          single     10244.931781 kcal/mol         0.000000 kcal/mol        51.559971 kcal/mol/nm         0.000000 kcal/mol/nm
            CUDA          single     10244.933432 kcal/mol         0.001651 kcal/mol        51.559975 kcal/mol/nm         0.000051 kcal/mol/nm
            CUDA          double     10244.933173 kcal/mol         0.001392 kcal/mol        51.559974 kcal/mol/nm         0.000022 kcal/mol/nm
          OpenCL          single     10244.933432 kcal/mol         0.001651 kcal/mol        51.559975 kcal/mol/nm         0.000051 kcal/mol/nm
          OpenCL          double     10244.933173 kcal/mol         0.001392 kcal/mol        51.559974 kcal/mol/nm         0.000022 kcal/mol/nm
PeriodicTorsionForce
        platform       precision        potential                     error                 force mag                 rms error
       Reference          double     13825.283049 kcal/mol         0.000000 kcal/mol        17.508402 kcal/mol/nm         0.000000 kcal/mol/nm
             CPU          single     13825.283049 kcal/mol         0.000000 kcal/mol        17.508402 kcal/mol/nm         0.000000 kcal/mol/nm
            CUDA          single     13825.282393 kcal/mol        -0.000655 kcal/mol        17.508398 kcal/mol/nm         0.000023 kcal/mol/nm
            CUDA          double     13825.283076 kcal/mol         0.000027 kcal/mol        17.508401 kcal/mol/nm         0.000005 kcal/mol/nm
          OpenCL          single     13825.285339 kcal/mol         0.002291 kcal/mol        17.508400 kcal/mol/nm         0.000022 kcal/mol/nm
          OpenCL          double     13825.282561 kcal/mol        -0.000487 kcal/mol        17.508399 kcal/mol/nm         0.000009 kcal/mol/nm
NonbondedForce (direct)
        platform       precision        potential                     error                 force mag                 rms error
       Reference          double   3651288.711688 kcal/mol         0.000000 kcal/mol       235.481438 kcal/mol/nm         0.000000 kcal/mol/nm
             CPU          single   3651288.624873 kcal/mol        -0.086816 kcal/mol       235.481378 kcal/mol/nm         0.000383 kcal/mol/nm
            CUDA          single   3651289.121167 kcal/mol         0.409479 kcal/mol       235.481407 kcal/mol/nm         0.000444 kcal/mol/nm
            CUDA          double   3651288.769640 kcal/mol         0.057951 kcal/mol       235.481441 kcal/mol/nm         0.000023 kcal/mol/nm
          OpenCL          single   3651289.141455 kcal/mol         0.429766 kcal/mol       235.481409 kcal/mol/nm         0.000444 kcal/mol/nm
          OpenCL          double   3651288.769640 kcal/mol         0.057951 kcal/mol       235.481441 kcal/mol/nm         0.000023 kcal/mol/nm
NonbondedForce (reciprocal)
        platform       precision        potential                     error                 force mag                 rms error
       Reference          double  -4535309.852100 kcal/mol         0.000000 kcal/mol        10.247086 kcal/mol/nm         0.000000 kcal/mol/nm
             CPU          single  -4535310.201288 kcal/mol        -0.349188 kcal/mol        10.247017 kcal/mol/nm         0.012318 kcal/mol/nm
            CUDA          single  -4535310.278834 kcal/mol        -0.426734 kcal/mol        10.247016 kcal/mol/nm         0.012019 kcal/mol/nm
            CUDA          double  -4535310.282783 kcal/mol        -0.430683 kcal/mol        10.247003 kcal/mol/nm         0.012013 kcal/mol/nm
          OpenCL          single  -4535310.281318 kcal/mol        -0.429218 kcal/mol        10.247008 kcal/mol/nm         0.012019 kcal/mol/nm
          OpenCL          double  -4535310.282816 kcal/mol        -0.430716 kcal/mol        10.247003 kcal/mol/nm         0.012013 kcal/mol/nm
CMMotionRemover
        platform       precision        potential                     error                 force mag                 rms error
       Reference          double         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol/nm         0.000000 kcal/mol/nm
             CPU          single         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol/nm         0.000000 kcal/mol/nm
            CUDA          single         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol/nm         0.000000 kcal/mol/nm
            CUDA          double         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol/nm         0.000000 kcal/mol/nm
          OpenCL          single         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol/nm         0.000000 kcal/mol/nm
          OpenCL          double         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol/nm         0.000000 kcal/mol/nm
MonteCarloBarostat
        platform       precision        potential                     error                 force mag                 rms error
       Reference          double         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol/nm         0.000000 kcal/mol/nm
             CPU          single         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol/nm         0.000000 kcal/mol/nm
            CUDA          single         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol/nm         0.000000 kcal/mol/nm
            CUDA          double         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol/nm         0.000000 kcal/mol/nm
          OpenCL          single         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol/nm         0.000000 kcal/mol/nm
          OpenCL          double         0.000000 kcal/mol         0.000000 kcal/mol         0.000000 kcal/mol/nm         0.000000 kcal/mol/nm
```

**Comment by peastman** [comment]
What do you have the Ewald error tolerance set to?  How do those results change if you make it smaller?

One thing to keep in mind is that different platforms might be using different grid sizes, which will cause the results to be slightly different (but still accurate to within the requested tolerance).  CUDA and OpenCL support radix 2, 3, 5, and 7 FFTs.  CPU uses FFTW, which allows you to also have a single factor of 11 or 13, but requires that the Z dimension must be even.  And Reference uses fftpack, which supports arbitrary grid dimensions.

**Comment by jchodera** [comment]
> What do you have the Ewald error tolerance set to? 

Everything is default OpenMM 6.2 for now.

> How do those results change if you make it smaller?

Great question.  I'll check!

> One thing to keep in mind is that different platforms might be using different grid sizes, which will cause the results to be slightly different (but still accurate to within the requested tolerance). CUDA and OpenCL support radix 2, 3, 5, and 7 FFTs. CPU uses FFTW, which allows you to also have a single factor of 11 or 13, but requires that the Z dimension must be even. And Reference uses fftpack, which supports arbitrary grid dimensions.

Is there some way to force the `Reference` platform to use whatever the `OpenCL` platform was using for our checks?

**Comment by peastman** [comment]
You can use setPMEParameters() to tell it what size to use.

**Comment by jchodera** [comment]
Having a bit of trouble here.  The PME parameters were not set in these systems
```
[Quantity(value=0.0, unit=/nanometer), 0, 0, 0]
```
and I can't figure out how to get the active PME parameters that `Context` decides to use in this case.  Is there an API call for that?

Alternatively, how should I choose a sensible set of PME parameters to use for multiple platforms?  I'm used to selecting the cutoff, error tolerance at the cutoff, and grid spacing, rather than `alpha, nx, ny, nz`.  I think you had a PME tuning script you used at some point?

**Comment by jchodera** [comment]
Found the PME tuning script:
https://simtk.org/svn/pyopenmm/trunk/simtk/pyopenmm/extras/optimizepme.py

**Comment by jchodera** [comment]
This is very odd---the script hangs at context creation in this method:
```
def _createContext(system, integrator, positions, platform, properties):
    integrator = mm.XmlSerializer.deserialize(mm.XmlSerializer.serialize(integrator))
    context = mm.Context(system, integrator, platform, properties)
    context.setPositions(positions)
    return context
```

**Comment by jchodera** [comment]
For CUDA context creation, I run out of memory (!!!) on a 12GB GTX-TITAN-X:
```
Tuning PME parameters for platform 'CUDA' precision model 'single'...

Selecting a length for the test simulations... 
Creating Context...
copying integrator...
Creating context...
Traceback (most recent call last):
  File "openMM_testscript.py", line 568, in <module>
    main()
  File "openMM_testscript.py", line 416, in main
    optimizePME(system, integrator, positions, platform, properties, minCutoff, maxCutoff)
  File "/cbio/jclab/home/chodera/fah-tools/optimizepme.py", line 138, in optimizePME
    context = _createContext(system, integrator, positions, platform, properties)
  File "/cbio/jclab/home/chodera/fah-tools/optimizepme.py", line 203, in _createContext
    context = mm.Context(system, integrator, platform, properties)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 6083, in __init__
    this = _openmm.new_Context(*args)
Exception: Error creating array pmeAtomRange: CUDA_ERROR_OUT_OF_MEMORY (2)
```

**Comment by jchodera** [comment]
Here are the [`{system,state0,integrator}.xml` files](https://drive.google.com/a/choderalab.org/folderview?id=0B075He2poqy1fjRLa1ZQZE16RVlqa3hBd2REdHNMQ1BrWGQ5SFdBSjM1NHp0Y1ZZZ2FSSlE&usp=sharing).

**Comment by jchodera** [comment]
The computation of `alpha, nx, ny, nz` is sort of documented [here](http://docs.openmm.org/6.3.0/userguide/theory.html?highlight=pme#coulomb-interaction-with-particle-mesh-ewald), with the caveat that some platforms may choose larger values for the number of grid parameters.

To summarize this long thread:
* Some of the discrepancies between `Reference` and `OpenCL` causing Bad State errors on core 0x21 projects might plausibly be due to different choices of PME parameters
* Selection of PME parameters is not straightforward because no simple tool is provided to go from what we normally specify (`cutoff`, `tolerance`) to the actual parameters we can set to eliminate the differences between platforms (`alpha, nx, ny, nz`)
* The [`optimizepme.py`](https://simtk.org/svn/pyopenmm/trunk/simtk/pyopenmm/extras/optimizepme.py) script, which can automatically select these parameters, hangs (OpenCL) or gives an out of memory error (CUDA) even on GPUs with 12GB memory
* It would be useful to have a `NonbondedForce.getPMEParmametersInContext(context)` method to retrieve the *actual* PME parameters in use, since this also seems relevant for general scientific reproducibility in other codes.

**Comment by peastman** [comment]
What range of cutoffs did you tell the optimize script to search?

**Comment by jchodera** [comment]
0.8 to 1.2 nm

**Comment by peastman** [comment]
That seems reasonable.  What are the box dimensions for this system?

Regarding an API for getting the box dimensions: `NonbondedForceImpl::calcPMEParameters()` computes the ideal values (using the formulas given in the manual).  You can then call `OpenCLFFT3D::findLegalDimension()` to find what size each dimension is being rounded up to.  That doesn't get exposed to Python, though.

**Comment by jchodera** [comment]
From the `state0.xml`:
```
        <PeriodicBoxVectors>
                <A x="14.101149886993863" y="0" z="0"/>
                <B x="0" y="14.101149886993863" z="0"/>
                <C x="0" y="0" z="14.101149886993863"/>
        </PeriodicBoxVectors>
```

**Comment by jchodera** [comment]
> Regarding an API for getting the box dimensions: NonbondedForceImpl::calcPMEParameters() computes the ideal values (using the formulas given in the manual). You can then call OpenCLFFT3D::findLegalDimension() to find what size each dimension is being rounded up to. That doesn't get exposed to Python, though.

Then it's not useful to us.  :)

I do think a way to query what PME parameters are in use and get access to the scheme that is used to compute PME parameters from `cutoff` and `tolerance` would be super useful.  Will add a feature request in a separate issue.

**Comment by swails** [comment]
Would it make sense to add these introspective functions to `Context`, since PME parameters are assigned both in `AmoebaMultipoleForce` and `NonbondedForce` (and potentially `CustomEwaldForce` sometime in the future)?

**Comment by jchodera** [comment]
> Would it make sense to add these introspective functions to Context, since PME parameters are assigned both in AmoebaMultipoleForce and NonbondedForce (and potentially CustomEwaldForce sometime in the future)?

Good point.  Move discussion to the feature request issue #1111?

**Comment by jchodera** [comment]
Regarding `optimizepme.py`: Do you mind if we pull this into [`openmmtools`](http://github.com/choderalab/openmmtools)?  It would make it easier for us to modify and extend that way, as well as get access to it via `conda`.

**Comment by peastman** [comment]
Possibly the Context isn't getting garbage collected correctly.  In `_timeWithCutoffs()`, try adding "del context" immediately after the call to `_timeIntegrator()`.

**Comment by jchodera** [comment]
> Possibly the Context isn't getting garbage collected correctly. In _timeWithCutoffs(), try adding "del context" immediately after the call to _timeIntegrator().

That may also be an issue, but this isn't even getting through one `Context` creation.

**Comment by jchodera** [comment]
It's hard to refer to specific line numbers since this isn't on GitHub, but the script is either stalling (OpenCL) or throwing an Exception (CUDA) here:
```
 print                                                                                                                                                                                                                                                                                                                                                                 
    print 'Selecting a length for the test simulations... '                                                                                                                                                                                                                                                                                                               
    nonbonded.setCutoffDistance(math.sqrt(minCutoff*maxCutoff))                                                                                                                                                                                                                                                                                                           
    properties[cpuPmeProperty] = 'false'                                                                                                                                                                                                                                                                                                                                  
    print "Creating Context..."                                                                                                                                                                                                                                                                                                                                           
    context = _createContext(system, integrator, positions, platform, properties) 
```

**Comment by jchodera** [comment]
I'm going to pull this into `openmmtools` to make this easier.  Let me know if that's not OK.

**Comment by peastman** [comment]
Something strange is going on then.  You're using the default value for Ewald error tolerance (5e-4), right?  With a cutoff of 0.8 nm, the ideal size for each dimension is 142.  That will get rounded up to 144, which means slightly under 3 million grid points.  Total storage for the grid should be well under 100 MB.

> I'm going to pull this into openmmtools to make this easier. Let me know if that's not OK.

Please do not.  I want there to be one and only one location for this script.  Otherwise, we'll end up with lots of copies that all get out of sync with each other.  We could consider moving the one official copy to a different location, but that's something that needs to be discussed first.

**Comment by jchodera** [comment]
> Something strange is going on then. You're using the default value for Ewald error tolerance (5e-4), right? 

We didn't specify an Ewald error tolerance in the creation of these systems, so it should be default.  The code can be seen here:
https://github.com/choderalab/ensembler/blob/master/ensembler/refinement.py#L888-L900

> With a cutoff of 0.8 nm, the ideal size for each dimension is 142. That will get rounded up to 144, which means slightly under 3 million grid points. Total storage for the grid should be well under 100 MB.

These systems run fine normally, and on the `openmm` core on Folding@home (though they trigger lots of Bad State errors).  For some reason, running them through `optimizepme` causes the hangs/crashes I describe.

> Please do not. I want there to be one and only one location for this script. Otherwise, we'll end up with lots of copies that all get out of sync with each other. We could consider moving the one official copy to a different location, but that's something that needs to be discussed first.

Should we discuss that in a separate issue?  In this repository or elsewhere?

Mainly, I am concerned that
* it can't be automatically installed via `conda`
* there are currently no automated tests
* there isn't an easy way for people to contribute improvements
* we can't even easily discuss changes on an issue tracker

Pulling this into `openmmtools` (or some other GitHub repo with our current testing and `omnia` packaging framework set up) would solve that.

**Comment by rmcgibbo** [comment]
+1 for pulling that script into pandegroup/openmm somehow. We haven't currently been installing scripts from the python app layer, but we do have `python -m simtk.testInstallation`, which is kind of like a script, and we could have `python -m simtk.tunePME` or similar.

**Comment by jchodera** [comment]
+1 also for getting it into `pandegroup/openmm`.  We want to preserve programmatic access, however, like `simtk.openmm.app.optimizepme` or something.

**Comment by rmcgibbo** [comment]
I got the following with your files on my GTX 660 w/ CUDA

```
Selecting a length for the test simulations... 
172 steps

Running simulations with standard PME

cutoff=0.8, time=10.216
cutoff=0.807, time=10.3079
cutoff=0.836, time=10.2253
Traceback (most recent call last):
  File "optimizepme.py", line 234, in <module>
    optimizePME(system, integrator, state.getPositions(), platform, properties, 0.8*unit.nanometers, 1.2*unit.nanometers)
  File "optimizepme.py", line 152, in optimizePME
    gpuTimes = _timeWithCutoffs(system, integrator, positions, platform, properties, nonbonded, gpuCutoffs, steps)
  File "optimizepme.py", line 218, in _timeWithCutoffs
    time = _timeIntegrator(context, steps)
  File "optimizepme.py", line 207, in _timeIntegrator
    context.getIntegrator().step(steps)
  File "/home/rmcgibbo/miniconda/envs/3.4.2/lib/python3.4/site-packages/simtk/openmm/openmm.py", line 14698, in step
    return _openmm.LangevinIntegrator_step(self, *args)
Exception: Error invoking kernel: CUDA error (700)
```

**Comment by rmcgibbo** [comment]
It's running fine with OpenCL now. Will post results shortly.

**Comment by rmcgibbo** [comment]
John's files with OpenCL on my GTX 660 (Ubuntu 15.04)
```
Running simulations with standard PME

cutoff=0.8, time=10.861
cutoff=0.807, time=10.8644
cutoff=0.836, time=10.6349
cutoff=0.882, time=11.4802
cutoff=0.896, time=10.1428
cutoff=0.903, time=10.1611
cutoff=0.941, time=10.896
cutoff=1.008, time=10.1919
cutoff=1.046, time=10.0371
cutoff=1.076, time=10.0456
cutoff=1.129, time=10.7012
cutoff=1.152, time=10.4002
cutoff=1.176, time=10.5393

Running simulations with CPU based PME

cutoff=0.8, time=9.59271
cutoff=0.807, time=9.63699
cutoff=0.836, time=9.4692
cutoff=0.855, time=9.5756
cutoff=0.869, time=9.67596
cutoff=0.882, time=9.71135

Confirming results for best configurations

Cutoff=0.836, OpenCLUseCpuPme=true
Times: 9.4692, 9.43661, 9.52738
Median time: 9.4692

Cutoff=0.855, OpenCLUseCpuPme=true
Times: 9.5756, 9.62686, 9.64876
Median time: 9.62686

Cutoff=0.8, OpenCLUseCpuPme=true
Times: 9.59271, 9.6766, 9.73108
Median time: 9.6766

Cutoff=0.807, OpenCLUseCpuPme=true
Times: 9.63699, 9.61087, 9.63283
Median time: 9.63283

Cutoff=0.869, OpenCLUseCpuPme=true
Times: 9.67596, 9.6521, 9.71374
Median time: 9.67596

Best configuration:

Cutoff=0.836 nm, OpenCLUseCpuPme=true
```

**Comment by jchodera** [comment]
Whoa. Which `openmm` are you using for this?

**Comment by rmcgibbo** [comment]
6.3 release for py34

**Comment by jchodera** [comment]
I just tried a fresh miniconda3 install on our `linux` cluster. Did you have to convert all the `print` statements in `optimizepme.py` for py34?

**Comment by rmcgibbo** [comment]
I ran 2to3 on it, and then added the following bit at the end

```
if __name__ == '__main__':
    import gzip
    system = mm.XmlSerializer.deserialize(gzip.open('system.xml.gz').read().decode('utf-8'))
    integrator = mm.XmlSerializer.deserialize(gzip.open('integrator.xml.gz').read().decode('utf-8'))
    state = mm.XmlSerializer.deserialize(gzip.open('state0.xml.gz').read().decode('utf-8'))
    platform = mm.Platform.getPlatformByName('OpenCL')
    properties = {}
    optimizePME(system, integrator, state.getPositions(), platform, properties, 0.8*unit.nanometers, 1.2*unit.nanometers)
```

**Comment by jchodera** [comment]
Ah!  That works fine for me.  Somehow, calling `optimizePME()` from our other `openMM_testscript.py` script didn't work, but this works fine.  Will try to figure out why.

**Comment by peastman** [comment]
Just making a wild guess: perhaps you specified the minimum cutoff as 0.8*angstroms rather than 0.8*nanometers?  That would lead to a huge grid.

**Comment by jchodera** [comment]
Right you are, sir!  I did 0.8A to 1.2A, not 0.8nm to 1.2nm.  Definitely not my finest work.

**Comment by jchodera** [comment]
Also, I am just realizing that `optimizePME` does not provide `alpha` and `nx,ny,nz` values, so we still need a way to guess and set these.

**Comment by jchodera** [comment]
After looking through the code, it looks like making the actual parameters used accessible via the API will be a decently big change, so I'll leave that to @peastman.  For expediency, I'll just hack in some print statements so we can fix the `alpha, nx, ny, nz` parameters and see if this eliminates the Bad States on FAH.

Just to check that I'm looking in the right place, I want to dump out these parameters, yes?
https://github.com/pandegroup/openmm/blob/master/platforms/opencl/src/OpenCLKernels.cpp#L1614-L1617

**Comment by peastman** [comment]
Correct.  Here is how they're computed in `NonbondedForceImpl::calcPMEParameters()`:

```C++
        alpha = (1.0/force.getCutoffDistance())*std::sqrt(-log(2.0*tol));
        xsize = (int) ceil(2*alpha*boxVectors[0][0]/(3*pow(tol, 0.2)));
        ysize = (int) ceil(2*alpha*boxVectors[1][1]/(3*pow(tol, 0.2)));
        zsize = (int) ceil(2*alpha*boxVectors[2][2]/(3*pow(tol, 0.2)));
```

And here is how `OpenCLFFT3D::findLegalDimension()` decides what to round them up to:

```C++
    while (true) {
        // Attempt to factor the current value.

        int unfactored = minimum;
        for (int factor = 2; factor < 8; factor++) {
            while (unfactored > 1 && unfactored%factor == 0)
                unfactored /= factor;
        }
        if (unfactored == 1)
            return minimum;
        minimum++;
    }
```

**Comment by jchodera** [comment]
@peastman: Thanks so much for this!  I ended up just implementing this logic in Python and using it to set the PME parameters.

Your hypothesis was borne out: Fixing the PME parameters means that the discrepancies with the Reference platform now behave as expected, becoming much smaller when double precision is used:
```
        platform       precision        potential                     error                 force mag                 rms error
RUN0 (277543 atoms)
       Reference          double   -855946.961148 kcal/mol         0.000000 kcal/mol       247.645899 kcal/mol/nm         0.000000 kcal/mol/nm
             CPU          single   -855947.034064 kcal/mol        -0.072916 kcal/mol       247.645849 kcal/mol/nm         0.000609 kcal/mol/nm
                                 WARNING: Potential energy error (-0.072916 kcal/mol) exceeds tolerance (0.060000 kcal/mol).  Test failed.
            CUDA          single   -855946.484216 kcal/mol         0.476932 kcal/mol       247.645881 kcal/mol/nm         0.000633 kcal/mol/nm
                                 WARNING: Potential energy error (0.476932 kcal/mol) exceeds tolerance (0.060000 kcal/mol).  Test failed.
            CUDA          double   -855946.901721 kcal/mol         0.059426 kcal/mol       247.645903 kcal/mol/nm         0.000081 kcal/mol/nm
          OpenCL          single   -855946.467142 kcal/mol         0.494006 kcal/mol       247.645883 kcal/mol/nm         0.000631 kcal/mol/nm
                                 WARNING: Potential energy error (0.494006 kcal/mol) exceeds tolerance (0.060000 kcal/mol).  Test failed.
          OpenCL          double   -855946.902273 kcal/mol         0.058874 kcal/mol       247.645902 kcal/mol/nm         0.000081 kcal/mol/nm
Breakdown of discrepancies by Force component:
...
NonbondedForce (direct)
        platform       precision        potential                     error                 force mag                 rms error
       Reference          double   3651715.454260 kcal/mol         0.000000 kcal/mol       234.841947 kcal/mol/nm         0.000000 kcal/mol/nm
             CPU          single   3651715.382051 kcal/mol        -0.072209 kcal/mol       234.841895 kcal/mol/nm         0.000454 kcal/mol/nm
            CUDA          single   3651715.929883 kcal/mol         0.475623 kcal/mol       234.841928 kcal/mol/nm         0.000461 kcal/mol/nm
            CUDA          double   3651715.511567 kcal/mol         0.057306 kcal/mol       234.841950 kcal/mol/nm         0.000023 kcal/mol/nm
          OpenCL          single   3651715.946674 kcal/mol         0.492413 kcal/mol       234.841930 kcal/mol/nm         0.000461 kcal/mol/nm
          OpenCL          double   3651715.511567 kcal/mol         0.057306 kcal/mol       234.841950 kcal/mol/nm         0.000023 kcal/mol/nm
NonbondedForce (reciprocal)
        platform       precision        potential                     error                 force mag                 rms error
       Reference          double  -4535329.742568 kcal/mol         0.000000 kcal/mol        10.182856 kcal/mol/nm         0.000000 kcal/mol/nm
             CPU          single  -4535329.743275 kcal/mol        -0.000707 kcal/mol        10.182855 kcal/mol/nm         0.000405 kcal/mol/nm
            CUDA          single  -4535329.742709 kcal/mol        -0.000141 kcal/mol        10.182857 kcal/mol/nm         0.000409 kcal/mol/nm
            CUDA          double  -4535329.742464 kcal/mol         0.000103 kcal/mol        10.182857 kcal/mol/nm         0.000009 kcal/mol/nm
          OpenCL          single  -4535329.744844 kcal/mol        -0.002276 kcal/mol        10.182851 kcal/mol/nm         0.000407 kcal/mol/nm
          OpenCL          double  -4535329.742498 kcal/mol         0.000070 kcal/mol        10.182857 kcal/mol/nm         0.000009 kcal/mol/nm
```
The discrepancy between `Reference` and `OpenCL` is still potentially problematic for `single` but greatly reduced for `double`, and the majority of this comes from the direct-space error.

I'll now check whether explicitly setting the PME parameters `alpha`, `nx`, `ny`, `nz` for Folding@home simulations reduces the Bad State errors we've been seeing, but it does suggest we should probably be doing this anyway.

**Comment by peastman** [comment]
You can also look at this another way: the forces calculated by different platforms aren't even *supposed* to agree to higher precision than the Ewald error tolerance.  They might just happen to, but it's not guaranteed.  If the test is expecting them to, that's arguably a bug in the test.

Of course, there are specific reasons they disagree, and we can try to create a test that works around those reasons.  But they could easily change again in the future, such as if we change which grid sizes are supported.  And keep in mind that the supported grid sizes for OpenCL are different from those for CPU.

**Comment by jchodera** [comment]
Excellent point about supported grid sizes.  We can definitely restructure the tests (both for the `openmm-core` and the one in `openmmtools`) to test something that *should* agree.  For example, we could:
* compute the energy with `platform`
* extract all parameters that `platform` has selected, and use these to initialize the `Reference` platform
* compute energy with `Reference`
* compare energies

This will require we have a Python way to programmatically extract the parameters in use by `platform` (feature request #1111).

Simply degrading the tolerance of energy comparisons may "fix" the `openmm-core` tests, but it would be less desirable in the `openmmtools` tests which are intended to help us check that approximations made in various platform implementations are not causing problematic levels of error on real-world problems.

**Comment by rmcgibbo** [comment]
Changing how the openmm core tests the platform against reference doesn't require any additions to the python wrappers.

**Comment by swails** [comment]
I think he was referring to how the PME parameters are extracted from the Context.  The suggested route that @peastman said is only exposed in the C++ layer.

Currently, if you let each platform select its own PME parameters, there's no way to figure out what those are in order to initialize another platform with the same values.

**Comment by rmcgibbo** [comment]
The core is written in C++...

**Comment by swails** [comment]
oh oh, FAH thing.  Got it.  nvm then.

**Comment by jchodera** [comment]
> Changing how the openmm core tests the platform against reference doesn't require any additions to the python wrappers.

Sorry, yes, you're right, but we still need to determine what PME parameters the OpenCL platform is using.  In the current special case of the OpenCL platform core, we can hack in the code used to compute the PME parameters for the OpenCL platform.  But when we support CUDA *and* OpenCL in the future, it would be much simpler and more general to be able to retrieve the PME parameters active in the current `Context` via the C++ API.  If we do that, it would also be useful to have them accessible via the Python API.

**Comment by peastman** [comment]
And more generally, it would be good not to have to duplicate the logic.  That way if it changes in the future, the core won't need updating.

**Comment by peastman** [comment]
Can we close this?  #1120 added the API discussed above.  Or is there anything else in this issue that's still open?

**Comment by jchodera** [comment]
Thanks!
