### ISSUE TITLE
Build without Doxygen

### ISSUE THREAD

**Issue by jcoffland** [pandegroup/openmm#1114]
It would be nice if OpenMM could be built with out Doxygen.  See #1044.  I tried setting both ``OPENMM_BUILD_PYTHON_WRAPPERS=OFF`` and ``OPENMM_GENERATE_API_DOCS=OFF`` but it still requires doxygen.  I get this error:

```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindDoxygen.cmake:85 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  wrappers/CMakeLists.txt:1 (find_package)
```

Note that I'm using FoldingAtHome/openmm core21 branch.

**Comment by rmcgibbo** [comment]
You have to turn off the C and FORTRAN wrappers too.

**Comment by rmcgibbo** [comment]
If you also set OPENMM_BUILD_C_AND_FORTRAN_WRAPPERS=OFF, you can build without doxygen.
