### ISSUE TITLE
Enable CI testing of OpenCL/CUDA Platforms

### ISSUE THREAD

**Issue by rmcgibbo** [pandegroup/openmm#1117]
Travis and Appveyor are both useful, but neither test the OpenCL or CUDA platforms. It would be quite useful to have build machines testing these platforms (e.g #1116 and related).

@jchodera, you have all of that jenkins infrastructure set up. Would it be possible to add tests that run against PRs and show up the Web UI next to the Appveyor and Travis results?

**Comment by rmcgibbo** [comment]
In supplement, it might be possible to get OpenCL working on Travis, but based on https://github.com/boostorg/compute, https://github.com/boostorg/compute/pull/483, https://github.com/travis-ci/apt-package-whitelist/issues/383, I'm not sure if it's possible to run OpenCL on the new travis infrastructure or not.

**Comment by jchodera** [comment]
> @jchodera, you have all of that jenkins infrastructure set up. Would it be possible to add tests that run against PRs and show up the Web UI next to the Appveyor and Travis results?

Yep, we can enable this.  I just hadn't done so up to now.

What kind of tests do you want run?  All of them?

And would we be OK with having Jenkins post to the PR thread?  

Documentation for the [Jenkins GitHub Pull Request Builder is here](https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin).

**Comment by rmcgibbo** [comment]
1. I think it can interact with github in the same way that Travis and Appveyor do, with the check marks and such. e.g. scroll down on https://github.com/jenkinsci/ghprb-plugin/pull/159.
2. Yes, all of the tests.
3. There might be some security issues, but I think you can whitelist certain trusted users, which covers like 99%
4. If you make the jenkins config simple execute a file called like ".jenkins.sh" in the main repo directory, then we can configure it through the same route that we configure appveyor.yml and travis.yml.

**Comment by rmcgibbo** [comment]
I would say we should start with a linux build. If it works smoothly, we could add an OSX as a later step.

**Comment by peastman** [comment]
And Windows. :/

**Comment by rmcgibbo** [comment]
But let's start with something easy.

**Comment by rmcgibbo** [comment]
Looks like MSFT has opensourced an Azure slave jenkins plugin, so it might actually be straightforward to run windows build on slave running on their cloud. https://github.com/jenkinsci/azure-slave-plugin

**Comment by rmcgibbo** [comment]
@jchodera, if you're down with giving me a privilidged account on your jenkins server, I could configure this.

**Comment by jchodera** [comment]
> @jchodera, if you're down with giving me a privilidged account on your jenkins server, I could configure this.
> 

I wish we could, but they use our MSK accounts for this, so we would need to go through the arduous process of getting you a vendor VPN account (if that even is part of the same account domain).

Maybe it would be possible to coordinate spending a few min on chat with me or @pgrinaway to make sure we are configuring things appropriately?

I think there IS a way to use a YAML plugin to get Travis-like behavior.
>

**Comment by rmcgibbo** [comment]
Okay, not worth it then. We don't really need the whole yaml. Mostly just the "execute shell script" part. I don't actually know how to configure it, but would just test and iterate.

**Comment by rmcgibbo** [comment]
But it should be easy to set up the linux/osx builds using the same executors you already have.

**Comment by rmcgibbo** [comment]
I got Jenkins slaves with Windows running on the Azure cloud using the Jenkins Azure plugin. Essentially, you configure a machine with the stuff you want, and then when builds are triggered, they run on these VMs. The VM provisioning takes a while (~5-10 minutes), so it's not discarded after each build. Instead, the VM sticks around as a worker, running any builds that get triggered. Once it's been left idle for ~1hr, it's deprovisioned. I also tried doing this with EC2, but I couldn't get it to work. Surprisingly, Azure was easier.

It's not quite as convenient as Travis/Appveyor, but you do have full control over the build machines (CPU OpenCL, although no GPUs, etc).

**Comment by jchodera** [comment]
Excellent!  What do I need to do to configure this?  Can you send
screenshots of your plugin config?

**Comment by rmcgibbo** [comment]
Currently I have a jenkins master running on a small VM inside Azure. I just sent you the URL. The other moving part is the Azure subscription, which is currently my free trial. You could either make a new one, or I might be able to add you as a co-administrator or something. But long-term, I should not be paying...

**Comment by rmcgibbo** [comment]
Also, I wrote down the basic steps for configuring a Windows build machine (getting the compilers and stuff): https://gist.github.com/rmcgibbo/6cbecb2d9a0ae2cb9f95

**Comment by jchodera** [comment]
Thanks again for setting this up!  I haven't had time to tackle this yet, but will be able to try this right after MolKin.  

It does look like there is a way to migrate VMs inside Azure, but it looks like a pain:
https://azure.microsoft.com/en-us/blog/migrate-azure-virtual-machines-between-storage-accounts/

**Comment by rmcgibbo** [comment]
Done.
