### ISSUE TITLE
CUDA 7.5

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1126]
CUDA 7.5 release is out:
http://developer.download.nvidia.com/compute/cuda/7.5/Prod/docs/sidebar/CUDA_Toolkit_Release_Notes.pdf

**Comment by peastman** [comment]
All test cases now pass under CUDA 7.5.  Let's plan that OpenMM 7.0 will be built against CUDA 7.5.

Can I close this issue, or is there anything else we should keep it open for?

**Comment by jchodera** [comment]
Thanks!
