### ISSUE TITLE
Inconsistency in AmoebaAngleForce.addAngle

### ISSUE THREAD

**Issue by swails** [pandegroup/openmm#1136]
I found this rather troublesome behavior in the course of working on #1076.

The docstring for `AmoebaAngleForce.addAngle` says this:

```
addAngle(AmoebaAngleForce self, int particle1, int particle2, int particle3, double length, double quadraticK) -> int

Add an angle term to the force field.

Parameters
particle1	the index of the first particle connected by the angle
particle2	the index of the second particle connected by the angle
particle3	the index of the third particle connected by the angle
length	the angle measured in degrees
quadratic	k the quadratic force constant for the angle, measured in kJ/mol/radian^2
```

So the angle needs to be specified in degrees (weird -- no other angle gets passed in degrees...).  So let's do that:

```Python
In [1]: from simtk.openmm import *

In [2]: from simtk.unit import *

In [3]: force = AmoebaAngleForce()

In [4]: force.addAngle(0, 1, 2, 109.47*degrees, 1.0*kilojoules_per_mole/radians**2)
Out[4]: 0

In [5]: force.getAngleParameters(0)
Out[5]: 
[0,
 1,
 2,
 Quantity(value=1.9106119321581925, unit=radian),
 Quantity(value=1.0, unit=kilojoule/(mole*radian**2))]
```

So it takes our input degrees and clobbers them to radians (and then it returns radians, although that is easily fixed).  The problem here is that `stripUnits` (as was implemented before and by @rmcgibbo in C) just applies `md_unit_system`.

I'm not sure what the best way of fixing this is -- it's rather unfortunate that the API demands degrees in this particular case...

**Comment by swails** [comment]
After thinking about it, I think the best thing to do is have AmoebaAngleForce interpret values >2*pi as degrees (which it has always done), and values < 2*pi as radians.  There are no valence angles that have equilibrium angle values of <10 degrees (that would be pretty absurd), so this should work in every case out in the wild so far.

I implemented this in #1076 (see 7ebe83b4b42175a2e33a07c1c2dc5dcd266c07d1 and 789024f).  The upside of this is that it shouldn't break backwards compatibility anywhere this code is in use currently, and it requires no modification of the `stripUnits` behavior, which has grown in complexity since it was moved to C.  As part of #1076, there are also tests for this behavior.

Thoughts?

**Comment by rmcgibbo** [comment]
Is the issue just that the docstring says it takes degrees, but the
md_unit_system unit for angles is radians?

**Comment by swails** [comment]
> Is the issue just that the docstring says it takes degrees, but the
> md_unit_system unit for angles is radians?

No.  The issue is that the force actually *takes* degrees (and presumably converts them to radians internally).  Tinker passes degrees to the C++ API and gets the same energies.

Unilaterally applying the `md_unit_system` to everything is the problem here, since it converts to radians when the force expects degrees (as per the docstring).

**Comment by peastman** [comment]
There's a *lot* of inconsistencies between the API for AMOEBA and everything else. :(

**Comment by rmcgibbo** [comment]
This could probably be worked around in the swig wrappers, by having AmoebaAngleForce.addAngle use different unit stripping code, although it would be ugly.

**Comment by jchodera** [comment]
Aren't we allowed to make API changes at major version number updates?

**Comment by rmcgibbo** [comment]
Sure. Obviously the cleanest thing would be to just fix the method to take radians.

**Comment by peastman** [comment]
Once a feature is out of beta, we pretty much guarantee to maintain source level compatibility.  We've never yet broken that guarantee.  So changing the API would be a really Big Deal (TM), and would require very close consultation with everyone who is using AMOEBA.

A safer approach is generally to keep the method working the way it does, but deprecate it and replace it with a new one.

**Comment by jchodera** [comment]
I like the idea of a new Amoeba API.  I'd love to see an Amoeba API that was consistent with the rest of the code.

The legacy Amoeba API is a plugin, yes?  What if there was an option as to whether or not to include the legacy Amoeba plugin at compile time?

**Comment by rmcgibbo** [comment]
The python API behavior that @swails described (`amoebaForce.addAngle(..., 109*degrees, ...)` not doing the right thing) is a bug though. It could be fixed
 - by changing the C++ API, with the ensuing backward compatibility problems
 - by changing how the unit stripping is applied in the swig wrappers, without changing the C++ API
 - something else.

**Comment by rmcgibbo** [comment]
> I like the idea of a new Amoeba API. I'd love to see an Amoeba API that was consistent with the rest of the code.

That sounds like a lot of work for... not much benefit.

**Comment by peastman** [comment]
That would be a way of doing it.  Though as @rmcgibbo says, it would be a lot of work.

Another possibility would be to just deprecate whole classes.  Just about all of the AMOEBA bonded forces could now be implemented with custom forces.  Had the custom forces existed when AMOEBA was first implemented, most of those classes probably wouldn't exist.  On the other hand, that would also be significantly less user friendly as an API.

**Comment by jchodera** [comment]
> That sounds like a lot of work for... not much benefit.

I'm just saying that I'd love to see it since it would make the API cleaner.  The cost/benefit analysis is obviously up to the people doing the heavy lifting.

I've heard Amoeba updates will be a major focus for OpenMM 7.  Are there other platform implementations (`CPU`, `OpenCL`) planned too?  Those would seem to also take a good deal of additional work.

> Another possibility would be to just deprecate whole classes. Just about all of the AMOEBA bonded forces could now be implemented with custom forces. Had the custom forces existed when AMOEBA was first implemented, most of those classes probably wouldn't exist. On the other hand, that would also be significantly less user friendly as an API.

Could you keep the classes and switch the implementation to use `Custom*Force` terms under the hood?  That could significantly simplify the implementation, and get you part of the way toward `CPU` and `OpenCL` platforms for free.

**Comment by peastman** [comment]
>  Are there other platform implementations (CPU, OpenCL) planned too?

Not currently.

> Could you keep the classes and switch the implementation to use Custom*Force terms under the hood?

Yes, that would be possible.

**Comment by swails** [comment]
> The python API behavior that @swails described (amoebaForce.addAngle(..., 109*degrees, ...) not doing the right thing) is a bug though. It could be fixed
> 
> * by changing the C++ API, with the ensuing backward compatibility problems

-1 on this.  I'm actively using the API as it exists right now.  As is Tinker through the OpenMM API.  This change would ruin all of my XML files and result in a painful transition period for me (and others) who use Tinker with OpenMM.

I'm with @peastman on this -- IMO we have committed to this API at this point.

> * by changing how the unit stripping is applied in the swig wrappers, without changing the C++ API

I'm good with this.  But I don't have the time to learn SWIG as well as I'd need to to implement this, so I won't be the one to do it.

> *  something else.

My solution to this in #1076 works just fine.  It's "unusual", but has some advantages IMO:

1. It works with the documented API and is backwards compatible
2. It works with the *expected* API (i.e., you give it an angle in radians, it works as expected).
3. Doesn't require changing the API
4. I've already done it.

It's definitely not what I would choose if I was making the API today -- it's "impure" for sure and requires angles less than 6.3 degrees be given in radians.  But there *are* no angles that small in real molecules, so I don't see this as a practical issue.

**Comment by peastman** [comment]
I think there should be a pretty simple way to deal with this in the SWIG wrappers.  My idea is to use %pythonprepend (see http://www.swig.org/Doc2.0/SWIGDocumentation.html#Python_nn42) to convert the value to an ordinary number given in degrees at the very start of the method.  Since stripUnits() is now done on the C++ side, the python code will get executed first and stripUnits() will just see a number.  Does that seem reasonable?

**Comment by peastman** [comment]
Add this to the end of pythoncode.i:

```Python
%pythonprepend OpenMM::AmoebaAngleForce::addAngle %{
    import simtk.unit as unit
    if unit.is_quantity(length):
        length = length.value_in_unit(unit.degrees);
%}

%pythonprepend OpenMM::AmoebaAngleForce::setAngleParameters %{
    import simtk.unit as unit
    if unit.is_quantity(length):
        length = length.value_in_unit(unit.degrees);
%}
```

**Comment by swails** [comment]
> Add this to the end of pythoncode.i:

That won't work for any version of SWIG too old to give named arguments, but we can do something like that.  I actually ran up against the same issue in `AmoebaTorsionTorsionForce`.  If I can get this to work, it's nicer than my solution.  My problem is that I had thought that the C++ `stripUnits` code was always invoked *before* anything else, but that's obviously not the case.

If I can get your idea to work, I'll report back and close this issue.  Thanks for the idea!

**Comment by peastman** [comment]
We're free to require whatever version of SWIG we want.  Why not just update the version check to require a version new enough to have named arguments?

https://github.com/pandegroup/openmm/blob/master/wrappers/python/CMakeLists.txt#L110-L120

**Comment by swails** [comment]
> We're free to require whatever version of SWIG we want. Why not just update the version check to require a version new enough to have named arguments?

Named arguments were introduced in SWIG 2.0.5, or maybe between 2.0.5 and 2.0.6 -- this is quite a recent version of SWIG (I think released within the last year) -- and I use SWIG 1.3.x on one of the machines I run production simulations on.  I'd really like to continue supporting older versions of SWIG for now.

It's a moot point, anyway, since I have it working for all versions now in #1076

**Comment by swails** [comment]
Actually, I'm going to keep this open until #1076 is merged (which is where this is fixed).

**Comment by rmcgibbo** [comment]
Swig 2.0.05 was released on 2014-04-19 according to
http://sourceforge.net/projects/swig/files/swig/.

**Comment by rmcgibbo** [comment]
edit: 2012, not 2014.

**Comment by swails** [comment]
Sorry.  My mistake.  SWIG fixed their Python wrappers (so it didn't always do compactdefaultargs) between 3.0.5 and 3.0.6.  *That* was released in the past year -- between Feb. and July 2015 according to that website (my version of 3.0.5 has explicit arguments, but I may have installed that from git; swigInputBuilder uses compact arguments for any version below 3.0.6).

So if we're not willing to support compact arguments, we need to require SWIG from July 2015 or newer.

**Comment by rmcgibbo** [comment]
@peastman's pythonprepend code could be done just fine without compact arguments. It's only for a couple methods, so you just have to know the position of the argument that needs to be corrected.

**Comment by swails** [comment]
> @peastman's pythonprepend code could be done just fine without compact arguments. It's only for a couple methods, so you just have to know the position of the argument that needs to be corrected.

I know.  I already did that.  See [here](https://github.com/swails/openmm/blob/tests/wrappers/python/src/swig_doxygen/swig_lib/python/pythoncode.i#L228-L279)

That code block works for compact args or the standard argument list.
