### ISSUE TITLE
loadCheckpoint failure (OpenMM 6.3.0 + Python 3.4)

### ISSUE THREAD

**Issue by mj-harvey** [pandegroup/openmm#1148]
Hi,

There appears to be a problem with the python binding for Context.loadCheckpoint() when using Python 3.4 (Anaconda, Linux). Running the TestSimulation unit test, I get the error:

```
...
======================================================================
ERROR: testRunForClockTime (__main__.TestSimulation)
Test the runForClockTime() method.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mjharvey/tmp/TestSimulation.py", line 131, in testRunForClockTime
    simulation.loadCheckpoint(checkpointFile)
  File "/home/mjharvey/anaconda3/lib/python3.4/site-packages/simtk/openmm/app/simulation.py", line 203, in loadCheckpoint
    self.context.loadCheckpoint(f.read())
  File "/home/mjharvey/anaconda3/lib/python3.4/site-packages/simtk/openmm/openmm.py", line 6063, in loadCheckpoint
    return _openmm.Context_loadCheckpoint(self, *args)
TypeError: in method 'Context_loadCheckpoint', argument 2 of type 'std::string'

----------------------------------------------------------------------
Ran 4 tests in 18.706s

FAILED (errors=2)

```

This was with the omnia/openmm 6.3.0 package installed via conda, but I've confirmed the problem seems to remain in HEAD.
The test passes correctly under Python 2.7

Matt

**Comment by peastman** [comment]
Someone recently reported the same problem on the simtk.org forum: https://simtk.org/forums/viewtopic.php?f=161&t=5976&sid=677f506d600c4d7b1db6f7336b4a9266.  But that test passes under Python 3.4 on both travis and appveyor.  Anyone have an idea what's going on?

**Comment by mj-harvey** [comment]
Hi Peter,

Yes, that looks like the same issue. I've done some limited investigation, but haven't made much progress. If I read the checkpoint file contents into a bytearray and then explicitly decode it as 'latin1', the loadCheckpoint() code no longer errors, but the simulation then throws a "Particle positions not set error".
As far as I can tell, from comparison to the run under python 2.7, the checkpoint file is being written correctly. 

My platform is 64bit anaconda 2.3.0 / python 3.4.3 on Ubuntu 15.04. I've limited opportunity to test other platforms right now, unfortunately.

**Comment by mj-harvey** [comment]
Working with a fresh build of head.
