### ISSUE TITLE
LocalCoordinatesSites / localCoords

### ISSUE THREAD

**Issue by rafwiewiora** [pandegroup/openmm#1185]
While thinking about the logic for position calculations for #1176 I realized `forcefield.py` has another VirtualSite type - localCoords, which is also mentioned in the User Guide, but does not have any corresponding logic in `modeller.py`. I can't find any Issues or PRs to do with it. 

Is there a reason why it's not part of `Modeller` or has it simply not been done yet? I'm just kind of wondering what the story behind it is. What kind of systems is that useful for?

**Comment by peastman** [comment]
Good point.  I'll add it.
