### ISSUE TITLE
Add fromName and toName attributes to ffxml parsing for Bond and ExternalBond

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1187]
(Continued from #1168)

We want to extend the `ffxml` format to add `fromName` and `toName` attributes to `<Bond>` and `<ExternalBond>` elements:
```XML
   <Bond fromName="O" toName="H1"/>
   <Bond fromName="O" toName="H2"/>
   ...
   <ExternalBond fromName="N">
```

**Comment by peastman** [comment]
I find "fromName" and "toName" a little clunky sounding.  How about this instead?

```XML
<Bond atom1="O" atom2="H1"/>
...
<ExternalBond atom="N"/>
```

**Comment by jchodera** [comment]
I like that, but doesn't that seem inconsistent and confusing if we continue to support "from/to" with atom indices?

**Comment by peastman** [comment]
We'll support them for backward compatibility, but specifying by name will be the recommended approach, and that's what the documentation will tell people to do.  Because really, that's how I should have done it in the first place!

**Comment by jchodera** [comment]
Before we commit to this (and essentially deprecating the old scheme) are there any other ways one might want to specify these?

**Comment by swails** [comment]
I like @peastman's idea.

**Comment by peastman** [comment]
I don't think so.  Did you have something in mind?

**Comment by jchodera** [comment]
> I don't think so. Did you have something in mind?

Nothing in particular, but wanted to make sure we didn't continue down the path of a weird inconsistent naming scheme if we needed to add more things down the road.

I'm happy with `atom1` and `atom2`.

**Comment by peastman** [comment]
If we change this, we really should also change `<VirtualSite>` tags to work the same way.  Unfortunately, those already use the attributes `atom1`, etc., but specifying atom indices instead of names:

```XML
<VirtualSite type="average3" index="3" atom1="0" atom2="1" atom3="2"
    weight1="0.786646558" weight2="0.106676721" weight3="0.106676721"/>
```

So we need a set of attribute names that will be consistent across all tags, and not conflict with any names that are currently used by any of them.

**Comment by jchodera** [comment]
I am back to favoring the inclusion of `Name` in the tag to be unambiguous, even if this is "clunky".  And hey, what is XML if not "clunky"?

What about 
```XML
<Bond fromName="O" toName="H1"/>
<ExternalBond atomName="N"/>
<VirtualSite type="average3" index="3" atomName1="N" atomName2="C" atomName3="O"
    weight1="0.786646558" weight2="0.106676721" weight3="0.106676721"/>
```
?

**Comment by mpharrigan** [comment]
Is there a justification for the "directionality" implied by from/to?

**Comment by peastman** [comment]
Not really.  Bonds are completely symmetric.

**Comment by jchodera** [comment]
The directionality implied by `to` and `from` is simply to maintain consistency with the existing schema:
```XML
 <Residues>
  <Residue name="ACE">
   <Atom name="HH31" type="710"/>
   <Atom name="CH3" type="711"/>
   <Atom name="HH32" type="710"/>
   <Atom name="HH33" type="710"/>
   <Atom name="C" type="712"/>
   <Atom name="O" type="713"/>
   <Bond from="0" to="1"/>
   <Bond from="1" to="2"/>
   <Bond from="1" to="3"/>
   <Bond from="1" to="4"/>
   <Bond from="4" to="5"/>
   <ExternalBond from="4"/>
  </Residue>
```
I don't like `from` and `to` either, honestly.

**Comment by peastman** [comment]
So `atomName1` and `atomName2`?

**Comment by jchodera** [comment]
> So `atomName1` and `atomName2`?

To be clear, are we talking about
```XML
<Bond atomName1="O" atomName2="H1"/>
<ExternalBond atomName="N"/>
<VirtualSite type="average3" index="3" atomName1="N" atomName2="C" atomName3="O"
    weight1="0.786646558" weight2="0.106676721" weight3="0.106676721"/>
```
but still allowing
```XML
<Bond from="0" to="1"/>
<ExternalBond from="0"/>
<VirtualSite type="average3" index="3" atom1="0" atom2="1" atom3="2"
    weight1="0.786646558" weight2="0.106676721" weight3="0.106676721"/>
```
?

**Comment by peastman** [comment]
Yes, but the documentation would only talk about the new naming convention.  The old convention would be supported only for backward compatibility.  Also, the virtual site would be

```XML
<VirtualSite type="average3" siteName="M" atomName1="N" atomName2="C" atomName3="O"
    weight1="0.786646558" weight2="0.106676721" weight3="0.106676721"/>
```

That is, which particle is the virtual site should be specified by name too.

**Comment by jchodera** [comment]
OK, so
```XML
<Bond atomName1="O" atomName2="H1"/>
<ExternalBond atomName="N"/>
<VirtualSite type="average3" siteName="M" atomName1="N" atomName2="C" atomName3="O"
    weight1="0.786646558" weight2="0.106676721" weight3="0.106676721"/>
```
Sounds good.

Maybe we can still document the old convention and label it "deprecated" rather than just omit it?

**Comment by jchodera** [comment]
Handled by #1258 (once that is merged).
