### ISSUE TITLE
Automatic neutralisation of system

### ISSUE THREAD

**Issue by leelasd** [pandegroup/openmm#1194]
Is it possible to add an option to not let do the modeller add counter ions ?
Say Neutralise=False in modeller add solvent

**Comment by peastman** [comment]
Yes, that would be possible.  Though I'm curious, when would you want to do that?

**Comment by leelasd** [comment]
I want to study ionic systems in water without the counter ions (using large enough boxes to not create ny artifacts). I generally use Gromacs to do that, but I want to use OpenMM. So I was wondering if its doable ?

**Comment by Lnaden** [comment]
Is it sufficient to just delete the added counter ions added by the `addSolvent` command with something like:

```python
modeller.delete([res for res in modeller.topology.residues() if res.name =="NA" or res.name == "CL"])
```

**Comment by leelasd** [comment]
That works too !! Thank you very much. 
But it would be good to have a warning rather than an error.

**Comment by peastman** [comment]
I hope you're doing this without periodic boundary conditions?  With PME, the system *must* be neutral, or the energy doesn't converge.  So the algorithm automatically adds a uniform neutralizing background.  With reaction field it's possible to have a charged system, but it's kind of a sketchy thing to do, and the reaction field approximation isn't really correct.

**Comment by leelasd** [comment]
I am trying to use a large water droplet and avoid using PBC with PME. I guess its fine

**Comment by peastman** [comment]
Ok.  In that case, this should be a reasonable thing to do.
