### ISSUE TITLE
CompoundIntegrator

### ISSUE THREAD

**Issue by wouterboomsma** [pandegroup/openmm#1196]
I am in the process of implementing a non-equilibrium candidate Monte Carlo procedure where I drive (perturb) internal degrees of freedom using some Monte Carlo move, and then propagate the remaining degrees of freedom using Velocity Verlet. After some discussions with John and Peter it seems these two steps are best coded in my own Integrator plugin - to allow specifying mutually exclusive sets of degrees of freedom. This should be no problem.

However, after a number of steps of this specialized integrator, I would like to run a number of steps with a generalized MD integrator on the entire system. For this purpose it would be extremely useful to have a CompoundIntegrator, which alternates between running two integrators, running a specified number of steps of each. For my purposes, no communication is needed between the integrators.

Would such an integrator be difficult to implement? - and would anyone else find it useful?

**Comment by jlmaccal** [comment]
I would find this useful as well. We are implementing some MC moves that we would like to intersperse with md.

I think the main question would be the API. I personally would like to have an arbitrary number of integrators and perhaps a `setActiveIntegrator` method or some way to schedule which integrators to run.

A way to share cached forces and energies would also be great, but that's probably a stretch. 


Sent from my iPhone

**Comment by jchodera** [comment]
How about this for an API usage example (based on @jlmaccal's suggestion):
```python
# Create some integrators we will want to switch between.
integrator1 = VerletIntegrator(timestep)
integrator2 = LangevinIntegrator(temperature, collision_rate, timestep)
integrator3 = MonteCarloIntegrator(...)
# Create a compound integrator.
integrator = CompoundIntegrator()
integrator.addIntegrator(integrator1)
integrator.addIntegrator(integrator2)
integrator.addIntegrator(integrator3)
# Create a Context
context = Context(system, integrator)
...
integrator.selectIntegrator(0)
integrator.step(1000)
integrator.selectIntegrator(1)
integrator.step(100)
...
```

**Comment by peastman** [comment]
In principle this should be straightforward.  In practice, I suspect there will be a lot of subtle complications from the fact that all current integrators expect to be the only integrator, and other parts of the system don't expect the integrator to ever change.  Those can be dealt with, but we'll need a lot of testing to make sure we've caught all of them.

**Comment by peastman** [comment]
Is everyone happy with the API John outlined above?  Are there any use cases we should try to address that wouldn't work with that design?

**Comment by jlmaccal** [comment]
> Is everyone happy with the API John outlined above?

It looks good to me.

**Comment by peastman** [comment]
Here's a first draft of the API.  Take a look and see if it looks ok.

https://github.com/peastman/openmm/blob/compoundintegrator/openmmapi/include/openmm/CompoundIntegrator.h

**Comment by wouterboomsma** [comment]
This certainly seems to cover my purposes. Thanks for looking into it, Peter.

**Comment by jchodera** [comment]
This is great, @peastman!

A few questions:
* What happens when `addIntegrator` is called after a `Context` is created?  Is an `Exception` thrown?
* How will `CustomIntegrator` be serialized to XML?
* Is it OK for the different added integrators to have different `timestep`s?  Is the current integrator's timestep just set as the current timestep?

**Comment by peastman** [comment]
> What happens when addIntegrator is called after a Context is created? Is an Exception thrown?

Yes, an exception.

> How will CustomIntegrator be serialized to XML?

It will include each of the component integrators as a tag inside it.

>  Is the current integrator's timestep just set as the current timestep?

Exactly.

**Comment by jchodera** [comment]
Sounds great, then!

**Comment by peastman** [comment]
CompoundIntegrator is now implemented and merged.  Give it a try.
