### ISSUE TITLE
binstar.org is renamed to anaconda.org

### ISSUE THREAD

**Issue by jhprinz** [pandegroup/openmm#1202]
Just realized that I cannot access or update my installed omnia packages using conda. Took me some time to realize that I had
```
conda config --add channels http://conda.binstar.org/omnia
```
in my settings and apparently the binstar url does not work anymore. You need to replace it by
```
conda config --add channels http://conda.anaconda.org/omnia
```
The old one can be removed using
```
conda config --force --remove channels http://conda.binstar.org/omnia
```

To see all installed channels you can use
```
conda config --get channels
```

if it finally looks like this
```
--add channels 'defaults'
--add channels 'http://conda.anaconda.org/omnia'
```
it should work again.

I fear this needs to be update everywhere (like omnia homepage, etc...) it also caused all my travis builds to fail

**Comment by mpharrigan** [comment]
Adding the channel simply as "omnia" (still) works

**Comment by jchodera** [comment]
We've been working on updating things everywhere slowly.

**Comment by jchodera** [comment]
Updated the `omnia` page:
http://www.omnia.md/instal/l

**Comment by jchodera** [comment]
Can you close this, @jhprinz?

**Comment by jhprinz** [comment]
Thanks!
