### ISSUE TITLE
Add methods for discovering parameters available in Context?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1206]
While `Context` has `getParameter(name)` and `setParameter(name, value)`, there are no other functions for inquiring or discovering which context parameters are available.

What do you think about extending the API to include something like this:
```python
nparameters = context.getNumParameters()
name = context.getParameterName(index)
```
so that we can autodiscover parameters like
```python
context_parameters = [ context.getParameterName(index) for index in range(context.getNumParameters()) ]
```
?

**Comment by jchodera** [comment]
It would also be incredibly convenient to have a convenient way to get a list of parameters in `System` objects as well.  This could similarly look like
```
nparameters = system.getNumParameters()
name = system.getParameterName(index)
```

**Comment by rmcgibbo** [comment]
Are you thinking of per-particle parameters or global parameters? I think all of the `*Force`s have getters for both types separately.

**Comment by jchodera** [comment]
Global parameters that can be changed dynamically via `context.setParameter(name, value)` or via the custom integrators.  

This can definitely be retrieved using the `Custom*Force` getters, but the idiom is a bit verbose:
```python
parameters = list()
for force_index in range(system.getNumForces()):
    force = system.getForce(force_index)
    if hasattr(force, 'getNumGlobalParameters'):
        for parameter_index in range(force.getNumGlobalParameters()):
            parameters.append(force.getGlobalParameterName(parameter_index))
```

**Comment by peastman** [comment]
`ContextImpl` already has a `getParameters()` method.  How about having `Context` provide an identical method that calls that?

**Comment by jchodera** [comment]
The `ContextImpl` API is [here](https://github.com/pandegroup/openmm/blob/master/openmmapi/include/openmm/internal/ContextImpl.h#L122-L125):
```C++
    /**
     * Get the set of all adjustable parameters and their values
     */
    const std::map<std::string, double>& getParameters() const;
```
It returns a map of parameters and their values.  That would be great for the `Context` case.

It would also be great to have a corresponding method for `System` objects.

**Comment by peastman** [comment]
A method on `System` would be more challenging.  The parameters are defined by the `ForceImpl` objects, and those don't get created until you create a `Context`.  So that would take significant architecture changes.

**Comment by swails** [comment]
You couldn't just loop through all `Force` objects and call `getGlobalParameter*()` functions?

**Comment by jchodera** [comment]
@swails, did you see the [earlier post](https://github.com/pandegroup/openmm/issues/1206#issuecomment-150980943)?

**Comment by peastman** [comment]
Not in C++.  Besides, that only covers custom forces.  There are others it would miss.

**Comment by jchodera** [comment]
Oh, I see---you're suggesting that as an implementation scheme!  That might require introspection, or some form of switch case.

Are all the `Custom*Force` objects derived from a common `CustomForce` superclass?

**Comment by peastman** [comment]
The only reliable way to identify context parameters for a force is by calling `getDefaultParameters()` on a `ForceImpl`.  Anything else is not guaranteed to work.  Custom forces happen to follow a naming convention, but that's just a convention, not from any common superclass.  And other types of forces do whatever they do.  For example, `AndersenThermostat` happens to define parameters called "AndersenTemperature" and "AndersenCollisionFrequency".  Those names are hardcoded.

**Comment by jchodera** [comment]
OK, so how about we go for the simple addition of `Context.getParameters()` and create a new feature request issue to backburner the mare involved addition of `System.getParameters()`?
