### ISSUE TITLE
Installing OpenMM for CUDA platform.

### ISSUE THREAD

**Issue by alexW432** [pandegroup/openmm#1233]
Hi,

I'm trying to install OpenMM for use with CUDA GPUs. Before installing I add the CUDA libraries and nvcc complier to my path. I have OpemMM installed in a custom directory so I also set OPENMM_PLUGIN_DIR to point to the new plugins directory. The instillation doesn't fail but if I run simtk.Installation it only recognises 3 platforms: Reference, OpenCL and CPU. I am new to CUDA and would like to ask are there any addition steps I should be performing for OpenMM to recognise a CUDA platform? Any help would be greatly appreciated.

Many thanks,
Alex

**Comment by swails** [comment]
Are you installing the binary package or compiling from source?

If you are installing the binary package, you *must* use the same CUDA version used to build OpenMM originally.  For OpenMM 6.3, I believe this means you need to have CUDA version 7.0 installed.

If you install from source, you can have whichever CUDA version installed that you want.

**Comment by rmcgibbo** [comment]
The method Platform.getPluginLoadFailures is pretty convenient here too. After importing OpenMM, it will tell you the error messages from the linker thst caused the plugin not to be loaded.

**Comment by alexW432** [comment]
I was using the binary package, changing to the correct version of CUDA worked perfectly.

Thank you,
Alex

**Comment by rmcgibbo** [comment]
@swails: I feel like we get this question/issue somewhat frequently -- and putting answers like this, or links to his, on the website or wiki or something in a consolidated place might be a good idea. Did you ever do anything like that with amber, or do you just encourage people to search the mailing list?

**Comment by rmcgibbo** [comment]
Also, for example, #1218 contains some super-useful information.

**Comment by swails** [comment]
> @swails: I feel like we get this question/issue somewhat frequently -- and putting answers like this, or links to his, on the website or wiki or something in a consolidated place might be a good idea. Did you ever do anything like that with amber, or do you just encourage people to search the mailing list?

Dave Case has expressed a similar sentiment before.  That is, to pull out particularly helpful or informative messages sent on the Amber mailing list and collect them in a single place as a helpful resource.  We haven't found a good place to do that, and such posts very quickly become lost.

My thought is something along the lines of the very-much-outdated-and-no-longer-updated http://ambermd.org/questions.html

Some ideas: take advantage of the Github Wiki to pull out helpful answers on issues (and the SimTK issue tracker) that have a high potential for re-use and collect/organize them.

**Comment by kyleabeauchamp** [comment]
Using Github Wiki as a FAQ seems like a reasonable starting point.  The Gromacs FAQ also seems pretty decent (http://www.gromacs.org/Documentation/FAQs).

**Comment by rmcgibbo** [comment]
I added a couple things: https://github.com/pandegroup/openmm/wiki. Feel free to make any edits.

**Comment by peastman** [comment]
We also have a troubleshooting guide at http://wiki.simtk.org/openmm/FAQApp, though it needs updating.

**Comment by yuhangwang** [comment]
I have the same issue. Here is the code suggested by rmcgibbo:
```
import simtk.openmm as m
print(m.Platform.getPluginLoadFailures())
```

In my case, I got the following output:
```
('Error loading library /Projects/steven/install/openmm/7.0.1/lib/plugins/libOpenMMCUDA.so: libcufft.so.7.5: cannot open shared object file: No such file or directory', 'Error loading library /Projects/steven/install/openmm/7.0.1/lib/plugins/libOpenMMRPMDCUDA.so: libOpenMMCUDA.so: cannot open shared object file: No such file or directory', 'Error loading library /Projects/steven/install/openmm/7.0.1/lib/plugins/libOpenMMDrudeCUDA.so: libOpenMMCUDA.so: cannot open shared object file: No such file or directory', 'Error loading library /Projects/steven/install/openmm/7.0.1/lib/plugins/libOpenMMAmoebaCUDA.so: libOpenMMCUDA.so: cannot open shared object file: No such file or directory', 'Error loading library /Projects/steven/install/openmm/7.0.1/lib/plugins/libOpenMMCudaCompiler.so: libnvrtc.so.7.5: cannot open shared object file: No such file or directory')
```

It turns out I added the `cuda/lib/` instead of `cuda/lib64` into `LD_LIBRARY_PATH`. After 
adding `cuda/lib64`, everything works.

```
There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 2.00224e-06
Reference vs. CUDA: 2.15066e-05
CPU vs. CUDA: 2.13644e-05
```

**Comment by liyigerry** [comment]
@rmcgibbo 
Can I use openmm only with GPU?
How to turn off the CPUs if I have these in the machine?

**Comment by rmcgibbo** [comment]
OpenMM can use either GPUs or CPUs. See the documentation on selecting the platform [here](http://docs.openmm.org/7.1.0/userguide/application.html#platforms).
