### ISSUE TITLE
Installation of pre-compiled binary requires write in source directory

### ISSUE THREAD

**Issue by dotsdl** [pandegroup/openmm#1239]
Installing OpenMM from a [pre-compiled binary](https://simtk.org/frs/download.php?file_id=4524) for Linux requires write privileges within the directory from which it is being installed. Without this, we get:

```
Traceback (most recent call last):
  File "setup.py", line 247, in <module>
    main()
  File "setup.py", line 243, in main
    writeVersionPy()
  File "setup.py", line 111, in writeVersionPy
    a = open(filename, 'w')
IOError: [Errno 13] Permission denied: 'simtk/openmm/version.py'

INSTALLATION FAILED
````
It seems strange that upon installation anything needs writing to in the source directory. I can get around this by explicitly moving the installation sources elsewhere, but it seemed a bit too obtuse to not report on. Is there a reason this can't be avoided?

**Comment by rmcgibbo** [comment]
Is this really a problem? 

Those binaries contain a compiled copy of the OpenMM library, but still require building the Python wrappers, IIRC. I'm sure it also needs to write to the `build` directory too, because it's using a standard `distutils`-based Python installation.

**Comment by peastman** [comment]
Distutils has various ways around this problem.  The easiest is the --user flag, which tells it to put the modules inside a directory in your home directory.  You can include that flag when you run the install script, and it will get passed along to distutils:

    ./install.sh --user

See https://docs.python.org/3/install/index.html#install-index for more information.

**Comment by rmcgibbo** [comment]
@peastman I think version.py still needs to be written in the source directory first, reglardless of distutils flags https://github.com/pandegroup/openmm/blob/master/wrappers/python/setup.py#L67-L76. We could have done that by using CMake's configure_file to write the version.py, but ¯\_(ツ)_/¯. I'm not convinced this is a problem.

**Comment by dotsdl** [comment]
Ah, yeah with distutils I guess there's no easy way around it. I'm installing OpenMM on each of our machines in the lab via ansible and keeping the pre-compiled binaries+installer in an NFS export with root_squash, so installing on a particular host with

    sudo /path/to/OpenMM-6.3.0-Linux/install.sh <<< "EOF\n\nEOF"

fails if the host can't write to the installer location (typical with root_squash). I think the workaround typically used for python packages is to just copy all the files to the local `/tmp` and then install from there, so I think I'll do that.

I was a bit perplexed by the contents of `setup.py`'s `writeVersionPy` function, which basically writes out `version.py`, which I wasn't sure if it was necessary. But given that you still need to build, too, seems moot.

Thanks for the help!
