### ISSUE TITLE
Modeller.addHydrogens() returns nan positions if hydrogens are already in place

### ISSUE THREAD

**Issue by rafwiewiora** [pandegroup/openmm#1251]
Test case: 4H12, after PDBFixer, add hydrogens in PDBFixer

`modeller.positions` are all `nan` after calling `modeller.addHydrogens()`. 

This does not happen if `modeller.addHydrogens(forcefield)` is called (`amber99sb.xml` and `tip3p.xml` in this test case, after removing Zn's from the file).

**Comment by peastman** [comment]
I can't reproduce this.  I told PDBFixer to load 4H12, then just stepped through the UI accepting defaults for everything (keep all chains, add all missing residues, keep all heterogens, add hydrogens for pH 7).  The results came out fine.

**Comment by rafwiewiora** [comment]
And you saved the file, loaded into OpenMM, made a `modeller` and called `modeller.addHydrogens()` and then inspected `modeller.positions`? Sorry I can't tell from your comment if you skipped this part in the comment or thought accidentally that I was talking about the PDBFixer output only? 

I did some playing around, it's weird - this only reproducibly happens if I save the file before then reloading into OpenMM. Using the PDBFixer API, just calling:
```python
fixer.findMissingResidues()
fixer.findMissingAtoms()
fixer.addMissingAtoms()
fixer.addMissingHydrogens(7.0)

modeller = Modeller(fixer.topology, fixer.positions)
modeller.addHydrogens()
modeller.positions
```

works fine most of the time, sometimes returns all 'nan' too and needs the fixer step to be repeated to return to normal behavior. UNLESS I call `modeller.addHydrogens()` again, then `modeler.positions` returns all `nan` every time. 
Same if I `PDBFile.writeFile` and `PDBFile` load before the modeller part. So it looks like it's sensitive to the exact positions that are fed in? 

Also, `random.choice` chose 10 structures from the PDB:
```
['./pdb1bia.ent',
 './pdb1mpw.ent',
 './pdb1seh.ent',
 './pdb1sgl.ent',
 './pdb2mol.ent',
 './pdb2qeq.ent',
 './pdb3p92.ent',
 './pdb3w7i.ent',
 './pdb4o0w.ent',
 './pdb4qb3.ent']
```

and run `modeller.addHydrogens()` on them TWICE. 6 of those return all `nan` `modeller.positions` (0, 1, 3, 5, 7, 9 in that list). 

If I reverse @jchodera 's commit here: #386 this doesn't happen (only checked for 4H12, the 10 random things hang within my patience limit) - also for 4H12 just increasing the number of max iterations to 100 restores ok behavior. Does `LocalEnergyMinimizer` return `nan` if the tolerance is not met within the max number of iterations?

**Comment by peastman** [comment]
I'm taking the file generated by PDBFixer and running it through this script:

```Python
from simtk.openmm.app import *
pdb = PDBFile('output.pdb')
modeller = Modeller(pdb.topology, pdb.positions)
modeller.addHydrogens()
print(modeller.positions[:100])
```

All the positions come out fine.  Do you have a PDB file that fails when run through that script?  If so, could you post it?

**Comment by peastman** [comment]
@rafwiewiora can you provide any more information on how to reproduce this?

**Comment by rafwiewiora** [comment]
Sorry! I can't reproduce this anymore in the same load file with H's - one run `addHydrogens()` way... But I can force it to fail by running `addHydrogens()` 3 times in a row on this: https://gist.github.com/rafwiewiora/84e33f8b28eab227a3b4

**Comment by rafwiewiora** [comment]
Something maybe similar that could suggest the culprit, yesterday I had a simulation run fail with a 'particle positions are nan' error. I can't link to the file, because confidential structure, but this was run: https://github.com/choderalab/fah-projects/blob/master/projects/setd8-p10478/code/equilibrate.py#L28-L41 on automatically chosen platform (Mac, CPU and OpenGL available). 

I assumed that was an OpenGL fail, the simulation runs ok when I force CPU. 

Could OpenGL be responsible for the above problems? 

Also a bonus question: how can I force OpenMM to always use CPU? Is there a system variable?

**Comment by jchodera** [comment]
You can request a particular platform with
```python
from simtk import openmm
platform_name = 'CPU' # can be 'CPU', 'CUDA', 'OpenCL', or 'Reference'
platform = openmm.Platform.getPlatformByName(platform_name)
...
context = openmm.Context(system, integrator, platform) # use specified platform
```
Note that the platform you are talking about is OpenCL, not OpenGL.

We would also need to know which architecture you ran this on (linux? mac?) and what version of OpenMM you were using to help further.

There is always a chance that running a simulation with finite timestep will produce an `NaN` stochastically.  We just hope that probability is small if we take precautions (minimize thoroughly first; use a reasonably small enough timestep; etc.)

**Comment by rafwiewiora** [comment]
> Note that the platform you are talking about is OpenCL, not OpenGL.

Haha, standard, I was reading some OpenGL stuff the other night that's why! 

OS X Yosemite, 10.10.4, OpenMM is 7.0.0.dev0, py27_0. 

> There is always a chance that running a simulation with finite timestep will produce an NaN stochastically.

This is very interesting to me - why? Can you expand a bit if quick or point me to some reading?

**Comment by rmcgibbo** [comment]
To have zero probability of producing NaNs, I think the potential would need to be Lipschitz (and you need to be running with a timestep less than the reciprocal Lipschitz constant). But since NaNs are in fact possible, the potential, as implemented, isn't Lipschitz continuous everywhere.

**Comment by rmcgibbo** [comment]
Intuitively, there's always going to be some positive Boltzmann weight on a region of phase space that's _basically adjacent_ to a region of phase space whose energy would be computed as NaN. So if you end up there -- which by ergodicity you will -- some of the time you'll jump across to NaNdyland.

**Comment by jchodera** [comment]
@rmcgibbo is correct.  The best we can do is to minimize the probability of `NaN`s occurring---it can be made vanishingly small---and reject excursions into `NaN` regions.  The FAH core essentially does this by backing up the the last good checkpoint when this happens and using a different sequence of random thermostat numbers to hopefully not cause a `NaN`, but it will only try a few times.  If things die over and over again, something is very wrong with the simulation settings.

**Comment by peastman** [comment]
To give a specific example of this, most water models don't include LJ terms on the hydrogens.  That means if an oxygen and a hydrogen get too close to each other, they'll feel an attractive force that goes to infinity as they approach each other.  Boom!  They rely on the repulsion between oxygens to keep them sufficiently far apart.  But if, just by chance, two water molecules ever get too large a relative velocity in the wrong direction, they'll be able to cross that barrier and get into the region of attraction, and then your simulation will probably explode within a few time steps.

On the other hand, if you're using appropriate settings, this sort of event should be rare.  If you see this happen regularly, that suggests something else is wrong.

**Comment by rafwiewiora** [comment]
I see, that's great explanations, thanks everyone!

**Comment by jchodera** [comment]
@rafwiewiora: Can this be closed?

**Comment by rafwiewiora** [comment]
Sorry! Yep, good to close, closing.
