### ISSUE TITLE
Geometry optimization result depends on which GPU is used

### ISSUE THREAD

**Issue by leeping** [pandegroup/openmm#1254]
Hi there,

It's been a while.  :)  I'm reporting an issue I found running on a development machine with four GPUs, and the result from OpenMM depends on which GPU I use:

```
GeForce GTX TITAN : CC 3.5
GeForce GTX 670    : CC 3.0
GeForce GTX 750 Ti : CC 5.0
Tesla C2075       : CC 2.0
```

I have compiled the latest development version of OpenMM from the repository and I'm using CUDA 6.5.  I'm running the ForceBalance unit tests, one of which checks the energy, geometry, and multipole moments resulting from a geometry optimization.  The optimization result is checked against a stored reference value.  The purpose of these tests is to ensure that the software packages are giving a consistent result for simple calculations.

My issue is that one of my ForceBalance unit tests is failing when I use the TITAN, 670, or 2075, but it works when I use the 750 Ti.  Namely, the optimized geometry is incorrect with three of the GPUs and correct with the fourth one.  This is a very simple geometry optimization of a small tripeptide in the AMBER force field.

The error message is:

```
Failure 1:
AssertionError: ndarrays not equal
A[0]	-15.2118053223 =! -15.1032528603	B[0]
A[1]	-6.46736545574 =! -3.84892632379	B[1]
A[2]	0.179680438621 =! 0.789929623519	B[2]
OpenMM dipole moments at optimized geometry do not match the reference
----------------------------------------------------------------------
Failure 2: 
AssertionError: -61.85246166271882 != -61.820866873804967 within 0.001 delta : OpenMM optimized energies do not match the reference
```

It will take some effort to distill this down into a runnable test case outside of ForceBalance, so I was wondering if this was a known issue that you have seen before.  Thanks a lot!

- Lee-Ping

**Comment by swails** [comment]
Are you using the default convergence criteria?  Because I believe that it was recently made a lot looser than it used to be (I think the default value is 10 kJ/mol now, where it used to be 1).

**Comment by leeping** [comment]
I'm not using the default convergence criteria. It's set to 1e-6 kJ/mol in the test and I'm using CUDA double precision.

**Comment by rmcgibbo** [comment]
- Have you tried comparing to the reference platform?
- Does the system have constraints?
- What about substituting out the default optimizer and using a steepest descent CustomIntegrator or similar?

**Comment by leeping** [comment]
Hi Robert,

- Yes, the test passes with the reference platform.
- There are no constraints.
- I haven't tried any other optimization algorithm apart from the default. Isn't the test still strange, though?

- Lee-Ping

**Comment by rmcgibbo** [comment]
Yeah, it's kind of strange. But it's hard to know how tight the tolerances you're asking for are without looking at it. If it's just a tripeptide with AMBER, can you attach the system.xml?

**Comment by leeping** [comment]
Sure, no problem, I can do that. :)  Here's an archive with the system.xml and four state.xml's corresponding to:

- Initial geometry
- Optimized, reference platform
- Optimized, CUDA platform, passes test
- Optimized, CUDA platform, fails test
 
Strangely, the failing case actually reports a lower energy than the passing case.  It's possible that my reference number is bad, though I obtained it from a past calculation where Gromacs, OpenMM and TINKER were all consistent.

https://dl.dropboxusercontent.com/u/5381783/robert.tar.gz

**Comment by jchodera** [comment]
Isn't energy minimization on a multimodal landscape very sensitive to the precise nature of the floating-point architecture?  I've often seen minimization in double precision on a CPU give different results on different architectures because some differences in instruction ordering or the precise floating point operations lead the minimizer to end up in different minima.

**Comment by rmcgibbo** [comment]
I think @jchodera is right. I don't think you can actually expect to reliably get the exact same minima each time, or that this test actually verifies anything that should be an invariant.

The two geometries you gave have potential energies of `-258.790` and `-258.658` kJ/mol. In contrast, by running just 2ps of dynamics after velocity randomization before quenching with the minimizer, I was able to get other minima at `-362.067, -342.704, -305.867, -299.195`, etc. ([script](http://pastebin.com/rREzx5dF)).

Even running 10 fs of dynamics before quenching was enough to tip the Reference platform from finding the `-258.65` to finding the `-258.78` minima.

**Comment by peastman** [comment]
There is one thing you can reliably test for: the magnitude of the force.  There's no guarantee about which minimum you'll get, but there is a guarantee about how close it will get you to whatever minimum it finds (unless you set a maximum number of iterations, of course, in which case that isn't guaranteed either).

Of course, that also assumes the tolerance you request is achievable in the requested precision model.  You're using double precision, so that's probably ok, but 1e-6 is a *really* strict tolerance.  The reason we increased the default from 1 to 10 was that 1 wasn't reliably achievable in single precision, and you're asking for something 7 orders of magnitude smaller.

**Comment by leeping** [comment]
Thanks for the tips.  I'm surprised that it's so easy for the same minimization algorithm to find a different local minimum, but it sounds like I should either retool or eliminate the test in ForceBalance.  I have other tests that checks energies, forces, and multipole moments - but since several of the targets actually involve optimizing the geometry first (for example, when calculating vibrational frequencies), I wanted to test that functionality.

- Lee-Ping

**Comment by leeping** [comment]
PS: I think there are some very simple systems (e.g. a water dimer) where converging to the same local minimum is pretty much guaranteed.

**Comment by jchodera** [comment]
> PS: I think there are some very simple systems (e.g. a water dimer) where converging to the same local minimum is pretty much guaranteed. Maybe I should just switch the system to one of those.

Can you modify the Hamiltonian so that it is unimodal?  For example, you could add harmonic bond and angle restraints that ensure that there is only one minimum.

Alternatively, you could converge estimates of expectations by running simulations, though would have to have a statistical form of the test (which is a whole other can of worms).

**Comment by leeping** [comment]
Hi John,

I think the harmonic restraint is a good idea, but presently ForceBalance doesn't have the functionality for automatically setting up restrained minimizations.  It might also be possible to play with the initial conditions and keep the test the same; for example, we may use Robert's script to find a deep minimum and perturb slightly away from that to make the initial condition.

- Lee-Ping

**Comment by rmcgibbo** [comment]
Okay, it sounds like there's not an openmm problem here, so I'll close this issue.
