### ISSUE TITLE
enforcePeriodicBox behaves weird for triclinic UCs

### ISSUE THREAD

**Issue by swails** [pandegroup/openmm#1255]
[I said weird, not wrong.](https://youtu.be/OHTcxLde9AY)

**Comment by peastman** [comment]
Can you post files to reproduce this?

**Comment by swails** [comment]
NEVER! (read, tomorrow when I'm back at my computer :)).

**Comment by swails** [comment]
[You can download the files from Dropbox here](https://www.dropbox.com/s/km2jycf69jwujvb/example.tgz?dl=0) -- you need to install ParmEd to run the script.

Note that this system also occasionally flounces off to NaNdyland despite the fact I can't see why it would.  My first suspicion was that it had to do with the barostat, since [it looks like a finalEnergy of NaN would result in the attempt succeeding](https://github.com/pandegroup/openmm/blob/master/openmmapi/src/MonteCarloBarostatImpl.cpp#L93-L102) -- an energy of NaN would *always* fail the comparison, meaning the step would *not* be rejected and would be accepted instead.

This turns out not to be the case, as running NVT resulted in a NaN over time as well.  My new suspicion is `periodicdistance` inside the `CustomExternalForce` I added.  I'm still testing that.  In any case, should we flip the logic in the MonteCarloBarostat to reject in the `else` branch (which would have the advantage that NaNs would always trigger rejection)?

**Comment by swails** [comment]
Looks about right.  I'll reopen if #1275 is not the right fix.

Thanks!
