### ISSUE TITLE
Remove GBVIForce?

### ISSUE THREAD

**Issue by peastman** [pandegroup/openmm#1265]
I wonder if the time has finally come for us to get rid of GBVIForce?  It's been marked as deprecated for ages.  We've never actually provided any force field that uses it.  Neither the CUDA nor OpenCL platform supports it.  It isn't mentioned anywhere in the user guide.  And if anyone really wants to use that functional form, it's easy to implement with CustomGBForce.

**Comment by swails** [comment]
I personally don't use it. and I can't imagine anybody else is either if it doesn't have a cuda or opencl implementation. 

IIRC, there is a test somewhere or something where GBVI is implemented with CustomGBForce, so if that's something that's easy to find it will probably help even the one person out there currently using GBVI to trash it. :)

**Comment by rmcgibbo** [comment]
No objection from me. If we're at all concerned, we could add the CustomGBForce-based implementation of GBVI as an example in the docs.

**Comment by jchodera** [comment]
Mark Friedrichs and I were never able to validate `GBVIForce` against the published data in the paper describing it, so I actually feel better about deprecating it than keeping it around.
