### ISSUE TITLE
Strange problem detecting platforms

### ISSUE THREAD

**Issue by jlmaccal** [pandegroup/openmm#1267]
Here's a new one...

OS X 10.11.1
Anaconda 2.3.0

Using the following script:
```python
#!/usr/bin/env python

from simtk import openmm as mm

n = mm.Platform.getNumPlatforms()
print 'There are {} platforms.'.format(n)
print

for i in range(n):
    p = mm.Platform.getPlatform(i)
    print '    {}'.format(p.getName())
print
```

When I run using `python`:
```
% which python
/Users/jlmaccal/anaconda/bin/python

% python test.py
There are 4 platforms.

    Reference
    CPU
    CUDA
    OpenCL
```

But when running `ipython` it doesn't find the CUDA platform:
```
% which ipython
/Users/jlmaccal/anaconda/bin/ipython

% ipython test.py
There are 3 platforms.

    Reference
    CPU
    OpenCL

```

I'm at a total loss here. I've `conda remove ipython; conda install ipython` to no avail. I have no idea what could be causing this.

**Comment by rmcgibbo** [comment]
From IPython, what's the output of
 - sys.executable
 - `mm.Platform.getPluginLoadFailures()`

**Comment by jlmaccal** [comment]
Thanks, I didn't no about `getPluginLoadFailures()`. Looks like it might be a problem with `libcufft`, but I don't understand why it works with `python`, but not `ipython`.

```
In [1]: import sys

In [2]: sys.executable
Out[2]: '/Users/jlmaccal/anaconda/bin/python'

In [3]: from simtk import openmm as mm

In [4]: mm.Platform.getPluginLoadFailures()
Out[4]: 
('Error loading library /usr/local/openmm/lib/plugins/libOpenMMCUDA.dylib: dlopen(/usr/local/openmm/lib/plugins/libOpenMMCUDA.dylib, 9): Library not loaded: @rpath/libcufft.6.5.dylib\n  Referenced from: /usr/local/openmm/lib/plugins/libOpenMMCUDA.dylib\n  Reason: image not found',
 'Error loading library /usr/local/openmm/lib/plugins/libOpenMMRPMDCUDA.dylib: dlopen(/usr/local/openmm/lib/plugins/libOpenMMRPMDCUDA.dylib, 9): Library not loaded: @rpath/libOpenMMCUDA.dylib\n  Referenced from: /usr/local/openmm/lib/plugins/libOpenMMRPMDCUDA.dylib\n  Reason: image not found',
 'Error loading library /usr/local/openmm/lib/plugins/libOpenMMDrudeCUDA.dylib: dlopen(/usr/local/openmm/lib/plugins/libOpenMMDrudeCUDA.dylib, 9): Library not loaded: @rpath/libOpenMMCUDA.dylib\n  Referenced from: /usr/local/openmm/lib/plugins/libOpenMMDrudeCUDA.dylib\n  Reason: image not found',
 'Error loading library /usr/local/openmm/lib/plugins/libOpenMMAmoebaCUDA.dylib: dlopen(/usr/local/openmm/lib/plugins/libOpenMMAmoebaCUDA.dylib, 9): Library not loaded: @rpath/libOpenMMCUDA.dylib\n  Referenced from: /usr/local/openmm/lib/plugins/libOpenMMAmoebaCUDA.dylib\n  Reason: image not found')
```

**Comment by rmcgibbo** [comment]
How do you compile / install OpenMM? I don't think the `@rpath` entry for libcufft is correct.

**Comment by rmcgibbo** [comment]
Also, can you post the output of `otool -L /usr/local/openmm/lib/plugins/libOpenMMCUDA.dylib`?

**Comment by jlmaccal** [comment]
I'm not compiling in any strange way. `ccmake` and then configure and generate. `make install; make PythonInstall`.

Output:
```
/usr/local/openmm/lib/plugins/libOpenMMCUDA.dylib:
	@rpath/libOpenMMCUDA.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/CUDA.framework/Versions/A/CUDA (compatibility version 1.1.0, current version 6.5.36)
	@rpath/libOpenMM.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libcufft.6.5.dylib (compatibility version 0.0.0, current version 6.5.14)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
```

**Comment by rmcgibbo** [comment]
Hmm.

**Comment by rmcgibbo** [comment]
Hmm. I really have no idea. Maybe that *is* right with `rpath`. I don't really know much about frameworks with the OS X linker.
- Do you have any IPython config files that might be preloading something that changes around dyld settings?
- Is this something that only recently started happening? Was it triggered by anything memorable like updating OpenMM / Python / Anaconda / OS X?
- What's the output of `DYLD_PRINT_LIBRARIES=1 python test.py` and `DYLD_PRINT_LIBRARIES=1 ipython test.py`
- What if you try putting `import IPython` and or `IPython.embed()` inside the python script before `import`ing openmm?

**Comment by jlmaccal** [comment]
* Just deleted `.ipython`. No change.
* I guess I haven't used OpenMM recently on this machine, so probably all of the above.
* The `DYLD_PRINT_LIBRARIES=1 ipython` command doesn't produce any additional output, whereas the other command prints a whole ton of libraries. Perhaps due to the way ipython is launched, it is somehow not getting the right environment?
* `import IPython` has no effect. Other command launches an ipython interpreter. The script runs after it closes and still finds all four platforms.

**Comment by rmcgibbo** [comment]
> The DYLD_PRINT_LIBRARIES=1 ipython command doesn't produce any additional output, whereas the other command prints a whole ton of libraries. Perhaps due to the way ipython is launched, it is somehow not getting the right environment?

Does `DYLD_PRINT_LIBRARIES=1 ipython -c 'import simtk.openmm as mm'` not produce _any_ output? That is weird. And `export DYLD_PRINT_LIBRARIES=1; ipython -c 'import simtk.openmm as mm'` also is silent?

**Comment by jlmaccal** [comment]
No sorry, the `DYLD_PRINT_LIBRARIES=1 ipython test.py` command produces the output from the script, but does not produce any additional output related to the linker.

I think I'm starting to track it down. `os.environ` gives different results between `python` and `ipython`. Most importantly, the `DYLD_LIBRARY_PATH` is missing from the ipython environment. I'm sure this is the problem, but don't know why it's happening.

**Comment by jlmaccal** [comment]
Yes, both commands are silent.

**Comment by rmcgibbo** [comment]
What's the shebang in `cat $(which ipython)`?

**Comment by jlmaccal** [comment]
`#!/bin/bash /Users/jlmaccal/anaconda/bin/python.app`

Contents of that file are:
```
#!/bin/bash
export PYTHONEXECUTABLE=/Users/jlmaccal/anaconda/bin/python
/Users/jlmaccal/anaconda/python.app/Contents/MacOS/python "$@"
```

I use `zsh` rather than bash. I wonder if that could be causing some problem? Changing both `bash` entries to `zsh` doesn't change the results.

**Comment by rmcgibbo** [comment]
And if you try running your script with `/Users/jlmaccal/anaconda/python.app/Contents/MacOS/python` instead of `python`, does it work  or fail?

**Comment by jlmaccal** [comment]
That works.

This appears to be an outstanding conda issue: https://github.com/ipython/ipython/issues/8878

**Comment by jlmaccal** [comment]
So, installing and using `jupyter` instead somehow magically fixes everything.

Anyway, closing as this clearly has nothing to do with OpenMM. Thanks for your help.

**Comment by rmcgibbo** [comment]
Very weird. I don't know what the purpose of this is in conda. cc: https://github.com/conda/conda-build/issues/628 I guess. I tried to reproduce https://github.com/ipython/ipython/issues/8878#issuecomment-146466453 on my environment, but I couldn't reproduce it.

The easiest fix, I think, would be to set `alias ipython='python -m IPython`, and ping that issue.

**Comment by rmcgibbo** [comment]
You should bump that issue on the conda repo though.

**Comment by jlmaccal** [comment]
Good point. I'll do that.

**Comment by swails** [comment]
I'm jumping in late and cherry-picking here, but one comment I'll make (because I somewhat recently found this out myself), is that setting `DYLD_LIBRARY_PATH` is generally discouraged.  It's much better to set `DYLD_FALLBACK_LIBRARY_PATH` instead ([reference](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/dyld.1.html)).

I think the general difference here is that for the former, those paths are forcibly searched first.  In the latter, they're only searched if the standard search paths yield no matching library.
