### ISSUE TITLE
Way to save positions, velocities, and box info via OpenMM only

### ISSUE THREAD

**Issue by dr-nate** [pandegroup/openmm#1269]
Hi all,

Is there a way to save a restart file that contains positions, velocities, and box dimensions at the end of a simulation using *only* the OpenMM package? [The user guide](http://docs.openmm.org/6.3.0/userguide/application.html#saving-the-results) don't seem to have anything about this. I also searched previous issues.

Up until now I've been using ParmEd to achieve this function, but it seems like this is something that should be supported natively, at least in one iteration (Amber has .rst files, NAMD has .coor .vel .xsc files). I'll be happy to go ahead and implement that if we want that, but I wanted to be sure there wasn't a reason it wasn't implemented.

Nate

**Comment by mpharrigan** [comment]
http://docs.openmm.org/6.3.0/userguide/application.html#writing-trajectories

mdtraj, parmed(?) contain additional "reporters" for different formats

**Comment by peastman** [comment]
Also see `Simulation.saveCheckpoint()` and `Simulation.saveState()`.

**Comment by peastman** [comment]
Can this be closed?  OpenMM already has multiple ways of doing this.

**Comment by rmcgibbo** [comment]
I think so. But we should add a note about saveCheckpoint and saveState to the userguide after the section that matt linked to about reporters.

**Comment by dr-nate** [comment]
You can close it. I'll update the docs in a few days to clarify all this
for people.

**Comment by cing** [comment]
No mention of ```CheckpointReporter()``` in this thread so far, I feel like that should be in the docs too!

**Comment by swails** [comment]
I'm personally more of a fan of serialized states than checkpoints.  The former are a lot more portable (and I often switch machines and/or GPUs), and can even be used as coordinate files easily. ParmEd will recognize a serialized state as a coordinate file the same way it would any other coordinate or trajectory file, for instance.  You can't get that with a checkpoint.

The only real advantage I see in checkpoints is that the files themselves are smaller (I believe?).  But a lot of the "extras" (like I think they restore random generator states and such?) don't really have much of an effect.

I personally save a serialized state at the end of my scripts and restart from that (which I think is what `Simulation.saveState` does).

**Comment by mpharrigan** [comment]
More relevant discussion for the docs ^^

**Comment by peastman** [comment]
In many cases, a checkpoint allows you to *exactly* reproduce the simulation.  You can reload the same checkpoint several times, and each time then get exactly the same trajectory.  There are situations where that's useful.

**Comment by swails** [comment]
> In many cases, a checkpoint allows you to exactly reproduce the simulation. You can reload the same checkpoint several times, and each time then get exactly the same trajectory. There are situations where that's useful.

OpenMM is deterministic now?

**Comment by peastman** [comment]
"In many cases".  On OpenCL, forces are completely deterministic.  On CUDA, they're deterministic if you either don't use PME, or if you use double precision.

**Comment by swails** [comment]
I didn't realize OCL and CUDA/double were deterministic, but I recall you mentioning that CUDA/PME was not deterministic because of the charge spreading step, but anything not using PME would be deterministic on CUDA.

What about Reference and CPU?  I suspect the former is, but not the latter?

**Comment by peastman** [comment]
I believe that's correct.

**Comment by dr-nate** [comment]
Just to clarify, is this statement correct?: "Using PME on any platform but `Reference` will result in a non deterministic simulation due to the way charge spreading calculations are done."

**Comment by swails** [comment]
No.  PME on OpenCL and Reference, and on CUDA in double precision only, will be deterministic.

The CPU platform is not deterministic (unless you do single-core, I believe).

**Comment by peastman** [comment]
More important, none of that behavior is actually guaranteed.  We reserve the right to change any of it in the future.  _In many cases_ it will lead to an identical trajectory, but we never guarantee that will happen.
