### ISSUE TITLE
ParmEd AMBER and CHARMM forcefield conversion

### ISSUE THREAD

**Issue by rafwiewiora** [pandegroup/openmm#1281]
@ChayaSt and I are now working on conversion of AMBER and CHARMM parameters to ffxmls using ParmEd. Opening this for discussion.

**Comment by swails** [comment]
Let's open this on the ParmEd github page (and link to this issue).  I think it's a more relevant discussion there.

**Comment by swails** [comment]
I opened an issue for discussion in the ParmEd repo (ParmEd/ParmEd#486).

**Comment by rafwiewiora** [comment]
Thanks @swails ! Haha I was gonna do just that after I opened this but got distracted...

**Comment by jchodera** [comment]
From #1184, the new `ParmEd`-based scheme will
* Produce AMBER `ffxml` files that use new `ffxml` extensions (#1168) such as the per-atom typing scheme (#1182) and the name-based `<Bond>` specification schemes (proposed in #1168)
Correctly handle prep files (see #1181)
* Uses a script to automate the conversion of AMBER forcefields and inclusion of references for provenance data in the `ffxml` files.
* Puts parameters and residue definitions into different `ffxml` files so that we can combine `gaff.xml`, small molecule residue templates (generated externally), and gbsa parameters in a "mix-and-match" way.
* Add automated nosetests to ensure that conversion gives correct parameters

**Comment by rafwiewiora** [comment]
While working on the new ffxml for https://github.com/pandegroup/openmm/pull/1176 last night I realized I was a bit confused about what exactly the new ffxml format should look like. The whole discussion was spread around a few issues and PRs, so could we summarize all the changes here and maybe put together an example ffxml in the new format?

Here's what I am sure of:
- charges can be specified in residue templates and L-J are not specified by class, not type: https://github.com/pandegroup/openmm/pull/1182/files
- bonds in residue templates can be specified using atom names rather than indices: https://github.com/pandegroup/openmm/pull/1258

What I'm not clear on:
- how are  <HarmonicBondForce>,  <HarmonicAngleForce> and  <PeriodicTorsionForce> specified in the new ffxml? This is where classes are used in the existing ffxml's, am I right in understanding that in the new ffxml's: we are now making Classes more general, i.e. L-J Classes, and Types are now grouping atoms that behave the same in <HarmonicBondForce>, <HarmonicAngleForce>  and <PeriodicTorsionForce> ? I.e. this is exactly the same two groupings that AMBER uses. 

    Has the use of Types in these sections instead of Classes been implemented? I haven't been able to confirm that. Or am I just not realizing you could always use Types there too? 

- what is the default for charges specification if all atoms in the same class have the same charge (which happens for very small classes, like I have in the metal ffxmls) - should the charges be specified in residue templates for consistency with other residues or in NonbondedForce?

**Comment by rafwiewiora** [comment]
> how are <HarmonicBondForce>, <HarmonicAngleForce> and <PeriodicTorsionForce> specified in the new ffxml? This is where classes are used in the existing ffxml's, am I right in understanding that in the new ffxml's: we are now making Classes more general, i.e. L-J Classes, and Types are now grouping atoms that behave the same in <HarmonicBondForce>, <HarmonicAngleForce> and <PeriodicTorsionForce>? I.e. this is exactly the same two groupings that AMBER uses.
> 
> Has the use of Types in these sections instead of Classes been implemented? I haven't been able to confirm that. Or am I just not realizing you could always use Types there too?

Ok, I'm clear on this now after talking to @jchodera and seeing that Forces could already be specified by type too. 

> what is the default for charges specification if all atoms in the same class have the same charge (which happens for very small classes, like I have in the metal ffxmls) - should the charges be specified in residue templates for consistency with other residues or in NonbondedForce?

Only this remaining to clarify.

**Comment by jchodera** [comment]
> Ok, I'm clear on this now after talking to @jchodera and seeing that Forces could already be specified by type too.

You can use either `type` or `class` to specify which atoms `Force` terms are to be applied to.

@peastman wrote some great documentation about this that might be worth re-reading:
http://docs.openmm.org/6.3.0/userguide/application.html#harmonicbondforce

**Comment by jchodera** [comment]
> what is the default for charges specification if all atoms in the same class have the same charge (which happens for very small classes, like I have in the metal ffxmls) - should the charges be specified in residue templates for consistency with other residues or in NonbondedForce?

I would *always* specify charges in the residue templates.

**Comment by swails** [comment]
> I would always specify charges in the residue templates.

+1

This is already done in the CHARMM and Amber residue template libraries.

**Comment by rafwiewiora** [comment]
Ok, great!

**Comment by rafwiewiora** [comment]
We're talking in separate issues, mostly on the https://github.com/choderalab/openmm fork now, I don't see this issue being useful ever again. Closing for now.
