### ISSUE TITLE
Final features for 7.0

### ISSUE THREAD

**Issue by peastman** [pandegroup/openmm#1282]
I think we're getting close to the point where we declare 7.0 feature complete and put out a beta.  Are there any remaining features we want to wait for?  I know of a few things that are in progress that we should consider.

1. Extrapolated polarization for AMOEBA (#1153).
2. Convert API docs to Sphinx (#1238).
3. Changes to how we protonate residues that coordinate ions (#1176).
4. Changes to support constant pH (#1278).

Are there any others we should consider?

Do people have estimates of how long each of the above will take to complete?  For extrapolated polarization, I'm still waiting for @andysim to complete the reference implementation.  Once that's done, it should take me very little time to port it to CUDA.  How about the others?

**Comment by andysim** [comment]
The polarization code that I pushed is correct, but I'm working right now to make it a little more efficient.  I know the reference implementation is not supposed to be fast, but I want to provide a sensible algorithm to base the CUDA version on.  I expect to have it done this week.

**Comment by peastman** [comment]
Great, thanks!  Also, having test cases for it will be essential.  That's even more important than efficiency.

**Comment by andysim** [comment]
I couldn't agree more.  I know how to add to the OpenMM unit tests, but may need some help hooking into the finite difference test machinery.

**Comment by peastman** [comment]
Do you mean for checking consistency between forces and energies?  Here's a good example of a test case that does that:

https://github.com/pandegroup/openmm/blob/master/tests/TestCustomManyParticleForce.h#L118-L138

**Comment by andysim** [comment]
Oh, that's easy.  I found [this page](https://github.com/pandegroup/openmm/issues/575) when I was searching for OpenMM's validation mechanisms, so I thought I'd have to do something to hook into it.

**Comment by jchodera** [comment]
My wishlist is:

### Pretty close
* Multisite ions for Amber (#1032) - @rafwiewiora is working on this with @peastman
* AmberTools15 forcefields (#503) - @rafwiewiora is working on this with @swails
* CHARMM 36 forcefields (#685) - @chayast is working on this with @swails

### Less close
* support for small molecules via `ForceField` and `ffxml` route, which needs better mix-and-match support (especially for GB) (#1168)
* constant-pH simulation support (#172; #494; #1278) - @bas-rustenburg is working on this, but it will take a great deal of work

### No idea
* Support for external hooks for `ForceField` to call out to parameterize small molecules (#488); ideally, we would include support for `antechamber` in `ambermini`
* Deterministic force and energy computation (necessary for #916)
* faster energy minimizers (#970; #1237) - I have the [FIRE minimizer](https://github.com/pandegroup/openmm/issues/1237#issuecomment-156891381) implemented as a `CustomIntegrator`, but it needs much more testing

**Comment by peastman** [comment]
I think anything in the "less close" or "no idea" categories can wait for 7.1.  How much work remains on the "pretty close" ones?  Any time estimate for them?

**Comment by swails** [comment]
The FF conversion should be measurable in weeks (hopefully a small number of weeks)

**Comment by jchodera** [comment]
I am confident we can finish off the "Pretty close" category in a few weeks.

The one thing I would like to move from "Less close" to "Pretty close" is support for small molecules via `ForceField` and `ffxml`, since we need to tweak `ffxml` a bit more to make this work and it would be too late to do that once we freeze 7.0.  This should be tightly coupled to the decisions we make in how to support the AMBER and CHARMM forcefields anyway.

**Comment by jchodera** [comment]
We're sure this will be 7.0 and not 6.4?

**Comment by rmcgibbo** [comment]
Does the version number matter?

**Comment by jchodera** [comment]
Either it does or it doesn't.

**Comment by jchodera** [comment]
I'm just worried about whether we'll be able to still make more major changes after 7.0 (such as building in better mix-and-match forcefield support) without resistance.

**Comment by peastman** [comment]
Don't worry about that.  The distinction between a change in the first and second digit is purely a matter of marketing.  There's no problem with adding features in either case.

A change in the third digit indicates a bug fix release, but that's another matter.

**Comment by peastman** [comment]
What's the current status of these features?  Extrapolated polarization was the last significant feature I was working for 7.0.  Are we almost ready to release a beta?  Are there any things we should still be waiting for?

**Comment by rmcgibbo** [comment]
I personally would like to see #1320, or something similar, but I've lost the energy to fight over it. :)

**Comment by jchodera** [comment]
On our end, we're finishing up
* Changes to how we protonate residues that coordinate ions (#1176).
* `ForceField` changes to support small molecules and better mix-and-match (#1298), which will likely require
  * deferred processing of atom classes
  * changing `ForceField` to allow later `ffxml` files to override parameters read earlier
* Broad GBSA support for small molecules, etc. (#1311)
* Conversion of latest AMBER and CHARMM forcefields (#1281, #1335, #1054, $685)

We also have a potential bug: #1319 

Are there other things we should clean up now, like:
* nvcc path #1189?
* VariableLangevinIntegrator corner case #981 (a fix will take you a minute)

**Comment by rmcgibbo** [comment]
Do all of those forcefield things need to make it into 7.0?

**Comment by rmcgibbo** [comment]
Also, we should decide what the recommending installation procedure is for users of the application layer who don't compile from source.
 * If it's `conda install...`, then the [relevant parts](https://github.com/pandegroup/openmm/blob/master/docs-source/usersguide/application.rst#installing-openmm) of userguide should be updated.
 * If it's the simtk.org / `install.sh` scheme, then we should either figure out how to fix the GCC 5 CXXABI issue on Linux (https://github.com/pandegroup/openmm/issues/1307#issuecomment-165925356), or update the documentation to say that GCC 5 is not supported for installing from the "pre-compiled" (actually half-compiled) binaries.

Ubuntu 16.04 (LTS) will be released in April with GCC 5 as the system default compiler, so even if the CXXABI issue seems to only affect bleeding-edge platforms right now, a suspect a significant number of people could be affected after the LTS is released.

**Comment by jchodera** [comment]
> Do all of those forcefield things need to make it into 7.0?

If we can make another release as soon as they are ready, no.

If the next release won't be for months, yes.

**Comment by rafwiewiora** [comment]
Re timeline for what I'm working on:

* AMBER --> ffxml conversions (#1281) - finishing up ParmEd scripts, should be good to convert and validate all next week

* `ForceField` changes for how to protonate residues for the multisite ions (#1176) - looking at it and hopefully finishing tomorrow / weekend

So I think a deadline of at least the end of next week would be comfortable.

**Comment by peastman** [comment]
By the way, this is just for the beta.  It's still fine to fix bugs, update documentation, etc. after it goes out.

**Comment by peastman** [comment]
We discussed this at the OpenMM meeting today.  Here's the consensus we reached.

First, 7.0 will not include any of the force field related changes and features.  Instead, we'll plan to follow it pretty quickly (hopefully within a couple of months) with a 7.1 update.  Force field improvements will be the main focus of that release.

Second, we'll update the documentation to recommend conda as the preferred way of installing.  Hopefully we can eventually drop the other installers and have conda installers be the only ones we create.  Before we do that, though, we'll need to wait a few releases and see how conda works for everyone.

Does that all sound ok?

**Comment by rmcgibbo** [comment]
That sounds like the right call to me.

I should not that it appeared from https://github.com/omnia-md/conda-dev-recipes/pull/5 that there are still some significant problems getting conda packages for OpenMM working on Windows w.r.t FFTW.

**Comment by jchodera** [comment]
One more thing I forgot: We had discussed having the ability to turn PME in a separate stream on or off via a `Platform` variable.  If we want to be able to use that in a core 22 release, might be good to put that in now.

**Comment by peastman** [comment]
I'm making the documentation changes and wanted to clarify something.  With the conda installers, do you still need to add the CUDA lib directory to your path?  Or does conda take care of that automatically?

**Comment by rmcgibbo** [comment]
> With the conda installers, do you still need to add the CUDA lib directory to your path?

No. It uses RPATHS to fix up the libraries to point to each other. Only `conda install ...` is necessary.

**Comment by peastman** [comment]
Thanks!

**Comment by rmcgibbo** [comment]
(the `OPENMM_CUDA_COMPILER` env var might still be necessary tho)

**Comment by peastman** [comment]
That shouldn't be needed anymore.  As long the CudaCompiler plugin is being installed, we don't need a separate compiler.  And libnvrtc, which does runtime compilation, is in the CUDA lib directory along with libcufft.

**Comment by rmcgibbo** [comment]
oh, we're upgrading the required cuda to 7.5?

**Comment by peastman** [comment]
Correct.  Although runtime compilation was added in CUDA 7.0, so that doesn't affect this question.

**Comment by jchodera** [comment]
If we're planning to require CUDA 7.5, perhaps now is a good time to first upgrade the `.travis.yml` testing and `openmm-dev` builds to use CUDA 7.5?

**Comment by peastman** [comment]
Sounds good.

**Comment by peastman** [comment]
I'm closing this since we're now at feature complete.
