### ISSUE TITLE
Compiling 7.0 using CUDA 7.5 

### ISSUE THREAD

**Issue by msultan** [pandegroup/openmm#1292]
I have been trying to get the master branch to compile with CUDA 7.5 but I keep running into the following issue with the wrappers. 

```python
 python -m simtk.testInstallation
Failed to import OpenMM packages; OpenMM will not work.
Make sure OpenMM is installed and the library path is set correctly.

Error message: /home/msultan/software/miniconda/lib/python2.7/site-packages/simtk/openmm/_openmm.so: undefined symbol: _ZTVN6OpenMM23CustomCentroidBondForceE

```
The tests are being passed so I think it compiled alright. 
```bash
make test
Running tests...
Test project /home/msultan/software/openmm/build_openmm
        Start   1: TestReferenceRandom
  1/269 Test   #1: TestReferenceRandom ............................   Passed    2.84 sec
        Start   2: TestReferenceBrownianIntegrator
  2/269 Test   #2: TestReferenceBrownianIntegrator ................   Passed    0.22 sec
        Start   3: TestReferenceCompoundIntegrator
  3/269 Test   #3: TestReferenceCompoundIntegrator ................   Passed    0.05 sec
        Start   4: TestReferenceVariableVerletIntegrator
  4/269 Test   #4: TestReferenceVariableVerletIntegrator ..........   Passed    5.13 sec
        Start   5: TestReferenceCustomHbondForce
  5/269 Test   #5: TestReferenceCustomHbondForce ..................   Passed    0.04 sec

```

I have already tried 
1). deleting the ```wrappers``` folder in ```openmm_build``` and running ```make PythonInstall`` a second time around. 
2). Manually removing the simtk folder from the site-packages and remaking the python wrappers 

Doing the same procedure with 6.3 release using CUDA 7.5 doesn't produce this issue.  Any one have any recommendations on what to do ?

**Comment by peastman** [comment]
I would guess that Python is linking to the OpenMM 6.3 library instead of the master branch version.  Do you in fact have two different copies of OpenMM on your computer?  Is one of them in your library path?

**Comment by msultan** [comment]
Yea, deleting the entire build folder and the python site-packages simtk folder seemed to have fixed it. Thanks @peastman!
