### ISSUE TITLE
addHydrogens - action when specified variant can't be prepared

### ISSUE THREAD

**Issue by rafwiewiora** [pandegroup/openmm#1301]
Follow up from our chat with @peastman and @jchodera yesterday. 

Currently: https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/modeller.py#L796

addHydrogens only does a simple check of existing vs expected number of hydrogen atoms bonded to a parent atom. There's no warning or exception if, due to the residue already being in a more 'hydrogen-rich' variant, the variant specified by user cannot be applied. 

HIS is the most worrying case in current behavior, where by running addHydrogens with variant HIE and then running again with variant HID, you will add both HD1 and HE2 hydrogens and achieve a positively charged HIS (HIP). (A more realistic case would be running with None for that residue, then remembering you wanted a particular variant and running with variant 'opposite' to the one automatically chosen in first call). 

I think throwing an exception here would be a good idea. 

- The easiest way seems to:

   Add an else to this if:
 https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/modeller.py#L713

 that will do checks for each possible residue with variants analogical to this check for HIS:
https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/modeller.py#L729-L736

   and throw an exception for cases where achieving this variant won't be possible. 

- Alternatively, to avoid hard-coding checks for all residues with possible variants we could, in addition to `actualVariants`, have another list `userVariants` and add an `elif len(existing) > len(expected):` to this if: https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/modeller.py#L796
 that will throw an exception if this residue's variant is not None in `userVariants`. We also need to repeat the check for HIS though as an else to the `if variant is None:` to avoid the HIS-catastrophy as I described above. 

On a separate note, is there a need for `deleteHydrogens` function? I imagine the exception would direct the user to run deleteHydrogens, followed by repeating addHydrogens?

**Comment by rafwiewiora** [comment]
Just refreshing this, what do you think - @peastman @jchodera ?

**Comment by peastman** [comment]
Sorry for the delay.  I guess there are three possible actions when there are existing hydrogens not in the variant:

1. Ignore them and add any additional hydrogens (the current behavior).
2. Throw an exception.
3. Delete them, so that you get the desired variant.

Any thoughts on which of those would be best?

**Comment by rafwiewiora** [comment]
No worries! I think 1 is least preferable because of the problems as I described above.

 I like 3 most, because a function that adjust protons to a particular state seems to me more useful than a function that can only add hydrogens. This would also be the best option for the changes for adjusting protonation changes for the multisite metal ion models. 

But I do appreciate that that would be a big conceptual shift for what addHydrogen is.

**Comment by peastman** [comment]
In principle I have no objection to it behaving that way.  I only worry about whether changing the behavior would cause problems for anyone.

To be honest, I didn't have any good reason for picking that behavior originally.  It just needed to do *something* in that case, so I picked that as the minimalist thing to do.  I have trouble thinking of situations where someone would actually be relying on that behavior.  But maybe one of you can think of cases?

**Comment by rafwiewiora** [comment]
I can't think of any case where changing the behavior from 1 --> 2 would change the behavior in existing people's scripts.

I assume here that hydrogens present in the topology will still take precedence before say the hydrogen bond estimation rules in the code for HIS - i.e. if one runs addHydrogens on a topology containing a HIS with protons in a HIE variant and the code would determine you should have an HID there, the HIE will remain. That's something I would wonder if I heard about the new behavior, so we should make sure it's clear in the docs. 

So really we'll be maintaining current behavior + fixing situations where the behavior might have been wrong / weird in the past. I guess someone could've had a script where they had some first HID, then HIE magic and they knew that was giving them HIP - which would now change, but that's a weird lifestyle choice...

**Comment by jchodera** [comment]
> In principle I have no objection to it behaving that way. I only worry about whether changing the behavior would cause problems for anyone.

I'm with @rafwiewiora on this one: If changing behavior to option 3 impacts anyone, they were getting wrong answers anyway, so this is just "fixing" broken behavior.

**Comment by peastman** [comment]
Just to make sure we're completely clear, is the following what you're proposing?

- If the user *does not* specify a variant, it will continue to work exactly as it does now.  That is, it will never remove a hydrogen that was already there.

- If the user explicitly specifies a variant, and a hydrogen is present that is not part of that variant, it will be removed.

If that's what you're saying, I think it sounds like a reasonable behavior.

**Comment by rafwiewiora** [comment]
That's exactly right. Will you work on it together with the changes for the metal ions or do you want me to have a go?

**Comment by peastman** [comment]
Either way.  I can do it, but it may be a few days before I can get to it.

**Comment by rafwiewiora** [comment]
Ok, same here so let's see who can do it first.

**Comment by peastman** [comment]
I can do this now that I'm finished with extrapolated polarization.  I'll try to get a PR in today or tomorrow.
