### ISSUE TITLE
Can NonbondedForce cutoff be updated without recreating Context?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1304]
We don't have a shortcut to updating the nonbonded cutoff of a `NonbondedForce` inside a `Context` without reinitializing/recreating the whole `Context`, do we?

**Comment by peastman** [comment]
No.  The cutoff distance gets hardcoded into kernels, so changing it requires recompiling them.

**Comment by swails** [comment]
Is this being left open as a feature request, or can it be closed?

FWIW, I think the current behavior is reasonable -- the cutoff affects the potential energy function (unless we start doing PME with L-J as well), and there are performance implications to naively turning this from a preprocessor define evaluated at kernel creation time to a variable used in a conditional that can be changed.

You can probably also accomplish the same thing using multiple NonbondedForce objects with different groups and cutoffs, and changing what groups the integrator uses within a Context (I think that can be done?)

**Comment by jchodera** [comment]
Closing.
