### ISSUE TITLE
Release 6.3.1

### ISSUE THREAD

**Issue by peastman** [pandegroup/openmm#1307]
I've created the 6.3.1 release on simtk.org.  It's currently hidden, so click the "List all hidden releases" link to see it.  Any help testing it would be appreciated!  At a minimum, we need to verify that each one installs correctly and that `testInstallation` works.

**Comment by rmcgibbo** [comment]
I tested `OpenMM-6.3.1-Mac.zip` with Python 3.5.1 on my MBP (no CUDA GPU), and everything worked. I also tested `OpenMM-6.3.1-Linux.zip` with Python 3.5.1 on Ubuntu 15.10 (gcc 5.2.1) and had a problem.

After installing, I see

```
rmcgibbo@vspm9  ~/OpenMM-6.3.0-Linux (test)
$ python -m simtk.testInstallation
Traceback (most recent call last):
  File "/home/rmcgibbo/miniconda/envs/test/lib/python3.5/site-packages/simtk/testInstallation.py", line 111, in <module>
    run_tests()
  File "/home/rmcgibbo/miniconda/envs/test/lib/python3.5/site-packages/simtk/testInstallation.py", line 29, in new_func
    func(*args, **kwargs)
  File "/home/rmcgibbo/miniconda/envs/test/lib/python3.5/site-packages/simtk/testInstallation.py", line 56, in run_tests
    '\n\nError message: %s' % simtk_import_error)
__main__.TestingError: Failed to import OpenMM packages; OpenMM will not work.
Make sure OpenMM is installed and the library path is set correctly.

Error message: /home/rmcgibbo/miniconda/envs/test/lib/python3.5/site-packages/simtk/openmm/_openmm.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZNK6OpenMM18CustomTorsionForce17getEnergyFunctionB5cxx11Ev

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rmcgibbo/miniconda/envs/test/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/rmcgibbo/miniconda/envs/test/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rmcgibbo/miniconda/envs/test/lib/python3.5/site-packages/simtk/testInstallation.py", line 113, in <module>
    print(err.message)
AttributeError: 'TestingError' object has no attribute 'message'
```

The undefined symbol is is
```
$ c++filt _ZNK6OpenMM18CustomTorsionForce17getEnergyFunctionB5cxx11Ev
OpenMM::CustomTorsionForce::getEnergyFunction[abi:cxx11]() const
```

I first figured that I must be linked to an older version of OpenMM that's on this machine, but that does not appear to be the case from `ldd`

```
$ ldd /home/rmcgibbo/miniconda/envs/test/lib/python3.5/site-packages/simtk/openmm/_openmm.cpython-35m-x86_64-linux-gnu.so
	linux-vdso.so.1 =>  (0x00007ffeabdee000)
	libOpenMM.so => /home/rmcgibbo/miniconda/envs/test/lib/libOpenMM.so (0x00007f6e80423000)
	libOpenMMAmoeba.so => /home/rmcgibbo/miniconda/envs/test/lib/libOpenMMAmoeba.so (0x00007f6e801c2000)
	libOpenMMRPMD.so => /home/rmcgibbo/miniconda/envs/test/lib/libOpenMMRPMD.so (0x00007f6e7ffb5000)
	libOpenMMDrude.so => /home/rmcgibbo/miniconda/envs/test/lib/libOpenMMDrude.so (0x00007f6e7fda5000)
	libpython3.5m.so.1.0 => /home/rmcgibbo/miniconda/envs/test/lib/libpython3.5m.so.1.0 (0x00007f6e7f8b6000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6e7f506000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6e7f1fe000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6e7efe7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6e7edc8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6e7e9fe000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f6e7e7f6000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6e7e5f1000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f6e7e3ee000)
	/lib64/ld-linux-x86-64.so.2 (0x000055e8ee59b000)
```

When I look for that symbol, I see
```
$ nm /home/rmcgibbo/miniconda/envs/test/lib/libOpenMM.so | grep  CustomTorsionForce17getEnergyFunction | awk '{print $3}' | c++filt
OpenMM::CustomTorsionForce::getEnergyFunction() const
```

So it looks like there's some C++11 ABI mismatch?

**Comment by peastman** [comment]
What if you run the OpenMM 6.3 installer on that machine?  Does it work?  In other words, is this something that changed between 6.3 and 6.3.1?

**Comment by rmcgibbo** [comment]
Same issue with both 6.3 and 6.3.1.

**Comment by jchodera** [comment]
Is this a problem with the vagrant VM we are using to build this?

Perhaps we should switch over to the [`https://hub.docker.com/r/rmcgibbo/centos5-build-box/` docker image](https://hub.docker.com/r/rmcgibbo/centos5-build-box/) that you are using to build the `conda` packages?  I can certainly do that on our Jenkins system if you'd like, but I wonder if this means we should just add a `.travis.yml` branch to do this.

**Comment by peastman** [comment]
If this problem was present in 6.3, the fix can probably wait until 7.0.  I haven't heard of anyone else reporting it.

**Comment by rmcgibbo** [comment]
No, it's not an issue with your Jenkins config. It's a more fundamental issue with a c++ ABI break in gcc 5.1.

**Comment by rmcgibbo** [comment]
http://developerblog.redhat.com/2015/02/05/gcc5-and-the-c11-abi/

**Comment by rmcgibbo** [comment]
The implication is that having install.sh pass `-D_GLIBCXX_USE_CXX11_ABI=0` to the compiler used by distutils would fix this.

In practice, I don't know if this matters much -- it's only relevant for users of the precompiled linux binaries (but not the conda packages, they are not affected) on a system with gcc >= 5.1 (Ubuntu 15.10, Fedora 23, or similar).

**Comment by mpharrigan** [comment]
I don't get it. Wasn't this built with gcc < 5 so it should work with new libcxx ?

Are the distutils compilers doing the wrong abi when installing the python extension?

**Comment by rmcgibbo** [comment]
The problem isn't libstdc++, it's that the libraries that Peter built use the old c++ ABI, and when I run install.sh, it compiled the python wrapper using the new ABI, because that's now the default.

Essentially, we ship the "pre-compiled" installer only half-compiled, in the sense that the swigged python exentsion is still in source form. Having this work requires that g++ doesn't change ABI between version used to compile the library and the version used to compile the extension, which has now happened :(

**Comment by peastman** [comment]
Has anyone else tested this?  We still need to confirm the Windows version works, and also that the Linux version works on systems that 6.3 worked on.

**Comment by jchodera** [comment]
The linux installer worked fine for me on am Ubuntu 12.04.5 LTS installation with CUDA 7.0.

**Comment by rmcgibbo** [comment]
I tested the linux in a 12.04 docker container, and it worked fine.

**Comment by peastman** [comment]
So we just need to check the Windows version.  Can anyone do that?

**Comment by rmcgibbo** [comment]
I booted up my windows partition, and got an error with 6.3.1.

```
PS C:\Users\rmcgibbo> python -m simtk.testInstallation
Traceback (most recent call last):
  File "C:\Users\rmcgibbo\Miniconda3\lib\site-packages\simtk\testInstallation.py", line 111, in <module>
    run_tests()
  File "C:\Users\rmcgibbo\Miniconda3\lib\site-packages\simtk\testInstallation.py", line 29, in new_func
    func(*args, **kwargs)
  File "C:\Users\rmcgibbo\Miniconda3\lib\site-packages\simtk\testInstallation.py", line 56, in run_tests
    '\n\nError message: %s' % simtk_import_error)
__main__.TestingError: Failed to import OpenMM packages; OpenMM will not work.
Make sure OpenMM is installed and the library path is set correctly.

Error message: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rmcgibbo\Miniconda3\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\rmcgibbo\Miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\rmcgibbo\Miniconda3\lib\site-packages\simtk\testInstallation.py", line 113, in <module>
    print(err.message)
AttributeError: 'TestingError' object has no attribute 'message'
```

**Comment by rmcgibbo** [comment]
```
PS C:\Users\rmcgibbo> cat C:\users\rmcgibbo\miniconda3\lib\site-packages\simtk\openmm\version.py

# THIS FILE IS GENERATED FROM OPENMM SETUP.PY
short_version = '6.3.1'
version = '6.3.1'
full_version = '6.3.1.dev-Unknown'
git_revision = 'Unknown'
release = False
openmm_library_path = r'C:\Users\peastman\openmm-install\lib'

if not release:
    version = full_version
```

**Comment by rmcgibbo** [comment]
(This was using the Python 3.4 installer.)

**Comment by rmcgibbo** [comment]
If I patch `version.py` to point to the proper place (e.g. `C:\Program Files\OpenMM\lib` as instructed in the user manual, after manually copying the files there), then everything works correctly:

```
There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Successfully computed forces
4 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 1.99952e-06
Reference vs. CUDA: 2.1541e-05
CPU vs. CUDA: 2.1383e-05
Reference vs. OpenCL: 2.15404e-05
CPU vs. OpenCL: 2.13838e-05
CUDA vs. OpenCL: 1.51672e-07
```

**Comment by rmcgibbo** [comment]
I realize we haven't done it this way in the past, but I think it would be preferable going forward if we changed the Python installation setup such that all the files were installed directly into `<python/lib/site-packages/simtk/etc...`, so that libOpenMM.{dll,so,dylib} and company were directly adjacent to `openmm.py` and the swig-generated `_openmm.{so,pyd}`.

This would be instead of installing the C++ library to `C:\ProgramFiles\OpenMM` or `/usr/local/openmm` (or whatever CMAKE_INSTALL_PREFIX is).

It would eliminate the need for a lot of the tricky OS X `@rpath` logic and Windows PATH logic, and make installing OpenMM the same as installing any other Python package (e.g. our package installation/distribution mechanism should be just `{pip,conda} install openmm`, not "download this file and extract the zip file, manually copy some files to `C:\Program Files`, etc...)

**Comment by rmcgibbo** [comment]
Ummm, I think this is also the case with the 6.3.0 installer

**Comment by peastman** [comment]
New version of the Windows installer posted that hopefully fixes the problem.

**Comment by rmcgibbo** [comment]
Confirmed. Works now.

(Although it will still be the case that if you forget to copy the libraries to `C:\Program Files\OpenMM`, or use a different path, you'll get the same "DLL Load failed" error, but we can improve that behavior later.)

**Comment by peastman** [comment]
Ok, thanks!  Everyone ok with making 6.3.1 public now?

**Comment by rmcgibbo** [comment]
+1 from me.

**Comment by jchodera** [comment]
+1

Who wants to update the [conda recipe](https://github.com/omnia-md/conda-recipes/blob/master/openmm/meta.yaml)?

**Comment by jchodera** [comment]
@peastman: Can you also [cut a new release on GitHub](https://github.com/pandegroup/openmm/releases)?

**Comment by peastman** [comment]
Releases on both simtk.org and github are now public.

**Comment by jchodera** [comment]
Thanks!

It might be useful to edit the release description to be a bit more specific.  As I recall, this bug could *only* occur with PME, and only on NVIDIA hardware.  Is that right?

**Comment by peastman** [comment]
Correct.  I included a link to the PR that gives lots of details about it.
