### ISSUE TITLE
Travis build timing out

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1315]
Now, after the fix from #1314, one of the travis builds is timing out due to no output received:
https://travis-ci.org/pandegroup/openmm/builds/99777387

Specifically, [`TestOpenCLAndersenThermostatSingle`](https://travis-ci.org/pandegroup/openmm/jobs/99777388#L1088-L1094) seems to be timing out:
```
 93/134 Test  #93: TestOpenCLCustomIntegratorDouble ................   Passed  141.44 sec
        Start  94: TestOpenCLAndersenThermostatSingle
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

**Comment by jchodera** [comment]
From reading [this blog post](https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future) in more detail, the best option might be to have @peastman (or whoever's account is running Travis) email travis-ci to opt in to the older Blue Box system.

**Comment by rmcgibbo** [comment]
I think you can tell ctest about the timeout so it'll skip the test if it goes for too long, no?

**Comment by jchodera** [comment]
Good point. Maybe this flag?
>* --timeout <seconds>*: Set a global timeout on all tests.
> This option will set a global timeout on all tests that do not already
have a timeout set on them.

https://cmake.org/cmake/help/v2.8.8/ctest.html

**Comment by jchodera** [comment]
There seems to be an issue with [the whole set of tests timing out](https://travis-ci.org/pandegroup/openmm/jobs/99882075#L1118) for OpenCL on Linux:
```
The job exceeded the maxmimum time limit for jobs, and has been terminated.
```
I thought the tests were supposed to be limited to 25 min of wall clock time, so I'm a bit confused as to how the whole job is timing out.

**Comment by rmcgibbo** [comment]
I wouldn't worry about it too much. Might need to play around with some of the settings like the timeout, or the number of tests to run in parallel (`-j`), etc.

**Comment by jchodera** [comment]
Taking a quick stab at it in #1316, but may need your help, @rmcgibbo.

I do wonder if [those OpenCL failures](https://github.com/pandegroup/openmm/pull/1312#issuecomment-168438851) could possibly be real.

**Comment by jchodera** [comment]
Seems like we're good again.
