### ISSUE TITLE
Possible CPU OpenCL errors on Travis-CI

### ISSUE THREAD

**Issue by rmcgibbo** [pandegroup/openmm#1319]
There may be a couple CPU OpenCL errors on Travis. They may have arisen with their [move to new infrastructure](https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future), or not.

- https://travis-ci.org/pandegroup/openmm/jobs/100031954#L979-L985
- https://travis-ci.org/pandegroup/openmm/jobs/99979017#L1078
- https://travis-ci.org/pandegroup/openmm/jobs/99990558#L1079

The apparent errors are segfaults in `TestOpenCLCustomManyParticleForce`.

I previously tried, but was unable to reproduce the bug on my machine, either in Ubuntu 15.04 or in a 12.04 container, using the CPU OpenCL platform (AMD drivers). So, ¯\_(ツ)_/¯.

cc: https://github.com/pandegroup/openmm/pull/1317#issuecomment-168567674, https://github.com/pandegroup/openmm/issues/1315#issuecomment-168448636, https://github.com/pandegroup/openmm/pull/1312#issuecomment-168438851

**Comment by rmcgibbo** [comment]
It doesn't always segfault. [Here](https://travis-ci.org/pandegroup/openmm/jobs/100437216), it segfaulted once and then failed an assertion in `TestCustomManyParticleForce:testCentralParticleModeLargeSystem` the second time.

```
16/134 Test  #77: TestOpenCLCustomManyParticleForceMixed ..........***Exception: SegFault 22.71 sec
[...]

******************************
Rerunning failing tests...
******************************
Test project /home/travis/build/pandegroup/openmm
    Start 77: TestOpenCLCustomManyParticleForceMixed
1/1 Test #77: TestOpenCLCustomManyParticleForceMixed ...***Failed   24.50 sec
exception: Assertion failure at TestCustomManyParticleForce.h:705.  Expected 107521, found 2.8418e+06
```

**Comment by jchodera** [comment]
I'm still seeing these failures (e.g. [here](https://travis-ci.org/pandegroup/openmm/jobs/107378907#L1015-L1021)).  

Before we release 7.0, I think it is essential that we debug this (if it is a bug) or disable that OpenCL kernel on OpenCL implementations we think are buggy.

**Comment by rmcgibbo** [comment]
I think Peter was pretty well convinced it was a driver bug. I tried to upgrade the driver on trusty in one PR, but ran into some different issues that I didn't know how to fix, but that might be a place to build from.

**Comment by rmcgibbo** [comment]
(CC #1378)

**Comment by jchodera** [comment]
Is this now resolved by https://github.com/peastman/openmm/commit/a7ce5784bc1d728ef7088c10308fa61b9c87e1a9
