### ISSUE TITLE
Amoeba simulations crashing on GTX 980 Ti in single precision

### ISSUE THREAD

**Issue by swails** [pandegroup/openmm#1323]
[I've put the files you can download on dropbox](https://www.dropbox.com/s/qwu3y79awhy8efb/4yula_amoeba.tgz?dl=0)

You need ParmEd installed, and you can run the script via the command `./run.sh`.  What I've observed so far:

- On a GTX 980 Ti in the default (single) precision, within 0-3k steps, the simulation flounces off to NaNdyland and never comes back. Before crashing, simulation looks "normal"
- Using mixed precision fixes the problem.  I have not checked double yet (running now).
- Problem occurs on every GTX 980 Ti we've tried (we have a box with 8 of them)
- Problem does not occur on the GTX 980, GTX 780, and GTX 680 cards we have
- Problem does not occur if we use the exact same coordinates/PDB, but use a system.xml file built with amber99sbildn instead of amoeba13.

**Comment by peastman** [comment]
Very strange.  I don't have a GTX 980 Ti to test it on.  I do have a Titan X, which is architecturally very similar, so I'll see if I can reproduce it on there.

**Comment by swails** [comment]
It wouldn't surprise me if it worked fine on the Titan X (after all, it worked on the 980 just fine -- is the Titan X closer to the 980 Ti than the 980 is?)

If you can't repro the issue on the Titan X, I'll talk to Dave about getting you access to our 8xGTX980Ti machine for you to repro.  A few other potentially helpful clues:

- Double precision works fine, albeit slow as molasses
- This is a crystal simulation, so there is an abnormally high ratio of protein:water atoms.  Dave tells me the same system in a water box works fine on the GTX 980 Ti, but I haven't checked it myself.

**Comment by peastman** [comment]
I *think* the 980 Ti is nearly identical to the Titan X, just with slightly fewer compute units.  I'll try it today and let you know.

**Comment by swails** [comment]
> I'll try it today and let you know.

Sounds good.  We can give you access to our machine with GTX 980 Ti's if you can't repro on the Titan X.  Thanks!

**Comment by peastman** [comment]
I've reproduced it on Titan X.  In single precision mode, it generally blows up within 1000 steps.  In mixed precision, it runs fine.  I'm investigating...

**Comment by swails** [comment]
Sweet, I'll let you work your magic.

**Comment by peastman** [comment]
I think I've identified the problem.  It's in AmoebaTorsionTorsionForce.  It's computing the angle with acos(), which has singularities at 0 and pi.  The other torsion forces check when you're getting close to one of them, and switch over to asin() instead.  But this one isn't doing that.

It should hopefully be pretty easy to fix.

**Comment by swails** [comment]
The explanation makes a lot of sense based on what we were observing.  I'd naively expect this to be more prevalent in single precision, and there are a lot more torsion-torsion terms in a xtal simulation which would increase the likelihood of this happening.

Thanks for hunting this down.  I'll let you know if it fixes things on our end after you push the fix.

**Comment by mpharrigan** [comment]
Why would this be so hardware-dependent ?

**Comment by swails** [comment]
> Why would this be so hardware-dependent ?

:)

**Comment by swails** [comment]
\*insert that weird utf-8 shruggy thing @rmcgibbo does sometimes\*

**Comment by peastman** [comment]
Basically!  Maybe a change in how they implemented the acos() function?  This error should be possible on any GPU, but rare on all of them.  I don't know why this particular case seems to trigger it much more often on some GPUs than others.

**Comment by jchodera** [comment]
[This paper](http://onlinelibrary.wiley.com/doi/10.1002/jcc.540130508/abstract) by Bill Swope on robust methods for computing torsion potentials seems relevant.

**Comment by swails** [comment]
The torsion-torsion (and CMAP) potentials are based on interpolated grids, though, not a closed analytical form that can be easily expressed and manipulated as cosines.  Admittedly my glance at the paper was quick, but I didn't immediately see that their discussion extended to this scenario.

**Comment by jchodera** [comment]
Ah, OK.  The AMOEBA and CMAP work certainly came far after this paper.
