### ISSUE TITLE
How do I specify multiple OpenCL include directories?

### ISSUE THREAD

**Issue by swails** [pandegroup/openmm#1329]
On one of the supercomputers I'm trying to build OpenMM on, the necessary OpenCL header files are in two separate locations.  The `CL/` include subdirectory is found in `/opt/sw/packages/cuda/6.5/lib64`, while the `GL/` include subdirectory is *only* found in `/opt/sw/packages/cuda/6.5/extras/CUPTI/include`.  All of the other machines I use OpenMM on has these include directories inside `/usr/include`, so I don't have to go hunting around for it.

I don't know CMake that well, so I don't know how to actually get OpenMM to search *both* directories for the needed includes -- I can do one or the other but then I get complaints about the location I didn't add.

I've temporarily worked around this by just disabling the whole OCL platform, but I'd rather find a solution that someone new to OpenMM can "just do".

**Comment by peastman** [comment]
Try listing both directories in OPENCL_INCLUDE_DIR, with a space between them.  I don't know if that will work, but it seems like it might.  The value you enter there is just passed to INCLUDE_DIRECTORIES: https://cmake.org/cmake/help/v3.0/command/include_directories.html.

**Comment by swails** [comment]
I tried that, doesn't work.

**Comment by rmcgibbo** [comment]
How about setting the compiler to `gcc -I/path/to/second/include/directory'`?

**Comment by rmcgibbo** [comment]
Or passing the `-I` in a CXX_RELEASE_FLAGS, or similar?

**Comment by mpharrigan** [comment]
If we're suggesting hacky solutions, you could always make a new directory with two symlinks to `CL` and `GL` :)

**Comment by swails** [comment]
I don't have root privileges on this machine.  It's a supercomputer...

**Comment by rmcgibbo** [comment]
No need for root. It could be in your home directory.

**Comment by swails** [comment]
I tried the symlink trick, too, and no dice (since I don't think any place I have write permissions is in the default include path).

I could try adding -I/path/to/include to gcc, though.  I hadn't thought of that.  That should probably work, although since I'm just using Amoeba for the time being OCL is not critical.

**Comment by mpharrigan** [comment]
Make a directory with two symlinks and set it as OPENCL_INCLUDE_DIR

**Comment by mpharrigan** [comment]
(I've used the symlink trick before with amdappsdk (which doesn't include GL) and it worked)

**Comment by swails** [comment]
That could work, too. Yuck, though :)

**Comment by rmcgibbo** [comment]
Oh, I know.

**Comment by rmcgibbo** [comment]
> Try listing both directories in OPENCL_INCLUDE_DIR, with a space between them. I don't know if that will work, but it seems like it might.

This was almost right. But the separator should be a semicolon, not a space.

**Comment by swails** [comment]
> This was almost right. But the separator should be a semicolon, not a space.

Oh!  I tried both a space and a colon...  Good thing to know.

**Comment by rmcgibbo** [comment]
Semicolon is the PATH separator on Windows... CMake, in being cross-platform, I guess takes the "best" features from each platform?

**Comment by rmcgibbo** [comment]
You can probably close this.

**Comment by swails** [comment]
Sure can.
