### ISSUE TITLE
OS X py27 dev conda package missing? 

### ISSUE THREAD

**Issue by rafwiewiora** [pandegroup/openmm#1330]
Has there been some Python 2 deprecation for dev I missed? No OS X py27 package on conda. Very much regretting that `conda remove` now...

**Comment by rafwiewiora** [comment]
Same for Linux.

**Comment by jchodera** [comment]
Things are broken. 

Working on it https://github.com/pandegroup/openmm/pull/1328

**Comment by rafwiewiora** [comment]
Ah ok!

**Comment by jchodera** [comment]
The good news is that these packages are now being uploaded by this repo:
https://github.com/omnia-md/conda-dev-recipes

The bad news is that the old packages aren't being deleted...

**Comment by jchodera** [comment]
Can you close this, @rafwiewiora?

**Comment by rafwiewiora** [comment]
Ok great, at least I can reinstall a dev on my laptop now! Closing.
