### ISSUE TITLE
Is there a way to decompose PeriodicTorsionForce into Proper and Improper contributions? 

### ISSUE THREAD

**Issue by rafwiewiora** [pandegroup/openmm#1346]
Came up in force field conversion testing in https://github.com/ParmEd/ParmEd/issues/486. 

Is it possible to decompose the PeriodicTorsionForce force group into proper and improper torsions, in getting these from a Context?

**Comment by swails** [comment]
This has to be done from the client application (ParmEd in this case) by using different forces for the propers and impropers. Then you can assign each to a different force group and decompose it that way. 

But the force itself has no way to know which is proper and improper. So there no way to decompose within a single force object.

**Comment by rafwiewiora** [comment]
Ok, answered here and @swails will work on it in ParmEd - closing.
