### ISSUE TITLE
Error launching CUDA compiler

### ISSUE THREAD

**Issue by dr-nate** [pandegroup/openmm#1352]
I just got this error for jobs running on Xstream:

```
# Loading Input files...
# Creating OpenMM System
Traceback (most recent call last):
  File "openmm.py", line 98, in <module>
    simulation = app.Simulation(parm.topology, system, integrator, platform, prop)
  File "/home/stanford/pande/users/natehs/anaconda/lib/python3.5/site-packages/simtk/openmm/app/simulation.py", line 88, in __init__
    self.context = mm.Context(system, integrator, platform, platformProperties)
  File "/home/stanford/pande/users/natehs/anaconda/lib/python3.5/site-packages/simtk/openmm/openmm.py", line 13878, in __init__
    this = _openmm.new_Context(*args)
Exception: Error launching CUDA compiler: 32512
sh: /usr/local/cuda/bin/nvcc: No such file or directory
```

I think I have the absolute latest build (built this morning, now regretting updating). Is the code set up to use the CUDA_HOME environment variable? I've tried running interactively and it's set, so that shouldn't be the problem. Any clues? Am I missing something?

**Comment by peastman** [comment]
Add the following to your bashrc:

```
export OPENMM_CUDA_COMPILER=/global/software/Core/CUDA/7.5.18/bin/nvcc
```

If you're using CUDA 7.0, the path will be slightly different.

**Comment by dr-nate** [comment]
Ok, thanks. That fixed it.

**Comment by dr-nate** [comment]
I spoke too soon. I am now getting another strange error:

```
python: /anaconda/conda-bld/work/libraries/quern/src/quern_factorization.cpp:88: bool apply_givens(SparseVector&, SparseVector&, int, double&, double&): Assertion `!y.empty() && y.front().index==diagonal && y.front().value' failed.
Aborted
```
I get this with both 6.3.1 and 7.0.0. :-/.  When I search for quern_factorization.cpp, among others issue #217 comes up. Not sure it that's relevant.

**Comment by peastman** [comment]
Never seen that before!  That's an assertion failure (I take it you built in debug mode?) in the library used to factor the constraint matrix.  What set of constraints do you have in your system?

**Comment by dr-nate** [comment]
I'm using the version straight from anaconda.org (conda install -c https://conda.anaconda.org/omnia openmm-dev).  I have the "AllBonds" constraint set. Does this mean there are bonds that are too long or something similar?

**Comment by peastman** [comment]
That line is a C++ assert, which should be ignored in release mode.  Are the conda binaries somehow getting compiled in debug mode?

I don't know what the assertion means, or whether it's an actual problem.  That function is inside the QR decomposition routine, and the vector it's complaining about is one that gets created internally, not something passed in from outside.  Could you post the files needed to reproduce this?

**Comment by dr-nate** [comment]
I have never compiled from source on Xstream, so it must be from the conda binaries. 

Ok. I can't post the files, unfortunately, but I'll email them to you.

**Comment by jchodera** [comment]
Do we explicitly have to set a release mode flag for the conda build?

https://github.com/omnia-md/conda-recipes/blob/master/openmm/build.sh

**Comment by peastman** [comment]
I thought `Release` was the default value for `CMAKE_BUILD_TYPE`.  I just looked up the documentation, though, and it doesn't say anything about a default value.

**Comment by jchodera** [comment]
Sorry about that---I guess I missed that too.

Created a PR to update the `openmm` release packages to `Release` mode: https://github.com/omnia-md/conda-recipes/pull/420

**Comment by jchodera** [comment]
The [`openmm-dev` conda package](https://anaconda.org/omnia/openmm-dev) should still be built in `Debug` mode, right?

**Comment by peastman** [comment]
I don't think so.  Just because someone wants the latest development code, that doesn't mean they want it to run slowly.  Also, we don't support debug binaries on Windows.

**Comment by jchodera** [comment]
OK, fixing that here!
https://github.com/omnia-md/conda-dev-recipes/pull/10

**Comment by dr-nate** [comment]
I think I discovered the problem resulting in the subsequent "strange error". I was testing against NAMD, and I found that it also failed with the equilibrated input files that came from OpenMM. However, if I increased the box size by 1Å in all directions, there was no problem. Same for OpenMM. Increasing by 0.01Å or 0.1Å  (i.e. enough for floating point issues to go away, but perhaps not enough for legitimate volume issues) was not sufficient.

The box size in the files I've used was the instantaneous box size at the end of the simulation. I write them out at the end of the simulation like so:

```
positions = simulation.context.getState(getPositions=True).getPositions()
app.PDBFile.writeFile(parm.topology, positions, open('output.pdb', 'w'))
```
Could this be arising because the coordinates are not wrapped into the box every step (in this case, before writing)? Or because the instantaneous box size is too small and causing extreme pressure, whereas average box size over the last 1000 steps or so would be more accurate?

**Comment by peastman** [comment]
Probably your box is just too small.  Wrapping coordinates shouldn't matter.  Forces are always computed based on the nearest periodic copy, so translating a molecule by a box vector doesn't affect the forces.

**Comment by dr-nate** [comment]
Ok, but then that means OpenMM is writing too small a box after equilibration. This was with MonteCarlo barostat.

**Comment by peastman** [comment]
It's writing whatever the box size was at the end of your equilibration.  I don't know why it happened to be so unstable.  Perhaps something to do with how you did the equilibration?

**Comment by jchodera** [comment]
Conda packages `openmm` and `openmm-dev` now are built in `Release` mode.
