### ISSUE TITLE
Update .travis.yml and openmm-dev builds to use CUDA 7.5

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1357]
Buried in #1352 is the suggestion that OpenMM 7.0 will use CUDA 7.5.

We should first update `.travis.yml` and the `openmm-dev` build environments in https://github.com/omnia-md/conda-dev-recipes to use CUDA 7.5.

**Comment by jchodera** [comment]
Working on `.travis.yml` in #1358.

Updating `conda-dev-recipes` and our `conda-recipes` build systems to use CUDA 7.5 seems like it will be much harder:
* NVIDIA has changed where they hide the `osx` network install files
* We will need to update the `Dockerfile` build scripts for `rmcgibbo/centos5-build-box` to use CUDA 7.5.  Given how hard it was to get 7.0 on there, it may take some tinkering.

**Comment by jchodera** [comment]
OK, `.travis.yml` has been upgraded in #1358.

What about updating which version of the AMD APP SDK we use?  We're currently on 2.9.1 for building conda packages---should that be updated to 3.0?

**Comment by peastman** [comment]
Sure, that would be reasonable.

**Comment by jchodera** [comment]
I think I've done this now.  conda packages rebuilding.
