### ISSUE TITLE
Changes to XML reading by ForceField for new Amber ffxml format

### ISSUE THREAD

**Issue by rafwiewiora** [pandegroup/openmm#1371]
I'm summarizing here for @peastman (and tagging @jchodera @swails) what needs to be done for the new Amber ffxml format to work:

from https://github.com/ParmEd/ParmEd/issues/486 and https://github.com/pandegroup/openmm/issues/1344 we have:

* for solving the problem that if parameters and residue templates are in separate files, parameters have to be passed to ForceField first in the file list: I'm thinking if there's more than one file, just parse them all, combine all roots into a list and then iterate over the roots - first for AtomTypes, then Residues, then Forces. Sounds good? 

* for making a meta / master ffxml file: is it easiest to solve it through forcefield.py code rather than XML tools? I'm thinking allow such structure for the master file:
``` xml
<MasterForceField>
 <ForceField href="ff99SBildn_params.xml"/>
 <ForceField href="ff99SBildn_protein.xml"/>
 <ForceField href="ff99SBildn_nucleic.xml"/>
</MasterForceField>
```

And you just pass the list of files to the code from the point above?

**Comment by rafwiewiora** [comment]
Maybe better to have `<ForceFieldFile href="..."/>` elements to avoid potential bugs with the element having the same name as the normal root.

**Comment by rafwiewiora** [comment]
https://github.com/pandegroup/openmm/pull/1373 fixed first point

**Comment by jchodera** [comment]
If we don't want to have to change the XML reader again, having something like
```XML
<ForceFieldFile href="...."/>
```
where `href` might actually be a URL on the internet (!!!) would work.  Alternatively, we might just call it `<include filename="..."/>`.

**Comment by rafwiewiora** [comment]
> where href might actually be a URL on the internet (!!!) would work

It's a neat idea! 

I'm gonna write some code for this, then let's settle on the naming of tags etc.

**Comment by rafwiewiora** [comment]
This is pretty much dead, because we decided for a different conversion approach. Closing.
