### ISSUE TITLE
AMOEBA simulations still crash

### ISSUE THREAD

**Issue by swails** [pandegroup/openmm#1375]
I'm still seeing periodic, although rare, crashes of AMOEBA simulations.  While it used to happen every few minutes before #1327, it now happens maybe once every day or two, give or take.  We're currently running the code on ~3-5 different systems, and the only system where it *never* fails only has ~6500 atoms (run out ~250 ns so far).  The others have substantially more (~15-20K) (which also means that it crashes within 5 ns or so fairly reliably).

Here's a repro case: https://www.dropbox.com/s/4o8i1j1vnlkzmin/amoeba_crash_repro.tgz?dl=0

It depends on having ParmEd installed, and uses a script I wrote and put on Github: https://github.com/apes-soft/OMM_Amoeba_Scripts/blob/master/runmd.py.

I'd like to help in the diagnosis here, so if you have any code you think might help me with this, let me know and I'll try it out.

**Comment by peastman** [comment]
I assume this is a duplicate of #1427?

**Comment by swails** [comment]
Yes.
