### ISSUE TITLE
Turn off reciprocal part of PME in AmoebaMultipoleForce

### ISSUE THREAD

**Issue by swails** [pandegroup/openmm#1383]
I've run into a roadblock in my implementation of the SINR integrator from Tuckerman's lab.  I need to be able to compute a short-range multipole force *with* converged induced dipoles using a short cutoff and, most importantly, *the reciprocal space calculation turned off*.  But I still need the PME switching functions turned on in the direct space part (with the same PME parameters as the multipole force with the long cutoff has).

I can't seem to find any way to set the reciprocal space calculation to a separate force group for AmoebaMultipoleForce or to turn it off in general (the latter being my intended behavior).  Simply not using PME isn't an option, either, since I still need the PME functional form for the direct space part.  So can we add something to the AmoebaMultipoleForce that allows me to calculate the PME-damped short-range, direct-space only part of the force (with induced dipoles)?  Does this make sense?

cc a discussion at Tinker's repo: jayponder/tinker#22

**Comment by peastman** [comment]
The problem is that in AMOEBA, the direct space and reciprocal space calculations aren't separable the way they are in standard force fields.  The mutually induced dipoles entangle them with each other.  So you do a series of iterations, each involving *both* direct *and* reciprocal space calculations.  At the end of that, you have the induced dipoles that go into the final direct and reciprocal space force calculations.  So the final interactions (both direct and reciprocal) are both dependent on both direct and reciprocal calculations while converging the dipoles.

**Comment by swails** [comment]
I know, but in the Tinker code where the SINR integrator was implemented by @dmargul, the reciprocal space part is simply turned off.  From the source code there, it appears that the induced dipoles are converged by simply omitting all calls to `emrecip`.  If I'm wrong hopefully he can give a more detailed description of what's happening, but the reciprocal space calculation is *definitely* omitted in the Tinker code (I'm not positive if the PME switching functions are also skipped, though...)

**Comment by peastman** [comment]
I don't see how that is meant to work.  Suppose you did the following two calculations:

1. Compute induced dipoles based on direct space only, then use them to calculate the direct space forces.

2. Compute induced dipoles based on reciprocal space only, then use them to calculate the reciprocal space forces.

The sum of those two will *not* equal the total forces.  The direct space forces depend on induced dipoles from reciprocal space, and reciprocal space forces depend on induced dipoles from direct space.

**Comment by peastman** [comment]
You could, of course, do the full induced dipole calculation, but then at the end compute only one part of the interaction (either direct or reciprocal).  But I don't think there would be much benefit to that.  Computing the induced dipoles is the most expensive part of the calculation.  And computing the direct space forces is the second most expensive part.  The reciprocal space forces—the only part of the calculation you would get to do less frequently—is a very small fraction of the computation time.

**Comment by jchodera** [comment]
If you have to subtract off the short-range electrostatics anyway, why not use `direct` polarization for that, and then only use the `induced` polarization for the full-electrostatics outer timestep?

**Comment by peastman** [comment]
Switching between direct and mutual isn't something you can do on the fly.  It involves recompiling kernels.

**Comment by rmcgibbo** [comment]
I'm not really too knowledgeable about the theory for multiple timestep integrators, but isn't the property that the total energy strictly decomposes into a sum across the terms that are integrated with the different timesteps a relatively important property?

**Comment by jchodera** [comment]
> I'm not really too knowledgeable about the theory for multiple timestep integrators, but isn't the property that the total energy strictly decomposes into a sum across the terms that are integrated with the different timesteps a relatively important property?

Yes, which is why you decompose things as
```
U = A + B + C + D
```
or
```
U = A + B + (C+X) + (D-X)
```
or whatever you want.

In the other thread, @swails talks of accessing the long-range forces by computing the whole thing (since OpenMM can't separate these) and subtracting off the short-range forces, like in the second scheme above.

**Comment by jchodera** [comment]
> Switching between direct and mutual isn't something you can do on the fly. It involves recompiling kernels.

You can't have one `Force` object for short-range in `direct` and another for full electrostatics with `mutual`?

**Comment by rmcgibbo** [comment]
Well yeah, but that kind of destroys the original purposes, which was to speed up MD, no?

**Comment by jchodera** [comment]
> Well yeah, but that kind of destroys the original purpose, which was to speed up MD, no?

Efficiency depends on the relative costs of each of those operations and the force update times you can manage while maintaining the same degree of steady-state nonequilibrium dissipation (or equivalently, HMC acceptance rates).

**Comment by jchodera** [comment]
For example, if `D` is *much* more expensive than `X`, it may not matter.  But it depends on the implementation details, the force splitting, and the system, so your mileage may vary.

**Comment by rmcgibbo** [comment]
yeah, of course.

**Comment by rmcgibbo** [comment]
Also, if you're using a metropolization step (I didn't think this was actually too common for MD) like HMC, you might be able to get away with more sloppiness or non-additivity of the force decomposition, as long as it's a valid proposal.

**Comment by jchodera** [comment]
> Also, if you're using a metropolization step (I didn't think this was actually too common for MD) like HMC, you might be able to get away with more sloppiness or non-additivity of the force decomposition, as long as it's a valid proposal.

I'd love to see an GHMC variant of this integrator that can Metropolize each timestep!

**Comment by swails** [comment]
I'm going to close this.  @peastman is right that the scheme I have in my head isn't going to work.  I need to figure out how the short-range multipole force is actually being done in Tinker with the AMOEBA force field.  I suspect it's a simple gas-phase cutoff calculation, but I need to be sure.  And it could be that these issues are there in the Tinker implementation as well.

Anyways, thanks for the comments.
