### ISSUE TITLE
Errors in documentation source?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1387]
Can someone take a look at [these errors in building the docs source](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/107375461#L4680-L4704) and see if they are actual errors, or if something has gone wrong with my conda build machinery?

**Comment by jchodera** [comment]
Here are [some more warnings](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/107375461#L4343-L4549).

**Comment by rmcgibbo** [comment]
do i don't think those are anything.

On Fri, Feb 5, 2016 at 5:16 PM, John Chodera <notifications@github.com>
wrote:

> Here are some more warnings
> <https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/107375461#L4343-L4549>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pandegroup/openmm/issues/1387#issuecomment-180644234>.
>



-- 
-Robert

**Comment by jchodera** [comment]
Thanks!
