### ISSUE TITLE
Keeping solute at the centre in MD simulation

### ISSUE THREAD

**Issue by leelasd** [pandegroup/openmm#1390]
I am trying to simulate Aniline in water. Minimisation in water goes well. **But right in the first step of simulation solute moves away from the center and goes to the corner**. Am I missing any option while running MD simulation ? or is this a bug. Here is the code for OpenMM simulation. Force field files for [aniline](https://gist.github.com/leelasd/e6138765544df44f2c73) and [water](https://gist.github.com/leelasd/08ba3592fe1829fdec2a) are here. Aniline is [PDB](https://gist.github.com/leelasd/0acabe62a135927c8964) is also attached.  

```
from simtk.openmm.app import *
import numpy as np
from simtk.openmm import *
from simtk.unit import *
from sys import stdout,exit

def OPLS_LJ(system):
        forces = { system.getForce(index).__class__.__name__ : system.getForce(index) for index in range(system.getNumForces()) }
        nonbonded_force = forces['NonbondedForce']
        lorentz=CustomNonbondedForce('4*epsilon*((sigma/r)^12-(sigma/r)^6); sigma=sqrt(sigma1*sigma2); epsilon=sqrt(epsilon1*epsilon2)')
        lorentz.setNonbondedMethod(nonbonded_force.getNonbondedMethod())
        lorentz.addPerParticleParameter('sigma')
        lorentz.addPerParticleParameter('epsilon')
        lorentz.setCutoffDistance(nonbonded_force.getCutoffDistance())
        system.addForce(lorentz)
        LJset={}
        for index in range(nonbonded_force.getNumParticles()):
                charge,sigma,epsilon=nonbonded_force.getParticleParameters(index)
                LJset[index]=(sigma,epsilon)
                lorentz.addParticle([sigma,epsilon])
                nonbonded_force.setParticleParameters(index, charge, sigma, epsilon*0)
        for i in range(nonbonded_force.getNumExceptions()):
                (p1, p2, q, sig, eps) = nonbonded_force.getExceptionParameters(i)
                lorentz.addExclusion(p1,p2) ## ALL THE 12,13 and 14 interactions are EXCLUDED FROM CUSTOM NONBONDED FORCE
                if eps._value != 0.0:
            print p1,p2,sig,eps
                        sig14=sqrt(LJset[p1][0]*LJset[p2][0])
                        eps14=sqrt(LJset[p1][1]*LJset[p2][1])
                        nonbonded_force.setExceptionParameters(i, p1, p2, q, sig14, eps)
        return system

pdb = PDBFile('anilin.pdb')

modeller = Modeller(pdb.topology, pdb.positions)
forcefield = ForceField('anilin.xml','tip3p.xml')
modeller.addSolvent(forcefield,boxSize=Vec3(2.0, 2.0, 2.0)*nanometers)

system = forcefield.createSystem(modeller.topology, nonbondedMethod=NoCutoff,  constraints=HBonds)
system = OPLS_LJ(system)

integrator = LangevinIntegrator(300*kelvin, 1/picosecond,  0.001*picoseconds)

simulation = Simulation(modeller.topology, system, integrator)
simulation.context.setPositions(modeller.positions)
## MINIMIZING 
simulation.minimizeEnergy(maxIterations=300)
position = simulation.context.getState(getPositions=True).getPositions()
PDBFile.writeFile(simulation.topology, position, open('boxmin.pdb', 'w'))
## Setting up simulation for 10ps
simulation.reporters.append(PDBReporter('boxoutput.pdb', 1))
simulation.reporters.append(StateDataReporter(stdout, 1, step=True,potentialEnergy=True, temperature=True))
simulation.step(1)
```
## Minimized structure

![min_box](https://cloud.githubusercontent.com/assets/7967695/12874814/ba87b004-cda9-11e5-9059-6c24a090185e.png)
## First step of MD simulation

![step1](https://cloud.githubusercontent.com/assets/7967695/12874857/cbe61d58-cdaa-11e5-9c57-8adc0dfbd305.png)

Any suggestions are highly appreciated.

**Comment by swails** [comment]
This is simply an imaging artifact and is related to OpenMM's "choice" of unit cell representation.  Since periodic boundary conditions are employed, the exact choice of unit cell representation is irrelevant.

So the answer is no, this is not a bug.  You can probably change the initial coordinates in a way that the initial wrapping does not surprise you, but the more appropriate long-term solution is to realize that this is not a problem with the simulation and to find some analysis program that will "reimage" the trajectory for you if you need it to.

I would suggest using cpptraj (part of AmberTools) and the "autoimage" command contained there.

**Comment by leelasd** [comment]
Thanks @swails !! Is there any I can convert the trajectory using OpenMMtools or MDTraj ?

**Comment by rmcgibbo** [comment]
No, I don't think so. Currently cpptraj is your best bet for reimaging.

On Sun, Feb 7, 2016 at 1:45 PM, Leela Dodda <notifications@github.com>
wrote:

> Thanks @swails <https://github.com/swails> !! Is there any I can convert
> the trajectory using OpenMMtools or MDTraj ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pandegroup/openmm/issues/1390#issuecomment-181125702>.
>



-- 
-Robert

**Comment by dr-nate** [comment]
One option is to not wrap them when writing to the DCD file. You can then wrap in another program like VMD with the Aniline in the center, using something like:

```
pbc wrap -center bb -centersel "resname $YOUR_ANILINE_RESNAME"  -compound fragment -all
```

[Here is a dcdreporter.py file](https://gist.github.com/880f825372eb715e091c) I hacked to allow this. Copy it into your simulation folder, then import it:
```
from dcdreporter import DCDReporter
```

Then add it to your simulation object:

```
simulation.reporters.append(DCDReporter('myfile.dcd', <Write every N steps>, enforcePeriodicBox=False))
```

If there's interest to make it standard functionality, I'll try to make it nice and submit a PR.

**Comment by swails** [comment]
I've actually been meaning to submit a PR to OpenMM itself to disable wrapping inside `Simulation`.  There are instances where wrapping is very undesirable.  In our hands, that has to do with crystal simulations and the fact that the wrapping violates some of the symmetry operations defined in the PDB file and makes analysis and comparison with experiment very difficult.

We have a workaround where we can unwrap the trajectory to a reference structure (usually the starting coordinates), but having an option to disable wrapping (*without* having to do another `getState`, which could be expensive) would be beneficial at least to our work.

**Comment by leelasd** [comment]
Adding this option would be great @swails. @dr-nate Thanks a lot for the code.

**Comment by peastman** [comment]
mdtraj now has a function for doing this.  See https://github.com/mdtraj/mdtraj/pull/1058.

**Comment by stefdoerr** [comment]
If I make a PR where `BaseReporter` has an option `enforcePeriodicBox` and `Simulation` respects the option set at each reporter would you accept it? Just asking so I don't waste time implementing it.
It's driving me a bit nuts the default wrapping of the reporters (sorry :disappointed:).

**Comment by peastman** [comment]
Could you describe how it would work?  The complication is that it might need to create multiple States, if some reporters wanted wrapped coordinates and others wanted unwrapped ones.  That isn't a problem, but we do want to avoid it when possible.

**Comment by stefdoerr** [comment]
I see. Well I guess at least two calls would be necessary  here https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/simulation.py#L215 (one wrapped, one not) unless we explicitly wrap the coordinates after getting the state without wrapping.

**Comment by peastman** [comment]
Right.  The current behavior tries to guess what you want.  If the system includes any force that uses periodic boundary conditions, it concludes you're simulating a periodic system and it should wrap coordinates.  Otherwise, it doesn't.  That's probably correct >95% of the time.  So what we want is a way to override that behavior in the rare exceptions.  Adding one reporter that overrides it shouldn't change the behavior of any other reporter, but we also don't want to go to the expense of creating multiple states except when it's truly needed.

**Comment by jchodera** [comment]
> The current behavior tries to guess what you want. If the system includes any force that uses periodic boundary conditions, it concludes you're simulating a periodic system and it should wrap coordinates.

Note that this is improper behavior for computing diffusion constants, so it's not reasonable that we're hiding the decision whether to wrap or not [in a private object field](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/simulation.py#L111-L114). This should be something that the user can override through a public API.

**Comment by stefdoerr** [comment]
I'm also wondering. How do you deal with stuff like protein-protein interactions where the molecules being wrapped are big? The periodic distance can be much shorter than the wrapped distance. Or do you unwrap the simulation afterwards to calculate the correct distances?

In the view of our group we decided some time ago that wrapping is really only necessary for visualization and all calculations should be done unwrapped. Wrapping isn't really that computationally intensive so we just do it on the fly at the moment of visualizing the trajectories.

I see two solutions to not recalculate the state.
1. `getState` returns unwrapped coordinates and you wrap with a separate call from Simulation after getting positions https://github.com/pandegroup/openmm/blob/e32875f3050f0f6844377d3b91ff75350422816a/wrappers/python/simtk/openmm/app/simulation.py#L215 That would mean making this code https://github.com/pandegroup/openmm/blob/7cdd6d16348b051e97f162580f908ace13be0e25/openmmapi/src/Context.cpp#L121-L140 available as a separate function.
2. `getState` returning both wrapped and unwrapped coordinates. Although this doubles the memory usage.
https://github.com/pandegroup/openmm/blob/7cdd6d16348b051e97f162580f908ace13be0e25/openmmapi/src/Context.cpp#L142 could have two calls: `setPositions()` and `setPositionsUnwrapped()`.

Is there any argument against solution #1?

**Comment by jchodera** [comment]
MDTraj has some clever [imaging schemes](http://mdtraj.org/1.8.0/api/generated/mdtraj.Trajectory.html#mdtraj.Trajectory.image_molecules) that try to "do the right thing" regarding macromolecules with binding partners.

**Comment by stefdoerr** [comment]
Yes I saw it was posted in this thread. But to me at least it feels like trying to fix something that should not be a problem in the first case. Distances should be wrapped for calculation of interactions and molecules only wrapped for visualization. At least that's how we decided to do it in HTMD because it seemed cleaner. But I might be missing some argument for default wrapping.

**Comment by jchodera** [comment]
> But I might be missing some argument for default wrapping.

Besides of ease of visualization, for very long simulations where molecules may diffuse many unit cells away, the simulations will experience a degradation of positional precision.

**Comment by stefdoerr** [comment]
I see.
Well I forgot there is option 3 which is to add a wrapping argument to `Simulation.__init__()` and only executes following lines if it's `None`.
https://github.com/pandegroup/openmm/blob/e32875f3050f0f6844377d3b91ff75350422816a/wrappers/python/simtk/openmm/app/simulation.py#L111-L114

I think that should be the easiest. Although I think setting a per-reporter option (as in option 1) is more elegant for the future.

**Comment by peastman** [comment]
I don't think any of those is a great option.  Option 1 unnecessarily adds complexity to the API, option 2 increases both memory and computation time, and option 3 is more limited.  Here's how I would do this:

1. Create a mechanism by which a reporter can request whether positions should be wrapped.  For example, define a new method the reporter can implemented, or return an extra value from `describeNextReport()`.  If a reporter doesn't implement that mechanism (which includes existing reporters that haven't been modified to support it), that means to use the default behavior.

2. If (and only if) there are two reporters that both request positions and that have different choices for wrapping, it will create two state objects and pass the appropriate one to each reporter.

If you prefer, I could implement this.  There are a few subtleties to making it efficient.

**Comment by stefdoerr** [comment]
Sure, if you can do it :) I'm in no extreme hurry but it would be nice to
not have to hack my way around it some day.

**Comment by peastman** [comment]
I just submitted a PR with the change: #1895.  Could you try it out and see how it works for you?

**Comment by peastman** [comment]
@stefdoerr does the implementation in #1895 look ok to you?  Will it meet your needs?

**Comment by stefdoerr** [comment]
Yes, sorry. Monday was holiday and Tuesday I was busy :stuck_out_tongue: I'll give it a try now

**Comment by stefdoerr** [comment]
Do you have some instructions on how to make a temporary installation of the PR to test against? I tried a bit around but could not get it to work.

From looking at it, the changes look fine to me (other than the recomputing of the lists that I mentioned).

**Comment by peastman** [comment]
If you click the "command line instructions" link on any PR, it gives you the commands for trying it out.  In this case that's

```
git checkout -b peastman-periodic master
git pull https://github.com/peastman/openmm.git periodic
```

**Comment by stefdoerr** [comment]
Yeah I got up to that point. But adding it to my pythonpath gives many
problems (I guess due to uncompiled stuff)

**Comment by peastman** [comment]
You need to compile and install it.  I assumed you were already building from source.  If not, don't worry about it.  I can just merge the PR, and you can test the next dev build.

**Comment by stefdoerr** [comment]
Yeah no I was using the conda distribution. I don't bother much with
compiling unless I have some clear instructions which I didn't find in the
developer's guide.
But as you said, next dev build is ok for me as well :)

**Comment by peastman** [comment]
Ok, PR is merged.  You should be able to test it tomorrow by installing from the label `omnia/label/dev`.
