### ISSUE TITLE
Is there anything we can do to improve numerical stability in CustomAngleForce?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1397]
We ran into a case where we wanted to be able to turn some valence terms on and off dynamically with global context parameters to exclude atoms that have not yet had positions assigned.  Unfortunately, when using `step` to turn interactions off,  `HarmonicAngleForce` still happily generates `NaN`s:
```python
#!/usr/bin/env python

from simtk import openmm, unit

system = openmm.System()

nparticles = 4
positions = list()
for index in range(nparticles):
    system.addParticle(1.0)
    positions.append([0,0,0])

force = openmm.CustomAngleForce('step(global_index - angle_index)*(K/2)*(theta-theta0)^2;')
force.addPerAngleParameter("theta0")
force.addPerAngleParameter("K")
force.addPerAngleParameter("angle_index")
force.addGlobalParameter('global_index', 0)
force.addAngle(0, 1, 2, [1.08, 500, 1])
system.addForce(force)

integrator = openmm.VerletIntegrator(1.0 * unit.femtoseconds)
platform = openmm.Platform.getPlatformByName('Reference')
context = openmm.Context(system, integrator, platform)
context.setPositions(positions)
print context.getState(getEnergy=True).getPotentialEnergy()
```
Output:
```
[LSKI1497:choderalab/perses/perses.choderalab] choderaj% python openmm-nans.py
nan kJ/mol
```
It appears that `theta` itself is `NaN` in this case; modifying the energy function to be just `theta` returns `nan` as well.  Obviously, `theta` is not really defined if all atoms in the bond have identical coordinates, but `0` may be more useful that `NaN` for those situations.

**Comment by peastman** [comment]
Use select() instead of multiplying by step().  This is exactly the sort of thing it's for.

**Comment by jchodera** [comment]
Ah!  Using `select(step(global_index - angle_index), (K/2)*(theta-theta0)^2, 0);` does the trick.

Thanks!
