### ISSUE TITLE
[openmm-beta] CUDA working on python but not IPython

### ISSUE THREAD

**Issue by jhprinz** [pandegroup/openmm#1401]
Just installed the new OpenMM-beta from conda. Then installed CUDA Toolkit 7.5 and updated CUDA to the latest drivers. Everything used to run before fine!

I set the `DYLD_LIBRARY_PATH` correctly to the cud folder
```
echo $DYLD_LIBRARY_PATH
>>> /usr/local/cuda/lib/
```

Running an IPython session lists 3 platforms
```
Reference
CPU
OpenCL
```
and the `omm.Platform.getPluginLoadFailures()` lists that all the referenced libraries using `@rpath` cannot be found. Using `otool` however shows that the current version is correctly found (With help of `DYLD_LIBRARY_PATH` I presume)

Now the strange thing:

Running 
```
python -c "import simtk.openmm as omm; print '\n'.join(omm.Platform.getPluginLoadFailures())"
```
lists the same errors as in IPython, but
```
python -c "import simtk.openmm as omm; print omm.Platform.getNumPlatforms()"
>>> 4
python -c "import simtk.openmm as omm; print omm.Platform.getPlatform(2).getName()"
>>> CUDA
```

So in `python` it is loaded correctly. I played around a little more and figured that apparently IPython does not load all environment variables so 

in python
```
python -c "import os; print os.environ['DYLD_LIBRARY_PATH']"
>>> /usr/local/cuda/lib/
```

while in IPython
```
import os
print 'DYLD_LIBRARY_PATH' in os.environ
>>> False
```

So, the necessary DYLD is not set at all. Also 
```
print os.getenv('DYLD_LIBRARY_PATH')`
>>> None 
```

Is it possible that all the `@rpath` trouble is caused by IPython? Or am I missing some special option to import environment variables (like sudo sometimes).

**Comment by peastman** [comment]
It looks like this is a known issue in conda on OS X: https://github.com/conda/conda-build/issues/628

There's a workaround suggested at https://github.com/ipython/ipython/issues/8878, though no one seems to be sure whether it's actually a safe workaround, since they aren't sure why the thing they're changing is the way it is in the first place.

**Comment by jhprinz** [comment]
This is fixed in ipython etc...
