### ISSUE TITLE
PDBFile should write unrecognized residues as HETATM with CONECT residues

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1406]
Our `PDBFile` doesn't seem to conform to the PDB standard of writing residues that are nonstandard as `HETATM` records with `CONECT` records.

**Comment by jchodera** [comment]
It looks like we already have a [list of standard residues](https://github.com/choderalab/openmm/blob/master/wrappers/python/simtk/openmm/app/pdbfile.py#L78-L80) defined in `PDBFile` that we can compare against to determine whether `HETATM` and `CONECT` records need to be written.

**Comment by jchodera** [comment]
PDB format documents [`HETATM`](http://deposit.rcsb.org/adit/docs/pdb_atom_format.html#HETATM) as being used for
> the atomic coordinate records for atoms within "non-standard"  groups. 

while [`ATOM`](http://deposit.rcsb.org/adit/docs/pdb_atom_format.html#ATOM) is used for
> the atomic coordinates for standard residues 

so we are currently writing files that are non-compliant with the PDB spec.

**Comment by peastman** [comment]
Should be very easy to fix.
