### ISSUE TITLE
bug and error using force groups for per-term energy decomposition 

### ISSUE THREAD

**Issue by zhengmin317** [pandegroup/openmm#1408]
I am using charmm27 force filed.
For simulation.context.getState(getEnergy=True,groups=0).getPotentialEnergy() and simulation.context.getState(getForces=True,groups=0).getForces(), they should give energy and forces from bonded interaction.
 Actually I got zero for both.

**Comment by Lnaden** [comment]
I think its because you are using `groups=0` instead of `groups=1`. The `groups` argument accepts a 32-bit int that is cast into bits that fetch the force group corresponding to bit X, so `groups=1` is interpreted as setting the `2^0` bit to true, and thus force group 0. Setting `groups=0` says all bits are false, and so no force groups are returned, giving you a zero energy and force.

**Comment by peastman** [comment]
In the latest version of the code, you can also specify a set of integers: `groups={0}`.

**Comment by zhengmin317** [comment]
**My inputs:**
from simtk.openmm.app import *                                                                                                                                
from simtk.openmm import *
from simtk.unit import *
from sys import stdout, exit, stderr

psf = CharmmPsfFile('rna_urea.psf')
pdb = PDBFile('1.pdb')
params = CharmmParameterSet('rna.rtf', 'rna.prm')
system = psf.createSystem(params, nonbondedMethod=NoCutoff)
integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
simulation = Simulation(psf.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
print "default groups" , simulation.context.getState(getEnergy=True).getPotentialEnergy()
print "groups=-1",simulation.context.getState(getEnergy=True,groups=-1).getPotentialEnergy()
print "groups=0",simulation.context.getState(getEnergy=True,groups=0).getPotentialEnergy()
print "groups=1",simulation.context.getState(getEnergy=True,groups=1).getPotentialEnergy()
print "groups=2",simulation.context.getState(getEnergy=True,groups=2).getPotentialEnergy()
print "groups=3",simulation.context.getState(getEnergy=True,groups=3).getPotentialEnergy()
print "groups=4",simulation.context.getState(getEnergy=True,groups=4).getPotentialEnergy()
print "groups=5",simulation.context.getState(getEnergy=True,groups=5).getPotentialEnergy()
print "groups=6",simulation.context.getState(getEnergy=True,groups=6).getPotentialEnergy()
print "groups=60",simulation.context.getState(getEnergy=True,groups=60).getPotentialEnergy()

**The outputs:**
/Library/Python/2.7/site-packages/simtk/openmm                                                                                                                
self.cmap_list  []
default groups 5429.6202528 kJ/mol
groups=-1 5429.6202528 kJ/mol
groups=0 0.0 kJ/mol
groups=1 637.458345561 kJ/mol
groups=2 1223.28544111 kJ/mol
groups=3 1860.74378581 kJ/mol
groups=4 1683.88986144 kJ/mol
groups=5 2321.34820497 kJ/mol
groups=6 2907.17530036 kJ/mol
groups=60 2046.0828454 kJ/mol

The cmap_list is empty, the energy should be zero when groups=5.
In charmmpsffile.py, the total energy has 7 components:
  BOND_FORCE_GROUP = 0                                                                                                                                                                                           
    ANGLE_FORCE_GROUP = 1
    DIHEDRAL_FORCE_GROUP = 2
    UREY_BRADLEY_FORCE_GROUP = 3
    IMPROPER_FORCE_GROUP = 4
    CMAP_FORCE_GROUP = 5
    NONBONDED_FORCE_GROUP = 6
    GB_FORCE_GROUP = 6,
so the energy should throw an error when groups =60.

**Comment by zhengmin317** [comment]
@peastman 
I tried groups={0}, and got the error "TypeError: in method 'Context__getStateAsLists', argument 8 of type 'int'".
The version of my openmm is 6.3.1.

**Comment by Lnaden** [comment]
You want to use a list object with square braces, [], for specifying groups by specific group number, but I'm not sure that was in 6.3.1. Passing the list will let you specify groups by their group number without converting the groups to an int that is calculated with bitwise math. Using curly braces, {}, creates a dictionary which is not accepted. 

If you pass in an int, you have to make sure the int sets the bits of the force groups you want. 
`groups=0` is no bits, so no force groups are selected
`groups=1` is the binary number `1` which sets `2^0` and fetches force group 0
`groups=60` is binary `111100` which sets bits `2^5`, `2^4`, `2^3`, and `2^2` so it gets force groups 2, 3, 4, and 5.
It follows the bitwise math that Group i will be included if (groups&(1<<i)) != 0 ([documented here](http://docs.openmm.org/6.3.0/api-python/classsimtk_1_1openmm_1_1openmm_1_1Context.html#a4ce4ebac6ce95bd44e0d8c96d2f7229c))

In your case, for groups 0 through 6 individually, you would want the ints 1, 2, 4, 8, 16, 32, and 64 respectively.

**Comment by swails** [comment]
Actually using curly braces without a key:value pair (i.e., just a key) creates a set, which is required by the API). When provided as a set, the list of groups is added together into the appropriate bit mask. 

For instance, {0, 1, 2} becomes 1+2+4=7.

**Comment by peastman** [comment]
That feature was added in 7.0.  In 6.3.1, you need to specify a bit mask.
