### ISSUE TITLE
bug and error: The energy of  Openmm is different from other softwares

### ISSUE THREAD

**Issue by zhengmin317** [pandegroup/openmm#1409]
I used charmm force filed to calculate the energy.
However the energy value of Openmm is obviously different from software CHARMM and NAMD

**Comment by peastman** [comment]
Could you provide more information?  What are you calculating the energy of?  How did you do it?  If you can provide your script and input files, as well as what results you were expecting to get, that would be very helpful.

**Comment by zhengmin317** [comment]
@peastman 
You can get input and output information from the issue
1408,https://github.com/pandegroup/openmm/issues/1408

**Comment by peastman** [comment]
I need all the input files.  Otherwise, I can't reproduce what you're doing.

**Comment by peastman** [comment]
Did you figure out the problem?

**Comment by zhengmin317** [comment]
I was comparing energy component from simulation.context.getState(getEnergy=True,groups=0).getPotentialEnergy() .
Now I know the groups can not take int directly, it needs a bit mask.
Thanks for the help.
