### ISSUE TITLE
Fortran wrapper problem

### ISSUE THREAD

**Issue by nullsatz** [pandegroup/openmm#1410]
In the fortran wrapper for OpenMM 7.0.0

OpenMM_Types contains:
integer*4, parameter :: OpenMM_CustomIntegrator_BeginIfBlock = 6
integer*4, parameter :: OpenMM_CustomIntegrator_BeginWhileBlock = 7
integer*4, parameter :: OpenMM_CustomIntegrator_EndBlock = 8

While the OpenMM module contains:
function OpenMM_CustomIntegrator_beginIfBlock(target, condition)
function OpenMM_CustomIntegrator_beginWhileBlock(target, condition)
function OpenMM_CustomIntegrator_endBlock(target)

This causes a compiler error along the lines of a namespace clash when the OpenMM module functions use OpenMM_Types.

**Comment by jchodera** [comment]
@peastman, are there any tests of the wrapper that we could try to add to Travis CI testing?

**Comment by peastman** [comment]
That would be a good idea.  Even if it's just to verify that a simple program using the Fortran wrapper compiles, that would catch problems like this.

**Comment by jchodera** [comment]
I'm happy to help try to add travis branches to do this testing if you can point me to the appropriate build/run instructions for the wrapper tests.

**Comment by rmcgibbo** [comment]
I don't think there are any fortran wrapper tests yet. They probably need to be written.

**Comment by peastman** [comment]
I just sent a PR (#1424) with the fix.  @nullsatz could you verify that it fixes the problem for you?

**Comment by nullsatz** [comment]
Yeah, that fixes the issue for me. Thanks!

**Comment by peastman** [comment]
Thanks!
