### ISSUE TITLE
GromacsTopFile bug?

### ISSUE THREAD

**Issue by thempel** [pandegroup/openmm#1414]
Hi guys,

there seems to be a problem with the input of GROMACS force field parameters. I am trying to use my .gro and .top files for running a simulation in openMM. After a couple of simulation steps, the nonbonded forces explode. The problem is most likely that the HarmonicBondForce parameter for a specific H atom is not read-in at all, even though present in the GROMACS topology file. It does not appear in system.getForce(1).getBondParameters(). I am using a CHARMM27 force field, might that be the problem?

**Comment by peastman** [comment]
Could you post the files needed to reproduce this?  Thanks!

**Comment by peastman** [comment]
@thempel can you provide your files?  Without a way to reproduce this, there's not a lot we can do.

**Comment by thempel** [comment]
Sorry, I could not extract a minimal example so far (which is also the reason for my late response). I am attaching gromacs .top and .gro files of the full system though. The positions were extracted from a longer trajectory and used as a starting point for another (working) gromacs MD run. If I use them with openMM without minimizing the energy, I get NaN particle positions. Thanks for your help!


[protein_example.zip](https://github.com/pandegroup/openmm/files/215485/protein_example.zip)

**Comment by thempel** [comment]
I think it's the periodic boundary conditions. An easy fix is to convert the input with
`gmx editconf -f in.gro -o out.gro -c -pbc`
Seems that e.g. water molecules that are split by the periodic boundary are not taken into account correctly.

**Comment by swails** [comment]
> Seems that e.g. water molecules that are split by the periodic boundary are not taken into account correctly.

Yes, I believe this is correct. Most programs do not adopt a MIC view of covalent bonds, and as such image whole molecules rather than individual atoms.  In fact, the ability to use PBC when evaluating bonded terms was introduced only recently to OpenMM (after 7.0 was released).

As such, if the periodic image of two atoms in the same molecule belong to *different* molecules, OpenMM will fail to correctly process the system.
