### ISSUE TITLE
Matching extra particles on name

### ISSUE THREAD

**Issue by rafwiewiora** [pandegroup/openmm#1415]
This surprised me when I was doing testing with TIP4PEW AMBER vs OpenMM. I generated a PDB with tleap, which calls the extra particle `EPW`. Topology generated from such PDB cannot create a System in OpenMM - the HOH template does not match. 

Looks like that's because for extra particles (i.e. for `None` element) the matching of atoms is done based on name: https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py#L1056

I guess this was intended to not have problems with the by-element matching that happens otherwise there. But it isn't something that I expected at all, because it deviaties from the 'names don't matter' strategy so much. 

Is this something you would like to fix - perhaps change that algorithm around a bit so that it does not have the use the names? I thought there was some kind of a bond graph matching going on here that would be okay with using `None` as a 'meaningful' element anyway. 

For now I'm just going to deal with this in the conversion script. My problem is that I can't use the same PDB for AMBER and OpenMM now without any changes - AMBER wants the `EPW` name, amber wants `M` for the virtual site. So I'm just going to throw in a name translation at some point.

**Comment by peastman** [comment]
Unfortunately, there are cases where there's no choice.  What if a residue has two virtual sites?  We need some way of telling which is which.  We can't use element (there isn't one) or bonds (virtual sites usually don't have those either).  Also, we're talking about extra particles, for which the rule of "use standard PDB names" doesn't apply.

**Comment by rafwiewiora** [comment]
Yeah, ok, I can see now there's no choice. I guess the only way to solve this would be to have virtual sites have 'virtual bonds' that indicate where they 'belong'. But that's way too much changing of the whole concept for just this use case of course. Ok, closing then!
