### ISSUE TITLE
`openmm-dev` conda package build is failing

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1419]
The [`openmm-dev` conda package build is failing](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/115770093):
[full log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/115770093/log.txt)
```

Fixing linking of @rpath/libOpenMMPME.dylib in /Users/travis/anaconda/envs/_build/lib/plugins/libOpenMMPME.dylib

Fixing linking of @rpath/libOpenMM.dylib in /Users/travis/anaconda/envs/_build/lib/plugins/libOpenMMPME.dylib

Fixing linking of /usr/lib/libSystem.B.dylib in /Users/travis/anaconda/envs/_build/lib/plugins/libOpenMMPME.dylib

Fixing linking of @rpath/./libfftw3f.3.dylib in /Users/travis/anaconda/envs/_build/lib/plugins/libOpenMMPME.dylib

Fixing linking of @rpath/./libfftw3f_threads.3.dylib in /Users/travis/anaconda/envs/_build/lib/plugins/libOpenMMPME.dylib

Fixing linking of /usr/lib/libc++.1.dylib in /Users/travis/anaconda/envs/_build/lib/plugins/libOpenMMPME.dylib

install_name_tool -add_rpath @loader_path/../ /Users/travis/anaconda/envs/_build/lib/plugins/libOpenMMPME.dylib

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: object: /Users/travis/anaconda/envs/_build/lib/plugins/libOpenMMPME.dylib malformed object (load command 18 cmdsize is zero)



Error: install_name_tool failed with exit status 1

ERROR: File does not exist: /Users/travis/anaconda/conda-bld/osx-64/openmm-dev-0.0.0-py27_0.tar.bz2
```

**Comment by mpharrigan** [comment]
## OpenMM repo

Last working commit:
```
commit 9b5b52f2bf2e851efdd0733fed3e83a24d9f16af

Merge: b768ff4 71cb735
Author: peastman <peter.eastman@gmail.com>
Date:   Fri Mar 4 12:54:01 2016 -0800

    Merge pull request #1407 from peastman/coefficients

    Updated default coefficients for extrapolated polarization
```

First Failing commit
```
commit 9b5b52f2bf2e851efdd0733fed3e83a24d9f16af
Merge: b768ff4 71cb735
Author: peastman <peter.eastman@gmail.com>

Date:   Fri Mar 4 12:54:01 2016 -0800

    Merge pull request #1407 from peastman/coefficients

    Updated default coefficients for extrapolated polarization
```

**Comment by mpharrigan** [comment]
## conda-recipes-dev repo

Last working commit: b00c778c13f7f64883f6e2933025393628a04061
First failing commit: b00c778c13f7f64883f6e2933025393628a04061

**Comment by mpharrigan** [comment]
What else could have changed?

**Comment by mpharrigan** [comment]
I see it pulls conda-build-all from conda-recipes master. Can you change that so it does this in some sort of versioned way? Either download from a specific tag/commit or download it via a git clone and do a `git show`.

Anyways, The build worked march 8 and failed march 9. Based on the "network view" for conda-recipes, nothing changed between those two dates either

**Comment by peastman** [comment]
Could it be that it's pulling the wrong version of FFTW?  It looks like Mar. 3 was the day I uploaded the new build for Windows with VS 2015.  It's hard to imagine how that would affect the Mac build, and this didn't break until the next day, but I'm just trying to consider anything that might have changed.

**Comment by peastman** [comment]
Might the CMake version have changed?  I found the following page where someone ran into this problem and traced it to a CMake bug:

http://stackoverflow.com/questions/22885207/opencv-and-pcl-builds-on-osx-result-in-malformed-object-load-command-cmdsize

They reported that 2.8.11 worked correctly, but 2.8.12 was broken.  It looks like travis is using a much newer version than that (3.3.1).

**Comment by jchodera** [comment]
> I see it pulls conda-build-all from conda-recipes master. Can you change that so it does this in some sort of versioned way? Either download from a specific tag/commit or download it via a git clone and do a git show.

We previously had a specific version of `conda-build-all` in the repo, but switched to pulling the `omnia/conda-recipes` version because @rmcgibbo suggested this was the only way to avoid having these two repositories become hopelessly out of sync.  Switching to a versioning scheme would allow these to once again become out of sync.  IMHO, the only way to easily catch problems is to have the `openmm-dev` package built by the `openmm` repo's travis script. There's no other way to easily identify when changes break conda package builds.

@peastman : I'm not sure I follow. How would the 2.8.12 issue impact things if travis is using 3.3.1?

**Comment by peastman** [comment]
I was just asking whether the CMake version might have changed.  I found a past case where a change to CMake caused exactly that error to occur.  *Something* changed, and since it wasn't either the source code or the conda recipe, I'm looking for other possibilities.

**Comment by jchodera** [comment]
Ah, OK.  Thanks for the clarification.

**Comment by mpharrigan** [comment]
> Switching to a versioning scheme would allow these to once again become out of sync.

I'm imagining a scheme where it still pulls the latest file but reports the git hash (like how it reports the git hash for openmm)

>  IMHO, the only way to easily catch problems is to have the openmm-dev package built by the openmm repo's travis script.

I don't understand this logic. We wouldn't have *any* additional debugging information if this was built by a travis worker operating on this repository*.

fine print: except we should print out the git hash for `conda-build-all`, see above :)

Specifically, it's pretty clear that there were no commits to the openmm repo, conda-dev repo, or conda repo

**Comment by mpharrigan** [comment]
re: peter's train of thought: it could be any number of version bumps in external software, no? I don't know how homebrew works but maybe that's getting a new version of something that breaks pme on mac

**Comment by mpharrigan** [comment]
Googling the error message gave this:

http://stackoverflow.com/questions/10390186/install-name-tool-reporting-malformed-object
https://github.com/Homebrew/homebrew/issues/25665

which seem to suggest old versions of `install_name_tool` can hang around and wreak havoc

**Comment by jchodera** [comment]
> I'm imagining a scheme where it still pulls the latest file but reports the git hash (like how it reports the git hash for openmm)

That sounds totally reasonable!  

> I don't understand this logic. We wouldn't have any additional debugging information if this was built by a travis worker operating on this repository*.

We'd know exactly when anything breaks because PRs would immediately start failing.

**Comment by jchodera** [comment]
[These folks](https://travis-ci.org/hughperkins/clnn/builds/107115627) may have had the same issue because they have inserted
```bash
which install_name_tool
path_to_install_name_tool=/usr/bin/install_name_tool
```

**Comment by mpharrigan** [comment]
> We'd know exactly when anything breaks because PRs would immediately start failing. 

And the failures would be unrelated to those PRs because apparently these builds can start failing due to reasons seemingly out of our control :) An email alert when things start breaking seems sufficient, imo

**Comment by jchodera** [comment]
We can do email notifications: https://docs.travis-ci.com/user/notifications/#Email-notifications

Who should receive them?

**Comment by peastman** [comment]
I would definitely want notifications.

In the mean time, how can we move forward on resolving this?

**Comment by jchodera** [comment]
I am not sure about what is going on here but can poke at this a bit.  More people poking at it may help.

**Comment by jchodera** [comment]
When the error is raised, it is using `Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool`:
```
Fixing linking of /usr/lib/libc++.1.dylib in /Users/travis/anaconda/envs/_build/lib/plugins/libOpenMMPME.dylib
install_name_tool -add_rpath @loader_path/../ /Users/travis/anaconda/envs/_build/lib/plugins/libOpenMMPME.dylib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: object: /Users/travis/anaconda/envs/_build/lib/plugins/libOpenMMPME.dylib malformed object (load command 18 cmdsize is zero)

Error: install_name_tool failed with exit status 1
```
but in other cases, `which install_name_tool` gives `/usr/bin/install_name_tool`:
```
+ which install_name_tool
/usr/bin/install_name_tool
```
I'm not certain if this is a symlink to `Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool`.  I'll see if I can check.

**Comment by peastman** [comment]
Possibly we need a call to `xcode-select` somewhere?

https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/xcode-select.1.html

**Comment by jchodera** [comment]
Any idea what would need to be done?  It seems to be set correctly:
```
+ xcode-select -p
/Applications/Xcode.app/Contents/Developer
+ which install_name_tool
/usr/bin/install_name_tool
++ which install_name_tool
```

**Comment by mingwandroid** [comment]
Sounds like a broken dylib had leaked in somewhere. Possibly due to a bug when calling -delete-rpath with an OS X 10.7 version of install_name_tool. Or this could be another bug in an old version of that program.

What version are you using @jchodera?

**Comment by jchodera** [comment]
Thanks for the idea about what else to look into! All of these builds happen on the Travis osx infrastructure:

https://docs.travis-ci.com/user/osx-ci-environment/
