### ISSUE TITLE
EXCEPTION: There is no registered Platform called "CPU"

### ISSUE THREAD

**Issue by pescobar** [pandegroup/openmm#1430]
Hi 

One of my cluster users reported a problem when using OpenMM in our compute nodes with AMD magny-cours cpus. 

I have installed the binary distribution provided in the OpenMM website. My user compiles his code like this `g++ HelloArgon.cpp -I/path/to/openmm/include -L/path/to/openmm/lib -lOpenMM` and the compilation works fine but when executing the binary he gets this error:

```EXCEPTION: There is no registered Platform called "CPU"```

The same procedure works fine in a machine with intel cpus using the same openmm installation (same openmm installation directory shared over nfs to all my compute nodes). I tried to build openmm from sources in case this could solve the issue but I still get the same error when compiling from sources.

I have tried with OpenMM-6.1 and OpenMM-6.3.1 and I get the same error with both. The test code I am compiling is this: https://github.com/pandegroup/openmm/blob/master/examples/HelloArgon.cpp

Any suggestion how I could solve this issue?

thanks

**Comment by peastman** [comment]
The CPU platform requires that your processor support SSE 4.2.  For Intel, that means Nehalem (introduced in 2008) or later.  For AMD, that means Bulldozer (introduced in 2011) or later.

**Comment by pescobar** [comment]
thanks for the clarification @peastman 

I think this issue can be closed.

**Comment by hainm** [comment]
@peastman I got the same issue. Did you mean that I can not use `openmm` in my machine?

**Comment by peastman** [comment]
First, make sure it really is the same issue.  There are various reasons it might not find the CPU platform, such as an incorrect path to the plugins directory.  What model of CPU do you have?

If it's too old to support the CPU platform, you can still use all the other platforms.  The reference platform is too slow to be useful for most purposes, but the OpenCL and CUDA platforms should still work fine, assuming you have appropriate hardware.

**Comment by hainm** [comment]
> First, make sure it really is the same issue. 

ah, I got the error when using Python interface. (installed from omnia, `v7.0`)

```
>>> openmm.Platform.getPlatformByName('CPU')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/haichit/anaconda3/lib/python3.5/site-packages/simtk/openmm/openmm.py", line 8485, in getPlatformByName
    return _openmm.Platform_getPlatformByName(name)
Exception: There is no registered Platform called "CPU"
```

> model of CPU

```bash
$ cat /proc/cpuinfo |grep model
model		: 4
model name	: AMD Phenom(tm) II X4 965 Processor
```

I got `Exception: There is no registered Platform called "CPU"` when testing `ParmEd`. https://github.com/ParmEd/ParmEd/blob/master/test/utils.py#L15-L21

**Comment by peastman** [comment]
Yeah, that model was introduced back in 2009, so it's too old to support the CPU platform.

**Comment by marscher** [comment]
There is some kind of inconsistency with python2 and python3 (I'm using just the py interface in two different conda environments on the same machine). The cpu used there supports sse4.2.

If I execute the following snippet I get different results depending on the major version of python:
python -c "from simtk.openmm import Platform; Platform.getPlatformByName('CPU')"

On Python 3.6 I get
```
Traceback (most recent call last):                                                                                                                                                                                
  File "<string>", line 1, in <module>                                                                                                                                                                            
  File "/home/marscher/anaconda/envs/adaptive_py36/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 12138, in getPlatformByName
    return _openmm.Platform_getPlatformByName(name)
Exception: There is no registered Platform called "CPU"
```
while the platform can be found on Py27.

Is Python 3.6 supported?

**Comment by marscher** [comment]
sorry I forgot to mention the version, it's 7.0rc1

**Comment by peastman** [comment]
There's no Python 3.6 build of that version, because it was released long before Python 3.6 existed.  The current OpenMM version (7.1) does have a Python 3.6 build.

**Comment by marscher** [comment]
I was mistaken, the used version is 7.1.0rc1.

**Comment by marscher** [comment]
If I replace "CPU" with "Reference" it works as expected.

**Comment by peastman** [comment]
Ok, then we need to track down why that platform isn't getting loaded.  Try the following in the Python interpreter:

```Python
from simtk.openmm import *
print(pluginLoadedLibNames)
print(Platform.getPluginLoadFailures())
```

That will tell us whether the plugin is getting loaded, and if it isn't, hopefully some information about why not.

**Comment by marscher** [comment]
both print statements yield empty tuples.

**Comment by peastman** [comment]
That means it isn't loading any plugins at all, presumably because it can't find the plugins directory.  Try

```Python
print(Platform.getDefaultPluginsDirectory())
```

Is it the correct directory for that install?

**Comment by marscher** [comment]
It is a conda install and the default plugin directory is falsely set to /usr/local/openmm/lib/plugins (does not exist).

**Comment by peastman** [comment]
What about

```Python
print(version.openmm_library_path)
```

That gets set at install time, so it should have the correct value.  Also, make sure you haven't set the environment variable `OPENMM_PLUGIN_DIR`.
