### ISSUE TITLE
More AMOEBA developments

### ISSUE THREAD

**Issue by swails** [pandegroup/openmm#1439]
Just an FYI, additional work has been going on in the AMOEBA plugin.  See https://github.com/pren/openmm-amoeba.

Since that code is actually required to get the Tinker-OpenMM interface working with the current TOT for Tinker, I think it would be good for there to be general awareness of the AMOEBA developments happening elsewhere.

It's probably (I'd say definitely) too late for OMM 7.0, but for later versions...

**Comment by jchodera** [comment]
Is that a plugin, or just a fork of openmm?

**Comment by swails** [comment]
Fork; but a (slightly) diverged fork.  It has potential energy terms added to the amoeba plugin that OpenMM does not have (hence why only that fork can currently compile the Tinker-OpenMM interface).

**Comment by jchodera** [comment]
It's unfortunate that there is fork divergence here.  Any way this could be avoided?

**Comment by peastman** [comment]
I've corresponded with them a bit and they're interested in eventually getting the changes merged back into OpenMM.  I think that's a ways off though.  They're still under development.
