### ISSUE TITLE
simulated tempering mathoverflow 

### ISSUE THREAD

**Issue by msultan** [pandegroup/openmm#1452]
Hi, 
I was trying to set up a simple simulated tempering job but I keep running into math overflow errors in the calculated probability distributions . 

``` python
    probability = [math.exp((self._weights[j]-self._weights[i])-(self.inverseTemperatures[j]-self.inverseTemperatures[i])*state.getPotentialEnergy()) for j in range(len(self._weights))]
OverflowError: math range error
```
I have tried the following things:

1.  At first, I thought my temperature jumps were too large so I changed the temperature jumps to ~ 1K for the first few rungs of the temperature ladder. 
2. I then thought that the ```tempChangeInterval``` was too small so I upped it to 6ps. However, the setup is still crashing. 

Any recommendations on how to proceed next?

**Comment by msultan** [comment]
I am on version ```6.3.1.dev-a81f286``` using the script thats available [here](https://simtk.org/svn/pyopenmm/trunk/simtk/pyopenmm/extras/simulatedtempering.py).

**Comment by jchodera** [comment]
Your code has the potential for math overflows in `exp` because you're just feeding in energy and weight differences, which may be large.  This has nothing to do with the temperature differences---just that energies can wildly fluctuation.

What is the `probability` vector supposed to have as its elements?  The probability of jumping to any given new temperature using [Gibbs sampling](http://scitation.aip.org/content/aip/journal/jcp/135/19/10.1063/1.3660669)?

**Comment by peastman** [comment]
Can you post your files so I can try to reproduce it?

**Comment by jchodera** [comment]
The problem is here:
```
        probability = [math.exp((self._weights[j]-self._weights[i])-(self.inverseTemperatures[j]-self.inverseTemperatures[i])*state.getPotentialEnergy()) for j in range(len(self._weights))]
        scale = 1.0/sum(probability)
        probability = [p*scale for p in probability]
```
This is numerically unstable.  You should be computing the probability in log space and using [`logsumexp`](http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.misc.logsumexp.html) to compute the normalization constant:
```python
nstates = len(self._weights)
# Always compute weights in log space
log_probability = np.array([ self._weights[i] - self.inverseTemperatures[i])*state.getPotentialEnergy() for i in range(nstates)], np.float64)
# Normalize
from scipy.misc import logsumexp
log_probability -= logsumexp(log_probability)
# Now compute jump probability, only risking underflow (which is irrelevant)
probability = np.exp(log_probability)
```

**Comment by jchodera** [comment]
Also, maybe we should move this over to [`openmmtools`](https://github.com/choderalab/openmmtools) or some other live tested repo?

**Comment by msultan** [comment]
@jchodera thanks for jumping in here. yes, its the temperature jump probability. 
@peastman here is the test case https://www.dropbox.com/s/z97nuarf83w16iy/test.gz?dl=0

**Comment by msultan** [comment]
@peastman the system was setup using amber and then equilibrated for a ns. It has run for several hundred generations(5ns/gen) on fah without issues. I copied the starting xml files, reset the velocities, ran for a couple of steps to output the ```state.xml``` thats in the zipped up folder.

**Comment by msultan** [comment]
> ```python
nstates = len(self._weights)
# Always compute weights in log space
log_probability = np.array([ self._weights[i] - self.inverseTemperatures[i])*state.getPotentialEnergy() for i in range(nstates)], np.float64)
# Normalize
from scipy.misc import logsumexp
log_probability -= logsumexp(log_probability)
# Now compute jump probability, only risking underflow (which is irrelevant)
probability = np.exp(log_probability)
```

Trying this now

**Comment by jchodera** [comment]
Note that I modified the above example a bit. Make sure you got the version where I got rid of typos!

**Comment by msultan** [comment]
@jchodera shouldn't the log_p calculate the delta in weights and inv_t to the current state instead of the absolute values ala the original calculation?

**Comment by jchodera** [comment]
Nope. You'll notice the original weights drop out in the normalization, since the same factor gets multiplied into all elements of a vector that is subsequently normalized.

You can find more details in [our paper on simulated tempering](http://scitation.aip.org/content/aip/journal/jcp/135/19/10.1063/1.3660669).  Let me try to find the exact equation.

**Comment by jchodera** [comment]
See Section II.C and III.A.2

**Comment by jchodera** [comment]
Note that the Metropolized importance sampling (Section III.A.3) has slightly better mixing properties, so if you wanted to optimize this at the same time as fixing the numerical issues, you can switch to that scheme.  It is a bit more complicated, though, since it involves an accept/reject step instead of just an update step.

**Comment by msultan** [comment]
@jchodera thanks for the link to the paper. Reading it now and working through the logsumexp bit to convince myself the probabilities are the same.

**Comment by msultan** [comment]
@jchodera I think once we have base sampler working, i can add the MC step. Right now, i would just like to not crash out every 10ps.

**Comment by jchodera** [comment]
> Right now, i would just like to not crash out every 10ps.

LOL, sure

**Comment by msultan** [comment]
alright, i think the switching over to logsumexp has helped with the numerical stability a lot. Its up to 100ps and hasnt crashed yet. I am gonna leave it overnight for a longer test run. 

Thanks for the input @jchodera. I might have to bug you again when i try to get the metropolized importance sampler up and running.

**Comment by jchodera** [comment]
Feel free to bug away!

I will try to ingest that script into openmmtools this weekend.

I actually thought I had written a whole expanded ensemble sampler stack, but I can't recall where that went.  Are you just in need of simulated tempering or something more sophisticated?

**Comment by msultan** [comment]
I was curious to see what kind of sampling enhancement I could get and simulated tempering seems to be a [ good  ](http://pubs.acs.org/doi/abs/10.1021/acs.jctc.5b00913) starting point. I am not familiar with the more sophisticated versions so i cant really say. I have tried aMD and other simple techniques in the past but they weren't either as useful or required a tad too much hand holding/tinkering before they worked.

**Comment by jchodera** [comment]
Did you get this sorted out, @msultan?

Also, @peastman: Where should we put the updated script? `openmmtools`? Its own conda package?

**Comment by msultan** [comment]
thanks for swinging back on this @jchodera . Happy to report, this has been stable for several hundred nanoseconds now across several systems(albeit of approximately similar size). 

Fyi, the simtk [webrepo](http://wiki.simtk.org/openmm/VirtualRepository) has a bunch of other scripts and samplers. Moving just this one is could lead to some fragmentation.

**Comment by jchodera** [comment]
Hm. OK, thanks for pointing that out. We should probably discuss what to do with those things.

**Comment by msultan** [comment]
Gonna close this now.

**Comment by peastman** [comment]
Can you send me your modified version of the script?  I'll update it on the website.

**Comment by peastman** [comment]
@msultan I still need you to send me your modified script.

**Comment by msultan** [comment]
@peastman sorry about that, it completely slipped my mind. here is the script. the relevant changes start at lines 204-210
https://gist.github.com/msultan/46e19897069554cf59b37240a54f4ede

**Comment by peastman** [comment]
Thanks!  I've committed an updated version.  Could you test it out to make sure it works correctly?  I made a few changes from your version, mainly to eliminate the dependence on SciPy (which isn't required for OpenMM).

**Comment by jchodera** [comment]
Are we still housing this in the SimTK script repository?  Do we want to do anything about migrating it into OpenMM or somewhere it can be subjected to continuous integration testing?

**Comment by peastman** [comment]
Eventually, I think migrating it to OpenMM would be a good idea.  I'd like to see it get a lot more testing first though.  It hasn't been used a lot, so I don't have a lot of confidence in its robustness.

**Comment by jchodera** [comment]
This sounds like a "catch 22": 
* We can't include it because we haven't tested it much
* It isn't being automatically tested because it isn't in a repo (like OpenMM) that has automated testing

**Comment by jchodera** [comment]
It sounds like a good candidate for `openmmtools` or something.

**Comment by peastman** [comment]
Well, I *did* try to jump start that by announcing it in group meeting and asking people to try it out.  And that seems to have worked, because it immediately led to @msultan finding a bug! :)

Automated testing isn't the problem here.  I've verified that it works in some basic cases, and an automated test would verify that nothing causes those cases to break.  But what it really needs now is some time being used in production on real systems to turn up more subtle problems.

**Comment by msultan** [comment]
@peastman glad i could help :) . I am on slurm's low prio right now but I will test the new script and report back if it causes issues. The version i sent has been continuously running for 18 odd days so we should be okay.  
Also you are correct, this bug doesn't appear on smaller tests of NTL9, but I am not sure something else wont break once we get to >100k atom systems.

**Comment by jchodera** [comment]
> Automated testing isn't the problem here. I've verified that it works in some basic cases, and an automated test would verify that nothing causes those cases to break. But what it really needs now is some time being used in production on real systems to turn up more subtle problems.

This is why I have dozens of test systems in [`openmmtools.testsystems`](https://github.com/choderalab/openmmtools/blob/master/openmmtools/testsystems.py). If it works on those systems, it will probably work on your system.  If it breaks, you can probably quickly figure out why by looking at which simple test systems it broke on.

**Comment by msultan** [comment]
I am almost certainly missing something but why cant we do both? I like the idea of having it on ```openmmtools``` but with the github page to the python script linked on the simtk website.

**Comment by peastman** [comment]
openmmtools is something of John's.  I've never looked at it, and I don't really know what it is.

Eventually I'd like this to be merged into OpenMM itself.  But I still consider the code to be alpha quality, and it's possible we might decide to completely change the API.  So it's not quite ready for that yet.  Right now, I just want to get a few people trying to use it for real work so I can get some feedback on the design.

**Comment by adekanmi** [comment]
Am I missing something here - Isn't the molar gas constant in this script in j/molK and the pe in kj/mol?

**Comment by peastman** [comment]
It takes care of all unit conversions automatically.  That's the advantage of using quantities with explicit units attached to them.
