### ISSUE TITLE
Allow minimization tolerance used in Modeller.addHydrogens to be specified

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1456]
We're having an issue where adding hydrogens to a protein on the `CPU` platform takes so long (>10 min) that it times out on travis.

It would be useful if adding hydrogens did not take this long, or at least there was some way to specify a more realistic tolerance to the minimizer used in this step.

**Comment by peastman** [comment]
Are you certain that's the problem?  Can you provide a test case for it?

**Comment by jchodera** [comment]
I am certain that it stalls for ~10 min at the call to `addHydrogens` on travis:
https://travis-ci.org/choderalab/ensembler/builds/122125965#L1101-L1106

Let me make sure that `ensembler-dev` is up to date, and then you can reproduce this yourself locally with
```bash
conda install --yes ensembler-dev
nosetests -vv --nocapture ensembler.tests.test_refinement.test_refine_implicit_md_short
```
Or would you need a more minimal test case?

**Comment by peastman** [comment]
I can start with that.

**Comment by jchodera** [comment]
I've rebuilt the `ensembler-dev` package for you to try:
https://anaconda.org/omnia/ensembler-dev

You should be able to test with
```bash
conda install --yes ensembler-dev
nosetests -vv --nocapture ensembler.tests.test_refinement.test_refine_implicit_md_short
```

**Comment by peastman** [comment]
It's not finding it:

```
Error:  Package missing in current osx-64 channels: 
  - ensembler-dev

Did you mean one of these?

    ensembler
```

Is there anything special I need to do to make it find it?

**Comment by jchodera** [comment]
Oh, sorry!  omnia `dev` packages are generally only built for `linux`.

This is unfortunately hard to change because it requires updating all package dev frameworks.

**Comment by peastman** [comment]
Ok.  I can test it on a different computer tomorrow.

**Comment by peastman** [comment]
Here's the error I get trying to install it into miniconda (Python 3.5) on a Linux machine:

```
The following specifications were found to be in conflict:
  - anaconda-client (target=anaconda-client-1.3.1-py35_0.tar.bz2) -> clyent
  - anaconda-client (target=anaconda-client-1.3.1-py35_0.tar.bz2) -> python 2.7*|3.3*|3.4*|3.5*
  - anaconda-client (target=anaconda-client-1.3.1-py35_0.tar.bz2) -> requests
  - anaconda-client (target=anaconda-client-1.3.1-py35_0.tar.bz2) -> setuptools
  - clyent (target=clyent-1.2.1-py35_0.tar.bz2) -> python 2.7*|3.3*|3.4*|3.5*
  - clyent (target=clyent-1.2.1-py35_0.tar.bz2) -> setuptools
  - conda -> conda-env
  - conda -> pycosat
  - conda -> python 2.7*
  - conda -> pyyaml
  - conda -> requests
  - conda-env (target=conda-env-2.4.5-py35_0.tar.bz2) -> python 2.7*|3.3*|3.4*|3.5*
  - cython (target=cython-0.23.4-py35_0.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*
  - ensembler-dev -> python 2.7*
  - ensembler-dev -> pyyaml
  - nose (target=nose-1.3.7-py35_0.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*
  - numexpr (target=numexpr-2.4.6-np110py35_1.tar.bz2) -> numpy 1.10*|1.7*|1.8*|1.9*
  - numexpr (target=numexpr-2.4.6-np110py35_1.tar.bz2) -> python 2.7*
  - numpy (target=numpy-1.10.4-py35_1.tar.bz2) -> python 2.7*
  - pandas (target=pandas-0.18.0-np110py35_0.tar.bz2) -> python 2.7*
  - pandas (target=pandas-0.18.0-np110py35_0.tar.bz2) -> setuptools
  - pip (target=pip-8.1.0-py35_0.tar.bz2) -> python 2.7*
  - pip (target=pip-8.1.0-py35_0.tar.bz2) -> setuptools
  - pip (target=pip-8.1.0-py35_0.tar.bz2) -> wheel
  - pycosat (target=pycosat-0.6.1-py35_0.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*
  - pycrypto (target=pycrypto-2.6.1-py35_0.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*
  - pytables (target=pytables-3.2.2-np110py35_0.tar.bz2) -> numpy 1.10*|1.7*|1.8*|1.9*
  - pytables (target=pytables-3.2.2-np110py35_0.tar.bz2) -> python 2.7*
  - pytables (target=pytables-3.2.2-np110py35_0.tar.bz2) -> setuptools
  - python 3.5*
  - python-dateutil (target=python-dateutil-2.5.0-py35_0.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*
  - pytz (target=pytz-2016.1-py35_0.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*
  - pyyaml (target=pyyaml-3.11-py35_1.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*
  - requests (target=requests-2.9.1-py35_0.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*
  - scipy (target=scipy-0.17.0-np110py35_2.tar.bz2) -> numpy 1.10*|1.7*|1.8*|1.9*
  - scipy (target=scipy-0.17.0-np110py35_2.tar.bz2) -> python 2.7*
  - setuptools (target=setuptools-20.2.2-py35_0.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*
  - six (target=six-1.10.0-py35_0.tar.bz2) -> python 2.6*|2.7*|3.3*|3.4*|3.5*
  - wheel (target=wheel-0.29.0-py35_0.tar.bz2) -> python 2.7*|3.3*|3.4*|3.5*
Use "conda info <package>" to see the dependencies for each package.
```

I tried `conda info six`.  That lists many different versions, one of which depends on nothing except Python 3.5.

**Comment by rmcgibbo** [comment]
Do you have omnia in your channels, or can you try passing `-c omnia` to `conda install`?

**Comment by peastman** [comment]
I did include `-c omnia`.  It isn't complaining about the package not being found.  It's complaining about conflicts of some sort.

**Comment by rmcgibbo** [comment]
Perhaps the ensembler-dev package requires python 2.7 only?

**Comment by jchodera** [comment]
Sorry about that---only the py27 package is up:
https://anaconda.org/omnia/ensembler-dev/files

We haven't modernized it to support py34 or py35 yet, but I'll get on that.

**Comment by peastman** [comment]
Running on my computer and forcing it to use CPU platform in `addHydrogens()`, the entire `test_refinement.py` (including both implicit and explicit solvent tests) takes just over 6 minutes.  Of that time, probably only about half is spent adding hydrogens (and that is split between the two different tests).  That doesn't seem excessive to me.  If the issue is simply that travis is really slow, how about using a smaller system for the test case?

One thing I did notice is that `solvate_pdb()` in `refinement.py` is using an incredibly inefficient method of creating an exact number of waters.  Just specify `numAdded` when you call `Modeller.addSolvent()` instead.  That will probably save about a minute off the run time of the test.

**Comment by jchodera** [comment]
Thanks!

Three minutes to add hydrogens still seems pretty slow. Is it possible there is still value in allowing control over the minimization termination criterion? 

The `numAdded` flag didn't exist in `Modeller.addSolvent()` when Ensembler was written, but you're right---we should definitely be using that now.  I'll change that.

**Comment by peastman** [comment]
It's only about 1.5 minutes for each of the two tests.  You're calling it twice on two different systems.

Here's the important question: is it using more iterations than are actually needed to produce good positions?  If so, we should reduce that.  If not, I don't want to add a "produce bad results" option that exists solely to make one test case faster on travis.

**Comment by jchodera** [comment]
> Here's the important question: is it using more iterations than are actually needed to produce good positions? If so, we should reduce that. If not, I don't want to add a "produce bad results" option that exists solely to make one test case faster on travis.

That's certainly a reasonable approach. Also, if it needs 1.5 minutes to produce good results, is there any way we can speed that up? If we're just optimizing hydrogens, do we need sterics and electrostatics in the System, for example?

**Comment by peastman** [comment]
Actually, I do see a way to speed it up.  When it creates the System for minimizing, it's leaving the nonbonded method as the default (NoCutoff).  Switching that to CutoffNonPeriodic with a 1 nm cutoff saves a few minutes off the run time for the test suite.

> If we're just optimizing hydrogens, do we need sterics and electrostatics in the System, for example?

If you pass a ForceField object to `addHydrogens()`, it uses whatever you give it.  If you don't, it creates a minimal force field with just a weak repulsion between atoms plus some bond and angle restraints.

**Comment by jchodera** [comment]
> Switching that to CutoffNonPeriodic with a 1 nm cutoff saves a few minutes off the run time for the test suite.

Hydrogen bonds are incredibly local.  How about a 5 A cutoff or something very short?

**Comment by peastman** [comment]
Using too short a cutoff could lead to numerical issues from the discontinuity.

**Comment by jchodera** [comment]
Isn't there a switch enabled by default?

**Comment by peastman** [comment]
I tried reducing the cutoff from 10 to 5 A, but it had very little effect on the run time for the test.  I don't think that's the bottleneck anymore.

**Comment by jchodera** [comment]
Interesting!
