### ISSUE TITLE
Truncated octahedron

### ISSUE THREAD

**Issue by proteneer** [pandegroup/openmm#146]
I had a discussion with Leeping about this. Tinker can use a truncated octahedron to result in a 2x speedup (since the volume of the truncated octahedron is half that of the smallest enclosing cube). It actually wouldn't be too hard to implement from a purely algorithmic point of view. We wouldn't be able to support anisotropic barostats (but otherwise isotropic NPT,NVT,NVE should still all be valid), and this wouldn't be ideal for simulations that are intrinsically rectangular (eg membrane simulations). 

The hairy part is probably adding the API so that it's supported all of our kernels.

**Comment by peastman** [comment]
Closing this now that we have triclinic box support.
