### ISSUE TITLE
Funky parentheses in Python docs

### ISSUE THREAD

**Issue by swails** [pandegroup/openmm#1460]
See here: http://docs.openmm.org/7.0.0/api-python/generated/simtk.openmm.openmm.CustomCompoundBondForce.html#

Under methods, it has, for example:

```
__init__((self, numParticles, ...)
```

Not sure what the double-open parentheses are about...  Minor nitpick, though.

**Comment by peastman** [comment]
It looks a bit weird, but I think it's actually correct, for some definition of "correct".  When a method has a return value, it puts all the arguments in parentheses.  For example, 

```
getNumPerBondParameters((self) -> int)
```

If there isn't enough room in the summary table for all the arguments, it truncates the list and adds "...".  For example,

```
addGlobalParameter((self, name, ...)
```

which is a somewhat odd looking abbreviation for

```
addGlobalParameter((self, name, defaultValue) -> int)
```
