### ISSUE TITLE
Energy Component Analysis in OpenMM

### ISSUE THREAD

**Issue by leelasd** [pandegroup/openmm#1463]
I have been trying to compare energies between AMBER and OpenMM outputs for prmtop and inpcrd files. I have tried to obtain the energy contributions from bonds, angles etc, using  groups={i} options but it seems like all the components are grouped into bond force group.

AMBER ENERGIES are shown below
                    FINAL RESULTS

   NSTEP       ENERGY          RMS            GMAX         NAME    NUMBER
   2000      -1.4295E+02     3.1979E-02     1.0557E-01     C09        10

 BOND    =        2.2121  ANGLE   =        4.4624  DIHED      =       -1.7833
 VDWAALS =       -3.8619  EEL     =      -14.2438  HBOND      =        0.0000
 1-4 VDW =       12.1673  1-4 EEL =     -141.9045  RESTRAINT  =        0.0000

With OpenMM i got the following result
```
Energy at Minima is -142.910 kcal/mol
<simtk.openmm.openmm.NonbondedForce; proxy of <Swig Object of type 'OpenMM::NonbondedForce *' at 0x10989a750> > 0.0
<simtk.openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x10989a780> > 0.0
<simtk.openmm.openmm.HarmonicBondForce; proxy of <Swig Object of type 'OpenMM::HarmonicBondForce *' at 0x10989a6f0> > -142.909593765
<simtk.openmm.openmm.PeriodicTorsionForce; proxy of <Swig Object of type 'OpenMM::PeriodicTorsionForce *' at 0x10989a6c0> > 0.0
<simtk.openmm.openmm.HarmonicAngleForce; proxy of <Swig Object of type 'OpenMM::HarmonicAngleForce *' at 0x10989a690> > 0.0
<simtk.openmm.openmm.CustomNonbondedForce; proxy of <Swig Object of type 'OpenMM::CustomNonbondedForce *' at 0x10989a720> > 0.0
```

The code I used is shown below. I used the code suggested by @rmcgibbo  in #387 
```
import mdtraj as md
from simtk.openmm import app,KcalPerKJ
import simtk.openmm as mm
from simtk import unit as u
from sys import stdout,exit

def Minimize(simulation):
	simulation.minimizeEnergy(maxIterations=0)
	position = simulation.context.getState(getPositions=True).getPositions()
	energy=simulation.context.getState(getEnergy=True).getPotentialEnergy()
	app.PDBFile.writeFile(simulation.topology, position, open('gasmin.pdb', 'w'))
	print 'Energy at Minima is %3.3f kcal/mol'%(energy._value*KcalPerKJ)
	return simulation

def forcegroupify(system):
    forcegroups = {}
    for i in range(system.getNumForces()):
        force = system.getForce(i)
        force.setForceGroup(i)
        forcegroups[force] = i
    return forcegroups

def getEnergyDecomposition(context, forcegroups):
    energies = {}
    for f, i in forcegroups.items():
        energies[f] = context.getState(getEnergy=True, groups=2**i).getPotentialEnergy()
    return energies

temperature=298.15*u.kelvin
prmtop = app.AmberPrmtopFile('celeco.prmtop')
inpcrd = app.AmberInpcrdFile('celeco.inpcrd')
system = prmtop.createSystem(nonbondedMethod=app.NoCutoff, constraints=None)
integrator = mm.LangevinIntegrator(temperature, 1/u.picosecond,  0.0005*u.picoseconds)
simulation = app.Simulation(prmtop.topology, system, integrator)
simulation.context.setPositions(inpcrd.positions)
simulation=Minimize(simulation)
fgrps=forcegroupify(system)
tt= getEnergyDecomposition(simulation.context, fgrps)
for idd in tt.keys():
	print idd,tt[idd]._value /4.184
```

I also tried the method @peastman suggested in #1408 to use groups={0} option but it has all the potential energy and other force groups 1,2,3,4 have 0.00 kcal/mol energies.

Is there anyway to get the fix the issue. Any help would be great.

**Comment by swails** [comment]
You applied the force groups *after* you created the `Simulation` object from the original `System` (where everything is in the same force group -- 0).  Changing the `System` has no effect on any `Context` (which is part of a `Simulation`) that you already created.  You need to create *another* `Simulation` object after you call `forcegroupify` in order to get a `Context` that has the updated force groups.

However, note that this will *not* give you the same energy decomposition as what Amber gives you.  You'll get the bond, angle, and torsion to come out the same, but that's it.  The 1-4 vdW and 1-4 electrostatics will be combined with the vdW and electrostatics as the "nonbonded energy" in OpenMM.  

It's possible to get the full decomposition that Amber provides, but it's laborious.  You need to create separate nonbonded forces for each of the L-J and electrostatic terms (where the other ones are zeroed-out), and then copy the 1-4 exception parameters to separate `CustomBondForce` instances in order to separate out the 1-4 terms.  It would be a good exercise to help you learn the OpenMM API, for sure.

You may also be interested in ParmEd, which has short-cuts for a lot of these kinds of tasks.  For instance, it has a `energy_decomposition_system` that automates the procedure of separating force groups and computing each one, simply returning a list of the resulting energies for your convenience (and returning each force in the system to its original group before returning).

**Comment by leelasd** [comment]
Thanks @swails its a great help. I will change the code and see if it works. If you have any example script with Parmed energy decomposition analysis please let me know.

**Comment by swails** [comment]
```Python
import parmed as pmd

parm = pmd.load_file('prmtop', 'inpcrd')
system = parm.createSystem() # same arguments that OpenMM uses
print(pmd.openmm.energy_decomposition_system(parm, system))
```

Pretty simple :).  [The test scripts also have a lot of examples](https://github.com/ParmEd/ParmEd/blob/master/test/test_openmm_amber.py).

That script, used with the `ash.parm7` and `ash.rst7` files from the ParmEd test suite gives the following output:

```python
>>> import parmed as pmd
>>> parm = pmd.load_file('test/files/ash.parm7', 'test/files/ash.rst7')
>>> system = parm.createSystem()
>>> print(pmd.openmm.energy_decomposition_system(parm, system))
[('HarmonicBondForce', 5.443559276602916), ('HarmonicAngleForce', 2.8765904910063242), ('PeriodicTorsionForce', 24.36969052970657), ('NonbondedForce', -30.238225685706784), ('CMMotionRemover', 0.0)]
```
And here's what the sander API gives:
```python
>>> import sander
>>> inp = sander.gas_input(6)
>>> with sander.setup(parm, parm.coordinates, None, inp):
...     e, f = sander.energy_forces()
... 
>>> e.bond
5.443525282479646
>>> e.angle
2.8765824057874045
>>> e.dihedral
24.36969037672399
>>> e.elec + e.vdw + e.elec_14 + e.vdw_14
-30.235437059476325
```

So you can see that the agreement is quite good.  One of the nice things about ParmEd is that its objects work seamlessly with both the OpenMM and sander Python APIs in the same script.

**Comment by leelasd** [comment]
@swails it works wonderfully. I have a question regarding structure variable for `pmd.openmm.energy_decomposition_system(structure, system)` 
  I am creating the structure using using a PDB file but since PDB file has coordinates only up to  3 decimals I want to pass an array with up to 5 decimal points. 

Is there any way to set the coordinates to already created system. I could access the coordinates using `structure.get_coordinates()` but is there a way to set coordinates?

**Comment by swails** [comment]
@leelasd -- I'm not sure if you still had a question about the coordinates, so I'll answer it briefly here.

`structure.coordinates` is the attribute that contains the numpy array of atomic coordinates for all atoms in the Structure (with shape (natom, 3)).  If `structure` has knowledge of multiple frames, then `get_coordinates` will allow you to access frames other than the first frame (`structure.coordinates` always returns the first frame).

To set coordinates, just assign to the `structure.coordinates` attribute:

```python
structure.coordinates = some_array
```

That should do it.

**Comment by peastman** [comment]
@leelasd can this be closed?  As far as I can tell, everything discussed above has been resolved.

**Comment by leelasd** [comment]
@peastman sure !! I got this problem resolved
