### ISSUE TITLE
Turning off electrostatic force

### ISSUE THREAD

**Issue by isjoung** [pandegroup/openmm#1473]
Is there an easy way to turn off electrostatic interaction after creating `System`. My purpose is replacing electrostatic force with other customized force. Creating vdw-only customized force is quite annoying, so I want to use built-in `createSystem` methods. Easy solution for now is assigning 0 charges on all the atoms, but I guess the unnecessary charge calculations are still performed uselessly?

**Comment by peastman** [comment]
It's actually smart enough to skip the unnecessary calculations.  When you first create a Context it checks to see if any particles have nonzero charge.  If it find that all of them are zero, it \#ifdefs out that whole section of the kernel.  See https://github.com/pandegroup/openmm/blob/master/platforms/cuda/src/kernels/coulombLennardJones.cu.

**Comment by isjoung** [comment]
Oh, it looks great! Thank you for the answer.

For someone's reference,

```python
# Turning off electrostatic force
# AmberPrmtopFile
prmtop = app.AmberPrmtopFile('model.prmtop')
prmtop._prmtop.getCharges()
for i in xrange(len(prmtop._prmtop._chargeList)):
    prmtop._prmtop._chargeList[i] = 0.0
```

```python
# Turning off electrostatic force
# parmed
prmtop = pmd.load_file('model.prmtop')
for a in prmtop.atoms:
    a.charge = 0.0
```

I don't know if there is a better way, but it works.

**Comment by peastman** [comment]
The other way you could do it is to edit the NonbondedForce after you create your System (but before you create a Simulation or Context from it):

```Python
for force in system.getForces():
    if isinstance(force, NonbondedForce):
        for i in range(force.getNumParticles()):
            charge, sigma, epsilon = force.getParticleParameters(i)
            force.setParticleParameters(i, 0, sigma, epsilon)
        for i in range(force.getNumExceptions()):
            p1, p2, charge, sigma, epsilon = force.getExceptionParameters(i)
            force.setExceptionParameters(i, p1, p2, 0, sigma, epsilon)
```

**Comment by isjoung** [comment]
It looks more useful because it is not dependent on 'structure' object. Thank you.
