### ISSUE TITLE
Kinetic energies in OpenMM

### ISSUE THREAD

**Issue by ppxasjsm** [pandegroup/openmm#1474]
I am trying to compute some kinetic energies, but I might be missing something obvious where I am going wrong. I am trying to make sure that my NVE ensemble actually conserves energy, but if I compute kinetic energies manually this is not the case. The total energy computed via OpenMM conserves energy as expected. 
Below is some very simple code that is meant to check the computation of the kinetic energy:
```
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from sys import stdout

prmtop = AmberPrmtopFile('ethane.top')
inpcrd = AmberInpcrdFile('ethane.crd')
system = prmtop.createSystem(constraints=None)

integrator = VerletIntegrator(0.001*picoseconds)
platform = Platform.getPlatformByName('CPU')
simulation = app.Simulation(prmtop.topology, system, integrator, platform)
simulation.context.setPositions(inpcrd.positions)

simulation.context.setVelocitiesToTemperature(300*kelvin)
simulation.step(100)
final_nve_state = simulation.context.getState(getVelocities=True, getPositions=True, getEnergy=True)
positions = final_nve_state.getPositions()
velocities = final_nve_state.getVelocities()
print ("Energy computed from OpenMM %f [kJ/mol]" %(final_nve_state.getKineticEnergy().value_in_unit(kilojoule/mole)))
v2 = velocities.in_units_of(meter/second)
vsqrt = 0
Energy = 0.0
for i in range(len(v2)):
    vsqrt = velocities[i][0]**2/(meter**2/(second**2))
    vsqrt +=velocities[i][1]**2/(meter**2/(second**2))
    vsqrt +=velocities[i][2]**2/(meter**2/(second**2))
    m = system.getParticleMass(i)
    m = m.in_units_of(kilogram/mole)
    Energy+=0.5*(system.getParticleMass(i)/((kilogram/mole)))*vsqrt
print ("Energy computed manually %f [kJ/mol] " %(Energy/1000.0))
```
The output I get from this not consistent:
```
Energy computed from OpenMM 21.566885 [kJ/mol]
Energy computed manually 23.833002 [kJ/mol]
```
Is there a reason why I can't do a straight up \sum_i 0.5 * m_i * (v_{ix}^2+v_{iy}^2+v_{iz}^2) to compute the kinetic energy? I am using the latest version from the conda openMM build.

**Comment by Lnaden** [comment]
In the Verlet integrator, the positions are a half time step later than the velocities, so potential and kinetic energies are not at the same timestep (see the [OpenMM manual here](http://docs.openmm.org/7.0.0/userguide/theory.html#verletintegrator) for documentation on it). 

You will get a more accurate answer by computing the on-step velocity as the average velocities of two consecutive time steps.

**Comment by peastman** [comment]
VerletIntegrator uses a leapfrog algorithm, so the positions and velocities are offset from each other by half a step.  That means you're adding the potential energy at time t and the kinetic energy at time t-dt/2.  To get the velocities at time t, compute `v+0.5*dt*f/m`.

The one complication is that if you have constraints, those velocities may then end up with a component parallel to the constraint direction, so you need to project that out.  When you ask for the kinetic energy, it does all of that for you.  Here's the code used in the reference platform to do all of that:

https://github.com/pandegroup/openmm/blob/master/platforms/reference/src/ReferenceKernels.cpp#L164-L194

**Comment by ppxasjsm** [comment]
Ah yes of course! Thanks that makes sense!
