### ISSUE TITLE
GromacsTopFile, list index float type

### ISSUE THREAD

**Issue by thempel** [pandegroup/openmm#1481]
When using Gromacs setups, I get the following error message:

`File ".../simtk/openmm/app/gromacstopfile.py", line 817, in createSystem
    map.append(float(params[8+mapSize*((j+mapSize/2)%mapSize)+((i+mapSize/2)%mapSize)]))
TypeError: list indices must be integers or slices, not float`

Should be fixed easily by enforcing integer type for the list index of `params`. 

Thanks!

**Comment by peastman** [comment]
Looks like this is caused by the change in how division works between Python 2 and 3.  I believe the correct fix is to replace `mapSize/2` with `mapSize//2`.  We used to run the code through 2to3 when installing on Python 3, so that took care of this, but #1083 broke it.

**Comment by peastman** [comment]
@thempel could you verify that #1482 fixes the problem for you?

**Comment by rmcgibbo** [comment]
Sorry for breaking this. :(

**Comment by thempel** [comment]
@peastman Thanks, it works!

**Comment by peastman** [comment]
Thanks!  The fix is merged.
