### ISSUE TITLE
Error on mac with new cuda compiler plugin

### ISSUE THREAD

**Issue by jlmaccal** [pandegroup/openmm#1485]
I'm getting the following error on mac:
```
Exception: Error compiling program: nvrtc: error: failed to load builtins
```

I think this has to do with new JIT compilation, but I'm not sure what the issue is. Google doesn't turn up much.

**Comment by peastman** [comment]
I found one other person reporting the same problem: https://devtalk.nvidia.com/default/topic/920047/cuda-programming-and-performance/nvrtc-error-failed-to-load-builtins-on-linux.  For that person it worked on Mac but failed on Linux.  And the only reply was someone speculating it had to do with the libnvrtc-builtins library, which sounds reasonable, but who knows?

I don't have a Mac that supports CUDA.  Did you compile OpenMM yourself, or use a precompiled binary?  Is this happening in a Python or C++ program?  If the former, what Python are you using?  (Especially, is it the system Python or one you installed yourself?)  What OS and CUDA versions do you have?

**Comment by jlmaccal** [comment]
This was a library path issue.

**Comment by remaininlight** [comment]
@jlmaccal Do you mind expanding a little on how you fixed it please? I'm having the same issue and have nearly tried all of the permutations of DYLD_FALLBACK_LIBRARY_PATH, Runpath Search Paths and linking libnvrtc in different ways.

**Comment by peastman** [comment]
I've also run into this problem, in my case on a Linux system.  @jlmaccal what did you do to fix it?

**Comment by BLCKPSTV** [comment]
Indeed what is the fix? I've got same problems.
