### ISSUE TITLE
problem in energy/force calculation

### ISSUE THREAD

**Issue by isjoung** [pandegroup/openmm#1491]
I have a test code below:

```python
from __future__ import print_function
from simtk.openmm import app
import simtk.openmm as mm
from simtk import unit
from sys import stdout
import parmed as pmd
from scipy import optimize
import sander
import numpy as np

def openmm_min():
    prmtop = pmd.load_file('model.prmtop')
    inpcrd = pmd.load_file('avg.inpcrd')

    system = prmtop.createSystem(nonbondedMethod=app.NoCutoff, implicitSolvent=app.GBn2,
        nonbondedCutoff=99.9*unit.nanometers, constraints=None, rigidWater=False)

    integrator = mm.VerletIntegrator(0.002*unit.picoseconds)

    platform = mm.Platform.getPlatformByName('CPU')
    #properties = {'CudaPrecision': 'double'}
    #properties = {'OpenCLPrecision': 'double'}
    properties = {}
    simulation = app.Simulation(prmtop.topology, system, integrator, platform, properties)
    simulation.context.setPositions(inpcrd.positions)

    # openmm energy minimization
    def energy_function(var):
        simulation.context.setPositions(var.reshape(-1,3)) # nanometer
        state = simulation.context.getState(getEnergy=True, getForces=True)
        ene = state.getPotentialEnergy().value_in_unit(unit.kilojoule_per_mole)
        frc = state.getForces(asNumpy=True).value_in_unit(unit.kilojoule_per_mole/unit.nanometer)
        return ene, -frc.ravel()

    svar = inpcrd.coordinates.ravel() / 10.0
    min_result = optimize.minimize(energy_function, svar, method='L-BFGS-B',
                    jac=True, options=dict(maxiter=1000, disp=True, gtol=0.01))

def sander_min():
    prmtop = pmd.load_file('model.prmtop', 'avg.inpcrd')

    # sander energy minimization
    inp = sander.gas_input(8)

    def energy_function(var):
        sander.set_positions(var)
        ene, frc = sander.energy_forces()
        print(ene)
        return ene.tot, -np.array(frc)

    with sander.setup(prmtop, prmtop.coordinates, None, inp):
        min_result = optimize.minimize(energy_function, prmtop.coordinates, method='L-BFGS-B',
                        jac=True, options=dict(maxiter=1000, disp=True, gtol=0.01))
```

There are two subroutines, openmm_min and sander_min. The two subroutines simply minimize energy using the coordinates from 'avg.inpcrd'. One uses openmm force and the other uses sander force of AMBER. 'avg.inpcrd' is a MD-averaged structure. Most of the hydrogen atoms are smeared, which causes atomic clashes. I think minimizing averaged structure is a common task for recovering the smeared conformations.

To eliminate the effect of a minimizer, I used lbfgsb subroutine in scipy.

sander_min()
```
At iterate    0    f=  1.07107D+09    |proj g|=  8.67647D+09

At iterate    1    f=  4.04722D+07    |proj g|=  1.35299D+08

At iterate    2    f=  3.44126D+07    |proj g|=  1.09561D+08
...
At iterate   28    f= -8.72823D+03    |proj g|=  4.09985D+02

At iterate   29    f= -9.31306D+03    |proj g|=  1.17192D+02

At iterate   30    f= -9.72276D+03    |proj g|=  9.16953D+01
...
```

openmm_min() (CPU)
```
At iterate    0    f=          NaN    |proj g|=  0.00000D+00
```

openmm_min() (CUDA, double)
```
At iterate    0    f=  4.48139D+09    |proj g|=  2.14748D+09

At iterate    1    f=  2.72982D+08    |proj g|=  2.14748D+09

At iterate    2    f=  5.47217D+07    |proj g|=  2.14497D+09

At iterate    3    f=  3.48468D+07    |proj g|=  2.14344D+09

At iterate    4    f=  3.37860D+07    |proj g|=  2.14356D+09

At iterate    5    f=  6.06433D+06    |proj g|=  3.03968D+08

At iterate    6    f=  2.14383D+06    |proj g|=  1.17711D+07

At iterate    7    f=  1.99532D+06    |proj g|=  8.56851D+06

At iterate    8    f=  1.62495D+06    |proj g|=  3.73530D+06

At iterate    9    f=  1.44578D+06    |proj g|=  1.90574D+06

At iterate   10    f=  1.30399D+06    |proj g|=  8.93391D+05

At iterate   11    f=  1.20167D+06    |proj g|=  3.98668D+05

At iterate   12    f=  1.09659D+06    |proj g|=  1.47482D+05

At iterate   13    f=  9.37040D+05    |proj g|=  5.93197D+04

At iterate   14    f=  6.21726D+05    |proj g|=  3.55243D+04

At iterate   15    f=  3.16747D+05    |proj g|=  7.06646D+06

At iterate   16    f=  2.52442D+05    |proj g|=  2.14748D+09
  ys=-1.579E+08  -gs= 6.611E+05 BFGS update SKIPPED

 Bad direction in the line search;
```

With sander, there was no problem in energy minimization. With openmm CPU, the initial energy is not calculable. With openmm CUDA, line search fails at high energy state. I understand that CUDA platform might have difficulty in calculating forces, but why does CPU platform fail to calculate the energy?

Test files are attached.
[avgmin.tar.gz](https://github.com/pandegroup/openmm/files/265062/avgmin.tar.gz)

**Comment by jchodera** [comment]
CPU only supports single precision forces, and CUDA uses single precision
forces by default.

Can you minimize your system in double precision on CUDA? It isn't quite as
good as double precision on Reference, but may still work for minimization.

**Comment by jchodera** [comment]
Whoops, sorry---I had missed that double precision failed on CUDA!

**Comment by peastman** [comment]
The nan energy is coming from the CustomGBForce.  It seems to be specific to the GBn2 model.  If I instead specify GBn (or OBC2 or HCT) then the energy is huge but still finite, and the minimizer is able to bring it down pretty quickly.  @swails do you have any idea what it might be?

**Comment by swails** [comment]
> @swails do you have any idea what it might be?

Not really.  GBneck and GBneck2 both use the same general model, and the typical problems tend to arise through the one feature they share -- the 2-D lookup tables for the forces and energies.  So if GBn works but GBneck2 doesn't, I'm not sure what would cause that.

What happens if you take a GBn-minimized structure and then use GBn2 on it?  Do you still get NaNs?

**Comment by isjoung** [comment]
> What happens if you take a GBn-minimized structure and then use GBn2 on it? Do you still get NaNs?

First run with GBn:
```
...
At iterate   29    f= -3.15805D+04    |proj g|=  7.01543D+03

At iterate   30    f= -3.52672D+04    |proj g|=  1.93046D+04

At iterate   31    f= -3.76810D+04    |proj g|=  1.04429D+04

At iterate   32    f= -3.91192D+04    |proj g|=  5.82868D+03

           * * *
```

Energy calculated with the minimized conformation with GBn2:
```
{'nonbonded': -17452.71094537605, 'total': -9620.621183232897, 'angle': 2128.6089957970216, 'dihedral': 5413.022154704198, 'bond': 290.458601403612}
```
(This is parmed energy_decomposition result, so unit is different.)

Then, subsequent energy minimization using the conformation with GBn2:
```
At iterate    0    f=          NaN    |proj g|=  0.00000D+00
```

So, the answer is "Yes".

**Comment by swails** [comment]
The next thing I'd look at is the GBn2 per-atom parameters (there are separate alpha, beta, and gamma parameters for all atoms).  This is the main place where GBn2 differs from GBn.

If there are any "strange" atom types (strange for biomolecular simulations, that is), then you may have run into a scenario where parameters are not available specifically and the fallback defaults are wrong (perhaps there is a 0 in there or something giving rise to a NaN).  Looking at the program logic I don't see where or how that could happen, but testing is the only way to be sure.

**Comment by hainm** [comment]
@isjoung what's your atom names / residue names

```python
prmtop = pmd.load_file('model.prmtop')
print(set(atom.name for atom in prmtop.atoms))
print(set(res.name for res in prmtop.residues))
```

**Comment by swails** [comment]
[parameter assignment is done by element rather than by name](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/internal/customgbforces.py#L593-L604)

A lot of that logic is copied from ParmEd.  @isjoung -- are you using ParmEd's or OpenMM's prmtop parser to create the OpenMM System object?

**Comment by peastman** [comment]
There are three atom pairs for which the first computed value is coming out as nan: (1270, 1271), (3449, 3450), and (5628, 5629).  The nan is coming from the log function in this line:

https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/internal/customgbforces.py#L577

It computes `log(L/U)`.  Looking at the first of those pairs, `L` is 0.222921 and `U` is -0.00287232.  So their ratio is -77.61, and the log of any negative value is nan.  `U` is defined as `r+sr2`.  In this case, `r` is 0.110025 and `sr2` is -0.112896.

Is `sr` actually supposed to be negative?  If it is, then it looks to me like you'll get a nan whenever an atom gets closer than `-sr` to any other atom.

**Comment by swails** [comment]
> Is sr actually supposed to be negative? If it is, then it looks to me like you'll get a nan whenever an atom gets closer than -sr to any other atom.

GBn2 should never go NaN.  So there's a bug somewhere.  What atoms (elements) are those 6 pairs?

**Comment by swails** [comment]
@isjoung -- what do you get using igb=8 with Amber?  Does it blow up?

**Comment by hainm** [comment]
I think he said 

> With sander, there was no problem in energy minimization.

(use pysander)

**Comment by peastman** [comment]
Each of those three pairs consists of the SG and HG atoms of CYS residue.  Here's where it specifies that parameter should be negative for sulfur atoms:

https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/internal/customgbforces.py#L377

**Comment by isjoung** [comment]
> are you using ParmEd's or OpenMM's prmtop parser to create the OpenMM System object?

ParmEd

@swails: Isn't the number, -0.703469 in Angstrom?

**Comment by isjoung** [comment]
Can this fix on the following line work? 
https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/internal/customgbforces.py#L578
```
"U=max(r+sr2,1.0e-3);"
```
1.0e-3 is an arbitrarily picked small number. Assuming unit is handled correctly in here, I think this fix should be ok. I confirmed that the 'nan' error disappears if it is fixed in this way. However, my knowledge on this GB model is shallow so I would appreciate if anyone can confirm this fix.

**Comment by peastman** [comment]
I don't know much about the GBn model either.  Just looking at the equations, it looks to me like that parameter should never be negative, so I'd want to find out where that negative value for sulfur came from.

**Comment by hainm** [comment]
> negative value for sulfur came from.

Come from me. I did the best fit between GB and Poisson–Boltzmann energies with [Powell method](https://en.wikipedia.org/wiki/Powell's_method). There is no constraint for minimization so Sulfur got the negative value accidentally. I have never got issue in AMBER so really did not pay attention to sulfur much (its code is in AMBER from 2010 and no one reported issue too).

**Comment by hainm** [comment]
> Could you check whether Amber has the same problem?

@peastman from @isjoung original post, he did use both `sander` and `openmm` for minimizing. Here is his conclusion

> With sander, there was no problem in energy minimization. With openmm CPU, the initial energy is not calculable.

(if I understand about your comment correctly).

**Comment by hainm** [comment]
install `pysander`

```bash
conda install -c ambermd pysander
```

**Comment by isjoung** [comment]
```
Ivdw=step(r+sr2-or1)*0.5*(1/L-1/U+0.25*(r-sr2^2/r)*(1/(U^2)-1/(L^2))+0.5*log(L/U)/r);
```
Because of the first step function, `Ivdw` probably should be zero if `r+sr2-or1` is negative. That it, the rest of the equation needs not to be evaluated. I guess `or1` is always positive(?) and negative `r+sr2` means that the step function is zero. NaN is probably caused by the operation 0.0*NaN = NaN(?).

**Comment by peastman** [comment]
I think  you're right.  If so, the fix is easy.  Instead of multiplying by the step function, put it into a select().

**Comment by isjoung** [comment]
```
Ivdw=select(step(r+sr2-or1),0.5*(1/L-1/U+0.25*(r-sr2^2/r)*(1/(U^2)-1/(L^2))+0.5*log(L/U)/r),0.0);
```
Is this correct? `select` function is certainly less advertised. It looks like it is newly added in 7.0 version. I think many `step` functions have been used as an `if`-alternative, so most of them should be wrapped with `select` to enhance performance.

**Comment by isjoung** [comment]
Now, I compared energies between AMBER and OPENMM after applying the fix above.

This is the test code.
```python
from __future__ import print_function
from simtk.openmm import app
import simtk.openmm as mm
from simtk import unit
from sys import stdout
import parmed as pmd
from scipy import optimize
import sander
import numpy as np

prmtop = pmd.load_file('model.prmtop')
inpcrd = pmd.load_file('avg.inpcrd')

system = prmtop.createSystem(nonbondedMethod=app.NoCutoff, implicitSolvent=app.GBn2,
    nonbondedCutoff=99.9*unit.nanometers, constraints=None, rigidWater=False)
for i in xrange(system.getNumForces()):
    frc = system.getForce(i)
    frc.setForceGroup(i)
    if isinstance(frc,mm.CustomGBForce):
        gbgroup = i

integrator = mm.VerletIntegrator(0.002*unit.picoseconds)

platform = mm.Platform.getPlatformByName('CPU')
properties = {}
simulation = app.Simulation(prmtop.topology, system, integrator, platform, properties)
simulation.context.setPositions(inpcrd.positions)

inp = sander.gas_input(8)

def energy_function(var):
    # sander
    sander.set_positions(np.array(var)*10.0)
    ene, frc = sander.energy_forces()
    print('sander',ene.tot*4.184,ene.gb*4.184)

    # openmm
    simulation.context.setPositions(var.reshape(-1,3))
    state = simulation.context.getState(getEnergy=True, getForces=True)
    ene = state.getPotentialEnergy().value_in_unit(unit.kilojoule_per_mole)
    frc = state.getForces(asNumpy=True).value_in_unit(unit.kilojoule_per_mole/unit.nanometer)
    state = simulation.context.getState(getEnergy=True,groups={gbgroup})
    ene_gb = state.getPotentialEnergy().value_in_unit(unit.kilojoule_per_mole)
    print('openmm',ene,ene_gb)

    return ene, -frc.ravel()

svar = inpcrd.coordinates.ravel() / 10.0 # nanometer
with sander.setup(prmtop, inpcrd.coordinates, None, inp):
    min_result = optimize.minimize(energy_function, svar, method='L-BFGS-B',
                    jac=True, options=dict(maxiter=1000, disp=True, gtol=0.01))
```

This is the result.

```
At X0         0 variables are exactly at the bounds
sander 4481375120.94 -35513.8973641
openmm 4481392238.54 -18695.6356345

At iterate    0    f=  4.48139D+09    |proj g|=  3.63024D+11
sander 39752254.0758 -35700.9510802
openmm 39769066.9381 -18999.860305

At iterate    1    f=  3.97691D+07    |proj g|=  9.89972D+08
sander 32924860.0937 -35701.7887475
openmm 32941650.5527 -19000.6181834

At iterate    2    f=  3.29417D+07    |proj g|=  7.35099D+08
sander 17241005.7299 -35692.2059431
openmm 17257821.5674 -19004.6633936

At iterate    3    f=  1.72578D+07    |proj g|=  2.98169D+08
sander 10815696.7433 -35722.9879648
openmm 10832520.4189 -19009.413728

At iterate    4    f=  1.08325D+07    |proj g|=  1.59382D+08
sander 6618143.09251 -35725.2952045
openmm 6634969.66863 -19015.976595

At iterate    5    f=  6.63497D+06    |proj g|=  7.67748D+07
sander 4378376.1616 -35869.9533968
openmm 4395342.75667 -19023.3630029

At iterate    6    f=  4.39534D+06    |proj g|=  3.88675D+07
sander 3069843.22139 -35858.1231283
openmm 3086791.95297 -19032.6169631

At iterate    7    f=  3.08679D+06    |proj g|=  1.91181D+07
sander 2313435.94765 -35804.4136344
openmm 2330323.8336 -19044.4150361
...
```

The first energy is the total energy and the second one is GB energy. There is a significant difference in GB energy between sander and openmm. What could be the reason?

**Comment by jchodera** [comment]
OpenMM and AMBER use very different functions for the SASA penalty part of
GBSA. I am not sure how much of a discrepancy this leads to, but since the
functional forms are so wildly different, it may be a contributor.

I believe both OpenMM and sander allow you to set the SASA penalty to zero
to eliminate this difference. Can you give it a try with these set to zero?
In principle, this should then be computing the same GB contribution,
though I am not sure if AMBER groups the GB energy terms in exactly the
same way that OpenMM does.

**Comment by isjoung** [comment]
I found that the default behaviors for GBSA are different between Parmed and AmberPrmtopFile. Parmed turns off SASA but AmberPrmtopFile uses ACE by default. The result shown above is calculated using parmed so no SASA is involved. AMBER also does not use SASA unless it is specified. I confirmed that the control parameter for AMBER (gbsa) is zero (meaning no SASA).

I also compared parmed with AmberPrmtopFile. The result was almost identical if SASA is turned off.

**Comment by swails** [comment]
ParmEd has a useSASA argument that lets you turn it on and off.  I did this because I disliked having to hack AmberPrmtopFile at the source level to disable SASA (which, as you've found, is required for comparisons since Amber uses LCPO).  I tried to make the API as close to OpenMM's as possible, but I made some changes that seemed to me to be more intuitive from an Amber user's perspective.

Among the principal differences:
- default system unit cell dimensions set from inpcrd if you loaded them together
- each force assigned to separate group for easy energy decomposition
- SASA a configurable option off by default (same as Amber defaults)
- flexibleConstraints a configurable option (so you can evaluate bond energies with SHAKE on, like setting ntc=2, ntf=1)
- supports the 10-12 potential
- supports chamber-style topologies

**Comment by hainm** [comment]
It makes lot of sense to not use SASA in amber as default

- poor model
- no GPU code (our simulation is ten times slower if using gbsa=1).

**Comment by isjoung** [comment]
More tests

igb=1 (OBC1)
```
At X0         0 variables are exactly at the bounds
sander 4481390319.12 -20315.7086142
openmm 4481390743.75 -20190.4192703

At iterate    0    f=  4.48139D+09    |proj g|=  3.63024D+11
sander 39767373.6994 -20582.2127504
openmm 39767611.3366 -20456.3614456

At iterate    1    f=  3.97676D+07    |proj g|=  9.89972D+08
sander 32939981.0027 -20582.2149701
openmm 32940196.1727 -20456.3612098

At iterate    2    f=  3.29402D+07    |proj g|=  7.35099D+08
sander 17256119.387 -20582.1950131
openmm 17256373.6339 -20456.3260105

At iterate    3    f=  1.72564D+07    |proj g|=  2.98169D+08
sander 10830843.0816 -20581.9933646
openmm 10831079.102 -20456.1098686

At iterate    4    f=  1.08311D+07    |proj g|=  1.59382D+08
sander 6633293.81001 -20581.7273082
openmm 6633536.96632 -20455.8259509

At iterate    5    f=  6.63354D+06    |proj g|=  7.67749D+07
sander 4393673.19493 -20581.5452361
openmm 4393919.09402 -20455.6186357
...
At iterate   20    f=  8.54369D+04    |proj g|=  7.21336D+04
sander 11057475.7779 -19424.910034
openmm 11057596.604 -19312.944466
sander 42297.7608756 -19946.8056011
openmm 42411.1060703 -19831.7980791
...
```


igb=5 (OBC2)
```
At X0         0 variables are exactly at the bounds
sander 4481392652.29 -17982.5480215
openmm 4481393094.71 -17839.4577855

At iterate    0    f=  4.48139D+09    |proj g|=  3.63024D+11
sander 39769714.5554 -18241.55755
openmm 39769970.0058 -18097.9051996

At iterate    1    f=  3.97700D+07    |proj g|=  9.89972D+08
sander 32942322.1721 -18241.3537857
openmm 32942555.1467 -18097.6957579

At iterate    2    f=  3.29426D+07    |proj g|=  7.35099D+08
sander 17258461.5398 -18240.3450172
openmm 17258733.6841 -18096.6649726

At iterate    3    f=  1.72587D+07    |proj g|=  2.98169D+08
sander 10833186.6956 -18239.1775007
openmm 10833440.5618 -18095.4817738

At iterate    4    f=  1.08334D+07    |proj g|=  1.59382D+08
sander 6635638.84037 -18237.6948156
openmm 6635899.79925 -18093.9831161

At iterate    5    f=  6.63590D+06    |proj g|=  7.67748D+07
sander 4396019.4728 -18236.3002869
openmm 4396283.15615 -18092.5744067
...
At iterate   20    f=  9.17505D+04    |proj g|=  6.97756D+04
sander 138846.681016 -17628.7065785
openmm 138960.477006 -17509.0372727
sander 32390.423529 -17954.2958538
openmm 32510.1331355 -17832.9099808
...
```

Openmm results are constantly higher than AMBER results by a few hundreds.

igb=7 (GBn)
```
At X0         0 variables are exactly at the bounds
sander 4481389569.57 -21065.2608894
openmm 4481394831.49 -16102.6793524

At iterate    0    f=  4.48139D+09    |proj g|=  3.63024D+11
sander 39766607.6972 -21347.65915
openmm 39771682.227 -16384.9284758

At iterate    1    f=  3.97717D+07    |proj g|=  9.89972D+08
sander 32938862.4846 -21699.8820846
openmm 32944266.2521 -16385.4425478

At iterate    2    f=  3.29443D+07    |proj g|=  7.35099D+08
sander 17254736.241 -21959.9631297
openmm 17260435.4616 -16389.2108497

At iterate    3    f=  1.72604D+07    |proj g|=  2.98169D+08
sander 10829455.9588 -21962.8657513
openmm 10835135.5169 -16393.5527712

At iterate    4    f=  1.08351D+07    |proj g|=  1.59382D+08
sander 6631902.2408 -21966.8924428
openmm 6637586.91605 -16399.6224051

At iterate    5    f=  6.63759D+06    |proj g|=  7.67748D+07
sander 4392276.37061 -21971.5491084
openmm 4397961.93603 -16406.2040279
...
At iterate   20    f=  1.45133D+05    |proj g|=  5.73504D+04
sander 48289567.1967 -19881.2686993
openmm 48289363.1441 -19824.5144742
sander 321344.521593 -17116.6217466
openmm 321385.269466 -17073.5855798
sander 124142.714242 -17543.2611969
openmm 124190.754397 -17493.7188402
...
```

It looks like there are big differences in GBn and GBn2 when the energy is high. Maybe, it is because of the lookup table?
