### ISSUE TITLE
Warning - CUDA 7.5 not (yet) compatible with Xcode 7.3.x / clang on Mac OS X

### ISSUE THREAD

**Issue by jhprinz** [pandegroup/openmm#1493]
I get this error when trying to run openmm with CUDA 7.5 with the newest version of XCode 7.3.1 under MacOS X 10.11.5.

```
nvcc fatal   : The version ('70300') of the host compiler ('Apple clang') is not supported
```

There is some discussion for a workaround, but this is mostly an issue between Nvidia and Apple and is likely to be fixed in an upcoming update of CUDA 7.5. In the meantime [stackoverflow.com](http://stackoverflow.com/questions/36250949/revert-apple-clang-version-for-nvcc) might help.

This is mostly a warning not to upgrade to Xcode 7.3 when you really want to use CUDA.

**Comment by peastman** [comment]
Thanks!  That's good to know.

**Comment by jhprinz** [comment]
Latest version of CUDA SDK 7.5.30 seems to have fixed the problem. At least CUDA is back working on my MacBook Pro. I will close this since it seems to no longer be an issue.
