### ISSUE TITLE
Minor Install Issues

### ISSUE THREAD

**Issue by kyleabeauchamp** [pandegroup/openmm#1497]
I was following the conda installation instructions (http://docs.openmm.org/7.0.0/userguide/application.html#installing-with-conda) and ran into two issues.  First, I needed to manually export the plugin path before I could detect any non-reference platforms.  

```
export  OPENMM_PLUGIN_DIR=~/opt/lib/plugins/
```

Second, I needed to set the environment variable to specify my nonstandard nvcc path:

```
export OPENMM_CUDA_COMPILER=/usr/local/cuda-7.5/bin/nvcc
```

I did a text search and it seems there's no mention of either of these environment variables on the installation docs page.  I think they were previously mentioned in the 6.1 docs, so I think they somehow got dropped during some docs refactoring.

**Comment by kyleabeauchamp** [comment]
For the conda packaging, would it make sense to install the plugins to the `$PREFIX/lib` and include that path in the default plugin search?  That would save users from having to specify anything.

**Comment by rmcgibbo** [comment]
I don't think either of those should be required? The plugins should not
require a separte environment variable anymore. I thought I fixed that in
the conda package. Perhaps not...

Also, CUDA 7.5 includes the JIT compiler (OpenMMCudaCompiler.so, so I don't
think it should need to invoke NVCC anyways. Was the conda package not
compiled against the proper version of CUDA or not compiled with the
appropriate build option (OPENMM_BUILD_CUDA_COMPILER_PLUGIN) set?

On Sun, May 22, 2016 at 12:23 AM, Kyle Beauchamp <notifications@github.com>
wrote:

> For the conda packaging, would it make sense to install the plugins to the
> $PREFIX/lib and include that path in the default plugin search? That
> would save users from having to specify anything.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pandegroup/openmm/issues/1497#issuecomment-220813597>
>



-- 
-Robert

**Comment by kyleabeauchamp** [comment]
OK, you may be right about the JIT.  Here are some more details:

```
In [1]: import simtk.openmm as mm

In [2]: mm.__version__
Out[2]: '7.0'


$python -m simtk.testInstallation
There are 1 Platforms available:

$export  OPENMM_PLUGIN_DIR=~/opt/lib/plugins/
$ python -m simtk.testInstallation
There are 4 Platforms available:

```

**Comment by jchodera** [comment]
Could you accidentally have two versions of OpenMM installed at once?

**Comment by jchodera** [comment]
You can us `simtk.openmm.Platform.getPluginLoadFailures()` to print a list of messages describing why each platform failed to load---this might help us track down the issue after you make certain you only have one version of OpenMM installed.

**Comment by jchodera** [comment]
Also, I'm a bit confused as to why your OpenMM plugins would get installed into `~/opt/lib/plugins/`.  Is your anaconda/miniconda installation actually called `~/opt`?

**Comment by kyleabeauchamp** [comment]
Fixed it.  I didn't have an old install, but I had an old environment variable.  Thanks!
