### ISSUE TITLE
How can we implement separate solute/solvent updates in CustomIntegrator?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1498]
I've been looking at implementing the new [g-BAOAB integrator](http://dx.doi.org/10.1098/rspa.2016.0138) from Ben Leimkuhler and Charles Matthews. This integrator has some very interesting properties---and claims [to permit timesteps up to 9 fs](http://d1czgh453hg3kg.cloudfront.net/content/royprsa/472/2189/20160138/F2.large.jpg), but utilizes a multiple timestep scheme in which the explicit solvent degrees of freedom are updated independently from the solute degrees of freedom.

I think we may need to extend `CustomIntegrator` in order to be able to update solute and solvent degrees of freedom separately, and wanted to see what @peastman and others thought might be the simplest and most flexible way to do this.

Some ideas:
* Allow a way to restrict which particles a given computation step applies to.  For example, we could add an optional argument that restricts the atoms to which `addComputePerDof` applies to:
```python
solvent_atoms = [ atom.index for atom in topology.atoms() if (atom.residue.name == 'HOH') ]
solute_atoms = [ atom.index for atom in topology.atoms() if (atom.residue.name != 'HOH') ]
...
# outer kick updates solvent
integrator.addComputePerDof("v", "v+0.5*dt*f1/m", solvent_atoms)
for inner_step in range(ninner):   
    # inner step updates solute
    integrator.addComputePerDof("v", "v+0.5*(dt/4)*f0/m", solute_atoms)
    integrator.addComputePerDof("x", "x+(dt/4)*v", solute_atoms)
    integrator.addComputePerDof("v", "v+0.5*(dt/4)*f0/m", solute_atoms)
# outer kick updates solvent
integrator.addComputePerDof("v", "v+0.5*dt*f1/m", solvent_atoms)
```
* Add control flow blocks that restrict which atoms the following instructions apply to
```python
# outer step updates solvent
integrator.beginSubsetBlock(solvent_atoms)
integrator.addComputePerDof("v", "v+0.5*dt*f1/m")
integrator.endBlock();
# inner step updates solute
integrator.beginSubsetBlock(solute_atoms)
for inner_step in range(ninner):   
    integrator.addComputePerDof("v", "v+0.5*(dt/4)*f0/m")
    integrator.addComputePerDof("x", "x+(dt/4)*v")
    integrator.addComputePerDof("v", "v+0.5*(dt/4)*f0/m")
integrator.endBlock();
# outer kick updates solvent
integrator.beginSubsetBlock(solvent_atoms)
integrator.addComputePerDof("v", "v+0.5*dt*f1/m")
integrator.endBlock();
```
* In a manner similar to `CustomNonbondedForce`, allow the user to set per-particle parameters that can then be used in the standard `addComputePerDof` updates. This could allow something like
```python
integrator.addPerParticleParameter('is_solvent')
for atom in topology.atoms():
   is_solvent = 1 if (atom.residue.name == 'HOH') else 0
   integrator.addParticle([is_solvent])
...
# outer kick updates solvent
integrator.addComputePerDof("v", "v+is_solvent*0.5*dt*f1/m")
for inner_step in range(ninner):   
    # inner step updates solute
    integrator.addComputePerDof("v", "v+(1-is_solvent)*0.5*(dt/4)*f0/m")
    integrator.addComputePerDof("x", "x+(1-is_solvent)*(dt/4)*v")
    integrator.addComputePerDof("v", "v+(1-is_solvent)*0.5*(dt/4)*f0/m")
# outer kick updates solvent
integrator.addComputePerDof("v", "v+is_solvent*0.5*dt*f1/m")
```

**Comment by peastman** [comment]
> allow the user to set per-particle parameters that can then be used in the standard addComputePerDof updates.

You can already do exactly that with a per-DOF parameter.  The only difference is that you specify a Vec3 instead of a scalar for each particle, so just set all three components to the same value.

**Comment by jchodera** [comment]
Ah, through [`setPerDofVariable()`](http://docs.openmm.org/7.0.0/api-python/generated/simtk.openmm.openmm.CustomIntegrator.html#simtk.openmm.openmm.CustomIntegrator.setPerDofVariable)!  I hadn't realized this existed.

So I would use something like this?
```python
values = list()
for atom in topology.atoms():
   value = Vec3(1,1,1) if (atom.residue.name == 'HOH') else Vec3(0,0,0)
   values.append(value)
integrator.addPerDofVariable('is_solvent', 0)
integrator.setPerDofVariableByName('is_solvent', values)
...
# outer kick updates solvent
integrator.addComputePerDof("v", "v+is_solvent*0.5*dt*f1/m")
for inner_step in range(ninner):   
    # inner step updates solute
    integrator.addComputePerDof("v", "v+(1-is_solvent)*0.5*(dt/4)*f0/m")
    integrator.addComputePerDof("x", "x+(1-is_solvent)*(dt/4)*v")
    integrator.addComputePerDof("v", "v+(1-is_solvent)*0.5*(dt/4)*f0/m")
# outer kick updates solvent
integrator.addComputePerDof("v", "v+is_solvent*0.5*dt*f1/m")
```

**Comment by peastman** [comment]
Exactly.

**Comment by jchodera** [comment]
Thanks!
