### ISSUE TITLE
ForceField can get stuck in an infinite recursion in _findAtomMatches

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1503]
I've run into some unexpected behavior with `ForceField` where, for some `Topology` and residue template combinations, it appears that `_findAtomMatches` can get stuck in an infinite recursion or loop.  The attached example demonstrates this (attached with necessary input files in a tarball):
```python
from simtk.openmm import app
import cPickle as pickle

topology = pickle.load(open('topology.pkl', 'r'))
forcefield = app.ForceField('tip3p.xml', 'amber99sbildn.xml', 'gaff.xml', 'Imatinib-epik-charged.ffxml')
print('Creating System...')
system = forcefield.createSystem(topology, nonbondedMethod=app.CutoffPeriodic)
```
It will never terminate, and `ctrl-c` gives the stack trace:
```
^CTraceback (most recent call last):
  File "forcefield-bug.py", line 7, in <module>
    system = forcefield.createSystem(topology, nonbondedMethod=app.CutoffPeriodic)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 769, in createSystem
    [template, matches] = self._getResidueTemplateMatches(res, bondedToAtom)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 570, in _getResidueTemplateMatches
    matches = _matchResidue(res, t, bondedToAtom)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 1046, in _matchResidue
    if _findAtomMatches(atoms, template, bondedTo, externalBonds, matches, hasMatch, 0):
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 1070, in _findAtomMatches
    if _findAtomMatches(atoms, template, bondedTo, externalBonds, matches, hasMatch, position+1):
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 1070, in _findAtomMatches
    if _findAtomMatches(atoms, template, bondedTo, externalBonds, matches, hasMatch, position+1):
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 1070, in _findAtomMatches
    if _findAtomMatches(atoms, template, bondedTo, externalBonds, matches, hasMatch, position+1):
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 1070, in _findAtomMatches
    if _findAtomMatches(atoms, template, bondedTo, externalBonds, matches, hasMatch, position+1):
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 1070, in _findAtomMatches
    if _findAtomMatches(atoms, template, bondedTo, externalBonds, matches, hasMatch, position+1):
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 1070, in _findAtomMatches
    if _findAtomMatches(atoms, template, bondedTo, externalBonds, matches, hasMatch, position+1):
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 1070, in _findAtomMatches
    if _findAtomMatches(atoms, template, bondedTo, externalBonds, matches, hasMatch, position+1):
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 1070, in _findAtomMatches
    if _findAtomMatches(atoms, template, bondedTo, externalBonds, matches, hasMatch, position+1):
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 1060, in _findAtomMatches
    atom = template.atoms[i]
KeyboardInterrupt
```

[forcefield-bug.zip](https://github.com/pandegroup/openmm/files/287527/forcefield-bug.zip)

**Comment by jchodera** [comment]
Here's the molecule (in `mol2` format) at the end of the `Topology` object that is causing trouble:
[molecule.zip](https://github.com/pandegroup/openmm/files/287532/molecule.zip)

**Comment by swails** [comment]
Shouldn't this throw a max recursion depth exceeded error?

**Comment by swails** [comment]
Eventually of course it'll segfault if it's really infinite recursion and you've disabled the max recursion depth check.

**Comment by jchodera** [comment]
I haven't seen that, so I suspect somehow there is a finite recursion depth reached by the behavior of the function calls are somehow periodic.

**Comment by jchodera** [comment]
I'll note that this may be a tough case because the molecules in the `ffxml` file are all protomers of the same molecule---the location of 1-2 protons are just moving around.

**Comment by jchodera** [comment]
If I replace the hurts-my-brain graph matching implementation in `forcefield.py` (`_matchResidue()` and `_findAtomMatches()`) with a short piece of code that uses the graph isomorphism matching from `NetworkX` (a conda-installable Python efficient graph library with huge userbase), I can confirm this problem goes away:
```python
def _matchResidueNX(res, template, bondedToAtom):
    """Determine whether a residue matches a template and return a list of corresponding atoms.

    This implementation uses NetworkX for graph isomorphism determination.

    Parameters
    ----------
    res : Residue
        The residue to check
    template : _TemplateData
        The template to compare it to
    bondedToAtom : list
        Enumerates which other atoms each atom is bonded to

    Returns
    -------
    list
        a list specifying which atom of the template each atom of the residue
        corresponds to, or None if it does not match the template

    TODO
    ----
    This code is made unnecessarily complex by the lack of consistency in interface between _TemplateData residues and topology.Residue objects.
    _TemplateData could use a complete overhaul to eliminate inconsistencies with Topology.

    """
    import networkx as nx

    # Build list of external bonds for residue
    number_of_external_bonds = { atom : 0 for atom in res.atoms() }
    for bond in res.external_bonds():
        if bond[0] in number_of_external_bonds: number_of_external_bonds[bond[0]] += 1
        if bond[1] in number_of_external_bonds: number_of_external_bonds[bond[1]] += 1

    # Residue graph
    residue_graph = nx.Graph()
    for atom in res.atoms():
        residue_graph.add_node(atom, element=atom.element, number_of_external_bonds=number_of_external_bonds[atom])
    for bond in res.internal_bonds():
        residue_graph.add_edge(bond[0], bond[1])

    # Template graph
    template_graph = nx.Graph()
    for atom in template.atoms:
        template_graph.add_node(atom, element=atom.element, number_of_external_bonds=atom.externalBonds)
    for bond in template.bonds:
        bond = (template.atoms[bond[0]], template.atoms[bond[1]]) # for some reason, the template uses indices in bonds instead of atoms
        template_graph.add_edge(bond[0], bond[1])

    # Determine graph isomorphism
    from networkx.algorithms import isomorphism
    graph_matcher = isomorphism.GraphMatcher(residue_graph, template_graph)
    if graph_matcher.is_isomorphic() == False:
        return None

    # Translate to local residue atom indices
    atom_index_within_residue = { atom : position for (position, atom) in enumerate(res.atoms()) }
    atom_index_within_template = { atom : position for (position, atom) in enumerate(template.atoms) }
    matches = { atom_index_within_residue[residue_atom] : atom_index_within_template[template_atom] for (residue_atom, template_atom) in graph_matcher.mapping.iteritems() }
    return matches
```
I know there is a general reluctance to add external dependencies to OpenMM, but I really don't think we should be "rolling our own" graph library when there are perfectly serviceable, robust, efficient, conda-installable options out there.

Note that my implementation doesn't include the puzzling inclusion of atom name matching when the atoms are dummy atoms (why was that there anyway?),
```python
((atom.element is not None and atom.element == elem) or (atom.element is None and atom.name == name))
```
but this can easily be included in the node matching function if so desired.

**Comment by jchodera** [comment]
If we actually do want to switch to the NetworkX implementation, I'm happy to open a pull request to make the necessary changes. Let me know.

Initially, this was just an attempt to determine whether one of my other inputs (topology, ffxml, etc.) was crazy, but it was indeed the graph-matching algorithm that was broken. Given that, I'm in favor of replacing any graph-matching with NetworkX functions.

**Comment by jchodera** [comment]
I've added a test for this issue [here](https://github.com/pandegroup/openmm/pull/1506).

**Comment by jchodera** [comment]
It looks like this recursion may not actually be infinite. I forgot to update the code on the cluster and it seemed to complete after an hour. An hour still seems like a long time to parameterize a molecule of a few dozen atoms, though.

**Comment by peastman** [comment]
> Note that my implementation doesn't include the puzzling inclusion of atom name matching when the atoms are dummy atoms (why was that there anyway?),

That's needed when a residue contains multiple non-equivalent virtual sites.  You can't match them by bonds, because virtual sites don't have bonds.  This comes up in the CHARMM polarizable force field, for example.

I'll take a look at that library to see what algorithm they're using.

**Comment by jchodera** [comment]
You can find more information about the `networkx` graph isomorphism algorithms [here](https://networkx.github.io/documentation/networkx-1.10/reference/algorithms.isomorphism.vf2.html).

You can [define your own functions](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.algorithms.isomorphism.GraphMatcher.__init__.html#networkx.algorithms.isomorphism.GraphMatcher.__init__) to check node equivalence in the `networkx` implementation.

> You can't match them by bonds, because virtual sites don't have bonds.

What about adding a concept of "virtual bonds", or does the concept of virtual sites being associated with particular atomic sites not even exist in this case?

I do think there could be advantages to using a robust code like `networkx` instead of rolling our own. A lot of development has gone into it that we could take advantage of...

**Comment by jchodera** [comment]
I think there are also some opportunities to speed up `ForceField.createSystem()` for cases (like ours) where multiple related systems must be created in the course of program execution. Once you decide on a fix for this, I can do some profiling and see what the easiest things to speed up might be. For example, caching the residue template and atom matches might be a very simple way to speed things up for the case where the systems may only differ by which small molecule or protonation state is present (like our case).

**Comment by jchodera** [comment]
What's the plan here?

**Comment by peastman** [comment]
I'll look into it when I have time.  I've been working on other things.

**Comment by jchodera** [comment]
Understood.  Note that I've given you a working solution, but you never responded about whether or not you wanted to avoid dependencies like `networkx`. I'm happy to create a PR to fix this if you're OK with adding the dependency.

**Comment by peastman** [comment]
Definitely avoid dependency on networkx.  But we may still be able to use the same algorithm they're using.

**Comment by jchodera** [comment]
OK, I can't help then.

**Comment by peastman** [comment]
No problem.  I'll try to get to it soon.

**Comment by peastman** [comment]
I implemented one optimization, and your test now completes in about 2.5 minutes on my laptop.  I'll see what else I can do.  How long does the networkx version take?

**Comment by jchodera** [comment]
11.3 seconds.

**Comment by jchodera** [comment]
This is on my old 1.7GHz Intel Core i7 MacBook Air.

**Comment by peastman** [comment]
Ok.  I have it down to 84 seconds at this point, but it sounds like there should be room for further improvement.

Networkx is actually solving a slightly simpler problem, because it assumes the graph is fully connected.  That won't be the case for residues involving virtual sites, and possibly in other situations too.

**Comment by peastman** [comment]
Ok, I got it down to 0.8 seconds.  Hopefully that will be fast enough for you. :)

**Comment by jchodera** [comment]
LOL. That is acceptable, yes. :)
