### ISSUE TITLE
Memory leak and significantly decreased simulation speed on GPU platform when using parmed.openmm.NetCDFReporter

### ISSUE THREAD

**Issue by xxffliu** [pandegroup/openmm#1513]
Hi,

I observed a memory leak on GPU platform when I use NetCDF trajectory reporter from ParmED. The memory cost tumbled from about 400MB to nearly 2.0GB and the simulation speed dropped gradually but very obviously. There is no such issue when I swapped back to native app.DCDReporter.

I attached the simulation script and PDB file I tested with. Also attached the data report from two simulations with NetCDF and DCD reporter, respectively. The OpenMM I used is version 7.0.1, parmed 2.5.1

Much appreciated for your help.

[test.zip](https://github.com/pandegroup/openmm/files/306911/test.zip)

**Comment by xxffliu** [comment]
BTW here is the GPU hardware information

| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K40m          On   | 0000:09:00.0     Off |                  Off |
| N/A   21C    P8    19W / 235W |     56MiB / 12287MiB |      0%   E. Process |

**Comment by swails** [comment]
See parmed/parmed#619

The solution here is to use a different NetCDF library for writing the files.

**Comment by jchodera** [comment]
Oh!  OpenMM doesn't use the `conda` `netcdf4` package already?

**Comment by swails** [comment]
Scipy parses faster than netcdf4 and is more commonly installed. 

Openmm doesn't write NetCDF at all. The op was using parmed to do that.

**Comment by xxffliu** [comment]
Thank you. Glad to know the issue has been aware of and can be fixed (though there were lot of historical concerns). I will stick to DCDReporter for now.

**Comment by swails** [comment]
For what it's worth, the latest version of ParmEd on GitHub addresses the performance degradation of the NetCDFReporter.

I think this issue can be closed now, as the problem is decidedly not with OpenMM in the first place.
