### ISSUE TITLE
Openmm compile with error "TestCudaAmoebaAngleForce.cpp(303) : error C2065: 'M_PI' : undeclared identifier" on Windows

### ISSUE THREAD

**Issue by Jack00112** [pandegroup/openmm#1515]
Penomenon:
Openmm compile with error "TestCudaAmoebaAngleForce.cpp(303) : error C2065: 'M_PI' : undeclared identifier" on Windows

Environment:
vs2010 sp1
Windows 7 x64
Openmm verson: Branch master latest

Step to reproduce:
1. Install CMAKE 3.4.0 for windows
2. Generate "NMake Makefiles" by CMAKE for vs2010
2. run script "nmake BUILD=Release"

Workaround:
Add  code as below in TestCudaAmoebaAngleForce.cpp
#define _USE_MATH_DEFINES
#include <math.h>

**Comment by peastman** [comment]
Thanks!  I just submitted a PR with the fix.
