### ISSUE TITLE
Did docs for simtk.unit go away?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1523]
I'm trying to find the docs for `simtk.unit` in the [current OpenMM API docs](http://docs.openmm.org/7.0.0/api-python/index.html), and it doesn't seem like they are still there. Searching for, for example, `Quantity` doesn't appear to bring anything up either.

**Comment by peastman** [comment]
It looks like it.  That must have happened as a side effect of the conversion from Doxygen to Sphinx.
