### ISSUE TITLE
Stuck at creating system after the fastmatching update

### ISSUE THREAD

**Issue by yudongqiu** [pandegroup/openmm#1527]
Dear Developers,

I found that after the update of fastmatching (88f19a95ddbe74ec59971f71c9bf76cfa46e3978) on Jun 15th, my simulations starts to get stuck at the creating system step. I waited for a couple of hours and it is still not proceeding. Using Ctrl+C to interrupt the program gives me this message:

`...`
`  File "/home/qyd/codes/anaconda2/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 1354, in _findAtomMatches`
`    if _findAtomMatches(template, bondedTo, matches, hasMatch, candidates, position+1):`
`  File "/home/qyd/codes/anaconda2/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 1354, in _findAtomMatches`
`    if _findAtomMatches(template, bondedTo, matches, hasMatch, candidates, position+1):
KeyboardInterrupt`

There are hundreds of the same message and I'm suspecting the new function somehow got stuck in a infinite loop in my case. The previous versions of OpenMM before the Jun. 15th updates do not have this issue.

I have attached related files for repreducing the problem. To run the simulation, I used the command
`python OpenMM-MD.py input.pdb amoeba.xml -I short.in `

Thanks,

Yudong Qiu

[attachment.zip](https://github.com/pandegroup/openmm/files/339781/attachment.zip)

**Comment by peastman** [comment]
Was it actually able to match it before that update?  Just looking at that molecule makes my head hurt, trying to figure out how one could possibly match it in a reasonable amount of time!  Over 700 atoms in a single residue, all of the same element, most of them with identical bonds.

**Comment by jchodera** [comment]
You mean graphite (hexagonal planar carbon)?
![graphite](https://cloud.githubusercontent.com/assets/3656088/16462292/8feb26bc-3dfe-11e6-857a-09c69638604d.png)

**Comment by peastman** [comment]
Exactly.  That's a pretty brutal case for any graph matching algorithm to deal with.

**Comment by peastman** [comment]
I think I have something that works.  PR should be coming shortly.

**Comment by yudongqiu** [comment]
Thanks a lot! 

It was able to match it within a short amount of time (20s) before the update. The previous output is attached:
[orig_output.txt](https://github.com/pandegroup/openmm/files/339885/orig_output.txt)

**Comment by peastman** [comment]
I'm really mystified by how it was able to do that.  It may have just been luck, perhaps because the atoms happened to be listed in exactly the same order in the PDB file and the XML file.  With the new update, it's able to match everything in about 3 seconds.

**Comment by yudongqiu** [comment]
I guess your are right because I did list the atoms of the huge residue in exact the same order in the PDB file and the XML file.
