### ISSUE TITLE
Swig version parsing problem

### ISSUE THREAD

**Issue by rmcgibbo** [pandegroup/openmm#1529]
When using swig 3.0.10, I see a message that says `Swig version must be 3.0.5 or greater! (You have 3.0.10)`. I think I wrote that code -- I suspect I stupidly was sorting in alphabetical order rather than numerical order or something.

**Comment by peastman** [comment]
It's doing a simple string comparison:

```
string(COMPARE LESS "${SWIG_VERSION}" "3.0.5" SWIG_VERSION_ERROR)
```

**Comment by peastman** [comment]
It looks like CMake has specific support for comparing version numbers, so we can just change that to

```CMake
if (SWIG_VERSION VERSION_LESS "3.0.5")
```

or something similar.  See https://cmake.org/cmake/help/v3.0/command/if.html.

**Comment by ProkopHapala** [comment]
I have still this problem (on Ubuntu 16.04) I just installed swig 3.0.8 but. I tried both clone your `master` branch and download latest 7.1 releas ... both gives this error on `cmake`

**Comment by peastman** [comment]
This problem was fixed almost a year ago.  If you're running into a problem, it's something different.  Please open a new issue, with details of exactly what you're doing and what error message you're getting.
