### ISSUE TITLE
CustomNonbondedForce not compatible with Amoeba Forces?

### ISSUE THREAD

**Issue by yudongqiu** [pandegroup/openmm#1532]
Dear Developers,

I tried to implement a CustomNonbondedForce in my system of study containing amoeba water molecules. When creating the system, I got this error message:

```
10:37:34 - Creating the Simulation object
Traceback (most recent call last):
  File "/home/qyd/codes/bin/OpenMM-MD.py", line 1230, in <module>
    simulation = Simulation(modeller.topology, system, integrator, platform)
  File "/home/qyd/codes/anaconda2/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 103, in __init__
    self.context = mm.Context(self.system, self.integrator, platform)
  File "/home/qyd/codes/anaconda2/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 4275, in __init__
    this = _openmm.new_Context(*args)
Exception: All Forces must have identical exceptions
```

Could you please help me to take a look? I have attached the related files and I used this command to run OpenMM:

`python OpenMM-MD.py c-water.pdb simple.xml`

Thanks,

Yudong QIu

[test.zip](https://github.com/pandegroup/openmm/files/340485/test.zip)

**Comment by peastman** [comment]
The error is essentially what it says: the CUDA platform requires that you have identical sets of exceptions/exclusions for all nonbonded forces.  In your `<CustomNonbondedForce>` tag you specify `bondCutoff='0'`.  First, that's incorrect syntax.  XML files require double quotes.  Second, assuming the parser manages to figure out what you mean, that will tell it not to exclude any interactions, which won't match the AmoebaMultipleForce.  I *think* if you specify `bondCutoff="4"` that will work.  AmoebaMultipoleForce represents exceptions a bit differently than other ones.  They're stored in the form of "covalent maps", and the largest map is for 1-5 interactions.

**Comment by yudongqiu** [comment]
Thanks a lot for the help! It works now.

**Comment by yudongqiu** [comment]
As a follow up: For another larger system of study containing several benzene rings, I tried to `bondCutoff="4"` is not working, and Lee-Ping and I found that we need to set that number up to 9 for it to work. I'm not quite sure if it's a valid approach to do this though. May I please ask is this a valid approach?

**Comment by peastman** [comment]
What you really need to do is call `getCovalentMap()` on the AmoebaMultipoleForce to identify all the atoms whose interactions are excluded.  Then add those to the CustomNonbondedForce as exclusions.
