### ISSUE TITLE
Bug reading AMBER topology file

### ISSUE THREAD

**Issue by bmanubay** [pandegroup/openmm#1538]
Howdy folks, 

I'm a little confused. I haven't made any recent changes to my openmm distro (until after this problem started occurring, at which point I conda uninstalled and conda installed the distro again), but I am trying to run a simulation off of AMBER topology and coordinate files and I keep get an issue thrown every time I try to load a topology file. The traceback stack is as follows:

```
  File "cp_cutoff.py", line 107, in minimization
    prmtop = AmberPrmtopFile(prmtop_filename)
  File "/home/bmanubay/anaconda2/lib/python2.7/site-packages/simtk/openmm/app/amberprmtopfile.py", line 92, in __init__
    prmtop = amber_file_parser.PrmtopLoader(file)
  File "/home/bmanubay/anaconda2/lib/python2.7/site-packages/simtk/openmm/app/internal/amber_file_parser.py", line 151, in __init__
    flag=self._flags[-1]
IndexError: list index out of range
```

The prmtop and inpcrd files are made using tleap, so I'm not sure what the issue could be. I've run simulations with these same files before also and everything went smoothly.

**Comment by jchodera** [comment]
Can you upload one of the problematic prmtop and inpcrd files in a ZIP file (you can attach these to github issues) and post the lines you were using to load them?

**Comment by bmanubay** [comment]
Actually think I just mislabeled the files somehow! Oops :(
