### ISSUE TITLE
Cut OpenMM 7.0.1 release

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1546]
We apparently [neglected](https://github.com/pandegroup/openmm/releases) to cut an OpenMM 7.0.1 release, which should correspond to git hash [`5e86c4f`](https://github.com/omnia-md/conda-recipes/blob/master/openmm/meta.yaml#L7).

@peastman: Can you do this?

**Comment by peastman** [comment]
Oops, thanks for pointing that out.  I've created the release.

**Comment by jchodera** [comment]
Thanks!
