### ISSUE TITLE
Travis failing with OpenCL

### ISSUE THREAD

**Issue by peastman** [pandegroup/openmm#1559]
The OpenCL builds on travis have recently stopped working.  When it tries to install the AMD APP SDK, it fails with this error:

> modprobe: ERROR: could not insert 'fglrx': No such device
> Error: Fail to load fglrx kernel module!
> Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly
> *** Error in `/home/travis/AMDAPPSDK/bin/x86_64/clinfo': munmap_chunk(): invalid pointer: 0x00007f248ccea11d ***
> /home/travis/build.sh: line 45:  3330 Aborted                 (core dumped) ${AMDAPPSDK}/bin/x86_64/clinfo

Any idea what might have changed?

**Comment by jchodera** [comment]
Could this be due to a switch in platform used for travis testing?

Some other folks seem to have had similar issues when they were migrated to Google Compute Engine:
https://github.com/travis-ci/travis-ci/issues/5249
https://github.com/travis-ci/travis-ci/issues/5221

Some people report seeing the addition of
```YAML
- sudo apt-get update -qq || true
```
resolve this for them. We have this in [the CUDA branch](https://github.com/pandegroup/openmm/blob/master/.travis.yml#L142-L145), but not the OpenCL branch.

**Comment by peastman** [comment]
I don't think that's the same problem.  They're talking about apt-get not being able to find packages.  We're download the APP SDK from a server in your lab.

**Comment by jchodera** [comment]
Whoops, sorry, you're totally right.

**Comment by jchodera** [comment]
Hm, I bet this is to blame:
https://blog.travis-ci.com/2016-08-09-outage-gce-images

**Comment by jchodera** [comment]
From: https://blog.travis-ci.com/2016-08-09-outage-gce-images
 
> GCE Images outage
> Brandon Burton, 9 Aug 2016
> We are deeply sorry for the outage of our sudo-enabled Precise and Trusty builds this morning.
> We've determined that an image cleanup process malfunctioned and deleted the stable build environment images. Due to various factors our only option at this point is roll forward with newer build environment images, for both Precise and Trusty.
> We're resuming builds with these new images, but these new images have not undergone thorough testing, so it is possible your builds will break.
> If you see issues with your builds failing, please email support@travis-ci.com, our engineering staff is available to help with any issues you run into. 
> We'll also continuing to investigate the exact cause of the issue and will be publishing a postmortem as we learn more.

Maybe it's worth dropping the engineering staff a line? I think that would be here:
https://github.com/travis-ci/travis-ci/issues

**Comment by peastman** [comment]
Good idea.  I'll do that.

**Comment by peastman** [comment]
It looks like they have the problem fixed.  See https://github.com/travis-ci/packer-templates/issues/221#issuecomment-242431509.
