### ISSUE TITLE
Addition of new residue to Gromacs topology file

### ISSUE THREAD

**Issue by MamtaMohan** [pandegroup/openmm#1568]
Hello,

I have to add a new residue in topology file  Gromacs using the CHARMM forcefield.

I have come across openmm python software. 

I would like to ask while using this software in python, will it create a new topology file for Charmm forcefields after it add residue to .rtp and other related files or will it modify the existing files.

How does it work. What information do I have to provide for this.

I have generated gromacs topology file for the residue via swissparam.

I will appreciate your response.

Mamta

**Comment by swails** [comment]
> I would like to ask while using this software in python, will it create a new topology file for Charmm forcefields after it add residue to .rtp and other related files or will it modify the existing files.

No, this is not what OpenMM is designed to do.  OpenMM will read in GROMACS files you have created and allow you to run a simulation on GPUs or CPUs.  Conversions are supported in other programs, like ParmEd or InterMol.

**Comment by MamtaMohan** [comment]
Thank you for the response.

I will look into ParmEd and InterMol

Mamta
