### ISSUE TITLE
Unusual platform properties behaviour in python with OpenCL and CUDA

### ISSUE THREAD

**Issue by jhprinz** [pandegroup/openmm#1569]
I came across some specific problems with using different platforms

I am running on an old MacBookPro with nVidia GPU and Intel 4000. These things happen:
1. When I create a system with `OpenCL` it can only use the `Intel 4000` and only with single precision. It lists this as device number `'1'`. Changing it so `'0'` fails. It seems I cannot use the nVidia with OpenCL. Does that make sense? I would have assumed that the nVidia would work, but not Intel.
2. When you add properties that are not used or specific to another platform it throws an error. This seems like the desired bahaviour. If you create a `CUDA` system and you specify a wrong option, _all_ options are ignored. In my case I used `{'OpenCLPrecision: 'mixed', 'CudaPrecision': 'mixed'}` to not have to change. On `OpenCL` is failed, on `CUDA` it worked without complains but used `CudaPrecision: 'single'`. This I think should not happen.

**Comment by peastman** [comment]
> It lists this as device number '1'. Changing it so '0' fails.

Try specifying '2'.  '0' is probably the CPU.

> On OpenCL is failed, on CUDA it worked without complains but used CudaPrecision: 'single'. This I think should not happen.

I agree.  That's not the intended behavior.

By the way, in the latest development code you can just specify 'Precision' without a platform name.  That way the same property will work for either one.

**Comment by jchodera** [comment]
@jhprinz : You can use the development version if you install via `conda` with:
```bash
conda install -c https://conda.anaconda.org/omnia/label/dev openmm==7.1.0
```
or if you add the `dev` label to your conda channels:
```bash
conda config --add channels https://conda.anaconda.org/omnia/label/dev
```
you can do 
```
conda install --yes openmm==7.1.0
```
to force an upgrade. In `travis`, if you haven't installed `openmm` yet, you can use
```
conda config --add channels https://conda.anaconda.org/omnia/label/dev
```
and then `openmm` will automatically pick up the `dev` version.

**Comment by jhprinz** [comment]
Thanks for the quick response. 

> Try specifying '2'. '0' is probably the CPU.

Yes, that worked! Thanks. I did not know.

> By the way, in the latest development code you can just specify 'Precision' without a platform name. That way the same property will work for either one.

I will wait then for 7.1 That is what I was hoping for.

Quick explanation on the context. We run simulations and store the setup for reruns. When doing the setup I do not want to fix settings that will need the exact same platform+setting to be available. Dy default we want OpenMM to pick the fastest, but it sill required setting options like `precision`, etc. So a _global_ `Precision` option is exactly what we need. 

For the Device I understand that it picks the first available because it might be difficult to guess which is faster. Is that correct? So I would have to let the user decide, what he wants there.

**Comment by peastman** [comment]
It does try to pick the fastest device, though it's not completely reliable.  For OpenCL, it does it based on clock rate and number of compute units.  For CUDA, it also prefers newer generation cards over older ones.

**Comment by peastman** [comment]
I tested on the latest code and verified the CUDA platform throws an exception when an unexpected property is specified.
