### ISSUE TITLE
Reproducing bechnmark performance

### ISSUE THREAD

**Issue by mj-harvey** [pandegroup/openmm#1573]
Hi,

I'm trying to reproduce the GPU benchmark figures quoted on
https://simtk.org/plugins/moinmoin/openmm/Benchmarks
and
https://simtk.org/plugins/moinmoin/openmm/BenchmarkOpenMMDHFR
but am not able to get the performance. Are the exact configuration scripts available anywhere?

cheers,

Matt

**Comment by peastman** [comment]
Yes, they were all generated with the `benchmark.py` script found in the examples folder.  Run `python benchmark.py --help` for details on the available options.

**Comment by mj-harvey** [comment]
Thanks, I can run them ok now. I'm not able to reproduce the GTX1080 performance quoted in the other benchmark thread (which I'll take up there)

**Comment by jchodera** [comment]
I think the other thread uses the development version of OpenMM, rather
than 7.0.1.
