### ISSUE TITLE
my new method to compute nonbonded force

### ISSUE THREAD

**Issue by Tron-x** [pandegroup/openmm#1574]
i have a new method to compute the nonbonded force,we create a datebase through calculation of quantum mechanics. the database contains,for example ,arbitrary pair molecular configuration potential of water,generally speaking，the nonbonded force of water is computed by the database interpolation.how can i implement this method by openMM to simulate a simple example such as rigid body ,or we can take water as rigid body.we need to test our method.can you help me.we want to make contibution to openmm

**Comment by peastman** [comment]
What is the functional form of your force?  For example, is it a pairwise interaction based on distance?  If so, you should be able to implement it with CustomNonbondedForce.  If it's something more complicated than that, there might be a different custom force that would work.

**Comment by Tron-x** [comment]
it is not a formula function form ,it is a database form ,the parameter is the Coordinate file and database file,the result is the potential of pair now can we use the TabulatedFunction API?

**Comment by peastman** [comment]
Yes, a tabulated function is fine.  But it's still a pairwise interaction that depends only on the distance between the particles?  If so, CustomNonbondedForce should work.

**Comment by Tron-x** [comment]
not only distance,but alse ,for example， the water ,we also consider about the Spatial configuration of water ,the potential is different if the distance of two pair is identical but the spatial configuration is different

**Comment by peastman** [comment]
Could you give more details?  I don't know what you mean by the "spatial configuration".  In what way does it depend on the configuration?  What is the functional form of the interaction?  I know it depends on a tabulated function, but what variables do you use as indices into that table?

**Comment by Tron-x** [comment]
sorry i do not represent clearly,at first we take the water as rigid body, for example ,we craete one waterbox the we will compute potential of every pair water through the database by interpolation,then we can get the interactive force of the pair water by some method,we take one water as a whole ,the force by  interpolation acts on one water ,not on Hydrogen and oxygen,generally speaking ,we do not have the force parameter,the Calculation of force is based on database ,you can take the database as a black box,the  parameter is one pair water and water QM database ,the result is potential of two water ,then we compute force by some method,we need a MD  frame directed against this method to make the water to run some step,could you help me ,thank you ,i need your help!

**Comment by peastman** [comment]
> at first we take the water as rigid body

Do you mean that you treat each water molecule as a point particle?  Or that you describe each water molecule by a position and orientation?  Or that you include the three atoms explicitly, and add constraints to make them rigid?

> the parameter is one pair water and water QM database

Does it depend only on the distance between then two waters?  Or also on their orientations?

**Comment by Tron-x** [comment]
1. include three atoms explicitly and add constraints to make them rigid
2. It depends not only on the distance between two waters but also on their orientations.

**Comment by Tron-x** [comment]
could you give me a use case about TabulatedFunction API,such as water case,it can replace of nonbonded force

**Comment by peastman** [comment]
I really need to know what the functional form of the interaction is.  You still haven't provided enough information to understand what you're trying to do.  Do you have a lookup table based on the distance between the oxygens and three Euler angles?  Or maybe a dot product between the vectors bisecting the angles made by the hydrogens?  Or is it based on the nine pairwise distances between atoms?  From what you have said, it could be any of those.  Or maybe even something different.  Please describe *exactly* what force you want to implement, with equations.

**Comment by Tron-x** [comment]
sorry ,what the lookup table do you mean?it is not based on nine pairwise distance between atoms.we have a QM database,the database is described by one structure include some sampling which is computed by QM,our code can compute the pairwise water by random though interpolation.our program code  Interface parameter is random Molecular coordinate，then we can get the pairwise energy by our code and database ,then we compute the force by disturbance one water ,then compute again, Two potential energy subtract/delta x, do openmm have method repace of the nonbonded force by our force

**Comment by peastman** [comment]
> the database is described by one structure

I still have no idea what that means.  _What is the functional form of the interaction?_  Give equations.

**Comment by Tron-x** [comment]
the interaction have no functional form,it is just based on database interpolation,for example ,if we know two water coordinate,we get the pairwise potential through our program ,could you give me your email,i can send you the result ,thank you !

**Comment by swails** [comment]
> the interaction have no functional form,it is just based on database interpolation,for example ,if we know two water coordinate,we get the pairwise potential through our program ,could you give me your email,i can send you the result ,thank you !

You *must* have an equation.  It is literally impossible not to.  In the case, as you say, where the potential is looked up in a table, your potential energy function will look something like this:

```python
energy = database_table[index]
force = -derivative_of_database_table[index] # you can get via spline interpolation, for instance
```

What is the index in the table?  *That* is the equation that we need to know.  Does the index depend only on the distance between two atoms?  Does that index take into account an angle?  A torsional angle?  Anything else?  In other words, what is the functional form of `index`?  How many particles' positions are used to compute the index?  How are their X-, Y-, and Z-coordinates combined (which is just another way of asking for the equation)?

If you can't give us equations or code that implements this model (which by definition would contain the equations we need), we cannot possibly know how to help.

**Comment by Tron-x** [comment]
![wtr_grids](https://cloud.githubusercontent.com/assets/7659413/18612370/9439d148-7d8a-11e6-82b3-cdbb4463f5ff.png)
wtr_grids is the database structure
![database](https://cloud.githubusercontent.com/assets/7659413/18612376/cbd792f2-7d8a-11e6-9c55-8d76aa36c8dd.png)
the database is based on this structure whose energy is computed by QM.
![random](https://cloud.githubusercontent.com/assets/7659413/18612386/fefe2dc6-7d8a-11e6-9292-adb706c0a7e3.png)
![random_content](https://cloud.githubusercontent.com/assets/7659413/18612387/03a77ed6-7d8b-11e6-9ccd-5b21f384aa58.png)
random.png is random coordinate,random_content.png is pairwise water in random.png
![energy](https://cloud.githubusercontent.com/assets/7659413/18612391/26c6b030-7d8b-11e6-8115-dd80f3807c71.png)
![code_main](https://cloud.githubusercontent.com/assets/7659413/18612392/2c92c7a6-7d8b-11e6-86af-5420ffb0efb5.png)
energy is the result through our program.
.i want to insert this method to openmm

**Comment by peastman** [comment]
Closing this, since we never got enough information to answer it.
