### ISSUE TITLE
Raise exception/warning on context creation if a non-periodic system has a barostat

### ISSUE THREAD

**Issue by andrrizzi** [pandegroup/openmm#1585]
Are there use cases in which we want to add a barostat to a non-periodic system? If not, can we raise a warning (if not an exception) on `Context` creation when this happens? The silent addition of the barostat to an implicit solvent system complicated debugging of choderalab/yank#469.

Simple working example
```python
from simtk import openmm, unit
from openmmtools import testsystems

system = testsystems.TolueneVacuum().system  # toluene in vacuum from prmtop/inpcrd files
print system.getDefaultPeriodicBoxVectors()
print system.usesPeriodicBoundaryConditions()
barostat = openmm.MonteCarloBarostat(1.0*unit.atmosphere, 310*unit.kelvin)
system.addForce(barostat)
print system.usesPeriodicBoundaryConditions()
```
outputs
```
[Quantity(value=(2.0, 0.0, 0.0), unit=nanometer), Quantity(value=(0.0, 2.0, 0.0), unit=nanometer), Quantity(value=(0.0, 0.0, 2.0), unit=nanometer)]
False
True
```

**Comment by jchodera** [comment]
> Are there use cases in which we want to add a barostat to a non-periodic system? 

Never!

> If not, can we raise a warning (if not an exception) on Context creation when this happens?

This should definitely raise an Exception.

**Comment by peastman** [comment]
Good point.  Yes, that should throw an exception.
