### ISSUE TITLE
Particle coordinate is nan error related to GB forces.

### ISSUE THREAD

**Issue by bas-rustenburg** [pandegroup/openmm#1586]
I've been experiencing some issues running implicit solvent simulations. In our particular test case, we observe crashes for a `ACE-TYR-NME` system. They occur often, but it is hard to reproduce the exact moment when it's going to happen. 

@jchodera discovered that the errors disappear when we eliminate `GBSAOBC` Forces from the system. 

Here is the minimal example, which contains the script, and serialized systems with and without GB forces. This is using openmm 7.0.1. I included the conda environment specifications in the zip file.

[debug.zip](https://github.com/pandegroup/openmm/files/464730/debug.zip)

When we run the script included, we get these errors, which happen in some iteration of the loop.

```pytb
Traceback (most recent call last):
  File "minimal.py", line 26, in <module>
    integrator.step(10)  # MD
  File "/home/rustenburg/anaconda/envs/gbforces/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 5330, in step
    return _openmm.CustomIntegrator_step(self, steps)
Exception: Particle coordinate is nan
```

It is hard to reproduce exactly the moment where it fails, but it is bound to happen if we run the loop for a few iterations. It does not occur when we remove GB forces.  We think there could be a numerical issue with the GB forces that is causing this behavior.

**Comment by bas-rustenburg** [comment]
For reading convenience, here is the contents of the script. 

```py
# load ACE-TYR-NME system in implicit solvent
from simtk import unit, openmm
from simtk.openmm import app
import openmmtools

withgb=True

temperature = 300.0 * unit.kelvin
timestep = 1.0 * unit.femtoseconds
collision_rate = 9.1 / unit.picoseconds
platform_name = 'CPU'
positions = openmm.XmlSerializer.deserialize(open('tyr.state.xml').read()).getPositions(asNumpy=True)

if withgb:    
    system = openmm.XmlSerializer.deserialize(open('tyr.sys.xml').read())
else:
    system = openmm.XmlSerializer.deserialize(open('noGB.tyr.sys.xml').read())

for i in range(1000):
    print(i)
    integrator = openmmtools.integrators.VelocityVerletIntegrator(timestep)
    platform = openmm.Platform.getPlatformByName('CPU')
    context = openmm.Context(system, integrator, platform)
    context.setPositions(positions)  # set to minimized positions
    context.setVelocitiesToTemperature(temperature)
    integrator.step(10)  # MD
    del context, integrator
```

**Comment by jchodera** [comment]
Just wondering if anyone else has been able to reproduce this.

**Comment by jchodera** [comment]
I can reproduce this `nan` on `linux` with a GTX-680 using the `openmm` current master.

Only the `CPU` platform seems to be affected. `OpenCL`, `CUDA`, and `Reference` work fine.

@bas-rustenburg : Note that the `Reference` platform is much faster than the `CPU` platform for tiny dipeptides like this.

**Comment by peastman** [comment]
I just sent a PR with the fix.  This was a case where padding was added to the end of an array to allow for vectorization, and the extra elements were never initialized.  They got masked out, so it didn't matter what their values were... unless they happened to be nan, in which case that propagated through and the force came out as nan.

Thanks for finding this!
