### ISSUE TITLE
Update swig for omnia builds from 3.0.7 to at least 3.0.8?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1589]
There is [a weird swig issue](https://github.com/choderalab/perses/pull/253#issuecomment-248450130) with versions before 3.0.8 in which using Python generators involving calls to swig-wrapped functions inside the called function can cause bizarre issues like this:

```
======================================================================
ERROR: Failure: SystemError (<built-in function delete_System> returned a result with an error set)
----------------------------------------------------------------------
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/choderaj/miniconda/envs/test35/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/choderaj/miniconda/envs/test35/lib/python3.5/site-packages/nose/loader.py", line 252, in generate
    for test in g():
SystemError: <built-in function delete_System> returned a result with an error set
```

This was fixed by https://github.com/swig/swig/pull/560, and this fix appears to have gone into `swig` between 3.0.7 and 3.0.8.

The `openmm` `omnia` recipe is currently [pinned to use `swig 3.0.7`](https://github.com/omnia-md/conda-recipes/blob/master/openmm/meta.yaml#L26-L27).

What do you guys think about releasing a new build of the `openmm` 7.0.1 package with an updated `swig` version?

See https://github.com/swig/swig/pull/560 for more information.

**Comment by peastman** [comment]
We should update the recipe to use 3.0.8.  But we can't just do a new build of 7.0.1.  If we rebuild to fix a bug, that means it's 7.0.2.  We would also need to build new zip installers, create a new release on simtk.org, etc.

**Comment by jchodera** [comment]
There's no change to the OpenMM codebase, though---we are just changing the `conda` recipe for the build so that it is no longer pinned to `swig 3.0.7`. The zip source installer would be identical, and there's no requirement that the binary distributions and the conda-installed distributions be completely 100% swig-compatible with each other, is there?

**Comment by peastman** [comment]
A change is a change, whether it comes from the source code or the build environment.  Otherwise, if someone said, "I'm using OpenMM 7.0.1," that wouldn't tell you whether they had a version with or without this problem.  The zip binary installers would change too, since they contain C files that are generated by SWIG.

**Comment by jchodera** [comment]
> A change is a change, whether it comes from the source code or the build environment. Otherwise, if someone said, "I'm using OpenMM 7.0.1," that wouldn't tell you whether they had a version with or without this problem. 

That's not quite true, since the OpenMM 7.0.1 release simply specifies SWIG as a dependency in [the manual](http://docs.openmm.org/7.0.0/userguide/library.html?highlight=swig), and it doesn't look like `CMake` requirements limit us to any specific version of SWIG. If somebody grabbed the source code release and compiled/installed it themselves, they're using OpenMM 7.0.1, but we have no control over what SWIG version they're using.

**Comment by peastman** [comment]
If someone builds it themself from source, we never know exactly what they've got.  They might have used a completely different compiler from what we used.  But the binary distributions we do control, and that's what I'm talking about.

**Comment by jchodera** [comment]
OK. Our Jenkins build platform is down, but we could get it back up again by Monday, I think.

**Comment by jchodera** [comment]
Scratch that. Our mac mini Jenkins build system has, remarkably, survived the lab move from 11 to 6 unscathed and ready for business.

**Comment by peastman** [comment]
I assume this can be closed now?

**Comment by jchodera** [comment]
That change was made in the `openmm` `beta` 7.1.0 build recipe: https://github.com/omnia-md/conda-recipes/pull/657
