### ISSUE TITLE
Undefined symbol when using python -m simtk.testInstallation

### ISSUE THREAD

**Issue by jlerche** [pandegroup/openmm#1595]
I'm in Ubuntu 16.04 with gcc 5.4, I tried compiling the master branch and everything seemed to work until the make PythonInstall step where I see this

```
building 'simtk.openmm._openmm' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=7 -DMINOR_VERSION=0 -I/home/lerche/libraries/openmm/openmm-master/./include -I/home/lerche/libraries/openmm/openmm-master/./include/openmm -I/home/lerche/libraries/openmm/openmm-master/./include/openmm/internal -I/home/lerche/libraries/openmm/openmm-master/openmmapi/include -I/home/lerche/libraries/openmm/openmm-master/openmmapi/include/openmm -I/home/lerche/libraries/openmm/openmm-master/openmmapi/include/openmm/internal -I/home/lerche/libraries/openmm/openmm-master/olla/include -I/home/lerche/libraries/openmm/openmm-master/olla/include/openmm -I/home/lerche/libraries/openmm/openmm-master/olla/include/openmm/internal -I/home/lerche/libraries/openmm/openmm-master/serialization/include -I/home/lerche/libraries/openmm/openmm-master/serialization/include/openmm -I/home/lerche/libraries/openmm/openmm-master/serialization/include/openmm/internal -I/home/lerche/libraries/openmm/openmm-master/plugins/amoeba/openmmapi/include -I/home/lerche/libraries/openmm/openmm-master/plugins/amoeba/openmmapi/include/openmm -I/home/lerche/libraries/openmm/openmm-master/plugins/amoeba/openmmapi/include/openmm/internal -I/home/lerche/libraries/openmm/openmm-master/plugins/rpmd/openmmapi/include -I/home/lerche/libraries/openmm/openmm-master/plugins/rpmd/openmmapi/include/openmm -I/home/lerche/libraries/openmm/openmm-master/plugins/rpmd/openmmapi/include/openmm/internal -I/home/lerche/libraries/openmm/openmm-master/plugins/drude/openmmapi/include -I/home/lerche/libraries/openmm/openmm-master/plugins/drude/openmmapi/include/openmm -I/home/lerche/libraries/openmm/openmm-master/plugins/drude/openmmapi/include/openmm/internal -I/home/lerche/miniconda2/include/python2.7 -c src/swig_doxygen/OpenMMSwig.cxx -o build/temp.linux-x86_64-2.7/src/swig_doxygen/OpenMMSwig.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/lerche/libraries/openmm/openmm-master/openmmapi/include/OpenMM.h:52:0,
                 from src/swig_doxygen/OpenMMSwig.cxx:6662:
/home/lerche/libraries/openmm/openmm-master/openmmapi/include/openmm/GayBerneForce.h: In constructor ‘OpenMM::GayBerneForce::ParticleInfo::ParticleInfo(double, double, int, int, double, double, double, double, double, double)’:
/home/lerche/libraries/openmm/openmm-master/openmmapi/include/openmm/GayBerneForce.h:286:19: warning: ‘OpenMM::GayBerneForce::ParticleInfo::epsilon’ will be initialized after [-Wreorder]
     double sigma, epsilon, sx, sy, sz, ex, ey, ez;
                   ^
/home/lerche/libraries/openmm/openmm-master/openmmapi/include/openmm/GayBerneForce.h:285:9: warning:   ‘int OpenMM::GayBerneForce::ParticleInfo::xparticle’ [-Wreorder]
     int xparticle, yparticle;
         ^
/home/lerche/libraries/openmm/openmm-master/openmmapi/include/openmm/GayBerneForce.h:291:5: warning:   when initialized here [-Wreorder]
     ParticleInfo(double sigma, double epsilon, int xparticle, int yparticle, double sx, double sy, double sz, double ex, double ey, double ez) :
     ^
g++ -pthread -shared -L/home/lerche/miniconda2/lib -Wl,-rpath=/home/lerche/miniconda2/lib,--no-as-needed build/temp.linux-x86_64-2.7/src/swig_doxygen/OpenMMSwig.o -L/usr/local/openmm/lib -L/home/lerche/miniconda2/lib -Wl,-R/usr/local/openmm/lib -lOpenMM -lOpenMMAmoeba -lOpenMMRPMD -lOpenMMDrude -lpython2.7 -o build/lib.linux-x86_64-2.7/simtk/openmm/_openmm.so
```

Everything else seems to proceed smoothly but then
```
> python -m simtk.testInstallation
Failed to import OpenMM packages; OpenMM will not work.
Make sure OpenMM is installed and the library path is set correctly.

Error message: /home/lerche/miniconda2/lib/python2.7/site-packages/simtk/openmm/_openmm.so: undefined symbol: _ZTVN6OpenMM13GayBerneForceE
```

The symbol `_ZTVN6OpenMM13GayBerneForceE` is the same one that gave me trouble above.

**Comment by jlerche** [comment]
`~/miniconda2/lib$ nm libOpenMM.so | grep Berne` no results

**Comment by peastman** [comment]
That class was just added recently, so it probably just means cmake has gotten confused and isn't regenerating the swig files.  Delete the `wrappers` subdirectory inside your build directory, then run cmake, then build again.

**Comment by jlerche** [comment]
Did the following steps in build directory:

> ccmake -i /path/to/openmm-src
c to configure, then g to generate
> make
> make install
> make PythonInstall

no change.

**Comment by peastman** [comment]
Does the file https://github.com/pandegroup/openmm/blob/master/openmmapi/src/GayBerneForce.cpp exist in your source tree?

**Comment by jlerche** [comment]
Yep

**Comment by peastman** [comment]
Ok, let's try to work through the various places something might be going wrong.

Did that file actually get compiled?  Look for the file CMakeFiles/OpenMM.dir/openmmapi/src/GayBerneForce.cpp.o.

Did it get properly linked into the library?  Check for the test case TestReferenceGayBerneForce.  It should exist, and you should be able to run it.

Is libOpenMM.so being properly copied to the install directory?  Compare the sizes and time stamps.

Is it possible you have two different versions of OpenMM installed on your computer?  Perhaps one compiled from source and one installed by conda?  If so, Python might be linking to the wrong one.

**Comment by jlerche** [comment]
It got compiled, GayBerneForce.cpp.o is in the directory.

TestReferenceGayBerneForce also exists and returns `Done` when run

It seems like it isn't getting copied, timestamp shows May 4. I'll remove all the libOpenMM* files and try the build process again

I did indeed have a conda installed version, but I removed the simtk directory from site-packages and from pkgs, but i'm guessing I overlooked the libOpenMM*.so files.

**Comment by jlerche** [comment]
After removing the libOpenMM*.so files in miniconda2/lib and going through the build process, it seems they aren't being copied to that directory. Does `make PythonInstall` need to be run with sudo? miniconda is in my home directory, but am i overlooking something?

**Comment by peastman** [comment]
Are you doing a `make install`?  That's where the libraries get installed.  And what directory is `CMAKE_INSTALL_PREFIX` set to?

**Comment by jlerche** [comment]
I was doing `sudo make install` because `CMAKE_INSTALL_PREFIX=/usr/local/openmm` and I assumed they were being copied over or symlinked. Should I change the install prefix directory then?

**Comment by peastman** [comment]
No, that's a fine location to install in.  (It's the default location.)  More likely the problem is that you didn't delete the libraries installed by conda, and those were getting found before the ones you compiled.

**Comment by jlerche** [comment]
Is there a list of things that need to be deleted to ensure there's no conflict?

**Comment by peastman** [comment]
The best thing is probably to `conda remove openmm`.  That should get everything.  Then you can do a `make install` and `make PythonInstall` to replace them with the versions you just compiled.

**Comment by jlerche** [comment]
Ok that worked! Seems like there's something else somewhere in conda that interferes beyond the files themselves.

**Comment by peastman** [comment]
Great!
