### ISSUE TITLE
make nonbonded force zero

### ISSUE THREAD

**Issue by Tron-x** [pandegroup/openmm#1597]
if i new a nonbonded force ,and addforce(nonbonded),but i don not want to use it ,how can i make the return value from the computing kernel zero.could you give me the code location which can control it,thanks!

**Comment by peastman** [comment]
What are you trying to accomplish?

If you set charge and epsilon to 0 for every particle, all the forces will come out to zero.  But in that case, why add the force to the system at all?  Or you could put it into a different force group with `setForceGroup()`, and use that to exclude it from the force calculations you care about.
