### ISSUE TITLE
Is "dt" read-only in CustomIntegrator?

### ISSUE THREAD

**Issue by kyleabeauchamp** [pandegroup/openmm#1598]
According to the docs, one can access the variable "dt" in a CustomIntegrator to retreive the current step size: "dt: (global) This is the step size being used by the integrator."

What is the anticipated behavior if one tries to to re-write "dt"?  For example, the following code didn't seem to do anything, and the `getStepSize()` method returned the original step size. 

```
self.addComputeGlobal("dt", "-1")
```

I suspect the right answer is to modify the docs to call "dt" read-only, similar to the "energy" variable.  It might also be worthwhile to do some checking at compile-time to ensure that reserved keywords are not being written to?

**Comment by kyleabeauchamp** [comment]
On a related note, is there any downside to being "stricter" with respect to adding compute steps outputting to variables that have not been initialized?  Right now it seems to simply end up with "undetermined" behavior which IMHO leads to tricky debugging.  Presumably it is possible to raise an exception at compile time rather than silently allow this.

**Comment by peastman** [comment]
`dt` should be modifiable by global steps.  Per-dof steps can read it but not modify it.

> On a related note, is there any downside to being "stricter" with respect to adding compute steps outputting to variables that have not been initialized?

There's no such thing as a variable not being initialized.  `addGlobalVariable()` and `addPerDofVariable()` both require you to specify the initial value it should be initialized to.

**Comment by kyleabeauchamp** [comment]
I mean that you can add a compute step without calling `addGlobalVariable()`

**Comment by kyleabeauchamp** [comment]
Should the changes in `dt` then be picked up later by `getStepSize()` on the integrator?

**Comment by peastman** [comment]
> I mean that you can add a compute step without calling addGlobalVariable()

If you try to write to a nonexistant variable, it should throw an exception.  If it doesn't, that's a bug!

> Should the changes in dt then be picked up later by getStepSize() on the integrator?

Yes.  If it doesn't, that's also a bug.

**Comment by kyleabeauchamp** [comment]
Thanks, I can confirm that the modified step size is now reported by `getStepSize()`
