### ISSUE TITLE
how to check the simulations from a check point

### ISSUE THREAD

**Issue by juanmit** [pandegroup/openmm#1599]
Hi,
I am wondering how to check if the checking point works.

I added the following two lines to Load the checkpoint, and restarted the simulation. However, the dcd file did  not append the original one. Could you tell me how to continue the simulations and append dcd files?

Thanks a lot.

--Hongbin 

with open('test.chk', 'rb') as chkfile:
    simulation.context.loadCheckpoint(chkfile.read())

**Comment by swails** [comment]
The only thing that loading a checkpoint does is restore the simulation `Context` to the same state it was in (as close as possible) to the time when the checkpoint was created (at a basic level, it will restore the coordinates and velocities to the values stored in the checkpoint).

Appending to existing files is not something that a checkpoint will automatically handle for you.  You can write your script to append, but that's something you would do with Python code.

**Comment by juanmit** [comment]
Hi swails,
Thanks for replying. That makes lots of more sense now because I thought it would automatically append everything.    :)   I can work on on the appending code myself. Thanks!!!! 
--Hongbin
