### ISSUE TITLE
CustomIntegrator fails to identify undeclared variables

### ISSUE THREAD

**Issue by kyleabeauchamp** [pandegroup/openmm#1602]
In #1598, @peastman mentioned that CustomIntegrator should raise an exception if an undeclared variable is written to.  Below is a minimal test case demonstrating that this behavior is not observed.  The code runs to the final line, at which point an Exception is raised.  I believe the desired behavior is to raise an error at the `addComputeGlobal()` line.

```
import simtk.openmm.app as app
import simtk.openmm as mm
from simtk import unit
from openmmtools import testsystems

testsystem = testsystems.HarmonicOscillator()
system, topology = testsystem.system, testsystem.topology
temperature = 298.0 * unit.kelvin

integrator = mm.CustomIntegrator(0.0001)
integrator.addComputePerDof("v", "v+0.5*dt*f/m")
integrator.addComputePerDof("x", "x+dt*v")
integrator.addComputePerDof("v", "v+0.5*dt*f/m")
integrator.addComputeGlobal("myvar", "1.0")


context = mm.Context(system, integrator)
context.setPositions(testsystem.positions)
context.setVelocitiesToTemperature(temperature)
integrator.step(5)

integrator.getGlobalVariableByName("myvar")

[...]

---> 22 integrator.getGlobalVariableByName("myvar")
Exception: Illegal global variable name: myvar
```

**Comment by swails** [comment]
Can't an integrator access global variables from other custom forces?

If that's the case, the real place to raise is the `Context` creation, I think.  Unless I'm missing something?

Although `myvar` is never actually used anywhere (it's just assigned to 1 each time the integrator runs).  So maybe the current behavior isn't all that strange?
