### ISSUE TITLE
Support for CUDA 8.0?

### ISSUE THREAD

**Issue by yabmtm** [pandegroup/openmm#1609]
I just installed OpenMM via conda and CUDA 8.0, and after several iterations of receiving the error:

`Exception: There is no registered Platform called "CUDA"`

and checking and re-checking that my PATH and environment variables were correctly assigned. I checked the existence and dependencies of the CUDA plugin and found that:

`libcufft.so.7.5 => not found`

This, I assume, means that CUDA 8.0 is not yet supported because I was able to find libcufft.so.8.0 on my system but not libcufft.so.7.5.

Is there any way that I can ask OpenMM to use the CUDA 8.0 library instead of the 7.5 ones? Or will I have to uninstall CUDA 8.0 and install 7.5 instead?

Thanks,
Matt

**Comment by swails** [comment]
Unless you compile OpenMM directly from source, you *must* use the same CUDA version that was used to build the original binaries.

So if you want to use CUDA 8, you can't use conda to install OpenMM.

**Comment by jchodera** [comment]
I think we can try to build a CUDA 8 compatible version using "features" to track the CUDA version:

http://conda.pydata.org/docs/building/meta-yaml.html#id1

We have to get the build framework updated for CUDA 8 anyway. Will take some engineering, but it could be useful.

Thoughts?

**Comment by jlmaccal** [comment]
I would love to see multiple conda packages built against different versions of CUDA. It would greatly simplify deployment onto different clusters, where we currently have to compile from source.

**Comment by jchodera** [comment]
We've got CUDA 8.0 support in the openmm 7.1 beta, and we have the docker images to build CUDA 7.5 and CUDA 8.0 versions, so we might be able to deliver conda packages for the two most current CUDA versions for 7.1.

**Comment by peastman** [comment]
Closing, since this is no longer relevant.

**Comment by jchodera** [comment]
Oh, if only it was no longer relevant. Could you re-open this? We're in need of building a conda package for ORNL TITAN (which is still on 8.0) and still trying to find a good way to deploy this.

**Comment by jchodera** [comment]
I imagine we're also not the only ones in this circumstance. Not everybody upgrades CUDA on their whole compute cluster every time OpenMM is released...

**Comment by peastman** [comment]
Reopening, though I think what you're describing is a different issue.  We *do* have support for CUDA 8.0 now.  This issue was about how to run OpenMM with a new version of CUDA that we hadn't yet added support for, which is different from wanting to run it on an old version that we've already dropped support for.

**Comment by jchodera** [comment]
Whoops, sorry! I'll create a separate issue asking about convenient conda deployment for earlier CUDA versions.

**Comment by peastman** [comment]
Ok, I'll close this again then!
