### ISSUE TITLE
OpenMM application

### ISSUE THREAD

**Issue by peastman** [pandegroup/openmm#1610]
@VijayPande has recently brought up the issue of creating a top level "OpenMM application" for running simulations without writing any code.  We've discussed this idea a few times before, but could never come to agreement on what it should be.  Different people had very different requirements for what they wanted an application to do and what problems they wanted it to solve.  Perhaps the time has come to consider it again.

Vijay, could you describe why you think this is important, and what the particular problems are the application should try to solve?

Possibly all we need to do is point people to the application @leeping developed.  Lee-Ping, are you still developing/maintaining it?  Do you think it's suitable for this purpose?

**Comment by jchodera** [comment]
This is certainly a neat idea, but we need to figure out the pitch:
* Who is the target audience?
* What key functionality do they need for this to fulfill the targeted niche?

I could imagine a bunch of different ways of doing this (command-line tool, PyMOL panel for GUI, IPython notebook interface, electron/photon desktop app, web app, docker image) depending on who the target audience is and what they need to do.

**Comment by peastman** [comment]
Anyone else?  @VijayPande?  @leeping?

**Comment by jchodera** [comment]
Also, with MolSSI now in the mix, is it better to do this now or wait for some clarity on what the field really needs?

**Comment by mpharrigan** [comment]
I think it would be neat to have a webby gui system builder (maybe based off of pdbfixer) that emits `state.xml`, `system.xml`, and `integrator.xml` as well as a fourth configgy file (similar to FAH's `core.xml`) that can be fed into a simple, command-line, cpp-only equivalent of gromacs's `mdrun`. The config file would give things like output filename, duration, and saving frequency. 

This system lets you have a rich, graphical environment for setting things up that can be great for new users. Power users can use a python script to generate xml files with more advanced things going on in them. The executable will be small and easy to compile (esp. on non-x86 archs). No python linking issues. Non-programmers won't be put off by "having to learn python"

**Comment by jchodera** [comment]
So [CHARMM-GUI](http://www.charmm-gui.org/)?

**Comment by swails** [comment]
But it can be locally hosted.

**Comment by swails** [comment]
I still think it's worth taking this opportunity to present an entirely different UI in an MD application.  The traditional UI (gmx, Amber, CHARMM, and NAMD are all different takes on the same kind of idea) means we remove UI as a potential differentiator to encourage adoption of OpenMM.  And it's not really *that* different from just treating a Python script as an "input file".

Having something GUI-based (but scriptable) and hooked into some kind of viewer (like nglview) for real-time visualization could be the first step toward something game-changing.

Just my 2c.

**Comment by mpharrigan** [comment]
> So CHARMM-GUI?

Sure! We'd still provide a small, easily-installable command line app. I think @peastman already had to do that for a labmember to get simulations running on a cray supercomputer. The fact that all these parts already exist is a benefit in my book :)

**Comment by jchodera** [comment]
I think it's definitely useful to make the CHARMM-GUI >> OpenMM pipeline easier to use, but I still don't have a feeling for the audience we're trying to reach here. 

Can anybody elaborate on who specifically we'd like to attract to use this?

**Comment by ctk3b** [comment]
[JupyterLab](https://github.com/jupyterlab/jupyterlab) looks like it's [shaping up quite nicely](https://www.youtube.com/watch?v=Ejh0ftSjk6g). Would a JupyterLab plugin provide the functionality that you're after? You could provide a nice GUI but retain the scriptability of the notebook, seamless access to nglview and the GUI itself is also fairly hackable.

However, this might be a bit pre-mature depending on your timeline given that JupyterLab is still pretty early in development.

**Comment by cing** [comment]
I think system preparation is a bit off topic for this issue, but if that's being discussed, it's worth mentioning QwikMD here as an example of a local GUI-based solution for system preparation/simulation (NAMD specific): http://www.nature.com/articles/srep26536

I'd also like to see a scriptable CHARMM-GUI (target audience power users) with user contributed templates for common pipelines, like membrane embedding, ENSEMBLER, generation of multiple initial conditions. Does that exist? I have a lot of rants about CHARMM-GUI, but none are really due to it's lack of a molecular viewer.

+1 to a single command-line version of `mdrun`.

**Comment by peastman** [comment]
> Can anybody elaborate on who specifically we'd like to attract to use this?

I don't know, but that's definitely the question we need to answer.  There are lots of things we could do because they're cool.  But that doesn't necessarily make them valuable things to do.  What problems are we trying to solve?  We need to identify a specific class of users who have specific unmet needs, then design an application to address them.

**Comment by jchodera** [comment]
> What problems are we trying to solve? We need to identify a specific class of users who have specific unmet needs, then design an application to address them.

I am in complete agreement that we need to address this question before going further along these lines.

**Comment by peastman** [comment]
Perhaps we can discuss it at the OpenMM meeting on Friday and get Vijay to elaborate on why he thinks this is important.

**Comment by jchodera** [comment]
One idea discussed in the phone call today was to create a plugin for PyMOL that adds new commands, menu items, or dialog boxes. The [tutorial](https://pymolwiki.org/index.php/Plugins_Tutorial) makes this look extremely straightforward.

Some useful basic functionality could be:
* Import CHARMM-GUI tarball output
* Use PDBFixer to download and prep a PDB file
* Run a simulation locally (and visualize the trajectory as it is produced)
* Load an OpenMM trajectory

**Comment by jchodera** [comment]
I also think that prepackaged IPython/Jupyter notebook tutorials that take users through the whole process
* loading initial files via CHARMM-GUI or PDBFixer
* running a simulation with OpenMM
* visualizing the trajectory with [nglview](https://github.com/arose/nglview)
* analyzing the data with [MDTraj](http://mdtraj.org)/[MDAnalysis](http://www.mdanalysis.org/) 

would be a great way to introduce new users both to OpenMM and Python/Jupyter. This is rapidly becoming technology that new students (at least, students I would want to enter computational chemistry) need to learn at the beginning of their graduate education. By starting them with fully-functional examples where all they have to do is tweak examples to do what they want, this is both a gentle way to introduce them to the ecosystem as well as allow them to do more powerful things as they learn more about OpenMM and Python.

A number of other fields are doing this:
* a great [sklearn tutorial](https://github.com/jakevdp/sklearn_tutorial); click through the notebooks [here](https://github.com/jakevdp/sklearn_tutorial/tree/master/notebooks)
* [LearnDataScience](https://github.com/nborwankar/LearnDataScience)
* [IPython Theano Tutorials](https://github.com/jaberg/IPythonTheanoTutorials)

**Comment by jchodera** [comment]
@avirshup of Autodesk Bio/Nano has also put together a beautiful infrastructure for running OpenMM inside of a fully functional Jupyter framework that makes things super easy for users to use: http://bionano.autodesk.com/MolecularDesignToolkit/

We could alternatively just help publicize this, and provide some more examples of using it for common introductory tasks.

**Comment by bas-rustenburg** [comment]
Just wanted to point out this library that very easily turns `argparse` python scripts into a GUI, in case the objective is to make a command line tool that is also accessible to non-programmers.
  
https://github.com/chriskiehl/Gooey

**Comment by jaimergp** [comment]
While this might not be what you are looking for, maybe you want take a look at a small utility I developed for my group, [`ommprotocol`](https://github.com/insilichem/ommprotocol). It provides a YAML input file interface in which you load the topologies, coordinates and so on, and the configure the simulation through a series of stages.

Just my two cents :)

**Comment by peastman** [comment]
I just had a long discussion with Tom Markland and some members of his group about this.  Here's a summary of what they had to say.

We discussed four distinct user groups an application might be targeted at:

1. Novice users who are new to MD in general.  These people would benefit from a lot of guidance in deciding what to simulate and how to do it.
2. People who are experienced running MD with a different program and would like to try OpenMM.  The goal for these people would be to reduce the initial barrier, so they can get started without having to learn as much.
3. People who are experienced running MD with a different program, and need features that aren't currently present in OpenMM (parametrize small molecules, etc.).
4. Experienced OpenMM users.  For these people, the goal is to save them work and let them get things done more efficiently.

They felt groups 1 and 2 are the most important ones to target.  Group 3 will gradually be addressed as we add the missing features, but that's outside the scope of this application.  And experienced OpenMM users mostly seem pretty happy writing Python scripts.

They also felt some sort of a GUI based application was the best way to address groups 1 and 2.  Sort of a combination between Zephyr, PDBFixer, and the existing script builder.  It would walk you through preparing your structure and setting simulation options.  It would then generate all the files you need (including a complete Python script), or could run the simulation itself and display it in a visualizer in real time.

There are lots of ways that application might be written.  It could be a conventional, standalone application, or a Jupyter notebook, or a local webapp like PDBFixer, or a hosted webapp like CHARMM-GUI, or a plugin to PyMol or VMD.  It's also possible we could do more than one of those.  They pointed me to the Electron framework (http://electron.atom.io), which lets you wrap webapps as standalone applications.  There are probably other ways of writing something than can be invoked in multiple ways.

Thoughts on any of this?

**Comment by avirshup** [comment]
Thanks for tagging me on this @jchodera , and apologies for the delay in replying.

As John mentioned, [my group](http://bionano.autodesk.com) has put out some interactive Jupyter notebooks that run OpenMM (here's a [prototype demo that you can run online](http://mybinder.org/repo/avirshup/mdt-gallery-test/), and an [offline example](https://github.com/Autodesk/molecular-design-toolkit/blob/master/moldesign/_notebooks/Example%203.%20Simulating%20a%20crystal%20structure.ipynb) if the first one isn't working)

We're also right now putting together tools to provide easier-to-use web interfaces for open source molecular modeling. The idea of an OpenMM app is very similar to the sorts of things we're thinking about - I'd be very happy to discuss the overlaps further, if there's interest.

**Comment by jchodera** [comment]
I was just talking to @peastman, and think it might be great for @peastman to head up to Pier 9 or @avirshup to head down to Stanford to chat. I'd be happy to join remotely if I could be of utility!

**Comment by avirshup** [comment]
That sounds great @jchodera - I'll send you and @peastman an email to set something up

**Comment by peastman** [comment]
Does anyone have thoughts on my previous post?  Do you agree with that analysis?  Are those the right groups of users to be targeting?  Do you have opinions on the various types of GUI we might create?

**Comment by peastman** [comment]
I had a great meeting yesterday with @avirshup and some other members of his group.  They were somewhat negative about using Jupyter notebook for this sort of thing.  Largely that ipywidgets is frustrating to work with, and every update to it breaks your code.  For their work, they're moving to more conventional webapps.  They suggested Flask (http://flask.pocoo.org) as a good framework for this sort of application.

**Comment by hainm** [comment]
>  Largely that ipywidgets is frustrating to work with, and every update to it breaks your code.  

I agree with them too. I wasted few weeks just to keep our [nglview](https://github.com/arose/nglview) updated with changes in `ipywidgets`.
It (`ipywidgets`) is quite new (originally from `IPytython widget`) but its ecosystems are really nice.

- [jupyterlab](https://github.com/jupyterlab/jupyterlab)
- [nteract](https://github.com/nteract/nteract)

I also agree that if you do not want something fancy, `Flask` is good to go.

**Comment by peastman** [comment]
Ok, let me offer a concrete proposal.  This is really just to keep the discussion moving, so feel free to tell me this is a terrible idea and we should do something totally different.  As long as you say exactly what you think we should do instead. :)

We will create a web application, written in Python using Flask.  It will resemble a combination of the script builder and PDBFixer, with some extra features thrown in.  It will consist of a series of steps that walk you through setting up your simulation.

1. First, it asks for your input files.  These could be any of the supported types: PDB, Amber, CHARMM, etc.

2. If you select a PDB file, it asks if you want to use the file as-is or clean it up.  If you say to clean it up, it takes you through all the steps from PDBFixer so you can remove chains, add missing atoms, build a water box, etc.

3. You then select all the simulation options, very similar to the script builder UI.

4. You then have two options.  It can either run the simulation right then on your computer, displaying results in the web browser, or it can save a script to run later just like the script builder.  In theory we could eventually add other options, like interacting with queuing systems to submit jobs to be run on clusters, or run it in a VM on AWS, or things like that.

There are other advanced features we could potentially add.  For example, we could incorporate a molecular viewer for various purposes (when selecting which chains to include, or when running a simulation locally).

**Comment by mpharrigan** [comment]
>  or it can save a script to run later just like the script builder

Option 1: The webapp saves a script very similar to the current script builder. The webapp optionally exports a fixed pdb. Otherwise, it's on the researcher to make sure the prmtops or whatever are in the right place.

Option 2: The webapp serializes system.xml integrator.xml state.xml for download in addition to a very short script that sets up reporters and calls integrator.step

I'd advocate for option 2
 - get everyone into openmm land as early as possible
 - quicker start up ... system doesn't have to be built every time
 - shorter script / easier for newbies to know what they're allowed to change

Option 3: Same as option 2, but return one file that's a tar.bz2 of the three xml files (maybe with a special openmm extension). Add a python function for loading all three things from a tar.bz2 file. This would simplify the script further. This would prevent mixing and matching integrators / states / systems. This would make it feel more like an application

Personally, I think this is a better route, but I expect some push-back

**Comment by peastman** [comment]
I did think about that too.  The main thing I didn't like about it was that most of the options would no longer be in the script.  There's a lot of value in producing a single script the user can easily edit.  I was even thinking of taking this further than the current script builder, and having it define variables for all user editable parameters right at the top of the script.  But if we just give them serialized XML files, they can't do that anymore.

The other issue is that we also need a Topology, so the script would still need access to the original files to get that.

> shorter script / easier for newbies to know what they're allowed to change

That's exactly the problem: they would hardly be able to change anything!  Want to change the cutoff distance?  It's not in the script.  The set of constraints?  Not there.  The force field?  Nope.  The temperature or pressure or step size?  They're all buried in XML files.

**Comment by hainm** [comment]
@peastman why not just follow what other packagers do (amber, charmm, gromacs, namd, ...).

- setup
- run simulation from command line with given user interface input.

**Comment by mpharrigan** [comment]
>  Want to change the cutoff distance? It's not in the script. The set of constraints? Not there. The force field? Nope. The temperature or pressure or step size? They're all buried in XML files.

My argument is that they should be changing these things *from the app*. To change these things in gromacs, you have to grompp. We could make it easy by adding a "load" function to the webapp to iterate on setup parameters

> The other issue is that we also need a Topology, so the script would still need access to the original files to get that.

This is true. I think there's been some desire to have a serializable openmm topology. This would be a use case for it

**Comment by swails** [comment]
> My argument is that they should be changing these things from the app.

Does that yield a better and more intuitive user experience?  GROMACS may do that, but CHARMM and Amber don't.  If you're going to base behavior on other programs, I think it's important to understand why those other programs made those design decisions to see if it makes sense to adopt a similar decision for another project.

The GROMACS workflow *feels* like the developers carefully thought out how the implementation workflow should be designed, then slapped a UI over each step almost as an afterthought.

**Comment by mpharrigan** [comment]
> Does that yield a better and more intuitive user experience

Changing cutoffs and integrators from the app with dropdowns and tooltips is a better experience. If it isn't, then we should stick with the status quo of do everything in the script.

**Comment by peastman** [comment]
> My argument is that they should be changing these things from the app.

Why?  It seems to me that produces a much more cumbersome workflow and requires a lot more work by the user.

I mean, suppose I used this app to generate a script, and I've copied that script and associated files over to a cluster, and run a simulation with it.  And now I decide I want to run it again, only with a different temperature.  So I can either 1) change one number in the script and rerun it, or 2) bring up the application again, go through the setup workflow again, generate a new script, and copy that script over to the cluster.

> Changing cutoffs and integrators from the app with dropdowns and tooltips is a better experience. If it isn't, then we should stick with the status quo of do everything in the script. 

It's not either/or.  Sometimes one is better, sometimes the other is.

It comes back to the question of what users we're targeting and what problems we're trying to solve for them.  For a new user who doesn't know what they're doing, a GUI is very friendly.  It lets them get something up and running very quickly, without reading lots of documentation first.  It can guide them in making good decisions.  But once they have a first simulation up and running, changing one number in a file can be much easier.

Also, a goal is to help them grow into the more powerful features.  If we teach them that system setup is a black box done by an opaque application, they'll be forever limited to the options in that application.  But if we give them a script that shows exactly what's happening and encourage them to edit it, they'll discover how easy it is to do all sorts of other things.

**Comment by swails** [comment]
> Changing cutoffs and integrators from the app with dropdowns and tooltips is a better experience.

My question doesn't have a single correct yes/no answer -- the "best" yes/no answer would be based on rather involved research to see how users actually tried to use it.  To me, the better UX is to make the parameters user-editable inside the top of the script.

Also, it's pretty trivial to support both.  The dropdown can be used to set the default value, but you can still make it user-editable as @peastman suggested.

**Comment by peastman** [comment]
I have a very early prototype of this written.  At the moment I'm just trying to reproduce the functionality of the script builder, so it doesn't clean up PDB files or run simulations or anything like that.  And a lot of options aren't hooked up yet (for example, only PDB and PDBx files work right now), and it looks ugly, and I haven't even tried running the script it generates.  It's still just a prototype!  But it's reached the point where you can try it out if you want to see how I'm approaching it.

Here's what you need to do:

- `pip install flask`
- Get the code from https://github.com/peastman/openmm-setup.
- cd to the openmm-setup directory.
- Type the following:
```
export FLASK_APP=openmm-setup
export FLASK_DEBUG=1
flask run
```
- Point your web browser to http://127.0.0.1:5000.

**Comment by jaimergp** [comment]
After following your instructions, all ll I get is `ImportError: No module named 'openmm-setup'`.

I am running this from a new Py35 conda environment, with freshly installed openmm and flask, from inside the cloned openmm-setup repo. The variables are exported and everything, but it can't seem to find the module for some reason (?).

**Comment by peastman** [comment]
Sorry, my mistake.  That should have been

```
export FLASK_APP=openmm-setup.py
```

I'll correct the  instructions above.

**Comment by peastman** [comment]
Lots of updates.  It looks a lot nicer now.

**Comment by hainm** [comment]
may be just add

```python
if __name__ == '__main__':
    app.run()
```

then 
```bash
python openmm-setup.py
```

**Comment by peastman** [comment]
You can now run simulations from inside the browser.  I'd really appreciate feedback.  The more I write, the more work it becomes to make changes to the basic design.

**Comment by mpharrigan** [comment]
I opened a bunch of issues on the repo with specifics!

**Comment by peastman** [comment]
Thanks!  Note though that I'm really looking for feedback on the overall design.  As I noted above, it's still at the prototype stage and lots of things don't work yet.

**Comment by jchodera** [comment]
Absolutely nothing happens when I select a PDB file. No output, no "loading...", no updates, just nothing. It's like I never selected a PDB file.

Using Chrome Version 54.0.2840.98 (64-bit) on OS X 10.11.6 (15G100).

**Comment by peastman** [comment]
What do you mean by "select a PDB file"?  Do you mean when you select PDB as your input format on the first page?  Or when you click the "Browse" button on the second page?  Or when you click "Continue" on the second page?

Check the console to see if any errors have been printed.

**Comment by jchodera** [comment]
1. Select "PDB" radio button.
2. Click "Continue"
3. Under "Input File", click the "Browse..." button
4. Select `7dfr.pdb`, which was downloaded from the RCSB, and click "Open".
5. Nothing happens. "Continue" is still grayed out.

Console output, in its entirety:
```
bash-3.2$ flask run
 * Serving Flask app "openmm-setup"
 * Forcing debug mode on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 157-205-233
127.0.0.1 - - [22/Nov/2016 18:43:43] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [22/Nov/2016 18:44:01] "GET /selectFiles?type=pdb HTTP/1.1" 200 -
```

**Comment by mpharrigan** [comment]
It is this https://github.com/peastman/openmm-setup/issues/1

**Comment by peastman** [comment]
Thanks, I think I've fixed it.  Try now.

**Comment by jchodera** [comment]
Have you thought about making this installable via a `setup.py` with an `entry_point` so that we can just
```
pip install git+https://github.com/peastman/openmm-setup.git
openmm-setup
```
to test?

**Comment by peastman** [comment]
Yes, the whole process of installing and running will need to get cleaned up.

**Comment by jchodera** [comment]
It's a good start! I worry that the target audience of this particular tool may currently be of measure zero, but I imagine you can take it in places that will increase the potential audience size.

**Comment by peastman** [comment]
> I worry that the target audience of this particular tool may currently be of measure zero, but I imagine you can take it in places that will increase the potential audience size.

Such as?  What issues are you concerned about that would keep it from being useful?

**Comment by jchodera** [comment]
I'm just trying to figure out who will use this. Right now, it's someone who knows enough to prepare an RCSB structure for MD simulation, but not enough to actually run an MD simulation without a GUI. That's literally nobody I've ever met. 

You mentioned that integrating PDBFixer is on your roadmap, though---that will help immensely!

**Comment by peastman** [comment]
The planned feature set is what I described above: https://github.com/pandegroup/openmm/issues/1610#issuecomment-259791674.  I just haven't implemented all of it yet!

**Comment by jchodera** [comment]
Ah, OK, thanks! I had missed that.

**Comment by peastman** [comment]
I have PDBFixer integration partly implemented.  Not all features are there yet, but the ones that are there should work correctly.

**Comment by peastman** [comment]
The PDBFixer integration is now complete.  We're getting closer to something that could be called a beta.  Now it needs a whole lot of polishing and testing.

One issue I've had questions about is equilibration.  Right now, I have it do an energy minimization, then run a user specified number of equilibration steps.  For constant temperature that's probably fine, except should the energy minimization be optional?  I'm not sure whether we should ask the user about that or not.

For constant energy, though, I'm really not sure what we should do.  What are standard protocols for this?  Energy minimize, then set initial velocities based on temperature?  Equilibrate with a Langevin integrator before starting the main simulation?  I guess it depends on *why* the person is running constant energy, and I'm not really sure what all the reasons are someone might want to do that.

**Comment by jchodera** [comment]
> One issue I've had questions about is equilibration. Right now, I have it do an energy minimization, then run a user specified number of equilibration steps. For constant temperature that's probably fine, except should the energy minimization be optional? I'm not sure whether we should ask the user about that or not.

In my experience, if energy minimization is avoided, simulations rapidly explode in OpenMM. On the other hand, energy minimization is excruciatingly slow.

> For constant energy, though, I'm really not sure what we should do. What are standard protocols for this? Energy minimize, then set initial velocities based on temperature? Equilibrate with a Langevin integrator before starting the main simulation? I guess it depends on why the person is running constant energy, and I'm not really sure what all the reasons are someone might want to do that.

Do we really want to support this? What's the expected use case?

If so, if the goal is to really mimic an equilibrium simulation, the system should be equilibrated with a Langevin integrator with strong coupling before starting the Verlet (or velocity Verlet) simulation.

Note that Verlet is achieved in the limit of zero collision rate for the LangevinIntegrator, so it may be simpler to just support separate collision rates for the equilibration and production phases, setting them to strong (e.g. 91/ps) and weak (2/ps) collision rates by default.

**Comment by peastman** [comment]
Removing the option for constant energy would be an easy solution.  There certainly are situations where people want to run constant energy, but that may be more of a "for experts only" case.  It's only something you should do if you really know what you're doing.

**Comment by jchodera** [comment]
Sure, and they can just set the collision rate for the production simulation to 0 in that case.

**Comment by peastman** [comment]
> Sure, and they can just set the collision rate for the production simulation to 0 in that case.

If you set the friction to 0, you'll get nans.  It might be possible to support that as a special case, but it would take some work.

**Comment by jchodera** [comment]
Really? This works fine for velocity Verlet discretization Langevin integrators [like VVVR](https://github.com/choderalab/openmmtools/blob/master/openmmtools/integrators.py#L682-L831), from what I recall.

**Comment by peastman** [comment]
Take a look at https://github.com/pandegroup/openmm/blob/master/platforms/reference/src/SimTKReference/ReferenceStochasticDynamics.cpp#L124-L127, and note that `tau` is 1/friction.  As you take the limit that friction->0, various quantities become 0*infinity.

**Comment by jchodera** [comment]
There's never a need to explicitly represent the inverse collision rate (timescale) `tau`. Pretty much all Langevin integrators exclusively use the dimensionless ratio `s = dt/tau = alpha*dt` and use this in computing some sort of scaling factor for mixing the current velocity with a source of random noise. They only use `s` in a manner where it is OK for `s` to be zero.

**Comment by peastman** [comment]
> On the other hand, energy minimization is excruciatingly slow.

I have some thoughts about that.  I'll post them on the issue where we were discussing minimization.

**Comment by peastman** [comment]
> Pretty much all Langevin integrators exclusively use the dimensionless ratio `s = dt/tau = gamma*dt`

Not this one, unless I'm missing something.  Here's the relevant code:

```C++
const RealOpenMM vscale = EXP(-getDeltaT()/tau);
const RealOpenMM fscale = (1-vscale)*tau;
const RealOpenMM kT = BOLTZ*getTemperature();
const RealOpenMM noisescale = SQRT(2*kT/tau)*SQRT(0.5*(1-vscale*vscale)*tau);
```

So `vscale` depends only on the ratio.  But `fscale = (1-exp(-dt*gamma))/gamma)`.  Of course if you take the limit `gamma`->0, the exponential becomes `1-dt*gamma` so that simplifies to `(1-1+dt*gamma)/gamma = dt`.  But for any finite value of `gamma`, it can't be written as a function of only the ratio.  So `gamma=0` has to be handled as a special case.

**Comment by peastman** [comment]
I think we're ready to move forward with a 1.0 release.  I'll transfer the repository to the pandegroup organization and start preparing the release.  Any further discussion can happen there, so I'll close this issue.
