### ISSUE TITLE
createSystem for small molecules

### ISSUE THREAD

**Issue by mzott** [pandegroup/openmm#1635]
I would like to use OpenMM for small molecules without defined residues by using atom types assigned through a program such as Antechamber, CGenFF, or a self-built tool. It seems like the createSystem method in the ForceField class assigns atom types by matching residues with templates; I made a rough script that will create an OpenMM system using the atom types from an atom typer and charges by passing these dictionaries into the corresponding OpenMM dictionaries. The pseudo-code is:

• Read in XYZ file
• Make topology with arbitrary residues/chains
• Generate atom types and charges 
• Create OpenMM system
• Run OpenMM methods

Would it be possible to arrange this procedure so that the powerful Modeller class would still work? I thought about using my custom createSystem method in the Modeller class in order to use the custom atom types, but I’m not sure that will work.

**Comment by jchodera** [comment]
We currently have experimental support for this via the [`registerTemplateGenerator`](http://docs.openmm.org/7.0.0/api-python/generated/simtk.openmm.app.forcefield.ForceField.html#simtk.openmm.app.forcefield.ForceField.registerTemplateGenerator) method. You call it with a Python function that will be called when `ForceField` encounters a residue in the `Topology` object for which no parameters can be found. It will then call your generator with the `ForceField` and `Residue` object so you can call 
* `forcefield.registerResidueTemplate(template)`
* `forcefield.loadFile(file)` to load residue definitions from an ffxml file you generate
* It can also use the ForceField programmatic API to add additional atom types (via `forcefield.registerAtomType(parameters)`)

An example of this that uses Antechamber to assign GAFF parameters is found [here](https://github.com/choderalab/openmoltools/blob/master/openmoltools/forcefield_generators.py).

More extensive support for small molecule generation via Antechamber and CGenFF is coming in a forthcoming release (currently slated for OpenMM 7.2).

**Comment by peastman** [comment]
Most methods in Modeller just require a Topology object, so as long as you can create that, those methods should work.  And they create a new Topology object.  So that is what then serves as the input for your routines to generate atom types and create the System.

**Comment by mzott** [comment]
Thanks - I will try out the Modeller class with the Topology object inputs again. That seems like it should be a pretty easy fix.

**Comment by peastman** [comment]
Can this issue be closed?
