### ISSUE TITLE
Modeller.addSolvent numAdded argument sometimes adds incorrect number of waters

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1636]
The number of requested waters and the number of actual waters added does not match when `neutralize=True` and ions must be added. 

The script below on the provided PDB file produces the following output:

```
[LSKI1497:choderalab/ensembler/ensembler.jchodera] choderaj% python addsolvent-bug.py
target_nwaters = 16262
actual_nwaters = 16259
```

where the discrepancy is due to three added `Cl-` ions.

We should presumably either modify the code to produce the desired number of waters (in addition to the number of ions that must be added) or clarify the documentation. I think users would prefer the less surprising former solution rather than the latter one, since the number of waters requested would then match the number of waters added.

Here is the script:

``` python
from simtk import openmm, unit
from simtk.openmm import app

target_nwaters = 16262
print('target_nwaters = %d' % target_nwaters)

forcefield = app.ForceField('amber99sbildn.xml', 'tip3p.xml')
water_model = 'tip3p'
pdb = app.PDBFile('model-initial.pdb')
modeller = app.Modeller(pdb.topology, pdb.positions)
modeller.addSolvent(forcefield, model=water_model, numAdded=target_nwaters)

# Count actual number of waters
def count_waters(topology):
    nwaters = 0
    for residue in topology.residues():
        if residue.name == 'HOH':
            nwaters += 1
    return nwaters

actual_nwaters = count_waters(modeller.topology)
print('actual_nwaters = %d' % actual_nwaters)
```

PDB file and script file are attached.
[addsolvent-bug.zip](https://github.com/pandegroup/openmm/files/531289/addsolvent-bug.zip)

**Comment by peastman** [comment]
`numAdded` is the total number of molecules (waters plus ions) to add.  See the API docs.  So it sounds to me like this is working as intended.

**Comment by jchodera** [comment]
Hm, I seem to recall the original feature request was to allow control of
the number of waters added.

Since there's no way to check how many waters will be replaced with ions,
what if we did one of the following:

(1) add a numWaters optional argument that can be specified instead
(2) add a method to retrieve the total charge (which will tell us how many
ions will be added)

**Comment by peastman** [comment]
We had a pretty long discussion about this when it was implemented.  See #886.

**Comment by jchodera** [comment]
You have to at least give me points for consistency in still trying to argue for a way to specify the total amount of *waters* added.  :)
