### ISSUE TITLE
What is the domain for the `dihedral()` function in CustomCompoundBoundForce?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1637]
To use the `dihedral` function defined in [`CustomCompoundBondForce`](http://docs.openmm.org/7.0.0/api-python/generated/simtk.openmm.openmm.CustomCompoundBondForce.html#simtk.openmm.openmm.CustomCompoundBondForce), it's necessary to know what domain this function uses. The docs don't seem to specify.

**Comment by peastman** [comment]
It's -pi to pi.  The docs do specify that for CustomTorsionForce, but perhaps we forgot to mention it for CustomCompoundBondForce.

**Comment by jchodera** [comment]
If one wanted to implement a harmonic restraint on a torsion*, is there a simple way to do this such that the domain is shifted to `[-pi, +pi)` around the reference torsion `phi0`? The documentation doesn't specify whether we have a "modulo" operation that would be useful in shifting the domain.

* Yes, I know this is a dumb idea since torsions are periodic, but it's something we have to do for "backward-compatibility" with stuff in the literature.

**Comment by jchodera** [comment]
Actually, I don't see the domain documented in [`CustomTorsionForce`](http://docs.openmm.org/7.0.0/api-python/generated/simtk.openmm.openmm.CustomTorsionForce.html#simtk.openmm.openmm.CustomTorsionForce) either. I'll add it to both.

**Comment by peastman** [comment]
Maybe something like this?

```
f(s); s=t-round(t/(2*pi))*2*pi; t=theta-theta0
```

We do specify the range at http://docs.openmm.org/7.0.0/userguide/theory.html#customtorsionforce, but having it in the API docs too would be good.  Note that the range is specified as [-pi,pi], *not* [-pi,pi).  That is, your expression should be prepared to handle values of exactly -pi or pi.  In practice, a particular platform will implement it in a way that gives a range of either [-pi,pi) or (-pi,pi], but we don't guarantee which it will be.

**Comment by jchodera** [comment]
Thanks! I've updated the PR to amend both the API and theory guide docs.

**Comment by jchodera** [comment]
> Maybe something like this?
```
f(s); s=t-round(t/(2*pi))*2*pi; t=theta-theta0
```
Huh. I wouldn't have thought of that, but I'll give it a try!

**Comment by jchodera** [comment]
Whoops:
```
unknown function: round
```
Looks like the [docs specify `ceil` and `floor`, but no `round`](http://docs.openmm.org/7.0.0/api-python/generated/simtk.openmm.openmm.CustomCompoundBondForce.html#simtk.openmm.openmm.CustomCompoundBondForce).

I'll use
```
round(x) = floor(x + 0.5)
```
but it might be neat to add `round()` since it seems to be useful.

**Comment by jchodera** [comment]
`lepton` won't allow us to define lambda functions that get substituted, will it? It will only substitute variables?

**Comment by peastman** [comment]
Correct.
