### ISSUE TITLE
Flag to allow residues with missing external bonds

### ISSUE THREAD

**Issue by tristanic** [pandegroup/openmm#1643]
Hi,

I'd like to suggest the attached change to forcefield.py. I've added an extra optional parameter, ignoreMissingExternalBonds, to createSystem. If true it allows the residue to match a template with the correct internal bonding even if one or more external bonds is missing (for example, an amino acid residue that's not bonded either to a neighbour or an OXT). The reason I need this is that I'm creating small interactive simulations cropped out of larger structures, with the outer shell of residues fixed in space to keep it all in context. Needless to say, this leaves me with many residues with missing external bonds - and it wouldn't make any physical sense to add them.

Best regards,

Tristan 

[forcefield.tar.gz](https://github.com/pandegroup/openmm/files/539436/forcefield.tar.gz)

**Comment by tristanic** [comment]
Hmm... wait, that doesn't quite work properly yet. I need to adjust it to still find the correct template when external bonds *are* present - currently disulfide bonds come out behaving very strangely indeed.

**Comment by tristanic** [comment]
This now works as expected.
[forcefield.tar.gz](https://github.com/pandegroup/openmm/files/539610/forcefield.tar.gz)

**Comment by peastman** [comment]
This sounds like a reasonable feature, and I can see the value of it.  The one thing that makes me a little nervous is whether it will ever create ambiguities.  Could there be cases where a residue could match two different templates, one with an external bond and one without?  Usually that shouldn't be a problem.  Terminal residues generally differ in other respects.  Likewise, CYS residues that participate in disulfides will be missing a hydrogen.  Possibly with united atom force fields it could happen though?

Probably I'm just worrying too much about an obscure corner case.  If we just tell users, "It's your job to make sure there aren't any ambiguities," that's probably good enough.

**Comment by tristanic** [comment]
The CYS example is one that could certainly lead to unexpected results - a CYS without a hydrogen on the sulphur is treated as deprotonated (i.e. with a formal charge of -1). But I agree with your last sentence - this would be a flag that should come with the warning, "only use if you know exactly what you're doing."

**Comment by peastman** [comment]
I hadn't thought about the charged CYS case.  There's really no way we can determine whether it's supposed to be negatively charged, or form a disulfide to another residue that's missing.

What about this as an alternative design.  `createSystem()` already has a `residueTemplates` argument you can use to force it to use a particular template for a particular residue.  It does check to make sure the template actually matches, though.  What if we make it tolerant of missing external bonds when doing that check?  So normally it will only match templates if all the external bonds are correct, but if you explicitly tell it to use a particular template, it will accept that even if there are missing external bonds.  In your case, you would use that to tell it what template to use for any residues bonded to missing parts of the system?

**Comment by tristanic** [comment]
How about a hybrid approach? I can see the value in pre-defining which templates to use if you want to run a non-interactive simulation from the command line, but what I'm building is all about interactivity - make a selection, click a button to make it mobile then start poking at it. Requiring the user to pre-define templates in that case would be non-ideal - if more than one template matches I think it would be better to just throw an exception listing the possibilities. Then I can catch it, bring up a dialog box asking the user to choose, and restart/continue using your suggested `residueTemplates` to specify the chosen template.

**Comment by peastman** [comment]
That could work.

**Comment by peastman** [comment]
Give it a try and see how it works for you.

**Comment by tristanic** [comment]
Thanks, will do!
