### ISSUE TITLE
ZOnly axis type returning incorrect energies in AmoebaMultipoleForce

### ISSUE THREAD

**Issue by mvanvleet** [pandegroup/openmm#1644]
The AmoebaMultipoleForce is supposed to support a variety of axis types, as described in the [Amoeba2013 paper](http://pubs.acs.org/doi/abs/10.1021/ct4003702), and as coded in [here]( https://github.com/pandegroup/openmm/blob/master/plugins/amoeba/openmmapi/include/openmm/AmoebaMultipoleForce.h). I believe the ZOnly convention is currently being handled incorrectly, as shown in the 3 examples in the attached tarball:

[test_axistypes.zip](https://github.com/pandegroup/openmm/files/540234/test_axistypes.zip)

Each example in the 3 subdirectories is of a benzene dimer, and can be run via the command line:
```
$ python run_benzene.py
```

In each of these examples, I've placed a dzz (y20 for those more familiar with spherical tensor notation) multipole moment on each hydrogen; because this multipole moment only depends on the z-axis, the choice of x-axis shouldn't matter. Indeed, using the Z-then-x convention for different choices of the x axis (subdirectories 02 and 03 in the attached tarball) returns the same energy. However, if I don't select a x-axis (kx="0" in the .xml file from subdirectory 01), then I get a completely different energy, which is incorrect.

I suspect the problem lies with setting up the multipole parameters, since printing the Amoeba Multipole parameters for hydrogen yields

```
[Quantity(value=0.0, unit=elementary charge), Quantity(value=(0.0, 0.0, 0.0), unit=nanometer*elementary charge), Quantity(value=(-0.01, 0.0, 0.0, 0.0, -0.01, 0.0, 0.0, 0.0, 0.02), unit=nanometer**2*elementary charge), 4, -1, -1, -1, 0.39, 0.0, Quantity(value=0.0, unit=nanometer**3)]
```

such that kz=kx=ky=-1 instead of the input kz=1, kx=ky=0.

**Comment by peastman** [comment]
Thanks!  It turns out that ZOnly is never actually used by the standard AMOEBA force fields, which is why this didn't get caught before.  This is fixed by #1646.

Even with the fix, your test produces a nan for the energy when run on CUDA.  That's because you have all the polarizabilities set to 0.  Changing them to a finite value makes it work correctly.

**Comment by mvanvleet** [comment]
@peastman , does that mean that AmoebaMultipoleForce can't be used with CUDA to run a non-polarizable model? I definitely want to run non-polarizable simulations with higher-order multipoles in the future, and it would be nice to be able to do this on the CUDA platform.

**Comment by peastman** [comment]
I'm not sure what would be involved in supporting polarizability=0.  Possibly just a few extra checks to avoid divides by 0, but I'd have to go through the code to see.

**Comment by mvanvleet** [comment]
Especially if this isn't too challenging, it'd be great to support polarizability=0. In addition to some of my own force fields, I can think of at least one [recent force field](http://scitation.aip.org/content/aip/journal/jcp/145/3/10.1063/1.4958621) that uses multipoles without polarizability. Furthermore, it's fairly common to make hydrogen atoms non-polarizable and to only include induced dipoles on heavy-atom sites (I can try and find references for this type of approach if necessary).

**Comment by peastman** [comment]
I'll look into it and see how hard that is to support.  Keep in mind that you won't get any performance benefit from making them nonpolarizable.  It will still do all the calculations to compute induced dipoles.  It just won't produce nans.  (If *nothing* is polarizable you can set the polarization mode to direct, which will keep the cost fairly low.  But if you want some atoms polarizable and others not, you'll pay the cost of computing all of them.)

**Comment by peastman** [comment]
Ok, I think I have it working.  See #1647.

**Comment by mvanvleet** [comment]
Not urgent, but I just found a system that's giving me NaN errors when I set any of the polarizabilities to zero. Attached is a test system for debugging purposes:

[nan_error_wi_zero_polarization.zip](https://github.com/pandegroup/openmm/files/1030734/nan_error_wi_zero_polarization.zip)
