### ISSUE TITLE
Precision in CustomIntegrator kernels

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1677]
In GHMC (Metropolized Langevin dynamics) implementations for OpenCL using mixed precision, the following forms of the inner velocity Verlet step have very different 

Version 1 (based on the "velocity Verlet" example code):
```python
        self.addComputePerDof("v", "v + 0.5*dt*f/m")
        self.addComputePerDof("x", "x + v*dt")
        self.addComputePerDof("x1", "x")
        self.addConstrainPositions()
        self.addComputePerDof("v", "v + (x-x1)/dt + 0.5*dt*f/m")
        self.addConstrainVelocities()
```
Version 2:
```python
        self.addComputePerDof("v", "v + 0.5*dt*f/m")
        self.addComputePerDof("x", "x + v*dt")
        self.addComputePerDof("x1", "x")
        self.addConstrainPositions()
        self.addComputePerDof("v", "v + (x-x1)/dt")
        self.addComputePerDof("v", "v + 0.5*dt*f/m")
        self.addConstrainVelocities()
```
Surprisingly, Version 2 has much better acceptance rates than version 1.

Looking through the [code for `CustomIntegrator](https://github.com/pandegroup/openmm/blob/master/platforms/cuda/src/CudaKernels.cpp#L7076-L7097), it looks like there is some cleverness going on with how positions are represented---even in mixed precision.

Any chance we could get a more elaborate explanation of how this works, and what we might be able to do to improve numerical conditioning in these Metropolized integrators?

**Comment by jchodera** [comment]
Actually, the "better" acceptance rate might be incorrect. Surprisingly, in Version 2, I'm seeing essentially exactly 50% acceptance rates (meaning the total energy goes down ~50% of the time) in pretty much every system with every combination of settings, which sounds highly suspicious.

**Comment by jchodera** [comment]
Hm, it looks like the [potential energy is stored as a float](https://github.com/pandegroup/openmm/blob/master/platforms/cuda/src/CudaKernels.cpp#L7190-L7193), as is [the kinetic energy](https://github.com/pandegroup/openmm/blob/master/platforms/cuda/src/CudaKernels.cpp#L7285-L7288). 

Is there any way to store globals in double precision in `mixed` mode? I wonder if the small differences in large potential energies we're computing in Metropolized integrators is suffering as a result of the use of single-precision floating point numbers there.

I had thought that `mixed` precision used double-precision throughout the integrators and constraints but used single-precision for forces, but it looks like that isn't the case.

**Comment by peastman** [comment]
It's not even the globals, it's only the potential energy.  Its type should be defined as `mixed` instead of `real` at https://github.com/pandegroup/openmm/blob/master/platforms/cuda/src/kernels/customIntegratorPerDof.cu#L37.  That will be easy to fix.

**Comment by jchodera** [comment]
Awesome, thanks!

Are there other instances where variables are being stored in single precision even in `mixed` precision mode?

I'm especially wondering if its possible to store positions and velocities in double precision, since it's super confusing when the gymnastics that `CustomIntegrator` goes through to achieve extra precision when possible in positions (but not velocities?) cause weird cases where
```python
        self.addComputePerDof("v", "v + (x-x1)/dt")
        self.addComputePerDof("v", "v + 0.5*dt*f/m")
```
and
```python
        self.addComputePerDof("v", "v + (x-x1)/dt + 0.5*dt*f/m")
```
give totally numerically different results.

**Comment by peastman** [comment]
Those should give identical results.  If they don't, something strange is going on.

It isn't actually doing anything very unusual with the representation.  It just stores the positions as two floats rather than one double.  That's to avoid extra expense when loading the positions into the force kernels (since they'd immediately cast them to floats anyway.)  There's no need for that with the velocities, since force kernels don't use them.

**Comment by jchodera** [comment]
Would it help to have some sort of minimal demonstration you can try to see that they give different results? Let me know if I can help debug further!

**Comment by peastman** [comment]
That would be great.

**Comment by jchodera** [comment]
Here you go!

Output:
```
mski1776:yank.choderalab choderaj$ python customintegrator-statement-ordering.py 
combined
  Accepted 481 / 500 GHMC steps (  96.200 %)
split
  Accepted 257 / 500 GHMC steps (  51.400 %)
```
You'll need `openmmtools` installed (`conda install -c omnia openmmtools`).

[customintegrator-statement-ordering.zip](https://github.com/pandegroup/openmm/files/617495/customintegrator-statement-ordering.zip)

The example runs a GHMC (Metropolized Langevin) integrator with the exact same starting conditions and settings, where the only difference is in the second velocity half-kick and RATTLE correction for the velocity Verlet inner core, `combined`:
```python
        self.addComputePerDof("v", "v + (x-x1)/dt + 0.5*dt*f/m")
```
vs `split`:
```python
        self.addComputePerDof("v", "v + (x-x1)/dt")
        self.addComputePerDof("v", "v + 0.5*dt*f/m")
```

**Comment by jchodera** [comment]
If you change the `timestep`, you can affect the `combined` acceptance rate in a logical way, but the `split` acceptance rate is always ~51%.

2.5 fs timestep:
```
mski1776:yank.choderalab choderaj$ python customintegrator-statement-ordering.py 
combined
  Accepted 311 / 500 GHMC steps (  62.200 %)
split
  Accepted 259 / 500 GHMC steps (  51.800 %)
```
4 fs timestep:
```
mski1776:yank.choderalab choderaj$ python customintegrator-statement-ordering.py 
combined
  Accepted 0 / 500 GHMC steps (   0.000 %)
split
  Accepted 258 / 500 GHMC steps (  51.600 %)
```

**Comment by peastman** [comment]
I've tried to install openmmtools before, but it fails because it lists OpenMM as a dependency, so it tries to install that from conda, which conflicts with the version I installed from source.

**Comment by jchodera** [comment]
Try this:
```python
conda install -c omnia --no-deps openmmtools
```
If you run into trouble, you may need to install some dependencies alongside it. Here's the complete mess:
```python
conda install -c omnia --nodeps openmmtools cython numpy scipy parmed
```

**Comment by jchodera** [comment]
To see if I could debug this a bit, I added the following line to print out the OpenCL program source code in `CustomIntegrator`:
```C++
```
Here is the relevant code generated for the lines that differ between the two velocity updates:

Combined:

Python
```python
        self.addComputePerDof("v", "v + (x-x1)/dt + 0.5*dt*f/m")
```
OpenCL:
```C++
{
double temp0_22 = 5.00000000e-01f*stepSize;
double temp0_23 = temp0_22*f.x;
double temp0_24 = temp0_23/mass;
double temp0_25 = velocity.x+temp0_24;
double temp0_26 = position.x-perDofx1.w;
double temp0_27 = temp0_26/stepSize;
double temp0_28 = temp0_25+temp0_27;
velocity.x = temp0_28;
double temp1_22 = 5.00000000e-01f*stepSize;
double temp1_23 = temp1_22*f.y;
double temp1_24 = temp1_23/mass;
double temp1_25 = velocity.y+temp1_24;
double temp1_26 = position.y-perDofy1.w;
double temp1_27 = temp1_26/stepSize;
double temp1_28 = temp1_25+temp1_27;
velocity.y = temp1_28;
double temp2_22 = 5.00000000e-01f*stepSize;
double temp2_23 = temp2_22*f.z;
double temp2_24 = temp2_23/mass;
double temp2_25 = velocity.z+temp2_24;
double temp2_26 = position.z-perDofz1.w;
double temp2_27 = temp2_26/stepSize;
double temp2_28 = temp2_25+temp2_27;
velocity.z = temp2_28;
velm[index] = convert_mixed4(velocity);
}
```
Split: 

Python
```python
        self.addComputePerDof("v", "v + (x-x1)/dt")
        self.addComputePerDof("v", "v + 0.5*dt*f/m")
```
OpenCL
```C++
{
double temp0_22 = position.x-perDofx1.w;
double temp0_23 = temp0_22/stepSize;
double temp0_24 = velocity.x+temp0_23;
velocity.x = temp0_24;
double temp1_22 = position.y-perDofy1.w;
double temp1_23 = temp1_22/stepSize;
double temp1_24 = velocity.y+temp1_23;
velocity.y = temp1_24;
double temp2_22 = position.z-perDofz1.w;
double temp2_23 = temp2_22/stepSize;
double temp2_24 = velocity.z+temp2_23;
velocity.z = temp2_24;
velm[index] = convert_mixed4(velocity);
}
{
double temp0_22 = 5.00000000e-01f*stepSize;
double temp0_23 = temp0_22*f.x;
double temp0_24 = temp0_23/mass;
double temp0_25 = velocity.x+temp0_24;
velocity.x = temp0_25;
double temp1_22 = 5.00000000e-01f*stepSize;
double temp1_23 = temp1_22*f.y;
double temp1_24 = temp1_23/mass;
double temp1_25 = velocity.y+temp1_24;
velocity.y = temp1_25;
double temp2_22 = 5.00000000e-01f*stepSize;
double temp2_23 = temp2_22*f.z;
double temp2_24 = temp2_23/mass;
double temp2_25 = velocity.z+temp2_24;
velocity.z = temp2_25;
velm[index] = convert_mixed4(velocity);
}
```

**Comment by peastman** [comment]
I've been working on it for the last few hours.  It's something more subtle than that.  If I split it like this, it fails:

```Python
            self.addComputePerDof("v", "v")
            self.addComputePerDof("v", "v + 0.5*dt*f/m + (x-x1)/dt")
```

But if I split it like this, it works:

```Python
            self.addComputePerDof("v", "v + 0.5*dt*f/m + (x-x1)/dt")
            self.addComputePerDof("v", "v")
```

**Comment by kyleabeauchamp** [comment]
Hmm, hopefully this improves the acceptance rate of my MTS GHMC integrators.  I think I was still seeing some occasional situations where the acceptance rate was not as high as I was expecting, and it could very well have to do with this issue.

**Comment by jchodera** [comment]
It all comes down to accurately representing the small difference between two large energies, so that's always a bit tricky.

@kyleabeauchamp : If you're using CUDA, are you using the deterministic PME option?

**Comment by kyleabeauchamp** [comment]
No, AFAIK.  I believe I was using higher accuracy PME, longer cutoffs, and a switch based on some previous issues we went over.

**Comment by jchodera** [comment]
You might try setting [`DeterministicForces` to `1`](https://github.com/pandegroup/openmm/blob/f7935fef719ed0cd8292afef676c39d881b6a960/platforms/cuda/include/CudaPlatform.h#L120-L126) if you're using CUDA.
