### ISSUE TITLE
Cannot build C++ API docs

### ISSUE THREAD

**Issue by peastman** [pandegroup/openmm#1685]
At some point, building the C++ API docs stopped working.  It fails with this message:

```
Exception occurred:
  File "/Users/peastman/anaconda/lib/python3.4/site-packages/sphinxcontrib/autodoc_doxygen/autosummary/__init__.py", line 41, in import_by_name
    raise ImportError('no module named %s' % ' or '.join(tried))
ImportError: no module named NonbondedMethod
```

@rmcgibbo it looks like this is happening in your autodoc_doxygen library.  Any idea what's going on?

**Comment by jchodera** [comment]
Are we somehow not testing this in a travis branch?

**Comment by peastman** [comment]
@rmcgibbo I sent a PR fixing the problem in autodoc_doxygen.  If you can merge it and make a new conda release, that would be great.

**Comment by peastman** [comment]
Fixed by https://github.com/rmcgibbo/sphinxcontrib-autodoc_doxygen/pull/17.
