### ISSUE TITLE
Creating checkpoints and resuming simulations from where they left off (Python API)

### ISSUE THREAD

**Issue by bmanubay** [pandegroup/openmm#1691]
Hello all,

I'm trying to script up a way to run a simulation with OpenMM and periodically measure the number of uncorrelated samples collected using PyMBAR. I was looking through some of the OpenMM Python API documentation and couldn't figure out how to stop the simulation and create a checkpoint file (so I could run the PyMBAR analysis) and then resume recording the simulation in the trajectory where I had previously stopped it. Any ideas? Thanks!

**Comment by peastman** [comment]
To write a checkpoint, call `saveCheckpoint()` or `saveState()` on the Simulation.  See http://docs.openmm.org/7.0.0/api-python/generated/simtk.openmm.app.simulation.Simulation.html#simtk.openmm.app.simulation.Simulation for details.

The DCD writer doesn't currently have an append mode to continue writing to an existing file.  We should add one.  But for the moment, you'll need to write each segment of the trajectory to a different file and then merge them together later, which isn't hard.

**Comment by bmanubay** [comment]
Great! Thanks Dr. Eastman! And agreed, an append mode for the writer would be great.

**Comment by euhruska** [comment]
Would be useful for me too

**Comment by peastman** [comment]
Closing since the question was answered.  Also note that DCDFile now has an append option.
