### ISSUE TITLE
Modify AmoebaMultipoleForce Exclusions?

### ISSUE THREAD

**Issue by yudongqiu** [pandegroup/openmm#1693]
Dear Developers,

I found that the Python API AmoebaVdwForce.setParticleExclusions() is very convenient when we are trying to exclude more or less atoms in the molecule. I didn't find the same function for AmoebaMultipoleForce. I tried to use AmoebaMultipoleForce.setCovalentMap() to set the level 0 or level 1 covalent map to include every atom but it didn't work. May I ask if there is a good way to manipulate the exclusion list for AmoebaMultipoleForce?

Thanks,

Yudong Qiu

**Comment by yudongqiu** [comment]
An update: I found that for atom i, calling f.setCovalentMap(i,0,all_list) is not enough. To make it work, we looped over all covalentTypes and emptied the other maps:
`for m in range(1, len(f.getCovalentMaps(i))):
                    f.setCovalentMap(i, m, [])`
From our test it seems that this will correctly set up the exclusions, but I still want to make sure we are using the correct functions to make the AmoebaVdwForce exclude all atoms in the same molecule. Thanks!

**Comment by peastman** [comment]
> I still want to make sure we are using the correct functions to make the AmoebaVdwForce exclude all atoms in the same molecule.

Yes, `setParticleExclusions()` is the correct one.

> Perhaps a warning or a check would be helpful, if users like me are not setting it correctly.

Good idea.

**Comment by yudongqiu** [comment]
Thanks a lot for the reply! May I also ask about the CovalentMap for AmoebaMultipoleForce?

Based on my observation, `f.getCovalentMap(i, l)` returns a list of atom indices: For `l=0`, it returns the atoms directly bonded to `i`; For `l=1`, it returns the rest of the atoms that are bonded to the ones in `l=0`; The `l=2` and `l=3` resulting lists are similar to `l=1`, but the `l=4` contains all the atoms in the residue. For `l=5, 6, 7`, the returning list is empty. However I'm not sure how these covalentmaps are used in the implementation. Is there any documents about these detailed settings?

Here, our goal is to make the AmoebaMultipoleForce on atom i to exclude all atom j that are on the same residue as i. I am thinking that I should first setting all atoms on the same residue to the `l=0` map: `f.setCovalentMap(i, 0, [all_atoms])`; Then I should empty the `l=1, 2, 3` maps; Then for `l=4 and above`, I should leave them the same as before. May I ask if this is the correct way to do it?

**Comment by peastman** [comment]
The typeId argument should be one of the values from the `AmoebaMultipoleForce.CovalentType` enumeration:

```C++
Covalent12 = 0, Covalent13 = 1, Covalent14 = 2, Covalent15 = 3,
PolarizationCovalent11 = 4, PolarizationCovalent12 = 5, PolarizationCovalent13 = 6, PolarizationCovalent14 = 7
```

Amoeba handles nonbonded exceptions in a more complicated way than most other force fields.  It defines "polarization groups", which are small clusters of atoms that are treated together for purposes of polarization.  The interaction between two atoms depends on both the distance between the atoms (as measured in bonds), and on the distance between their polarization groups.  So if two atoms are separated by two bonds, and are in the same polarization group, then they would be in the Covalent13 map and in the PolarizationCovalent11 map.

**Comment by yudongqiu** [comment]
Thanks a lot for the explanation! I think I understand it better now.
