### ISSUE TITLE
Particle coordinate is nan with the newest OpenMM version

### ISSUE THREAD

**Issue by Aksonik** [pandegroup/openmm#1695]
Hello,
I have updated OpenMM to the newest git version from Dec 20, 2016, and all simulations that I had been running successfully for hundreds of nanoseconds started crashing with "Particle coordinate is nan". I tried a few systems of distinct size and composition, and a few GPU types, i.e.  GTX-1080, GTX-980, and Tesla K40m, always with the same result. In one of the simulations I am able to reproduce the error - please, find the input files. It looks like a water molecule (residue 29,642) explodes in 168th step without any obvious reason. For comparison, the same simulation runs fine with OpenMM 7.0.1. Could you please take a look?

Best regards,
[system.tar.gz](https://github.com/pandegroup/openmm/files/667576/system.tar.gz)
[integrator.tar.gz](https://github.com/pandegroup/openmm/files/667577/integrator.tar.gz)
[stat.1.tar.gz](https://github.com/pandegroup/openmm/files/667578/stat.1.tar.gz)
[stat.2.tar.gz](https://github.com/pandegroup/openmm/files/667580/stat.2.tar.gz)

**Comment by yumipxd** [comment]
I encountered the same problem in my simulation.

**Comment by Aksonik** [comment]
I guess, this might be informative. Almost all of my simulations terminated with "Particle coordinate is NaN" or "Energy is NaN" error message. However, once I got "Error compiling program: nvrtc: error: invalid value for --gpu-architecture (-arch)", that led me to [#1653](https://github.com/pandegroup/openmm/issues/1653) issue that might be related. I use CUDA Version 8.0.44 and nVidia dirver 375.26.

**Comment by peastman** [comment]
Thanks for the test case!  Almost everyone is out for the holidays right now.  I'll put this near the top of my list to check out when I'm back in the office.

I notice you attached two different states.  Which one should I load in?  Also, I assume this is with the CUDA platform?

**Comment by Aksonik** [comment]
Hi Peter,
Thank you for the response. This is one state divided into two parts. Single file was too big to upload (>10MB). Please, simply uncompress them and splice. Yes, this is CUDA. Happy Holidays.

**Comment by peastman** [comment]
Could you give more details on how to reproduce this?  The following script runs without problem for me:

```Python
from simtk.openmm import *
from simtk.openmm.app import *
from simtk.unit import *

system = XmlSerializer.deserialize(open('mf.system.xml').read())
state = XmlSerializer.deserialize(open('mf.stat.xml').read())
integrator = XmlSerializer.deserialize(open('mf.integrator.xml').read())
context = Context(system, integrator, Platform.getPlatformByName('CUDA'))
context.setState(state)
for i in range(200):
    print(i, context.getState(getEnergy=True).getPotentialEnergy())
    integrator.step(1)
```

This is using the latest code from the repository, a GTX 980, and CUDA 8.0 with the 367.48 driver.

**Comment by yumipxd** [comment]
My jobs usually run for a while (about 1000000~2000000 or more step) before they stop. I use K20m and K80 with CUDA 7.5 and  352.30 driver and the OpenMM version is 7.0.1. This is my scripts and inputs: [Uploading debug.tar.gz…]. There are 7 separate input files (gro), you can run at the same time in order to reproduce the error as soon as possible.

**Comment by yumipxd** [comment]
[debug.tar.gz](https://github.com/pandegroup/openmm/files/689298/debug.tar.gz)

**Comment by Aksonik** [comment]
Peter,
Could you please extend the range in your script to 1000 and try once again? When I do this, along with XML files that I sent, the simulation crashes every time at 501 step. Sorry, I said 168 previously - I don't know why.

**Comment by peastman** [comment]
Do you have a PDB file for this system?  Or anything else from which I could get a Topology.  That would make it a lot easier for me to visualize what's going on.

**Comment by Aksonik** [comment]
Here is the PDB file:
[sys.tar.gz](https://github.com/pandegroup/openmm/files/697075/sys.tar.gz)

**Comment by peastman** [comment]
I just sent a PR with the fix.  Give it a try.
