### ISSUE TITLE
Implement pair-wise nonbonded interaction using CustomNonbondedForce

### ISSUE THREAD

**Issue by yudongqiu** [pandegroup/openmm#1696]
Dear Developers,

We have recently encounterred two issues when we are trying to add a pair-wise nonbonded force in our system, using the CustomNonbondedForce. The first issue is that I found CustomNonbondedForce only support adding particles, but not particle pairs. As a result, if we want to add this force for describing the interaction between RES and water, it appears to be hard to exclude all interactions between water molecules, using the `CustomNonbondedForce.addExclusion(particle1, particle2)`, since there are several thousands of water molecules in our system. May I ask is there a better way to exclude interactions between atom classes or residues? 

A second issue is that in a system with 4 atom classes (class1, class2, water-O, water-H), there are a total of 10 different types of pair-wise interactions, and they are derived from the 4 PerParticleParameters using the combining rule specified in the energy formula, e.g. `energy="4*epsilon*((sigma/r)^12-(sigma/r)^6); sigma=0.5*(sigma1+sigma2); epsilon=sqrt(epsilon1*epsilon2)"`. When we are optimizing the parameters, the degrees of freedom (4) is a lot less than the true pair-wise formula (10). May I ask if there is a good way to implement the true "pair-wise" nonbonded force? In that case the first issue will be also solved.

Thanks,

Yudong

**Comment by jchodera** [comment]
You can use a [`CustomNonbondedForce`](http://docs.openmm.org/7.0.0/api-python/generated/simtk.openmm.openmm.CustomNonbondedForce.html#simtk.openmm.openmm.CustomNonbondedForce) to specify your interactions. This is very flexible, and allows you to both specify special combining rules (which can even depend on tabulated functions) and restrict the computation of these interactions to be between only [specified groups](http://docs.openmm.org/7.0.0/api-python/generated/simtk.openmm.openmm.CustomNonbondedForce.html#simtk.openmm.openmm.CustomNonbondedForce.addInteractionGroup).

**Comment by Lnaden** [comment]
With the `CustomNonbondedForce` you can add any number of `InteractionGroup`s which define sets of atoms that are allowed to interact, even over periodic copies.

e.g.
```python
myCustomNBForce.addInteractionGroup(RES,water)
```
where `RES` is the set of atoms defining the residue and `water` is the set of atoms defining the waters restricts that force to only do interaction between those sets, there will be no `RES`/`RES` interactions nor `water`/`water` interactions in that force. You can define any number of them as well. Documentation for it is [here](http://docs.openmm.org/7.0.0/api-python/generated/simtk.openmm.openmm.CustomNonbondedForce.html#simtk.openmm.openmm.CustomNonbondedForce.addInteractionGroup)

**Comment by Lnaden** [comment]
And @jchodera beat me to it.

**Comment by yudongqiu** [comment]
Thanks very much for the idea of using the InteractionGroup! I saw it before, but I wasn't quite sure if the InteractionGroup will 1) utilize the same cutoff method and distance, 2) exclude anything else that are not in the group, 3) work together with the exclusions in a "exclusive" way. In my test if the forcefield was initialized by app.ForceField('ff.xml'), (ff.xml contains the <CustomNonbondedForce> block), calling `CustomNonbondedForce.getInteractionGroupParameters(0)` returns the error of `index out of range`, indicating there was no InteractionGroup by default.

May I confirm how the InteractionGroup works? Based on my current understanding:
1) If there is no InteractionGroup specified, the CustomNonbondedForce will act in the same way as if there is InteractionGroup(All, All). 
2) If there is at least one InteractionGroup specified, then all other interactions will be excluded. i.e. If All=[0,1,2,3,4], if we call addInteractionGroup([0,1],[2,3]), then only the interactions 0-1, 0-2, 1-2, 1-3 will be included.
3) Multiple InteractionGroups such as ([0,1],[2,3]) and ([1,3], [2,4]) will work together but not double counting the 1-3 interaction here.
4) If we call addExclusion(1,2) and addInteractionGroup([0,1],[2,3]), then 1-2 will still be excluded, and the only interactions left will be 0-1, 0-2, 1-3

If all above is true, then it is very powerful and will be very helpful for us. Thanks a lot!

**Comment by Lnaden** [comment]
> If there is no InteractionGroup specified, the CustomNonbondedForce will act in the same way as if there is InteractionGroup(All, All).

Yes. You can also specify an All, All if you really want, but that would be redundant.

> If there is at least one InteractionGroup specified, then all other interactions will be excluded. i.e. If All=[0,1,2,3,4], if we call addInteractionGroup([0,1],[2,3]), then only the interactions 0-1, 0-2, 1-2, 1-3 will be included.

No. Only what is in set A will interact with set B, so that case the interactions are 0-2, 0-3, 1-2, 1-3.

> Multiple InteractionGroups such as ([0,1],[2,3]) and ([1,3], [2,4]) will work together but not double counting the 1-2 interaction here.

I don't think it doubles up. Someone else can confirm that for me. It at the very least Shouldn't double up.

> If we call addExclusion(1,2) and addInteractionGroup([0,1],[2,3]), then 1-2 will still be excluded, and the only interactions left will be 0-1, 0-2, 1-3. It should be noted that the same atom can appear in both sets, making it interact with every atom in both sets and itself. 

Exclusions superseded interaction groups, Excluded pairs atoms will still be ignored, even if the interaction groups say they can interact.

**Comment by yudongqiu** [comment]
Oh sorry for the type-o in my 2nd guess, and thanks a lot for the detailed explanation!

**Comment by peastman** [comment]
> Multiple InteractionGroups such as ([0,1],[2,3]) and ([1,3], [2,4]) will work together but not double counting the 1-2 interaction here.

Yes, it's possible to get double counting if you're not careful.  See the documentation at http://docs.openmm.org/7.0.0/api-c++/generated/OpenMM.CustomNonbondedForce.html#_CPPv2N6OpenMM20CustomNonbondedForceE.  In particular it specifies:

> If a particle pair appears in two different interaction groups, its interaction will be computed twice. This is sometimes useful, but be aware of it so you do not accidentally create unwanted duplicate interactions.

**Comment by yudongqiu** [comment]
Thanks very much for all the help. It is working now and I am closing this issue.
