### ISSUE TITLE
Context.setVelocitiesToTemperature() produces  large or`nan` velocities

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1699]
I've been testing the `7.1.0` `beta` conda package (and `7.2.0` `dev` build) with `miniconda` python, and have run into a case where simply calling `context.setVelocitiesToTemperature(300 * unit.kelvin)` produces velocities of extremely large magnitude or `nan`. I've checked to make sure the masses were reasonable. A test case is attached.

I worry that this may be due to the `clang`-compiled packages, so I'll switch the `dev` builds back to `gcc` temporarily (and leave the `beta` untouched) to be able to compare.

Here is some truncated example output showing what the large velocities look like:
```
Reference
velocities before setVelocitiesToTemperature:
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 ...
[ 0.  0.  0.]] nm/ps
velocities after setVelocitiesToTemperature:
[[  6.29332748e+45   2.95952189e+46   6.99333855e+44]
 [  8.88686047e+44  -3.26026826e+45   4.30704692e+45]
...
 [  1.87835349e+00  -3.08385810e-01  -9.40770089e-01]] nm/ps
CPU
velocities before setVelocitiesToTemperature:
[[ 0.  0.  0.]
 [ 0.  0.  0.]
...
 [ 0.  0.  0.]] nm/ps
velocities after setVelocitiesToTemperature:
[[  5.87550066e+45   2.76303321e+46   6.52903656e+44]
 [  8.25422226e+44  -3.04926672e+45   4.36184621e+45]
...
 [  7.21309559e-01  -6.82054253e-01   1.04775292e+00]] nm/ps
CUDA
velocities before setVelocitiesToTemperature:
[[ 0.  0.  0.]
 [ 0.  0.  0.]
...
 [ 0.  0.  0.]] nm/ps
velocities after setVelocitiesToTemperature:
[[        inf         inf         inf]
 [        nan         nan         nan]
...
 [-0.42207414 -1.61906338  0.88288629]] nm/ps
OpenCL
velocities before setVelocitiesToTemperature:
[[ 0.  0.  0.]
 [ 0.  0.  0.]
...
 [ 0.  0.  0.]] nm/ps
velocities after setVelocitiesToTemperature:
[[        nan         nan         nan]
 [        nan         nan         nan]
...
 [-1.45576859 -0.17318904 -3.09035373]] nm/ps
```
[velocities-bug.zip](https://github.com/pandegroup/openmm/files/672492/velocities-bug.zip)

**Comment by jchodera** [comment]
Quick update: Switching to the 7.2.0 `dev` package built with `gcc` doesn't seem to change the behavior on this test case.

**Comment by peastman** [comment]
What sort of constraints do you have?  This sounds like it might be an ill-conditioned constraint matrix.  Also, I assume you've set the positions to reasonable values?

**Comment by jchodera** [comment]
Oh! Does `setVelocitiesToTemperature()` automatically apply constraints?

**Comment by jchodera** [comment]
Aha! [It does](https://github.com/pandegroup/openmm/blob/f7935fef719ed0cd8292afef676c39d881b6a960/openmmapi/src/Context.cpp#L207). 

I'll check whether the constraints and positions are all reasonable.

**Comment by jchodera** [comment]
I think the constraints/positions issue is probably the reason for this, so I can close this issue and reopen if necessary.

Should we throw an `Exception` if the constraint matrix is too ill-conditioned to produce meaningful results? This might help identify this issue much earlier than waiting for the system to explode.

**Comment by peastman** [comment]
If we're able to detect it, that would be useful.  It should also throw an exception if you haven't yet called `setPositions()`, which I don't think it currently checks for.

**Comment by jchodera** [comment]
In this particular case, the velocities become enormous (e.g. 1e+46). I imagine it would be simple and relatively inexpensive to add a check to ensure the velocity squared-magnitude does not *increase*.

Checking the condition number of the constraint matrix would be ideal for catching the underlying pathology, but my understanding is that this involves ratios of eigenvalues or singular values. I'm not sure whether there may be much simpler and less expensive ways of estimating condition numbers that could easily be added to check on the fly.

**Comment by peastman** [comment]
I took a look at your file, and I see why the matrix is singular: you have several constraints that are listed two or even three times.  How did you create this system?

Anyway, that's an easy problem to detect, much easier than the general problem of estimating the condition number.  I'll add a check for duplicate constraints.

**Comment by jchodera** [comment]
> I took a look at your file, and I see why the matrix is singular: you have several constraints that are listed two or even three times. 

Good catch!

> How did you create this system?

I believe this system was created by `simtk.openmm.app.ForceField` with the [`gaffTemplateGenerator`](https://github.com/choderalab/openmoltools/blob/master/openmoltools/forcefield_generators.py#L469-L512) registered. If we can throw an exception when `system.addConstraint()` is called to add a duplicate constraint (as suggested [here](https://github.com/pandegroup/openmm/pull/1711#issuecomment-270926107)), it will be super easy to track down the cause.
