### ISSUE TITLE
setBondParameters example

### ISSUE THREAD

**Issue by axelcournac** [pandegroup/openmm#1701]
Hi all,
What is the index to put in the function setBondParameters?
I added a bond with the function addBond and I want to switch off it during simulation something like this:
addBond(particle1=1485,particle2=1515, length=0.05, k=100)
then later:
setBondParameters(index=0,particle1=1485,particle2=1515,length=0.05,k=0.0)
If someone has an example of code using the functions setBondParameters and updateParametersInContext() to change a Bond parameter during a simulation in openMM, would be great.
Thanks,
Axel

**Comment by jchodera** [comment]
`addBond` will return the index of the bond parameter entry. You want to use that index.

**Comment by axelcournac** [comment]
I missed it! It works, thanks.
