### ISSUE TITLE
@deprecated warnings not rendering in API docs

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1706]
A number of methods are tagged with `@deprecated` warnings (such as [`CustomGBForce.addFunction()`](https://github.com/pandegroup/openmm/blob/master/openmmapi/include/openmm/CustomGBForce.h#L521-L526)). These warnings appear to be completely invisible in the sphinx API docs:

http://docs.openmm.org/7.0.0/api-python/generated/simtk.openmm.openmm.CustomGBForce.html#simtk.openmm.openmm.CustomGBForce.addFunction

Is there some way we can ensure these render in sphinx?

**Comment by peastman** [comment]
More specifically, they don't appear in the Python API docs.  They do appear in the C++ API docs.
