### ISSUE TITLE
Hard to trap NaN positions with CustomNonbondedForce?

### ISSUE THREAD

**Issue by Lnaden** [pandegroup/openmm#1723]
I have found a condition on which NaN positions are randomly generated in YANK which uses MC Barostat, Langevin Integrator, and several `Custom*Force`. I think these are related to the NaN's we were seeing on #1651. However, I have finally been able to actually trap the conditions to reliably generate the NaN on certain hardware. One of the main factors of the randomness is the Integrator random seed, which I have trapped in this example.

The tarball has a python file in it which can recreate the context that generates the NaN on GTX 680s and GTX TITANs with the OpenCL platform. The `txt` file has the hardware and software info relevant to generating the error.

I'm not sure if it helps, but on the 680 the minimal force indicies I need to generate the error are `[2,3,4]` which correspond to the `PeriodicTorisonForce`, `NonbondedForce`, and the primary `CustomNonbondedForce`. That may not be helpful since having only a subset of forces could cause other instabilities, but any other combination of forces I have tried does not generate the NaN positions (unless it fails immediately due to Barostat + non-periodic box).

I know this isn't much to go on so let me know if there is any other info I can provide to help debug this.

[nanrebuild.tar.gz](https://github.com/pandegroup/openmm/files/717754/nanrebuild.tar.gz)

cc @jchodera

**Comment by peastman** [comment]
Do you have a PDB file for this system?  I can't look at it in a visualizer with that.

**Comment by Lnaden** [comment]
Here is the PDB of the initial coordinates. I can work to generate a trajectory PDB if you need it as well.

[phenol_tip3p.tar.gz](https://github.com/pandegroup/openmm/files/720289/phenol_tip3p.tar.gz)

**Comment by Lnaden** [comment]
Wooooo!

I'll restart all our jobs to make sure we don't have anything else we missed!

Thank you!
