### ISSUE TITLE
How to speed up steered MD?

### ISSUE THREAD

**Issue by Yuan-Yu** [pandegroup/openmm#1725]
pullforce = CustomExternalForce('fc_ppos*(dx^2+dy^2+dz^2); \
                                      dx=abs(x-x0); \
                                      dy=abs(y-y0); \
                                      dz=abs(z-z0);')
    pullforce.addPerParticleParameter('fc_ppos')
    pullforce.addPerParticleParameter('x0')
    pullforce.addPerParticleParameter('y0')
    pullforce.addPerParticleParameter('z0')
    pullforceCoff = pullforceCoff.value_in_unit(kilojoule/(mole * nanometer * nanometer))
    pullforce.addParticle(pullIndex, [pullforceCoff, pullto[0], pullto[1], pullto[2] ])
    system = simulation.context.getSystem()
    system.addForce(pullforce)
    simulation.context.reinitialize()
    simulation.context.setState(currentState)
    currentContext = simulation.context
    pulltoy = pullto[1] #pull along y-axis
    for i in xrange(20000):
        pulltoy += 0.0002 #move restraint position
        pullforce.setParticleParameters(0,pullIndex,[ pullforceCoff,pullto[0],pulltoy,pullto[2] ])
        pullforce.updateParametersInContext(currentContext)
        simulation.step(1)

This is how I did the steered md.
But this implementation is very slow.
Is there any part of this implementation that can be modified?

**Comment by peastman** [comment]
How about

```Python
for i in xrange(200):
    pulltoy += 0.02 #move restraint position
    pullforce.setParticleParameters(0,pullIndex,[ pullforceCoff,pullto[0],pulltoy,pullto[2] ])
    pullforce.updateParametersInContext(currentContext)
    simulation.step(100)
```

`updateParametersInContext()` involves flushing the GPU's work queue, doing some work on the CPU, and transferring new data to the GPU.  All of that takes a lot longer than a single MD step, so if possible you don't want to call it after every time step.

**Comment by Yuan-Yu** [comment]
Thank you for your quick reply!!
Is it possible that using timestep in the expression of energy function? 
Something like  

    pullforce = Custom*Force('fc_ppos*(dx^2+dy^2+dz^2); \
                                      dx=abs(x-x0); \
                                      dy=abs(y-y0)+ t*0.02 ; \
                                      dz=abs(z-z0);')
where t is timestep.

**Comment by Lnaden** [comment]
The `Custom*Forces` do not have access to the timestep variable as that falls under the `Integrator`'s namespace. However, you could add a `GlobalParameter` which is exposed to both the `Integrator` and the `Context` that you could update in your loop. So something like:

```python
pullforce = Custom*Force('fc_ppos*(dx^2+dy^2+dz^2); \
                                  dx=abs(x-x0); \
                                  dy=abs(y-y0)+ displaceVar*0.02 ; \
                                  dz=abs(z-z0);')
pullforce.addGobalParameter('displaceVar', 0)
...
for i in range(200):
    ...
   simulation.step(100)
   simulation.context.setParameter('displaceVar', 0.02*(i+1))
```

which does not require `Context` re-initilization

**Comment by peastman** [comment]
Also, setting a context parameter is much cheaper that `updateParametersInContext()`.  You could even call it every time step without much loss in performance.

```
dy=abs(y-y0)+ displaceVar*0.02 ; \
```

That should be

```
dy=abs(y-y0)+ displaceVar; \
```

You already multiplied by 0.02 when you set the parameter.

**Comment by Lnaden** [comment]
Oh, yes. I'll fix the typo in case you want to use it as reference.

**Comment by Yuan-Yu** [comment]
It works well. The speed is close to normal simulation. :)
Thank you!!

**Comment by peastman** [comment]
Closing this since I think everything has been resolved.
