### ISSUE TITLE
centre-of-mass restraint

### ISSUE THREAD

**Issue by mj-harvey** [pandegroup/openmm#1727]
Hi,

I'd like to apply a restraint force to an atom group, restraining its centre of mass relative to an absolute coordinate. CustomCentroidBondForce looks like it would be able to do this, except that it requires two atom groups. Is there a way to shoe-horn my use-case into it or do I need to extend CustomExternalForce into CustomCentroidExternalForce? 

Ta,

Matt

**Comment by peastman** [comment]
One of the arguments to CustomCentroidBondForce's constructor is the number of groups it gets calculated based on.  In your case you want to base it on a single group, so pass 1 for that argument.  Then give it an energy expression that calculates the energy as a function of `x1`, `y1`, and `z1`, which are the coordinates of the single group's centroid.

**Comment by mj-harvey** [comment]
Perfect, thanks!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: peastmanSent: Thursday, 26 January 2017 01:21To: pandegroup/openmmReply To: pandegroup/openmmCc: M J Harvey; AuthorSubject: Re: [pandegroup/openmm] centre-of-mass restraint (#1727)One of the arguments to CustomCentroidBondForce's constructor is the number of groups it gets calculated based on.  In your case you want to base it on a single group, so pass 1 for that argument.  Then give it an energy expression that calculates the energy as a function of x1, y1, and z1, which are the coordinates of the single group's centroid.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pandegroup/openmm","title":"pandegroup/openmm","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/pandegroup/openmm"}},"updates":{"snippets":[{"icon":"PERSON","message":"@peastman in #1727: One of the arguments to CustomCentroidBondForce's constructor is the number of groups it gets calculated based on.  In your case you want to base it on a single group, so pass 1 for that argument.  Then give it an energy expression that calculates the energy as a function of `x1`, `y1`, and `z1`, which are the coordinates of the single group's centroid."}],"action":{"name":"View Issue","url":"https://github.com/pandegroup/openmm/issues/1727#issuecomment-275274803"}}}
