### ISSUE TITLE
MTS Integrator missing documentation

### ISSUE THREAD

**Issue by rnowling** [pandegroup/openmm#1729]
The MTS integrator is mentioned in [section 4](http://docs.openmm.org/development/userguide/application.html#integrators) of the user guide, but not in [section 21](http://docs.openmm.org/development/userguide/theory.html#integrators) or in the [C++ API docs](http://docs.openmm.org/development/api-c++/library.html#id3).

**Comment by kyleabeauchamp** [comment]
It's not part of the C++ API, but rather an "extra" integrator implemented in the python wrapper layer.

**Comment by rnowling** [comment]
It makes sense why I couldn't find it then!  Could that be clarified in Section 4 of the manual then?

As a side note, what is the status of the MTS integrator?  Does it offer reasonable performance?  Would there be any benefit in requesting a C++/CUDA/OpenCL implementation?

Thanks!

**Comment by kyleabeauchamp** [comment]
It uses CustomIntegrator, so it is expected to be reasonably close in performance to a hand-written implementation in each individual platform.

**Comment by rnowling** [comment]
Good to know.  Thank you!

**Comment by peastman** [comment]
Closing this, since the question has been answered.
