### ISSUE TITLE
Explain crazy version numbering scheme relationships in documentation

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1733]
We will need to add documentation to OpenMM to explain that OpenMM release 7.1.0 is actually called 7.1.0rc1 on conda, despite being the same thing, and that if people want to use openmm in their own conda recipes they need to specify the constraint `openmm >=7.1.0rc1` because `openmm >=7.1.0` will not work.

**Comment by peastman** [comment]
For future releases, this is the procedure we have agreed on (https://github.com/pandegroup/pdbfixer/issues/147#issuecomment-277838934):

We will build release candidates with the version number of the actual release, no "rc" in them.  We will post them for testing under the `rc` label.  If a problem is found and we need to do a new release candidate, we will do another build with the *exact same version number* as the previous one, delete the old build from conda, replace it with the new one, and warn testers that they need to manually uninstall the old build.  John will then object that we can't have a new build with the same version number as the previous one, and I will throw a rubber chicken at him.  When we're ready to release it, we will simply change the label from `rc` to `main`.

I'm not entirely happy with this, but it seems the best way to work around the flaws in conda.

**Comment by peastman** [comment]
I just went through the conda documentation to see if there was actually a proper way of handling this situation, and it turns out there is: the build number.  So the first release candidate of OpenMM 7.2 will have version number "7.2.0" and build number "0".  If we need a second release candidate, the version number will stay the same but the build number will increase to "1".  That way conda can tell them apart and knows which one is more recent.

I might still throw a rubber chicken at John, though, just because it would be fun.

**Comment by mpharrigan** [comment]
Incrementing the build number is fine if there's a problem with the build system that needs to be worked out. If there's a code change, i suggest we increment the x.x.0 component of the version number so we can also have disambiguous git tags

**Comment by peastman** [comment]
You're conflating two different types of changes: a new build of an unreleased version, working up to the final release; and a new release that fixes bugs.  There are good reasons for indicating those differently.  A change to the third digit of the version number indicates a new release, which itself might involve multiple release candidates.

**Comment by mpharrigan** [comment]
What are those good reasons? I don't think the distinction between a "release" and a build that is used for testing and may later be called a release is as big as you think. As long as you're distributing binaries to more than one other person, you need to be able to talk meaningfully about different instances of code and binaries. The "public" doesn't need to have a contiguous x.x.0 number

**Comment by peastman** [comment]
There's a very important difference: releases are expected to work correctly and we encourage people to use them for production work.  Intermediate builds should never be used for production work, and we don't claim they've been thoroughly tested.

For example, my computer is running OS X 10.11.6 build 15G1108.  Apple is constantly running new builds, and periodically seeds them to members of their developer program.  Eventually they declare one of those builds to be the official release, and post it so all users have it appear in Software Update.  The version numbers are always consecutive.  They never skip.  But the build numbers often skip (at least the ones they release externally), and you don't know in advance which build will get promoted to become the official release.

**Comment by mpharrigan** [comment]
Ok, let's use the conda "build number" as you suggested above (and how apple does it). I would love to have git tags for each {version, build number} as well *including* for builds that are never released. Am I right to expect some push back on this point? Maybe the tags could use the `rc` syntax so people know it's not a release.

example for a good rc:

source tag | git hash (example) | version | conda build number
-|-|-|-
7.2.0rc0 | aaaa1 | 7.2.0 | 0
7.2.0  | aaaa1 | 7.2.0 | 0

example for a bad rc:

source tag | git hash (example) | version | conda build number
-|-|-|-
7.3.0rc0 | bbbb1 | 7.3.0 | 0
7.3.0rc1 | bbbb2 | 7.3.0 | 1
7.3.0  | bbbb2 | 7.3.0 | 1

**Comment by peastman** [comment]
We already do.  See https://github.com/pandegroup/openmm/wiki/Release-Candidates.

**Comment by mpharrigan** [comment]
Ok, but there's no rc tag for 7.1

**Comment by peastman** [comment]
There is now! :)

(Thanks for pointing that out.)

**Comment by peastman** [comment]
This has been resolved.
