### ISSUE TITLE
Release 7.1 - python 3.6

### ISSUE THREAD

**Issue by mj-harvey** [pandegroup/openmm#1734]
Hi,

Just a note to make you aware that the latest Anaconda release has started shipping Python 3.6 by default,  so conda packages will have to be built for that version sooner or later (I don't see any in the omnia channel). Miniconda-latest is still at 3.5 for now. Hopefully that's a simple addition of a build rule somewhere.

Matt

**Comment by jchodera** [comment]
We're working on adding python 3.6 support for all `omnia` packages now:
https://github.com/omnia-md/conda-recipes/pull/698

**Comment by mj-harvey** [comment]
Thanks John,  good to know
Matt
