### ISSUE TITLE
NVT simulation - distorted box

### ISSUE THREAD

**Issue by susietomasio** [pandegroup/openmm#1735]
Hello,

I've run an NVT  simulation with the following script but obtained a distorted box.
Can anyone help please?
I've attached a snapshot of the last frame of the simulation.
Thank you in advance.
Susana

![lastframe](https://cloud.githubusercontent.com/assets/14070632/22786705/9d6738e2-eed1-11e6-9008-1cdc2c2f67ce.png)

from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from sys import stdout

print('Loading... \n')
prmtop = AmberPrmtopFile('1n2v_box_tleap.top')
inpcrd = AmberInpcrdFile('1n2v_box_tleap.crd')
system = prmtop.createSystem(constraints=HBonds,nonbondedMethod=PME )
modeller = Modeller(prmtop.topology, inpcrd.positions)
integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
simulation = Simulation(prmtop.topology, system, integrator)

simulation.context.setPositions(inpcrd.positions)
if inpcrd.boxVectors is not None:
    simulation.context.setPeriodicBoxVectors(*inpcrd.boxVectors)
print('Minimising...')
simulation.minimizeEnergy(maxIterations=100)

#simulation.context.setVelocities(initialVelocities)
print('Equilibrating...')
simulation.step(100)

simulation.reporters.append(PDBReporter('output.pdb', 1000))
simulation.reporters.append(StateDataReporter(stdout, 1000, step=True, potentialEnergy=True, temperature=True))
print('Running Production...')
simulation.step(100000000)
print('Done!')

**Comment by peastman** [comment]
Could you post your input files?  It's hard to guess what's happening without them.

**Comment by susietomasio** [comment]
Thank you! Here are the input files. I changed the file extension to .txt to be able to upload the files.

[1n2v_box_tLeap.top.txt](https://github.com/pandegroup/openmm/files/770624/1n2v_box_tLeap.top.txt)
[1n2v_box_tLeap.crd.txt](https://github.com/pandegroup/openmm/files/770626/1n2v_box_tLeap.crd.txt)
[simulateAmber.py.txt](https://github.com/pandegroup/openmm/files/770629/simulateAmber.py.txt)

Thank you in advance.
Susana

**Comment by peastman** [comment]
Your initial particle positions don't match the box size:

```Python
print(prmtop.topology.getPeriodicBoxVectors())
print(max(inpcrd.positions)-min(inpcrd.positions))
```

produces this output:

```
((7.9110798, 0.0, 0.0), (0.0, 7.511427000000001, 0.0), (0.0, 0.0, 9.253880700000002)) nm
(76.093953, 41.118482, 83.140528) A
```

(Note the first is in nm and the second in Angstroms).  So the box size is about 7.9 by 7.5 by 9.25 nm, but the initial particle positions only fill a smaller box of 7.6 by 4.1 by 8.3 nm.

**Comment by peastman** [comment]
The box dimensions in the inpcrd file are also the same as the ones in the prmtop file.  The last line of the file is

```
  79.1107980  75.1142700  92.5388070  90.0000000  90.0000000  90.0000000
```

So the atoms don't fill the box.

**Comment by susietomasio** [comment]
Thank you Pete.
I am creating the box and solvating the box with tleap. It looks like the density is too low. Those are the dimensions given by tleap. I'm not sure why the initial particle positions are so small.

**Comment by peastman** [comment]
I'm closing this, since I think everything related to OpenMM has been resolved.

**Comment by susietomasio** [comment]
Thank you Pete.
