### ISSUE TITLE
Tempreture in log file is wrong

### ISSUE THREAD

**Issue by wanghaiyunustc** [pandegroup/openmm#1738]
Hi,
I use MBpol in openMM to simulate water cluster,  however, after the NVT simulation, I find that the tempreture in log file is different with the tempreture in input file.
Attachment are my input file, log file and pdb file.
Thank you!
[1water75.zip](https://github.com/pandegroup/openmm/files/770588/1water75.zip)

**Comment by peastman** [comment]
You're doing an NVE simulation, not NVT.  If you want to do NVT, you should either use a LangevinIntegrator in place of the VerletIntegrator, or else add an AndersenThermostat to the system.

**Comment by wanghaiyunustc** [comment]
Thanke you very much. However,  "temperature_k = 50" and "collision_rate_1overps = 1.0" in the .ini file don't mean that  the Thermostat is added? If not, could you please tell me how to Thermostat and set temperature. 
Sorry to bother you again!

**Comment by peastman** [comment]
OpenMM doesn't use .ini files.  The type of simulation you run is specified by the Python script, which specifies a VerletIntegrator and doesn't add any other thermostat.  Take a look at http://docs.openmm.org/7.0.0/userguide/application.html#a-first-example for an example of a script that uses a LangevinIntegrator, and therefore simulates constant temperature.

**Comment by peastman** [comment]
Closing this, since I think everything has been resolved.

**Comment by wanghaiyunustc** [comment]
Sorry to reply so late. I will close it right away.

在2017-02-24 04:28:22，peastmannotifications@github.com写道：

Closing this, since I think everything has been resolved.
