### ISSUE TITLE
Travis badge is incorrect

### ISSUE THREAD

**Issue by peastman** [pandegroup/openmm#1750]
If you click on the travis badge in the readme, it takes you to the results from whatever build was run most recently, even if that was a PR that hasn't been merged.  It should show the current results for the code in the master branch.

**Comment by jchodera** [comment]
The current badge text in `README.md` reads:
```
[![Build Status](https://travis-ci.org/pandegroup/openmm.svg?branch=master)](https://travis-ci.org/pandegroup/openmm)
```
This should be
```
[![Build Status](https://travis-ci.org/pandegroup/openmm.svg?branch=master)](https://travis-ci.org/pandegroup/openmm?branch=master)
```
