### ISSUE TITLE
Correct handling of intermolecular forces in external plugins

### ISSUE THREAD

**Issue by jlmaccal** [pandegroup/openmm#1751]
We've run into some strange behaviour using MELD in a system where 4 identical molecules (Ca2+ in this case) are restrained using MELD. The system behaves very strangely and it wasn't immediately obvious what was going on. After simplifying the system, it turns out that the Ca2+ ions are frequently trying to switch places with each other. Eventually, I figured out that this happens because OpenMM is reordering the "identical" Ca2+ ions when it builds neighbourlists.

@peastman, how do I tell OpenMM to not reorder molecules involved in a MELD force? This involves `CudaForceInfo`, but I'm not sure what the semantics of the methods on these classes are, so I'm not quite sure what to implement.

In my case, I have a list of particles that are involved in some type of MELD interaction. I would like to prevent any molecule containing one of these particles from being reordered. What should the output of the following methods be?
- `getNumParticleGroups`
- `getParticlesInGroup`
- `areGroupsIdentical`
- `areParticlesIdentical`

What is a particle group in this context? Should I just be returning 1 particle group containing all of the particles involved in the MELD force? Therefore, `areGroupsIdentical` would always return true, because there's only one group compared with itself? If `areParticlesIdentical` returned false whenever either of the two atoms is involved in the MELD force, would that give correct behaviour?

**Comment by peastman** [comment]
> If areParticlesIdentical returned false whenever either of the two atoms is involved in the MELD force, would that give correct behaviour?

I think that's exactly what you want.  If you tell it a particle isn't identical to any other particle, it will never get reordered.

**Comment by jlmaccal** [comment]
> I think that's exactly what you want. If you tell it a particle isn't identical to any other particle, it will never get reordered.

Great! Do I need to do anything with particle groups? Or can `getNumParticleGroups` just return zero?

**Comment by peastman** [comment]
Returning zero should be fine.  Particle groups are for situations that depend on multiple particles.  For example, in a bonded force the important question is not whether two particles are identical, but whether two bonds are identical.  So it would report each bond as being a particle group.

**Comment by jlmaccal** [comment]
That did the trick, thanks!
