### ISSUE TITLE
Support Python 3.6

### ISSUE THREAD

**Issue by peastman** [pandegroup/openmm#1758]
See https://github.com/omnia-md/conda-recipes/issues/702.  Are we going to release OpenMM 7.1 builds for Python 3.6?  If so we need to build them properly using our standard build process and fully test them.

**Comment by jchodera** [comment]
We at least need conda builds for python 3.6 if we are going to add omnia support for python 3.6. It looks like `linux` and `osx` conda packages for `7.0rc1` have been built and pushed to `dev` already, though @lnaden can comment on whether those are ready for testing.

I have no opinions on the ZIP installers.

**Comment by Lnaden** [comment]
They should be ready for testing. Reviewing the compiled docs would be good since I updated all the doc compile versions

**Comment by peastman** [comment]
Were those builds created by the same process we use for standard builds?

**Comment by Lnaden** [comment]
They were built with the `conda-build-all` in `omnia-md/conda-recipes`, so if the procedure is different than the `meta.yaml` file on the CentOS5 Holy Build Box, then no.

**Comment by jchodera** [comment]
We need to test this package so we can move it to the main channel ASAP. This his holding up the addition of python 3.6 support to omnia.

**Comment by peastman** [comment]
You need to rebuild them using the correct process for release packages.

**Comment by jchodera** [comment]
We can discuss on the call, but these packages were built using the same procedure we used to build the existing released OpenMM 7.1.0rc1 packages except that using Python 3.6. I don't understand what you want us to do differently.

**Comment by peastman** [comment]
That's not what @Lnaden said above.

**Comment by jchodera** [comment]
He said the same thing I did, though admittedly in a more confusing manner.

**Comment by peastman** [comment]
Let's be very clear then to avoid confusion: this build was or wasn't built using exactly the same procedure, scripts, and build environment that we use for other releases, changing only the version of python specified when running `conda build`?

**Comment by jchodera** [comment]
@peastman : I'm having trouble finding the specific testing instructions on the wiki. Can you send a pointer?

**Comment by peastman** [comment]
Step 3 at https://github.com/pandegroup/openmm/wiki/Release-Candidates.

**Comment by Lnaden** [comment]
Okay, just to make sure I did this right:

1. Installed the 7.1.0rc1 build from the omnia/label/dev channel
2. Make sure we can import openmm
3. Check the `Platform.getOpenMMVersion()` (7.1)
4. Run `testInstallation` script, which is works.
5. Can't check the Git Hash since we apply a patch on the build.

That should be all I need to do before moving the build from `dev` to `main`, yes?

**Comment by jchodera** [comment]
> Can't check the Git Hash since we apply a patch on the build.

You should be able to do `print(simtk.openmm.version.version)`. That contains the git hash.

**Comment by jchodera** [comment]
> That should be all I need to do before moving the build from dev to main, yes?

Yes.

**Comment by Lnaden** [comment]
> You should be able to do...

The commit hash will change every time the patch is applied because the new hash is a function of the previous commits, and the *time* that the commits occur (SHA1 hashing). So checking the `mm.git_version` from a local test will be different than the one Travis builds because a patch is applied at build time, making it a moot point.

**Comment by peastman** [comment]
That sounds good to me.  Let's go ahead.

**Comment by Lnaden** [comment]
Okay, the Linux and OSX builds appear to be working. I have moved them from `dev` to `main` on the omnia channel, woo!

Now we just have to do the Windows build

**Comment by peastman** [comment]
I'm trying to do the Windows build, but running into problems.  Here's the command I'm executing to do the build:

```
c:\Miniconda3\Scripts\conda.exe build --python=3.6 conda-recipes\openmm
```

And here's the last bit of the log:

```
The following NEW packages will be INSTALLED:

    docutils:   0.13.1-py36_0
    jinja2:     2.9.5-py36_0
    markupsafe: 0.23-py36_2
    pybtex:     0.18-py36_0   local
    pygments:   2.2.0-py36_0
    pyyaml:     3.12-py36_0


c:\Miniconda3\conda-bld\openmm_1490387524172\test_tmp>call "c:\Miniconda3\Scripts\activate.bat" "c:\Miniconda3\conda-bld\openmm_1490387524172\_t_env"  1>nul 2>&1

(c:\Miniconda3\conda-bld\openmm_1490387524172\_t_env) c:\Miniconda3\conda-bld\openmm_1490387524172\test_tmp>if errorlevel 1 exit 1

(c:\Miniconda3\conda-bld\openmm_1490387524172\_t_env) c:\Miniconda3\conda-bld\openmm_1490387524172\test_tmp>"c:\Miniconda3\conda-bld\openmm_1490387524172\_t_env\python.exe" -s "c:\Miniconda3\conda-bld\openmm_1490387524172\test_tmp\run_test.py"
'"c:\Miniconda3\conda-bld\openmm_1490387524172\_t_env\python.exe"' is not recognized as an internal or external command,
operable program or batch file.

(c:\Miniconda3\conda-bld\openmm_1490387524172\_t_env) c:\Miniconda3\conda-bld\openmm_1490387524172\test_tmp>if errorlevel 1 exit 1
TESTS FAILED: pybtex-0.18-py36_0
```

Looking in the directory, I can confirm there is no Python executable in the `_t_env` folder.  There *is* one in the `_b_env` folder.  I don't really understand what's going on.  Anyone have an idea?

**Comment by Lnaden** [comment]
Have you updated the `conda` and `conda-build` versions? I know they can do some weird stuff when they are out of sync, but I have not worked with the m on windows. My guess is one of them is out of date enough that they don't have Python 3.6 compatible stuff since its relatively new, but this is my guess.

**Comment by peastman** [comment]
I just built the VM and installed everything today.  `conda list` gives the following versions:

```
conda                     4.3.14                   py36_1
conda-build               2.1.7                    py36_0
```

**Comment by Lnaden** [comment]
Hmm... Is there a reason its trying to use your local `pybtex` install? It may be that an old build is superseding pulling it from the `omnia` channel, causing some oddities?

**Comment by peastman** [comment]
Maybe?  The prepare script for the VM installs `sphinxcontrib.bibtex` using `pip`, and I think that's where `pybtex` gets pulled in.  So maybe that's causing the problem.  I just uninstalled it and I'm trying again.

Here's one other thing that might or might not be related.  The prepare script also uses `conda` to install various dependencies it will need:

```
& "C:\Miniconda3\Scripts\conda.exe" install -y -c omnia fftw3f jinja2 lxml sphinx sphinxcontrib-autodoc_doxygen sphinxcontrib-lunrsearch conda-build anaconda-client
```

But that line failed with this error:

```
==> default: UnsatisfiableError: The following specifications were found to be in conflict:
==> default:   - python 3.6*
==> default:   - sphinxcontrib-autodoc_doxygen
```

I worked around it by installing only `conda-build` by hand.  But perhaps this indicates some of our dependencies don't have Python 3.6 versions for Windows?

**Comment by Lnaden** [comment]
Yup, the `sphinxcontrib-autodoc_doxygen` isn't building on windows, I removed the `skip` for it. I'll keep an eye on it and let you know.

**Comment by jchodera** [comment]
Looks like the python 3.6 win package [posted](https://anaconda.org/omnia/sphinxcontrib-autodoc_doxygen/files).

**Comment by Lnaden** [comment]
I also just merged the `sphinxcontrib-lunrsearch` which should have the Py 3.6 version uploading soon as well

**Comment by peastman** [comment]
Thanks!  I'm now getting further.  It appears to build successfully, but fails when it gets to testing.  Here's the relevant bit of the log:

```
INFO conda_build.build:bundle_conda(864): Packaging openmm-7.1.0rc1-py36_0
compiling .pyc files...
number of files: 544
Fixing permissions
Fixing permissions
WARNING conda_build.source:git_info(261): git not installed in root environment.  Skipping recording of git info.
c:\Miniconda3\conda-bld\win-64\openmm-7.1.0rc1-py36_0.tar.bz2
updating index in: c:\Miniconda3\conda-bld
updating index in: c:\Miniconda3\conda-bld\noarch
updating index in: c:\Miniconda3\conda-bld\win-64
updating: openmm-7.1.0rc1-py36_0.tar.bz2
updating index in: c:\Miniconda3\conda-bld
TEST START: c:\Miniconda3\conda-bld\win-64\openmm-7.1.0rc1-py36_0.tar.bz2
Deleting work directory, c:\Miniconda3\conda-bld\openmm_1490634345232\work
updating index in: c:\Miniconda3\conda-bld\win-64
updating index in: c:\Miniconda3\conda-bld\noarch

The following NEW packages will be INSTALLED:

    fftw3f:         3.3.4-vc14_2    omnia [vc14]
    openmm:         7.1.0rc1-py36_0 local
    pip:            9.0.1-py36_1
    python:         3.6.1-0
    setuptools:     27.2.0-py36_1
    vs2015_runtime: 14.0.25123-0
    wheel:          0.29.0-py36_0


c:\Miniconda3\conda-bld\openmm_1490634345232\test_tmp>call "c:\Miniconda3\Scripts\activate.bat" "c:\Miniconda3\conda-bld\openmm_1490634345232\_t_env"  1>nul 2>&1

(c:\Miniconda3\conda-bld\openmm_1490634345232\_t_env) c:\Miniconda3\conda-bld\openmm_1490634345232\test_tmp>if errorlevel 1 exit 1

(c:\Miniconda3\conda-bld\openmm_1490634345232\_t_env) c:\Miniconda3\conda-bld\openmm_1490634345232\test_tmp>"c:\Miniconda3\conda-bld\openmm_1490634345232\_t_env\python.exe" -s "c:\Miniconda3\conda-bld\openmm_1490634345232\test_tmp\run_test.py"
===== testing package: openmm-7.1.0rc1-py36_0 =====
running run_test.py
Traceback (most recent call last):
  File "c:\Miniconda3\conda-bld\openmm_1490634345232\test_tmp\run_test.py", line 7, in <module>
    from simtk import openmm
ModuleNotFoundError: No module named 'simtk'

(c:\Miniconda3\conda-bld\openmm_1490634345232\_t_env) c:\Miniconda3\conda-bld\openmm_1490634345232\test_tmp>if errorlevel 1 exit 1
TESTS FAILED: openmm-7.1.0rc1-py36_0
```
'
Looking through the build directories, the file `c:\Miniconda3\conda-bld\win-64\openmm-7.1.0rc1-py36_0.tar.bz2` does not exist.  There are other files in that directory, but nothing for OpenMM.  But it did build the C++ libraries.  They're in the `_t_env\Lib` directory.

**Comment by jchodera** [comment]
That's super weird. It clearly says it created this file:
```
c:\Miniconda3\conda-bld\win-64\openmm-7.1.0rc1-py36_0.tar.bz2
updating index in: c:\Miniconda3\conda-bld
updating index in: c:\Miniconda3\conda-bld\noarch
updating index in: c:\Miniconda3\conda-bld\win-64
updating: openmm-7.1.0rc1-py36_0.tar.bz2
updating index in: c:\Miniconda3\conda-bld
```
Any chance you manually deleted any of your `conda` folders? Are you starting from a totally fresh Miniconda install? [This thread](https://github.com/conda/conda-build/issues/1432) suggests bad things can happen if these directories get messed up.

**Comment by peastman** [comment]
> Are you starting from a totally fresh Miniconda install?

Yes.  I created a new VM just for doing this build.

**Comment by jchodera** [comment]
If you need to try again, I'd suggest `conda clean -pltis --yes` first, but if this was the first time you built with a clean install, I'm not sure if that would help.

**Comment by Lnaden** [comment]
I also am not seeing anything out of the ordinary. I can't replicate on the windows machine we have here, but I am testing non-openmm packages. I would suggest the clean install, but it would be nice if conda actually just worked. :/

**Comment by Lnaden** [comment]
The only thing I can think of is the `jom` commands in the `build.bat` file are messing up. Maybe `jom` is not meant to work with python 3.6 right now?

**Comment by Lnaden** [comment]
Long shot: Do you still have the `build: skip: True # [win]` on in your build? I doubt it since it should just outright fail.

**Comment by peastman** [comment]
> If you need to try again, I'd suggest conda clean -pltis --yes first

Trying again with that.

> Do you still have the build: skip: True # [win] on in your build?

No.  With that it just doesn't build.

**Comment by Lnaden** [comment]
> No. With that it just doesn't build.

Okay, i knew that was going to be a dumb question, but I don't have any other ideas at the moment.

**Comment by peastman** [comment]
This time I watched that directory while it was building, and the file does get created there.  It just gets deleted after the test fails.

**Comment by peastman** [comment]
I just tried building for Python 3.5, and that is failing too with the same error.  Is there something else that's changed recently?  Or am I forgetting some essential step?  Here's the command I'm using to build:

```
c:\Miniconda3\Scripts\conda.exe build -c omnia --python=3.5 conda-recipes\openmm
```

**Comment by Lnaden** [comment]
That should be it. The only thing I can think of is `conda-build` broke something, as they are want to do. Maybe pin to an older version like `conda-build=2.1.5` and see what happens?

**Comment by jchodera** [comment]
Our omnia build framework uses [these steps](https://github.com/omnia-md/conda-recipes/blob/master/appveyor.yml#L58-L64) to prepare the environment. Instead of `-c omnia`, it explicitly adds the channel first:
```
c:\Miniconda3\Scripts\conda.exe --add channels omnia
```
I don't *think* this sould make a difference, but it might.

**Comment by peastman** [comment]
To be safe I deleted the miniconda installation and reinstalled it.  Then I told it to install conda-build 2.1.5, and tried building again.  It now fails slightly earlier:

```
INFO conda_build.build:bundle_conda(865): Packaging openmm-7.1.0rc1-py35_0
compiling .pyc files...
number of files: 544
Fixing permissions
Fixing permissions
Traceback (most recent call last):
  File "c:\Miniconda3\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "c:\Miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 322, in main
    execute(sys.argv[1:])
  File "c:\Miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 313, in execute
    noverify=args.no_verify)
  File "c:\Miniconda3\lib\site-packages\conda_build\api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "c:\Miniconda3\lib\site-packages\conda_build\build.py", line 1493, in build_tree
    config=config)
  File "c:\Miniconda3\lib\site-packages\conda_build\build.py", line 1143, in build
    built_package = bundlers[output_dict.get('type', 'conda')](output_dict, m, config, env)
  File "c:\Miniconda3\lib\site-packages\conda_build\build.py", line 890, in bundle_conda
    create_info_files(tmp_metadata, files, config=config, prefix=config.build_prefix)
  File "c:\Miniconda3\lib\site-packages\conda_build\build.py", line 510, in create_info_files
    source.git_info(config, fo)
  File "c:\Miniconda3\lib\site-packages\conda_build\source.py", line 266, in git_info
    p = Popen(cmd.split(), stdout=PIPE, stderr=PIPE, cwd=config.work_dir, env=env)
  File "c:\Miniconda3\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "c:\Miniconda3\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

I don't know what file it's talking about that it can't find.

I've always used `-c omnia` when doing builds in the past, and it worked then, so I doubt that's the problem.

**Comment by Lnaden** [comment]
Okay, so downgrading conda-build did not work, based on the error, that failed in simply trying to source the build environment. They recently did some monkey-patching of conda-build to work with changes in an upcoming conda, but there has not been a conda release that I can see which would throw that off.

See what happens when you rename the `run_test.py` script to something else and letting the test that's already in the `meta.yaml` file execute instead. I doubt that is it though since you said the files are just strait up missing from the build environment.

[This issue](https://github.com/conda/conda-build/issues/1835) may be relevant, but also probably not since we are not doing any compiler requirements on the `run` section,

> I don't think this should make a difference, but it might.

That would only be true if we were getting packages from the wrong channels due to channel priority, I don't see any of that

**Comment by Lnaden** [comment]
This problem appears to have the same symptom (at least on the surface) as what we are seeing on the [omnia-dev-recipes](https://github.com/omnia-md/conda-dev-recipes/pull/86) for the OSX versions. I wonder if there is a similar problem related to the VCXX versions where the python is compiled against a particular version and failing.

I have no evidence to suggest that would be the problem (no full logs like on travis), but its a thought at least.

**Comment by jchodera** [comment]
We're already supporting Python 3.6 now, so we can close this @peastman.
