### ISSUE TITLE
CHARMM reader produces incorrect improper energies

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1760]
[`CharmmPsfFile`](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/charmmpsffile.py) uses [this code](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/charmmpsffile.py#L910) to encode CHARMM improper torsions:
```python
        # Ick. OpenMM does not have an improper torsion class. Need to
        # construct one from CustomTorsionForce
        force = mm.CustomTorsionForce('k*(theta-theta0)^2')
```
Given that OpenMM computes [the torsion `theta` on the domain `[-pi,pi]`](http://docs.openmm.org/7.1.0/api-python/generated/simtk.openmm.openmm.CustomTorsionForce.html#simtk.openmm.openmm.CustomTorsionForce), guess what happens when `theta0` is not 0?

**Comment by jchodera** [comment]
@peastman : Since the correct idiom of replacing
```
energy_function = 'k*(theta-theta0)^2'
```
with
```
energy_function  = 'k*dtheta_torus^2;'
energy_function += 'dtheta_torus = dtheta - floor(dtheta/(2*pi)+0.5)*(2*pi);'
energy_function += 'dtheta = theta - theta0;'
energy_function += 'pi = %f;' % pi
```
is rather non-obvious, what would you think of adding a function to lepton that is a shortcut for this?

For example, `minimum_image(delta, min, max)` could return the minimum image of the separation `delta` in the interval `[min, max]`, or we could even have `minimum_torsion_image(delta)` assume this is `[-pi,+pi]`.

**Comment by swails** [comment]
Does #1761 not fix this issue?

**Comment by jchodera** [comment]
> Does #1761 not fix this issue?

It does, which is why the first line of https://github.com/pandegroup/openmm/pull/1761 says "Fixes #1760". :)

The remaining discussion point is whether this is the *best* fix.

**Comment by swails** [comment]
The fix seems straightforward, simple enough, and (based on what you just said) catches the corner cases.  It also doesn't impose a lot more computational cost on a term that contributes negligibly to the overall computational efficiency.

I struggle to see what "better" looks like or why it's even worth trying to figure that out.

**Comment by jchodera** [comment]
Well, for starters, there seems to be a simpler fix:
```
energy_function  = 'k*min(dtheta^2, (2*pi-dtheta)^2);'
energy_function += 'dtheta = abs(theta - theta0);'
energy_function += 'pi = %f;' % pi
```
Next, since this bug has been in there for a while and was missed by all of us, who are supposedly *experts*, others are bound to make the same mistake themselves, and discussing whether this is a sign of a deeper issue that could be addressed seems worthwhile. This is the second time I've caught the same issue---the first was when I made the same mistake in my own implementation of Boresch restraints for protein-ligand binding. It could be that we add some functionality to make it easier to not mess this up, or it could be that we improve the documentation to better warn people how not to mess up.

Finally, there's the question of how to appropriately test it (in the PR).
