### ISSUE TITLE
Could forces in different force groups use different cutoff distances?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1763]
How hard would it be to support the ability of forces in different force groups to use different cutoff distances? This can be useful for MTS schemes in which the inner timestep uses a different cutoff than the middle or outer timesteps.

**Comment by peastman** [comment]
They already can.

**Comment by jchodera** [comment]
Whoops. I see what I was doing wrong now. Thanks!

**Comment by swails** [comment]
![easy](https://media.giphy.com/media/Rl9Yqavfj2Ula/giphy.gif)
