### ISSUE TITLE
Amoeba computeoneinteraction

### ISSUE THREAD

**Issue by amrhamedp** [pandegroup/openmm#1768]
I tried to capture pairwise atomic  interaction energy from both openmm and tinker for a system. The values of different types of energies were the same except the electrostatic energy comprised of multipoles and polarization energy. Openmm tends to use d-scale in calculating the energy, for example eUInpCoef = rInvVec[2]*dScale*thole_c  which lead to appearance of some pairwise energies between covalently bonded atoms that belongs to different polarization groups in openmm (whenever d-scale =1 ). However , in tinker when you print those energies out, we get the value of zero. e,g 1C----2C electrostatic energy is equal zero in tinker but has some value in openmm. What confuses me even more is that the total pairwise interaction energy for given system is the same in both although individual pairwise interaction energy is slightly different. What is the reason for such difference? 

My main goal is to analyze per- atomic energy in openmm amoeba the same way as in tinker analyze by summing up the pairwise interaction energies. However, because pairwise energies are slightly different, per-atomic energies are different too (p.s the total electrostatic energies of the whole system (not atoms) based on sum of pairwise energies is the same however)

Example for part of system
http://imgur.com/QFqVmcI

**Comment by peastman** [comment]
Where are you getting those values from?  OpenMM doesn't provide any API for querying the d and p interactions separately, so you must be modifying the code to print them out somewhere?  But if the total energy is coming out correct, then clearly it's calculating them correctly, so the problem must be in how you're extracting the individual pieces.

**Comment by amrhamedp** [comment]
Thanks for your response. We printed the pair-wise energies directly in the cuda kernel including computeOneInteraction:
 
    // Evaluate the energies, forces and torques due to permanent+induced moments
    // interacting with just the permanent moments.
    energy += forceFactor*0.5f*(
        atom1.q*Vij[0] + rotatedDipole1.x*Vij[1] + rotatedDipole1.y*Vij[2] + rotatedDipole1.z*Vij[3] + rotatedQuadrupole1[0]*Vij[4] + rotatedQuadrupole1[1]*Vij[5] + rotatedQuadrupole1[2]*Vij[6] + rotatedQuadrupole1[3]*Vij[7] + rotatedQuadrupole1[4]*Vij[8] +
        atom2.q*Vji[0] + rotatedDipole2.x*Vji[1] + rotatedDipole2.y*Vji[2] + rotatedDipole2.z*Vji[3] + rotatedQuadrupole2[0]*Vji[4] + rotatedQuadrupole2[1]*Vji[5] + rotatedQuadrupole2[2]*Vji[6] + rotatedQuadrupole2[3]*Vji[7] + rotatedQuadrupole2[4]*Vji[8]);
    real fIZ = atom1.q*VijR[0] + rotatedDipole1.x*VijR[1] + rotatedDipole1.y*VijR[2] + rotatedDipole1.z*VijR[3] + rotatedQuadrupole1[0]*VijR[4] + rotatedQuadrupole1[1]*VijR[5] + rotatedQuadrupole1[2]*VijR[6] + rotatedQuadrupole1[3]*VijR[7] + rotatedQuadrupole1[4]*VijR[8];
    real fJZ = atom2.q*VjiR[0] + rotatedDipole2.x*VjiR[1] + rotatedDipole2.y*VjiR[2] + rotatedDipole2.z*VjiR[3] + rotatedQuadrupole2[0]*VjiR[4] + rotatedQuadrupole2[1]*VjiR[5] + rotatedQuadrupole2[2]*VjiR[6] + rotatedQuadrupole2[3]*VjiR[7] + rotatedQuadrupole2[4]*VjiR[8];
    real EIX = rotatedDipole1.z*Vij[1] - rotatedDipole1.x*Vij[3] + sqrtThree*rotatedQuadrupole1[2]*Vij[4] + rotatedQuadrupole1[4]*Vij[5] - (sqrtThree*rotatedQuadrupole1[0]+rotatedQuadrupole1[3])*Vij[6] + rotatedQuadrupole1[2]*Vij[7] - rotatedQuadrupole1[1]*Vij[8];
    real EIY = -rotatedDipole1.y*Vij[1] + rotatedDipole1.x*Vij[2] - sqrtThree*rotatedQuadrupole1[1]*Vij[4] + (sqrtThree*rotatedQuadrupole1[0]-rotatedQuadrupole1[3])*Vij[5] - rotatedQuadrupole1[4]*Vij[6] + rotatedQuadrupole1[1]*Vij[7] + rotatedQuadrupole1[2]*Vij[8];
    real EIZ = -rotatedDipole1.z*Vij[2] + rotatedDipole1.y*Vij[3] - rotatedQuadrupole1[2]*Vij[5] + rotatedQuadrupole1[1]*Vij[6] - 2*rotatedQuadrupole1[4]*Vij[7] + 2*rotatedQuadrupole1[3]*Vij[8];
    real EJX = rotatedDipole2.z*Vji[1] - rotatedDipole2.x*Vji[3] + sqrtThree*rotatedQuadrupole2[2]*Vji[4] + rotatedQuadrupole2[4]*Vji[5] - (sqrtThree*rotatedQuadrupole2[0]+rotatedQuadrupole2[3])*Vji[6] + rotatedQuadrupole2[2]*Vji[7] - rotatedQuadrupole2[1]*Vji[8];
    real EJY = -rotatedDipole2.y*Vji[1] + rotatedDipole2.x*Vji[2] - sqrtThree*rotatedQuadrupole2[1]*Vji[4] + (sqrtThree*rotatedQuadrupole2[0]-rotatedQuadrupole2[3])*Vji[5] - rotatedQuadrupole2[4]*Vji[6] + rotatedQuadrupole2[1]*Vji[7] + rotatedQuadrupole2[2]*Vji[8];
    real EJZ = -rotatedDipole2.z*Vji[2] + rotatedDipole2.y*Vji[3] - rotatedQuadrupole2[2]*Vji[5] + rotatedQuadrupole2[1]*Vji[6] - 2*rotatedQuadrupole2[4]*Vji[7] + 2*rotatedQuadrupole2[3]*Vji[8];
 
    // YY print
    printf("atom1.pos.x, atom2.pos.x, energy: %12.3f   %12.3f   %12.6f  \n", atom1.pos.x*10, atom2.pos.x*10, energy*0.239006*1.38935456e+02f);
 
We also summed up the symmetric pairs, e.g. E(1-6) + E(6-1) to compare with tinker which only computes E(1-6).

**Comment by peastman** [comment]
That's your problem.  Notice it starts `energy +=` rather than `energy =`?  It's a running total of the energy of all interactions that have been computed by that thread.

**Comment by amrhamedp** [comment]
I am sorry but I forgot to mention that for this particular analysis we set the energy to zero before entering the computeOneInteraction routine. Thus, it is only computing the pair interaction and not the total of the energy.

**Comment by peastman** [comment]
What is the value of `pScale` when computing those interactions?  Is it zero?

**Comment by peastman** [comment]
Closing this since there's been no reply since March.
