### ISSUE TITLE
Add tabulated function capabilities to CustomIntegrator?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1772]
How hard would it be to add tabulated function capabilities to `CustomIntegrator` to match those found in the `Custom*Force` classes? 

This feature turns out to be surprisingly useful in build nonequilibrium integrators that use optimized nonequilibrium switching protocols, which could be very useful for the constant-pH code (and other tools) we are working on.

**Comment by peastman** [comment]
That should be possible.  A bit of work, but not too bad.

**Comment by jchodera** [comment]
Tagging @pgrinaway and @maxentile, who are particularly interested in this.

**Comment by jchodera** [comment]
Thanks!

Tagging @pgrinaway @maxentile @bas-rustenburg @gregoryross.
