### ISSUE TITLE
How do you update a global parameter in a custom force?

### ISSUE THREAD

**Issue by mpharrigan** [pandegroup/openmm#1775]
Specifically, custom torsion force. The documentation has this method

> setGlobalParameterDefaultValue(self, index, ...) 	Set the default value of a global parameter.

it's not clear if this is what I want, because I want to set the actual value.

Threre's another method

>  updateParametersInContext(self, context)  Update the per-torsion parameters in a Context to match those stored in this Force object.

Does this apply to global parameters in addition to per-torsion parameters?

**Comment by peastman** [comment]
Global parameters are stored in the Context.  You set them by calling `context.setParameter(name, value)`.

**Comment by mpharrigan** [comment]
Should we document this somewhere? Maybe in the user manual in the custom force section

**Comment by peastman** [comment]
You mean like in the API documentation at http://docs.openmm.org/7.1.0/api-c++/generated/OpenMM.CustomTorsionForce.html#_CPPv2N6OpenMM18CustomTorsionForceE?

> The values of per-torsion parameters are specified as part of the system definition, while values of global parameters may be modified during a simulation by calling Context::setParameter().

Though possibly we could repeat that in a few other places, like in the descriptions of `addGlobalParameter()` and `setGlobalParameterDefaultValue()`.

**Comment by mpharrigan** [comment]
gah must have missed that one :)

**Comment by peastman** [comment]
To be fair, it's easy to miss.  Repeating that information in a few other places would be helpful.

**Comment by jchodera** [comment]
+1 for repeating this in the User Guide, and maybe even adding a section on different strategies for changing parameters on the fly and the performance tradeoffs that come with them.
