### ISSUE TITLE
Allow for different cutoff styles on CUDA platform

### ISSUE THREAD

**Issue by mvanvleet** [pandegroup/openmm#1779]
I'm attempting to run a simulation which simultaneously uses the following forces: AmoebaMultipoleForce, NonbondedForce, CustomHBondForce, and CustomManyParticleForce. I intend to run a simulation using periodic boundary conditions and as much Ewald summation as possible, which means that I should be using (respectively) the following cutoffs: PME, LJPME, CutoffPeriodic, CutoffPeriodic.

If I use the CPU platform, I've been able to use the python layer to tailor these cutoffs as follows:

```python
# Create system from force field
system = forcefield.createSystem(model_topology,
                nonbondedMethod=app.NoCutoff,
                nonbondedCutoff=1.0*unit.nanometers,
                constraints='AllBonds',
                polarization='mutual',
                ewaldErrorTolerance=0.0005)

# Set distance cutoffs, constraints, and other force-specific options
two_body_cutoff = 1.1*unit.nanometers
three_body_cutoff = 0.9*unit.nanometers
for force in system.getForces():
    if isinstance(force, mm.CustomHbondForce):
        force.setNonbondedMethod(mm.NonbondedForce.CutoffPeriodic)
        force.setCutoffDistance(two_body_cutoff)
    elif isinstance(force, mm.CustomNonbondedForce):
        force.setNonbondedMethod(mm.NonbondedForce.CutoffPeriodic)
        force.setCutoffDistance(two_body_cutoff)
        force.setUseLongRangeCorrection(True)
    elif isinstance(force, mm.AmoebaMultipoleForce):
        force.setNonbondedMethod(mm.NonbondedForce.PME)
    elif isinstance(force, mm.NonbondedForce):
        force.setNonbondedMethod(mm.NonbondedForce.LJPME)
    elif isinstance(force, mm.CustomManyParticleForce):
        force.setNonbondedMethod(mm.NonbondedForce.CutoffPeriodic)
        force.setCutoffDistance(three_body_cutoff)
    else:
        pass

```
(Note that, in my initial call to createSystem, only the choice of `nonbondedMethod=app.NoCutoff` doesn't raise an error.)

If I switch to using the CUDA platform, however, I get the following error:

```
Traceback (most recent call last):
  File "run_co2.py", line 98, in <module>
    simulation = app.Simulation(model_topology, system, integrator, platform)
  File "/home/mvanvleet/.local/lib64/python2.7/site-packages/simtk/openmm/app/simulation.py", line 103, in __init__
    self.context = mm.Context(self.system, self.integrator, platform)
  File "/home/mvanvleet/.local/lib64/python2.7/site-packages/simtk/openmm/openmm.py", line 2835, in __init__
    this = _openmm.new_Context(*args)
Exception: All Forces must agree on whether to use a cutoff
```

Either I'm misunderstanding how to properly input cutoffs for each of my forces (in which case advice on how to structure my input script is very welcome), or the exception handling in openmm.py should be changed to better deal with different, non-mutually-exclusive choices of cutoffs for different forces.

Finally, in case its helpful I've attached my input scripts in the following file:
[cuda_cutoff.zip](https://github.com/pandegroup/openmm/files/906114/cuda_cutoff.zip)
Github won't allow me to upload a .tgz file, so you may need to change the file extension from .zip to .tgz before unarchiving.

**Comment by peastman** [comment]
That does look like odd.  Is it possible you have some other force in your system that is missed in the loop?

**Comment by Lnaden** [comment]
Your input files have a few problems, so I haven't been able to replicate, but I would guess that there is a force you are missing which checks periodic boundary conditions. I can see you have a HarmonicAngleForce in your xml files. There was a recent feature added where bonded terms can wrap around PBC's. @peastman does that Force's `usesPeriodicBoundaryConditions` default to `True` when loaded from xml? That is the only thing I can see which may cause that problem in general. 

I think you will also have problems where you have two different nonbonded cutoff distances for forces in the same force group, that will cause an error also. If you need two different cutoffs, I think you can get around that by separating the forces into different force groups based on the cutoff.

**Comment by Lnaden** [comment]
Wait, no, if it defaults to False we would see that problem. I'm willing to bet that is what is happening. Scratch my previous comment, @peastman

**Comment by mvanvleet** [comment]
@Lnaden, two things:

1. I tried adding a `NonbondedMethod` to the `HarmonicAngleForce`, and got the following error:
```
  File "run_co2.py", line 62, in <module>
    force.setNonbondedMethod(mm.NonbondedForce.CutoffPeriodic)
  File "/home/mvanvleet/.local/lib64/python2.7/site-packages/simtk/openmm/openmm.py", line 14594, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, HarmonicAngleForce, name)
  File "/home/mvanvleet/.local/lib64/python2.7/site-packages/simtk/openmm/openmm.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'HarmonicAngleForce' object has no attribute 'setNonbondedMethod'
```
2. If I comment out the `HarmonicAngleForce`, I still get the `Exception: All Forces must agree on whether to use a cutoff` error.

Thus I don't think `HarmonicAngleForce` is the problem.

@peastman , when I run the code using the CPU platform, I'm getting the following output:
```
Loaded bond definitions
Loaded PDB file
Loaded force field
<simtk.openmm.openmm.AmoebaMultipoleForce; proxy of <Swig Object of type 'OpenMM::AmoebaMultipoleForce *' at 0x2020210> > -2397.12721416 kJ/mol
<simtk.openmm.openmm.NonbondedForce; proxy of <Swig Object of type 'OpenMM::NonbondedForce *' at 0x2020120> > 4277168.51838 kJ/mol
<simtk.openmm.openmm.CustomHbondForce; proxy of <Swig Object of type 'OpenMM::CustomHbondForce *' at 0x2020930> > -4283790.29996 kJ/mol
<simtk.openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x2020090> > 0.0 kJ/mol
<simtk.openmm.openmm.CustomManyParticleForce; proxy of <Swig Object of type 'OpenMM::CustomManyParticleForce *' at 0x2020bd0> > 206.35010419 kJ/mol
-8812.55869238 kJ/mol
```
I don't think you can set a NonbondedMethod for CMMotionRemover, so I think I accounted for all of the forces in my cutoffs loop.

**Comment by mvanvleet** [comment]
Also, @Lnaden, I accidentally deleted a parenthesis in the original .xml input file I gave you; in case that's the 'input file' problem you were referring to, I attached an updated version (renamed as a .txt file so that I could upload it).

[sapt_co2.txt](https://github.com/pandegroup/openmm/files/906810/sapt_co2.txt)

**Comment by Lnaden** [comment]
The bonded forces dont have a periodic method, they simply check whether or not to respect the bond over a periodic boundary. The corresponding methods are `usesPeriodicBoundaryConditions()` which returns the bool, and `setUsesPeriodicBoundaryConditions()` which accepts a bool. 

> If I comment out the HarmonicAngleForce, I still get the Exception

Hmm... problematic. The LJPME is somewhat new, maybe there is a bug where LJPME and PME conflict? That is the only other thing I can think of at the moment. Maybe someone else can see something I don't.

**Comment by mvanvleet** [comment]
> I think you will also have problems where you have two different nonbonded cutoff distances for forces in the same force group, that will cause an error also. If you need two different cutoffs, I think you can get around that by separating the forces into different force groups based on the cutoff.

I did not know this, so thanks for bringing it up! I do want to have two different cutoffs, one for my 2-body interactions (i.e. for all forces except CustomManyParticleForce) and one for 3-body interactions. I'll make sure to separate these forces into different groups in the future. As a side note, it would be good to note this fact in the documentation, as other users may want to use different cutoffs for different forces.

**Comment by peastman** [comment]
> I do want to have two different cutoffs, one for my 2-body interactions (i.e. for all forces except CustomManyParticleForce) and one for 3-body interactions.

You don't need to worry about that case.  CustomManyParticleForce doesn't use the same neighbor list as other nonbonded forces, so it doesn't have the same problems with different cutoffs.

**Comment by peastman** [comment]
I see the problem.  You're passing the wrong constants to the `setNonbondedMethod()` methods.  For example,

```Python
if isinstance(force, mm.CustomHbondForce):
    force.setNonbondedMethod(mm.NonbondedForce.CutoffPeriodic)
```

should instead be

```Python
if isinstance(force, mm.CustomHbondForce):
    force.setNonbondedMethod(mm.CustomHbondForce.CutoffPeriodic)
```

Each class provides it's own set of constants.  They just get converted to integers in the C++ layer.  For example, NonbondedForce defines NoCutoff=0, CutoffNonPeriodic=1, CutoffPeriodic=2, Ewald=3, PME=4, and LJPME=5.  On the other hand, AmoebaMultipoleForce defines NoCutoff=0, PME=1.  So if you take the constants from one and pass it to the other, you end up with the wrong method.

We should probably add some error checking.  I don't know that we can really make it robust, but at least when you pass 4 to AmoebaMultipoleForce, it should recognize that's an invalid argument and throw an exception.

**Comment by peastman** [comment]
I just sent a PR to add error checking.  With that change, your script throws a much more useful error message:

```
Exception: AmoebaMultipoleForce: Illegal value for nonbonded method
```

**Comment by mvanvleet** [comment]
Sounds great. Thanks Peter!
