### ISSUE TITLE
Reorganize examples

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1782]
What do you think about (1) organizing the `examples/` directory a bit, and (2) including the `run_benchmark.sh` and `benchmark.py` scripts in a separate `benchmarks/` directory to make it easier to find?

**Comment by peastman** [comment]
Both are reasonable.  But this is a duplicate of #730, so I'm going to close it.  Let's keep the discussion in one place.

**Comment by jchodera** [comment]
Whoops, sorry!
