### ISSUE TITLE
Context.setVelocitiesToTemperature() does not apply velocity constraints

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1788]
We recently caught a bug in our code due to the fact that `Context.setVelocitiesToTemperature()` does not apply velocity constraints. This may be an intended feature, but it certainly seems to violate the "principle of least surprise" since there are few cases in which that would be desired behavior for constrained systems.

I suggest we:
* Add a call to `applyVelocityConstraints()` using the tolerance in the currently active integrator
* Update the [documentation](http://docs.openmm.org/7.1.0/api-python/generated/simtk.openmm.openmm.Context.html#simtk.openmm.openmm.Context.setVelocitiesToTemperature) to make the behavior for constrained systems clear

**Comment by peastman** [comment]
I think you're mistaken: it already does that.

https://github.com/pandegroup/openmm/blob/master/openmmapi/src/Context.cpp#L205

Your bug must have been caused by something else.

**Comment by jchodera** [comment]
That's....very odd.

@maxentile: Maybe this was an issue with the constraint precision?

@peastman: Why use the hardcoded tolerance `1e-5` instead of `impl->getIntegrator()->getConstraintTolerance()`?

**Comment by maxentile** [comment]
>@maxentile: Maybe this was an issue with the constraint precision?

Unlikely-- the constraint tolerance in the experiments was `1e-8`, and I doubt the difference between solving the constraints to a tolerance of `1e-5` vs `1e-8` would cause the magnitude of error we were observing. Will look into this further...

**Comment by jchodera** [comment]
Ah! It's probably because the random (constrained) velocities are generated from a different configuration than the one sampled, so the constrained components will be incorrect: 
https://github.com/choderalab/integrator-benchmark/blob/refactor/benchmark/testsystems/bookkeepers.py#L149-L156

**Comment by maxentile** [comment]
Ahh, thanks for catching that! That's definitely incorrect in the constrained case, and would explain the behavior we were seeing.

**Comment by peastman** [comment]
Can this be closed?

**Comment by jchodera** [comment]
Thanks!
