### ISSUE TITLE
Is there a way to make PME energies on the CPU deterministic?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1799]
We just realized (or were reminded) today that PME energies on the CPU platform is non-deterministic when more than one thread is in use, which causes some problems for specific applications (such as measuring nonequilibrium work). Setting `OPENMM_CPU_THREADS=1` appears to eliminate the non-determinism.

Is there a way to enforce determinism (possibly with some performance loss, but not forcing only one compute thread) as a platform property?

**Comment by peastman** [comment]
It's not just PME.  Most forces on the CPU are nondeterministic.  That's because we're accumulating them in floating point, which is sensitive to the order in which you add them.

**Comment by jchodera** [comment]
Is there some way to optionally enforce ordering of the accumulation to achieve determinism, with some performance penalty that is intermediate between current performance and forcing the `CPU` platform to use a single thread? We extensively use the `CPU` platform on travis for testing because it is *so much* faster than `Reference`.  Or is running OpenCL on travis the key to fast deterministic behavior on travis?

Oddly enough, it seems that repeated energy computations on the same configuration yield different energies. I wonder if there would at least be some way to cache computed energies if nothing has changed that would cause the energy to change. I believe the `CustomIntegrator` already does this kind of caching...?

**Comment by jchodera** [comment]
I should note that, in our case, only PME has non-deterministic errors large enough to fail our consistency checks. Switching to reaction field (or anything else) seems to give very minimal energy differences from call to call.

**Comment by peastman** [comment]
That's not surprising.  It mostly accumulates energies in double precision, so any variation caused by the order of summation will be tiny.  But PME depends on a whole sequence of calculations based on the single precision grid.  I'll look into what can be done to improve that.
