### ISSUE TITLE
Lack of CONECT records in PDBXFile

### ISSUE THREAD

**Issue by bas-rustenburg** [pandegroup/openmm#1801]
This is not high-priority for me, but it is something to be aware of.

I noticed that `PDBXFile.writeFile` does not write out CONECT records when saving coordinates. It would be handy when working with non-standard residues/small molecules if it did. It might be worth implementing this feature in the future.

**Comment by peastman** [comment]
Or more accurately, `struct_conn` records.  Yes, we should add that.

**Comment by bas-rustenburg** [comment]
Thanks Peter!
