### ISSUE TITLE
Suggestion: Python-friendly persistent topology

### ISSUE THREAD

**Issue by tristanc1** [pandegroup/openmm#1811]
I'm typically working with one large "master" structure, from which I/the user will create simulations of fragments based on arbitrary selections. At the moment I'm generating the topology afresh for each simulation, but since this is an interactive application it's very important to me that startup time is kept to a minimum - and I'm particularly worried that topology generation will slow down a bit once the selection of available residues grows to the full CHARMM set, for example. A separate issue is that I absolutely have to maintain strict correspondence to PDB residue and atom nomenclature, so to make it bombproof I'll have to be applying some checks to make sure the topology applied to each residue actually matches the one expected from the Chemical Components Dictionary. I think the best approach for me would be to create a persistent master topology of the entire structure so the most time-consuming tasks only have to be done once, then cut out the bits matching the current selection to feed straight to OpenMM. What I'm envisioning is an object that behaves rather like a Numpy array, such that:

```
new_topology = topology[atom_indices]
```
... yields a simulation-ready topology covering the selected atoms.

**Comment by peastman** [comment]
How about this?

```Python
modeller = Modeller(master_topology, master_positions)
modeller.delete(parts_to_delete)
new_topology = modeller.topology
```

`Modeller.delete()` is very fast, since it just copies the topology while skipping anything in the list.  See http://docs.openmm.org/7.1.0/api-python/generated/simtk.openmm.app.modeller.Modeller.html#simtk.openmm.app.modeller.Modeller.delete.

**Comment by tristanc1** [comment]
... huh. Yup, that looks very close indeed to what I'm after.

**Comment by tristanc1** [comment]
Actually, after looking at this more closely what I want is one step
further than this: I'd like to capture and hold the master topology *with
all forcefield parameters assigned*, to avoid the overhead of looking these
up again every time - just once on loading the structure, then only if I
edit the master structure or choose to switch forcefields. It's a fairly
niche request and not at all urgent - I'm happy to try to hack something
together myself when I have the time, but just wanted to put the idea out
there.

**Comment by peastman** [comment]
> I'd like to capture and hold the master topology *with all forcefield parameters assigned*

You mean a System?

If you want to create a function similar to `Modeller.delete()` that works on Systems rather than Topologies, that shouldn't be hard.  I'm thinking of something along these lines:

```Python
def createSubSystem(system, particlesToKeep):
  newSystem = System()
  newSystem.setDefaultPeriodicBoxVectors(*system.getDefaultPeriodicBoxVectors())
  for p in particlesToKeep:
    newSystem.addParticle(system.getParticleMass(p))
  indexMap = dict((oldIndex, newIndex) for newIndex, oldIndex in enumerate(particlesToKeep))
  for i in range(system.getNumConstraints()):
    p1, p2, distance = system.getConstraintParameters(i)
    if p1 in indexMap and p2 in indexMap:
      newSystem.addConstraint(indexMap[p1], indexMap[p2], distance)
  ...
```

It would be a bit of work, since you would need to include code for copying every Force class you might use.  But it shouldn't be difficult.

**Comment by tristanc1** [comment]
Thanks for the pointers! It's great to get this level of help from someone
who knows the code inside and out.

**Comment by swails** [comment]
> What I'm envisioning is an object that behaves rather like a Numpy array, such that:
> 
> new_topology = topology[atom_indices]
> ... yields a simulation-ready topology covering the selected atoms.

FWIW, ParmEd does exactly this.  Whether it's performant enough for your needs is something you'll have to decide.  But it has numpy-like indexing (you an either treat it as a flattened list of atoms or a 2-D array of residue, atom tuples).

What's more is that if parameters are loaded into the Topology (called a `Structure` in ParmEd), then those are kept through any subsequent slicing or other manipulations (of course, only those parameters in which all atoms involved in the interaction remain in the resulting `Structure`).
