### ISSUE TITLE
Have `latest` for linking to latest version of API docs?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1813]
Currently, the OpenMM docs push to URLs that include the current release version, like
```
http://docs.openmm.org/7.1.0/api-python/generated/simtk.openmm.openmm.CustomIntegrator.html#simtk.openmm.openmm.CustomIntegrator
```
It would be great to also have the URL with `latest` instead of `7.1.0` resolve to the latest version of the docs, such as
```
http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.CustomIntegrator.html#simtk.openmm.openmm.CustomIntegrator
```
to facilitate linking back to a stable version of OpenMM docs from documentation in other codes.

**Comment by mpharrigan** [comment]
How do you propose we do this? As far as I know, the docs are hosted statically via s3. One way would be to literally copy the latest docs into a folder called `latest` but that's not very elegant.

**Comment by jchodera** [comment]
> One way would be to literally copy the latest docs into a folder called latest but that's not very elegant.

Not elegant, but practical!

**Comment by Lnaden** [comment]
>  the docs are hosted statically via s3  ...  copy the latest docs into a folder

Yes, they are static and you could do that. I came up with a slightly different solution where i drop an HTTP Redirect file into the folder called "latest" which then changes the pointer ([code here](https://github.com/choderalab/yank/blob/e535c3f03e9ad0e246b4eedc5e811b98d9152f0d/devtools/travis-ci/set_doc_version.py#L15-L24)). Its a bit odd since you cant then do extra forwarding such as `...com/latest/second-page`, but it prevents the double up.

**Comment by jchodera** [comment]
I don't think object-level forwarding will work if we want to link to a specific page. We'd have to create a forwarding object for *each* page we want to link to. 

Copying everything to `latest/` seems like the easiest solution.

How are docs releases made anyway?

**Comment by mpharrigan** [comment]
https://github.com/pandegroup/openmm/wiki/Uploading-documentation

**Comment by jchodera** [comment]
OK, I've fixed that to say we should also copy to `/latest/`:
https://github.com/pandegroup/openmm/wiki/Uploading-documentation

Does anyone have access to do this now for the current release 7.1.1? 

But, hm, those instructions won't work here since `/development/` is pushed from `master`, the current 7.2 development branch, not `7.1_branch`. Maybe we have to trigger a travis build of the `7.1_branch` branch and then copy over to `/7.1.1/` and `/latest/`?

**Comment by mpharrigan** [comment]
Have the docs changed in any of the 7.1.1 patches?

**Comment by jchodera** [comment]
I don't think so, but (1) we should have a 1:1 correspondence between releases and doc trees, and (2) I'm not 100% certain the current 7.1 docs were built immediately after a `7.1_branch` build, so it's possible they have some 7.2 dev contamination. (Hopefully not!)

**Comment by peastman** [comment]
> we should have a 1:1 correspondence between releases and doc trees

We never have before.  We've only posted new docs for major releases, not for patches.  Why would we want to?

**Comment by jchodera** [comment]
So we can programmatically send the user to the appropriate documentation page?

**Comment by jchodera** [comment]
Also, given that we made the unfortunate choice to call the documentation directory 7.1.0 despite purportedly having a policy of only releasing docs for major x.y updates, it would now mean that people think we are either lazy or forgetful if we have a 7.1.1 but expect users to go to 7.1.0 for the docs. If we had put the docs in /7.1/ we would be able to get away with that, but now we can't.

**Comment by jchodera** [comment]
@mpharrigan : Any chance you can also copy the currently deployed release docs from the `7.1.0/` directory in the `docs.openmm.org` bucket to a `latest/` subdirectory? That way, links in things like [our openmm tutorials](http://github.com/choderalab/openmm-tutorials) can be made to `latest/` and still point to the latest versions of things, rather than have to be updated every release to fix the URLs.

**Comment by mpharrigan** [comment]
Sure. 

A related thing to consider is to use canonical link elements https://en.wikipedia.org/wiki/Canonical_link_element so search engines and stuff always point to `latest` instead of a specific version

**Comment by mpharrigan** [comment]
copied

**Comment by jchodera** [comment]
We'll have to make sure to do this manually henceforth!
