### ISSUE TITLE
cmake probably cannot find swig on ubuntu 16.04

### ISSUE THREAD

**Issue by ProkopHapala** [pandegroup/openmm#1814]
cmake gives me this error message 

`Swig version must be 3.0.5 or greater! (You have 0.0.0)`

I have installed this swig package using standard package manager of ubuntu:

      swig3.0
      Generate scripting interfaces to C/C++ code
      version: 3.0.8-0ubuntu3 (xenial)

and I can locate it there:

     prokop@prokop-Lenovo-ideapad-Y700-15ISK:~$ whereis swig 
     swig: /usr/bin/swig3.0 /usr/share/swig3.0

I tested it both with recent `master` on github and with `release 7.1` with the same result

**Comment by peastman** [comment]
That means CMake wasn't able to find swig.  Run `ccmake` and check the variable `SWIG_EXECUTABLE`.  Set it to have the correct path to swig.

**Comment by ProkopHapala** [comment]
Great, it works now !
-------------------------
btw. I'm now running the examples/tests which are in `Build` directory it they seem to run properly, just I don't see any output to check (e.g. load relaxed geometry or MD trajectory to some visualization program) ... are there some examples of this type from which I can learn how to use it ?

**Comment by peastman** [comment]
That's an old version of the documentation.  You can always find the most recent documentation at http://openmm.org/documentation.html.
