### ISSUE TITLE
Travis master builds have been failing due to sphinx docs issue

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1820]
This is odd: The travis master builds have been repeatedly failing:

https://travis-ci.org/pandegroup/openmm/branches

![image](https://cloud.githubusercontent.com/assets/3656088/26273145/c8d3c35a-3cf7-11e7-92b4-4861f8f395a5.png)

It looks to be a failure in the sphinx docs:
https://travis-ci.org/pandegroup/openmm/jobs/234088080#L5590-L5602

```
reading sources... [  6%] generated/OpenMM.AmoebaMultipoleForce
Exception occurred:
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/sphinxcontrib/autodoc_doxygen/autosummary/__init__.py", line 44, in import_by_name
    raise ImportError('no module named %s' % ' or '.join(tried))
ImportError: no module named NonbondedMethod or NonbondedMethod
The full traceback has been saved in /tmp/sphinx-err-NJ__ko.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make[3]: *** [api-c++/index.html] Error 1
make[2]: *** [docs-source/api-c++/CMakeFiles/C++ApiDocs.dir/all] Error 2
make[1]: *** [docs-source/api-c++/CMakeFiles/C++ApiDocs.dir/rule] Error 2
make: *** [C++ApiDocs] Error 2
mv: cannot stat ‘sphinx-docs/developerguide/html’: No such file or directory
```

**Comment by jchodera** [comment]
This may be related to why the [conda-dev-recipe for openmm](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/234439715#L3675-L3753) is also failing on the sphinx docs.

**Comment by peastman** [comment]
There's an earlier error that might or might not be connected to that:

```
Exception occurred:
  File "/home/travis/build/pandegroup/openmm/docs-source/sphinx/autonumber.py", line 60, in doctree_resolved
    raise ValueError('Unknown target for autonumber reference: '+target)
ValueError: Unknown target for autonumber reference: Example,Gromacs example
```

Do you know what versions of Doxygen and Sphinx it's using?

**Comment by jchodera** [comment]
Looks like since we've switched to `conda-forge` versions of `doxygen` and `sphinx` unpinned to a specific version. Currently, it seems to be grabbing doxygen (`1.8.13`) and sphinx (`1.6.1`).

Do we need to specify specific versions as part of our [build requirements](https://github.com/pandegroup/openmm/wiki/OpenMM-build-platforms-and-environments)?

**Comment by Lnaden** [comment]
Decent chance, Last I checked, Sphinx was on 1.5.something and going from 1.3 to 1.5 broke a fair amount as they stopped shipping a number of latex packages, I wonder if they did the same going to 1.6

**Comment by jchodera** [comment]
I'll try pinning to 1.5.6.

Let me know if you have any knowledge of which versions are known to work.

**Comment by jchodera** [comment]
Pinning sphinx to 1.5.6 seems to have worked:

https://github.com/omnia-md/conda-dev-recipes/pull/88

**Comment by jchodera** [comment]
I've also opened a PR (#1821) to pin sphinx to 1.5.6 here and noted this in [the wiki](https://github.com/pandegroup/openmm/wiki/OpenMM-build-platforms-and-environments) until we can figure out what is needed to make 1.6.x work.

**Comment by Lnaden** [comment]
Okay, keep this issue open for the time being until we can actually fix this problem. I can look into it tomorrow

**Comment by peastman** [comment]
My attempts to install the latest sphinx have produced a complete broken anaconda.  Even `conda list` just produces an exception.  I think it's caused by incompatibilities between conda and pip, which each want to install their own (different) versions of lots of packages.

Why are we using pip to install Sphinx?  It's also available on conda.  Although it installs 1.5.1, not 1.6.1.

**Comment by jchodera** [comment]
> Why are we using pip to install Sphinx? It's also available on conda. Although it installs 1.5.1, not 1.6.1.

The `.travis.yml` doesn't use anaconda at all. I presumed that was to keep things "lightweight".

**Comment by jchodera** [comment]
> My attempts to install the latest sphinx have produced a complete broken anaconda. Even conda list just produces an exception. I think it's caused by incompatibilities between conda and pip, which each want to install their own (different) versions of lots of packages.

I find it's good to install `miniconda` from scratch every so often. Takes about two minutes, but is pretty easy to do. 

You can also use conda environments to keep things isolated to some degree.

**Comment by jchodera** [comment]
Workaround in #1821.
