### ISSUE TITLE
Intermediate values in custom functions?

### ISSUE THREAD

**Issue by tristanc1** [pandegroup/openmm#1825]
The context for this is my (moderately successful) attempts to implement a flat-bottomed periodic torsion restraint using CustomTorsionForce. From the manual:

> As an example, the following code creates a CustomTorsionForce that implements a harmonic potential:
> ```
> CustomTorsionForce* force = new CustomTorsionForce("0.5*k*(theta-theta0)^2");
> ```
> 

This doesn't work when theta0 is near -180 degrees, since the theta-theta0 difference is non-periodic. Working within the available framework for Lepton expressions I came up with:
 
```
class FlatBottomTorsionRestraintForce(CustomTorsionForce):
    '''
    Wraps an OpenMM CustomTorsionForce to restrain torsion angles while 
    allowing free movement within a range (target +/- cutoff). Within 
    the cutoff range the potential is constant, while outside it 
    is defined as -k * cos (theta-theta0). 
    '''
    def __init__(self):
        standard_energy = '-k*cos(theta-theta0)'
        flat_energy = '-k*cos_cutoff'
        switch_function = 'step(cos(theta-theta0)-cos_cutoff)'
        complete_function = 'select({},{},{})'.format(
            switch_function, flat_energy, standard_energy)
        super().__init__(complete_function)
        per_bond_parameters = ('k', 'theta0', 'cos_cutoff')
        for p in per_bond_parameters:
            self.addPerTorsionParameter(p)
```
where cos_cutoff is the cosine of the cutoff angle.
... which does actually work quite well, but is unsatisfying on two fronts. The first, relatively minor thing is that it creates a potentially metastable state where the torsion is 180 degrees away from the target - in practice, that doesn't appear to be too much of an issue for what I'm doing. The other is that (unless I'm mistaken in how Lepton does its optimisations), cos(theta-theta0) ends up being unnecessarily calculated twice for each torsion: once in the step function to choose the energy equation, and once to actually calculate the energy. Not the biggest issue in this case, but it makes me think: would it be of value to add the capability for custom functions to include variables that are placeholders for other custom functions, with their result substituted in to the main function prior to its execution? In the example above, for example:

```
standard_energy = '-k*cos_theta_minus_theta0'
...
self.addIntermediateFunction('cos_theta_minus_theta0', 'cos(theta-theta0)')
```

**Comment by peastman** [comment]
You can already specify intermediate values.  You just add them after the main expression separated by a semicolon.  So in your example, that would be

```Python
standard_energy = '-k*cos_theta_minus_theta0; cos_theta_minus_theta0=cos(theta-theta0)'
```

See http://docs.openmm.org/7.1.0/userguide/theory.html#writing-custom-expressions for details.

This is just a shortcut to simplify writing expressions.  Regardless of whether you write them that way or not, the expression compiler does common subexpression elimination.  So the intermediate quantities only get computed once.

**Comment by tristanc1** [comment]
Ah, excellent!

**Comment by jchodera** [comment]
@peastman : This reminds me that we updated the API docs for `CustomTorsionForce` in https://github.com/pandegroup/openmm/pull/1761 (which made it into 7.1.1) with clarification about this issue. Perhaps that's another reason to push 7.1.1 docs online?

**Comment by tristanc1** [comment]
A modulo function might also be a nice addition...
For the record, this implementation of a more standard harmonic restraint seems to work nicely. I'm continually blown away by what's actually available in this package.

```
    def __init__(self):
        normalize_fn = '((theta-theta0 + pi) - floor((theta-theta0 + pi) / two_pi) * two_pi - pi)' 
        standard_energy = '0.5*k * dtheta^2'
        flat_energy = '0.5* k * cutoff^2'
        switch_function = 'step(cutoff-dtheta)'
        complete_function = 'select({},{},{});dtheta = {}'.format(
            switch_function, flat_energy, standard_energy, normalize_fn)
        super().__init__(complete_function)
        per_bond_parameters = ('k', 'theta0', 'cutoff')
        for p in per_bond_parameters:
            self.addPerTorsionParameter(p)
        self.addGlobalParameter('pi', pi)
        self.addGlobalParameter('two_pi', 2*pi)
```

**Comment by jchodera** [comment]
> A modulo function might also be a nice addition...

+1

**Comment by peastman** [comment]
> A modulo function might also be a nice addition...

How would you want it defined?  Should it round downward or toward zero?

In C++, the fmod() function rounds toward zero and the remainder() function rounds downward, so `fmod(-1.5, 2.0)` is -1.5 and `remainder(-1.5, 2.0)` is 0.5.  In Python, the mod operator rounds downward, so `-1.5%2.0` is 0.5.

**Comment by jchodera** [comment]
I still think that a function like `minimum_image(delta)`, which would return the minimum image of the separation `delta` in the interval `[-pi, +pi]`, would greatly simplify these cases.

**Comment by tristanc1** [comment]
Actually, John's suggestion would be even better. But, in terms of a mod
function I'd go with the Python definition - the C version can be quite
surprising to non-programmers, since most people are taught in school that
the result of a mod b is strictly positive.

**Comment by davidlmobley** [comment]
Has there been any headway on the modulo function? We're trying to do umbrella sampling on a torsion and run into the obvious issue when we approach the endpoints (+/- 180 degrees). Perhaps there is a simple workaround, but the modulo seems like it would be easiest.

**Comment by davidlmobley** [comment]
(`minimum_image` would also be great)

**Comment by tristanc1** [comment]
If you just want to restrain a torsion to a given angle with a
straightforward harmonic potential, then PeriodicTorsionForce should suit
your purposes.

**Comment by jchodera** [comment]
I'd really love a `minimum_image()` function, but the workaround for now is to use a scheme like [this](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/charmmpsffile.py#L918-L920):
```python
        energy_function = 'k*min(dtheta, 2*pi-dtheta)^2; dtheta = abs(theta-theta0);'
        energy_function += 'pi = %f;' % pi
        force = mm.CustomTorsionForce(energy_function)
```

**Comment by jchodera** [comment]
> If you just want to restrain a torsion to a given angle with a straightforward harmonic potential, then PeriodicTorsionForce should suit your purposes.

Note that `PeriodicTorsionForce` does *not* use harmonic restraints, but instead Fourier expansions. However, the 1-fold Fourier term is just a `cos(theta)` function that is the equivalent of the [von Mises distribution](https://en.wikipedia.org/wiki/Von_Mises_distribution).

**Comment by davidlmobley** [comment]
Thanks!

**Comment by tristanc1** [comment]
Ah - thanks for the info!

When implementing a flat-bottomed torsion restraint potential with
CustomTorsionForce I found making the energy proportional to cos(dtheta)
outside the flat region to be quite well-behaved. The alternative
minimum_image approach seems to give weird behavior when the starting
torsion is 180 degrees away from the target (presumably due to the
singularity in the gradient there).

**Comment by jlmaccal** [comment]
@davidlmobley I think something like this will give you the absolute difference that runs from 0 to pi.
```
diff = pi - abs(abs(theta - theta0) - pi);
```

**Comment by tristanic** [comment]
Having had to address the angle-wrapping question again while porting some of my code from Python to C++, it turns out there's a ridiculously simple solution in the latter:

```
#include <cmath> // just for M_PI
const double TWO_PI = 2.0*M_PI;
// Retuns the angle in the range [-pi,pi]
inline double wrapped_angle(const double &angle) { return remainder(angle, TWO_PI); }
```
