### ISSUE TITLE
CustomCentroidBondForce Wrong number of parameters for bond 0 Error

### ISSUE THREAD

**Issue by lenhsherr** [pandegroup/openmm#1833]
Hi,

I encountered a problem when using CustomCentroidBondForce. I created a virtual equilibrium point and tried to set a CustomCentroidBondForce between the ligand and this point, while moving the point  to emulate a continuous pulling force in a steered MD simulation.

Here is now I initialize this force by setting the point to COM of the ligand.

```
pull_vx, pull_vy, pull_vz = list(pull_vector * pull_v)
pullforce = CustomCompoundBondForce(1, '0.5*k*((x1-pullpoint_x)^2+(y1-pullpoint_y)^2+(z1-pullpoint_z)^2)')
k_parm_idx = pullforce.addGlobalParameter('k',1 * md_kilocalorie / (mole * angstrom * angstrom))
x_parm_idx = pullforce.addGlobalParameter('pullpoint_x',ligand_initial_com[0])
y_parm_idx = pullforce.addGlobalParameter('pullpoint_y',ligand_initial_com[1])
z_parm_idx = pullforce.addGlobalParameter('pullpoint_z',ligand_initial_com[2])
for i in range(4):
        print(pullforce.getGlobalParameterDefaultValue(i))
pullforce.addGroup(ligand_atom_index)
pullforce.addBond([0], [k_parm_idx,x_parm_idx,y_parm_idx,z_parm_idx])
print(pullforce.getNumGlobalParameters())
print(pullforce.getNumPerBondParameters())
system = openmm_top.createSystem(nonbondedMethod=PME, nonbondedCutoff=1 * nanometer,
                                     constraints=HBonds)
system.addForce(pullforce)
integrator = LangevinIntegrator(300 * kelvin, 1 / picosecond, 0.002 * picoseconds)
sim = Simulation(openmm_top.topology, system, integrator, platform, properties)
```

And I get the error:
`Exception: CustomCentroidBondForce: Wrong number of parameters for bond 0`

Could you help me out?

Thanks!

**Comment by jlmaccal** [comment]
You don't have any per-bond parameters, so the call to `addBond` is expecting no parameters, while you are giving it 4.

You need to change the calls to `addGlobalParameter` to `addPerBondParameter`.

**Comment by lenhsherr** [comment]
Thanks a lot. That solves the problem.
