### ISSUE TITLE
Fix documentation issues and add a branch that tests documentation build

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1835]
We've run into an issue where we have accidentally introduced errors into the docstrings of some of the Python bits of OpenMM without noticing.

We should 
* correct the docstring errors (here is an [example](https://travis-ci.org/pandegroup/openmm/jobs/242962112#L6028-L6045))
* ensure the sphinx docs build is tested in some travis branch

cc #1821

**Comment by jchodera** [comment]
Deployment of the [development documentation build](http://docs.openmm.org/development/api-python/index.html) [is failing](https://travis-ci.org/pandegroup/openmm/jobs/263314139#L6539-L6546) due to what appears to be S3 bucket permissions issues:
```
Preparing deploy
Logging in with Access Key: ****************ICHQ
dpl.3
Deploying application
uploading "userguide/application.html" with {:content_type=>"text/html"}
Oops, It looks like you tried to write to a bucket that isn't yours or doesn't exist yet. Please create the bucket before trying to write to it.
failed to deploy
```
It would be great to get this fixed ASAP.

**Comment by jchodera** [comment]
Just a reminder that the documentation deployment is failing, but it would be great to get this fixed.

@rmcgibbo : Any chance you can help?

**Comment by jchodera** [comment]
Deployment of the dev docs is [still failing](https://travis-ci.org/pandegroup/openmm/jobs/268497277#L6552-L6559):
```
Preparing deploy
Logging in with Access Key: ****************ICHQ
dpl.3
Deploying application
uploading "userguide/application.html" with {:content_type=>"text/html"}
Oops, It looks like you tried to write to a bucket that isn't yours or doesn't exist yet. Please create the bucket before trying to write to it.
failed to deploy
```
We should really get this fixed ASAP.

**Comment by mpharrigan** [comment]
that access key can only push to openmm.org. I'll add docs.openmm.org as well

**Comment by mpharrigan** [comment]
try it now

**Comment by jchodera** [comment]
> that access key can only push to openmm.org. I'll add docs.openmm.org as well

I think @peastman may have to retrigger travis on `master` to see if this works. I don't have access to do so:

https://travis-ci.org/pandegroup/openmm/builds/268497272

**Comment by peastman** [comment]
It's running now.

**Comment by jchodera** [comment]
It worked! Thanks!

**Comment by peastman** [comment]
Yay!  Thanks!

**Comment by peastman** [comment]
Can this be closed?  It sounds like the issue is now fixed.

**Comment by jchodera** [comment]
Looks like the docs are up to date!
