### ISSUE TITLE
Errors as using OpenMM7.1.1 on GPU (Quadro M6000) 

### ISSUE THREAD

**Issue by yongwangCPH** [pandegroup/openmm#1840]
I tried to run openmm7.1.1 (installed by "conda install -c acellera openmm") on a single GPU (Quadro M6000). But got errors at this step: 
simulation = Simulation(top.topology, system, integrator, platform, properties)
as shown below:

python: /anaconda/conda-bld/openmm_1494332150045/work/libraries/quern/src/quern_factorization.cpp:88: bool apply_givens(SparseVector &, SparseVector &, int, double &, double &): Assertion `!y.empty() && y.front().index==diagonal && y.front().value' failed.

Any clues?

**Comment by peastman** [comment]
I'm not familiar with the `acellera` channel.  Perhaps someone is copying OpenMM builds over to their own channel, or maybe they're doing their own builds?  The command to install the official OpenMM build is

```
conda install -c omnia openmm
```

Anyway, Quern is a sparse matrix library we use for inverting constraint matrices.  If it's failing, the most likely reason is that you have a singular constraint matrix.  Here are some reasons that might happen:

- You've added two constraints to the System for the same pair of particles.
- You've added inconsistent constraints.  For example, you've constrained all the distances between three particles, but those distances don't satisfy the triangle inequality.
- You've added too many constraints such that the matrix is overdetermined.

**Comment by peastman** [comment]
Closing this, since there's been no reply since June.
