### ISSUE TITLE
PDBWriter reuses residue index for different water molecules

### ISSUE THREAD

**Issue by JoaoRodrigues** [pandegroup/openmm#1843]
Hi all,

I'm having a small issue with one of my simulations. After loading a PDB file and using the `Modeller` class to add solvent (TIP3P water), I am doing a small energy minimization and saving the resulting minimized structure to use later on when doing restarts of my simulation (to get the initial topology and call `createSystem`).

I can reproduce the problem doing this:
```
from simtk.openmm import app
import simtk.unit as units

pdb = app.PDBFile('minimized.pdb')
forcefield = app.ForceField('amber99sbildn_phopho.xml', 'tip3p.xml')  # see end of issue
system = ff.createSystem(pdb.topology, nonbondedMethod=app.PME,
                                       nonbondedCutoff=1.0*units.nanometer, constraints=app.AllBonds,
                                       hydrogenMass=4*units.amu, ewaldErrorTolerance=0.0005)
```

The error I am getting is:
```
Traceback (most recent call last):
  File "md.py", line 267, in <module>
    ewaldErrorTolerance=0.0005)
  File "/home/stanford/levittm/shared/software/miniconda2/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 1078, in createSystem
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 33491 (HOH).  The set of atoms matches HOH, but the bonds are different.
```

Adding a few `print` statements to `forcefield.py`, I found that the topology is somehow messed up, as there are extra bonds for that particular water molecule:
```
Bond(<Atom 100995 (H1) of chain 1 residue 33490 (HOH)>, <Atom 100994 (O) of chain 1 residue 33490 (HOH)>)
Bond(<Atom 100996 (H2) of chain 1 residue 33490 (HOH)>, <Atom 100994 (O) of chain 1 residue 33490 (HOH)>)
Bond(<Atom 100994 (O) of chain 1 residue 33490 (HOH)>, <Atom 101009 (O) of chain 1 residue 33495 (HOH)>)]
```

Looking at the PDB file I am loading, grepping for that `index`, I get residue `HOH B 919`. When I grep again the file for `HOH B 919` this is what I get:
```
HETATM 3490  O   HOH B 919      20.197  23.765   2.487  1.00  0.00           O
HETATM 3491  H1  HOH B 919      19.518  24.303   2.080  1.00  0.00           H
HETATM 3492  H2  HOH B 919      20.107  23.933   3.425  1.00  0.00           H
HETATM33490  O   HOH B 919      38.220  17.345   9.788  1.00  0.00           O
HETATM33491  H1  HOH B 919      38.587  18.204   9.579  1.00  0.00           H
HETATM33492  H2  HOH B 919      37.913  17.429  10.691  1.00  0.00           H
HETATM63490  O   HOH B 919      34.994 101.711  67.553  1.00  0.00           O
HETATM63491  H1  HOH B 919      34.607 101.251  68.297  1.00  0.00           H
HETATM63492  H2  HOH B 919      35.357 102.513  67.929  1.00  0.00           H
HETATM93490  O   HOH B 919      77.376 119.844  82.356  1.00  0.00           O
HETATM93491  H1  HOH B 919      77.038 119.150  81.790  1.00  0.00           H
HETATM93492  H2  HOH B 919      77.377 119.460  83.233  1.00  0.00           H
HETATM23490  O   HOH B 919      91.120 103.415  56.590  1.00  0.00           O
HETATM23491  H1  HOH B 919      91.316 104.225  57.060  1.00  0.00           H
HETATM23492  H2  HOH B 919      91.952 103.162  56.190  1.00  0.00           H
```

It seems that the PDBWriter is writing multiple waters to the same residue number. This is potentially throwing off the topology builder? Or is there something else wrong with my setup/file? This same structure went on (in a first pass) to be simulated for a few dozen nanoseconds without a problem.

You can download the minimized structure [here](https://u5333631.dl.dropboxusercontent.com/u/5333631/RPS6_CTD_S235p_minimized_EM.pdb), although it has a modified residue (SEP). The modified forcefield is [here](https://u5333631.dl.dropboxusercontent.com/u/5333631/amber99sbildn_phospho.xml) and corresponding `residues.xml` [here](https://u5333631.dl.dropboxusercontent.com/u/5333631/residues.xml).

**Comment by peastman** [comment]
This is a limitation of the PDB format: it officially doesn't support more than 9999 residues or more than 99,999 atoms in a single file.  It only provides four columns for the residue ID and five columns for the atom ID.  So when you pass that many, it wraps around and starts reusing IDs.  In many cases this wouldn't matter, but your file includes a nonstandard SEP residue for which there are CONECT records.  Those records specify the bonds between atoms of that residue, indicated by atom ID.  But because there are multiple atoms with the same ID, it doesn't know which ones they refer to.

The best solution is probably to use PDBxWriter instead of PDBWriter.  It's a much newer file format that doesn't have those limitations.

**Comment by JoaoRodrigues** [comment]
Thanks @peastman , makes sense indeed. I didn't think of that. I'll just switch to `PDBxWriter` then from now on, to keep it simple.
