### ISSUE TITLE
Add new OpenMM logo to openmm.org webpage

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1845]
Now that we have a snazzy OpenMM logo, we can add it to the http://openmm.org webpage!

**Comment by peastman** [comment]
PR welcome. :)

**Comment by pandelab** [comment]
Good idea!

**Comment by pandelab** [comment]
Ok that was me. Theresa not Vijay.

**Comment by mpharrigan** [comment]
https://github.com/pandegroup/openmm-org/pull/7

**Comment by jchodera** [comment]
Thanks!

**Comment by peastman** [comment]
It looks like that PR got forgotten.  In addition to adding the logos, it also made some changes we didn't want, and @frabjous5 never replied to the question about it.  We should just make a new PR with only the logos and close that one.

**Comment by jchodera** [comment]
This has been rolled into https://github.com/pandegroup/openmm-org/pull/19
