### ISSUE TITLE
slower CUDA benchmarks just for PME

### ISSUE THREAD

**Issue by zonca** [pandegroup/openmm#1851]
hi,
I have a bunch of GPU cards I'm testing, I have 2 cards that compared to the rest show a much slower performance, but just in PME...

See here the ratio in percentage between those cards and the rest. They are 40% slower in the first test! (I repeated the test 3 times with consistent results)

```
test	Explicit-PME, 2 fs	Explicit-PME, 5 fs HMR	Explicit-RF, 2 fs	Explicit-RF, 5 fs HMR	Implicit, 2 fs	Implicit, 5 fs HMR						
1	58.797015	89.066308	97.769848	98.403075	99.820583	98.361318
2	58.820896	89.108602	97.568113	97.961898	100.011831	97.797768
```

What is special in the PME tests that are the only ones affected? (I might be too hopeful here) Would you be able to guess what is wrong with the cards?

**Comment by peastman** [comment]
What kinds of GPUs are you comparing?

**Comment by zonca** [comment]
P100

**Comment by peastman** [comment]
Are the P100s the slow ones or the fast ones?  What are the others?  Or are you saying they're all P100s, and some of them are slower than others?

There's no good reason for some cards to be slower than others that are supposedly identical.  That sounds like something is wrong with them.  But make sure these results are reproducible.  For example, that there wasn't just something else running on the computer during those tests that was slowing it down.  Or that the GPU had gotten hot and was throttling the clock speed.

**Comment by zonca** [comment]
They are all P100, I repeated the tests a few times and got consistent
results.
What is interesting is that only PME is so much slower. I am wondering if
something in the card is particularly stressed by that test!

**Comment by peastman** [comment]
It's hard to guess.  If supposedly identical cards running identical code give such different performance, that certainly seems like *something* is wrong.  Are there any other differences that might explain it?  For example, did you test them all in the same computer, or were they in different computers?

**Comment by zonca** [comment]
I was wondering is the fact that just PME gives worse performance could give a hint on what could be wrong. Do you have a feeling of what is special about the first test compared to the others?

**Comment by zonca** [comment]
Reading again your previous answer it looks like there is nothing obvious, we are doing other tests, we'll try to identify the issue with other tools!

**Comment by peastman** [comment]
A good first step would be to run your test through nvvp.  That would tell you which kernels are taking longer.
