### ISSUE TITLE
Different speed of simulation with same number of water molecules and water model

### ISSUE THREAD

**Issue by arjunwadhawan** [pandegroup/openmm#1852]
Hello,

I am running MD simulation on 100 TIP4P-ice waters in a box using openMM from two different .pdb files (which I got from 2 different gromacs simulation).

I am failing to understand why I am getting different speed with same number of molecules (and box size) , same residue name  and using same force field. Difference is more than 100 ns/Day 

I am running openmm -7.1.1 with openmmtools -0.9.4 on a NVIDIA GeForce GTX TITAN X with CUDA

I can think that it is due to different force filed that openmm is choosing in each case but I am not able to understand why, how and finally which is correct. Both .pdb have same residue name and atom name. Both have same number of atoms (but different positions).

The solution could be very silly one but since I was stuck for more than 2 days, I thought of asking for help. 

Attached are following file

1- a_100_water_fast.pdb : 100 water which give faster speed
2- b_100_water_slow.pdb : 100 water which give slower speed
3- tip4pice.xml : force field
4- openmm_CUDA_100water.py : script used for running 
Rest are the analysis showing different speed .
[openmm_speed_issue_100water.zip](https://github.com/pandegroup/openmm/files/1115556/openmm_speed_issue_100water.zip)

**Comment by peastman** [comment]
The fast one has a smaller box.  It specifies

```
CRYST1   49.787   49.787   49.787  90.00  90.00  90.00 P 1           1
```

and the slow one specifies

```
CRYST1   53.400   53.400   53.400  90.00  90.00  90.00 P 1           1
```

That will cause it to use a larger PME grid.

**Comment by arjunwadhawan** [comment]
Thanks for the quick answer. Yes that is indeed the issue and I thought 3 A to be insignificant to effect the speed. Two more questions came to my mind:-
1- Is there any way to log the generated PME grid used during the simulation ?
2- Is the PME grid ever optimised while running simulations (eg: simulating with a barostat) ?

**Comment by peastman** [comment]
> I thought 3 A to be insignificant to effect the speed.

Remember you're dealing with a 3D grid.  So the box volume is (53.4/49.787)^3 = 1.23 times as large.  It's a bigger difference than you think!

>  1- Is there any way to log the generated PME grid used during the simulation ?

Call `getPMEParametersInContext()` on the NonbondedForce.

>  2- Is the PME grid ever optimised while running simulations (eg: simulating with a barostat) ?

No, it gets set at the start of the simulation and never changes.

**Comment by arjunwadhawan** [comment]
Thanks for the answer.
