### ISSUE TITLE
Simulating LJ spheres on a 2D plane

### ISSUE THREAD

**Issue by stefdoerr** [pandegroup/openmm#1856]
Hey, sorry that this is a noob question but I thought it might be faster to just ask so I hope you don't mind.

How would you go about simulating a bunch of arbitrarily sized spheres in OpenMM with only a Lennard-Jones potential? I am trying to distribute these spheres more or less regularly over a 2D plane (find a good packing).

Looking at the documentation I thought of doing it as follows.
Define a forcefield with a new [atom-type](http://docs.openmm.org/7.1.0/userguide/application.html#atomtypes) and manually write the LJ potential as two [CustomNonBondedForce](http://docs.openmm.org/7.1.0/userguide/application.html#customnonbondedforce) corresponding to the VdW force and Pauli repulsion.
But I assume these must be modelled already somewhere in OpenMM?

No idea how to make it a 2D simulation but I guess I could apply forces to keep the atoms on a fixed z plane.

**Comment by jchodera** [comment]
Take a look at the [`LennardJonesCluster`](https://github.com/choderalab/openmmtools/blob/master/openmmtools/testsystems.py#L1611-L1722) testsystem from [`openmmtools.testsystems`](http://openmmtools.readthedocs.io/en/latest/testsystems.html#clusters-and-simple-fluids) for an example that I think is similar to what you are looking for.

**Comment by stefdoerr** [comment]
Great! Many thanks for the pointer :)

**Comment by stefdoerr** [comment]
In the end I used the LennardJonesFluid example, made all starting positions have z=0 and I added an extra potential.

[ljfluid.py.tar.gz](https://github.com/pandegroup/openmm/files/1145198/ljfluid.py.tar.gz)
```python
        [...]
        # Add a restraining potential to keep atoms in z=0
        energy_expression = 'k * (z^2)'
        force = openmm.CustomExternalForce(energy_expression)
        force.addGlobalParameter('k', 10)
        for particle_index in range(nparticles):
            force.addParticle(particle_index, [])
        system.addForce(force)

        integrator = VerletIntegrator(0.002 * picoseconds)
        simulation = Simulation(topology, system, integrator)
        simulation.context.setPositions(positions)
        simulation.minimizeEnergy()
        simulation.step(nsteps)
```

My problem is that when I put all my atoms on a z=0 plane it explodes. Here is the starting conformation

![screenshot from 2017-07-13 14-43-21](https://user-images.githubusercontent.com/7935362/28166893-f1ef08b4-67d9-11e7-9f4c-a0ae0fec48fc.png)

I see that there are many clashes but there is enough space for them to resolve as far as I can tell.

With a sigma of 2+ (Argon should be 3.4) I get:
```
#"Step"   "Potential Energy (kJ/mole)"   "Total Energy (kJ/mole)"
1000   6319700576262.403   3018687544961030.5
```
And my atoms shoot off into the z dimension.

With a sigma of 1 I get:
```
#"Step"   "Potential Energy (kJ/mole)"   "Total Energy (kJ/mole)"
1000   -7.539158192124563   -2.6891315622491616
```
and my atoms stay on the plane (but very few interact since my  cutoff is 3*sigma)


I thought minimization might help avoid the explosion but doesn't seem to do it.

If you have any suggestions or comments I would be happy to hear them :)

**Comment by stefdoerr** [comment]
Eh probably ignore me. Seems like there is probably not enough space for 100 atoms on that small plane box. I reduced the number of atoms and they seem to behave fine.

**Comment by stefdoerr** [comment]
With a box size of 34x34 I should be able to fit 100 atoms of sigma 3.4 in the box if I understand right. This is also the equivalent of the equation used in the [3D example](https://github.com/choderalab/openmmtools/blob/master/openmmtools/testsystems.py#L1828). However with more than 85 atoms the energy explodes.

**Comment by jchodera** [comment]
Are you OK with using a square number of particles? If so, placing the particles in a rectangular grid and then minimizing the energy is a good way to make sure the energies stay reasonable. 

If the number can be arbitrary, I think you could still use the subrandom number generator we use for the fluid----just use the (x,y) coordinates, but it's important you take the first N positions from the subrandom number generator rather than just projecting all the 3D coordinates afterwards.

Also, how critical is it that they remain in the 2D plane? We might need a special CustomIntegrator that doesn't change the z dimensions.

**Comment by stefdoerr** [comment]
No unfortunately it's for arbitrary number of particles. 
Indeed in my code I just call sobol `ivec = sobol.i4_sobol_generate(ndim, nparticles, 1)` with `ndim = 2` so I am not projecting the 3D points to 2D but actually using the first N 2D points.

I tried it now with halton subrandom numbers and it works fine for 100 atoms. Even in wikipedia if you look at the two sequences you see that halton produces fewer overlaps.

[Sobol](https://en.wikipedia.org/wiki/Sobol_sequence#/media/File:Sobol_sequence_2D.svg)
[Halton](https://en.wikipedia.org/wiki/Halton_sequence#/media/File:Halton_sequence_2D.svg)

I will give it a try now with different sigmas per atom which was the initial idea and see if it works without the need of a CustomIntegrator.

**Comment by stefdoerr** [comment]
Great! Works fine with different sigmas. The trick was the Halton initialization which reduced clashes.

Shouldn't the minimizer deal with these initial clashes? 

I will probably make another thread on this in a few days because I've had problems in normal simulations as well with the minimizer not actually minimizing.

**Comment by jchodera** [comment]
> Shouldn't the minimizer deal with these initial clashes?

The L-BFGS minimizer isn't going to help a huge amount in really bad initial cases---it can too easily get stuck or slow down near the numerous saddle points.

> I will probably make another thread on this in a few days because I've had problems in normal simulations as well with the minimizer not actually minimizing.

There are cases where either [better minimizers that avoid saddle points](https://ganguli-gang.stanford.edu/pdf/14.SaddlePoint.NIPS.pdf) or [sloppier minimizers that can escape local minima](http://dx.doi.org/10.1103/PhysRevLett.97.170201) would help.

**Comment by stefdoerr** [comment]
I was actually comparing it to the minimizer in Acemd which uses steepest
descent but seems to minimize much better in the cases I tried.

**Comment by stefdoerr** [comment]
I don't know if I will find time tomorrow, otherwise I will provide
examples for this in August when I'm back in the lab.

**Comment by jchodera** [comment]
It would be great to find an example that works well with ACEMD's minimizer but poorly in OpenMM's `LocalEnergyMinimizer`. We could certainly implement a different kind of optimizer, allow more control about how much (or little) memory is retained, or implement something simple as a `CustomIntegrator`.
