### ISSUE TITLE
Pure liquid simulations not calculating density

### ISSUE THREAD

**Issue by jthorton** [pandegroup/openmm#1859]
Hello,
I have been using OpenMM to simulate pure organic liquids and get strange results whereby the volume and density of the simulation do not vary. This seems to happen when I call the OPLS geometric combination rule at the start the script, shown below, while using PME as the nonbonded method otherwise the simulation works as expected with the Cutoff Periodic option.  The results of running the script on ethanol are also attached along with the xml and pdb input file. I am using OpenMM7.1.1 installed through conda install -c omnia openmm with python3 from Anaconda 4.4.0 running on ubuntu 16.04, has anyone else came across this error?

from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from sys import stdout
#from dcdreporter import DCDReporter
import numpy as np

def OPLS_LJ(system):
    forces = {system.getForce(index).__class__.__name__: system.getForce(
        index) for index in range(system.getNumForces())}
    nonbonded_force = forces['NonbondedForce']
    lorentz = CustomNonbondedForce(
        '4*epsilon*((sigma/r)^12-(sigma/r)^6); sigma=sqrt(sigma1*sigma2); epsilon=sqrt(epsilon1*epsilon2)')
    lorentz.setNonbondedMethod(nonbonded_force.getNonbondedMethod())
    lorentz.addPerParticleParameter('sigma')
    lorentz.addPerParticleParameter('epsilon')
    lorentz.setCutoffDistance(nonbonded_force.getCutoffDistance())
    system.addForce(lorentz)
    LJset = {}
    for index in range(nonbonded_force.getNumParticles()):
        charge, sigma, epsilon = nonbonded_force.getParticleParameters(index)
        LJset[index] = (sigma, epsilon)
        lorentz.addParticle([sigma, epsilon])
        nonbonded_force.setParticleParameters(
            index, charge, sigma, epsilon * 0)
    for i in range(nonbonded_force.getNumExceptions()):
        (p1, p2, q, sig, eps) = nonbonded_force.getExceptionParameters(i)
        # ALL THE 12,13 and 14 interactions are EXCLUDED FROM CUSTOM NONBONDED
        # FORCE
        lorentz.addExclusion(p1, p2)
        if eps._value != 0.0:
            # print p1,p2,sig,eps
            sig14 = sqrt(LJset[p1][0] * LJset[p2][0])
            eps14 = sqrt(LJset[p1][1] * LJset[p2][1])
            nonbonded_force.setExceptionParameters(i, p1, p2, q, sig14, eps)
    return system

pdb = PDBFile('NewBox_ETH.pdb')
modeller = Modeller(pdb.topology, pdb.positions)
forcefield = ForceField('ETH.xml')
system = forcefield.createSystem(
    modeller.topology, nonbondedMethod=PME, nonbondedCutoff=1 * nanometer)
system = OPLS_LJ(system)
TEMP = 298.15 * kelvin
system.addForce(MonteCarloBarostat(1 * bar, TEMP))
integrator = LangevinIntegrator(TEMP, 1 / picosecond, 0.001 * picoseconds)
simulation = Simulation(pdb.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
print('MINIMIZATION STARTED')
simulation.minimizeEnergy()
#print('Energy at Minima is %3.3f kcal/mol' % (energy._value * KcalPerKJ))
print('MINIMIZATION DONE')
simulation.reporters.append(PDBReporter('output.pdb', 1000))
simulation.reporters.append(StateDataReporter('data.txt', 1000, step=True, potentialEnergy=True, temperature=True, density=True ,volume=True))
simulation.step(50000)
np_equ_pos = simulation.context.getState(getPositions=True).getPositions()
PDBFile.writeFile(simulation.topology, np_equ_pos, open('NPT_EQ_FINAL.pdb', 'w'))

#"Step","Potential Energy (kJ/mole)","Temperature (K)","Box Volume (nm^3)","Density (g/mL)"
1000,1348.6706442521554,189.81011151148093,64.15248023003338,0.31838721367267125
2000,3360.3268497374097,256.62722141468515,64.15248023003338,0.31838721367267125
3000,4038.2536988693582,279.5913300452281,64.15248023003338,0.31838721367267125
4000,4200.466046247545,293.14019430123415,64.15248023003338,0.31838721367267125
5000,3933.895683314894,294.2655098803533,64.15248023003338,0.31838721367267125
6000,4058.4867082384812,302.2091331469401,64.15248023003338,0.31838721367267125
7000,3800.5357911221527,305.2839936547145,64.15248023003338,0.31838721367267125
8000,3945.392471514505,303.5029208081474,64.15248023003338,0.31838721367267125
9000,3698.472924979846,304.36478894374943,64.15248023003338,0.31838721367267125
10000,3832.2731989104554,290.7256344794723,64.15248023003338,0.31838721367267125

[ethanol_liq.zip](https://github.com/pandegroup/openmm/files/1164938/ethanol_liq.zip)

**Comment by jchodera** [comment]
Could you ZIP up your script and upload that as well?

**Comment by jthorton** [comment]
Yeah, I have moved everything to the attached zip file.

**Comment by peastman** [comment]
When I run your script it fails with this exception:

```
Traceback (most recent call last):
  File "OpenMM_PureLiquids.py", line 44, in <module>
    system = OPLS_LJ(system)
  File "OpenMM_PureLiquids.py", line 15, in OPLS_LJ
    lorentz.setNonbondedMethod(nonbonded_force.getNonbondedMethod())
  File "/usr/local/lib/python2.7/dist-packages/simtk/openmm/openmm.py", line 5196, in setNonbondedMethod
    return _openmm.CustomNonbondedForce_setNonbondedMethod(self, method)
Exception: CustomNonbondedForce: Illegal value for nonbonded method
```

The NonbondedForce has its nonbonded method set to PME, which isn't an option for CustomNonbondedForce.  I changed that line to

```Python
lorentz.setNonbondedMethod(CustomNonbondedForce.CutoffPeriodic)
```

And now it works:

```
#"Step","Potential Energy (kJ/mole)","Temperature (K)","Box Volume (nm^3)","Dens
ity (g/mL)"
1000,1311.99582105,196.546160959,61.2600832336,0.333419877227
2000,3056.66769605,255.699354129,59.6410731908,0.342470856708
3000,3229.6091023,282.3281225,54.796268046,0.372750374414
4000,3511.0544148,287.141855958,51.9614944927,0.393085873108
5000,3483.6403523,293.486417286,46.2884566578,0.441261837301
```

The error checking to catch this mistake was just added a few months ago (#1781), so that's why you didn't get the exception.

**Comment by jthorton** [comment]
Thank you very much that works great now.
