### ISSUE TITLE
Issue of mbpol_openmm_plugin

### ISSUE THREAD

**Issue by semoday** [pandegroup/openmm#1860]
Hello,

I installed openMM with Conda and mbpol_openmm_plugin from source. 
And I made a generated_script_filename.py to run the simulation from mbpol_builder. 

There are 2 Platforms available:
1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
GPU acceleration is not available in my environment.

This is my issue.
![platform](https://user-images.githubusercontent.com/25753034/28417633-ce80aa62-6d93-11e7-8bb8-4828ac006171.png)

Specified a Platform for a Context which does not support all required kernels was returned for both Reference and CPU. I have no idea about this. 

And here is my script file. 
[generated_script_filename.zip](https://github.com/pandegroup/openmm/files/1162271/generated_script_filename.zip)

**Comment by peastman** [comment]
Most likely this means the plugin isn't getting loaded.  Try opening up a Python interpreter and enter the following:

```Python
from simtk.openmm import *
print(pluginLoadedLibNames)
print(Platform.getPluginLoadFailures())
```

That will tell you which plugins were loaded, and if any failed to load it will give hopefully informative error messages.

**Comment by semoday** [comment]
I found what problem is thanks to your comment.
Thank you peastman.

**Comment by peastman** [comment]
Great!
