### ISSUE TITLE
Unable to install using conda: PermissionError

### ISSUE THREAD

**Issue by rcrehuet** [pandegroup/openmm#1864]
I am trying to install OpenMM with conda and I get the following error:

```
ramon@puput:~$ conda install -c omnia openmm
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /home/ramon/anaconda3:

The following NEW packages will be INSTALLED:

    fftw3f: 3.3.4-2      omnia
    openmm: 7.1.1-py35_0 omnia

Proceed ([y]/n)? y

ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'omnia::openmm-7.1.1-py35_0'.
PermissionError(13, 'Permission denied')
Attempting to roll back.


PermissionError(13, 'Permission denied')
```
I am installing in an Ubuntu 16.04 machine with conda 4.3.23 installed in my home directory. I had never encountered this permission issue before.

Thanks in advance.

**Comment by peastman** [comment]
I've never seen anything like that.  Is it possible that you have some files in your conda install that you don't have permission to modify?  For example, have you ever installed anything into it as a different user or using `sudo`?  That could have left behind files with a different owner.

**Comment by rcrehuet** [comment]
You were right. For some strange reason that I cannot understand nor recall, the directory:`~/anaconda3/lib/python3.5/site-packages/simtk` belong to root. I removed it and reinstalled, and everything worked fine. Thanks.
BTW, I could find the problem with `conda install -c omnia openmm -v -v ` which verbosely reports every step of the installation.

**Comment by peastman** [comment]
Glad to hear you figured it out.
