### ISSUE TITLE
Weird Jump in Solvent Positions

### ISSUE THREAD

**Issue by whitleyo** [pandegroup/openmm#1867]
Hello,

I ran a series of simulations, ramping temperature from 60 degrees to 300 degrees K for the first 5, then running another 5 simulations at 300K, then running a longer production simulation at 300K. I got a weird jump in RMSD for all atoms, but less so if I restricted RMSD calculation to C, C-alpha, and N atoms. This applied regardless of whether or not I set k (constant for restraints, see below code) to 0 or 500. Below are the RMSD plots, and following them the relevant code to running the simulations:

All Atoms, Restrictions Applied

![image](https://user-images.githubusercontent.com/25909144/28849534-6932aa38-76e5-11e7-95d8-caeb50784aad.png)

C, CA, N, Restrictions Applied

![image](https://user-images.githubusercontent.com/25909144/28849554-7c50124a-76e5-11e7-8862-d644c15cd812.png)

All atoms, no restrictions

![image](https://user-images.githubusercontent.com/25909144/28849561-880e0650-76e5-11e7-90fa-f5a93f9afae5.png)

C, CA, N, no restrictions applied 

![image](https://user-images.githubusercontent.com/25909144/28849566-8f4fbb98-76e5-11e7-8dc0-77fe7b938017.png)

Below, the relevant code. The lines under 'if __name__ == __main__' were used to generate the above plots:

def init_sim(prmtop, inpcrd, output_xml_name = 'init_sim.xml'):
    

    prmtop = AmberPrmtopFile(prmtop)
    inpcrd = AmberInpcrdFile(inpcrd)
    system = prmtop.createSystem(nonbondedMethod=PME, nonbondedCutoff=1*nanometer,
            constraints=HBonds)
    
    integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
    simulation = Simulation(prmtop.topology, system, integrator)
    simulation.context.setPositions(inpcrd.positions)
    
    if inpcrd.boxVectors is not None:
        simulation.context.setPeriodicBoxVectors(*inpcrd.boxVectors)
    simulation.minimizeEnergy()
    simulation.saveState(output_xml_name)

def run_sim(prmtop,input_xml, nstep = 20000, temp = 300, k = 0.0, output_name = 'output.pdb'):
    prmtop = AmberPrmtopFile(prmtop)
    system = prmtop.createSystem(nonbondedMethod=PME, nonbondedCutoff=1*nanometer,
            constraints=HBonds)
    
    force = openmm.CustomExternalForce("k*((x-x0)^2+(y-y0)^2+(z-z0)^2)")
    force.addGlobalParameter("k", k*kilocalories_per_mole/angstroms**2)
    force.addPerParticleParameter("x0")
    force.addPerParticleParameter("y0")
    force.addPerParticleParameter("z0")
    
    integrator = LangevinIntegrator(temp*kelvin, 1/picosecond, 0.002*picoseconds)
    simulation = Simulation(prmtop.topology, system, integrator)
    simulation.loadState(input_xml)
    state = simulation.context.getState(getPositions = True)
    
    for i,atom in enumerate(prmtop.topology.atoms()):
        if atom.name in ('CA', 'C', 'N'):
            force.addParticle(i,state.getPositions()[i])
    simulation.system.addForce(force)
    
    simulation.reporters.append(PDBReporter(output_name, 1000))
    simulation.reporters.append(StateDataReporter(stdout, 1000, step=True,
            potentialEnergy=True, temperature=True))
    simulation.step(nstep)

    simulation.saveState(output_name[0:-4] + '.xml')
    
def equilibrate(prmtop, #amber prmtop file
                input_xml, #xml that will be used to load coordinates and velocities of simulation,
                output_prefix,
                nstage, 
                total_steps, 
                ramp_temp = False, 
                t0 = 0, 
                tf = 300, 
                ramp_restraints = False, 
                k0 = 0, #initial constant for restraints, in units kcal/(mol*A^2). Unused if ramp_restrains = False
                kf = 500): #Final constnant for restraints, in same units. Used for entire protocol if ramp_restraints = False
                        #generally, if restraints are ramped, it is suggested that k0 > kf
    
    if total_steps%nstage > 0:
        
        raise ValueError('total_steps must be divisible by nstage')
        
    if ramp_temp == True:
        
        temp = t0
        
    elif ramp_temp == False:
        
        temp = tf
        
    else:
        
        raise ValueError('ramp_temp must be specified as True or False, in boolean type')
        
    if ramp_restraints == True:
        
        k = k0
        
    elif ramp_restraints == False:
        
        k = kf
        
    else:
        
        raise ValueError('ramp_restraints must be specified as True or False, in boolean type')
        
    dTemp = (tf-temp)/nstage #this value will be added to temperature during each iteration
                            #if ramp_temp = False, since t = tf, this will be 0
    
    dK = (kf-k)/nstage #this value will be added to the restraint constant k during each
                        # iteration. if ramp_restraints = False, since k = kf,
                        #this value will be 0
                        
    step_per_stage = total_steps/nstage #steps run per stage of equilibration
    
    for i in range(nstage):
        
        if i == 0:
            input_xml = init_xml
            
        else:
            input_xml = eq_name[0:-4] + '.xml'
        
        temp = temp + dTemp #adjust temperature for next simulation
        k = k + dK #do the same for restraints
        
        eq_name = output_prefix + '_equil' + str(i+1) + '.pdb'
        run_sim(prmtop, input_xml, temp = temp, k = k, output_name = eq_name, nstep = step_per_stage)
        
    out_xml_name = eq_name[0:-4] + '.xml'
    return(out_xml_name)

if __name__ == '__main__':

    folder = '/home/kimlab2/owenwhitley/amber_projects/test_ext_openmm'
    os.chdir(folder)
    prmtop = os.path.join(folder,'test_ext_openmm_testrun_1.prmtop')
    inpcrd = os.path.join(folder, 'test_ext_openmm_testrun_1.inpcrd')
    output_1 = os.path.join(folder,'output2_300k.pdb')
    init_xml = os.path.join(folder,'test_omm_init_sim.xml')
    init_sim(prmtop,inpcrd,init_xml)
    heat_solv_prefix = 'test_omm_heat_solv'
    heat_solv_xml = equilibrate(prmtop, init_xml, heat_solv_prefix, nstage = 5, total_steps = 50000, ramp_temp = True, kf = 0)
    heat_sys_prefix = 'test_omm_heat_sys'
    heat_sys_xml = equilibrate(prmtop, heat_solv_xml, heat_sys_prefix, nstage = 5, total_steps = 50000, ramp_temp = False, ramp_restraints = False, k0 = 0, kf = 0)
    run_sim(prmtop, heat_sys_xml, nstep = 50000, output_name = 'test_omm_prod.pdb')

**Comment by peastman** [comment]
> force = openmm.CustomExternalForce("k*((x-x0)^2+(y-y0)^2+(z-z0)^2)")

I think that's your problem.  Try changing it to

```Python
force = openmm.CustomExternalForce("k*periodicdistance(x, y, z, x0, y0, z0)^2")
```

See the discussion at http://docs.openmm.org/7.1.0/api-c++/generated/OpenMM.CustomExternalForce.html#_CPPv2N6OpenMM19CustomExternalForceE for more details.

**Comment by whitleyo** [comment]
I found the bug:

for i in range(nstage):
    
    if i == 0:
        input_xml = init_xml
        
    else:
        input_xml = eq_name[0:-4] + '.xml'
    
    temp = temp + dTemp #adjust temperature for next simulation
    k = k + dK #do the same for restraints

init_xml should be input_xml, and on the left and side input_xml should be given another name that gets passed to run_sim(), as the input_xml argument. My bad.

**Comment by peastman** [comment]
Ok, glad you found it!
