### ISSUE TITLE
CUDA 9.0 release candidate is out

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1869]
https://developer.nvidia.com/cuda-release-candidate-download

We should create a new tagged version of the https://github.com/omnia-md/omnia-linux-anvil and start testing OpenMM against this version.

Note that I think we still have some sort of huge slowdown in our new `omnia-linux-anvil` `clang`-compiled conda `openmm` `dev` label packages that we haven't tracked down yet.

**Comment by jchodera** [comment]
In preparation for the upcoming OpenMM 7.2 release with CUDA 9.0, OpenMM conda `dev` builds are now being built with the new [`omnia-linux-anvil:texlive-amd30-cuda90`](https://hub.docker.com/r/jchodera/omnia-linux-anvil/tags/) docker image:
```bash
conda remove --yes openmm
conda clean -pltis --yes
conda install --yes -c omnia/label/dev openmm
```
Please test!

Note that we had to upgrade to TeXLive 2017.

**Comment by peastman** [comment]
It's not directly related to CUDA 9.0, but the above build seems to have something wrong with the CPU platform.  It's getting terrible performance:

```
$ python benchmark.py --platform=CPU --seconds=30
Platform: CPU

Test: gbsa
Step Size: 2 fs
Integrated 72 steps in 28.9038 seconds
0.430448 ns/day

Test: rf
Step Size: 2 fs
Integrated 151 steps in 28.5267 seconds
0.914678 ns/day

Test: pme (cutoff=0.9)
Step Size: 2 fs
Integrated 93 steps in 28.14 seconds
0.571087 ns/day
```

Compiling myself from source, all those times are >10x faster.

@Lnaden

**Comment by Lnaden** [comment]
Do we happen to have a dev build pre-CUDA 9.0 to compare to? The only change made to the dev build should have been the CUDA target. Otherwise we might have to go back and manually figure out when the builds started having performance issues. Might have also been something changed on the travis build machine or the conda-downloaded compiler version.

**Comment by jchodera** [comment]
@lnaden: I'm pretty sure this problem has been present since we switched to the omnia-linux-anvil build system. We simply never bothered to check the CPU performance after that change.

**Comment by jchodera** [comment]
I think I changed the CMAKE_BUILD_TYPE to Debug recently:
https://github.com/omnia-md/conda-dev-recipes/blob/master/openmm/build.sh

Could this affect the compiler flags used for optimization?

**Comment by jchodera** [comment]
One issue pointed out to me recently is that docker images appear to be "noarch" when queried for their architecture type. If the compiler is automatically checking to see whether some vector instruction set is available, it may not think any are available and compile unvectorized code. We can feed it flags to force it to compile vectorized code, but we'd have to pick the architecture.

**Comment by peastman** [comment]
> I think I changed the CMAKE_BUILD_TYPE to Debug recently:

That would definitely explain it!  Debug builds have all optimizations turned off.

> One issue pointed out to me recently is that docker images appear to be "noarch" when queried for their architecture type.

That shouldn't be an issue.  The build scripts don't care what processor you're building on.

**Comment by Lnaden** [comment]
I wonder if we could find a way to build and push both versions as part of the `dev` repo. Maybe build one under the `dev` label and the other under a new `debug` label?

**Comment by jchodera** [comment]
Definitely possible, but likely unnecessary. The `Debug` build was just an attempt to help track down the segfaults that were fixed in https://github.com/pandegroup/openmm/pull/1882

**Comment by jchodera** [comment]
Updated as `Release` build:
https://anaconda.org/omnia/openmm/files

Please re-test!

**Comment by peastman** [comment]
I just retested, but it's still just as slow.  I installed it with `conda install -c omnia/label/dev openmm`.  Should that be the correct version?  I also did this check:

```
$ file ~/miniconda3/envs/test/lib/libOpenMM.so 
/home/peastman/miniconda3/envs/test/lib/libOpenMM.so: ELF 64-bit LSB  shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=3cda8ce1e05fa596047ae87b569166a318e3246b, not stripped
```

I think (but I'm not certain) that "not stripped" means it's a debug build.

**Comment by jchodera** [comment]
Did you uninstall first?
```
conda remove --yes openmm
conda clean -pltis --yes
conda install -c omnia/label/dev openmm
```

**Comment by peastman** [comment]
What speeds do you get when you run the same test with it?

**Comment by jchodera** [comment]
Ah, OK. I think I've been seeing slow CPU performance since we updated to `omnia-linux-anvil`.

@Lnaden : Can you dig into this?

**Comment by Lnaden** [comment]
Yes, but I have no eta on when I will have anything concrete. I just don't know what would have changed since we set all the compiler flags on the build, not the image.

**Comment by peastman** [comment]
Is the build log available?  That might give a clue.

**Comment by Lnaden** [comment]
Sure, https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/282500308, this was built early enough ago that its available still and not lost in the sea of nightly attempts

**Comment by Lnaden** [comment]
We do compile this with the GCC `-g` flag, but that has been in place for 7 months now, just under 2 months before we switched to the new docker image.

Change was made here: https://github.com/omnia-md/conda-dev-recipes/pull/82

**Comment by peastman** [comment]
Probably not related, but you really shouldn't be setting CFLAGS or CXXFLAGS.  The only thing you should set is CMAKE_BUILD_TYPE.  All the flags will automatically get set correctly based on that.

**Comment by peastman** [comment]
I bet this line is your problem:

```
CMAKE_FLAGS+=' -DCMAKE_CXX_FLAGS_RELEASE=-I/usr/include/nvidia/'
```

The default value for `CMAKE_CXX_FLAGS_RELEASE` is `-O3 -DNDEBUG`.  But you just overwrote that, thus throwing out the `-O3` flag.  There's no need for you to set that property.  It will automatically locate the CUDA headers based on `CUDA_TOOLKIT_INCLUDE`.  And you don't need to specify *that* either.  You only need to set a single property to tell it where CUDA is installed, and it will automatically locate all the subdirectories and libraries based on that.

**Comment by Lnaden** [comment]
Ah, thanks. So we can remove all of the `-DCUDA_...` entries from the `CMAKE_FLAGS` except for the single `CMAKE_FLAGS+=" -DCUDA_TOOLKIT_ROOT_DIR=${CUDA_PATH}/"`, or do we still need to also set the CMAKE_FLAGS+=" -DCUDA_SDK_ROOT_DIR=${CUDA_PATH}/"?

**Comment by peastman** [comment]
I believe `CUDA_TOOLKIT_ROOT_DIR` is the only one you need to set.

**Comment by Lnaden** [comment]
Great, I'll update that now and let you know once its built. 

A side note, the main release of OpenMM on conda [is also setup that way](https://github.com/omnia-md/conda-recipes/blob/027206845515bd2d840684ddc35509f46ffd1ba7/openmm/build.sh), so it probably also has the speed problem.

**Comment by peastman** [comment]
Eek!  Let's fix that asap.

**Comment by Lnaden** [comment]
Once we confirm this fix works, we can fix that. We'll have to trigger a new conda-build (easy enough), but that does mean there will technically be two "versions" of 7.1.1 on the anaconda cloud, if thats acceptable.

**Comment by Lnaden** [comment]
I'll prep the PR in anticipation

**Comment by peastman** [comment]
We can update the build number, so conda will know to install the newer one.

**Comment by jchodera** [comment]
That's odd, since @peastman tested [the openmm 7.1 conda package and found identical CPU performance](https://github.com/pandegroup/openmm/issues/1718#issuecomment-277843717).

**Comment by Lnaden** [comment]
Yup! PR on the main channel is open, if the changes to the dev builds work, then we can merge in main channel as well.

**Comment by peastman** [comment]
It looks like you're right.  I just tested the 7.1.1 build:

```
Platform: CPU

Test: gbsa
Step Size: 2 fs
Integrated 1505 steps in 29.282 seconds
8.88135 ns/day

Test: rf
Step Size: 2 fs
Integrated 2340 steps in 30.1166 seconds
13.4262 ns/day

Test: pme (cutoff=0.9)
Step Size: 2 fs
Integrated 1726 steps in 28.9375 seconds
10.3068 ns/day
```

So the problem was introduced sometime after 7.1.1 was built.

**Comment by Lnaden** [comment]
Whelp, back to the drawing board. Still helpful not to have the redundant flags. I'll hold of on merging the conda-recipes PR I have open for now.

**Comment by Lnaden** [comment]
From what I can see, the 7.1.1 build was actually cut right before we switched the docker images. Also, all the extra `CMAKE` have been around for a couple years. But my local testing is showing a speed up by removing the flags. I'm not quite sure why this is, given this problem should have shown up earlier. @peastman could you try with the newly minted version:

`python benchmark.py --platform=CPU --seconds=30`

### old dev build
```
Test: gbsa
Step Size: 2 fs
Integrated 20 steps in 45.8228 seconds
0.075421 ns/day

Test: rf
Step Size: 2 fs
Integrated 20 steps in 19.9216 seconds
0.17348 ns/day

Test: pme (cutoff=0.9)
Step Size: 2 fs
Integrated 20 steps in 26.9517 seconds
0.128229 ns/day
```

### new dev build
```
Test: gbsa
Step Size: 2 fs
Integrated 206 steps in 27.8724 seconds
1.27714 ns/day

Test: rf
Step Size: 2 fs
Integrated 356 steps in 27.7272 seconds
2.21864 ns/day

Test: pme (cutoff=0.9)
Step Size: 2 fs
Integrated 250 steps in 28.4347 seconds
1.51927 ns/day
```

**Comment by Lnaden** [comment]
I also have the complete set of compiler flags on a system with no GPU drivers, if it helps you find something I don't see, I cut down the OpenMM specifics like build version and include directories (this is for the new dev version)
```
/root/miniconda3/bin/clang++   
-DOPENMM_BUILD_VERSION= {version info} 
-DOpenMM_EXPORTS {all the openmm exports}
--gcc-toolchain=/opt/rh/devtoolset-2/root/usr/ 
-O3 
-DNDEBUG 
-fPIC   
-msse2 
-DLEPTON_USE_JIT 
-DOPENMM_BUILDING_SHARED_LIBRARY 
-DLEPTON_BUILDING_SHARED_LIBRARY 
-DPTHREAD_BUILDING_SHARED_LIBRARY 
-std=gnu++11
```

**Comment by peastman** [comment]
Much better!

```
Test: gbsa
Step Size: 2 fs
Integrated 1485 steps in 29.0168 seconds
8.84344 ns/day

Test: rf
Step Size: 2 fs
Integrated 2303 steps in 30.2987 seconds
13.1345 ns/day

Test: pme (cutoff=0.9)
Step Size: 2 fs
Integrated 1785 steps in 29.5569 seconds
10.4358 ns/day
```

**Comment by Lnaden** [comment]
Great! I don't know why the flags were seemingly ignored on the old Docker image, but this does mean we don't have to trigger a new build on the Release version for 7.1.1. 

I'll go ahead and tweak the PR on the `conda-recipes` repo to replace the flags but not re-build if theses speeds are acceptable.

**Comment by peastman** [comment]
Sounds good.  The speed of this build is very similar to what I get when compiling myself.

**Comment by Lnaden** [comment]
Changes merged on the main `conda-recipes` channel as well.

**Comment by jchodera** [comment]
Thanks for wrapping this up!
