### ISSUE TITLE
Context.getParameters() should return a dict in Python

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1874]
It looks like [`Context.getParameters()`](http://docs.openmm.org/7.1.0/api-python/generated/simtk.openmm.openmm.Context.html#simtk.openmm.openmm.Context.getParameters) returns a proxy of a Swig-wrapped `map<std::string,double>` instead of a Python `dict` in Python:
```python
>>> from simtk import openmm, unit
>>> from openmmtools import testsystems
>>> t = testsystems.HarmonicOscillator()
>>> integrator = openmm.VerletIntegrator(1*unit.femtoseconds)
>>> context = openmm.Context(t.system, integrator)
>>> print(context.getParameters())
<simtk.openmm.openmm.mapstringdouble; proxy of <Swig Object of type 'std::map< std::string,double > *' at 0x10e299630> >
```
Probably just a minor oversight in the Swig [typemaps](https://github.com/pandegroup/openmm/blob/master/wrappers/python/src/swig_doxygen/swig_lib/python/typemaps.i)?

**Comment by peastman** [comment]
Is this a problem?  It's a swig class, but it still works exactly as you'd expect.

```
>>> p = context.getParameters()
>>> for x in p:
...   print(x, p[x])
... 
AndersenCollisionFrequency 1.0
AndersenTemperature 300.0
```

**Comment by peastman** [comment]
Can you confirm whether this is actually a bug?  Is there anything that works incorrectly?

**Comment by jchodera** [comment]
Apologies!

I've played with this a bit more, and it looks like it does indeed act like a `dict` despite not being a subclass of `dict` or `UserDict`. So this isn't strictly a bug---just a surprise.

**Comment by BastiaanvHoorn** [comment]
Could this information be added to the documentation of the context page? I had to end up on this github issue before figuring out how to use this function.
