### ISSUE TITLE
OpenCL invalid context error when running in separate Python process on Mac

### ISSUE THREAD

**Issue by tristanc1** [pandegroup/openmm#1886]
I've been putting together an improved interactive MD implementation that uses Python's multiprocessing module to start the simulation in a separate process and keep it out of the graphics loop. This is working really well in Linux, but on my 2016 MacBook Air on the OpenCL platform I get the error:

```
Traceback (most recent call last):
File "/Users/tic20/Library/Application Support/ChimeraX/0.1/site-packages/chimerax/isolde/openmm/sim_thread.py", line 429, in __init__
self.sim = sh.create_sim()
File "/Users/tic20/Library/Application Support/ChimeraX/0.1/site-packages/chimerax/isolde/openmm/sim_handler.py", line 547, in create_sim
self.topology, self.system, self.integrator, self.platform)
File "/Applications/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 103, in __init__
self.context = mm.Context(self.system, self.integrator, platform)
File "/Applications/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 6481, in __init__
this = _openmm.new_Context(*args)
Exception: Error initializing context: Retain Object (-34)
```

... which I believe corresponds to OpenCL's CL_INVALID_CONTEXT

Not really sure where to go from here in debugging. Some extra details: 

- I'm using the "fork" multiprocessing approach
- Running OpenMM's `benchmark.py --platform=OpenCL` from the command line using the same Python as in the GUI passes the first three tests, but fails on amoeba:

```
Test: amoebagk (epsilon=1e-05)
Step Size: 2 fs
Traceback (most recent call last):
  File "/usr/local/openmm/examples/benchmark.py", line 143, in <module>
    runOneTest(test, options)
  File "/usr/local/openmm/examples/benchmark.py", line 97, in runOneTest
    context = mm.Context(system, integ, platform, properties)
  File "/Applications/ChimeraX.app/Contents/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 6481, in __init__
    this = _openmm.new_Context(*args)
Exception: Specified a Platform for a Context which does not support all required kernels
```

... which isn't a problem for me, since my use case corresponds most closely to the gbsa benchmark.

EDIT: Oh, and the CPU platform runs fine in the threaded implementation.

**Comment by jchodera** [comment]
I haven't seen the first error before, but the second error is due to the fact that the AMOEBA kernels are only implemented for `CUDA`, not `OpenCL`.

**Comment by tristanc1** [comment]
Yeah, I didn't really think those were related.

I've made some progress in tracking down _where_ the problem arises, but I'm still mystified about _why_. 

Where: the OpenCLContext constructor, at the line:
```
context = cl::Context(contextDevices, cprops, errorCallback);
```

The weird thing is that the cl::Context constructor appears to run fine - I've logged every step through to the end, and it completes successfully with an error code of 0. Yet the OpenCLContext constructor never reaches the next line - the error is raised by the assignment operator. In cl.h, I replaced all possible occurrences of the __RELEASE_ERR string with unique strings, and this is the one that is thrown:

```
    Wrapper<cl_type>& operator = (const Wrapper<cl_type>& rhs)
    {
        if (object_ != NULL) { detail::errHandler(release(), __RELEASE_ERR); }
        object_ = rhs.object_;
        //if (object_ != NULL) { detail::errHandler(retain(), __RETAIN_ERR); }
        if (object_ != NULL) { detail::errHandler(retain(), "Retain Object Two"); }
        return *this;
    }
```

**Comment by tristanc1** [comment]
The upshot is that in these circumstances the Context is treated as invalid by everything downstream, and the reasons why are buried away in the closed-source Apple OpenCL implementation. Seems I'm going to have to find a different/better approach if I want a cross-platform threaded implementation... Feel free to close this - I'd be quite surprised if anyone else were to run into the same issue.

**Comment by jchodera** [comment]
I'd love to hear @peatman's thoughts on this---he has a Mac laptop too, I believe.

**Comment by tristanc1** [comment]
I'll try to define a simple test case to play with.

**Comment by tristanc1** [comment]
OK, while putting together the test case I ran into trouble with both Linux _and_ Mac, which ended up illuminating where the problem seems to be coming from. I thought I had been quite strict about ensuring that OpenMM proper was only ever imported into the process hosting the simulation, but it appears I have some digging to do.

What it boils down to: if the OpenCL code has been touched by the host process, the OpenCL platform becomes unavailable to the child process. On the Mac it crashes with error -34, in Linux with -5 (out of resources). The below snippet reproduces it (just provide your favourite small simulation-ready structure as input.pdb). As written it should run without a hitch, but uncommenting the do_sim() line (which runs before setting up the multiprocessing Pool) causes the thread to crash.

It seems that the Mac is a little more touchy than Linux about all this - my existing code *does* run perfectly well in Linux, getting 40-50 fps graphics while the simulation provides 20-odd coordinate updates per second. A bit of a needle-in-a-haystack search ahead to find what's triggering the Mac fail.

```
import multiprocessing as mp
from time import sleep
from simtk.openmm import app
from simtk import openmm
from simtk import unit


def do_sim():
    platform = openmm.Platform.getPlatformByName('OpenCL')
    pdb = app.PDBFile('input.pdb')
    forcefield = app.ForceField('amber99sb.xml', 'amber99_obc.xml')
    system = forcefield.createSystem(pdb.topology, nonbondedMethod=app.CutoffNonPeriodic, nonbondedCutoff=1.0*unit.nanometer, constraints=app.HBonds)
    integrator = openmm.LangevinIntegrator(300*unit.kelvin, 1/unit.picosecond, 0.002*unit.picoseconds)
    context = openmm.Context(system, integrator, platform)
    context.setPositions(pdb.positions)
    context.setVelocitiesToTemperature(300*unit.kelvin)
    context.getIntegrator().step(100)

#do_sim()
#print('single-threaded run done')



def sim_thread(queue):
    do_sim()
    queue.put('Finished')

global error
error = False

def error_cb(e):
    global error
    print(e)
    error = True

manager = mp.Manager()
out_q = manager.Queue()

error = None

p = mp.Pool(processes = 1)
p.apply_async(sim_thread, args = (out_q, ), error_callback = error_cb)
msg_count = 0
while msg_count < 1:
    if error:
        break
    if not out_q.empty():
        msg = out_q.get()
        if msg == 'Fail!':
            error = msg
            break
        print(msg)
        msg_count += 1
    sleep(1e-1)
```

**Comment by tristanc1** [comment]
The plot thickens. If the above code is in a file called `test_multiproc.py`, then on the Mac:

` /Applications/ChimeraX.app/Contents/bin/python3.6 test_multiproc.py`

runs successfully. But if I run ChimeraX, open its Python shell internally, and copy the same code in there, then I get the error:

`Error initializing context: Retain Object (-34)`

... despite the ChimeraX environment never having touched OpenMM until this point. Yet if I run again from the command line while ChimeraX is still open, it runs without error. ChimeraX is using PyOpenGL (which also appears to use PyOpenCL internally)... it would seem that the master process having any OpenCL (OpenGL?) context initialised is enough to block the forked process from accessing the GPU. 

In Linux, running a simulation in the main process also kills the ability to run in the child for the CUDA platform. Here the error is:
```
Error initializing Context: CUDA_ERROR_NOT_INITIALIZED (3) at /anaconda/conda-bld/openmm_1494334816111/work/platforms/cuda/src/CudaContext.cpp:177
```

**Comment by tristanc1** [comment]
Looks like https://stackoverflow.com/questions/22950047/cuda-initialization-error-after-fork explains the root of the problem. Looks rather painful to work around.

**Comment by peastman** [comment]
I don't think that's the same problem.  In that case, the person is trying to share a CUDA context between two processes.  But you're getting the error when creating a new context, not sharing an existing one.

But I don't have a lot of insight on what the problem actually is.  Perhaps some sort of information sharing down inside the OpenCL implementation?  When you create a subprocess with `fork()`, it shares information with the parent process.  Presumably if you were to create a fully independent process this issue wouldn't happen.

**Comment by tristanc1** [comment]
Working via a fully-independent process is something I've been trying to
avoid - not least because the Python API for that looks nightmarish! Also,
taking the approach I have lets me do all the communication with the
simulation thread via shared-memory Numpy arrays, giving me far better
performance than what is available through multiprocessing.Pipe() or
Queue(). The downside is that it only works in Unix (and, by the look of
it, possibly only Linux).

For my next iteration (sometime down the track once I have a few other
features in place) I was hoping to get my head around the C++ API and
build/run the simulation in a std::thread, but it looks like this will run
into the same issues.

**Comment by tristanc1** [comment]
Running under lldb shows the error returned is a bit misleading - there's
actually a CL_DEVICE_NOT_FOUND error thrown first.

2017-09-06 20:41:01.934483 ChimeraX[5646:204692] [CL_DEVICE_NOT_FOUND] :
OpenCL Error : Could not create GFX shared state

2017-09-06 20:41:01.934636 ChimeraX[5646:204692] [CL_INVALID_CONTEXT] :
OpenCL Error : Failed to retain context! Invalid context

2017-09-06 20:41:01.934922 ChimeraX[5646:204692] [CL_INVALID_CONTEXT] :
OpenCL Error : Failed to release context! Invalid context

2017-09-06 20:41:01.935210 ChimeraX[5646:204692] [CL_INVALID_CONTEXT] :
OpenCL Error : Failed to release context! Invalid context

In Python, after first running the simulation in the main process then
attempting to run in the pool, the error is the same:

2017-09-06 20:52:15.142109 python3.6[5844:213601] [CL_DEVICE_NOT_FOUND] :
OpenCL Error : Could not create GFX shared state

2017-09-06 20:52:15.142474 python3.6[5844:213601] [CL_INVALID_CONTEXT] :
OpenCL Error : Failed to retain context! Invalid context

2017-09-06 20:52:15.142847 python3.6[5844:213601] [CL_INVALID_CONTEXT] :
OpenCL Error : Failed to release context! Invalid context

2017-09-06 20:52:15.143495 python3.6[5844:213601] [CL_INVALID_CONTEXT] :
OpenCL Error : Failed to release context! Invalid context

A Google search for the actual error string "Could not create GFX shared
state" finds nothing.

**Comment by peastman** [comment]
I wonder if this is somehow related to the device being in some sort of exclusive mode, such that once one context has been created for it, you aren't allowed to create a second one within the same process?  I don't know anything about how that works on Macs, but it would explain the error saying the device couldn't be found.

**Comment by tristanc1** [comment]
It turns out that Python's multiprocessing module has an undocumented feature that avoids the problem entirely. `multiprocessing.pool.ThreadPool` provides an identical API to `multiprocessing.Pool` but uses threads rather than separate processes. After swapping them out, everything works just fine on the Mac (and presumably will do in Windows as well).

**Comment by tobigithub** [comment]
Just as reference, under Ubuntu LINUX and CUDA 10 and OpenCL 1.2 CUDA,
the AMOEBA kernels ( 'amoebagk', 'amoebapme') are not working as referenced above. 
CUDA is fine. 

```
python benchmark.py --test=amoebagk --platform CUDA
Platform: CUDA
Precision: single

Test: amoebagk (epsilon=1e-05)
Step Size: 2 fs
Integrated 1972 steps in 52.9472 seconds
6.43587 ns/day
```

```
python benchmark.py --test=amoebagk --platform OpenCL
Platform: OpenCL
Precision: single

Test: amoebagk (epsilon=1e-05)
Step Size: 2 fs
Traceback (most recent call last):
  File "benchmark.py", line 161, in <module>
    runOneTest(options.test, options)
  File "benchmark.py", line 111, in runOneTest
    context = mm.Context(system, integ, platform, properties)
  File "/home/anaconda3/envs/openmm/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 12231, in __init__
    this = _openmm.new_Context(*args)
Exception: Specified a Platform for a Context which does not support all required kernels
```

**Comment by peastman** [comment]
That's because the AMOEBA plugin doesn't support OpenCL, only CUDA and reference.  It's not related to this issue.
