### ISSUE TITLE
Bugfix release?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1890]
We've accumulated a few bugfixes since the last 7.1.1 bugfix release. What do folks think about releasing a 7.1.2 bugfix release with some back-ported bugfixes?

My nominations would be:
* `Context.getIntegrator` returns correct Python subclasses (#1870 #1882 #1883)
* Fix parameter derivatives with interaction groups (#1889)
* Error appending to DCD files (#1866)
* Finding identical molecules bugfix (#1881)
* CustomGBForce bugfix (#1850)
* CustomIntegrator bugfix (#1824)
* PDBxFile bonds bugfix (#1819)
* Create3DNaturalSpline bugfix (#1806 #1807)

**Comment by peastman** [comment]
This partly depends on how soon we think the new force fields will be ready.  I'm hoping we're only a few weeks away from releasing a beta of 7.2.

**Comment by jchodera** [comment]
> This partly depends on how soon we think the new force fields will be ready. I'm hoping we're only a few weeks away from releasing a beta of 7.2.

If we decouple the release of OpenMM 7.2 proper and the conda-installable `openmm-forcefields` package, we could indeed be just a few weeks away from a 7.2 beta.

I've been trying to keep the [project board](https://github.com/choderalab/openmm-forcefields/projects/1) up to date. There are still a few things in the OpenMM column, though we might bump the metal ions to 7.3 if needed.

I think the thing we're most behind on there is how we should [revamp the GBSA parameter assignment](https://github.com/choderalab/openmm-forcefields/issues/2) to handle small molecules. Since our last big discussion about this, @swails has implemented logic that does all the parameter assignment in the `app` layer, but it currently just uses this logic to throw warnings of non-optimal GBSA parameters are detected. We could use this to actually *assign* parameters to biomolecules and small molecules, but we would have to figure out how we want that to work. Alternatively, we can extend the `GBSAForce` XML syntax a bit and allow the typing logic to be encoded there.

**Comment by peastman** [comment]
> If we decouple the release of OpenMM 7.2 proper and the conda-installable openmm-forcefields package, we could indeed be just a few weeks away from a 7.2 beta.

That's reasonable.  The important things I really want to get into 7.2 are Amber14 and CHARMM36, plus the membrane builder.  Between those and the things we've already implemented (CustomCVForce, tabulated functions in CustomIntegrator, arbitrary particles for LocalCoordinatesSite, etc.), it makes for a pretty good 7.2 update.  And since `openmm-forcefields` is a separate package, we can make releases of it on its own schedule.

**Comment by peastman** [comment]
We're going straight to 7.2.
