### ISSUE TITLE
Restraints ignored?

### ISSUE THREAD

**Issue by stefdoerr** [pandegroup/openmm#1894]
I tried to restrain groups of atoms in my simulation with different constants with the following code:
(I can probably do it with a single force and per-particle k value. But it shouldn't matter for this discussion)

```python
pdb = app.PDBFile(os.path.join(build, 'structure.pdb'))
forcefield = app.ForceField('amber99sbildn.xml', 'amber99_obc.xml')

system = forcefield.createSystem(pdb.topology, constraints=app.HBonds, rigidWater=True,
                                 ewaldErrorTolerance=0.0005)

for atoms, restraint in groups:
    force = mm.CustomExternalForce("k*((x-x0)^2+(y-y0)^2+(z-z0)^2)")
    force.addGlobalParameter("k", restraint)
    force.addPerParticleParameter("x0")
    force.addPerParticleParameter("y0")
    force.addPerParticleParameter("z0")
    for a in atoms:
        force.addParticle(int(a), coords[a].value_in_unit(unit.nanometer))
    system.addForce(force)

platform, prop = getPlatform(platform, device)
integrator = mm.LangevinIntegrator(300 * unit.kelvin, 1.0 / unit.picoseconds, 2.0 * unit.femtoseconds)
simulation = app.Simulation(pdb.topology, system, integrator, platform, prop)
simulation.context.setPositions(pdb.positions)

simulation.minimizeEnergy(tolerance=minimizetol * unit.kilojoule / unit.mole, maxIterations=iterations)
state = simulation.context.getState(getPositions=True)
```

However my atoms keep on moving. Does minimize not respect custom forces? 
I even put an insanely high constant to see if it would help.

I am probably doing something stupid here.

```pytb
In [10]: ff = system.getForces()[-1]

In [12]: ff.getGlobalParameterDefaultValue(0)
Out[12]: 10000000.0
In [16]: ff.getParticleParameters(0)
Out[16]: [57, (-1.2582000000000002, 0.14550000000000002, 1.9055)]
In [23]: bmol.coords[57]  # Starting coordinates
Out[23]: 
array([[-12.58199978],
       [  1.45500004],
       [ 19.05500031]], dtype=float32)

In [24]: cmol.coords[57]  # Coordinates after minimization
Out[24]: 
array([[-12.61516953],
       [  1.50716925],
       [ 18.99417877]], dtype=float32)

```

**Comment by stefdoerr** [comment]
Oh wait, if I make it a single force with per-particle k value it works!
Is my assumption then correct that Forces share same-named global parameters (and I was overwriting it)?

**Comment by jchodera** [comment]
> Is my assumption then correct that Forces share same-named global parameters (and I was overwriting it)?

All `Custom*Force` objects share the same global parameter namespace, so if you define the same global parameter name for two such forces, they will share the same global context parameter.

**Comment by stefdoerr** [comment]
Ok great thanks! I thought global meant "between all atoms in that force"

**Comment by Lnaden** [comment]
Its also worth noting that `Context`'s `Custom*Force` global variables are passed up to a `CustomIntegrator` as global variables available to the integrator.* Helpful fact if you want to adjust global parameters as part of the integrator.

*if you are using a `CustomIntegrator`
