### ISSUE TITLE
Pickled States drop parameters data

### ISSUE THREAD

**Issue by salotz** [pandegroup/openmm#1899]
It appears that when you pickle a state it loses the parameters data. Basically I run:
```
     state = simulation.context.getState(getPositions=True,
                                                  getVelocities=True,
                                                  getParameters=True,
                                                  getForces=True,
                                                  getEnergy=True,
                                                  getParameterDerivatives=True)

```
For example this has an Andersen thermostat with two parameters which I can access with `state.getParameters()`.

    pickle.dump(state, wf)

and when I load it back `state.getParameters()` returns an empty dict. Everything else seems to be fine although I haven't tested parameter derivatives because I don't actually know how to make a test case that has them.

**Comment by peastman** [comment]
Which version of OpenMM are you using?  Is it a release, or did you build from the code in the repository?  The latest development code has completely changed how the Python API for State is implemented.

**Comment by salotz** [comment]
Release 7.1.1, just using omnia conda repo

**Comment by peastman** [comment]
Could you try with the current code from the repository?  I'm pretty sure that problem no longer exists.

**Comment by jchodera** [comment]
You can install from the 'omnia/label/dev' channel to test the current version.

**Comment by salotz** [comment]
Pickled states work on the 'omnia/label/dev'. When will this be released?
