### ISSUE TITLE
Assigning 1-4 interaction scale factor for CustomNonbondedForce

### ISSUE THREAD

**Issue by leelasd** [pandegroup/openmm#1901]
Hi,

I am trying to figure out how I can scale 1-4 interaction for custom nonbonded force. I tried doing bondcutoff=3 in the XML file. But this completely excluded the 1,4 interactions. 
Is there any other way  I can scale the 1,4 interactions of a custom nonbonded force?

Any suggestions are appreciated !!

**Comment by peastman** [comment]
CustomNonbondedForce doesn't have any special handling of 1-4 interactions.  If you want them to be computed differently, the normal way to do that is to exclude them from the nonbonded force, then add a CustomBondForce to compute the 1-4 pairs in whatever way you want.

**Comment by leelasd** [comment]
Ok Thanks, @peastman I will use that strategy.

**Comment by hjuinj** [comment]
Am I right in thinking currently OpenMM does not have an API that can directly return me all atom pairs separated by 3 bonds?

I should instead translate and modify the C++ code written for [createExceptionsFromBonds](https://github.com/pandegroup/openmm/blob/111844a2c2d9645e8c305f6cf916c45c0650d7d2/openmmapi/src/NonbondedForce.cpp#L207) for my purpose?

**Comment by peastman** [comment]
That depends on the context.  For example, if you're doing this within a force field, just take the list of proper torsions.  The first and last atoms in each one are separated by three bonds.

Then there's the approach used by `LennardJonesGenerator`.  It creates a clone of the `CustomNonbondedForce`.  It calls `createExclusionsFromBonds()` on each one, setting a cutoff of two bonds on one and three bonds on the other.  The difference between those sets is the ones separated by exactly three bonds.  See https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py#L2453-L2479.

**Comment by hjuinj** [comment]
Is the most handy way of identifying proper torsions from my PeriodicTorsionForce  by seeing if the first and third element returned from `getTorsionParameters` is connected?

**Comment by hjuinj** [comment]
I am getting some odd behaviour when using CustomBondForce for 1,4 interaction and I am wondering if you could please take a look at my code?

Basically I want to separate out my LJ and electrostatic contributions for my solute. I am going to illustrate the issue with the LJ part below.

I start by reading in the parameters from amber .prmtop file and then creating the LJ potential via CustomNonbondedForce with sufficiently large `r_cutoff` value (1 nm):
```python
V_lj = """4*epsilon*(((sigma/r)^6)^2 - (sigma/r)^6);
        epsilon = sqrt(epsilon1 * epsilon2);
        sigma = 0.5*(sigma1+sigma2)
""" 

total_lj = CustomNonbondedForce(V_lj)
total_lj.setNonbondedMethod(NonbondedForce.CutoffPeriodic)
total_lj.setCutoffDistance(r_cutoff)
total_lj.addPerParticleParameter('sigma')
total_lj.addPerParticleParameter('epsilon')

for particle in range(nonbonded_force.getNumParticles()):
    [charge, sigma, epsilon] = nonbonded_force.getParticleParameters(particle)
    total_lj.addParticle([sigma, epsilon])
total_lj.addInteractionGroup(solute_atoms, solute_atoms)

```
Here I set  bond separation in `createExclusionsFromBonds` to 2
```python
total_lj.createExclusionsFromBonds([(i[0].index, i[1].index) for i in topology.bonds()], 2)
```


In comparison, as a test, if I implement with the same expression in CustomNonbondedForce but setting bond separation to 3. Then, I create the 1-4 interaction via CustomBondForce (code below), my LJ term grows to a positive value two orders of magnitude bigger than the value I obtained before.

Assuming I have correctly gathered all solute atom pairs separated by three bonds and stored in `one_four_pairs`(no duplicates), could you see any obvious mistakes  below that could lead to this?

```python
V_14_lj = "4*epsilon*(((sigma/r)^6)^2 - (sigma/r)^6)" 

total_lj = CustomBondForce(V_14_lj)
total_lj.addPerBondParameter('sigma')
total_lj.addPerBondParameter('epsilon')

for atom_pair in one_four_pairs:
    charge1, sigma1, epsilon1 = nonbonded_force.getParticleParameters(atom_pair[0])
    charge2, sigma2, epsilon2 = nonbonded_force.getParticleParameters(atom_pair[1])
 
    sigma = 0.5*(sigma1+sigma2)
    epsilon = (epsilon1 * epsilon2).sqrt()

    total_lj.addBond(atom_pair[0], atom_pair[1], [sigma.value_in_unit_system(md_unit_system), epsilon.value_in_unit_system(md_unit_system)])

system.addForce(total_lj)
```


---

Another questions I have about the `CustomBondForce` is apparently `usesPeriodicBoundaryConditions` is always false, would this impact things when I simulate under PBC?

**Comment by peastman** [comment]
I don't see anything obviously wrong, though I'd suggest a few minor simplifications (noted below).  What is the odd behavior you're seeing?  If in doubt, try using a standard force field with a standard NonbondedForce.  You can then loop over the exceptions that were added to that force, compare them to what your code creates, and identify where the two differ from each other.

> V_14_lj = "4\*epsilon\*(((sigma/r)^6)^2 - (sigma/r)^6)" 

I would make that

```
V_14_lj = "4*epsilon*((sigma/r)^12 - (sigma/r)^6)" 
```

You're trying to manually optimize the expression, but actually you're just going to get in the way of the force's ability to optimize it.

>     total_lj.addBond(atom_pair[0], atom_pair[1], [sigma.value_in_unit_system(md_unit_system), epsilon.value_in_unit_system(md_unit_system)])

That can just be `[sigma, epsilon]`.  It will convert the arguments to the proper units automatically.

**Comment by hjuinj** [comment]
Thank you Peter for the very helpful advice which let me find my error (at least one of them). 

I took your suggestion above of identifying the 1-4 interaction pairs from the proper torsions in the forcefield. But it turns out this would over-count in certain cases. For example when I have a five membered ring, say the atoms are indexed 0 through 4. Then I will find a torsion term for atom pairs indexed (0,3) via 0-1-2-3. However, this will not be included as a 1-4 exception since I can go via 0-4-3. 

So I guess I will need to filter all the 1-4 pairs obtained from the `torsion force` with atom pairs from the first and last index obtained from the `angle force` .

Or I guess if I am starting with a forcefield with 1-4 interactions treated specially, I can just loop through all the exceptions in the `nonbondedforce` and those exceptions with charge, sigma and epsilon all being non-zero would be the 1-4 exceptions, right?

**Comment by peastman** [comment]
That might sometimes produce the wrong result.  For example, if an atom happens to actually have charge 0, then 1-4 interactions involving it will have their charge product as 0.  If you really want to be sure you're getting the right set of terms, I follow what LennardJonesGenerator does: clone the force and call `createExclusionsFromBonds()` on it with a smaller cutoff.

**Comment by hjuinj** [comment]
Thank you, I will try the LennardJonesGenerator way. 
Could you see any glitches with the method of getting all the terminal atom pairs from the proper torsion force into a set and filter the set with terminal atom pairs from the angle force?

**Comment by peastman** [comment]
That could still fail in certain cases.  For example, think of a loop of four atoms:

```
A-D
| |
B-C
```

It will identify a torsion A-B-C-D, so you would incorrectly mark A-D as being a 1-4 pair.
