### ISSUE TITLE
Unnecessary calculation in CpuLangevinDynamics

### ISSUE THREAD

**Issue by stefdoerr** [pandegroup/openmm#1902]
Just skimming through some code I saw that sqrtInvMass not being used

https://github.com/pandegroup/openmm/blob/8469621fae417559589ab0ef69bb9017459895c0/platforms/cpu/src/CpuLangevinDynamics.cpp#L115

**Comment by stefdoerr** [comment]
Although I guess it's not "unnecessary calculation" since it will be cut out by the compiler. Sorry for the wrong title

**Comment by peastman** [comment]
Thanks for pointing that out!  If you'd like to send a PR removing it, that would be great.  As you say, though, the compiler will already remove it.  So it doesn't affect the performance, it just makes the code a little more complicated.
