### ISSUE TITLE
Combining amber ligand parameters with OpenMM forcefields

### ISSUE THREAD

**Issue by stefdoerr** [pandegroup/openmm#1905]
Ok sorry for this since it might be an obvious question but I'm a bit stumped here.
I have a protein ligand system and parameters for the ligand in `frcmod` and topology in `prepi` format. I want to simulate it with `forcefield = app.ForceField('amber99sbildn.xml', 'amber99_obc.xml')` OpenMM forcefield.

ForceField class can only read ffxml so I guess I have to use parmed.
I can read it with `parmed.amber.AmberParameterSet` but then I have no clue how to combine these parameters with the rest of the ForceField to simulate my protein-ligand system.

**Comment by jchodera** [comment]
> I have a protein ligand system and parameters for the ligand in frcmod and topology in prepi format. 

Where did these come from? Did you generate them with some tools from AmberTools? That'll help us suggest a solution that is most convenient for you, since there are many possible solutions.

**Comment by stefdoerr** [comment]
Hm I have no idea in this specific case. It must have come from antechamber since it's quite old. But generally out parametrization procedure will either produce `prm/rtf` or `frcmod/prepi` pairs for parametrized ligands.

**Comment by jchodera** [comment]
If you have access to AmberTools (which is conda-installable) and can use LEaP to set up your systems, you can use the [Amber readers in `simtk.openmm.app`](http://docs.openmm.org/latest/userguide/application.html#using-amber-files) to create your system. LEaP can natively read all of those formats.

Alternatively, you can use `parmed` to convert the `frcmod` parameters to `ffxml`, and this should work alongside the existing `ffxml` files with a conversion of `gaff.prm` to `gaff.xml` (also by parmed).

There are a bunch of other possible solutions too, but they're likely more difficult. If you can find out more about where you plan to get your `prm/rtf` and `frcmod/prepi` files in the future, we might be able to simplify this process by writing out a slightly different format.

**Comment by stefdoerr** [comment]
Yes I considered the first solution but I really preferred to avoid using LEaP to build the system.

Oh I don't know how I missed this [from_parameterset](https://parmed.github.io/ParmEd/html/api/parmed/parmed.openmm.parameters.html#parmed.openmm.parameters.OpenMMParameterSet.from_parameterset). That plus the write should do the conversion. 

For the third point as I said it's an in-house parametrization which we will make public eventually. You suggest implementing a ffxml writer in our pamatetrizer? Would not be a bad idea if it's easy actually.

**Comment by stefdoerr** [comment]
Okay, I guess I closed this issue a bit too fast. Actually it might be more of a parmed question so if you dont know how to do it I can move over to their issue tracker. Or rather I'll ping @swails 

I managed to convert the parameters from frcmod to xml like this.

```python
benprm = parmed.amber.AmberParameterSet('benzamidine.frcmod')
benprm_omm = parmed.openmm.parameters.OpenMMParameterSet.from_parameterset(benprm)
benprm_omm.write('benzamidine.frcmod.xml')
```
which gave me a xml file containing this 
```xml
<ForceField>
    <HarmonicAngleForce>
        <Angle type1="nh" type2="ce" type3="nh" angle="1.9673351328480082" k="623.08128"/>
    </HarmonicAngleForce>
    <PeriodicTorsionForce>
        <Proper type1="ca" type2="ce" type3="nh" type4="hn" periodicity1="2" phase1="3.141592653589793"
                k1="2.8242000000000003"/>
        <Proper type1="ca" type2="ca" type3="ce" type4="nh" periodicity1="2" phase1="3.141592653589793"
                k1="27.823600000000003"/>
        <Proper type1="nh" type2="ce" type3="nh" type4="hn" periodicity1="2" phase1="3.141592653589793"
                k1="2.8242000000000003"/>
        <Improper type1="ca" type2="ca" type3="ca" type4="ce" periodicity1="2" phase1="3.141592653589793" k1="4.6024"/>
        <Improper type1="ca" type2="ca" type3="ca" type4="ha" periodicity1="2" phase1="3.141592653589793" k1="4.6024"/>
        <Improper type1="ce" type2="ca" type3="nh" type4="nh" periodicity1="2" phase1="3.141592653589793" k1="4.6024"/>
        <Improper type1="nh" type2="ce" type3="hn" type4="hn" periodicity1="2" phase1="3.141592653589793" k1="4.6024"/>
    </PeriodicTorsionForce>
</ForceField>
```

But I am obviously still missing in my xml:

1. Atom types (stored in prepi and mol2)
1. LJ parameters (stored in the prepi)
2. Charges (stored in the prepi)
3. Topology (stored in the prepi and the mol2)

I tried to read the prepi file with parmed but to no success (couldnt find any method for it and abusing AmberParm complained about not being able to parse it). I tried reading the `mol2` and writing at least the topology and atom types but parmed loads it into a `Structure` object which [I have not found a way](https://parmed.github.io/ParmEd/html/readwrite.html#writing-files-with-structure-save) to write into `xml` format.

I can convert the `Structure` to `OpenMMParameterSet` with [from_structure()](https://parmed.github.io/ParmEd/html/api/parmed/parmed.openmm.html#parmed.openmm.OpenMMParameterSet.from_structure) but then it obviously only writes the parameters of the mol2 (which there are none) and doesn't write the topology.

I also considered @jchodera suggestion to build with tleap but I could not find the OBC forcefield in the official AMBER files.

So to summarize, I have not found a way yet to convert a `frcmod`/`prepi` combo to something I can use to simulate the ligand in OpenMM. I will write my own topology XML writer for HTMD since that is quite easy and eventually we will also modify our parametrization protocol to spit out XMLs but for the moment I don't see a way of simulating my ligand in Amber99 OBC forcefield.

In the end I wrote the fake xml file below by hand to see if it would run and indeed it ran (with bullshit results obviously).
```xml
<ForceField>
    <Info>
        <DateGenerated>2017-09-22</DateGenerated>
    </Info>
    <AtomTypes>
        <Type name="ca" class="ca" element="C" mass="0.0"/>
        <Type name="ce" class="ce" element="C" mass="0.0"/>
        <Type name="ha" class="ha" element="H" mass="0.0"/>
        <Type name="nh" class="nh" element="N" mass="0.0"/>
        <Type name="hn" class="hn" element="H" mass="0.0"/>
    </AtomTypes>
    <GBSAOBCForce>
        <Atom type="ca" charge="-0.4157" radius="0.1706" scale="0.79"/>
        <Atom type="ce" charge="0.2719" radius="0.115" scale="0.85"/>
        <Atom type="ha" charge="0.0337" radius="0.19" scale="0.72"/>
        <Atom type="nh" charge="0.0823" radius="0.125" scale="0.85"/>
        <Atom type="hn" charge="-0.1825" radius="0.19" scale="0.72"/>
    </GBSAOBCForce>
    <NonbondedForce coulomb14scale="0.833333" lj14scale="0.5">
        <Atom type="ca" charge='0.149000' sigma="1.0" epsilon="0.0"/>
        <Atom type="ce" charge='0.149000' sigma="1.0" epsilon="0.0"/>
        <Atom type="ha" charge='0.149000' sigma="1.0" epsilon="0.0"/>
        <Atom type="nh" charge='0.149000' sigma="1.0" epsilon="0.0"/>
        <Atom type="hn" charge='0.149000' sigma="1.0" epsilon="0.0"/>
    </NonbondedForce>
    <Residues>
        <Residue name="MOL">
            <Atom name="C" type="ca"/>
            <Atom name="C2" type="ca"/>
            <Atom name="C3" type="ca"/>
            <Atom name="C4" type="ca"/>
            <Atom name="C5" type="ca"/>
            <Atom name="C6" type="ca"/>
            <Atom name="C7" type="ce"/>
            <Atom name="H" type="ha"/>
            <Atom name="H9" type="ha"/>
            <Atom name="H10" type="ha"/>
            <Atom name="H11" type="ha"/>
            <Atom name="H12" type="ha"/>
            <Atom name="N" type="nh"/>
            <Atom name="N14" type="nh"/>
            <Atom name="H15" type="hn"/>
            <Atom name="H16" type="hn"/>
            <Atom name="H17" type="hn"/>
            <Atom name="H18" type="hn"/>
            <Bond from="0" to="1"/>
            <Bond from="0" to="5"/>
            <Bond from="0" to="6"/>
            <Bond from="1" to="2"/>
            <Bond from="1" to="7"/>
            <Bond from="2" to="3"/>
            <Bond from="2" to="8"/>
            <Bond from="3" to="4"/>
            <Bond from="3" to="9"/>
            <Bond from="4" to="5"/>
            <Bond from="4" to="10"/>
            <Bond from="5" to="11"/>
            <Bond from="6" to="12"/>
            <Bond from="6" to="13"/>
            <Bond from="12" to="16"/>
            <Bond from="12" to="17"/>
            <Bond from="13" to="14"/>
            <Bond from="13" to="15"/>
        </Residue>
    </Residues>
    <HarmonicAngleForce>
        <Angle type1="nh" type2="ce" type3="nh" angle="1.9673351328480082" k="623.08128"/>
    </HarmonicAngleForce>
    <PeriodicTorsionForce>
        <Proper type1="ca" type2="ce" type3="nh" type4="hn" periodicity1="2" phase1="3.141592653589793"
                k1="2.8242000000000003"/>
        <Proper type1="ca" type2="ca" type3="ce" type4="nh" periodicity1="2" phase1="3.141592653589793"
                k1="27.823600000000003"/>
        <Proper type1="nh" type2="ce" type3="nh" type4="hn" periodicity1="2" phase1="3.141592653589793"
                k1="2.8242000000000003"/>
        <Improper type1="ca" type2="ca" type3="ca" type4="ce" periodicity1="2" phase1="3.141592653589793" k1="4.6024"/>
        <Improper type1="ca" type2="ca" type3="ca" type4="ha" periodicity1="2" phase1="3.141592653589793" k1="4.6024"/>
        <Improper type1="ce" type2="ca" type3="nh" type4="nh" periodicity1="2" phase1="3.141592653589793" k1="4.6024"/>
        <Improper type1="nh" type2="ce" type3="hn" type4="hn" periodicity1="2" phase1="3.141592653589793" k1="4.6024"/>
    </PeriodicTorsionForce>
</ForceField>
```

**Comment by jchodera** [comment]
> I also considered @jchodera suggestion to build with tleap but I could not find the OBC forcefield in the official AMBER files.

OBC parameters are assigned by LEaP and written out to the `prmtop` file automatically. See the [Amber manual](http://ambermd.org/doc12/Amber17.pdf) page 59-60, which advise you simply to include `set default PBradii mbondi2` to use OBC (`igb=2` in `sander`). This [LEaP Tutorial](http://ambermd.org/tutorials/pengfei/) is also helpful in understanding the LEaP workflow.

**Comment by jchodera** [comment]
> I tried to read the prepi file with parmed but to no success (couldnt find any method for it and abusing AmberParm complained about not being able to parse it).

`prepi` is a very old AMBER format that predates LEaP. You can probably easily add support for it to `parmed` if you really want to use these files, but I'm still puzzled about where you are getting them since no modern AMBER workflow would generate them.

Another alternative would be to use `antechamber` (part of AmberTools) to convert the `prepi` files to something else (like `mol2`). See pages 279-280 of the [Amber manual](http://ambermd.org/doc12/Amber17.pdf).

**Comment by stefdoerr** [comment]
Ok thanks a lot for the pointers! I will take a look at it. 

I apologize, I didn't know prepi was deprecated, was just testing on an old parametrization of benzamidine. Seems like we actually write the LJ into frcmod now and the rest in mol2.

**Comment by stefdoerr** [comment]
So my only remaining question then is about parmed and how I could combine the `OpenMMParameterSet` read from `frcmod` with the topology of a `mol2` to write them into a single XML file for OpenMM

**Comment by swails** [comment]
I never wrote an Amber prep parser/writer (either internal or cartesian coordinates) for many reasons:

1. Format was deprecated, and there's a desire in Amber to discourage its use
1. You can convert to mol2 pretty easily using either tleap or, I think, antechamber
1. I prioritized other things
1. I dislike prepi :smiley:

As far as adding `mol2` residue templates to the OpenMM XML file, you need to add those residues to the `residues` attribute of the `OpenMMParameterSet`.  So something like this:

```python
import parmed as pmd

# Load the Amber FF
ff = pmd.openmm.OpenMMParameterSet.from_parameterset(
    pmd.amber.AmberParameterSet(file1, file2, ...)
)

# Load mol2 files
mol2 = pmd.load_file(your_mol2file)

# If there are multiple residue definitions, mol2 will be a pmd.modeller.ResidueTemplateContainer
# Otherwise it will be a pmd.modeller.ResidueTemplate
if isinstance(mol2, pmd.modeller.ResidueTemplateContainer):
    ff.residues = mol2.to_library()
else:
    ff.residues[mol2.name] = mol2

# Now you can write the FF XML file
```

**Comment by stefdoerr** [comment]
Oh ok great. That answer my other issue https://github.com/ParmEd/ParmEd/issues/901

Sorry for moving around :)

**Comment by stefdoerr** [comment]
Okay so last issue on this subject. 
`ValueError: GBSAOBCForce: No parameters defined for atom type nv`
If I want to run amber OBC simulation with a parametrized ligand I need to either provide `GBSAOBSForce` parameters manually or somehow tell openmm to get them from GAFF. I could not find a 'gaff.xml` in openMM. How do you do such simulations?

I know, I can build with tleap with `mbondi2` and load the prmtop but I feel that is a workaround.

**Comment by Luc1100** [comment]
Are there any updates on this. I am having the same issue that @stefdoerr was having where I need to provide the parameters for the atom types manually. I am able to produce the ffxml file using the method suggested by @swails, however it does not add atom types. Is this something I need to write myself or is there a way to do this automatically?

**Comment by jchodera** [comment]
OpenMM 7.7 ([release candidate](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=14212&p=0&start=0&view=&sid=18738392597a9b5d816c633d76fbdeb1) out now) includes updated support for applying GBSA parameters that solves this issue!

Check out the [User Guide for the development version of OpenMM](http://docs.openmm.org/development/userguide/application/02_running_sims.html#implicit-solvent) for more information.
