### ISSUE TITLE
Minimization stops early

### ISSUE THREAD

**Issue by stefdoerr** [pandegroup/openmm#1913]
```python
simulation.minimizeEnergy(tolerance=0, maxIterations=999999999)
# or 
simulation.minimizeEnergy(tolerance=0.0000001*unit.kilojoule_per_mole, maxIterations=0)
# or 
simulation.minimizeEnergy(tolerance=0, maxIterations=0)
```
Starting pot energy: 198122.41868667453 kJ\**2/(mol\**2)
Ending pot energy: 178205.965131004 kJ\**2/(mol\**2)

Okay so I might just be confused here. On a system with 3222 atoms, of which 2507 are constrained (so 715 free or restrained) this finishes in 100ms on CPU. I assume it does not run 999999999 minimization steps or achieve such low tolerance. Maybe I'm missing some undocumented information on how the minimizer works? (or is it really that blazing fast and I can close the issue happily?)

Full code: 
```python
coords = unit.Quantity(coords, unit=unit.angstrom)
parm = parmed.amber.AmberParm(prmtop)
system = parm.createSystem(nonbondedMethod=app.CutoffNonPeriodic)

otheratoms = np.arange(system.getNumParticles())
force = mm.CustomExternalForce("k*((x-x0)^2+(y-y0)^2+(z-z0)^2)")
force.addPerParticleParameter("k")
force.addPerParticleParameter("x0")
force.addPerParticleParameter("y0")
force.addPerParticleParameter("z0")
for atoms, restraint in sbc:
    otheratoms = np.setdiff1d(otheratoms, atoms)
    for a in atoms:
        force.addParticle(int(a), [restraint] + list(coords[a].value_in_unit(unit.nanometer)))
system.addForce(force)
# Set all other atoms to mass 0 which is the way to constrain them
for a in otheratoms:
    system.setParticleMass(int(a), 0 * unit.dalton)

platform, prop = getPlatform(platform, device)
integrator = mm.LangevinIntegrator(300 * unit.kelvin, 1.0 / unit.picoseconds, 2.0 * unit.femtoseconds)
simulation = app.Simulation(parm.topology, system, integrator, platform, prop)
simulation.context.setPositions(coords)

simulation.minimizeEnergy(tolerance=0, maxIterations=999999999)
```

**Comment by peastman** [comment]
The conditions for halting minimization are pretty complicated.  The L-BFGS library we use has a bunch of different parameters and tolerances you can set, so we try to take the single tolerance you specify and select appropriate values for all of them.  In this case, probably what it means is simply that the minimizer concluded it had minimized things as far as was possible, and further iterations weren't going to bring down the energy any more.

Try computing the RMS force on all unconstrained atoms.  What is that before and after minimization?

**Comment by stefdoerr** [comment]
Ok, since the documentation didn't mention it I didn't know about the extra conditions.

```python
ipdb> np.mean(np.sqrt(np.sum(forces**2, axis=1)))
2383.7999962078738
ipdb> np.mean(np.sqrt(np.sum(forces2**2, axis=1)))
1.9646952245831066
```

**Comment by peastman** [comment]
That looks like it's done a pretty effective job of minimizing it.  If you were to run it on the GPU in double precision mode, it would probably be able to minimize it a bit further.  The CPU platform computes nonbonded forces in single precision.  The minimizer figures out pretty quickly when it has reached the point where it's just changing the last few bits in the coordinates, and further steps aren't going to help.

**Comment by stefdoerr** [comment]
Okay, thank you very much!
