### ISSUE TITLE
Additional carbon atoms being created

### ISSUE THREAD

**Issue by timmonspatrick** [pandegroup/openmm#1917]
When I run the below script, three additional, lone (non-bonded) carbon atoms appear in the output file. This means the output has three more atoms than the input.

`from __future__ import print_function
from simtk.openmm import app
import simtk.openmm as mm
from simtk import unit
from sys import stdout
import numpy as np

pdb = app.PDBFile('[G16A]2mhw.pdb')
modeller = app.Modeller(pdb.topology, pdb.positions)

forcefield = app.ForceField('amber99sbnmr.xml', 'tip3p.xml')
print("adding solvent...")
modeller.addSolvent(forcefield, padding=3*unit.nanometers),
                   
modeller.deleteWater()
print("solvent removed")  #quick trick for creating reasonable box size

system = forcefield.createSystem(modeller.topology, nonbondedMethod=app.PME, 
    nonbondedCutoff=1.0*unit.nanometers, constraints=app.HBonds, rigidWater=True, 
    ewaldErrorTolerance=0.0005,
    implicitSolvent=app.GBn2, 
    soluteDielectric=1.0,
    solventDielectric=80.0)

box_vectors = system.getDefaultPeriodicBoxVectors()
min_box_dimension = min([np.linalg.norm(vector) for vector in box_vectors])
cutoff_distance = min_box_dimension * 0.99 / 2.0
for force in system.getForces():
    try:
        force.setCutoffDistance(cutoff_distance)
    except AttributeError:
        pass
print("Cutoff distance = " + str(cutoff_distance))

print("System estabilished")

integrator = mm.VerletIntegrator(2.0*unit.femtoseconds)
integrator.setConstraintTolerance(0.00001)

platform = mm.Platform.getPlatformByName('OpenCL')
properties = {'OpenCLPrecision': 'mixed'}
simulation = app.Simulation(modeller.topology, system, integrator, platform, 
    properties)
simulation.context.setPositions(modeller.positions)

print('Minimizing...')
simulation.minimizeEnergy()

simulation.context.setVelocitiesToTemperature(300*unit.kelvin)
print('Equilibrating...')
simulation.step(100)

no_steps = 100000

simulation.reporters.append(app.DCDReporter('trajectory.pdb', 100)) #report interval
simulation.reporters.append(app.StateDataReporter(stdout, no_steps, step=True, 
    potentialEnergy=True, temperature=True, progress=True, remainingTime=True, 
    speed=True, totalSteps=no_steps, separator='\t'))

print('Running Production...')
simulation.step(no_steps)
print('Done!')`

**Comment by rmcgibbo** [comment]
Are you sure they're carbon? I suspect they're ions, added by the modeller to balance the charge.

**Comment by timmonspatrick** [comment]
You're right, I must have misread Cl as C. Thanks!
