### ISSUE TITLE
CPU platform implementation of CustomNonbondedForce

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#192]
Is there enthusiasm from others for a CPU platform implementation of CustomNonbondedForce?  This would be very helpful for running YANK on CPUs.

**Comment by swails** [comment]
@jchodera -- I think this can be closed now.  @peastman implemented a CPU version of `CustomNonbondedForce` in addition to adding JIT compilation of custom Lepton expressions.

**Comment by jchodera** [comment]
Thanks for the reminder, @swails!
