### ISSUE TITLE
Instructions for installing from source

### ISSUE THREAD

**Issue by IAPark** [pandegroup/openmm#1922]
I don't seem to see any instructions for installing from source.

Should this be added, or did I miss it somewhere. It seems it mostly installed fine on my Linux Arch laptop after installing some dependencies, but I think I need to add the python lib to a path of some sort.

**Comment by peastman** [comment]
I somehow missed this issue when it was originally opened.  Detailed instructions for compiling from source are at http://docs.openmm.org/latest/userguide/library.html#compiling-openmm-from-source-code.
