### ISSUE TITLE
Unable to install openmm in Linux 16.04

### ISSUE THREAD

**Issue by Pallavims2** [pandegroup/openmm#1923]
I am unable to run openmm in Linux 16.04. I have installed CUDA 8.0 and python 2.7.12

symbol lookup error: /usr/local/openmm/lib/plugins/libOpenMMCUDA.so: undefined symbol: _ZN6OpenMM8Platform21registerKernelFactoryERKSsPNS_13KernelFactoryE

**Comment by peastman** [comment]
What Linux distribution?

How did you install OpenMM?  Did you compile from source, or use the zip installer?  Based on the path to the library, I gather you didn't use conda (which is the easiest and most reliable way to install).

**Comment by Pallavims2** [comment]
I have tried installing using conda as you said
conda install -c omnia openmm 
python -m simtk.testInstallation

But when I verified the installation, I got the following error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 563, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 545, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 237, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 582, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 528, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python2.7/sysconfig.py", line 412, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_nd import *
ImportError: No module named _sysconfigdata_nd

**Comment by rmcgibbo** [comment]
@Pallavims2: it looks like you have two completely independent Python installations, one in `/usr/lib/` (the system's python, which doesn't have conda), and one with conda, probably installed to your home directory.

Perhaps try running `$ dirname $(which conda)`. that will give you the path to the `/bin` directory where conda is installed.  Then run `$ /path/to/this/bin/python -m simtk.testInstallation` to make sure you're using the correct copy of Python that has openmm installed.

**Comment by Pallavims2** [comment]
Thank you Robert T. McGibbon... I am able to get the output. Its working now. Once gain I thank you very much for your time and support. :-)
