### ISSUE TITLE
Error launching CUDA compiler: 512

### ISSUE THREAD

**Issue by bmanubay** [pandegroup/openmm#1925]
Having an error launching some GPU accelerated simulations on MSKCC's Lilac GPU cluster. Unfortunately the tracebacks have not been very informative (:/) : 

```
Traceback (most recent call last):
  File "run_molecule.py", line 81, in <module>
    simulation.minimizeEnergy()
  File "/home/brma3379/anaconda3/envs/openff2/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 128, in minimizeEnergy
    mm.LocalEnergyMinimizer.minimize(self.context, tolerance, maxIterations)
  File "/home/brma3379/anaconda3/envs/openff2/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 2631, in minimize
    return _openmm.LocalEnergyMinimizer_minimize(context, tolerance, maxIterations)
Exception: Error launching CUDA compiler: 512
/tmp/992072.tmpdir/openmmTempKernel0x3f48020_26797.cu(777): error: identifier "__ballot_sync" is undefined

/tmp/992072.tmpdir/openmmTempKernel0x3f48020_26797.cu(933): error: identifier "__ballot_sync" is undefined

/tmp/992072.tmpdir/openmmTempKernel0x3f48020_26797.cu(857): warning: variable "sumBuffer" was declared but never referenced

/tmp/992072.tmpdir/openmmTempKernel0x3f48020_26797.cu(863): warning: variable "pairStartIndex" was declared but never referenced

2 errors detected in the compilation of "/tmp/992072.tmpdir/tmpxft_000069dc_00000000-7_openmmTempKernel0x3f48020_26797.cpp1.ii".
```
I'm able to launch the simulation successfully with the `CPU` or  `Reference` platform, but I keep getting errors when attempting to use `CUDA`. I've got `CUDA 8.0` loaded and all of the correct environment variables set according to the OpenMM documentation, so I'm at a bit of a loss. By the way, I'm just simulating bulk liquid cyclohexane that I set up with `solvationtoolkit`. I've successfully simulated on other computers, so I'm sure that all is fine. Any incite is appreciated!

Thanks,

Bryce

**Comment by jchodera** [comment]
I believe @andrizzi has just noticed the same issue with the latest `dev` version.

@bmanubay : Which node were you running on? Can you also provide the output of `nvcc --version` and `nvidia-smi` on that node?

**Comment by andrrizzi** [comment]
Correct, this is the same error I'm getting. I believe this is the same error that is being discussed in this PR #1924.

**Comment by jchodera** [comment]
Can one of you post the output of nvcc and nvidia-smi?

**Comment by andrrizzi** [comment]
nvidia-smi
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.81                 Driver Version: 384.81                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
| 28%   34C    P8     9W / 250W |      0MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```
nvcc --version
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Sun_Sep__4_22:14:01_CDT_2016
Cuda compilation tools, release 8.0, V8.0.44
```

**Comment by peastman** [comment]
This happens when you're using the CUDA 9.0 driver with the CUDA 8.0 toolkit.  To guarantee correct results with the 9.0 driver, we need to use new functions that aren't supported by the 8.0 compiler.

A simple solution might be to only use those functions with Volta or later GPUs.  The new functions are needed because of changes to how thread synchronization works on Volta, so we don't need them with earlier GPUs.  And since earlier versions of the toolkit don't support Volta, we don't need to worry you might have an old toolkit in that case.

**Comment by andrrizzi** [comment]
Ah! Sorry, I should have checked what kind of driver was 384.81. I can confirm that after `module add cuda/9.0`, it seems to work fine. Thanks!

**Comment by bmanubay** [comment]
Dang, I thought I'd already tried all the `CUDA` versions available already, but that fixed it for me too! Oops! Thanks for the help, guys!

**Comment by jchodera** [comment]
> A simple solution might be to only use those functions with Volta or later GPUs. The new functions are needed because of changes to how thread synchronization works on Volta, so we don't need them with earlier GPUs. And since earlier versions of the toolkit don't support Volta, we don't need to worry you might have an old toolkit in that case.

Were those functions introduced in CUDA 9.0, but not present in CUDA 8.0? If so, this sounds like a great solution so that we can still build OpenMM with CUDA 8.0 for older hardware.

In any case, @Lnaden, we should update the [omnia-linux-anvil](https://github.com/omnia-md/omnia-linux-anvil) to use CUDA 9.0 in preparation for the new OpenMM 7.2 release.

**Comment by peastman** [comment]
> Were those functions introduced in CUDA 9.0, but not present in CUDA 8.0?

Correct.
