### ISSUE TITLE
Including bonded interactions in 1-2 and 1-3 bonded pairs

### ISSUE THREAD

**Issue by mattwthompson** [pandegroup/openmm#1926]
This might be pushing openmm too far out of the biophysical world and into the interfacial/materials world. I have a system in which I want some non-bonded interactions between bonded pairs to be *included* - yes, I know this is peculiar. There is a solid that I want to be described by this, but also a fluid that I want to describe using OPLS (normal 1-2, 1-3 exclusions and 1-4 interactions scaled). I have the solid running stably in GROMACS, but I was interested in using OpenMM because GROMACS doesn't support the mixed 1-4 scaling that I would need to run the fluid and the solid. Is this possible/feasible?

From what I can tell, `createExceptionsFromBonds` is the closest to this but instead is used to generate the scaled 1-4 interactions and can't *include* 1-2 and 1-3 interactions.

**Comment by Lnaden** [comment]
You can actually add these as a [`Custom*Force`](http://docs.openmm.org/latest/userguide/theory.html?highlight=custombondforce#custom-forces) and manually add the particle pairs to the force.

We do something similar in our [Alchemical Free Energy Factory](https://github.com/choderalab/openmmtools/blob/master/openmmtools/alchemy.py) where we implement the 1-4 interactions through a `CustomBondForce` which emulates a standard `NonbondedForce` at close range, but nothing stopping you from doing this at the 1-2 and 1-3 level.

The code I linked is a bit deep, but I'll summarize the psuedo-code you would need for what you are doing
```python
# Define the force you want to emulate by its potential energy as a string
sterics_energy_expression = "4*epsilon*x*(x-1.0); x = (sigma/r)^6;"
# Create the Custom*Force object, we are using CustomBondForce since it allows description between exact pairs of atoms
sterics_custom_bond_force = openmm.CustomBondForce(sterics_energy_expression)
# Define the parameters of the force
sterics_custom_bond_force.addPerBondParameter("sigma")  # Lennard-Jones effective sigma
sterics_custom_bond_force.addPerBondParameter("epsilon")  # Lennard-Jones effective epsilon
# Cycle through the parameters somehow, we're using the built-in OpenMM NonbondedForce for example here
for exception_index in range(nonbonded_force.getNumExceptions()):
    [iatom, jatom, chargeprod, sigma, epsilon] = nonbonded_force.getExceptionParameters(exception_index)
    # Add the atoms to the CustomForce we made
    sterics_custom_bond_force.addBond(iatom, jatom, [sigma, epsilon])
    # Zero out the exception in the normal nonbonded force so we don't double count
    nonbonded_force.setExceptionParameters(exception_index, iatom, jatom, abs(0.0*chargeprod), sigma, abs(0.0*epsilon))
# Add the new force to the system
system.addForce(sterics_custom_bond_force)
```

This is a simplified version of what I'm sure you would want to do, and I've excluded electrostatics, but at least this should give you an idea of how we approached it with our application.

**Comment by peastman** [comment]
The other thing to remember is that `createExceptionsFromBonds()` is just a convenience function.  It deals with the most conventional case and identifies the exceptions for you.  But you can also just identify the exceptions you want and add them yourself with `addException()`.

**Comment by peastman** [comment]
Closing this, since the question has been answered.
