### ISSUE TITLE
ValueError: Virtual sites not yet supported by Gromacs parsers

### ISSUE THREAD

**Issue by duxinzheng** [pandegroup/openmm#1928]
When I tried to Using Gromacs Files to start I ran python simulateGromacs.py, then the error occurred:

**File "/public/home/xzdu/lib/python3.5/site-packages/simtk/openmm/app/gromacstopfile.py", line 501, in __init__
    raise ValueError('Virtual sites not yet supported by Gromacs parsers')
ValueError: Virtual sites not yet supported by Gromacs parsers**

Please tell me how to solve this. Thanks a lot.

**Comment by peastman** [comment]
We should add support for them.

**Comment by swails** [comment]
ParmEd has support for some of the GROMACS virtual sites.  You can try using `parmed.gromacs.GromacsTopologyFile` -- it should be usable as a drop-in replacement for the built-in OpenMM class.

**Comment by peastman** [comment]
Does it actually?  I searched the ParmEd source but didn't find any uses of the OpenMM virtual site classes, so I concluded it didn't support them either.

**Comment by swails** [comment]
[this is where ParmEd sets the virtual sites](https://github.com/ParmEd/ParmEd/blob/master/parmed/structure.py#L2161-L2197)

[and this is where ParmEd parses some of the GROMACS vsites](https://github.com/ParmEd/ParmEd/blob/master/parmed/gromacs/gromacstop.py#L1958-L1991)

[and some more](https://github.com/ParmEd/ParmEd/blob/master/parmed/gromacs/gromacstop.py#L669-L710)

It doesn't support all of what GROMACS does, I don't think.  But it will at least get the common ones like TIPnP.

**Comment by peastman** [comment]
Thanks!  I missed that.

**Comment by sunhwan** [comment]
Does ParmEd read virtual_sites2? I read the code briefly but the parser only seemed to process virtual_sites3.

**Comment by sunhwan** [comment]
I have made gromacstopfile.py to handle NBFIX/VSITE2 section. Is there a guide on how to test with existing test cases and submit pull request?

**Comment by peastman** [comment]
That's great!  Test cases for that class go in this file: https://github.com/pandegroup/openmm/blob/master/wrappers/python/tests/TestGromacsTopFile.py.  If you need to include a new .top file for testing, that can go in https://github.com/pandegroup/openmm/tree/master/wrappers/python/tests/systems (but keep it small, preferably no more than a few KB).

**Comment by duxinzheng** [comment]
i use parmed and this has been solved. Thanks a lot!
