### ISSUE TITLE
Bug or operator error in adding atoms/virtual sites to topology/system "out of order"

### ISSUE THREAD

**Issue by davidlmobley** [pandegroup/openmm#1931]
For reasons I probably don't need to go into here (but relating to adding off-site charges in SMIRNOFF), I'm working through a test example where I try to turn TIP3P water into TIP4P water without using `Modeller`, and I ran into an issue where atoms get reordered in a way which was unexpected to me. **Specifically, it seems that atoms must be numerically in order within the residues in which they occur** (e.g. I can't have atoms 0, 1, 2, and 648 in residue 0, and 3, 4, 5, and 649 in residue 1, etc.), and if I deviate from this, atoms end up having the wrong coordinates.

I'm trying to figure out whether this is a bug or just a "naive user" problem. If it may be a bug, I'm happy to create and post a minimal example to reproduce the problem, though I suspect it's just a "naive user" problem and I need to work around the issue.

Here's what I did, roughly (as it relates to virtual sites and my problem):
- Load a PDB file for TIP3P water (216 residues/648 atoms)
- Create a system using tip3p.xml and  the standard OpenMM `forcefield.createSystem`
- Loop through the forces in the system, and for the `NonbondedForce` add a new virtual site in each residue (when I do so) a new particle at the location of this site; naturally these new particles have indices at the end of the system
- Add relevant exceptions
- Create dummy positions at the end of the position array (entries 648 and onwards)
- Modify Topology to add a new virtual site atom (with indices 648 and onwards) in each residue, corresponding to the changes I made in the System. At this point, I can confirm that atoms in my Topology are in the same order as those in my System and have the intended coordinates
- Set up a simulation and compute virtual sites; output coordinates and check that they are as intended
- Find that they are clearly incorrect

What I had created in this process was, for the first water molecule (for example), a residue consisting of atoms 0, 1, and 2, and particle 648 which was a virtual site. But what I find when I output the results of the procedure (e.g. by writing to a PDB) is that the virtual site ends up with the coordinates which had been assigned to the oxygen of the second water molecule (and the oxygen gets the coordinates of the next hydrogen, etc.) -- basically the virtual acts as if it is atom 4 (and indeed this is what gets output to the PDB) and bumps the indices of all subsequent atoms.

I must admit, what I'm doing is a bit funky (normally presumably one would have atoms that are in numerical order within their residues) which makes me suspect I'm doing something that shouldn't work. However, I haven't run across anywhere in the docs that indicates that atom indices must be consecutive within their residues, so I figured I should at least ask. Also, the current behavior (where this is a silent failure) seems less than ideal.

**Comment by peastman** [comment]
I'm not sure I ever even thought about the possibility of someone doing that.  I just sort of assumed that when you added a residue to the topology, you would immediately add all the atoms it contains.  I'm not sure what's causing the reordering, but I would generally advise not trying to do that, since it will certainly cause problems.  For example, writing a PDB file would be completely broken. since you could easily have atoms that were supposed to be in the same residue, yet had a TER record between them.

**Comment by davidlmobley** [comment]
OK. Maybe a good approach, then, would be to (a) make sure it's documented that this is ill-advised, and (b) see if there's a way you can detect if someone has done this and raise an exception? 

I know how to avoid doing this, so I'll just proceed that direction. Thanks.
