### ISSUE TITLE
How can I change the path of openmm library (installed) to run correctly in different absolute pathes in homogeneous clusters?

### ISSUE THREAD

**Issue by jht0664** [pandegroup/openmm#1934]
Hello, 

I am wondering if I can copy openmm library installed in /scratch/folder1 of "A" cluster to /scratch/folder2 of "B" cluster, then run python with the openmm library in "B" cluster.
Let me show I did for my questions and please let me know how to run correctly in this case.

1. For installation of OpenMM in "A" gpu cluster with CUDA 8.0 (/usr/local/cuda/lib64):
I used Pre-compiled Binaries "Linux" version and Python 3.6 installed from source file.
When I run "sh ./install.sh", it asked two locations for openmm and python, so I set
/scratch/folder1/openmm and /scratch/folder1/python/bin/python.

2. Then, I validated my installation using  /scratch/folder1/python/bin/python -m simtk.simtk.testInstallation.
Then, it showed 
```
There are 4 Platforms available:
1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Successfully computed forces
4 OpenCL - Successfully computed forces
```
3. I tar two folders like /scratch/folder1/openmm and /scratch/folder1/python/bin/python.
Then, transfer the tar files to /scratch/folder2 of "B" cluster.

4. For running of OpenMM in /scratch/folder2/ "B" gpu cluster with CUDA 8.0 (/usr/local/cuda/lib64):
untar two tar files from "A" clusters into /scratch/folder2/openmm/ and /scratch/folder2/python.
Also, I did: 
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/scratch/folder2/openmm/lib/
```
5. I got problem with following message when I run: it did not show CUDA or CPU even I run the cluster with the same environment as previous "A" cluster.
```
/scratch/folder2/python/bin/python -m simtk.testInstallation
There are 1 Platforms available:
1 Reference - Successfully computed forces
```
And run for my openmm own script: 
```
/scratch/folder2/python/bin/python run_myID.py

Traceback (most recent call last):
  File "run_openMM.py", line 54, in <module>
    platform = Platform.getPlatformByName('CUDA')
  File "/scratch/folder2/python/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 6829, in getPlatformByName
    return _openmm.Platform_getPlatformByName(name)
Exception: There is no registered Platform called "CUDA"
```

**Comment by peastman** [comment]
This will be much easier if you install with conda.  Put copies of miniconda (which includes Python) in `/scratch/folder1` and `/scratch/folder2`.  You can then use each one to install a copy of OpenMM, and it will put all the libraries in its own local directory.

**Comment by jht0664** [comment]
Thank you for your advice. As you said, when I install miniconda and then install OpenMM using the miniconda, I copy miniconda directory to another cluster "B" .
But I got the same message with step 5 in previous post: 
only 1 platform available and no registered platform called "CUDA"

In my queue system, whenever I submit queue, the home directory and server are changed. That's why I need to transfer pre-installed and compiled files to a given folder in the running node.

**Comment by peastman** [comment]
Perhaps you just need to set `OPENMM_PLUGIN_DIR` to tell it where to load the plugins from?  You can call `Platform.getDefaultPluginsDirectory()` to see what directory it's looking in.

**Comment by jht0664** [comment]
Yes, it works. When I set `OPENMM_PLUGIN_DIR` like,
` export OPENMM_PLUGIN_DIR=miniconda_folder/lib/plugins/`
then OpenMM correctly run.  Thank you for your help!

**Comment by peastman** [comment]
Glad that solved it.
