### ISSUE TITLE
Sphinx docs are failing due to non-ASCII character in references.bib

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1949]
A stray non-ASCII character in `references.bib` added in https://github.com/pandegroup/openmm/pull/1942 is [causing the `dev` conda package builds to fail](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/309839769#L8989-L9013):
```
! Package inputenc Error: Unicode char ϕ (U+3D5)
(inputenc)                not set up for use with LaTeX.
See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.9879 ...ing improved sampling of the backbone ϕ
                                                  , \(\psi\) and side-chain ...
? 
! Emergency stop.
 ...                                              
                                                  
l.9879 ...ing improved sampling of the backbone ϕ
                                                  , \(\psi\) and side-chain ...
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on OpenMMUsersGuide.log.
make[5]: *** [OpenMMUsersGuide.pdf] Error 1
make[4]: *** [latexpdf] Error 2
make[3]: *** [sphinx-docs/userguide/latex/OpenMMUsersGuide.pdf] Error 2
make[2]: *** [docs-source/CMakeFiles/sphinxpdf.dir/all] Error 2
make[1]: *** [docs-source/CMakeFiles/sphinxpdf.dir/rule] Error 2
make: *** [sphinxpdf] Error 2
```
Here's the failure in `docs-source/usersguide/references.bib`:
```
@article{Best2012,
   author = {Best, Robert B. and Zhu, Xiao and Shim, Jihyun and Lopes, Pedro E. M. and Mittal, Jeetain and Feig, Michael and MacKerell, Alexander D.},
   title = {Optimization of the Additive CHARMM All-Atom Protein Force Field Targeting Improved Sampling of the Backbone ϕ, ψ and Side-Chain χ1 and χ2 Dihedral Angles},
```
I'll open a PR to correct this, but @peastman should add a travis test branch that will fail if the sphinx docs builds fail so we don't merge PRs that break the conda builds.

**Comment by jchodera** [comment]
@peastman : The sphinx docs are [built when `DOCS_DEPLOY=true`](https://github.com/pandegroup/openmm/blob/master/.travis.yml#L183-L192):
```
  - if [[ ! -z "${DOCS_DEPLOY}" && "${DOCS_DEPLOY}" = "true" ]]; then
      pip install sphinx==1.5.6 sphinxcontrib-bibtex sphinxcontrib-lunrsearch sphinxcontrib-autodoc_doxygen;
      make sphinxhtml;
      make C++ApiDocs PythonApiDocs;
      mkdir -p api-docs;
      mv sphinx-docs/userguide/html api-docs/userguide;
      mv sphinx-docs/developerguide/html api-docs/developerguide;
      mv api-python api-docs;
      mv api-c++ api-docs;
    fi
```
which is enabled in [this branch](https://github.com/pandegroup/openmm/blob/master/.travis.yml#L85-L94) of travis. Any idea why this is somehow passing?

**Comment by jchodera** [comment]
Weird. The [user guide built successfully](https://travis-ci.org/pandegroup/openmm/jobs/308662884#L5355-L5491) in that PR.

**Comment by jchodera** [comment]
Maybe we're using a different version of sphinx in travis and the `dev` conda builds @Lnaden? Or maybe a different version of latex?

**Comment by Lnaden** [comment]
Thats because that is compiling the HTML version of the docs. The build scripts on the `conda-{dev}-recipes` repos build the [PDF version of the docs](https://github.com/omnia-md/conda-dev-recipes/blob/d8206fc12ae1c0271c32d148c84460e1788ebf94/openmm/build.sh#L78). Different LaTeX compilers, different allowed unicode chars

**Comment by jchodera** [comment]
Awesome! I've added the sphinx PDF build to #1950
