### ISSUE TITLE
Support for stationary external magnetic fields

### ISSUE THREAD

**Issue by dextorious** [pandegroup/openmm#1955]
I'm interested in using OpenMM to investigate the effects of strong (tesla-range) stationary magnetic fields on the properties of certain solvents. Having read the documentation, I understand there's no specific support for this usecase, and as I'm new to OpenMM I'd like to understand how easy it would be to implement this. 

From a theory standpoint, the simplest way to implement this is simply adding the effect of a Lorentz force to the acceleration of each particle with a non-zero magnetic moment: `$\vec{a} = \vec{a}_0 + \frac{q}{m}(\vec{v} \times \vec{B})$`, where `$\vec{a}_0$` denotes the original acceleration of the particle, `$\vec{v}$` is the particle velocity and `$\vec{B}$` the external magnetic field. There are more advanced approaches for avoiding constraints on the permissible timesteps for specific integrators imposed by the Larmor frequencies, but I'd like to start with the simplest case. 

If I understand the documentation correctly, this cannot be done using the existing support for user-defined external forces, since those are defined as potentials depending solely on the particle coordinates. Is a CustomIntegrator the right way to go here, or does this require more extensive changes to the codebase?

**Comment by Lnaden** [comment]
Based on what you described, it sounds like you need a `CustomExternalForce` object which can be attached to the `System` object. In this case, you can describe the potential energy of your force through algebraic expressions as a string, then pass the expressions to the `CustomExternalForce` init. From there, you would any global/per-particle variables, then add the particles to the `CustomExternalForce` before adding it to the `System`.

**Comment by peastman** [comment]
CustomIntegrator is exactly how I'd do it.  That has access to all the velocities.

By the way, you can find a large collection of custom integrators at https://github.com/choderalab/openmmtools/blob/master/openmmtools/integrators.py.  You might find it easiest to start with one of those (such as the Verlet or Langevin integrator), then just make the changes to add the extra acceleration.

**Comment by peastman** [comment]
CustomExternalForce can't do this, because it doesn't let the force depend on velocity.

**Comment by Lnaden** [comment]
D'oh, you're right, my apologies!

**Comment by dextorious** [comment]
Thank you very much for the quick responses! The integrator examples @peastman linked look like exactly what I need to get started. This is a very niche usecase, but I'll make sure to open source a working example as soon as I have one in case it helps anyone else.

**Comment by limked** [comment]
@dextorious I know it's an old discussion, but did you find a satisfying solution?
