### ISSUE TITLE
How to setup PBC correctly

### ISSUE THREAD

**Issue by stefdoerr** [pandegroup/openmm#1960]
I made a test system with only 2 sodiums whose periodic distance should be shorter than the non-periodic. For some reason when I set up the system with periodic box, the electrostatic energy goes down instead of up as if the distance between the atoms increased instead of decreased.

I must be doing something blatantly wrong but I cannot figure out what.

```python
prm = parmed.charmm.CharmmParameterSet(prmFile)
struct = parmed.charmm.CharmmPsfFile(psfFile)
if periodic:
    a = unit.Quantity((box[0] * unit.angstrom, 0 * unit.angstrom, 0 * unit.angstrom))
    b = unit.Quantity((0 * unit.angstrom, box[1] * unit.angstrom, 0 * unit.angstrom))
    c = unit.Quantity((0 * unit.angstrom, 0 * unit.angstrom, box[2] * unit.angstrom))
    structure.box_vectors = (a, b, c)
    system = structure.createSystem(prm, nonbondedMethod=app.CutoffPeriodic, nonbondedCutoff=cutoff * unit.angstrom)
    system.setDefaultPeriodicBoxVectors(a, b, c)
else:
    system = structure.createSystem(prm)
integrator = openmm.LangevinIntegrator(300 * unit.kelvin, 1 / unit.picoseconds, 2 * unit.femtoseconds)
platform = openmm.Platform.getPlatformByName('CPU')
context = openmm.Context(system, integrator, platform)

# Run OpenMM with given coordinates
context.setPositions(coords * unit.angstrom)
omm_energies = parmed.openmm.energy_decomposition(structure, context)
state = context.getState(getForces=True, getEnergy=True)
omm_energies2 = state.getPotentialEnergy()
omm_forces = state.getForces(asNumpy=True).value_in_unit(unit.kilocalories_per_mole / unit.angstrom)
```
```python
In [7]: state.getPositions()
Out[7]: Quantity(value=[(1.5099258422851562, 0.04148092493414879, 0.4780002534389496), (0.0, 0.0, 0.0)], unit=nanometer)

In [8]: system.getDefaultPeriodicBoxVectors()
Out[8]: 
[Quantity(value=(1.933925986289978, 0.0, 0.0), unit=nanometer),
 Quantity(value=(0.0, 1.912519097328186, 0.0), unit=nanometer),
 Quantity(value=(0.0, 0.0, 1.9139999151229858), unit=nanometer)]
```

With `periodic=False`:
```python
In [15]: omm_energies
Out[15]: {'bond': 0.0, 'nonbonded': 20.959339907702706, 'total': 20.959339907702706}
```
With `periodic=True`:
```python
In [5]: omm_energies
Out[5]: {'bond': 0.0, 'nonbonded': 7.709079217272552, 'total': 7.709079217272552}
```

![tmp](https://user-images.githubusercontent.com/7935362/34107706-839654b2-e3fd-11e7-96b8-50ec10769a99.png)

ps. I have zeroed the LJ parameters to only calculate the electrostatics
```python
In [14]: system.getForces()
Out[14]: 
[<simtk.openmm.openmm.NonbondedForce; proxy of <Swig Object of type 'OpenMM::NonbondedForce *' at 0x7f27f2117d20> >,
 <simtk.openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x7f27f21171e0> >]

In [15]: system.getForces()[0].getParticleParameters(0)
Out[15]: 
[Quantity(value=1.0, unit=elementary charge),
 Quantity(value=0.0, unit=nanometer),
 Quantity(value=0.0, unit=kilojoule/mole)]

In [16]: system.getForces()[0].getParticleParameters(1)
Out[16]: 
[Quantity(value=1.0, unit=elementary charge),
 Quantity(value=0.0, unit=nanometer),
 Quantity(value=0.0, unit=kilojoule/mole)]
```

**Comment by stefdoerr** [comment]
```python
In [48]: state.getPositions()
Out[48]: Quantity(value=[(2.002000093460083, -1.141038179397583, 3.7750000953674316), (0.49207422137260437, -1.1825190782546997, 3.29699969291687)], unit=nanometer)

In [49]: system.getDefaultPeriodicBoxVectors()
Out[49]: 
[Quantity(value=(1.933925986289978, 0.0, 0.0), unit=nanometer),
 Quantity(value=(0.0, 1.912519097328186, 0.0), unit=nanometer),
 Quantity(value=(0.0, 0.0, 1.9139999151229858), unit=nanometer)]
```

**Comment by stefdoerr** [comment]
I notice now that my coordinates lie outside of the [0, boxsize] coordinates. Would that matter for OpenMM? Does it expect the coordinates to be wrapped inside the [0, boxsize] box?

**Comment by stefdoerr** [comment]
![tmp](https://user-images.githubusercontent.com/7935362/34107706-839654b2-e3fd-11e7-96b8-50ec10769a99.png)

**Comment by peastman** [comment]
You're using a cutoff in the periodic case, but not in the non-periodic case.  That dramatically changes the results.  With a cutoff, the energy goes to 0 at the cutoff distances, but without a cutoff it goes to 0 at infinity.  For the non-periodic case, try setting the nonbonded method to `CutoffNonPeriodic` and using the same cutoff distance as in the periodic case.

**Comment by stefdoerr** [comment]
The cutoff is around 9. How would this affect the calculation? In the non-periodic I don't use cutoff to include the interaction as it's at 15angstrom but in the periodic the interaction is at 6angstrom and hence the cutoff doesn't affect it.

On December 18, 2017 6:51:47 PM GMT+01:00, peastman <notifications@github.com> wrote:
>You're using a cutoff in the periodic case, but not in the non-periodic
>case.  That dramatically changes the results.  With a cutoff, the
>energy goes to 0 at the cutoff distances, but without a cutoff it goes
>to 0 at infinity.  For the non-periodic case, try setting the nonbonded
>method to `CutoffNonPeriodic` and using the same cutoff distance as in
>the periodic case.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pandegroup/openmm/issues/1960#issuecomment-352503625

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stefdoerr** [comment]
Ah the cutoff is a linear scaling? Not a hard cutoff threshold?

On December 18, 2017 6:58:08 PM GMT+01:00, stefdoerr@gmail.com wrote:
>The cutoff is around 9. How would this affect the calculation? In the
>non-periodic I don't use cutoff to include the interaction as it's at
>15angstrom but in the periodic the interaction is at 6angstrom and
>hence the cutoff doesn't affect it.
>
>On December 18, 2017 6:51:47 PM GMT+01:00, peastman
><notifications@github.com> wrote:
>>You're using a cutoff in the periodic case, but not in the
>non-periodic
>>case.  That dramatically changes the results.  With a cutoff, the
>>energy goes to 0 at the cutoff distances, but without a cutoff it goes
>>to 0 at infinity.  For the non-periodic case, try setting the
>nonbonded
>>method to `CutoffNonPeriodic` and using the same cutoff distance as in
>>the periodic case.
>>
>>-- 
>>You are receiving this because you authored the thread.
>>Reply to this email directly or view it on GitHub:
>>https://github.com/pandegroup/openmm/issues/1960#issuecomment-352503625
>
>-- 
>Sent from my Android device with K-9 Mail. Please excuse my brevity.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by peastman** [comment]
It uses the reaction field approximation to make the energy go smoothly to zero.  The equations are given in http://docs.openmm.org/latest/userguide/theory.html#coulomb-interaction-with-cutoff.

**Comment by stefdoerr** [comment]
Oh great! Thank you!

On December 18, 2017 7:31:23 PM GMT+01:00, peastman <notifications@github.com> wrote:
>It uses the reaction field approximation to make the energy go smoothly
>to zero.  The equations are given in
>http://docs.openmm.org/latest/userguide/theory.html#coulomb-interaction-with-cutoff.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pandegroup/openmm/issues/1960#issuecomment-352517328

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
