### ISSUE TITLE
CUDA 9.1 release

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1969]
@peastman : It appears that CUDA 9.1 has been released:
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html

* Should the OpenMM 7.2 release be moved to CUDA 9.1, or remain at 9.0?
* Should the `dev` builds be moved to CUDA 9.1?

**Comment by jchodera** [comment]
@peastman: Have you profiled OpenMM against CUDA 9 and 9.1? Ross Walker noted 9.1 was at least 10% faster for AMBER, which seems significant enough that we should look into this.

**Comment by peastman** [comment]
I haven't, but that would be nice if it is!

**Comment by jchodera** [comment]
We're looking into whether we can build OpenMM against multiple CUDA versions and deploy them all on `conda` in a manner that avoids accidentally letting users install more than one at once.

We have a few ideas:
* Use the [`conda` features](https://conda.io/docs/user-guide/tasks/build-packages/features.html) facility. I've tried (unsuccessfully) to get this to work before, but the new conda-build may fix things
* Use a scheme similar to [pytorch](https://github.com/pytorch/builder/tree/master/conda)

@lnaden and I are investigating

**Comment by jchodera** [comment]
Just a heads-up that CUDA 9.2 is out now:
https://developer.nvidia.com/cuda-toolkit/whatsnew

I've got a working prototype that builds CUDA-specific conda packages like `openmm-cudaXY`, but this requires users manually force an uninstall and install, which leads to fragile conda installations. I'm still experimenting with the "feature" options, and we haven't had a chance to yet dig into what pytorch does.

**Comment by Lnaden** [comment]
Is there a reason this CUDA generation is coming out much faster than 6/7/8?

**Comment by peastman** [comment]
They announced it, but it isn't released yet.  https://developer.nvidia.com/cuda-downloads still lists 9.1 as the latest release.  It sounds like they might have a prerelease build available through the developer program (I haven't checked to see yet).
