### ISSUE TITLE
Monitoring CVs on the fly. 

### ISSUE THREAD

**Issue by msultan** [pandegroup/openmm#1970]
I am currently trying to work on writing some custom CVs using the ```CustomCVForce``` and it would be great to be able to directly monitor the value of the CV for debugging purposes while the simulation progresses. I don't believe the CustomCVForce supports this currently. 

I was thinking maybe having the state reporter be able to accept a new "ouputCV" argument ?

**Comment by peastman** [comment]
I was mistaken when I told you there was no way to do this.  `CustomCVForce` actually has a `getCollectiveVariableValues()` method you can use to query the values in a context.  Clever me for thinking to include such a useful function!

**Comment by msultan** [comment]
Perfect, just what I needed.
