### ISSUE TITLE
DCDReporter misses a frame

### ISSUE THREAD

**Issue by stefdoerr** [pandegroup/openmm#1971]
I've noticed that the DCDReporter is always missing one frame (the first?)
Loading into VMD it complains that `dcdplugin) Warning: DCD header claims 2000 frames, file size indicates there are actually 1999 frames`.

**Comment by stefdoerr** [comment]
Code used was copied from the script builder of openMM http://builder.openmm.org/

**Comment by yumipxd** [comment]
DCDReporter does not lose any frame. Every time DCDFile add a frame, it first updates the header of the DCD file, then write the coordinates. If the simulation is done normally, the number of frames will be correct.

**Comment by stefdoerr** [comment]
I will try to see if I can make a minimal example.

**Comment by stefdoerr** [comment]
Hm, I can't find the code now that produced it and indeed a simple test I wrote now works fine. I will close this for now and in case I find it again I'll reopen.
