### ISSUE TITLE
OpenMM 7.1.1 Windows - Cuda/OpenCL WorkThread class not exposed.

### ISSUE THREAD

**Issue by mikeoconnor0308** [pandegroup/openmm#1976]
I'm writing a little plugin for interactive molecular dynamics. It's very similar to the Plumed plugin. I've run into a problem linking on Windows, when attempting to flush the work threads. A minimal example is [here](https://github.com/mikeoconnor0308/openmmexampleplugin), where I've just added the following line to the Cuda example kernel:

```c
cu.getWorkThread().flush()
```

On Windows, this leads to the following error when linking against the conda distributed binary:

```
LNK2019	unresolved external symbol "public: void __cdecl OpenMM::CudaContext::WorkThread::flush(void)" (?flush@WorkThread@CudaContext@OpenMM@@QEAAXXZ) referenced in function "public: virtual void __cdecl ExamplePlugin::CudaCalcExampleForceKernel::copyParametersToContext(class OpenMM::ContextImpl &,class ExamplePlugin::ExampleForce const &)" (?copyParametersToContext@CudaCalcExampleForceKernel@ExamplePlugin@@UEAAXAEAVContextImpl@OpenMM@@AEBVExampleForce@2@@Z)	ExamplePluginCUDA	
```

This works fine on Linux. I had a poke about in OpenMMCuda.lib and observe that these symbols do not exist on Windows, but are present in OpenMMCuda.so on Linux. The same applies for the OpenCL platform.

How come these symbols are not exposed on Windows, and is there a workaround?

**Comment by peastman** [comment]
I see the problem.  Library linking on Windows is really a mess, and it requires library developers to jump through some hoops.  If you look in CudaContext.h, you'll see we declare the class as

```C++
class OPENMM_EXPORT_CUDA CudaContext {
```

`OPENMM_EXPORT_CUDA` is a macro that gets defined differently depending on whether you're building the library or linking against it.  It makes linking from external code possible.  But if you scroll down to the other classes defined in that header, you'll see we forgot to include the macro.  For example,

```C++
class CudaContext::WorkThread {
```

If you add `OPENMM_EXPORT_CUDA` to that declaration and recompile the library, then your code should work.

**Comment by mikeoconnor0308** [comment]
Ah ok, that makes sense, I'll give it a go.
