### ISSUE TITLE
Understanding `state.getPotentialEnergy()` with a `CustomBondForce`

### ISSUE THREAD

**Issue by slochower** [pandegroup/openmm#1979]
I've seen https://github.com/pandegroup/openmm/issues/1463 and want to make sure I'm understanding the energy that is reported by `state.getPotentialEnergy()`. I have been trying to add a complex set of restraints and was confused when the total potential energy of the system with and without the restraints wasn't significantly different. I've made a reproducible test case that illustrates the problem: I create a `system` and `simulation` and run 100 (very short) simulations without any restraints and compare that to the same `system` and `simulation` with a hugely unfavorable restraint. The difference in potential energy should be clear, even after 10 steps.

```python
for restraint_on in [0, 1]:
    energies = []
    for run in range(100):
        prmtop = app.AmberPrmtopFile('../test/cb6-but/vac.topo')
        inpcrd = app.AmberInpcrdFile('../test/cb6-but/vac.crds')
        system = prmtop.createSystem(nonbondedMethod=app.NoCutoff, constraints=None)
        integrator = mm.LangevinIntegrator(300, 1/unit.picosecond,  0.0005*unit.picoseconds)
        simulation = app.Simulation(prmtop.topology, system, integrator, mm.Platform.getPlatformByName('Reference'))   

        if restraint_on:
            bond_restraint = mm.CustomBondForce('k * (r - r_0)**2')
            bond_restraint.addPerBondParameter('k')
            bond_restraint.addPerBondParameter('r_0')

            r_0 = 10.5 * unit.nanometers
            k = 1000 * unit.kilojoules_per_mole / unit.nanometers ** 2
            bond_restraint.addBond(1, 100, [k, r_0])
            system.addForce(bond_restraint)

        simulation.context.setPositions(inpcrd.positions)
        simulation.context.setVelocitiesToTemperature(300 * unit.kelvin, 42)
        simulation.step(10)

        state = simulation.context.getState(getEnergy=True)
        energy = state.getPotentialEnergy() / unit.kilocalories_per_mole
        energies.append(energy)
    print('{0:4.4f} +/- {1:4.4f}'.format(np.mean(energies), np.std(energies)))
```

```
-641.2306 +/- 0.5333
-641.2279 +/- 0.5498
```
I am fairly certain that the small difference is due to the random number seed of the integrator (I can get the numbers to be exactly the same if I call `integrator.setRandomNumberSeed(42)`).

Upon seeing this, I puzzled for awhile thinking that I must be implementing the restraints incorrectly. But then I printed `system.getForces()` inside the loop and can clearly see the addition of `<simtk.openmm.openmm.CustomBondForce; proxy of ...> ` when `restraint_on` is `True`. So I can confirm that the force is being added to the system. Yet the forces are exactly the same if I set the seed of the integrator, so it seems like the `CustomBondForce` is not being applied to atoms 1 and 100. 

Is there something else I should be checking? 

The coordinates I'm using can be found [here](https://github.com/slochower/pAPRika/tree/master/test/cb6-but), but I'm fairly certain this is more of a conceptual misunderstanding on my part, and not due to the specific system I'm using.

As an aside, I've seen @swails `pmd.openmm.utils.energy_decomposition`. If I call that function with `prmtop` as above (i.e., a `simtk.openmm.app.amberprmtopfile.AmberPrmtopFile`) I get a `KeyError` with loading `force_group_names[gp]` and if I call it with a ParmEd `AmberParm`, then I only get `'bond'` and `'total`' energy, so that hasn't been helpful determining if the restraints are being applied. With the caveats of https://github.com/pandegroup/openmm/issues/387 about energy decomposition, is there a way of defining a force group for just the `Custom`* forces and then getting the energy for that group? I think that would tell me if the restraints are being applied.

**Comment by jchodera** [comment]
When you create your `Simulation` using the current `system`, the GPU context is created. After that point, adding more `Force` terms won't actually affect the system being simulated.

I think this will work if you simply move the addition of your additional `Force` before creating the `Simulation`.

**Comment by slochower** [comment]
@jchodera Perfect! Just had to move that one line below. Do you happen to know if there is an easy way to pull out the restraint energy? Are you doing that with Yank?

**Comment by jchodera** [comment]
You can assign different `Force` objects to different [force groups](http://docs.openmm.org/latest/userguide/theory.html#force-groups). Use [`force.setForceGroup(index)`](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.CustomBondForce.html#simtk.openmm.openmm.CustomBondForce.setForceGroup) to set the group, and then use the `groups` optional argument in [`Context.getState()`](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.Context.html#simtk.openmm.openmm.Context.getState).

**Comment by slochower** [comment]
Thanks. I'll try setting `<simtk.openmm.openmm.CustomBondForce; proxy of ...> ` to a specific force group and checking.

**Comment by slochower** [comment]
@jchodera I think I've split my system into two force groups: one group for all the non-restraint forces and one group for the restraint(s). If I turn on the restraint, the energy skyrockets, as expected. So I know the restraint is working. However, if I try to pull out just the restraint energy, I'm always getting zero, even though the non-restraint energy is nonzero and close to, but not the same as, the total potential energy. Here is code to set the non-restraint forces to group `10` and the restraint force to group `1`:

```python
for restraint_on in [0, 1]:
    energies = []
    prmtop = app.AmberPrmtopFile('../test/cb6-but/vac.topo')
    inpcrd = app.AmberInpcrdFile('../test/cb6-but/vac.crds')
    system = prmtop.createSystem(nonbondedMethod=app.NoCutoff, constraints=None)
    integrator = mm.LangevinIntegrator(300, 1/unit.picosecond,  0.0005*unit.picoseconds)

    for force in system.getForces():
        force.setForceGroup(10)
    
    if restraint_on:
        bond_restraint = mm.CustomBondForce('k * (r - r_0)^2')
        bond_restraint.addPerBondParameter('k')
        bond_restraint.addPerBondParameter('r_0')

        r_0 = 10.5 * unit.nanometers
        k = 1000 * unit.kilojoules_per_mole / unit.nanometers ** 2
        bond_restraint.addBond(1, 100, [k, r_0])
        system.addForce(bond_restraint)
        bond_restraint.setForceGroup(1)

    simulation = app.Simulation(prmtop.topology, system, integrator, mm.Platform.getPlatformByName('Reference'))   

    simulation.context.setPositions(inpcrd.positions)
    simulation.context.setVelocitiesToTemperature(300 * unit.kelvin, 42)
    simulation.step(10)
    
    total_state = simulation.context.getState(getEnergy=True)
    total_energy = total_state.getPotentialEnergy() / unit.kilocalories_per_mole
    
    if restraint_on:
        restraint_state = simulation.context.getState(getEnergy=True, groups=1)
        restraint_energy = restraint_state.getPotentialEnergy() / unit.kilocalories_per_mole
        
        non_restraint_state = simulation.context.getState(getEnergy=True, groups=10)
        non_restraint_energy = non_restraint_state.getPotentialEnergy() / unit.kilocalorie_per_mole
    
    print('Total energy = {0:4.4f}'.format(total_energy))
    if restraint_on:
        print('Restraint energy = {0:4.4f}'.format(restraint_energy))
        print('Non-restraint energy = {0:4.4f}'.format(non_restraint_energy))
```
```
Total energy = -641.2783
Total energy = 23353.5996
Restraint energy = 0.0000
Non-restraint energy = 23931.9643
```

Notably, if I don't set the non-restraint forces to group `10`, and I call `non_restraint_state = simulation.context.getState(getEnergy=True, groups=0)` with group `0` (which is how they show up if I cycle through `force.getForceGroup`) then the restraint energy is populated and the non-restraint energy is zero (i.e., I'm not sure how to get both non-restraint energy and restraint energy to show up). Have you run into this before?

**Comment by peastman** [comment]
It needs to be `groups={10}` instead of `groups=10`.  This is a confusing bit of the API.  If you specify an integer, it gets interpreted as a set of bit flags marking which groups to include.  That's the only way to specify it in the C++ API, but in Python you can also specify a set of group indices.

**Comment by slochower** [comment]
Aha! Got it. Thanks @peastman. I think it's safe to close the issue now.

**Comment by slochower** [comment]
Apologies for commenting again @peastman, but I re-read through the original [thread](https://github.com/pandegroup/openmm/issues/387) from Lee-Ping and it's not clear to me if calling, e.g., 
```python
        restraint_state = simulation.context.getState(getEnergy=True, groups=1)
        restraint_energy = restraint_state.getPotentialEnergy() / unit.kilocalories_per_mole
```
is the most efficient way to get the restraint energy, if say, we want to monitor this quantity every 10 steps or something frequently. Is this the recommended procedure?

Also, is there a shortcut to getting the restraint *value* (in addition to the energy) if the restraint corresponds to `mm.CustomBondForce`? I noticed that someone asked something similar in https://github.com/pandegroup/openmm/issues/1970 and you commented there is `getCollectiveVariableValues()`, but I don't see that -- or anything similar -- available for `mm.CustomBondForce`.

**Comment by jchodera** [comment]
> is the most efficient way to get the restraint energy, if say, we want to monitor this quantity every 10 steps or something frequently. Is this the recommended procedure?

You're always going to slow things down if you want to retrieve information from the GPU frequently. What do you want to do with the retrieved values? Are you doing some computation on the fly, or do you just need to store the values? Is every 10 steps really less frequent than the correlation time of your system?

> Also, is there a shortcut to getting the restraint value (in addition to the energy) if the restraint corresponds to mm.CustomBondForce? I noticed that someone asked something similar in #1970 and you commented there is getCollectiveVariableValues(), but I don't see that -- or anything similar -- available for mm.CustomBondForce.

You will probably want to instead use [`CustomCVForce`](http://docs.openmm.org/development/api-python/generated/simtk.openmm.openmm.CustomCVForce.html#simtk.openmm.openmm.CustomCVForce) where the collective variable is a [`CustomCompoundBondForce`](http://docs.openmm.org/development/api-python/generated/simtk.openmm.openmm.CustomCompoundBondForce.html#simtk.openmm.openmm.CustomCompoundBondForce) that uses `distance(p1,p2)`. Be sure to [set the periodic boundary conditions appropriately](http://docs.openmm.org/development/api-python/generated/simtk.openmm.openmm.CustomCompoundBondForce.html#simtk.openmm.openmm.CustomCompoundBondForce.setUsesPeriodicBoundaryConditions)!

**Comment by slochower** [comment]
> Are you doing some computation on the fly, or do you just need to store the values? Is every 10 steps really less frequent than the correlation time of your system?

Store them, for later analysis. So nothing needs to happen on the fly. Ideally, I was thinking I could just add whatever quantities I wanted to a separate `reporter`.

> You will probably want to instead use CustomCVForce where the collective variable is a CustomCompoundBondForce that uses distance(p1,p2). Be sure to set the periodic boundary conditions appropriately!

Okay, I'll look into that. Presumably there is a way to get it to work with`mm.CustomAngleForce` and `mm.CustomTorsionForce` too.

**Comment by jchodera** [comment]
> Okay, I'll look into that. Presumably there is a way to get it to work withmm.CustomAngleForce and mm.CustomTorsionForce too.

I'd just define a [`CustomCompoundForce`](http://docs.openmm.org/development/api-python/generated/simtk.openmm.openmm.CustomCompoundBondForce.html#simtk.openmm.openmm.CustomCompoundBondForce) for whatever you wanted. It supports angles and torsions too!

**Comment by slochower** [comment]
@jchodera Correct me if I'm wrong, but we want the actual value of the restraints (not just the energy) during the simulation so we can run, e.g., MBAR to evaluate the restraint in all the other windows' Hamiltonians. Does it make sense to simply run each window's simulation without pulling the restraint information off the GPU, and then post-process to get the value of the restraints for each window?
