### ISSUE TITLE
getting force components on each atom

### ISSUE THREAD

**Issue by jht0664** [pandegroup/openmm#1989]
Hello,

I am wonder how to get force components on each atom.
I am going to calculate pressure tensor (see [http://lammps.sandia.gov/doc/compute_pressure.html](http://lammps.sandia.gov/doc/compute_pressure.html))and then viscosity via Green-Kubo equation, so I need to get velocity and force on each atom for pressure tensors.
However, I am not sure if it is possible to get "force components" on each atom, e.g. f_x(i); x-component of force on i-th atom, during simulation.
I expect that to run the simulation should calculate the force components every time step,
thus I guess it might be a way to get the forces. 
Would you give any advices on it?

**Comment by Lnaden** [comment]
If you only need the force acting on each atom you can tell the `Context` to fetch the forces at the same time as the velocities, then call `getForces` on the `State` object to get the per-particle, per-dimension forces in kJ/(nm mol)

The Python API calls would look like
`Context.getState(getVelocities=True, getForces=True).getForces()`
OR
`Context.getState(getVelocities=True, getForces=True).getForces(asNumpy=True)`

Returns a list of tuples or Numpy array of shape `[n_atoms, 3]` where each row is the sum of the forces acting on that particle in the (x,y,z) unit vector.

You don't need `getVelocities=True` to also call `getForces=True`, but since you are wanting both, call and store `getState` first with those keywords and then you can use the same `State` object to then call `getForces)_` and `getVelocities()`

**Comment by jht0664** [comment]
Wow, so clear. Thank you so much!

**Comment by mkrompiec** [comment]
@jht0664 Hi, I am interested in your approach. Have you managed to compute pressure tensors in OpenMM and use the Green-Kubo equation? If so, would you consider sharing some code snippets?

**Comment by csu1505110121** [comment]
> If you only need the force acting on each atom you can tell the `Context` to fetch the forces at the same time as the velocities, then call `getForces` on the `State` object to get the per-particle, per-dimension forces in kJ/(nm mol)
> 
> The Python API calls would look like `Context.getState(getVelocities=True, getForces=True).getForces()` OR `Context.getState(getVelocities=True, getForces=True).getForces(asNumpy=True)`
> 
> Returns a list of tuples or Numpy array of shape `[n_atoms, 3]` where each row is the sum of the forces acting on that particle in the (x,y,z) unit vector.
> 
> You don't need `getVelocities=True` to also call `getForces=True`, but since you are wanting both, call and store `getState` first with those keywords and then you can use the same `State` object to then call `getForces()` and `getVelocities()`
> 
> _edit_: fixed typo

Hi Lnaden,

It seems just worked for the current state, how to store the velocities and forces of each frames?

Best,
Qiang

**Comment by Lnaden** [comment]
You would have to call these functions after each call of `step(1)` of the simulation, or setup your `Reporter` class attached to the `Simulation` class to report every time step. This is a very slow operation as passing state data that frequently is an expensive step relative to iterating the simulation for another `step`. 

Depending on your use case, it may be possible to get relevant values through a `CustomIntegrator`, but, this particular issue is almost 4 years old at this point; If you want to have a discussion on your use case, please feel free to open a new issue, @csu1505110121. If you want to tag me in that, make sure you use "@lnaden" so it pings me more directly. Thanks.

**Comment by csu1505110121** [comment]
> You would have to call these functions after each call of `step(1)` of the simulation, or setup your `Reporter` class attached to the `Simulation` class to report every time step. This is a very slow operation as passing state data that frequently is an expensive step relative to iterating the simulation for another `step`.
> 
> Depending on your use case, it may be possible to get relevant values through a `CustomIntegrator`, but, this particular issue is almost 4 years old at this point; If you want to have a discussion on your use case, please feel free to open a new issue, @csu1505110121. If you want to tag me in that, make sure you use "@Lnaden" so it pings me more directly. Thanks.

Thank you for your reply, a new issue is open and hope to see you there

**Comment by peter-zhang-chem** [comment]
Hey, I am wondering if there is a way to get the atom pair-wise force in openMM?

**Comment by peastman** [comment]
No, it only returns the total force on an atom, not each individual interaction.  If you just want one pair, of course, you can easily calculate it yourself.  The equations are in http://docs.openmm.org/latest/userguide/theory/02_standard_forces.html.

**Comment by peter-zhang-chem** [comment]
I see, thanks Peter. I wanted to double check before doing that, I am trying to get the atom pair-wise forces at each frame for some calculations and wanted to see if I can get these values without recalculating them during my simulation. How much slow down would you anticipate if I am recalculating these atom pair-wise forces (perhaps less frequency than my actual simulation output frequency)?

**Comment by peastman** [comment]
That depends how many you compute and how often!  Computing one pair every 1000 steps will have negligible cost.  Computing 1000 pairs every step will be much more expensive.

**Comment by peter-zhang-chem** [comment]
Yes, that makes sense. I am thinking to compute around 5000 pairs every 1,000 steps.

Another approach would be to compute them numerically from the trajectory after the simulation is finished. Do you see any problem with this approach instead of computing them while running the simulation?

**Comment by peastman** [comment]
That would be fine too.

**Comment by peter-zhang-chem** [comment]
Thank you so much

**Comment by ShinyEgg-pku** [comment]
Hi! I want to know if the getForce command obtains conservative force, and if it also includes viscous force and random force?

**Comment by ShinyEgg-pku** [comment]
I see. Thank you so much!
