### ISSUE TITLE
OpenMM not recognizing CUDA platform

### ISSUE THREAD

**Issue by ocmadin** [pandegroup/openmm#1991]
I am trying to set up OpenMM with CUDA on a new machine (RHEL 7.4) and have been unable to get OpenMM to recognize the CUDA platform (when running `simtk.testInstallation` it only lists reference, CPU, and OpenGL).

I've added the following lines to my `.bashrc`:

```
export CUDA_HOME=/usr/local/cuda-9.0/
export CUDA_INCLUDE_DIR=/usr/local/cuda-9.0/include
export CUDA_LIB_DIR=/usr/local/cuda-9.0/lib64
export OPENMM_CUDA_COMPILER=/usr/local/cuda-9.0/bin/nvcc
export PATH=/usr/local/cuda-9.0/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64:$LD_LIBRARY_PATH
```

Is there anything else I might need to do for OpenMM to recognize CUDA?
My CUDA version is 9.0.176, and my NVIDIA Driver Version is 387.26.  The driver itself is a GeForce GTX 1080.
@jchodera Bryce said you might have some insight into this issue.

-Owen

**Comment by peastman** [comment]
CUDA releases are not binary compatible with each other, so each version of OpenMM only works with the CUDA version it was compiled against.  OpenMM 7.1 binaries were compiled against CUDA 8.0, so they don't work with 9.0.  The new OpenMM 7.2 release candidate is compiled against CUDA 9.0.  See https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=8493&p=0&start=0&view=&sid=33a658539a29d2ec6c1fde41ea02c3ca.  You also can always recompile from source with whatever CUDA version you want.

**Comment by ocmadin** [comment]
Thanks, this was exactly my issue. Updated to OpenMM 7.2 and it's now recognizing CUDA.
