### ISSUE TITLE
Have ForceField.createSystem() accept switchDistance argument, and raise exception if some arguments are unused

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1994]
cc: https://github.com/choderalab/openmm-forcefields/pull/61#issuecomment-366043877

It would be useful to have `ForceField.createSystem()` accept a `switchDistance` argument (as `CharmmPsfFile.createSystem()` does) to pass on to [`LennardJonesGenerator`](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py#L2342) and [`NonbondedGenerator`](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py#L2282).

Also, it seems like we should really have a mechanism for force generators to flag which options they actually used, and raise an exception if some option was provided that isn't actually used anywhere. That will prevent programming errors.

**Comment by peastman** [comment]
`AmberPrmtopFile.createSystem()` also has this feature already.
