### ISSUE TITLE
Incompatibility with newer clang versions

### ISSUE THREAD

**Issue by tristanic** [pandegroup/openmm#1997]
I'm not going to call this a bug, exactly - more of a note because it was really frustrating getting to the bottom of it.

I have a C++ wrapper class which takes the pointer to an existing Context from Python (the point being to run Integrator.step() in a separate thread, but that's not relevant to this issue). If, within this class I have:

```
OpenMM::Integrator& integrator() { return _context->getIntegrator();}

void step(size_t steps)
{
    size_t steps_done = 0;
    _starting_state = _final_state;
    for (; steps_done < steps; )
    {
        size_t these_steps, remaining_steps = steps-steps_done;
        if (remaining_steps > STEPS_PER_VELOCITY_CHECK) {
            these_steps = STEPS_PER_VELOCITY_CHECK;
        } else {
            these_steps = remaining_steps;
        }
        integrator().step(these_steps);
        steps_done += these_steps;
        auto state = _context->getState(OpenMM::State::Velocities);
        if (overly_fast_atoms(state.getVelocities()).size() >0)
        {
            _unstable = true;
            break;
        }
    }
    _final_state = _context->getState(OpenMM::State::Positions + OpenMM::State::Velocities);
}
```
... it works just fine on a Linux machine. But, when compiled on a macOS Sierra machine using clang-802.0.42 and linked against the 7.1.1 OpenMM release, when called it runs through the loop with our raising any exceptions, but far too fast and without making any changes to atom positions (_final_state and _starting_state are identical). Then, attempting to call Integrator.step() through the standard OpenMM Python leads to a hard crash (EXC_BAD_ACCESS). Somewhat surprisingly, minimisation still works fine. After much wailing and gnashing of teeth, it appears to boil down to some unflagged backwards incompatibility - recompiling OpenMM on the same machine makes the problem go away.

Doesn't appear to be specific to a Platform - I tried both CPU and OpenCL platforms and got the same behaviour.

**Comment by peastman** [comment]
I don't recognize this as any incompatibility I'm aware of.  It sounds like some sort of miscommunication between the Python and C++ layers, such that the wrong value for a pointer is getting received.  Did you install OpenMM through conda?  It's usually pretty good about making sure everything is compiled in a compatible way.

**Comment by tristanic** [comment]
I didn’t actually install OpenMM myself. I’m using the build distributed with ChimeraX, which to my understanding came from the OpenMM zip installer.

I agree it’s very odd behaviour. The only pointer I hand from Python to the C++ layer is to the Context, and everything but the Integrator still seems to work. I can get and set States with coordinates remaining sane, the minimizer does its thing, ... it’s just the Integrator (even more specifically, its step() function) that gets borked. I narrowed it down to show that it’s specifically the act of calling step() via my C++ class that broke it, and even after that calling various Integrator functions other than step() through Python was still fine - only step() led to a crash.

After recompiling OpenMM, for a toy simulation of IGF-I (70 residues in implicit solvent) I’m getting steady 60fps graphics with ~10 50-step simulation updates a second - on a MacBook Air, no less!

 
 
Tristan Croll
Research Fellow
Cambridge Institute for Medical Research
University of Cambridge CB2 0XY

**Comment by tristanic** [comment]
Could you tell me which version of clang is being used to compile the official builds at present? Looks to me like my best bet is to build my extensions with a matching version. Building against the official OpenMM 7.1.1 release (note: should be updating to 7.2.1 soon, once my collaborator finds the time), I now get the following upon trying to load it from Python:

`error: dlopen(/Users/tic20/isolde/isolde/src/openmm/../openmm.cpython-36m-darwin.so, 6): Symbol not found: __ZN6OpenMM7Context12reinitializeEb`

Once again, rebuilding OpenMM on the same machine fixes the problem. My collaborators in the ChimeraX team are really keen to avoid having to compile OpenMM from source in their builds, so I need to find an alternative solution.

**Comment by tristanic** [comment]
Turns out this was (highly embarrassingly) all my fault. I hadn't properly rolled back some changes to Context.h after some tinkering.
