### ISSUE TITLE
Cannot enable executable stack as shared object 

### ISSUE THREAD

**Issue by samarjeet** [pandegroup/openmm#2001]
Hi , I am trying to test with a very simple basic line 

``
#include <caffe2/core/init.h>
#include <caffe2/core/net.h>
#include <iostream>

namespace caffe2 {
    void run() {
        std::cout << "Hello world\n" ;
        Workspace workspace("tmp");
    }
}

int main(int argc, char **argv) {
    caffe2::run();
}

I compile it with 

>  g++ -std=c++11  -L/usr/local/lib -v testCaffe2.cpp -lcaffe2

The code compiles but has problem with loading shared libraries at runtime. 
>  ./a.out: error while loading shared libraries: libcaffe2.so: cannot enable executable stack as shared object requires: Invalid argument

**Comment by Lnaden** [comment]
I might be missing something, but is this issue posted on the wrong repo? Did you mean instead to post this on Caffe2's repo instead of OpenMM?

**Comment by samarjeet** [comment]
Sorry..wrong repo.
