### ISSUE TITLE
Disulfide bonds are broken in Amber14

### ISSUE THREAD

**Issue by peastman** [pandegroup/openmm#2003]
There's a critical bug in the Amber14 force field in OpenMM 7.2: disulfide bonds don't work.  The CYX template is missing the `<ExternalBond>` tag for SG.

Given the seriousness of this and the fact that 7.2 is already out, I'm inclined to add the missing tag by hand and push out 7.2.1 ASAP.

**Comment by jchodera** [comment]
We didn't have any disulfide containing proteins in our tests with @rafwiewiora, so we must have missed this. 

I agree that adding the tag by hand is a good idea for now. Can you provide an example disulfide containing PDB we can add to the tests so we can get this fixed in openmm-forcefields too?

I'm stuck in meetings this afternoon and unfortunately won't be able to join for the call, but could look into this ASAP.

**Comment by peastman** [comment]
Here's the forum thread where the problem came up:

https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=8704&p=24008

The user there posted a file.  But really, absolutely anything containing a disulfide will work equally well.  Since we ran into exactly the same problem in CHARMM36, I assume you added something with disulfides to the tests for that?

By the way, it would be really useful if you monitored the forum.  A lot of problems first get reported there, not here.

**Comment by peastman** [comment]
Fixed by #2004.

**Comment by jchodera** [comment]
Thanks! I found the problem (see https://github.com/ParmEd/ParmEd/issues/964). 

There may be other residues with this issue, so I'll regenerate these tonight and we can `diff` the files to see if another update is needed.

**Comment by jchodera** [comment]
@peastman : can we keep this open until we're sure there are no other residues missing connections?

For example, I bet the same problem exists in CHARMM.

**Comment by jchodera** [comment]
Correction: CHARMM handles disulfides through patches, so I don't think that's a worry.

**Comment by peastman** [comment]
Reopening until we're sure everything is fixed.

**Comment by jchodera** [comment]
@peastman : See this PR: https://github.com/choderalab/openmm-forcefields/pull/62

**Comment by peastman** [comment]
A release candidate with the changes is now posted.

**Comment by peastman** [comment]
7.2.1 is now released.
