### ISSUE TITLE
Error synchronizing on event for CCMA: CUDA error

### ISSUE THREAD

**Issue by rcrehuet** [pandegroup/openmm#2018]
I am running a simulation with the Charmm FF in explicit solvent. NVE ensemble. After having run for several minutes I get the following error. I've tried several times (even changing time step) and sooner or later, it happens:

```
Traceback (most recent call last):
  File "production.py", line 90, in <module>
    sim.step(steps)
  File "/home/ramon/miniconda3/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 132, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/home/ramon/miniconda3/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 194, in _simulate
    self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
  File "/home/ramon/miniconda3/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 14643, in step
    return _openmm.LangevinIntegrator_step(self, steps)
Exception: Error synchronizing on event for CCMA: CUDA error (700) at /home/ramon/OpenMM-7.1.1-Source/platforms/cuda/src/CudaIntegrationUtilities.cpp:736
Exception ignored in: <built-in function delete_Context>
Exception: Error deleting array bondParams: CUDA error (700)
Exception ignored in: <built-in function delete_LangevinIntegrator>
Exception: Error deleting array langevinParams: CUDA error (700)
```

Is this a bug? A problem with the CUDA driver (I'm using CUDA 8.0)? A problem with the stability of the simulation? I can provide more details of the simulation, my hardware or my system.

**Comment by peastman** [comment]
It's hard to guess.  Something got messed up on the GPU, but the CUDA error code doesn't tell us much beyond that.  A few questions:

- What OpenMM version are you using?
- How did you install it (conda, build from source, etc.)?
- What OS are you running on?  (I assume some Linux distro based on the paths.  Which one?)
- What GPU?

**Comment by rcrehuet** [comment]
I'm using OpeMM version 7.1.1. I compiled it from source because the conda build was not detecting the CUDA library. I think this was because my CUDA version is different from the one that the conda build was compiled on. My CUDA version is 8.0. 
Running on a CentOS 7.0.
My GPU is a GeForce GTX 1080 Ti.
Do you think installing CUDA 9.1 and recompiling OpenMM could be a possible way to solve the problem?

**Comment by jchodera** [comment]
The current `conda` release (`openmm==7.2.1`) is compiled against CUDA 9.0. That will hopefully resolve your issue, but please let us know if it doesn't!

**Comment by peastman** [comment]
Upgrading to the latest release (7.2.1) is definitely the place to start.  You can either use the conda build with CUDA 9.0, or compile from source which should work with any recent CUDA version.

**Comment by rcrehuet** [comment]
Sorry, I've been unavailable for a week. 
The latest CUDA version is 9.1. You suggest 9.0 because openmm uses 9.0? So even within subversions, one has to match the one openmm was compiled against?

**Comment by jchodera** [comment]
If you want to use the CUDA platform, you will need to use the same version of the CUDA Toolkit that OpenMM was compiled against. In this case, the current conda release (7.2.1) is compiled against CUDA 9.0, not 9.1. The OpenCL platform should work just fine with CUDA 9.1.

We're exploring ways to deploy OpenMM conda packages built against different versions of CUDA, though this is not trivial. That discussion is going on here: https://github.com/pandegroup/openmm/issues/1969

**Comment by rcrehuet** [comment]
I installed CUDA 9.0 and OpenMM 7.2.1 in another machine with exactly the same hardware and the problem is gone. I run the same simulation, and in one case I got the error at step 384000 and in the second case it has been running one order of magnitude more steps (up to step 7229000, when I killed it).
So, unless I have a hardware problem I can say the problem is solved.
