### ISSUE TITLE
PDBFixer's addSolvent throws protein hydrogens willy nilly 

### ISSUE THREAD

**Issue by ljmartin** [pandegroup/openmm#2025]
[pdbfixer_hydrogens.tar.gz](https://github.com/pandegroup/openmm/files/1831854/pdbfixer_hydrogens.tar.gz)
I noticed the developers mention a lack of feedback from beta testers wrt openmm7.2, so Im just gonna keep posting any issues as they come up...

PDBFixer adds missing atoms and hydrogens to a protein from OPM (pdb 3jae) no problem. When I use addSolvent, the protein hydrogens get exploded away from the protein. 

I realise this is not a protein that should be fully hydrated. But the addMembrane(POPC) command struggles on for a bit and exits with 'Killed'. Have included the script to reproduce.

**Comment by jchodera** [comment]
cc: @pgrinaway who has observed similar issues.

**Comment by peastman** [comment]
I just tried running your pdbfixer_solvate.py script, then opened the resulting solvate.pdb file in VMD.  It looks fine as far as I can tell, with protein hydrogens right where they should be.

![image](https://user-images.githubusercontent.com/4379786/37732466-503fae6c-2d02-11e8-9be7-9b985c40b927.png)

Can you give any more information about what I should be looking for, or how to reproduce it?

**Comment by ljmartin** [comment]
Im sorry I wasn't more thorough with that upload, but it looks like I can run it too without error now. Could you run the addMembrane script?

**Comment by peastman** [comment]
> Could you run the addMembrane script? Mine still exits with 'Killed'

I just posted a pull request (#2072) that might help with this.  I believe it was probably caused by running out of memory.  I made some changes that reduce the memory requirements while building membranes.

**Comment by ljmartin** [comment]
It was super effective, thanks @peastman !

A couple of P.S.s:
- I was getting NaN's in the first step of the protein scaling process. To fix this I ended up reducing the timestep by ten times and increasing the number of steps by ten times. The choice of 1000 steps of scaling in the original g_membed paper seems arbitrary - with GPU it doesn't cost much time to increase it anyway. 
- Is the new modeller.py available in conda? I ended up just replacing my copy of modeller.py with the updated one. Because of this maybe there's another script I'm missing, but I had to remove all references to `residue.insertionCode` because `Residue object has no attribute insertionCode`.
cheers again

**Comment by peastman** [comment]
> Is the new modeller.py available in conda?

Development builds for Linux and Mac are produced every night.  You can get the latest one with

```
conda install -c omnia/label/dev openmm
```

`insertionCode` is from another PR that was just merged yesterday.

**Comment by ljmartin** [comment]
I ran that command (after uninstalling and removing any trace of existing openmm) but I'm still getting the 'old' modeller.py. On the pull request, 2 out of the 3 checks did not pass - could that be the reason?

**Comment by peastman** [comment]
According to https://anaconda.org/omnia/openmm/files, the dev builds got rebuilt about 14 hours ago, so they should be up to date.  How are you concluding that they aren't?

> On the pull request, 2 out of the 3 checks did not pass - could that be the reason?

No, that's unrelated.  AppVeyor was temporarily broken (fixed by #2074), and there was one random failure of an OpenCL test case.  Everything else passed.

**Comment by ljmartin** [comment]
Maybe Im doing it wrong but for me, there is no /home/lewis/miniconda3/lib/python3.6/site-packages/simtk/ directory before running `conda install -c omnia/label/dev openmm`. After running that, `/home/lewis/miniconda3/lib/python3.6/site-packages/simtk/openmm/app/modeller.py` doesn't have any of the things you added like `import gc` or the `del` statements. It DOES have older lines like 
```
# Add membrane patches.  We exclude any water that is within a cutoff distance of the *actual* protein,
# and any lipid that is within a cutoff distance of the *scaled* protein.  We also keep track of how
```
and so on

**Comment by nitroamos** [comment]
@ljmartin maybe you didn't force the upgrade?

it looks like although openmm is deployed every night, the version number doesn't change, so conda doesn't know it's different. I tried this just now to force the upgrade:

`conda install -c omnia/label/dev openmm -f`

and I'm seeing changes that I was looking for. starting to do some testing now...

**Comment by ljmartin** [comment]
OK so I had left old openmm files in the miniconda/pkgs directory. Removing those forced conda to download the new version. Thanks!
