### ISSUE TITLE
accessing Cpu platform data

### ISSUE THREAD

**Issue by egallicc** [pandegroup/openmm#2042]
I started working on the CPU version of the [AGBNP plugin](https://github.com/egallicc/openmm_agbnp_plugin). The goal is to eventually run on the KNL processors of Stampede2 (let's not get on the merits of this "XSEDE-imposed" task).

Anyway, I have encountered problems accessing PlatformData from the plugin to, for example, set the number of processors. Later on, I would like to access the neighbor list as well.

I know PlatformData is initialized properly:

In `CpuPlatform.cpp`:
```
CpuPlatform::PlatformData::PlatformData(int numParticles, int numThreads) : posq(4*numParticles), threads(numThreads),
        neighborList(NULL), cutoff(0.0), paddedCutoff(0.0), anyExclusions(false) {
      numThreads = threads.getNumThreads();
    std::cout << "CpuPlatform::PlatformData::PlatformData(): " << "numThreads =" << numThreads << std::endl;
...
}
```

For example, gives numThreads=4. 

However accessing, presumably, the same data structure from the plugin returns a different number of processors:

In the plugin:
```
double CpuCalcAGBNPForceKernel::execute(ContextImpl& context, bool includeForces, bool includeEnergy) {
    CpuPlatform::PlatformData& data = CpuPlatform::getPlatformData(context);
    numThreads = data.threads.getNumThreads();
    cout << "Number of Threads: " << numThreads << endl;
    ...
  }
```
gives numThreads=0.

What could I be doing wrong?

**Comment by peastman** [comment]
I don't see anything obviously wrong there.  The only explanation that comes to mind is that somehow they must be different objects.  Once the number of threads is initialized for a `ThreadPool`, it shouldn't ever change.  You could try printing out the address of the `PlatformData` both in its constructor

```c++
printf("in constructor %p\n", this);
```

and when you use it

```c++
print("in execute %p\n", &data);
```

to make sure they're really the same.  Looking through the regular kernels for the CPU platform, I notice they don't use `getPlatformData()`.  Instead, the kernel factory passes it as an argument to the constructor.  But I don't see any reason it wouldn't work.

**Comment by egallicc** [comment]
It turns out that I had a silly typo in my actual code, which your suggestion helped uncover. Thank you for the reassurance that the approach of accessing PlatformData is correct.

**Comment by peastman** [comment]
Glad it was something simple.
