### ISSUE TITLE
Error when setting switchDistance in createSystem

### ISSUE THREAD

**Issue by JoaoRodrigues** [pandegroup/openmm#2043]
There seems to be a small typo in the `forcefield.py` file around line 2451 ([link](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py#L2451)). When checking for `switchDistance`, it tries to set parameters on a non-existing variable `force`, instead of `self.force`. This breaks usage of switching functions, e.g. in CHARMM.

**Comment by peastman** [comment]
Fixed by #2044.
