### ISSUE TITLE
TestCudaNonbondedForce error on Nvidia Volta architecture

### ISSUE THREAD

**Issue by kelnv** [pandegroup/openmm#2046]
Hi Peter,

The following error occurs with the current master HEAD if running on V100/GV100 or Titan V (on Pascal P100 and previous are successful)
./TestCudaNonbondedForce "single"
exception: Assertion failure at TestCustomNonbondedForce.h:1039.  Expected 4280.26, found 4289.31
(Same error for the openCL version on Nvidia GPUs)

The commit 2305f05 from PR 2013 is  the last commit that can pass the test on Volta GPUs.
What is introduced since then? Related to the neighbourlist ?

A simple fix is to modify the CudaContex.cpp file:
Adding:
>    if(major == 7){
>       major = 6;
>       minor = 0;
>    }

just before:
>     gpuArchitecture = intToString(major)+intToString(minor);

This strongly indicates that the issue is related to the independent thread scheduling on Volta GPUs.
Do you recall any code that is not ported to Volta/Cuda9 yet? Normally this happens when code is doing shfl or shared memory based reduction. But I saw you have already ported shfl to shfl_sync.

Ke Li

**Comment by peastman** [comment]
As of about an hour ago, I finally have a working computer with a Titan V set up!  (The GPU came over a month ago.  It's been painful.)  I'll look into this shortly.

**Comment by kelnv** [comment]
Thanks! Same issue for OpenCL test but the cause would be the same. I suspect it's related to independent thread execution, but could not locate where the program went wrong.
