### ISSUE TITLE
Is it possible to distinguish between vector components in CustomIntegrator?

### ISSUE THREAD

**Issue by dextorious** [pandegroup/openmm#2050]
Consider, for instance, the implementation of the basic velocity verlet integrator, which contains code such as:
```
self.addComputePerDof("v", "v+0.5*dt*f/m")
self.addComputePerDof("x", "x+dt*v")
self.addComputePerDof("x1", "x")
self.addConstrainPositions()
self.addComputePerDof("v", "v+0.5*dt*f/m+(x-x1)/dt")
```
I would like to extend the per DOF expressions with terms that depend on different components of the positions and velocities, for instance, scale the `y` and `z` components of the velocity by some global variable (while leaving the `x` component untouched), etc. Is this possible?

The motivation for this question comes from trying to implement external forces that depend on the velocities as well as the positions, which means I cannot use the normal API for adding custom forces.

**Comment by jchodera** [comment]
This is currently not possible with `CustomIntegrator`, but I agree that it would be a very useful feature!

**Comment by dextorious** [comment]
Is there any reasonable workaround currently possible through some other means? I don't mind dropping down to the C++ API and investing more effort as this is currently completely blocking my attempt to introduce handling external magnetic fields (via Lorentz forces).

**Comment by peastman** [comment]
You can do this by defining a per-dof variable, then setting its value for each atom to have the right x, y, and z scale factors.  Then you can write `v*scale`, and it will scale the different components by different amounts.

**Comment by dextorious** [comment]
I may have given an overly trivialized example. The issue is that the (additive) acceleration caused by the Lorentz force (`q/m * (v x B)`) requires mixing the velocity components due to the cross product. For instance, for a stationary magnetic field in the x direction `B = (Bx, 0, 0)` you would have an additional acceleration term `q/m * (0, vz*Bx, -vy*Bx)`. I hope I'm missing something, but I don't see a way to handle that with a per-dof variable without the ability to distinguish between the vector components.

**Comment by jchodera** [comment]
Could we simply add a cross-product operation `cross(a,b)`?

**Comment by peastman** [comment]
Right, that isn't currently possible.  We've discussed this problem a bit before and considered adding "per-particle" computation steps that would support operations like `cross()` and `dot()`.  See #1445.  It does seem like a possibility.  The implementation could be complex, though, since you'd almost certainly want to mix vector and scalar quantities in a single expression, which means incorporating a type system into the code for parsing and evaluating expressions.

**Comment by dextorious** [comment]
#1445 seems stalled. In the meantime, after a quick glance at the [plugin example code](https://github.com/peastman/openmmexampleplugin) it seems like I could just write a LorentzForcePlugin (it looks like I'd have full access to the vector components there) and then just use it like any other force with any of the existing integrators. Does that make any sense as an approach to this problem or am I missing some obvious issues?

**Comment by peastman** [comment]
Doing it as a force should work fine.

**Comment by peastman** [comment]
I've been thinking about how to implement per-particle computations in ways that wouldn't be too complicated.  I think I have an idea that might work.  Let me describe it, and you can tell me if you see any problems with it.

The main simplification would be that *all* quantities in the expression would be vectors.  If you write a constant, that really means a vector whose components are all equal to that constant.  Operators would be applied component-wise in the normal way.  In most cases, this should produce the expected result.  For example, if you wrote `v/2`, that would be interpreted as `(v_x, v_y, v_z)/(2, 2, 2)`, which would then evaluate to `(v_x/2, v_y/2, v_z/2)`.

We would provide `dot()` and `cross()` functions that would act in the expected way, except remember that the `dot()` function is really returning a vector, each component of which equals the dot product.  We would also provide a `vector()` function that takes three arguments and assembles a new vector from their components: `vector(a, b, c) = (a_x, b_y, c_z)`.  We also could have functions `_x()`, `_y()`, and `_z()` for extracting a single component of a vector and returning it in all three components of its output,  For example, you asked how to compute `q/m * (0, vz*Bx, -vy*Bx)`.  That could be done with the following expression:

```
q/m * vector(0, _z(v)*_x(B), -_y(v)*_x(B))
```

**Comment by jchodera** [comment]
This looks awesome, @peastman.

Tagging @pgrinaway and @maxentile to take a look.

**Comment by dextorious** [comment]
@peastman That looks wonderful and would solve my issue completely. Can't wait to try it out.

**Comment by peastman** [comment]
@pgrinaway and @maxentile would this design work for you?

**Comment by jchodera** [comment]
I've just pinged them internally to look at this and comment, but this looks good to me!

If I understand correctly, this would presumably also allow us to compute matrix-vector products as
```
vector(dot(a,x), dot(b,x), dot(c,x))
```
which corresponds to the product of the matrix formed by row vectors `a`, `b`, and `c` applied to the vector `x`.

**Comment by peastman** [comment]
I have an initial implementation in #2057.  Only the reference platform is done so far, but that should be enough for you to try it out.

**Comment by dextorious** [comment]
I've been trying out #2057, got a custom integrator up and running with the new functionality - it's a simple two half-step Verlet algorithm that takes into account an additional acceleration that's a simple per-DOF variable with the expression `"q / m * cross(v,B) + q / m * E"`, where `B` and `E` are also given per-DOF. I also tried out the `vector` syntax and the component access functionality, so far everything seems to be working great!

Some caveats: I haven't tried the Python API yet, nor have I properly verified the results physically. Those things are next on my list, but so far it's looking very good indeed.

**Comment by peastman** [comment]
Great, thanks!  I'll work on the CUDA and OpenCL versions this week.

**Comment by dextorious** [comment]
Awesome! I'll keep using the reference platform for now, will let you know if I find any bugs.

**Comment by peastman** [comment]
The OpenCL platform is now working too.

**Comment by dextorious** [comment]
That's great, I'll try it out today! No issues with the CPU/Reference platforms so far.
