### ISSUE TITLE
Retrieving the current value of a collective variable?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#2058]
Is there a way to retrieve the current value of collective variables (as used by [`CustomCVForce`](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.CustomCVForce.html#simtk.openmm.openmm.CustomCVForce) in a simulation context? Can this be done with force groups? Or perhaps we could use a way to retrieve them through `State`?

**Comment by peastman** [comment]
`getCollectiveVariableValues()`

**Comment by jchodera** [comment]
Ah! I had totally missed that! Thanks!

For posterity, docs are [here](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.CustomCVForce.html#simtk.openmm.openmm.CustomCVForce.getCollectiveVariableValues).
