### ISSUE TITLE
installing openmm

### ISSUE THREAD

**Issue by hrg1000** [pandegroup/openmm#2059]
Dear All,

I am trying to install openmm as sudo so that other users from our research group can also use it. I have two problems:

1) It is being installed in subdirectories in the conda directory (in the environment I have made conda/miniconda2/envs/openmm_env/ ]. I want the users to be able to easily access the openmm program. Can I specify an installation directory? [I install using conda install -c omnia openmm ] So far I have just put a link in a directory I made: openmm -> /home/data/conda/miniconda2/envs/openmm_env/share/openmm/
2) When I tried running the example "python simulatePdb.py", as administrator and not as sudo I get the error "Permission denied: 'output.pdb'" . Which permissions do I need to change for the program to work for all users?

Please note I have successfully installed it as a specific user, I want to let all users have access.

Thank you,

**Comment by hrg1000** [comment]
Please note I have successfully installed it as a specific user, I want to let all users have access.

**Comment by peastman** [comment]
1. OpenMM isn't really a "program" as such, it's a collections of libraries.  If all users have access to that Python and the libraries installed into it, they should be able to use it.  Trying starting the python interpreter and typing `import simtk.openmm`.  Does that work for all users?

2. In this case you're trying to run one of the example scripts.  It tries to write its output to whatever is your current working directory.  It sounds like you're running it from a directory where you don't have write permission?  Try copying `simulatePdb.py` and `input.pdb` to your home directory and run it there.

**Comment by hrg1000** [comment]
Thank you so much, this solved the problem!

**Comment by peastman** [comment]
Glad to hear it!
