### ISSUE TITLE
OpenMM restraints and constraints didn't work

### ISSUE THREAD

**Issue by Manojcu** [pandegroup/openmm#2070]
Hello All,
I'm new to openMM and I'm tried to run openMM simulation where I wanted  to restraint a specific metal-amino acid bond.
But  my script didn't work. 
Then I tried to constraint the distance but it also didn't work. 
Could you please let me know what is wrong with my script?

Best regards,
Manoj

My script is here:
..........................................
----------------------------------------------------
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from simtk import unit
from sys import stdout, exit, stderr

# Load CHARMM files
psf = CharmmPsfFile('step1_pdbreader.psf')
pdb = PDBFile('step1_pdbreader.pdb')

toppar_files = ['toppar/par_all36m_prot.prm', 'toppar/top_all36_prot.rtf',
				 'mx3/mx3.prm', 'mx3/mx3.rtf', 
				 'toppar/toppar_water_ions.str']

params = CharmmParameterSet(*toppar_files)

# Create an openmm system by calling createSystem on psf
system = psf.createSystem(params, nonbondedMethod=NoCutoff,
         nonbondedCutoff=1*nanometer, constraints=HBonds)
integrator = LangevinIntegrator(300*unit.kelvin,   # Temperature of head bath
                                1/unit.picosecond, # Friction coefficient
                                0.002*unit.picoseconds) # Time step
# prepare simulation
platform = Platform.getPlatformByName('OpenCL')

simulation = Simulation(psf.topology, system, integrator, platform)
simulation.context.setPositions(pdb.positions)
#adding restrains
my_restraints = HarmonicBondForce()
my_restraints.addBond(469, 41, 3.13*unit.angstroms, 1000*unit.kilocalories_per_mole/unit.angstroms**2)
system.addForce(my_restraints)

# minimize
print('Minimizing...')
simulation.minimizeEnergy()

# equilibrate for 100 steps
simulation.context.setVelocitiesToTemperature(300*unit.kelvin)
print('Equilibrating...')
simulation.step(100)

# Set up the reporters to report energies every 1000 steps.
simulation.reporters.append(app.DCDReporter('trajectory1.dcd', 50))
simulation.reporters.append(StateDataReporter(stdout, 1000, step=True,
                            potentialEnergy=True, temperature=True))
# run simulation
simulation.step(10000)

------------------------------------
------------------------------------
I tried to constraint it using:

#add constraint
system.addConstraint(469, 41, 3.13*unit.angstroms)
------------
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from simtk import unit
from sys import stdout, exit, stderr

# Load CHARMM files
psf = CharmmPsfFile('step1_pdbreader.psf')
pdb = PDBFile('step1_pdbreader.pdb')

toppar_files = ['toppar/par_all36m_prot.prm', 'toppar/top_all36_prot.rtf',
				 'mx3/mx3.prm', 'mx3/mx3.rtf', 
				 'toppar/toppar_water_ions.str']

params = CharmmParameterSet(*toppar_files)

# Create an openmm system by calling createSystem on psf
system = psf.createSystem(params, nonbondedMethod=NoCutoff,
         nonbondedCutoff=1*nanometer, constraints=HBonds)
integrator = LangevinIntegrator(300*unit.kelvin,   # Temperature of head bath
                                1/unit.picosecond, # Friction coefficient
                                0.002*unit.picoseconds) # Time step
# prepare simulation
platform = Platform.getPlatformByName('OpenCL')

simulation = Simulation(psf.topology, system, integrator, platform)
simulation.context.setPositions(pdb.positions)
#adding restrains
system.addConstraint(469, 41, 3.13*unit.angstroms)

print('Minimizing...')
simulation.minimizeEnergy()

# equilibrate for 100 steps
simulation.context.setVelocitiesToTemperature(300*unit.kelvin)
print('Equilibrating...')
simulation.step(100)

# Set up the reporters to report energies every 1000 steps.
simulation.reporters.append(app.DCDReporter('trajectory2.dcd', 50))
simulation.reporters.append(StateDataReporter(stdout, 1000, step=True,
                            potentialEnergy=True, temperature=True))
# run simulation
simulation.step(10000)

**Comment by peastman** [comment]
When you create a Context/Simulation, it copies over the system definition into its own variables.  From then on, any change to the System, such as adding or modifying a Force, or adding or modifying constraints, has no effect on the existing Context.  It only affects new Contexts you create after that.

Move the lines that add the restraint or constraint to before you create the Simulation object, and it should work.

**Comment by Manojcu** [comment]
Thanks for the suggestion. But it also didn't work. The bond is still changing, even when I constraint it. 

My modified script looks like:
-------------------------------------
# Create an openmm system by calling createSystem on psf
system = psf.createSystem(params, nonbondedMethod=NoCutoff,
         nonbondedCutoff=1*nanometer, constraints=HBonds)

#add constraint
system.addConstraint(469, 41, 3.13*unit.angstroms)


integrator = LangevinIntegrator(300*unit.kelvin,   # Temperature of head bath
                                1/unit.picosecond, # Friction coefficient
                                0.002*unit.picoseconds) # Time step
# prepare simulation
platform = Platform.getPlatformByName('OpenCL')

simulation = Simulation(psf.topology, system, integrator, platform)
simulation.context.setPositions(pdb.positions)


# minimize
print('Minimizing...')
simulation.minimizeEnergy()

# equilibrate for 100 steps
simulation.context.setVelocitiesToTemperature(300*unit.kelvin)
print('Equilibrating...')
simulation.step(100)

# Set up the reporters to report energies every 1000 steps.
simulation.reporters.append(app.DCDReporter('trajectory3.dcd', 50))
simulation.reporters.append(StateDataReporter(stdout, 1000, step=True,
                            potentialEnergy=True, temperature=True))
# run simulation
simulation.step(2000)

**Comment by peastman** [comment]
That looks like it ought to work.  How exactly are you concluding that the bond length is changing?  Can you provide a complete working example that demonstrates the problem?

By the way, when posting source code, put a line above and below with the characters \`\`\`.  See https://guides.github.com/features/mastering-markdown/.  Otherwise it interprets your Python code as markdown, which makes it hard to read!

**Comment by Manojcu** [comment]
Its working. I'm sorry. Thanks for the help. I was picking wrong atoms as python uses '0' based indexing.

**Comment by peastman** [comment]
Glad to hear it!
