### ISSUE TITLE
Jenkins update

### ISSUE THREAD

**Issue by swails** [pandegroup/openmm#2071]
@peastman -- I've overhauled how I handle HTTP traffic coming into my home computer, which means my Jenkins instance is no longer reachable at http://www.jasonswails.com:8888.

The address has changed to a more sensible https://jenkins.jasonswails.com (standard HTTPS port 443).  Can you check the Jenkins webhook to make sure GitHub tries to communicate with the correct URL?  I've closed port 8888 inbound to my house, so the current URL will no longer work.

Thanks!

**Comment by peastman** [comment]
Ok, it's back to http://www.jasonswails.com:8888/ghprbhook/.

**Comment by swails** [comment]
Back to working... that's too bad that the reverse proxy wasn't working as I expected it to, though.
