### ISSUE TITLE
Feature request - query PME grid parameters in AmoebaMultipoleForce.

### ISSUE THREAD

**Issue by leeping** [pandegroup/openmm#2081]
Hi there,

I would like to query the PME grid parameters in AmoebaMultipoleForce.  At the moment, the following function call returns `(0,0,0)`:

```for f in simulation.context.getSystem().getForces():
    if f.__class__.__name__ == 'AmoebaMultipoleForce':
        logger.info("AMOEBA PME order      : %i" % f.getPmeBSplineOrder())
        logger.info("AMOEBA PME grid       : %s" % str(f.getPmeGridDimensions()))
```

I can go into the OpenMM source codes and write a hack that prints out the grid dimensions that I want, for example in `plugins/amoeba/platforms/cuda/src/AmoebaCudaKernels.cpp`:

```
void CudaCalcAmoebaMultipoleForceKernel::initialize(const System& system, const AmoebaMultipoleForce& force) {
...
    // Set up PME.                                                                                                                                                    
    if (usePME) {
        // Create the PME kernels.                                                                                                                                    
...
        printf("LPW In AmoebaCudaKernels.cpp: PME grid %i %i %i\n", gridSizeX, gridSizeY, gridSizeZ);
        pmeBsplineModuliX.initialize(cu, gridSizeX, elementSize, "pmeBsplineModuliX");
```

How can we make this easier for users to query?

Thanks,

- Lee-Ping

**Comment by peastman** [comment]
The function you're looking for is `AmoebaMultipoleForce.getPMEParametersInContext()`.  http://docs.openmm.org/latest/api-c++/generated/OpenMM.AmoebaMultipoleForce.html#_CPPv2NK6OpenMM20AmoebaMultipoleForce25getPMEParametersInContextERK7ContextRdRiRiRi

**Comment by leeping** [comment]
Ah, thanks - I hadn't seen this function. :)

- Lee-Ping
