### ISSUE TITLE
Simulation explodes if chains are non-contiguous in topology

### ISSUE THREAD

**Issue by tristanic** [pandegroup/openmm#2091]
If I use the below method to generate an OpenMM topology, then everything works fine as long as each chain is in a single contiguous block. If not (most commonly because HETATMs are bundled together at the end of the PDB file regardless of chain), then the topology and simulation are created without any error message but the minimizer sends the atoms off to infinity in every direction. Error messages I get when starting a partial simulation (with a shell of residues with all atoms fixed surrounding the mobile ones) suggests the simulation becomes confused about which atom is which (I get "Error: a constraint cannot involve a massless particle" when the only constraints are on H-bonds and my code only ever fixes whole residues).

```
    def create_openmm_topology(self, atoms, residue_templates):
        '''
        Generate a simulation topology from a set of atoms.

        Args:
            * atoms:
                - a :py:class:`chimerax.Atoms` instance. Residues must be
                  complete, and the atoms in each residue must be contiguous
                  in the array.
            * residue_templates:
                - A {residue_index: residue_type} dict for residues whose
                  topology is otherwise ambiguous, where residue_type is the
                  name of the residue in the forcefield definition. OpenMM
                  requires a {:py:class:`openmm.Residue`: residue_type} dict, so
                  we need to do the conversion here.
        '''

        anames   = atoms.names
        n = len(anames)
        enames   = atoms.element_names
        rnames   = atoms.residues.names
        rnums    = atoms.residues.numbers
        cids    = atoms.chain_ids
        bonds = atoms.intra_bonds
        bond_is = [atoms.indices(alist) for alist in bonds.atoms]

        templates_out = {}
        from simtk.openmm.app import Topology, Element
        top = self.topology = Topology()
        cmap = {}
        rmap = {}
        atoms = {}
        rcount = 0
        for i, (aname, ename, rname, rnum, cid) in enumerate(
                zip(anames, enames, rnames, rnums, cids)):
            if not cid in cmap:
                cmap[cid] = top.addChain()   # OpenMM chains have no name
            rid = (rname, rnum, cid)
            if not rid in rmap:
                res = rmap[rid] = top.addResidue(rname, cmap[cid])
                if rcount in residue_templates.keys():
                    templates_out[res] = residue_templates[rcount]
                rcount += 1


            element = Element.getBySymbol(ename)
            atoms[i] = top.addAtom(aname, element,rmap[rid])

        for i1, i2 in zip(*bond_is):
            top.addBond(atoms[i1],  atoms[i2])

        return top, templates_out
```

**Comment by peastman** [comment]
What do you do with this Topology once you create it?  That error message relates to the System rather than the Topology.  Can you show the code you use to create the System?

**Comment by tristanic** [comment]
To create the system I just pass it through forcefield.py:

```
    def _create_openmm_system(self, forcefield, top, params, residue_templates):
        system_params = {
            'nonbondedMethod':      params.nonbonded_cutoff_method,
            'nonbondedCutoff':      params.nonbonded_cutoff_distance,
            'constraints':          params.rigid_bonds,
            'rigidWater':           params.rigid_water,
            'removeCMMotion':       params.remove_c_of_m_motion,
            'residueTemplates':     residue_templates,
        }
        return forcefield.createSystem(top, **system_params)
```
... where the forcefield is created by:

```
    def define_forcefield(self, forcefield_file_list):
        '''
        Create a :py:class:`openmm.ForceField` object from a set of OpenMM
        ffXML files.

        Args:
            * forcefield_file_list:
                - An iterable of file names.
        '''
        from simtk.openmm.app import ForceField
        ff = ForceField(*[f for f in forcefield_file_list if f is not None])
        return ff
```

**Comment by tristanic** [comment]
Oops - add 
`‘ignoreExternalBonds’:  True`
to that list of `createSystem()` flags.

 
 
Tristan Croll
Research Fellow
Cambridge Institute for Medical Research
University of Cambridge CB2 0XY

**Comment by peastman** [comment]
Why `ignoreExternalBonds`?  Do you actually have reason to expect there to be missing external bonds?  That option should only be used in unusual situations, and I'm suspicious that something is inconsistent in how the topology is being defined.  In particular, that the list of indices you're using when creating bonds doesn't match the order you add the atoms in.

A good place to start debugging this is to identify the constraint or constraints producing the error message.  You can do something like this.

```python
atoms = list(topology.atoms())
for i in range(system.getNumConstraints()):
  atom1, atom2, distance = system.getConstraintParameters(i)
  if system.getParticleMass(atom1) == 0*amu or system.getParticleMass(atom2) == 0*amu:
    print('Illegal constraint between particle', atom1, atoms[atom1], 'and particle', atom2, atoms[atom2])
```

**Comment by tristanic** [comment]
Yes, in my general use case (some fairly arbitrary subset of a larger structure, with the mobile residues surrounded by a shell of fixed residues surrounded by nothing), I have (many) missing external bonds. This all works flawlessly except in this very specific situation.

 
 
Tristan Croll
Research Fellow
Cambridge Institute for Medical Research
University of Cambridge CB2 0XY

**Comment by tristanic** [comment]
Oh - I see this is now taken care of in 7.2.2 (by blocking the creation of non-contiguous chains in the topology in the first place). In topology.py, line 158:

```
        if len(chain._residues) > 0 and self._numResidues != chain._residues[-1].index+1:
            raise ValueError('All residues within a chain must be contiguous')
```
