### ISSUE TITLE
The AMD APP SDK is no more 

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#2098]
The AMD APP SDK appears to have been discontinued:
https://github.com/fireice-uk/xmr-stak/issues/1511

@peastman: Should we still be using this in our OpenMM builds?

**Comment by jchodera** [comment]
The AMD "Tools & SDKs" page:
https://developer.amd.com/tools-and-sdks/

**Comment by peastman** [comment]
No one seems to be sure what's going on.  Apparently it's been unavailable (the download page returns 404) for a while, but AMD hasn't said anything about discontinuing it.  People have asked about it on the AMD forums, but there seems to have been no official response of any kind.

They still have a page about OpenCL (https://www.amd.com/en-us/solutions/professional/hpc/opencl), but the only download link is for drivers.

**Comment by jchodera** [comment]
We're making progress on multi-CUDA build versions for conda builds of OpenMM 7.3.0. Should we tentatively plan to still include the AMD APP SDK in our build image, @peastman? The latest I've found is a slight revision of what we were using---v3.0.130.136-GA.

**Comment by peastman** [comment]
It's probably fine if we just compile against the OpenCL headers from the CUDA SDK.  If I recall correctly, the reason we used the AMD headers was that compiling against the Nvidia ones produced slightly slower performance when using an AMD GPU on Windows.  But how many users are going to be running production simulations with AMD GPUs on Windows?  For the F@H core we probably still want to use it, but for regular OpenMM builds, I don't think that's very important.

**Comment by jchodera** [comment]
We'll remove the AMD APP SDK from the new build images. Feel free to reopen if status changes!

**Comment by informatorius** [comment]
AMD APP SDK  is now OCL-SDK
https://github.com/GPUOpen-LibrariesAndSDKs/OCL-SDK/releases

**Comment by peastman** [comment]
Thanks!
