### ISSUE TITLE
Ions are placed too close to membrane leading to very large energies

### ISSUE THREAD

**Issue by JoaoRodrigues** [pandegroup/openmm#2099]
Hi there,

Using the `neutralize=True` option in `modeller.addMembrane()` (sometimes) leads to very large potential energies in the system that cannot be solved by the minimizer. The cause (at least from what we gathered) is that ions are placed at the position of randomly picked water molecules. Sometimes, these are waters very close to the lipid bilayer and since ions are substantially larger than the water oxygens they replace, there is essentially an overlap. @peastman you can verify this by trying to minimize the system I sent you privately last week that was causing the membrane water addition to fail.

I solved this problem in my system by adding an extra check in `addMembrane()` to ignore waters that are within a certain distance (in Z) from the min/max lipid Z coordinates, when selecting the random subset to be replaced by ions. It does not add that much of an overhead and seems to be a pretty generalizable solution for any lipid membrane. I am running some tests and cleaning the code before I create a pull request.

EDIT: sometimes this still fails, because two neighboring waters are selected randomly to be replaced, leading to the same issue (overlapping particles, in this case two ions).

**Comment by peastman** [comment]
That sounds like a good solution.  It looks like nearly all positive ions have radii that are similar to or smaller than the water oxygen.  But negative ions tend to be a bit larger, so that's probably where the problem is coming from.

**Comment by JoaoRodrigues** [comment]
New implementation of the fix in #2274
