### ISSUE TITLE
openmm, single or double precision

### ISSUE THREAD

**Issue by hrg1000** [pandegroup/openmm#2104]
I installed openmm via the standard method of using conda (conda install -c omnia openmm). How can I find out whether the calculations are being performed in single or double precision?
Thank you,
Dr. Helen Eisenberg

**Comment by peastman** [comment]
Assuming you're using the CUDA or OpenCL platform, it gives a choice of precision modes.  You select which one to use by specifying a property when you create your Simulation or Context.  See http://docs.openmm.org/latest/userguide/library.html#cuda-platform and http://docs.openmm.org/latest/userguide/application.html#platforms.

The CPU platform always uses mixed precision.  The Reference platform always uses double precision.

**Comment by hrg1000** [comment]
Thank you for your reply.

**Comment by peastman** [comment]
You're welcome!
