### ISSUE TITLE
numpy.sqrt destroys units on Quantity objects who's values are of NumPy types

### ISSUE THREAD

**Issue by Lnaden** [pandegroup/openmm#2106]
`numpy.sqrt` causes `simtk.unit.Quantity._value`s of NumPy based types to return non-`Quantity` objects.

NumPy has its own types for float/int/etc. If those are wrapped in a `Quantity`, the `numpy.sqrt` function correctly takes the square root, but then returns a non-Quantity object. I imagine the bug has to do with the fact that the NumPy based objects carry certain Magic Methods which the `units` module checks for like `__array_prepare__` and `__array_wrap__`, but I have not been able to trace it further.

Minimal example here:
```python
import simtk.unit as unit
import numpy as np

a_float =  4.0 * unit.meter ** 2
np_float = np.float32(4.0) * unit.meter ** 2
print(a_float, np_float)  # These both behave correctly as Quantities for all other operations
print(type(a_float._value), type(np_float._value))
print(np.sqrt(a_float), np.sqrt(np_float))  # Both should be 2m, gives: 2m and 2
print(a_float.sqrt(), np_float.sqrt())  # Correctly gives both as 2m
print(a_float**0.5, np_float**0.5)  # Correctly gives both as 2m
```
For completeness, the 5 print statements give the following outputs
```
4.0 m**2 4.0 m**2
<class 'float'> <class 'numpy.float32'>
2.0 m 2.0
2.0 m 2.0 m
2.0 m 2.0 m
```
This bug exists for Numpy arrays as well, but not for lists.

**Comment by Lnaden** [comment]
Although the example use case is not common, the more common issue would be if someone extracted a value from a NumPy array through indexing or when adding something in the square, then did square root.

E.g. I ran into this adding errors in the quadrature with units, so I had `array_of_errors **2 + aother_array_of_errors**2` then doing `np.sqrt(sum_of_square_errors)`

**Comment by peastman** [comment]
Use `unit.sqrt()` instead.  We weren't able to make `np.sqrt()` or `math.sqrt()` handle units properly, so that's why we had to create a new function for it.

**Comment by Lnaden** [comment]
`unit.sqrt()` only works on scalars/size-1 objects though, similar to the `math.sqrt` function. So if its a quantity wrapped around an array, then the `unit.sqrt` function does not work correctly. I can use `** 0.5` as a workaround, but float exponents always make me nervous, which is mostly just paranoia.

**Comment by peastman** [comment]
If you can figure out a way to make `np.sqrt()` work, that would be great.  It also should be easy to make all the functions in unit_math.py work with numpy arrays.  We could do something like this:

```
try:
  from numpy import sqrt, sin, cos, ...
except:
  from math import sqrt, sin, cos, ...
```

That way it will use the numpy versions of all those functions if it's installed, or the math version if it isn't.

**Comment by Lnaden** [comment]
Its probably some black magic involving `__array_ufunc__`. After much digging I have only found other other code which kind of uses this with a wrapper (oddly enough, for unit handling) but it looks like [its way more trouble](https://github.com/astropy/astropy/blob/91fc1830e60ae4a0b983f690561422e465941e66/astropy/units/quantity.py#L597) than [its worth right now](https://github.com/astropy/astropy/blob/91fc1830e60ae4a0b983f690561422e465941e66/astropy/units/quantity_helper.py#L503) to put in. Also because I am still having some issues wrapping my head around the sheer power that `ufunc`s offers.

I'll work around it for now and close this issue, but I think implementing ufunc hooks in the future may be the way to go. Something to think about.
