### ISSUE TITLE
numAdded failing to clear area around protein

### ISSUE THREAD

**Issue by 404random** [pandegroup/openmm#2109]
numAdded (in `modeller.addSolvent()`) is not creating a cavity around the protein as it should. As such, any simulation fails either during minimization or during runs. 

Relevant code:
```
modeller = app.Modeller(topology_main, trajectory.xyz[frame])
        with open("%s_%s_beginning.pdb" %(run_name, frame), 'w') as outfile:
            app.PDBFile.writeFile(modeller.topology, modeller.positions, file=outfile, keepIds=True)
        if water_num is None:
            modeller.addSolvent(forcefield, padding = 1.0 *unit.nanometer)
        else:
            modeller.addSolvent(forcefield, numAdded = water_num)
```
See pdb files below:

[pdb_bugs.zip](https://github.com/pandegroup/openmm/files/2157193/pdb_bugs.zip)

**Comment by peastman** [comment]
Can you provide a full set of files to reproduce the problem?  I tried using the following script

```python
from simtk.openmm import *
from simtk.openmm.app import *
from simtk.unit import *

ff = ForceField('amber99sb.xml', 'tip3p.xml')
pdb = PDBFile('bug_run_145_beginning.pdb')
modeller = Modeller(pdb.topology, pdb.positions)
modeller.addSolvent(ff, numAdded=1000)
with open('solvated.pxb', 'w') as output:
    PDBFile.writeFile(modeller.topology, modeller.positions, output)
```

but it fails with this exception:

```
ValueError: No template found for residue 163 (SAM).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field.
```

**Comment by peastman** [comment]
It's working fine for me.  I used the script above, just adding the two extra files to the force field and setting numAdded to 11000.  The output PDB file is exactly what I'd expect, with the water correctly avoiding the protein.

**Comment by peastman** [comment]
Can you provide any more information?  As I noted above, this works for me.

**Comment by 404random** [comment]
I used an mdtraj object to generate the topology and positions. Everything else seems to be the same.

**Comment by peastman** [comment]
Can you provide code to reproduce the problem?

**Comment by 404random** [comment]
```
def run_frames(run_name, trajectory,n_steps, forcefield_list=None, water_num = None, frame_list = None, platform_val = 'CUDA'):
    forcefield = app.ForceField('amber99sbildn.xml', 'tip3p.xml')
    topology_main = trajectory.top.to_openmm()
    for field in forcefield_list:
        forcefield.loadFile(field)
    if frame_list is None:
        frame_list = [i for i in range(len(trajectory))]
    for frame in frame_list:
        integrator = openmm.LangevinIntegrator(300*unit.kelvin, 1.0/unit.picoseconds, 2.0*unit.femtoseconds)
        integrator.setConstraintTolerance(0.00001)
        platform = openmm.Platform.getPlatformByName(platform_val)
        if platform_val is not 'CPU':
            platform.setPropertyDefaultValue('Precision', 'mixed')
        modeller = app.Modeller(topology_main, trajectory.xyz[frame])
        if water_num is None:
            modeller.addSolvent(forcefield, padding = 1.0 *unit.nanometer)
        else:
            modeller.addSolvent(forcefield, numAdded = water_num)
```

**Comment by peastman** [comment]
Can you give a complete, self contained program?  I don't know what arguments you're passing to that method.  I need to reproduce exactly what you're doing.

**Comment by 404random** [comment]
Sorry, I attached it below. I think running `bug.py` should be able to recreate it. It should create two pdb files called` beginning.pdb`, which is the original protein, and the second should be called `bug.pdb`. 

[bug_report.zip](https://github.com/pandegroup/openmm/files/2211151/bug_report.zip)

**Comment by peastman** [comment]
I see what's going on.  The problem is that the protein is far away from the origin.  So it starts building a water box, and eventually reaches the number of molecules you set, and they've never gotten to the protein.  So you end up with a cube of water, and a protein sitting a little way away.

You might ask, shouldn't it apply periodic boundary conditions so the water would go around a periodic copy of the protein?  But in this case it can't.  It doesn't know what the box size will be until it's finished adding water!

The fix is quite easy.  Just translate the protein so it will be inside the water box.  Currently you're passing `trajectory.xyz[frame]` to the Modeller as the initial particle positions.  Just change that to `trajectory.xyz[frame]-np.min(trajectory.xyz[frame], axis=0)`.

**Comment by 404random** [comment]
Thanks! That does fix it.
