### ISSUE TITLE
RMSD calculation for python

### ISSUE THREAD

**Issue by ZenPylon** [pandegroup/openmm#2110]
Hello,

In the documentation, I see that there is a way to calculate the RMSDForce in C++, but I don't see a python interface for it in openmm.py where the other forces are defined.  Will this be added at some point?  In the meantime, is there a workaround I could try?

Thanks!

**Comment by peastman** [comment]
It works in Python exactly the same as in C++.  What makes you think it doesn't?

Remember that RMSDForce is a recently added feature.  It hasn't yet made it into a release.

**Comment by jchodera** [comment]
The developer documentation can be found here:
http://docs.openmm.org/development/api-python/index.html

and the page for `RMSDForce`:
http://docs.openmm.org/development/api-python/generated/simtk.openmm.openmm.RMSDForce.html#simtk.openmm.openmm.RMSDForce

You can install a development snapshot via `conda` with
```
conda install --yes -c omnia/label/dev openmm
```

**Comment by ZenPylon** [comment]
Thank you both for the prompt reply!  Apologies - for some reason, I assumed it had been merged.  Really appreciate the help :)
