### ISSUE TITLE
How to remove LJ interactions from NonbondedForce

### ISSUE THREAD

**Issue by joegomes** [pandegroup/openmm#2125]
Hi,

I'm using a CustomNonbondedForce to compute vdw interactions in my system. I would like to know if there is a way to keep the electrostatic NonbondedForce (in my case, PME) but remove the LJ interaction. Currently, I've modified the LJ parameters such that the interaction and force are always zero but I suspect I could speed up the simulations if LJ is gone entirely.

Thanks,
Joe

**Comment by Lnaden** [comment]
If you set the epsilon parameter to 0 for each particle, that should disable the sterics calculation for the standard `NonbondedForce` object, but keep the PME. If I remember correctly, this is a very efficient action as the execution skips over the Lennard-Jones calculation for the particles entirely if epsilon is 0.

**Comment by peastman** [comment]
Just set epsilon to 0 for every particle.  It will realize that you aren't using LJ and ifdef out section of the kernel that computes it.

**Comment by joegomes** [comment]
I was setting epsilon to 0 to zero-out the interaction, but I guess I was also skipping the LJ calculation entirely. Thanks @Lnaden and @peastman!
