### ISSUE TITLE
PeriodicDistance() with non-periodic system

### ISSUE THREAD

**Issue by frank-stonybrook** [pandegroup/openmm#2131]
Hi Guys, 

Recently we had some simulations behaved abnormal with cartesian restraint like this 
<img width="621" alt="screen shot 2018-07-24 at 16 06 42" src="https://user-images.githubusercontent.com/10855977/43163262-a29220e4-8f5b-11e8-9b64-baefb4a88536.png"> 
The cart_delta=2.5Å, k=250kcal/mol*nm, restraining all CA atoms. The simulation system is built up from a pdb structure with gbneck2 implicit solvent model. 

1. When simulation with a box vector [0.,0.,0.] and the system center of mass did not moved to the origin, the rmsd of CA is far from the initial structure we restrained to. The rmsd did not show here. 

2. When simulation with a box vector [0.,0.,0.] and system moved to origin before starting the simulation, the system behave more like it should be. The protein CA rmsd is plotted as red line. 

3. However, if we provided a box vector [999.,999.,999.], the system behaves even more normal than the second protocol. The protein CA rmsd is plotted as blue line. 

![image](https://user-images.githubusercontent.com/10855977/43163805-471828d8-8f5d-11e8-9bb8-a796909090fe.png)

I checked the Meld code, the box vector information should not be used during non-periodic simulation. But somehow the box vector influences the behavior of the simulation. 

I did some tests on openmm's periodicdistance function, and the calculated force only goes wrong when the box vector size closes to 0 (something like 0.00001). But if I understood correctly, the meld setup code will only pass the box information to openmm when using explicit solvent model. While all the test simulations we have done is using gbneck2 implicit solvent model. 

I am running out of ideas. Do you guys have any idea why it will happen?

Thanks.

**Comment by peastman** [comment]
This *is* a periodic system.  By definition.  If you use the `periodicdistance()` function, that tells it to apply periodic boundary conditions to the distance.  If one of the dimensions of the box is 0, that will give you nonsensical results.

If you don't want it to apply periodic boundary conditions, don't use `periodicdistance()`.

**Comment by frank-stonybrook** [comment]
Thanks peastman! 

Few more questions:

> This is a periodic system. By definition. 

So, even if the box vector is [0,0,0], OpenMM will still treat the system as a periodic system?

> If you use the periodicdistance() function, that tells it to apply periodic boundary conditions to the distance.

But if I understood correctly, [meld will only pass the box vector info to OpenMM when using explicit solvent model.](https://github.com/maccallumlab/meld/blob/2205854772e39a0c4ea732bce4af7b722ec76510/meld/system/openmm_runner/runner.py#L315). If there is no box vector provided, how does OpenMM calculate distance displacement using periodicdistance()?

**Comment by peastman** [comment]
> So, even if the box vector is [0,0,0], OpenMM will still treat the system as a periodic system?

Specifying the box vectors is independent of telling it to use periodic boundary conditions.  If you tell it to use PBC and then set the box volume to 0, that will produce broken results.  But just because you've given nonsensical box vectors, it isn't going to assume you didn't really mean it when you said to use PBC.

Also keep in mind that each Force decides for itself whether to apply PBC.  It's quite common for some to do it and others not.  For example, even when you've told the nonbonded forces to use PBC, the default behavior is for bonded forces not to.  (There's an option to make them do it, but that's only appropriate in unusual situations.)

> meld will only pass the box vector info to OpenMM when using explicit solvent model.

I can't speak for what MELD does.  Perhaps @jlmaccal can comment on it.

**Comment by frank-stonybrook** [comment]
Learns a lot. Thank for your helpful comments, Peastman!

**Comment by peastman** [comment]
Glad to help!  I'm going ahead and closing this issue, since it sounds like it's resolved.
