### ISSUE TITLE
dev version not found by conda

### ISSUE THREAD

**Issue by ljmartin** [pandegroup/openmm#2135]
AFAIK this isn't in the documentation which is why I come here. 
Basically, `conda install -c omnia openmm` works fine, but `conda install -c omnia/label/dev openmm` and `conda install -c omnia/label/dev openmm==7.3.0` result in PackagesNotFoundError. Is there something else I should be using?
Thanks!
![screenshot from 2018-07-30 14-34-15](https://user-images.githubusercontent.com/8262765/43377740-c7601288-9405-11e8-9253-87cae3e2031a.png)

**Comment by peastman** [comment]
It's happening because there's no fftw3f package under the dev label.  First do

```
conda install -c omnia fftw3f
```

Once you've installed that, installing OpenMM from the dev label should work.

**Comment by peastman** [comment]
We should probably add `dev`, `beta`, and `rc` labels (in addition to `main`) to fftw3f.  That way installing from any of those labels will work.

**Comment by ljmartin** [comment]
Thanks!

**Comment by jchodera** [comment]
The proper way to handle this is to
* First add the omnia and conda-forge channels. We now require these for all omnia tools.
* Second, specify the appropriate CUDA version as -c omnia/label/cudaXY where eg CUDA 9.2 is omnia/label/cuda92

Apologies for the lack of documentation for dev version conda installs. I can add that to the manual.

**Comment by peastman** [comment]
The problem had nothing to do with CUDA.  It wasn't finding fftw3f, which we distribute on the omnia channel.  The problem is that it only has the `main` label, so trying to install openmm from `dev` will fail if you don't already have fftw3f installed.

**Comment by jchodera** [comment]
@peastman: Since about a year ago, we require all omnia users to add both the `omnia` and `conda-forge` channels. See [the current installation instructions](http://omnia.md/install).

Also, anyone who wants to install the 7.3.0 dev version *must* specify the appropriate channels or else they are not guaranteed to get the appropriate CUDA build.
