### ISSUE TITLE
Is it possible to extend the XML(de)Serializer?

### ISSUE THREAD

**Issue by Lnaden** [pandegroup/openmm#2136]
If we subclass an OpenMM object in Python, is it possible to extend its serialization interface in a way that the OpenMM XML de/Serializer can pick up on, or are we on our own for writing a custom `__getstate__`/`__setstate__` objects? 

I figure the answer is the later but wanted to ask anyways. Thanks!

**Comment by peastman** [comment]
Serialization is implemented in C++.  If you extend something in Python, it doesn't know anything about it.  You define a new Python class, but it still references a C++ object of the original class.

**Comment by Lnaden** [comment]
Thats what I figured the answer was from me looking through the code, but just thought I would ask in case there was was interface. Thanks.
