### ISSUE TITLE
CharmmPsfFile segfaults for long protein chains

### ISSUE THREAD

**Issue by SimoneCnt** [pandegroup/openmm#2138]
I'm trying to load a protein with a long AA chain with CharmmPsfFile, but python segfaults. The code I use is simply:

    import simtk.openmm.app as app
    psf = app.CharmmPsfFile('prote.psf')

As example psf file, I created a protein containing 7000 alanines: [prote.psf.gz](https://github.com/pandegroup/openmm/files/2258796/prote.psf.gz)

The problem is at line in function ``set_molecule`` in file `

    wrappers/python/simtk/openmm/app/charmmpsffile.py

which calls recursively the function ``_set_owner``. 

For long chains, the stacksize in python is exceeded and there the segfault. There is already an attempt to mitigated this at line 1342 using ``setrecursionlimit``, but looks like it is not enough. Following [this stackoverflow answer](https://stackoverflow.com/questions/5061582/setting-stacksize-in-a-python-script/16248113#16248113), I added 

    resource.setrlimit(resource.RLIMIT_STACK, (resource.RLIM_INFINITY, resource.RLIM_INFINITY))

just after line 1342, and the problem appears to be solved. Not sure it this is the best way to solve the problem...

**Comment by peastman** [comment]
I think the best solution is to restructure `_set_owner()` to be iterative instead of recursive.  That way we don't need to worry about stack depth.  It's a very simple method, so that ought to be pretty easy.  I can look into it next week.

**Comment by peastman** [comment]
The fix is in #2142.  Could you try it and see if it works for you?

**Comment by SimoneCnt** [comment]
Looks like it is working fine.
Thank you!

**Comment by peastman** [comment]
Thanks!  I've merged the fix.
