### ISSUE TITLE
Openmm failed to build topology 

### ISSUE THREAD

**Issue by XiaojuanHu** [pandegroup/openmm#2140]
Openmm failed to build topology, this error occured.

File "computing_energy.py", line 12, in <module>
    system = forcefield.createSystem(pdb.topology, nonbondedMethod=NoCutoff, constraints=None)
  File "/usr/local/lib/python3.5/dist-packages/simtk/openmm/app/forcefield.py", line 1077, in createSystem
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 1 (CE).  The set of atoms matches ACE, but the bonds are different.  Perhaps the chain is missing a terminal group?

this is the pdb file i used:

REMARK    GENERATED BY TRJCONV
HEADER    Cys
MODEL        0
ATOM     1  CH3 ACE     1       3.481   2.343   0.056  1.00  0.00           C  
ATOM     2 HH31 ACE     1       4.004   1.772  -0.723  1.00  0.00           H  
ATOM     3 HH32 ACE     1       3.158   3.287  -0.399  1.00  0.00           H  
ATOM     4 HH33 ACE     1       4.176   2.553   0.876  1.00  0.00           H  
ATOM     5  C   ACE     1       2.264   1.571   0.472  1.00  0.00           C  
ATOM     6  O   ACE     1       1.354   1.391  -0.379  1.00  0.00           O  
ATOM     7  N   CYM     2       2.243   1.121   1.749  1.00  0.00           N  
ATOM     8  HN  CYM     2       3.081   1.344   2.274  1.00  0.00           H  
ATOM     9  CA  CYM     2       1.224   0.395   2.557  1.00  0.00           C  
ATOM    10  HA  CYM     2       1.596   0.515   3.585  1.00  0.00           H  
ATOM    11  CB  CYM     2       1.160  -1.143   2.354  1.00  0.00           C  
ATOM    12  HB3 CYM     2       2.165  -1.530   2.568  1.00  0.00           H  
ATOM    13  HB2 CYM     2       0.484  -1.528   3.131  1.00  0.00           H  
ATOM    14  SG  CYM     2       0.670  -1.921   0.738  1.00  0.00           S  
ATOM    15  C   CYM     2      -0.159   1.071   2.506  1.00  0.00           C  
ATOM    16  O   CYM     2      -0.846   1.111   1.449  1.00  0.00           O  
ATOM    17  N   NME     3      -0.615   1.585   3.648  1.00  0.00           N  
ATOM    18  H   NME     3      -0.021   1.530   4.469  1.00  0.00           H  
ATOM    19  CH3 NME     3      -1.927   2.209   3.800  1.00  0.00           C  
ATOM    20 HH31 NME     3      -2.538   1.632   4.505  1.00  0.00           H  
ATOM    21 HH32 NME     3      -1.809   3.232   4.177  1.00  0.00           H  
ATOM    22 HH33 NME     3      -2.420   2.233   2.825  1.00  0.00           H  
ATOM    23 Zn   Zn      4       0.007   0.000   0.004  1.00  0.00          Zn 
END

**Comment by peastman** [comment]
You need to use standard PDB names for residues and atoms.  According to the chemical components dictionary, CYM is S-methylcysteine.  The correct name for cysteine is CYS (see ftp://ftp.wwpdb.org/pub/pdb/data/monomers/CYS).  If you don't use standard names, the PDB loader can't tell which atoms should be bonded to each other.

**Comment by XiaojuanHu** [comment]
Thank you for the quick reply! But i need the deprotonated Cysteine in my system. I thought CYM may be the most relative one? Is CYM the problem? From the error messages, it seems like it can not read the ACE residue.

**Comment by peastman** [comment]
The name is CYS whether it's protonated or not.  Names in PDB files don't depend on the protonation state.

I think there's also a second problem with your PDB file: the spacing is incorrect.  I can't tell exactly, because you didn't surround the file content with \``` marks, so github is removing duplicate spaces.  But the PDB reader thinks the ACE residue is called CE, which suggests the name has been shifted by a column.  PDB files require particular pieces of information to be in particular columns within each line.  See http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM.  If you add or remove a space, things won't get read correctly.

**Comment by XiaojuanHu** [comment]
Thank you! problem solved! I actually missed one space before residue name column.

I have the last question. if i use amber03 force field, openmm will read the charges of deprotonated Cysteine from the residue CYS, then the total charge of the deprotonated Cysteine residue will not be -1, right?

**Comment by XiaojuanHu** [comment]
Thank you very much!
