### ISSUE TITLE
CustomCentroidBondForce Python API example appears to be written in C

### ISSUE THREAD

**Issue by ljmartin** [pandegroup/openmm#2141]
I'm trying to write a `CustomCentroidBondForce` for a single group of particles and I'm not sure how to `addBond` with just a single group, or whether this step is replaced by `addGroup`. Looking at the example in the API ( http://docs.openmm.org/development/api-python/generated/simtk.openmm.openmm.CustomCentroidBondForce.html#simtk.openmm.openmm.CustomCentroidBondForce ) it seems the example is in C and not python. It would be much appreciated to have an example in python. Thanks :)

**Comment by peastman** [comment]
The API documentation is generated from the comments in the source code, which is written in C++.  Wherever you see a `vector` in the C++ example, use a list in Python.  In the example code you cited, `addBond()` gets called like this:

```c++
vector<int> bondGroups;
bondGroups.push_back(0);
bondGroups.push_back(1);
vector<double> bondParameters;
bondParameters.push_back(k);
force->addBond(bondGroups, bondParameters);
```

For Python you call it exactly the same way, except creating and filling in the lists is a lot simpler:

```python
bondGroups = [0, 1]
bondParameters = [k]
force.addBond(bondGroups, bondParameters)
```

Or even more simply:

```python
force.addBond([0, 1], [k])
```

> I'm not sure how to addBond with just a single group, or whether this step is replaced by addGroup.

You still need to do both steps.  First create a group by calling `addGroup()`.  Then create a bond  that depends on that group by calling `addBond()`.

**Comment by ljmartin** [comment]
Thanks!
