### ISSUE TITLE
Possible performance issue with CustomIntegrator

### ISSUE THREAD

**Issue by pgrinaway** [pandegroup/openmm#2143]
Hi,

@jchodera noticed last night that the benchmark script was markedly slower using our OpenMMTools LangevinIntegrator:

```
Platform: CUDA
Precision: mixed

Test: pme (cutoff=1)
Step Size: 2 fs
OpenMM integrator
Integrated 85279 steps in 58.8584 seconds
250.367 ns/day
```

vs

```
Platform: CUDA
Precision: mixed

Test: pme (cutoff=1)
V R O R V
Step Size: 2 fs
Integrated 56113 steps in 58.7484 seconds
165.048 ns/day
```

 Digging a bit deeper, I decided to try the nvidia profiler. With the OpenMM `LangevinIntegrator`, I was seeing timings like this:

```
API calls:   35.04%  34.6233s   2017678  17.159us  4.8860us  42.059ms  cuLaunchKernel
                   27.78%  27.4532s     86782  316.35us  2.3830us  45.249ms  cuEventSynchronize
                   14.33%  14.1641s    694256  20.401us  5.5930us  48.078ms  cudaLaunchKernel
                    7.58%  7.49070s      1053  7.1137ms  103.95us  35.564ms  cuMemcpyDtoH
                    6.38%  6.30195s      1417  4.4474ms  9.3200us  23.612ms  cuMemcpyHtoD
```

But for the OpenMMTools `CustomIntegrator`, I was seeing timings like this:

```
      API calls:   72.92%  64.6311s     54423  1.1876ms  5.0570us  43.805ms  cuMemcpyHtoD
                   15.69%  13.9028s   2354192  5.9050us  3.7250us  4.2585ms  cuLaunchKernel
                    3.69%  3.27111s     53336  61.330us  1.8390us  1.2271ms  cuEventSynchronize
                    3.33%  2.95045s    426688  6.9140us  4.1710us  303.76us  cudaLaunchKernel
                    0.96%  851.97ms      1073  794.01us  28.689us  14.010ms  cuMemcpyDtoH
                    0.80%  705.52ms     53336  13.227us  9.8010us  285.60us  cuMemcpyDtoDAsync
```

It seemed odd that something still doing Langevin integration would cause so much host to device copies, so we were playing around a bit. Attached are files for the system, integrator, and state for an integrator with the problem and without the problem. 

The difference between the two is simply that I've eliminated random number generation from the one that doesn't have the problem. Could it be that random numbers are being generated on the CPU, and have to be copied to the device?

[speed_example.tar.gz](https://github.com/pandegroup/openmm/files/2276022/speed_example.tar.gz)

**Comment by peastman** [comment]
Is this the same issue that was discussed in https://github.com/choderalab/openmmtools/issues/342?  If so, the OpenMMTools integrator is slower because it's using a more complicated algorithm that involves a lot more computation.  It also may be doing a lot more computation than it really needs to.  See my comments at https://github.com/choderalab/openmmtools/issues/342#issuecomment-378006069.

**Comment by maxentile** [comment]
We also are observing this problem for [`AndersenVelocityVerletIntegrator`](https://github.com/choderalab/openmmtools/blob/b889f635d12d8ec567dddf836d47bab3a0a9bd00/openmmtools/integrators.py#L498-L563), which I believe is the integrator in @pgrinaway 's serialized example. (It appears to spend a large amount of time on `cuMemcpyHtoD`s, which can be resolved by eliminating random number generation.)

**Comment by peastman** [comment]
Random number generation is done on the GPU.  It involves no host to device data transfer.

If you want to understand what's really going on, look at the timeline in nvvp.  Where is the time being spent?

**Comment by pgrinaway** [comment]
I’ll check when I get back home, but note that in the example the only difference between the code with a lot of time spent on host to device copies and one with very little is that one uses random numbers and the other does not.

**Comment by peastman** [comment]
That means you didn't actually test what you thought you did. :)  Simply calculating random numbers involves no communication between host and device.  Something else is different between your two tests.

Also, the "API calls" section of the nvprof output usually tells little or nothing about what is limiting performance.  That just tells you where the CPU spent its time.  We really care about where the GPU spent its time.  The CPU may spend a long time inside a function call not doing anything, just waiting for the GPU to finish its work.

**Comment by pgrinaway** [comment]
so if we run the code that I attached, we see that the integrator with no random numbers is about twice as fast as the one with random numbers. Is this to be expected then? Sorry for wasting your time if I’ve misunderstood what’s going on here, but I think this example is fairly minimal and shows an interesting difference between what happens with and without random numbers (maybe just that random numbers are expensive and I’m chasing a red herring).

**Comment by jchodera** [comment]
The difference in the `Computations` block seems to come down to two lines:
```XML
<                 <Computation computationExpression="step(p_collision-uniform)" computationType="1" computationVariable="collision"/>
<                 <Computation computationExpression="(1-collision)*v + collision*sigma_v*gaussian" computationType="1" computationVariable="v"/>
---
>                 <Computation computationExpression="1.0" computationType="1" computationVariable="collision"/>
>                 <Computation computationExpression="(1-collision)*v + collision*sigma_v*0.0" computationType="1" computationVariable="v"/>
```
@pgrinaway suggests that the only difference is that `0.0` is used in the fast case and `gaussian` is used in the slow case.

**Comment by jchodera** [comment]
On a GTX-1080, I'm not seeing as big a difference as you are:
```
[chodera@lilac:example]$ python run_test.py 
The slow time is 8.993572473526001
The fast time is 6.722618579864502
```

**Comment by jchodera** [comment]
After running this a couple of times on a GTX-1080, I'm observing a much smaller difference:
```
[chodera@lilac:example]$ python run_test.py 
The slow time is 8.054375648498535
The fast time is 6.310144901275635
```
If I get change the slow integrator line
```
<Computation computationExpression="step(p_collision-uniform)" computationType="1" computationVariable="collision"/>
```
to match the fast integrator, this reduces further
```
[chodera@lilac:example]$ python run_test.py 
The slow time is 6.632540941238403
The fast time is 6.39315938949585
```

**Comment by pgrinaway** [comment]
>After running this a couple of times on a GTX-1080, I'm observing a much smaller difference:

I wonder why this is. When I ran it I got ~2x slowdown for the slow integrator. Could the step command be the slow part?

I'll investigate tomorrow, as well as post the full output of the `nvprof` command. The reason I had mentioned the API call list was because the profiling of the actual computation time didn't seem to differ much between the `CustomIntegrator` and the `LangevinIntegrator`. The only notable difference in `nvprof` output was that without the random variables, `cuMemcpyHtoD` was much less prominent in API calls than with the random variables. Maybe I'm seeing a side effect of something different, but either way it strikes me as odd that there would be far more calls to copy memory from the host to device when there are random variables (or maybe it's the `step` expression as @jchodera pointed out? either way I wouldn't imagine that to show up as more calls to `cuMemcpyHtoD`).

This is commit ` f6cbe7d` by the way.

**Comment by jchodera** [comment]
Your test just times the `step()` call:
```python
def run_test(system, integrator, state):
    platform = openmm.Platform.getPlatformByName("CUDA")
    ctx = openmm.Context(system, integrator, platform)
    ctx.setState(state)
    ctx.setVelocitiesToTemperature(300.0*unit.kelvin)
    initial_time = time.time()
    integrator.step(10000)
    final_time = time.time()
    return final_time - initial_time
```
Instead, if you split out a single initial step, you force compilation of the kernels before timing:
```
def run_test(system, integrator, state):
    platform = openmm.Platform.getPlatformByName("CUDA")
    ctx = openmm.Context(system, integrator, platform)
    ctx.setState(state)
    ctx.setVelocitiesToTemperature(300.0*unit.kelvin)
    integrator.step(1)
    initial_time = time.time()
    integrator.step(10000)
    final_time = time.time()
    return final_time - initial_time
```

**Comment by jchodera** [comment]
After a couple of runs, the difference between the standard `LangevinIntegrator` and our `openmmtools` slower `LangevinIntegrator` seems ~50% for this test system (after a couple of runs to compile the kernels):
```
[chodera@lilac:example]$ python run_test.py 
The slow time is 9.323823928833008
The fast time is 6.272755861282349
```
Shaving off some of the extra constraint steps only brings this down to
```
[chodera@lilac:example]$ python run_test.py 
The slow time is 8.520955562591553
The fast time is 6.237375020980835
```

[example2.zip](https://github.com/pandegroup/openmm/files/2276517/example2.zip)

**Comment by pgrinaway** [comment]
Ok, I think there are two issues here. One is the original issue where the OpenMM `LangevinIntegrator` was significantly faster than the OpenMMTools `LangevinIntegrator`. @jchodera demonstrates above that some of this problem is probably due to compilation. I was unaware that the integrator was compiled on the first step (I thought it was on context creation), so perhaps that mystery is not so mysterious after all.

The second issue, though, is one where I still have a few questions. In the example I posted, the comparison was between two _custom_ integrators, so (I thought) they should both share the compilation overhead. But I do see what you see @jchodera : moving the `step(1)` out of the timed loop gives me something like this:

```
The slow time is 7.476632118225098
The fast time is 6.078141927719116
```

So then my questions are:

1) is the time difference we observe in my test case (not with the complex OpenMMTools `LangevinIntegrator`) just a result of taking (much) longer to compile one than the other?

and more for my curiosity:

2) Why would the `slow_integrator` in my test case result in >10x more calls to `cuMemcpyHtoD` when the only difference is the presence or absence of a line that computes `step(p_collision-uniform)`?

**Comment by peastman** [comment]
I profiled this with nvvp.  There is in fact a problem that's unnecessarily hurting performance by a small amount, but it has nothing to do with random numbers.  The memory copies are actually related to the use of global parameters.  It has an array with the values of all global variables, and stores copies on both the CPU and GPU.  Because that step uses the global parameter `p_collision`, it's uploading that array to the GPU.  That's where the memory copy is coming from.

It has a flag to keep track of whether the global parameters on the GPU are up to date, and it's supposed to only upload the array if they've changed.  But it isn't resetting the flag when it does, so it keeps reuploading them every time step.  I'll send a PR fixing it.  With that change, here is the output I get from your test.

```
The slow time is 5.141849040985107
The fast time is 4.662378311157227
```

According to nvvp there's only a tiny difference in the time to perform integration: about 15 us between the fast and slow cases.  Most of the difference is actually coming from a completely different source: rebuilding the neighbor list.  It does that whenever an atom has moved further than a cutoff distance.  In your "fast" integrator, you first set `collision` to 1.0, then set the velocities to `(1-collision)*v + collision*sigma_v*0.0`.  That sets all the velocities to 0!  So the particles never move, and the neighbor list never gets rebuilt.

By the way, here is how I recommend measuring integration time:

```python
    integrator.step(5)
    ctx.getState(getEnergy=True)
    initial_time = time.time()
    integrator.step(10000)
    ctx.getState(getEnergy=True)
    final_time = time.time()
```

Notice that it does several integration steps at the beginning.  That's to make sure all initialization and warm up is finished.  The two calls to `getState()` are to flush the queue.  `step()` may return before the GPU has actually finished the integration.  By asking for the energy, we force it to block until it really is done.

**Comment by maxentile** [comment]
Thank you for clarifying the problem and solving it so quickly!

To confirm @peastman 's conclusions, I tried to isolate the contribution of random numbers. I confirm that they are a negligible contribution in this minimal example.

Here I compared one barebones `CustomIntegrator` that doesn't use random numbers (`GradientDescent`) vs one that does use random numbers (`NoisyGradientDescent`) -- neither uses `step` functions or defines global variables or any of the other confounders mentioned in the thread, and neither uses anything in openmmtools. (Also, `nvprof` confirms that neither of these spend much time on host-to-device transfer.)

```python
from simtk import openmm, unit

class GradientDescent(openmm.CustomIntegrator):
    def __init__(self, timestep=0.01 * unit.femtoseconds):
        super(GradientDescent, self).__init__(timestep)
        self.addUpdateContextState()
        self.addComputePerDof("x", "x + dt*(f/m)")
        self.addConstrainPositions()

class NoisyGradientDescent(openmm.CustomIntegrator):
    def __init__(self, timestep=0.01 * unit.femtoseconds):
        super(NoisyGradientDescent, self).__init__(timestep)
        self.addUpdateContextState()
        self.addComputePerDof("x", "x + dt*((f/m) + gaussian)")
        self.addConstrainPositions()
```

On OpenMM version 7.2.0.dev-69aa676, there's a negligible performance difference between these two integrators (13.398s vs 13.407s to run 5000 steps, average of 5 repetitions).

On OpenMM version 7.3.0.dev-f6cbe7d, there's a negligible performance difference between these two integrators (16.1768s vs 16.1744s to run 5000 steps, average of 5 repetitions).

However, there does appear to be a noticeable difference between the two versions of OpenMM I tested (7.3 is ~20% slower than 7.2). Is there the possibility of a generic slowdown of CustomIntegrator after OpenMM 7.2?

Timing script: https://gist.github.com/maxentile/af670a8295c7749a7e5cf502f4943720
Platform: CUDA, precision: mixed, GPU: 1080Ti.

**Comment by peastman** [comment]
If in doubt, run both versions in nvvp and see where the difference is coming from.  The profiler is your friend!

**Comment by peastman** [comment]
First, reduce the length of the simulation.  For profiling, about 100 steps is the maximum you want to do, and less is fine.

Now zoom in on the time line so it's showing just 2 or 3 time steps.  That will let you make out the individual kernels.  You can see which ones it's spending most of its time in.  You can also see if there are gaps where the GPU isn't doing anything.

Also look at the "GPU Details (Summary)" tab.  You can highlight individual kernels in the timeline and see the average duration for each one.  Are there particular kernels that are taking longer in one case than the other?  This needs to be interpreted carefully though.  It can execute multiple kernels at once in different streams, so the execution time for a kernel may depend on what else is running at the same time.  You can determine that from the timeline.  Also see if there's a lot of variation, where a kernel sometimes takes much longer than others.
