### ISSUE TITLE
Inconsistent AmoebaMultipoleForce energy between CPU vs CUDA platform (nan energy in CUDA)

### ISSUE THREAD

**Issue by scychon** [pandegroup/openmm#2145]
I'm working with Mary van Vleet to implement our newly developed SAPT-based water model with OpenMM. We've got the force field working in CPU platform, but is unable to use the same forcefield with CUDA platform. The problem happens when I try to use PME with AmoebaMultipoleForce in CUDA platform. While CPU platform gives reasonable energy value, CUDA platform gives nan energy for AmoebaMultipoleForce. Moreover, a weird thing happens with getKineticEnergy function of state. It gives unrealistically large number (25316962372.434834 kJ/mol) while the velocity vectors shows they are explicitly zero. If I turn off the PME part it works fine in CUDA. This happens with even water dimer case. I've tested with removing all the other force components before creating the simulation object, and it does happen when there's only AmoebaMultipoleForce there.

I also get 700 CUDA error when I include somewhat modest sized system (~800 water molecule box initiated with tip3p.pdb) but with large cutoff for multibody interactions, when I try to get the state information. "Error synchronizing on event for CustomManyParticleForce: CUDA error (700) ..." I guess this is related to the CUDA memory issue, but wasn't sure how to bypass this error or how to increase the GPU memory allocation if its possible. Again, the same setup works well in CPU platform, albeit very slow.

Could you please see whether there could be some issues with both AmoebaMultipoleForce with PME and CustomManyParticleForce ?

I've compiled OpenMM-7.2 from the git source, with CUDA 9.0
I'm seeing these errors both with GTX-1080 Ti and Titan Xp.
 
I attached the files that can reproduce those errors.
If you just uncomment the line for PDBFile('tip3p.pdb') you can see the second error as well. (It might be system dependent though.)
[saptwater.zip](https://github.com/pandegroup/openmm/files/2280085/saptwater.zip)

As always, thanks a lot for your helpful feedback and responses.

**Comment by peastman** [comment]
I'm getting an error trying to expand your zip file.

```
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
```

Can you check to make sure it hasn't gotten corrupted?

**Comment by scychon** [comment]
That's strange. I just downloaded the linked file and successfully uncompressed it using Mac's finder. Just in case, I recompressed it and attached the zip file again. If the link still doesn't work, you can access the files via the following link to my dropbox,

https://www.dropbox.com/sh/smfgmwmm6kftu3o/AAApBHZYGFYVww5QonugRHqya?dl=0
 
[saptwater.zip](https://github.com/pandegroup/openmm/files/2292321/saptwater.zip)

**Comment by peastman** [comment]
Thanks, that works.  I'm investigating now.

**Comment by peastman** [comment]
It looks like this is happening because some polarizabilities are set to 0.  On the CPU, this leads to a huge number multiplied by 0, which is 0.  But the CUDA platform is working in single precision, and the huge number is too large to represent in single precision.  So it becomes Inf, and Inf\*0=nan.

It should be easy to put in a check for this case.

**Comment by scychon** [comment]
Thanks. Yes I also suspected that this might be due to the 0 polarizabilities, which might be related to issue #1644 . I look forward to seeing the update.

**Comment by peastman** [comment]
The fix is in #2152.  Give it a try.

**Comment by scychon** [comment]
Thanks ! That worked beautifully and now the energies from both CPU and CUDA kernels are consistent.

I still get the 700 CUDA error  with CustomManyParticleForce, which you can see by changing the initial PDB structure from water.pdb to 'tip3p.pdb' (uncomment line 19 on 'run.py'). I think this should be related to CUDA Memory, but don't know what would be the work around for this. For current simulation of small water box I can avoid the error by invoking short cutoff distance for the CustomManyParticleForce, but this would ultimately happen with even smaller cutoffs as system gets larger. Do you have any suggestions? Or could it be avoided with simple check in the kernel?

**Comment by peastman** [comment]
I changed which PDB file it loads, and there is now a CustomManyParticleForce, but I don't get the CUDA error.  I also tried running it through `cuda-memcheck` and it didn't report any problems.  Is there anything else I need to change?

**Comment by scychon** [comment]
No that should be enough to trigger the error. Could it be GPU & CUDA specific? I'm using GTX-1080 Ti with CUDA-9.0 to compile mine, and attached the error & output messages from using cuda-memcheck. Is there any other CUDA tools that I can use  to diagnose the cause?
[err.txt](https://github.com/pandegroup/openmm/files/2295476/err.txt)
[out.txt](https://github.com/pandegroup/openmm/files/2295477/out.txt)

**Comment by peastman** [comment]
I'm using a Titan X, which is very similar to the 1080 Ti, so it's unlikely to be a hardware difference.  Are you using the latest development code?  There was a CUDA error fixed a couple of months ago (#2102) that produced errors similar to that, though I don't think it was in exactly the same place.

**Comment by scychon** [comment]
Updating to the latest development code fixed it. Thanks a lot !!

**Comment by peastman** [comment]
Great!
