### ISSUE TITLE
CUDA 10 announced

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#2147]
CUDA 10 was recently announced:

https://developer.nvidia.com/announcing-cuda-toolkit-10

The "CUDA Graphs" feature appears to be some sort of built-in graph computation execution engine:
> CUDA Graphs: Programming model constructs for a "define-once-run-repeatedly" execution flow

Presumably, CUDA 10 will support the new NVIDIA RTX hardware which include ray-tracing (RT) cores in addition to tensor cores:

https://www.tomshardware.com/news/nvidia-turing-quadro-rtx-announced,37599.html

**Comment by jchodera** [comment]
@peastman: I have CUDA 10.0 builds of the latest `master` up:
```
conda install --yes -c omnia/label/devcuda100 openmm
```
Can you give them a try if you have a CUDA 10 installation and/or new hardware to play with?

Also, do we know anyone with incoming new RTX 20x0 hardware? Are you able to access any as part of a developer program?

**Comment by peastman** [comment]
> Also, do we know anyone with incoming new RTX 20x0 hardware? Are you able to access any as part of a developer program?

I don't have access to one.

**Comment by jchodera** [comment]
We now have CUDA 10 support (though 9.2 is still default).
