### ISSUE TITLE
release GPU memory in script

### ISSUE THREAD

**Issue by euhruska** [pandegroup/openmm#2148]
Is there a command to release all GPU memory in python after the simulation is finished?
I want to do later in the same script some memory intensive calculations, but I can't see any information hot to release the GPU memory before the python script is done.

**Comment by sroet** [comment]
I normally free up the GPU for another process (my GPUs are in exclusive process mode) via deletion of the context
```python
del simulation.context
``` 
you do need to get the relevant data out of your simulation before you do this and recreate the `simulation` object afterwards if you want to start running simulations again

**Comment by euhruska** [comment]
is that a python command?

**Comment by peastman** [comment]
To make sure everything is released it's best to do this:

```python
del simulation
del integrator
```

**Comment by euhruska** [comment]
works as intended, thank you
