### ISSUE TITLE
atan2 in Force expressions

### ISSUE THREAD

**Issue by ljmartin** [pandegroup/openmm#2151]
Hi, 
Is it possible to add the atan2 function to the acceptable terms in an expression for a Force object e.g. CustomCentroidBondForce? I think I could replicate its function using a bunch of `step`/`max`/`select` functions but atan2 would be a lot simpler to implement, for example, restraints based on the angle around the z axis in the xy plane. atan2 takes into account the quadrant of the x and y coordinates to give the angle to the positive x axis. 
Thankyou. 
P.S. I have no idea of the amount of work, but could all the `math` library methods be added? Can I do this myself somehow? I can't find it in openmm.py which is why I came here.

**Comment by ljmartin** [comment]
Turned out to be quite easy to make with the step function:
`force2 = CustomCentroidBondForce(1, "atan2; atan2 = step(x1)*angle + step(-x1)*step(y1)*(angle+180) + step(-x1)*step(-y1)*(angle-180); angle = atan(y1/x1)*180/3.14159265")`
 but Ill leave this up for the moment for comment.

**Comment by peastman** [comment]
That should be pretty easy to add.
