### ISSUE TITLE
CustonNonbondedForce() add specific pairwise interaction parameters

### ISSUE THREAD

**Issue by TensorDuck** [pandegroup/openmm#2167]
OpenMM is quite nice so far, but I am running into a problem I am hoping you can give some suggestion to work through. I am trying to make a Structure-Based Coarse-Grained model with openMM. This would require adding a usual LJ potentials, but it would also require adding specific pairwise interactions that are not based off particle type. This would be similar to the GROMACS Pairs section where you can specify a pair of atom indices and their corresponding parameters.

For example, if I add:
E = (Ca / r) ^12 - (Cb / r) ^ 6

Where C1 and C2 are not particle specific, and can not be cast as a combination of two particle parameters. In principle I would like E to be any arbtirary function of specific parameters. In GROMACS, this is just giving a list in the topology file with the atom indices followed by Ca and Cb. I'm wondering if there is an analagous way to do this with OpenMM? I am wondering if I've missed something very simple and I am open to any suggestions.

My thoughts based on my understanding:
I looked in the documentation, and there doesn't appear to be an easy way to do this. The best suggestion I've seen in the issue log so far is to add them all as a tabulated function, but the documentation for tabulated functions seem to indicate the feature will be deprecated soon here: 
http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.TabulatedFunction.html#simtk.openmm.openmm.TabulatedFunction

Alternatively, I considered I can add all the custom values as Global Parameters and have multiple CustomNonbondedForces() objects for each specific pairwise interaction. I was wondering if this would hinder performance if I have many such forces. 

Many Thanks

**Comment by peastman** [comment]
> the documentation for tabulated functions seem to indicate the feature will be deprecated soon here

Definitely not!  That notice just refers to the `Copy()` function.  Tabulated functions are here to stay.

If you just want to add an interaction between two specific particles, what about doing it with a CustomBondForce?  That's what it's for.

**Comment by peastman** [comment]
That depends what you're doing.  Are you adding the force to the system directly, or creating it from a ForceField?  If you add it directly, it has no effect on exclusions.  That's determined by the list of bonds passed to `createExceptionsFromBonds()`.  But if you add a `<CustomBondForce>` tag to a force field definition, it will take those bonds into account when determining exclusion.

**Comment by peastman** [comment]
Great!
