### ISSUE TITLE
Keep the CustomIntegrator Python class in CompoundIntegrator.getIntegrator()

### ISSUE THREAD

**Issue by andrrizzi** [pandegroup/openmm#2168]
I believe `Context.getIntegrator()` now maintains the Python class of integrators inheriting from `CustomIntegrator`, but `CompoundIntegrator.getIntegrator()` doesn't. It would be a nice addition to 7.3 if it's still possible to add the fix.

**Comment by peastman** [comment]
I did try to do that a while back, but I ran into segfaults and eventually concluded it just wasn't possible to do reliably.  See https://github.com/pandegroup/openmm/pull/1882#issuecomment-325003199.

**Comment by andrrizzi** [comment]
I see. Apologies for forgetting about that. Thank you anyway!
