### ISSUE TITLE
possible to support cuda 9.1

### ISSUE THREAD

**Issue by jht0664** [pandegroup/openmm#2169]
Hi,

I read #2169 #2084 issues, but I wonder if OpenMM 7.3 would support different versions of CUDA library and development version currently could read CUDA 9.1 library.
Because Titan supercomputer at Oak Ridge Nat. Lab has CUDA 9.1 and older versions (5, 6.5, 7.0, and 7.5),
if possible, I would like to get a help to run OpenMM with CUDA 9.1.

**Comment by jchodera** [comment]
This is also exactly what we are using on ORNL Titan, so it should work for you too!

**Comment by jht0664** [comment]
Thank you for a help! It works
