### ISSUE TITLE
Forces differ between platforms

### ISSUE THREAD

**Issue by jlmaccal** [pandegroup/openmm#2186]
I am working on a port of the martini force field to openmm. As part of this, I have been validating by comparing the openmm forces and energies to those from gromacs.

I have five different test systems. Four of these are behaving correctly, giving relative energy and force errors of < 1e-5.

However, the last system is behaving very strangely. It is a much larger (300k particles) and more complex system with a mixture of different proteins and lipids. The energy differs by a large amount (1000 kJ/mol), but the relative relative error isn't too crazy at ~1e-4. What is more troubling is that some of the forces have large errors, e.g. 0.6 kJ/mol/nm error on a force of 130 kJ/mol/nm, or 0.5%, which seems way too large.

I've noticed large differences between platforms:

- Both `CPU` and `Reference` give many particles with large force errors.
- Even stranger, the errors are almost exclusively in the x-component of the force. There is nothing about the system that would suggest anything strange should preferentially be happening in the x-direction.
- The errors also appear to come in pairs, where one particle has an error of +X and another has an error of -X.
- Almost all of the force errors are in the proteins, with the exception of a single pair of water molecules that are near to each other across the periodic boundaries (not coincidentally across the x-boundary).
- For `CUDA`, the results are much better, with only the same single pair of water molecules giving a large force error. All of the other errors are much smaller and are more uniformly mixed between x, y, and z-components.

This is all very confusing. I think this is a bug in openmm, but I'm not sure where to even start looking. I think this might have something to do with re-indexing of molecules. The fact that it occurs in the x-direction seems like a clue.

@peastman Any thoughts on where to start looking?

**Comment by peastman** [comment]
Can you post files to reproduce it?  If you've got a test case that consistently gives different forces on different platforms, it shouldn't be hard to track down where the difference is coming from.

What precision mode are you using for CUDA?  Try both single and double.  Do they agree with each other?

**Comment by jlmaccal** [comment]
I'll work to package up everything into a test case.

I also checked `cuda double`. It doesn't agree with `cuda mixed`.
- `CUDA double`, `CPU`, and `Reference` all have large force errors relative to `gromacs`. 
- `CUDA mixed` is much closer to `gromacs` with two of 300k atoms with larger than expected force discrepancies.
- `CUDA single` gives similar results to `CUDA mixed`, as expected.

I don't have a script that compares the forces from the different precision / platform combinations from openmm. I'll pull that together and include it as part of the test case.

**Comment by peastman** [comment]
I wondered if that might be the case.  I bet you're running Gromacs in single precision mode?  I wonder if this is really just a difference of numeric precision, and CUDA in single precision mode agrees with Gromacs because they are both equally inaccurate?

Try running the double precision version of Gromacs.  How do the results compare?

**Comment by jlmaccal** [comment]
I'll give that a try too.

I'm just surprised that the forces are off by that much. That seems too high to me to be a precision issue, but I guess if there are large opposing forces, it could be. Why would it be more prevalent with a larger system size? Is it just a larger statistical sample, so there are more outliers?

I'm working on testing, and it seems that the discrepancy between platforms is for the bonded and LJ terms. For bonded, `CPU` + `Reference` + `CUDA double` agree, but `CUDA_single` is different. For LJ, `Reference` and `CUDA double` match, as do `CPU` and `CUDA single`, but they don't agree with each other.

**Comment by peastman** [comment]
Not coincidentally, the CPU platform evaluates bonded forces in double precision but LJ in single precision.

**Comment by jlmaccal** [comment]
OK, this looks like it might just be a precision issue. I'm still a bit surprised the errors in forces are so large, but Reference, CUDA double, and gromacs in double agree very closely.

I want to do some more testing, but will close once I'm done.
