### ISSUE TITLE
Illegal CUDA device index on shareable multi-GPU node

### ISSUE THREAD

**Issue by lohedges** [pandegroup/openmm#2190]
This issue seems somewhat related to #2000, so apologies for any duplication.

Here at Bristol we have GPU nodes that contain two NVIDIA cards. We use the Slurm scheduler and users can request access to one or both of the GPUs on a node using the General Resource flag, `-gres`. If both GPUs are selected, then Slurm assigns the environment variable `CUDA_VISIBLE_DEVICES=0,1`. In the case of a single GPU the value is dependent on what other jobs are running on the node, and whether the user requests exclusive node access. If no other jobs are running, or if exclusive access is requested, then It will be set to `0`. If there is another single GPU job running, then the ID will be assigned to `0` or `1` depending on which device is free. Importantly, Slurm hides GPUs that are not accessible to the user, so `CUDA_VISIBLE_DEVICES` only contains a single entry whenever a single GPU is requested.

On line 180 of [CudaContext.cpp](https://github.com/pandegroup/openmm/blob/master/platforms/cuda/src/CudaContext.cpp#L180) there is a check to see whether the GPU device index is less than, or equal to, the number of visible devices:

```cpp
int numDevices;
CHECK_RESULT(cuDeviceGetCount(&numDevices));
  if (deviceIndex < -1 || deviceIndex >= numDevices)
    throw OpenMMException("Illegal value for DeviceIndex: "+intToString(deviceIndex));
```

This exception will be thrown whenever a user is given a device index that is equal to, or greater than, the number of visible devices on a multi-GPU node, i.e. in our case device index `1` since `1 >= 1 == True`.

As a workaround, the user can place the following in their batch script:

```bash
GPU_ID = $CUDA_VISIBLE_DEVICES

if [ "$GPU_ID" == "0" ]; then
    export CUDA_VISIBLE_DEVICES=0,1
elif [ "$GPU_ID" == "1" ]; then
    export CUDA_VISIBLE_DEVICES=1,0
fi
```

This ensures that `CUDA_VISIBLE_DEVICES` always contains two entries, regardless of how many GPUs are requested. This is safe, since the environment variable is set by Slurm at runtime on a per user basis, so wont affect other jobs on the node. (The variable is unique to the user for the duration of the job.)

Is there a reason for this runtime device ID check that I'm missing? It seems that Slurm is correctly configuring the compute environment, but perhaps there are other setups where things are done differently.

**Comment by peastman** [comment]
When you set CUDA_VISIBLE_DEVICES, it appears to all CUDA programs that there's a smaller number of devices.  Those devices are still indexed from 0 to numDevices.  The indices (as seen by the program) refer to the order of devices as listed in CUDA_VISIBLE_DEVICES.  So if there's only one device available, you should tell OpenMM to use device 0.  If CUDA_VISIBLE_DEVICES is set to "1", that will actually correspond to the device whose true index is 1.

**Comment by lohedges** [comment]
Ah, thanks for the clarification. That makes sense: the device index is actually the index into the CUDA_VISIBLE_DEVICES array, not the actual hardware device index. I am using OpenMM indirectly via SOMD and the documentation for the GPU index configuration parameter did not make this clear.

I'll test this on our cluster tomorrow and close the issue when I'm done.

Cheers.

**Comment by lohedges** [comment]
Just to confirm that everything is now working as expected. Thanks again for your help.
