### ISSUE TITLE
Error in compiling openmm from source

### ISSUE THREAD

**Issue by mrinal-shekhar** [pandegroup/openmm#2201]
Hi 
I have been trying to compile openmm from source using ccmake and following the instructions 
http://docs.openmm.org/6.1.0/userguide/library.html
However at the   Step 3: Build OpenMM stage, i am getting stuck with the following error.

Scanning dependencies of target OpenMM
[  0%] Building CXX object CMakeFiles/OpenMM.dir/openmmapi/src/PeriodicTorsionForceImpl.cpp.o
[  0%] Building CXX object CMakeFiles/OpenMM.dir/openmmapi/src/HarmonicBondForce.cpp.o
[  0%] Building CXX object CMakeFiles/OpenMM.dir/openmmapi/src/CustomExternalForceImpl.cpp.o
[  0%] Building CXX object CMakeFiles/OpenMM.dir/openmmapi/src/AndersenThermostatImpl.cpp.o
/Scr/mrinal/install/openmm/openmm/openmmapi/src/AndersenThermostatImpl.cpp: In static member function 'static void OpenMM::AndersenThermostatImpl::tagParticlesInGroup(int, int, std::vector<int, std::allocator<int> >&, std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >&)':
/Scr/mrinal/install/openmm/openmm/openmmapi/src/AndersenThermostatImpl.cpp:97: error: expected initializer before ':' token
/Scr/mrinal/install/openmm/openmm/openmmapi/src/AndersenThermostatImpl.cpp:100: error: expected primary-expression before '}' token
/Scr/mrinal/install/openmm/openmm/openmmapi/src/AndersenThermostatImpl.cpp:100: error: expected ';' before '}' token
/Scr/mrinal/install/openmm/openmm/openmmapi/src/AndersenThermostatImpl.cpp:100: error: expected primary-expression before '}' token
/Scr/mrinal/install/openmm/openmm/openmmapi/src/AndersenThermostatImpl.cpp:100: error: expected ')' before '}' token
/Scr/mrinal/install/openmm/openmm/openmmapi/src/AndersenThermostatImpl.cpp:100: error: expected primary-expression before '}' token
/Scr/mrinal/install/openmm/openmm/openmmapi/src/AndersenThermostatImpl.cpp:100: error: expected ';' before '}' token
make[2]: *** [CMakeFiles/OpenMM.dir/openmmapi/src/AndersenThermostatImpl.cpp.o] Error 1
make[1]: *** [CMakeFiles/OpenMM.dir/all] Error 2
make: *** [all] Error 2

Please help, new to the openmm community.
Regards
Mrinal

**Comment by peastman** [comment]
Which version of the code are you compiling?  The instructions you linked to are for 6.1, which is a quite old version.  The current documentation is at http://docs.openmm.org/latest/userguide/library.html#compiling-openmm-from-source-code.

Also, what compiler and OS are you using?

**Comment by mrinal-shekhar** [comment]
Hello
Thanks for the prompt reply. I am using gcc compiler on linux. On the basis of your reply, i downloaded the git version and followed the instructions. I am now getting an error in compilation at 21 %. I am attaching a screenshot of the same.
<img width="1318" alt="screen shot 2018-11-06 at 4 46 16 pm" src="https://user-images.githubusercontent.com/40069534/48095788-96491d80-e1e3-11e8-9e64-af26c3f46a92.png">

**Comment by mrinal-shekhar** [comment]
I think i have closed this issue by mistake, can it be opened again

**Comment by peastman** [comment]
I haven't seen that error, but it sounds like the one described at https://stackoverflow.com/questions/956640/linux-c-error-undefined-reference-to-dlopen.  When you run `ccmake`, try adding `-ldl` to `CMAKE_CXX_FLAGS`.

**Comment by mrinal-shekhar** [comment]
Hello
Thanks for the response the compilation was completed. However when i am doing the unit tests using 
make test
I am getting the following tests fails which makes me nervous as they pertain mainly to Cuda
<img width="925" alt="screen shot 2018-11-06 at 6 18 53 pm" src="https://user-images.githubusercontent.com/40069534/48100266-7cfa9e00-e1f0-11e8-957d-c3ae1bd340ce.png">

**Comment by mrinal-shekhar** [comment]
I tried to individually test them and it seems for some reason they are pointing to a wrong location for the CUDA compiler. It is present in /usr/local/cuda-9.0/bin/nvcc and not in usr/local/cuda/bin/nvcc. 
How can i fix it after i have compiled the code. Do i need to restart from scratch? Here is the error

bash-4.2$ ./TestCudaVerletIntegrator
exception: Error launching CUDA compiler: 32512
sh: /usr/local/cuda/bin/nvcc: No such file or directory

**Comment by peastman** [comment]
Ok, that's fine.  You just need to tell it where to find the compiler.

```
export OPENMM_CUDA_COMPILER=/usr/local/cuda-9.0/bin/nvcc
```

After setting that environment variable, the tests should work.  See http://docs.openmm.org/latest/userguide/library.html#cuda-platform for more information.

**Comment by mrinal-shekhar** [comment]
Thanks worked this time. Closing the issue
