### ISSUE TITLE
How to add restraining potential

### ISSUE THREAD

**Issue by snpreddy** [pandegroup/openmm#2206]
I have tried to add external force, it's not taking into account. I think something is missing, I appreciate if some one look at this. --Thanks

from __future__ import print_function
from simtk.openmm import app
import simtk.openmm as mm
from simtk import unit
from sys import stdout
import mbpol

simulation_name = "w4"
pdb = app.PDBFile('w4.pdb')
temperature = float(250)*unit.kelvin
forcefield = mm.app.ForceField("/opt/conda/miniconda2/envs/openmm_env/lib/python3.6/site-packages/mbpol-1.0-py3.6-linux-x86_64.egg/mbpol.xml")
nonbonded = mm.app.CutoffNonPeriodic
ewaldErrorTolerance = 1e-8
timestep = 0.2*unit.femtoseconds
production_steps = 1500000
################################## NVE

system = forcefield.createSystem(pdb.topology, nonbondedMethod=nonbonded,
    nonbondedCutoff=0.9*unit.nanometers, ewaldErrorTolerance=ewaldErrorTolerance)

force = mm.CustomExternalForce('100*max(0, r-2)^2; r=sqrt(x*x+y*y+z*z)')
system.addForce(force)
for i in range(system.getNumParticles()):
    force.addParticle(i, [])

integrator = mm.VerletIntegrator(timestep)
simulation = app.Simulation(pdb.topology, system, integrator)
simulation.loadState('nvt7.xml')
final_nvt_state = simulation.context.getState(getVelocities=True, getPositions=True)
positions = final_nvt_state.getPositions()
velocities = final_nvt_state.getVelocities()
simulation.context.setPositions(positions)
simulation.context.computeVirtualSites()
simulation.context.setVelocities(velocities)
simulation.reporters.append(app.PDBReporter('restart_nve.pdb', 5))

simulation.reporters.append(app.StateDataReporter(simulation_name + "_restart_nve.log", 20, step=True,
    potentialEnergy=True, kineticEnergy=True, totalEnergy=True, temperature=True,
    progress=True, remainingTime=True, speed=True, totalSteps=production_steps,
    separator=' '))

print('Running Production...')
simulation.step(production_steps)
print('Done!')

**Comment by jchodera** [comment]
Does this code actually run? It looks like your energy expression is malformed:
```
force = mm.CustomExternalForce('100max(0, r-2)^2; r=sqrt(xx+yy+zz)')
```
The energy expression should presumably be 
```
force = mm.CustomExternalForce('100*max(0, r-2)^2; r=sqrt(x^2+y^2+z^2)')
```
You'll also want to be careful about constants like `100`, since OpenMM assumes they are in MD units (kJ/mol, nm, etc.). You can use global variables to let OpenMM automatically convert for you:
```
force = mm.CustomExternalForce('(K/2)*max(0, r-2)^2; r=sqrt(x^2+y^2+z^2)')
force.addGlobalParameter('K', 100*unit.kilocalories_per_mole/unit.nanometers**2)
```
See the [API docs](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.CustomExternalForce.html#simtk.openmm.openmm.CustomExternalForce) for more details.

**Comment by snpreddy** [comment]
Thanks @jchodera 
The expression was "force = CustomExternalForce('100*max(0, r-2)^2; r=sqrt(x*x+y*y+z*z)')". While copying it turned that. 
I have copied your two lines, still not taking into account.

In the link (http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.CustomExternalForce.html#simtk.openmm.openmm.CustomExternalForce)

force = mm.CustomExternalForce("k*((x-x0)^2+(y-y0)^2+(z-z0)^2)")
force.addGlobalParameter("k", 5.0*kilocalories_per_mole/angstroms**2)
force.addPerParticleParameter("x0")
force.addPerParticleParameter("y0")
force.addPerParticleParameter("z0")

Here the expression defines energy, the manual says we need to add a particle and call it to experience the field. I have gone through the related issues, and didn't get clarity to define. Could you please help me to do it?

**Comment by Lnaden** [comment]
The `CustomExternalForce`'s energy expression knows that `x`, `y`, and `z` are the X, Y, and Z coordinate of each particle you add to the force, the index of the particle you add to this force matches up to the index of the the particles in the `System` object.

Most every other string of alpha-numeric characters have to be defined as by one of the following:
* A follow-up expression in the energy expression string (which you already did by defining `; r=sqrt(...)` in your expression after)
* As a `PerParticleParameter` such as the example in the API docs where `force.addPerParticleParameter("x0")` defines the behavior of the `x0` in the energy expression i.e. `(x-x0)`. The value of these parameters are defined *per particle* as the function implies and are set when you do the `addParticle` call on the `force`. I'll put an example below.
* As a `GlobalParameter` which is a single value set when you define it. this is like the API docs where `force.addGlobalParameter("k", 5.0*kilocalories_per_mole/angstroms**2)` defines the behavior of `k` in the energy expression, and then also sets its initial value to 5 kcal/mol/A^2, which will get automatically converted to the internal unit system of kJ/mol/nm^2; no need to do the calculation yourself.

Exceptions to the above rules are built in functions like `sqrt()` and each `Custom*Force` may have slightly different rules defined, e.g. the `CustomNonbondedForce` knows that `r` is particle-particle separation distance, `CustomExternalForce` does not. There are some nuances to the Global Variables shared between different forces, but thats not important for this example or your original issue.

So on this API example of the `PerParticleParameter`s of `x0`, `y0`, and `z0`: by adding these three per-particle parameters to the `force`, we now *must* define 3 parameters every time we add a particle. So in your call where you do 
```python
for i in range(system.getNumParticles()):
    force.addParticle(i, [])
```
you would replace the empty list of `[]` with 3 values for each particle you add.
```python
for i in range(system.getNumParticles()):
    force.addParticle(i, [25*unit.angstrom, -5*unit.angstrom, 2.5*unit.angstrom])
```
which would set every particle to have `x0 = 25A`, `y0=-5A`, and `z0=2.5A`. I'm guessing you don't want them all the same, but this should show the basic call and code.

In theory, you could do the `addParticle` calls and the `addPerParticleParameter` calls in any order, so long as the number of per-particle parameters for each atom equals the number of `addPerParticleParameter` calls, but for clarity for yourself and anyone else looking at your code, you might want to do the `addPerParticleParameter` calls before the `force.addParticle` calls.

In your original code, `xx` is not a term defined, and as @jchodera alluded to, you probably meant "particle X coordinate square" which would be `x^2`. If you meant for `xx` to mean something else, you would need to define it as a Per-Particle or Global Parameter

**Comment by peastman** [comment]
The confusion is happening because you didn't surround your code with \``` lines, so Github interprets it as markdown.  \* indicates italic, so where you wrote `x*x` it's being displayed as x*x*.

**Comment by peastman** [comment]
What leads you to believe the force isn't being applied?

**Comment by snpreddy** [comment]
> What leads you to believe the force isn't being applied?

I am comparing the log file which ran earlier with out field. I have observed the energy and T varied from the old one if field applied.

**Comment by snpreddy** [comment]
@peastman 
As you suggested, I have checked the platform, using Reference, and it’s double precision. So the problem is not related to precision.

As suggested by @jchodera, applied external force, still E not conserved. I don’t know the problem exactly which leads large drift in E.

Could you please let me know any other options to solve it?

**Comment by snpreddy** [comment]
> The confusion is happening because you didn't surround your code with ``` lines, so Github interprets it as markdown. * indicates italic, so where you wrote `x*x` it's being displayed as x_x_.

Okay, now I understand.
I will crosscheck while posting to avoid confusion.
