### ISSUE TITLE
Default problem in mm.CustomCentroidBondForce  

### ISSUE THREAD

**Issue by hhh-water** [pandegroup/openmm#2210]
I want to use OpenMM7.2.2 to take umbrella sampling simulations. However, i can not get a reasonable value in PMF. So, i may make a mistake with the default unit in CustomCentroidBondForce. what is the default unit with "k" in the OpenMM? kJ mol^-1 nm^-2 or kJ mol^-1 Å^-2? 

rest_force=mm.CustomCentroidBondForce(2,"0.5*k*(distance(g1,g2)-r0)^2")
rest_force.addPerBondParameter('r0')
rest_force.addPerBondParameter('k')
rest_force.addGroup([39,89])
rest_force.addGroup([80])
system.addForce(rest_force)
rest_force.addBond([0,1],[dist_ref,force_constant])
simulation = app.Simulation(psf.topology, system, integrator, platform)

**Comment by jchodera** [comment]
If you don't specify units, everything is in [default OpenMM units](http://docs.openmm.org/latest/userguide/theory.html#units). However, it is highly recommended you instead explicitly provide units and have OpenMM convert for you, such that `dist_ref` is something like `10.0 * unit.angstroms` (or compatible dimensions) and `force_constant` is something like `10.0 * unit.kilojoules_per_mole / unit.angstroms**2` (or compatible dimensions).

**Comment by hhh-water** [comment]
@jchodera thank you for your reply.
