### ISSUE TITLE
RTX support

### ISSUE THREAD

**Issue by amrhamedp** [pandegroup/openmm#2213]
Hello,
I would like to install openmm on a machine which has turing card. I would like if it can be done  or if there is a work around to get it working. I have both cuda 10 and cuda 9.2 installed.

**Comment by peastman** [comment]
Try it and see.  I haven't tested a Turing GPU, but I don't know any reason it wouldn't work.  I'd certainly be interested to hear whether it works, and how fast it is.

**Comment by giadefa** [comment]
it works. Around 900 ns/day at 5 fs on 2080TI.

**Comment by Lnaden** [comment]
Interesting! Could you provide the command you ran to get that number, just so we have a reference on what system/settings you ran with? Thanks!

**Comment by giadefa** [comment]
python benchmark.py --platform CUDA --test pme --heavy-hydrogens

on a Acellera MetroCubo 4x RTX2080TI machine

**Comment by giadefa** [comment]
with cuda10 installed

**Comment by peastman** [comment]
Nice!   On a Titan X that same command gives 772 ns/day, so that's about a 15% speedup.  Not huge, but still significant.

Which OpenMM version did you test?  7.3 has optimizations for Volta which probably help Turing as well.

**Comment by giadefa** [comment]
# Name                    Version                   Build  Channel
openmm                    debug            py37_cuda100_1
omnia/label/devcuda100

**Comment by peastman** [comment]
@jchodera "debug" doesn't mean it was compiled in debug mode, does it?

**Comment by amrhamedp** [comment]
I think it is higher
(normal_openmm) [root@3a41d28d5687 examples]# python benchmark.py --platform CUDA --test pme --heavy-hydrogens
Platform: CUDA
Precision: single

Test: pme (cutoff=0.9)
Step Size: 5 fs
Integrated 123041 steps in 54.5561 seconds
974.295 ns/day

**Comment by amrhamedp** [comment]
This is the full test using rtx 2080ti nvidia stock card
normal_openmm) [root@3a41d28d5687 examples]# python benchmark.py --platform CUDA  --heavy-hydrogens
Platform: CUDA
Precision: single

Test: gbsa
Step Size: 5 fs
Integrated 216036 steps in 55.5965 seconds
1678.66 ns/day

Test: rf
Step Size: 5 fs
Integrated 159240 steps in 56.5597 seconds
1216.27 ns/day

Test: pme (cutoff=0.9)
Step Size: 5 fs
Integrated 124469 steps in 56.2219 seconds
956.399 ns/day

Test: apoa1rf
Step Size: 5 fs
Integrated 56497 steps in 60.0902 seconds
406.168 ns/day

Test: apoa1pme
Step Size: 5 fs
Integrated 40258 steps in 58.5531 seconds
297.02 ns/day

Test: apoa1ljpme
Step Size: 5 fs
Integrated 30728 steps in 58.1294 seconds
228.361 ns/day

Test: amoebagk (epsilon=1e-05)
Step Size: 2 fs
Integrated 2797 steps in 57.5532 seconds
8.39782 ns/day

Test: amoebapme (epsilon=1e-05)
Step Size: 2 fs
Integrated 6653 steps in 59.7942 seconds
19.2266 ns/day

**Comment by giadefa** [comment]
use --seconds=600
there is quite a bit of thermal speed adjustment  and a lot of variation
depending on how many GPUs are on.

**Comment by peastman** [comment]
If you have to run it that long for the speed to settle down, that suggests your computer doesn't have enough cooling.  When you're ordering a computer to put a high end GPU into, always get the upgraded cooling system.  Otherwise you'll get thermal throttling and you won't see the full performance of the GPU.

**Comment by peastman** [comment]
If you have enough cooling it won't heat up, no matter how long you run it.  However many cards are in your computer, you should be able to run all of them at 100% utilitization indefinitely and never get any throttling.

**Comment by giadefa** [comment]
as far as I understand that is how RTX works. They are continuously
boosting up and down to maintain the power and thermal limits.
They appear to stay in P2 all the time from nvidia-smi, but some site show
that can peak to 375W for milliseconds.

g

**Comment by peastman** [comment]
Exactly.  You want the GPU to constantly run at its maximum performance.  If you have enough cooling and a big enough power supply, it will.  For example, if you have four of those cards in a single box you should probably get a 2500W power supply.  If you don't you'll get less performance, but that doesn't reflect what the GPUs are capable of, just that they're being limited by having too small a power supply.

**Comment by giadefa** [comment]
you don't need a 2500W power supply.

Maybe I was not clear. The GPUs start at 30 degrees, after you start a job,
they can take several seconds or tens of seconds to stabilize to 70-80sh.
More if the cooling is good. So running for 60 seconds is border line in my
view.

**Comment by peastman** [comment]
For comparison, the following was run on a Titan V in a box with a big power supply and lots of cooling.

```
$ python benchmark.py --test=pme --platform=CUDA --seconds=60
Platform: CUDA
Precision: single

Test: pme (cutoff=0.9)
Step Size: 2 fs
Integrated 128245 steps in 58.8694 seconds
376.439 ns/day
$ python benchmark.py --test=pme --platform=CUDA --seconds=600
Platform: CUDA
Precision: single

Test: pme (cutoff=0.9)
Step Size: 2 fs
Integrated 1263619 steps in 581.813 seconds
375.298 ns/day
```

No difference at all.  Just before starting the first test, the GPU temperature was reported as 43C.  Immediately after finishing the second one, it was reported as 64C.  It went up a bit, but remained well below the range where it starts to throttle.
