### ISSUE TITLE
Segfault when running in travis

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#2216]
@andrrizzi : Can we report this problem to the OpenMM issue tracker with a pointer to the code?
https://travis-ci.org/choderalab/openmmtools/jobs/460717552#L3410-L3413
```
ThermodynamicState._find_barostat() method. ... ok (0.0022s)
ThermodynamicState._find_thermostat() method. ... *** Error in `/home/travis/miniconda/envs/test/bin/python': corrupted size vs. prev_size: 0x0000000003716290 ***
/home/travis/.travis/job_stages: line 104:  2862 Aborted                 (core dumped) nosetests $PACKAGENAME --nocapture --verbosity=2 --with-timer --with-doctest --doctest-options="+IGNORE_EXCEPTION_DETAIL" -a '!slow'
```
I think we've had difficulty reproducing it locally, but I'm going to try to get some memory issue testing implemented in travis, and we might be able to track it down that way.

There may also be a way for us to build a `dev` openmm package that gives better stack traces on segfaults.

**Comment by andrrizzi** [comment]
I don't think this is caused by a bug in openmm or openmmtools. I did a lot of testing on travis a few months ago and the SWIG resources are already deallocated before reaching that test. This is likely a problem that arise only when you mix nosetests, Travis, and SWIG.

**Comment by jchodera** [comment]
Oh! Thanks for the clarification. Perhaps we should upgrade to pytest?

**Comment by andrrizzi** [comment]
> Perhaps we should upgrade to pytest?

I think it's worth the shot!
