### ISSUE TITLE
print out loaded forcefield parameter

### ISSUE THREAD

**Issue by jjgoings** [pandegroup/openmm#2219]
More of a question than an issue, but I couldn't find the answer I was looking for in the documentation.

If I have loaded a ForceField, what is the protocol for printing out the different force field parameters?

Obviously not the syntax, but I'd like to do something like

```
for atom1 in atomTypes:
    for atom2 in atomTypes:
        print(HarmonicBondForce(atom1,atom2).k)
        print(HarmonicBondForce(atom1,atom2).length)
```

And so on for angles, etc. Is this possible, and how might I do this?

**Comment by peastman** [comment]
All that information is in the files you just loaded.  See http://docs.openmm.org/latest/userguide/application.html#creating-force-fields for a description of the format.

**Comment by jjgoings** [comment]
Thanks @peastman 

I understand that the information is in the XML force field file, but I want to perform some manipulations on the force field within a Python script. I was hoping that instead of writing a parser for the XML file, I could use the fact that OpenMM reads and parses the XML already.

doing

```
from simtk.openmm.app import *

ff = ForceField('tip3p.xml')

for atom in ff._atomTypes:
    print(ff._atomTypes[atom].name,
          ff._atomTypes[atom].element,
          ff._atomTypes[atom].mass,
          ff._atomTypes[atom].atomClass)
```

gives

```
tip3p-O <Element oxygen> 15.99943 OW
tip3p-H <Element hydrogen> 1.007947 HW
```

which gets me part of the way, but I cannot figure out if/how I can print out the bond parameters for a bond between `tip3p-O` and `tip3p-H`.

**Comment by peastman** [comment]
All the parameters are stored in "generator" objects, each of which contains the information to create a single `Force` object.  You can call `getGenerators()` to get the generators for a force field, but their internals aren't documented.  You'll need to look at the source code for each one.  For example, this prints out the definitions of harmonic bonds:

```python
for g in ff.getGenerators():
  if isinstance(g, forcefield.HarmonicBondGenerator):
    for i in range(len(g.types1)):
      print(g.types1[i], g.types2[i], g.length[i], g.k[i])
```

Most of the generator definitions are pretty straightforward.  Let me know if you have questions about specific ones.

**Comment by jjgoings** [comment]
@peastman Perfect, thank you!

**Comment by jjgoings** [comment]
@peastman How do I obtain the Lennard Jones parameters? 

If, like before, I start with
```python
for g in ff.getGenerators():
  if isinstance(g, forcefield.LennardJonesGenerator):
    ...
```

I do not see a `g.types` option, and looking at the source it is not obvious to me where the `epsilon` or `sigma` are stored? Are non-bondeds handled differently internally?

**Comment by peastman** [comment]
First, are you sure you're actually looking for a LennardJonesGenerator instead of a NonbondedGenerator?  Many force fields use the latter.  LennardJonesGenerator exists to support the NBFIX terms that appear in some CHARMM force fields.  These are "special" pairs of atom types that use different parameters, not the ones you would normally get from the combining rules.

Assuming you really are looking at a LennardJonesGenerator, the field is called `ljTypes`, not `types`.  You'll also want to check the `nbfixTypes` field which records the NBFIX parameters.
