### ISSUE TITLE
No development builds

### ISSUE THREAD

**Issue by peastman** [pandegroup/openmm#2233]
https://anaconda.org/omnia/openmm/files reports that no dev builds have gotten uploaded in over a month and a half.  Any idea what's going on with that?

**Comment by jchodera** [comment]
To avoid interference with the standard release packages, we have moved the dev packages to a new channel (omnia-md):

https://anaconda.org/omnia-dev/openmm/files

That reminds me that I need to update the documentation!

**Comment by peastman** [comment]
Had you posted about that anywhere?  If so, I missed it.

So to install the dev build, the command would be

```
conda install -c omnia-dev openmm
```

Is that right?

**Comment by jchodera** [comment]
Yes, that should do it! Let me know if that doesn't work for you.

**Comment by peastman** [comment]
Ok, thanks.
