### ISSUE TITLE
LocalEnergyMinimizer_minimize failure 

### ISSUE THREAD

**Issue by frank-stonybrook** [pandegroup/openmm#2242]
Hi Guys, 

I am trying to debug a OpenMM **LocalEnergyMinimizer_minimize** failure. 
[
<img width="773" alt="screen shot 2019-01-11 at 12 29 32" src="https://user-images.githubusercontent.com/10855977/51049698-9d522a80-159c-11e9-9505-2df1afffa01c.png">
](url)

The system crashed at very beginning before running real simulation. Using minimized structure doesn't seem to help. The simulation still failed with the same error. By the way, the version of OpenMM I am using is already include the patch discussed in #1924 

Right now, I am suspecting:

1.  The distance restraints which introduced into my system using a plugin similar to  this(https://github.com/peastman/openmmexampleplugin). My question is whether those distance restraints will be enforced during minimization. I saw the docs mentions about distance constraint. Not quite sure the difference between them. 

2. Simultaneous request cuda compiler. Since my simulation is a replica exchange simulation, would a large number(~100) of GPUs request compiler at the same time might cause some trouble. 

Thanks.

**Comment by peastman** [comment]
That message means it tried to launch `nvcc` to compile a kernel, and it failed with error code 32512.  I don't know what that code means.  I haven't been able to find any documentation on it.  But having a large number of simultaneous contexts seems like a likely reason.  It's possible nvcc isn't designed to be executed on many processes at once.

If that's the reason, you might have more success with the runtime compiler instead.  Try setting `OPENMM_CUDA_COMPILER` to an empty string.  That will prevent it from using nvcc and (hopefully) cause it to use the runtime compiler instead.

Regarding distance restraints, the minimizer does respect them, but it makes minimization both slower and a lot more likely to fail.  (Constrained optimization is a lot harder than unconstrained!)  It replaces the constraints by harmonic restraints and runs the optimization.  It then checks to see if all constraints are satisfied to within the tolerance.  If not, it increases the strength of the restraints and calls the optimizer again.  This continues until it either satisfies all constraints to within tolerance, or the optimizer reports a failure.

**Comment by frank-stonybrook** [comment]
Thanks for your comment! I will try both approaches and see whether it help.

**Comment by peastman** [comment]
That means you're using too old a version of CUDA.  That function was introduced in CUDA 9.

**Comment by frank-stonybrook** [comment]
That's interesting, since I already load the cudatoolkit/9.1 in my job module. Why the system did not use the correct runtime compiler?

**Comment by frank-stonybrook** [comment]
Hi Peastman, 

Here is the output of ldd:
<img width="1090" alt="screen shot 2019-01-11 at 17 45 31" src="https://user-images.githubusercontent.com/10855977/51063409-df916100-15c8-11e9-9851-542474ddbb86.png">

The OpenMM version: 0fc3a50a927db4697b4f75d7f61ec97c496510ad;
The GPU: Nvidia Kepler K20x;

Thanks,
Cong

**Comment by peastman** [comment]
That's a very old revision, and it doesn't correspond to any release.  Try upgrading to 7.3.

**Comment by frank-stonybrook** [comment]
I tried with the latest released of OpenMM. The compilation seems fine. But when the minimizer tried to switch to CPU platform due to large force. It failed with error message:
**Specified a Platform for a Context which does not support all required kernels.**
However, I am pretty sure there is one CPU associate with each GPU. How does the OpenMM detect whether there is a CPU platform available?
Thanks

**Comment by peastman** [comment]
That isn't what it means.  It's saying that your simulation uses features that aren't supported on the reference platform.  Are you using any nonstandard plugins?

**Comment by frank-stonybrook** [comment]
Yes, I am using the plugin based MELD which introduce  some sort of nonstandard distance restraints to the system.

**Comment by peastman** [comment]
That's the reason.  The plugin only includes an implementation for the CUDA platform, not the reference platform.

**Comment by frank-stonybrook** [comment]
Thanks! 
One last question, I am still confusing why it must be reference platform instead of cpu one. Since I am able to run simulation without meld restraints, I assume the problem comes from minimizing those restraints. So I take a look at the code in 
https://github.com/pandegroup/openmm/blob/4d7ab095ab4e76d9eeeaf82129156e99c5fb5648/openmmapi/src/LocalEnergyMinimizer.cpp#L60-L75

Since cpu platform is first requested, should be the absence of cpu platform inside MELD plugin causes this problem? What does this reference platform used for here?

**Comment by peastman** [comment]
The CPU platform can use kernels written for the Reference platform.  So if the plugin provided an implementation for Reference, it would work on both platforms.

**Comment by jchodera** [comment]
@jlmaccal : Can we help you update the MELD plugin to fix this issue?

**Comment by peastman** [comment]
Be aware that any time the minimizer falls back to the reference/CPU platform, it's because the forces are too large to represent on the CUDA platform.  That means that in 7.2, minimization will probably fail.

Try first doing a minimization *without* the MELD force.  That will hopefully take care of whatever clashes are producing the huge forces.  Then use those coordinates as a starting point for minimizing with MELD.  That should work as long as it isn't the MELD force itself that's producing the huge forces.

But really MELD needs to add a reference implementation.

**Comment by frank-stonybrook** [comment]
Thanks for your advice!
