### ISSUE TITLE
Bugs in the CustomIntegrator implementation for CUDA

### ISSUE THREAD

**Issue by craabreu** [pandegroup/openmm#2249]
There are bugs in the `CustomIntegrator` implementation for the CUDA platform. Some expressions cannot be compiled due to missing definitions of some functions and operators. The CUDA compiler throws error messages like:

> error: no operator "+" matches these operands
>            operand types are: float + double3

My guess is that these bugs emerged with the recent implementation of vector operations. I'm using version 7.3.0, installed from omnia/label/cuda100. I could reproduce some of these errors with the piece of code below. Platforms CPU and OpenCL seem to work properly.

```
from openmmtools import testsystems
from simtk import openmm
from simtk import unit

waterbox = testsystems.FlexibleWaterBox()
platform = openmm.Platform.getPlatformByName('CUDA')
properties = dict(Precision='mixed') if platform.getName() == 'CUDA' else dict()

integrator = openmm.CustomIntegrator(1*unit.femtoseconds)
integrator.addComputePerDof('v', 'v+0.5*dt*f/m')
integrator.addComputePerDof('v', 'max(-vlim,min(v,vlim)); vlim=1000')
integrator.addComputePerDof('x', 'x+dt*(v+1)-dt')
integrator.addComputePerDof('v', 'v+0.5*dt*f/m')

simulation = openmm.app.Simulation(waterbox.topology, waterbox.system, integrator, platform, properties)
simulation.context.setPositions(waterbox.positions)
simulation.context.setVelocitiesToTemperature(300*unit.kelvin)
simulation.step(1)
```

**Comment by jchodera** [comment]
Thanks for catching this! We must have missed this in travis testing.
@peastman : Would be great to add a test for this (and other functions) that the Jenkins CUDA tests will catch.

**Comment by peastman** [comment]
Thanks for reminding me.  Yes, I can reproduce it.  I'm looking into it now.
