### ISSUE TITLE
OpenCL platform falling back to CPU for minimization

### ISSUE THREAD

**Issue by tristanic** [pandegroup/openmm#2250]
Just updated to OpenMM 7.3 for ChimeraX/ISOLDE, and my built-in demo/test model now runs agonizingly slow on minimization - about 5 minutes where it used to take 1-2 seconds. Each 1,000-round minimization seems to spend most of its time on the Reference platform (one CPU running at 100%), with a brief spike to ~26 cores at the end. Once it _does_ successfully minimize the dynamics runs at the expected speed. The culprit seems to be the MDFF energy term (in this case a `CustomCompoundBondForce` with the energy equation below).

```
'select(step(enabled-0.5), -mdff_global_k_1 * individual_k * map_potential(i,j,k), 0); i = x1 * mdff_rot00_1 + mdff_trn0_1;j = y1 * mdff_rot11_1 + mdff_trn1_1;k = z1 * mdff_rot22_1 + mdff_trn2_1'
```

where `map_potential` is a `Continuous3DFunction`. If I switch to an alternative form which uses a `Discrete3DFunction` instead, the result is the same - but if I leave the map force out entirely then the minimization runs almost instantly. Doesn't seem related to out-of-gamut forces - behaviour is the same whether I start from a model with minor clashes or one that is pre-equilibrated. In the worst case the system energy starts at ~-400,000 kJ/mol and converges to ~-415,000 kJ/mol, which seems quite reasonable.

Not really sure where to go from here in terms of debugging.

**Comment by peastman** [comment]
It only switches to the CPU if it encounters a force that's too big for the OpenCL platform to represent: greater than +/- 2 billion kJ/mol/nm.  That doesn't necessarily mean it's starting from a bad clash, just that it encounters one at some point while doing a line minimization.

Does the CustomCompoundBondForce involve a large number of bonds?  We could potentially create an implementation of it for the CPU platform that would use multiple cores.  That wouldn't completely fix the problem, but it would help.

**Comment by tristanic** [comment]
I'll run a few more experiments to check (e.g. by turning the force 
coupling constant to a very low value or zero) but it looks to me like 
there's some bug here. There's no way the CustomCompoundBondForce should 
be able to generate anything *like* those values - it's tuned so that 
the MDFF forces are substantially weaker than anything coming out of the 
normal forcefield. I also tried setting {"Precision": "double"} when 
setting up the Simulation, and saw the same behaviour (for the same 
construct that started essentially instantly in OpenMM 7.2, where the 
model has already been settled in a previous simulation at zero Kelvin).

I'm afraid that for the application I'm working on the CPU platform 
simply isn't going to be fast enough. As an interactive graphical 
environment where the user is constantly stopping and starting small 
local simulations, the delay involved would be a killer. In my current 
version I already have code to catch when the minimiser is unable to 
converge and take the user to the offending atoms... assuming that 
whatever's currently causing the switch to the CPU platform *isn't* a 
bug, would it be possible to keep the old behaviour available under an 
optional switch?

**Comment by peastman** [comment]
Here's the relevant code if you want to debug what's going on:

https://github.com/pandegroup/openmm/blob/master/openmmapi/src/LocalEnergyMinimizer.cpp#L117-L122

**Comment by tristanic** [comment]
Thanks - will have a look tomorrow. Will also do a double-check on my own code to see if e.g. any uninitialised values are creeping in to the TabulatedFunction data.

 
 
Tristan Croll
Research Fellow
Cambridge Institute for Medical Research
University of Cambridge CB2 0XY

**Comment by tristanic** [comment]
Quick test on my Mac says there's nothing wrong with the values in the 
TabulatedFunction:

tf = f.getTabulatedFunction(0)
vals = tf.getFunctionParameters()[-1]
min(vals)
  -0.3712
max(vals)
  0.5999

Meanwhile mdff_global_k_1 is 4.6 kJ/mol/nm3, the rotnn terms (somewhat 
misnamed, come to thing of it - they also cover scale and skew) have 
values of 13.6 and translation terms are zero. Would be quite surprising 
if any of that managed to combine to give a force value above 2e9 - and 
yet it's specifically this Force that seems to trigger the problem.

**Comment by jchodera** [comment]
Since it's the force that somehow must get large, is it possible that two adjacent tabulated values are very different from each other, but very closely spaced? Or that this might be some sort of edge effect with getting close to the edge of the tabulated functions?

**Comment by tristanic** [comment]
Might be possible, but seems unlikely in this case. This is a 3 Angstrom resolution map sampled at 1.5 x Nyquist - making a nice neat 1 Angstrom-cubed voxel size. Given the overall min and max, the maximum possible step from one grid point to the next is on the order of 1 density unit.

**Comment by tristanic** [comment]
Oh - sorry, yes, I did that check too.

import numpy
vv = numpy.array(vals)
numpy.where(numpy.isnan(vv))

... returns an empty array.

**Comment by jchodera** [comment]
I wonder if checking the case where the grid is all set to a constant value would be informative.

**Comment by tristanic** [comment]
Hmm... it's not being caused by the TabulatedFunction after all. I was 
thrown off by the fact that once it's removed, everything else runs 
multicore - which on my 32-core Xeon was fast enough to trick me. Will 
keep looking into it. If it comes down to to it, I've been meaning to 
move over to using strictly soft-core potentials at some point anyway.

**Comment by tristanic** [comment]
I added a reporter to lbfgs.cpp to report the number of steps it got through before hitting problems, and tweaked `LocalEnergyMinimizer::evaluate()` and `LocalEnergyMinimizer::minimize()` to just return early when it hits an out-of-range force so I could get a look at what sort of geometry is being generated. It returned after 26 steps, and this is what the geometry looked like. The starting model is just 3io0 - a pretty standard smallish protein.

![minimizer_bad_geom](https://user-images.githubusercontent.com/22666848/51972252-e64a2000-2472-11e9-8c5d-eff648963605.jpg)

**Comment by tristanic** [comment]
This seems very reminiscent of a bug I noticed in NAMD's minimiser some years back (see https://www.ks.uiuc.edu/Research/namd/mailing_list/namd-l.2013-2014/2114.html - amazingly the videos are still sitting on Dropbox). Some small local problem causes a runaway positive feedback in the lbfgs, which transiently goes through some crazy geometry before managing to reel things back in and continue.

**Comment by tristanic** [comment]
OK, after some extensive playing around:

- In `LocalEnergyMinimizer::minimize()`, setting:

```
param.gtol = 0.001;
param.max_step = 1;
```

... dramatically reduces the number of instances of the above behaviour, while still generally converging well. Set max_step too much higher and it's constantly falling into bad territory; too much lower and it simply doesn't do much of anything.

- If the starting model doesn't generate any out-of-range forces on the GPU, then the fall-back to CPU seems unnecessary. I replaced the following from `LocalEnergyMinimizer::evaluate()`:
```
        for (int i = 0; i < 3*numParticles; i++) {
            if (!(fabs(g[i]) < 2e9)) {
                energy = computeForcesAndEnergy(data->getCpuContext(), positions, g);
                break;
            }
        }
```
with just a log to std::cerr:
```
        for (int i = 0; i < 3*numParticles; i++) {
            if (!(fabs(g[i]) < 2e9)) {
                std::cerr << "Excessive force of " << fabs(g[i]) << " on particle " << i/3 << std::endl;
            }
        }
```
... and minimisation runs fine despite hitting the occasional out-of-range value (converging to within ~1000 kJ/mol of the minimised starting model about 9 times out of 10 after perturbing the coordinates by up to 0.4 Angstroms along each axis according to 
`m.atoms.coords += numpy.random.rand(*m.atoms.coords.shape)*0.8-0.4`
Admittedly this is with the softcore L-J potential still applied, but I'll try removing that and report back.

- The behaviour of the minimiser tolerance parameter is a little surprising. If I set it to a low value (say, 1e-5 * natoms), minimization will often do not much of anything (converging at a high energy and not reducing even after repeated calls to `minimize()`). Changing it to a substantially higher value (1e-3 - 1 * natoms) brings the energy down much further (and tends to keep gradually reducing it even after a few dozen calls to `minimize(tol, 1000)` despite each individual run converging after a few dozen iterations). 

My suggestion would be to do a single check for large forces on the starting coordinates, and only fall back to CPU in that case. It would be particularly great if there was the option to throw an error instead - in many cases it's a bad idea to blindly let the minimiser deal with a bad clash, and in my case I really want to avoid triggering the CPU fallback unless absolutely necessary.

**Comment by tristanic** [comment]
Oh - and the incidence of these weird jumps into bad geometry doesn't appear directly related to the local gradient strength. Watching a loop repeatedly running `minimize(tol, 1000)` and updating coordinates, I noticed a few times after giving the atoms a random kick that it would go through a few full minimisation runs (going from ~+300 MJ/mol to -400 MJ/mol) and get to the point where further rounds were only reducing energy by ~1 MJ/mol before suddenly jumping.

**Comment by tristanic** [comment]
OK, with full standard L-J potentials reinstated, the following is a brief summary of what I get from a few repeated rounds of kicking the model by 4A and minimising.

Energies starting from the original coordinates:
Initial: -402611
Final: -412917

Repeated kicks:
Initial: 139900
Final: -412934

Initial: 158514
Final: -412936

Initial: 132124
Final: -412968

Initial: 142633
Final: -412978

Initial: 149690
Final: -412994

... and here's a full log from my reporters following one kick (where 'Initial energy' and 'Final energy' are reported directly before and after one call to `minimize(tol, 1000)`:

> Initial energy: 145253 kJ/mol
> Final energy: 120968 kJ/mol
> Finished minimization round
> Initial energy: 120968 kJ/mol
> Final energy: 120968 kJ/mol
> Finished minimization round
> Initial energy: 120968 kJ/mol
> Excessive force of 2.14748e+09 on particle 791
> Excessive force of 2.14748e+09 on particle 1301
> Excessive force of 2.14748e+09 on particle 1301
> Excessive force of 2.14748e+09 on particle 1301
> Excessive force of 2.14747e+09 on particle 1327
> Excessive force of 2.14746e+09 on particle 1327
> Excessive force of 2.14747e+09 on particle 1327
> Excessive force of 2.14745e+09 on particle 1905
> Excessive force of 2.14748e+09 on particle 791
> Excessive force of 2.14748e+09 on particle 1301
> Excessive force of 2.14748e+09 on particle 1301
> Excessive force of 2.14748e+09 on particle 1301
> Excessive force of 2.14747e+09 on particle 1327
> Excessive force of 2.14746e+09 on particle 1327
> Excessive force of 2.14747e+09 on particle 1327
> Excessive force of 2.14745e+09 on particle 1905
> Final energy: -412993 kJ/mol
> Initial energy: -412993 kJ/mol
> Excessive force of 2.14748e+09 on particle 791
> Excessive force of 2.14748e+09 on particle 1301
> Excessive force of 2.14748e+09 on particle 1301
> Excessive force of 2.14748e+09 on particle 1301
> Excessive force of 2.14747e+09 on particle 1327
> Excessive force of 2.14746e+09 on particle 1327
> Excessive force of 2.14747e+09 on particle 1327
> Excessive force of 2.14745e+09 on particle 1905
> Excessive force of 2.14748e+09 on particle 791
> Excessive force of 2.14748e+09 on particle 1301
> Excessive force of 2.14748e+09 on particle 1301
> Excessive force of 2.14748e+09 on particle 1301
> Excessive force of 2.14747e+09 on particle 1327
> Excessive force of 2.14746e+09 on particle 1327
> Excessive force of 2.14747e+09 on particle 1327
> Excessive force of 2.14745e+09 on particle 1905
> Final energy: -412994 kJ/mol
> Finished minimization round
>

**Comment by tristanic** [comment]
There's a related issue in this model that further illustrates that the minimiser struggles somewhat with large gradients. After adding hydrogens to 3io0, the HB atoms of Thr248 and Thr266 end up clashing quite badly:
![thr_pair_start](https://user-images.githubusercontent.com/22666848/51997959-b2d9b680-24af-11e9-815f-98fab7969210.jpg)

I noticed some time back that if I don't set a very low value for the minimiser tolerance (on the order of 1e-7*natoms) then this would lead to the chiral centres of both sidechains flipping handedness:

![thr_pair_default_l-j](https://user-images.githubusercontent.com/22666848/51998149-0946f500-24b0-11e9-8530-91bc57e04bd9.jpg)

(the weird geometry is because I apply 1000 kJ/mol/rad**2 improper chiral restraints to all chiral centres). I actually thought it was happening at the start of dynamics due to insufficient minimisation, but now it looks like (as per my previous posts) the very low tolerance was preventing the minimiser from doing _anything_! In any case, after my adjustments this handedness flip happens during minimisation every time, without hitting the "Excessive force" trigger. But if I switch to a soft-core L-J potential:

```
class NonbondedSoftcoreForce(CustomNonbondedForce):
    '''
    Defines a soft-core Lennard-Jones potential to replace the default version,
    to reduce the generation of out-of-gamut forces during energy minimisation.
    '''
    def __init__(self, nb_lambda=0.9995):
        energy_function = ('nb_lambda*4*epsilon*x*(x-1.0); '
            'x = (sigma/reff_sterics)^6;'
            'reff_sterics = sigma*(0.5*(1.0-nb_lambda) + (r/sigma)^6)^(1/6);'
            'sigma = 0.5*(sigma1+sigma2);'
            'epsilon = sqrt(epsilon1*epsilon2);'
            )
        super().__init__(energy_function)
        self.addGlobalParameter('nb_lambda', nb_lambda)
        self.addPerParticleParameter('sigma')
        self.addPerParticleParameter('epsilon')
```
... then it minimises stably:
![thr_pair_soft_core_l-j](https://user-images.githubusercontent.com/22666848/51999232-2e3c6780-24b2-11e9-88da-24c36fcdf1f2.jpg)

**Comment by tristanic** [comment]
Make that lambda=0.99. I still see the chiral flip under some conditions for higher values.

**Comment by peastman** [comment]
I think what you're discovering is that minimization is chaotic and unpredictable.  Sometimes it just does strange things.  And any arbitrary change, such as to a tolerance, can cause the strange behavior to appear or disappear.  That doesn't mean one value of the tolerance is better than the other.  You're just perturbing the chaotic process, which causes it to go off in a different direction.

```
Excessive force of 2.14745e+09 on particle 1905
Final energy: -412993 kJ/mol
Initial energy: -412993 kJ/mol
```

That's a perfect demonstration of why the fallback to CPU is needed.  The force is maxing out, hitting the highest value we can represent in fixed point.  This causes LBFGS to get very confused.  It expects the force to be the gradient of the energy, but in this case it isn't, which invalidates all the math the algorithm is based on.  As a result, it thrashes for a while, then gives up and just returns without having minimized anything.

**Comment by tristanic** [comment]
The lines you've quoted constitute the end of one 1000-step minimisation and the start of the next. The relevant section is:

> Initial energy: 120968 kJ/mol
> Excessive force of 2.14748e+09 on particle 791
> Excessive force of 2.14748e+09 on particle 1301
> Excessive force of 2.14748e+09 on particle 1301
> Excessive force of 2.14748e+09 on particle 1301
> Excessive force of 2.14747e+09 on particle 1327
> Excessive force of 2.14746e+09 on particle 1327
> Excessive force of 2.14747e+09 on particle 1327
> Excessive force of 2.14745e+09 on particle 1905
> Excessive force of 2.14748e+09 on particle 791
> Excessive force of 2.14748e+09 on particle 1301
> Excessive force of 2.14748e+09 on particle 1301
> Excessive force of 2.14748e+09 on particle 1301
> Excessive force of 2.14747e+09 on particle 1327
> Excessive force of 2.14746e+09 on particle 1327
> Excessive force of 2.14747e+09 on particle 1327
> Excessive force of 2.14745e+09 on particle 1905
> Final energy: -412993 kJ/mol

... so it managed to get from 120968 down to -412993 (essentially full convergence for this model) despite hitting bad values 16 times in between. If I understand correctly, the reason it works out is that the bad values arise from individual steps along a 20-step line search - and regardless of their absolute value are high enough that they're bound to be discarded anyway in favour of the lowest energy value along the line. (Again, if I understand correctly) the only way it's going to get stuck entirely is if _every_ value along the line is out of range - but if the algorithm is working correctly that should only ever happen if the model *starts* with an atom experiencing an out-of-range force.

**Comment by tristanic** [comment]
It turns out that almost all the instability in minimisation (and the flip in chiral handedness pictured above) comes down to this line: https://github.com/pandegroup/openmm/blob/master/openmmapi/src/LocalEnergyMinimizer.cpp#L155

`    double k = tolerance/workingConstraintTol;`

As written, the harmonic constant applied in place of constraints for minimisation purposes gets **weaker** as the user-input tolerance gets stronger - which explains why minimisation was doing nothing when I set tight tolerance values. If tolerance is 1e-8, then the starting k is a practically-non-existent 1e-4 kJ/mol/nm2, so the code would just be hitting https://github.com/pandegroup/openmm/blob/master/openmmapi/src/LocalEnergyMinimizer.cpp#L216-L229 every time.  Was the intention to make it:

`    double k = 1/(tolerance*workingConstraintTol;`

? I'm not convinced that it makes sense to use the `tolerance` parameter at all for determining `k`. From some trial-and-error experimentation with my test case, the starting value of `k` needs to be at least 1e6 to reliably avoid flipping the chirality of both sidechains.  If I instead change the line to: 

`    double k = 100/workingConstraintTol;`

then everything immediately becomes **much** more reliable. If I further set:

```
param.m = 20;
param.ftol = 1e-6;
param.max_step = 1;
```

... then the minimiser almost never steps out of line for my test case. It minimises stably every time from the starting coordinates without introducing the chiral flip, and recovered from a random 0.4 Angstrom kick to within a few hundred kJ/mol 30 times out of 30 times. It reported hitting out-of-range forces in roughly one case out of 10, but typically only in 1-5 energy evaluations out of a 1000-round lbfgs cycle - and it's recovered from them every time.

**Comment by peastman** [comment]
I didn't realize you were using constraints.  That explains a lot.  Constrained optimization is *much* harder than unconstrained optimization.  If it's possible for you to work without constraints, you'll find the optimizer works a lot better.

LBFGS as an algorithm doesn't support constraints.  There are different algorithms specifically designed for constrained optimization, but they tend to be slower and less robust.  So here's how LocalEnergyMinimizer handles constraints.  It replaces them with harmonic restraints, then runs the optimization.  It then checks the result to see if all constraints are satisfied to within the requested tolerance.  If they aren't, it increases the strength of the restraints and tries again.  This keeps repeating until either all constraints are satisfied, or optimization fails and it gives up.

That's why the strength of the restraint force has to depend on the tolerance.  It needs to be strong enough to have a plausible chance of satisfying the constraints.  If you make it much weaker, as you did above, then minimization will get a lot easier, but the end result won't satisfy your constraints.

**Comment by tristanic** [comment]
... and as a backup check, with those settings the 40377-atom 6h3i (in a Continuous3DFunction-based MDFF simulation against EMD 0133, in implicit solvent) reproducibly minimises from a random 0.4A kick (reducing from 2e6 to -5e6 kJ/mol) in about 15 seconds on the OpenCL platform on my machine (Xeon E5-2687W with Nvidia Titan Xp), despite the occasional out-of-range force.

**Comment by tristanic** [comment]
Yes, from reading the code I understand that the constraints are being replaced by restraints for the purposes of minimisation (and that it loops through repeated minimisations with progressively stronger spring constants until either the constraints are satisfied or it gives up). My point is that the current relationship between tolerance and the restraint strength seems inverted compared to what it should be (currently tighter tolerance --> weaker restraints).

**Comment by jchodera** [comment]
>  From some trial-and-error experimentation with my test case, the starting value of k needs to be at least 1e6 to reliably avoid flipping the chirality of both sidechains.

I just want to say we've been bitten by the same problem, and we *really* should find a way to fix this issue to make minimization more robust or we risk having people generate scientifically invalid results.

**Comment by peastman** [comment]
> the current relationship between tolerance and the restraint strength seems inverted compared to what it should be

I see, you're saying the restraints are too weak rather than too strong?

**Comment by tristanic** [comment]
With regard to avoiding constraints entirely, that's something of a challenge. By the nature of the task at hand (building/rebuilding and equilibrating sections of a model into a map) I can't be working in explicit solvent. The environment is built to allow the user to "play" with the model by dragging atoms around, and while I give them a big buffer zone of mobile atoms around the region they're interested in, there's a hard shell of fixed atoms around that. Without constraints on hydrogen bond lengths, I found things would constantly fly apart. With the constraints, the variable-timestep integrator and a final extra safety check for overly-fast atoms every 10 steps (automatically triggering a minimisation) I haven't had a simulation fall apart in months (despite trying **really** hard to break it).

**Comment by tristanic** [comment]
Yes, too weak. I've been playing around all afternoon with `k` coded to `1000/workingConstraintTol` (so it starts at 1e7 kJ/mol/nm), and it's been rock solid.

**Comment by tristanic** [comment]
One other thought I had with regard to making absolutely sure that minimisation can be stable on the GPU: for the core `Force`s most prone to singularities (probably just the L-J and Coulomb forces, in the absence of any truly bizarre geometry), how challenging/costly would it be to redefine them with a `select` to switch between a soft-core formulation for minimisation and the standard form for dynamics? With the `NonbondedSoftcoreForce` above, lambda=0.9995 (if I recall correctly) puts the maximum possible force at 40,000 kJ/mol/nm - way outside the naturally-accessible range and still more than strong enough to provide a strong gradient to the minimiser, but with a minimum essentially unchanged from the default L-J form.
