### ISSUE TITLE
Precision bug in openmm 7.3.0? 

### ISSUE THREAD

**Issue by bas-rustenburg** [pandegroup/openmm#2254]
I ran into some unexpected behavior while performing NCMC protocols. Summarizing my calculations:

I have a ligand with 2 states that have the same energy, but the charge distribution (protonation state) is mirrored. I use a 10,000 step (2fs each) NCMC switching trajectory, where I linearly perturb the charges of the atoms using `force.setParticleParameters` and `force.updateParametersInContext`. With a previous version of openmm (7.2.1) I experienced no issues, but as of 7.3.0 I seem to be accumulating error in my NCMC protocols. I can recover the old behavior when I switch from `mixed` to `double` precision.

![image](https://user-images.githubusercontent.com/3977731/52308068-5de3e780-296a-11e9-9503-16d09b683f28.png)

I'm using the customIntegrator implemented here:https://github.com/choderalab/openmmtools/blob/master/openmmtools/integrators.py#L1868 

Posting this to start the discussion as to what the cause could be. @jchodera mentioned to me a way we may be able to set up a minimal example.

**Comment by jchodera** [comment]
I've attached a minimal example below. In this example, we create a water box and run a Langevin simulation to generate equilibrium samples. Every 1 ps, we shoot a 5000 step nonequilibrium trajectory where the charges for one water molecule are reduced a bit over steps [0,2500] and then restored over [2500,5000]. If everything is behaving correctly, as the protocol gets longer, the cumulative work (sum of potential energy changes for every intermediate charge perturbation) should get closer and closer to zero.

For OpenMM 7.2.2, this works as expected in `mixed` precision:
```
Creating test system...
Extracting reference charges...
Creating Langevin integrator...
Creating context...
Setting DeterministicForces to true
Setting Precision to mixed
Sampling...
iteration        0 /       10 : work    1.242 kT
iteration        1 /       10 : work   -1.372 kT
iteration        2 /       10 : work    0.834 kT
iteration        3 /       10 : work    0.861 kT
iteration        4 /       10 : work   -0.552 kT
iteration        5 /       10 : work    0.440 kT
iteration        6 /       10 : work    1.801 kT
iteration        7 /       10 : work    0.063 kT
iteration        8 /       10 : work    0.721 kT
iteration        9 /       10 : work    0.398 kT
```
For OpenMM 7.3, suddenly we see a huge energy leak in `mixed` precision:
```
[chodera@lilac:chodera]$ python integrator-precision.py
Creating test system...
Extracting reference charges...
Creating Langevin integrator...
Creating context...
Setting DeterministicForces to true
Setting Precision to mixed
Sampling...
iteration        0 /       10 : work  -13.076 kT
iteration        1 /       10 : work  -13.715 kT
iteration        2 /       10 : work  -13.472 kT
iteration        3 /       10 : work  -12.354 kT
iteration        4 /       10 : work  -10.988 kT
iteration        5 /       10 : work  -10.597 kT
iteration        6 /       10 : work  -11.885 kT
iteration        7 /       10 : work  -12.098 kT
iteration        8 /       10 : work  -12.169 kT
iteration        9 /       10 : work  -11.133 kT
```
Here's a comparison of the cumulative work over the trajectory:
![pasted_image_at_2019-02-05__6_11_pm](https://user-images.githubusercontent.com/3656088/52310742-78ba5a00-2972-11e9-8a75-55a8f7eb6bd0.png)

We can switch to `double` precision and see better behavior:
```
Creating test system...
Extracting reference charges...
Creating Langevin integrator...
Creating context...
Setting DeterministicForces to true
Setting Precision to double
Sampling...
iteration        0 /       10 : work    0.759 kT
iteration        1 /       10 : work   -0.234 kT
iteration        2 /       10 : work   -1.185 kT
iteration        3 /       10 : work    2.248 kT
iteration        4 /       10 : work   -1.474 kT
```

We use deterministic PME forces and Both `openmm.LangevinIntegrator` and `openmmtools.integrators.LangevinIntegrator` show the same behavior. 

Here's the script, which also generates the numpy file I plotted above to give the cumulative work as a function of step:
```
#!/bin/env python

from simtk import unit, openmm
from openmmtools import testsystems, integrators
import copy
import time
import numpy as np

precision = 'mixed'

print('Creating test system...')
t = testsystems.WaterBox()
system, positions = t.system, t.positions
atoms_to_discharge = [0,1,2] # discharge one water

print('Extracting reference charges...')
forces = { system.getForce(index).__class__.__name__ : system.getForce(index) for index in range(system.getNumForces()) }
reference_charges = [ forces['NonbondedForce'].getParticleParameters(index)[0] for index in range(system.getNumParticles()) ]

print('Creating Langevin integrator...')
temperature = 300 * unit.kelvin
collision_rate = 1.0 / unit.picoseconds
timestep = 2.0 * unit.femtoseconds
kB = unit.AVOGADRO_CONSTANT_NA * unit.BOLTZMANN_CONSTANT_kB 
kT = kB * temperature
integrator = integrators.LangevinIntegrator(temperature, collision_rate, timestep)

print('Creating context...')
platform_name = 'CUDA'
platform = openmm.Platform.getPlatformByName(platform_name)
properties = { 'DeterministicForces' : 'true', 'Precision': precision }
for property_name, value in properties.items():
    if property_name in platform.getPropertyNames():
        print('Setting {} to {}'.format(property_name, value))
        platform.setPropertyDefaultValue(property_name, value)
context = openmm.Context(system, integrator, platform)
context.setPositions(positions)

# Store initial equilibrium box vectors and positions
state = context.getState(getPositions=True)

print('Sampling...')
niterations = 10
nsteps_per_iteration = 500
nsteps_per_nonequilibrium_switch = 5000
work = np.zeros([niterations, nsteps_per_nonequilibrium_switch], np.float64)
for iteration in range(niterations):
    # Generate a new equilibrium sample
    context.setPeriodicBoxVectors(*state.getPeriodicBoxVectors())
    context.setPositions(state.getPositions())
    integrator.step(nsteps_per_iteration)

    # Store final equilibrium sample
    state = context.getState(getPositions=True)

    # Perform a nonequilibrium switching step
    integrator.step(1)
    cumulative_work = 0.0
    for step in range(nsteps_per_nonequilibrium_switch):
        # Take a step
        integrator.step(1)

        # Accumulate protocol work
        initial_potential = context.getState(getEnergy=True).getPotentialEnergy() / kT
        fraction = float(step+1) / float(nsteps_per_nonequilibrium_switch)
        alchemical_lambda = 1.0 - fraction*(1.0-fraction)
        for index in atoms_to_discharge:
            charge, sigma, epsilon = forces['NonbondedForce'].getParticleParameters(index)
            forces['NonbondedForce'].setParticleParameters(index, alchemical_lambda * reference_charges[index], sigma, epsilon)
        forces['NonbondedForce'].updateParametersInContext(context)
        final_potential = context.getState(getEnergy=True).getPotentialEnergy() / kT
        cumulative_work += final_potential - initial_potential
        work[iteration, step] = cumulative_work

    print('iteration %8d / %8d : work %8.3f kT' % (iteration, niterations, cumulative_work))
    np.save('work-%s.npy' % precision, work[0:iteration+1,:])
```

**Comment by jchodera** [comment]
Here's a comparison of `single`, `mixed`, and `double` precision with OpenMM 7.2.2. There's a slight dependence on precision, but `mixed` and `double` are serviceable, and even `single` isn't too bad:
![image](https://user-images.githubusercontent.com/3656088/52311687-d2705380-2975-11e9-84ce-0f51e42ba3fc.png)
But with OpenMM 7.3, suddenly, there is a huge precision dependence, and both `single`, and `mixed` are unusable:
![image](https://user-images.githubusercontent.com/3656088/52311696-dc925200-2975-11e9-9dd6-3711aaf02b2a.png)
I'm struggling to think of what might be causing this.

**Comment by peastman** [comment]
Strange.  I'm not thinking of any changes that would have caused that.  How long does it take to run the test?  Would it be reasonable to try bisecting to identify when the problem appeared?

**Comment by jchodera** [comment]
It should take only about a minute to produce a few samples. The difference between them (< -10 kT vs > -3 kT) would make it very quick to discriminate behavior based on just 2-3 samples.

**Comment by jchodera** [comment]
Just so we don't duplicate effort: Did you want me to give "git bisect run" a go on this test?

**Comment by peastman** [comment]
Go for it!  That would be great.

**Comment by jchodera** [comment]
This is odd, though, since the waterbox example above doesn't even use the new offset feature---it just uses `NonbondedForce.updateParametersInContext()`.

**Comment by jchodera** [comment]
For reference, here's what I did to use `git bisect run` to identify this commit:
* I installed a clean version of [miniconda](https://docs.conda.io/en/latest/miniconda.html) in a directory on fast local scratch space. Since conda-build creates and deletes a lot of files over and over, this can speed things up a great deal over using network-mounted storage.
* I checked out a fresh copy of OpenMM from GitHub with `git clone https://github.com/pandegroup/openmm.git`
* I created a `conda-recipe` directory within the `openmm` source directory that contained a minimal `meta.yaml` and `build.sh` to build OpenMM with dependencies.
* I adapted the test script above to exit with 0 on success and 1 on failure, and named it `run_test.py` within `conda-recipe` so that it would run after the build and cause `conda build` relay the results of success or failure of this test.
* Initiated `git bisect run` via
```bash
git bisect start
git checkout 7.3.0
git bisect bad
git checkout 7.2.1
git bisect good
git bisect run conda build --numpy 1.14 conda-recipe
```
Each build took approximately 10 minutes, followed by another 10 minutes of installation and testing. Bisection took approximately 7 cycles to identify the faulty commit.

Here is an archive of my `conda-recipe` directory:
[conda-recipe.zip](https://github.com/pandegroup/openmm/files/2836895/conda-recipe.zip)

**Comment by jchodera** [comment]
Some other clues:
* In `OpenCL`, the test produces NaNs during the nonequilibrium shooting part:
```
[chodera@lilac:chodera]$ python integrator-precision.py
Creating test system...
Extracting reference charges...
Creating Langevin integrator...
Creating context...
Using platform OpenCL
Setting Precision to mixed
Sampling...
Traceback (most recent call last):
  File "integrator-precision.py", line 62, in <module>
    integrator.step(1)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 18984, in step
    return _openmm.CustomIntegrator_step(self, steps)
Exception: Particle coordinate is nan
```
* The `CPU` platform seems fine:
```
[chodera@lilac:chodera]$ python integrator-precision.py
Creating test system...
Extracting reference charges...
Creating Langevin integrator...
Creating context...
Using platform CPU
Setting DeterministicForces to true
Sampling...
iteration        0 /       10 : work    1.548 kT
iteration        1 /       10 : work    0.064 kT
```

**Comment by jchodera** [comment]
Also, it looks like CUDA `mixed` with `CutoffPeriodic` is fine:
```
[chodera@lilac:chodera]$ python integrator-precision.py
Creating test system...
Extracting reference charges...
Setting to CutoffPeriodic...
Creating Langevin integrator...
Creating context...
Using platform CUDA
Setting DeterministicForces to true
Setting Precision to mixed
Sampling...
iteration        0 /       10 : work    0.406 kT
iteration        1 /       10 : work    1.335 kT
iteration        2 /       10 : work   -0.317 kT
iteration        3 /       10 : work   -0.297 kT
iteration        4 /       10 : work   -0.377 kT
iteration        5 /       10 : work    0.946 kT
iteration        6 /       10 : work    2.479 kT
iteration        7 /       10 : work    0.395 kT
iteration        8 /       10 : work    0.709 kT
iteration        9 /       10 : work    0.539 kT
```
as is `NoCutoff`:
```
[chodera@lilac:chodera]$ python integrator-precision.py
Creating test system...
Extracting reference charges...
Setting to NoCutoff...
Creating Langevin integrator...
Creating context...
Using platform CUDA
Setting DeterministicForces to true
Setting Precision to mixed
Sampling...
iteration        0 /       10 : work    2.547 kT
iteration        1 /       10 : work    1.801 kT
iteration        2 /       10 : work    0.819 kT
iteration        3 /       10 : work   -0.543 kT
iteration        4 /       10 : work    0.225 kT
iteration        5 /       10 : work    0.365 kT
iteration        6 /       10 : work    2.450 kT
iteration        7 /       10 : work    1.291 kT
iteration        8 /       10 : work    1.399 kT
iteration        9 /       10 : work    1.476 kT
```
though `Ewald` does not look good:
```
[chodera@lilac:chodera]$ python integrator-precision.py
Creating test system...
Extracting reference charges...
Setting to Ewald...
Creating Langevin integrator...
Creating context...
Using platform CUDA
Setting DeterministicForces to true
Setting Precision to mixed
Sampling...
iteration        0 /       10 : work -108077.565 kT
iteration        1 /       10 : work  -13.302 kT
iteration        2 /       10 : work  -11.006 kT
iteration        3 /       10 : work  -12.131 kT
iteration        4 /       10 : work  -12.563 kT
iteration        5 /       10 : work  -12.880 kT
iteration        6 /       10 : work  -13.104 kT
iteration        7 /       10 : work  -11.379 kT
iteration        8 /       10 : work  -11.941 kT
iteration        9 /       10 : work  -12.032 kT
```

**Comment by jchodera** [comment]
@peastman: Let us know if there's anything else we can do on our end to chase down what's going on here. Hopefully, knowing the exact commit that introduced the issue helps.

**Comment by peastman** [comment]
I'm working on it now.  Unfortunately, something is preventing me from logging into any of my workstations remotely, so I'm having to do it on my laptop, which is slow.  I can reproduce the nan with OpenCL, but it's very unpredictable.  Sometimes it happens immediately, sometimes not at all.  I'll let you know when I find out more.

**Comment by jchodera** [comment]
The stochastic nature of the test may have caused problems with `git bisect`. I reran it and came up with [a different commit](https://github.com/pandegroup/openmm/commit/7c6f0b4b2e3a692764d53577c4a7468422ebc012) still related to offsets:
```
7c6f0b4b2e3a692764d53577c4a7468422ebc012 is the first bad commit
commit 7c6f0b4b2e3a692764d53577c4a7468422ebc012
Author: Peter Eastman <peter.eastman@gmail.com>
Date:   Tue Jun 26 15:40:25 2018 -0700

    CUDA implementation of parameter offsets for NonbondedForce
```
I'll tighten the criteria and rerun to make sure this is it.

**Comment by peastman** [comment]
One thing I've noticed while investigating this is that the starting configuration includes a bunch of very large forces, over 50,000 kJ/mol/nm.  Could that be part of the problem?

**Comment by peastman** [comment]
Immediately after the call to `setPositions()` at the start of the loop, I added the following code:

```python
    forces = context.getState(getForces=True).getForces()._value
    for i,f in enumerate(forces):
        if unit.norm(f) > 5e4:
            print(i,f)
```

And here's what it prints.

```
21 (65459.46875, -113094.5078125, -92391.71875)
120 (-7089.13818359375, -58884.3515625, 13595.02734375)
276 (-65836.6015625, 114668.125, 95709.7109375)
789 (86688.078125, -135241.25, 36723.49609375)
816 (4627.54150390625, 59274.09765625, -13963.8525390625)
894 (93141.1015625, -96975.484375, 63592.34375)
1260 (-97027.890625, 98232.1640625, -64133.203125)
1446 (-86983.2578125, 131900.1875, -35841.3125)
```

Those values are the same for both CPU and OpenCL, so I don't think they're the result of a platform specific bug.

**Comment by jchodera** [comment]
> One thing I've noticed while investigating this is that the starting configuration includes a bunch of very large forces, over 50,000 kJ/mol/nm. Could that be part of the problem?

Hm. I'm not sure how that would that lead to radically different behavior on OpenMM 7.2.2 and 7.3.0, or how after multiple iterations of equilibrium Langevin dynamics, (which would reduce those forces enormously), that would still be an issue.

**Comment by jchodera** [comment]
To reduce the initial force magnitudes, I've inserted this after the first `getPositions()`:
```python
# Minimize and equilibrate                                                                                                                                                                                                                                    
print('Minimizing...')
openmm.LocalEnergyMinimizer.minimize(context)
print('Equilibrating...')
integrator.step(5000)
current_forces = context.getState(getForces=True).getForces()._value
for i,f in enumerate(current_forces):
    if unit.norm(f) > 5e4:
        print(i,f)
```
which prints (on OpenMM 7.3.0):
```
[chodera@lilac:chodera]$ python integrator-precision.py
Creating test system...
Extracting reference charges...
Creating Langevin integrator...
Creating context...
Using platform CUDA
Setting DeterministicForces to true
Setting Precision to mixed
Minimizing...
Equilibrating...
Sampling...
iteration        0 /       10 : work  -11.391 kT
iteration        1 /       10 : work  -12.560 kT
iteration        2 /       10 : work  -13.102 kT
iteration        3 /       10 : work  -13.318 kT
iteration        4 /       10 : work  -12.353 kT
iteration        5 /       10 : work  -11.288 kT
iteration        6 /       10 : work  -14.271 kT
iteration        7 /       10 : work  -10.364 kT
iteration        8 /       10 : work  -11.998 kT
iteration        9 /       10 : work  -12.768 kT
```
indicating no forces are really large after minimization and a bit of equilibration, but the energy leak still occurs.

**Comment by peastman** [comment]
The large forces were the cause of the nans, which is what I've been focusing on tracking down.  But if minimizing doesn't affect the test results, then that was probably a red herring.

**Comment by jchodera** [comment]
Sorry about that---I thought the easily reproducible precision-dependent energy loss where behavior has significantly changed after introducing the offset feature (even when it is not in use) would be the more critical thing right now.

**Comment by jchodera** [comment]
Also, if there's more debugging we can do to help you track things down, let us know! Right now, it looks like _something_ in the [implementation of offsets](https://github.com/pandegroup/openmm/commit/7c6f0b4b2e3a692764d53577c4a7468422ebc012) introduced some sort of significant issue in PME and Ewald that at least affects `updateParametersInContext()`, but may in fact affect significantly more than this.

**Comment by peastman** [comment]
I found it!  That was a *really* subtle issue.  I'll get a PR with the fix in shortly.

It had to do with the calculation of the Ewald self energy.  In the past, that was always calculated on the CPU, since it's just a constant that doesn't change unless the particle charges change.  But parameter offsets mean that the charges could change every step, and in that case it's much more efficient to calculate it on the GPU.  So we ended up with a split system.  Whenever the parameters change, either because you're using offsets or because you just called `updateParametersInContext()`, it uses a value calculated on the GPU.  Otherwise, it uses a value calculated on the CPU.

Of course, those values should be the same.  Except that the CPU calculation is done in double precision and the GPU calculation is in single precision.  Actually, it's even more subtle than that.  If you're using mixed precision, the GPU calculation gets done *mostly* in double.  But there's a constant prefactor that it gets multiplied by, and it was representing that prefactor as a single precision value.  So depending on whether or not you just called `updateParametersInContext()` there's a tiny difference in the value of the Ewald self energy.

Now look at your script.  Each time through the loop it computes energy twice.  And because of the details of your code, it happened to be getting the CPU value the first time and the GPU value the second time.  So those would have a tiny but systematic difference between them.  Then you'd add up 5000 of those differences, leading to a significant error in the final value.

**Comment by jchodera** [comment]
Oh, wow! Great detective work!

I'll think through the ramifications of this, but essentially, calculations that made use of updateParametersInContext() or offsets to update charges when using PME or Ewald on the GPU are suspect, yes?

**Comment by peastman** [comment]
If they used offsets there's no problem.  In that case it was consistently using the value computed on the GPU.  Also remember this didn't affect the forces, just the energy.  And if the next thing you did after `updateParametersInContext()` was to take a step, that was fine too.  But if the next thing you did was to query the energy, you would get a value for the self energy that was very slightly different (at about the eighth decimal place).

**Comment by jchodera** [comment]
Thanks for the explanation!
