### ISSUE TITLE
Building conda-installable openmm packages for ppc64le

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#2258]
@peastman: I'm working on building a conda-installable openmm package (currently `master`, since the PPC support didn't make it into 7.3.0) for [ORNL Summit](https://www.olcf.ornl.gov/for-users/system-user-guides/summit/summit-user-guide).

Luckily, [conda-forge is in the process of building packages for ppc64le](https://github.com/regro/cf-scripts/pull/444), though I had to manually build and push a few packages that had not yet been re-rendered. The recipes I used are [here](https://github.com/inspiremd/conda-recipes-summit).

I've managed to assemble a [modified recipe to build openmm](https://github.com/inspiremd/conda-recipes-summit/tree/master/openmm) that is not pretty, but appears to build a complete package. While the Python components can be imported, `import simtk.openmm` fails with this error:
```
>>> import simtk.openmm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs/alpine/scratch/jchodera1/bip178/miniconda/lib/python3.6/site-packages/simtk/openmm/__init__.py", line 19, in <module>
    from simtk.openmm.openmm import *
  File "/gpfs/alpine/scratch/jchodera1/bip178/miniconda/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 28, in <module>
    _openmm = swig_import_helper()
  File "/gpfs/alpine/scratch/jchodera1/bip178/miniconda/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 24, in swig_import_helper
    _mod = imp.load_module('_openmm', fp, pathname, description)
  File "/gpfs/alpine/scratch/jchodera1/bip178/miniconda/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/gpfs/alpine/scratch/jchodera1/bip178/miniconda/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /gpfs/alpine/scratch/jchodera1/bip178/miniconda/lib/python3.6/site-packages/simtk/openmm/_openmm.cpython-36m-powerpc64le-linux-gnu.so: undefined symbol: _ZN6OpenMM23CustomCentroidBondForce20addTabulatedFunctionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_17TabulatedFunctionE
```
I'm looking for help on how I debug this.

The package has been [pushed to `omnia-dev`](https://anaconda.org/omnia-dev/openmm/files) if you'd like to inspect its contents:
https://anaconda.org/omnia-dev/openmm/7.4.0/download/linux-ppc64le/openmm-7.4.0-py36_cuda92_rc_1.tar.bz2

**Comment by jchodera** [comment]
Looks like `libOpenMM.so` has a different version of that symbol that omits the internal `_cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_`:
```
bash-4.2$ nm /gpfs/alpine/scratch/jchodera1/bip178/miniconda/lib/libOpenMM.so | grep _ZN6OpenMM23CustomCentroidBondForce20addTabulatedFunction       
00000000000cacf0 t 000000cc.plt_call._ZN6OpenMM23CustomCentroidBondForce20addTabulatedFunctionERKSsPNS_17TabulatedFunctionE
00000000000f5090 T _ZN6OpenMM23CustomCentroidBondForce20addTabulatedFunctionERKSsPNS_17TabulatedFunctionE
```
Could this be due to somehow using an incompatible set of compilers/linkers in the build?

I've captured the build output here:
[build.txt](https://github.com/pandegroup/openmm/files/2849615/build.txt)

**Comment by peastman** [comment]
That looks like a problem with the library and Python module being compiled for different ABIs.  I'm not familiar with PPC ABIs, so I don't know what specific options might be responsible.

**Comment by jchodera** [comment]
Thanks! Looks like I just have to find a way to force compilation of the C++ code, the cython code, and the Python swig wrapper to all use the same compiler. Any hints?

Also, is there a way to disable cython compilation? That was a pain to get working, and I fear we'll run into this issue a lot.

**Comment by peastman** [comment]
> Any hints?

Not really.  What compiler(s) are you using?  And what OS?

> Also, is there a way to disable cython compilation?

Since `ForceField` won't work without it, nope.

**Comment by jchodera** [comment]
> Not really. What compiler(s) are you using? And what OS?

Can you log into summit yet?

There is extensive documentation in the [user guide](https://www.olcf.ornl.gov/for-users/system-user-guides/summit/summit-user-guide/) I linked to above, but here's a quick summary:
```
[jchodera1@login2.summit conda-recipes-summit]$ uname -r
4.14.0-49.18.1.el7a.ppc64le
[jchodera1@login2.summit conda-recipes-summit]$ lsb_release -a
LSB Version:	:core-4.1-noarch:core-4.1-ppc64le
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.5 (Maipo)
Release:	7.5
Codename:	Maipo
```
Instead of the [module-based local compilers](https://www.olcf.ornl.gov/for-users/system-user-guides/summit/summit-user-guide/#compiling), I'm trying to build `conda` packages with the new [Anaconda 5 compiler system](https://www.anaconda.com/utilizing-the-new-compilers-in-anaconda-distribution-5/), in which we specify templates [in the recipe](https://github.com/inspiremd/conda-recipes-summit/blob/master/openmm/meta.yaml#L31-L32) that are then translated into architecture-appropriate compilers. This ends up setting `$CC` and `$CXX` to compilers whose `--version` output is:
```
owerpc64le-conda_cos7-linux-gnu-cc (crosstool-NG 1.23.0.444-4ea7) 8.2.0 Copyright (C) 2018 Free Software Foundation, Inc. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
powerpc64le-conda_cos7-linux-gnu-c++ (crosstool-NG 1.23.0.444-4ea7) 8.2.0 Copyright (C) 2018 Free Software Foundation, Inc. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by peastman** [comment]
> Can you log into summit yet?

Not yet.  Hopefully in a few days.

**Comment by jchodera** [comment]
This is odd: When forcing CMake to use the `$CC` and `$CXX` defined above with
```
CMAKE_FLAGS+=" -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX"
```
it's now wanting to link `-lcuda`, which gets installed into `/usr/lib64/nvidia` (and symlinked in `/usr/lib64`). Adding that gives me a cascade of missing symbols during linking:
```
[ 95%] Linking CXX executable ../../../TestCudaCompiler
/gpfs/alpine/bip178/scratch/jchodera1/miniconda/conda-bld/openmm_1549852083566/_build_env/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/bin/ld: warning: libnvidia-fatbinaryloader.so.396.64, needed by /usr/lib64/libcuda.so, not found (try using -rpath or -rpath-link)
/gpfs/alpine/bip178/scratch/jchodera1/miniconda/conda-bld/openmm_1549852083566/_build_env/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/bin/ld: /usr/lib64/libcuda.so: undefined reference to `fatBinaryCtl_Create'
/gpfs/alpine/bip178/scratch/jchodera1/miniconda/conda-bld/openmm_1549852083566/_build_env/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/bin/ld: /usr/lib64/libcuda.so: undefined reference to `elfLink_Finish'
/gpfs/alpine/bip178/scratch/jchodera1/miniconda/conda-bld/openmm_1549852083566/_build_env/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/bin/ld: /usr/lib64/libcuda.so: undefined reference to `elf64_symbol_name'
...
```
Should it really be trying to link `libcuda.so`? And any idea what might be going on here? Presumably, this is another case of `libcuda.so` being compiled with a different ABI from the conda compilers?

**Comment by jchodera** [comment]
I was able to disable the building of `TestCudaCompiler` by setting 
```
CMAKE_FLAGS+=" -DOPENMM_BUILD_CUDA_TESTS=OFF"
```
Success!
```
bash-4.2$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:34:02) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import simtk.openmm
>>> print(simtk.openmm.version.version)
7.3.0.dev-81bad1b
>>> print(simtk.openmm.Platform.getNumPlatforms())
3
>>> print([simtk.openmm.Platform.getPlatform(index).getName() for index in range(simtk.openmm.Platform.getNumPlatforms())])
['Reference', 'CPU', 'CUDA']
```
The builds are being pushed [here](https://anaconda.org/omnia-dev/openmm/files).
