### ISSUE TITLE
OpenMM 7.3.1 bugfix release?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#2260]
There have been a slew of useful bugfixes since the 7.3.0 release:
* fixed Ewald energy inconsistencies (#2257)
* improved minimizer constraint behavior (#2255)
* tabulated CustomGBForce fixes (#2248) 
* fixed OBC GBSA constants (#2246)
* fixed lepton functions (#2241) 
* fixed 2D tabulated functions in CustomHBondForce (#2232)
* fixed parsing of PSF files with multiple segments (#2231)
* Vec3 improvements (#2230)
* CPU LJPME (#2218)
* ppc64le support (#2212)

What do we think about cutting a 7.3.1 bugfix release? We can also build conda packages for `ppc64le`.

**Comment by peastman** [comment]
I'd just been thinking the same thing.  There've been a lot of fixes, and it's feeling like about time to do a patch release.

I agree with everything on your list except #2230 and #2212.  Those are both features, not bug fixes.  #2212 especially is a substantial new feature, including hundreds of new lines of code and significant changes to the build scripts.  That isn't something we can safely slip into a patch release.

**Comment by peastman** [comment]
I'd suggest also including #2229 (Eliminated use of a deprecated shuffle function) and #2222 (Improved logic for matching multi-residue patches).

**Comment by jchodera** [comment]
Is #2212 (compile on ppc64le) really a new "feature", in the user sense? No new API features were added---it will just compile and run on more hardware now.

We can certainly test it thoroughly prior to release, following our normal testing procedure, but it seems like it wouldn't quote merit a 7.40 designation.

**Comment by peastman** [comment]
> No new API features were added---it will just compile and run on more hardware now.

Which is to say, a major new feature!

> We can certainly test it thoroughly prior to release

What do you propose?

**Comment by jchodera** [comment]
> Which is to say, a major new feature!

It's just expanded support of more (CPU) hardware, which isn't really "new feature" territory. Back in the old days, this was just a few more lines in the makefile...

> What do you propose?

How about we cut a bugfix release, put together a conda package release candidate, test it thoroughly on multiple systems (including Summit; we got all the unit tests to pass now!), and run through a more elaborate comprehensive test suite (such as the [openmmtools](https://github.com/choderalab/openmmtools/tree/master/openmmtools/tests) one) before we move it to `main`?

**Comment by peastman** [comment]
> Back in the old days, this was just a few more lines in the makefile...

Um, no.  Take a look at the actual changes: https://github.com/pandegroup/openmm/pull/2212/files.

**Comment by jchodera** [comment]
> Um, no. Take a look at the actual changes: https://github.com/pandegroup/openmm/pull/2212/files.

Yep, I've seen worse all encoded in Makefiles...

**Comment by peastman** [comment]
The number one rule of patch releases is, "Don't break anything!"  That means not including anything unless you're confident that 1) it works correctly, and 2) it doesn't break anything else.  Given the large amount of new and changed code, both in C++ and CMake scripts, I'm not at all confident of either of those!

Once we've had a few months of people actually trying to use OpenMM on PPC, that will hopefully flush out the bugs and give us the confidence to include it in an official release.  But right now it's just too immature, and especially trying to include it in a patch release would be a super risky thing to do.

**Comment by jchodera** [comment]
> Once we've had a few months of people actually trying to use OpenMM on PPC, that will hopefully flush out the bugs and give us the confidence to include it in an official release

It took an ORNL software scientist a couple of weeks just to try to get it running, and without having a specific release to point to, it's hard to imagine anyone will actually want to do reproducible science before it is included in a point release. If nobody uses it, that plan is totally useless at identifying and eliminating bugs.

Tests help find and eliminate bugs. If we find the builds fail our tests, we can fix the bugs and issue point releases.

I'm honestly much more concerned about major bugs like #2257 that we *know* actually corrupt scientific results. Speaking of which, did you end up adding a test in #2257 that would have caught the original bug? That's certainly something we should do anytime we find our test coverage was incomplete.

**Comment by peastman** [comment]
By all means, create a dev conda package that people can use to install it on Summit.  Just make sure they know it's beta code, not an officially supported release.  Once we're confident it's working correctly, then we'll put it in an official release.

Automated test cases are an important part of testing, but they're far from sufficient.  There's no substitute for people actually working with the code.

**Comment by jchodera** [comment]
> There's no substitute for people actually working with the code.

That's the most economically and scientifically inefficient way to "test" scientific software imaginable.
OpenMM isn't a web browser. It's not easy to spot a glitch that leads to slightly wrong scientific results, and most humans are ill-prepared to identify things that don't lead to totally obvious failures or nans. Scientific software is verified by ensuring it reproduces expected results in comprehensive suite of test cases.

Expecting a nonexistent set of users to somehow validate code by not reporting errors after a few months is entirely magical thinking.

**Comment by peastman** [comment]
> That's the most economically and scientifically inefficient way to "test" scientific software imaginable.

No, *every single bug we've ever found* was one that got past the automated testing.  If automated testing were sufficient, we'd never have a single bug.  Sadly, that isn't the case.

> Expecting a nonexistent set of users to somehow validate code by not reporting errors after a few months is entirely magical thinking.

Could you please try to tone down the personal insults?  They're getting a little tiring.  And where do you get this "nonexistent set of users"?  We *already* have several people (including you!) who want to try out OpenMM on Summit.

**Comment by jchodera** [comment]
This was certainly not intended to be personally offensive, and I'm terribly sorry to have offended you. 

Fundamentally, we seem to have very different philosophies when it comes to how to ensure that the software we deliver to users is likely to be both useful and operating correctly, what kind of burden we expect to place on users for identifying potential issues with the code, and the confidence we attribute to nobody having reported a bug with a component for a given interval of time.

Most of the bugs _we've_ reported have been found by various test suites implemented in our codes. The bugs found by noticing funny behavior and banging our heads against the code for days to weeks are really problematic and end up with lots of wasted time, and indicate we've slipped up in test coverage somewhere along the way.

We've spent the week with an ORNL engineer, and it appears that, while other major MD codes are available for Summit (`ppc64le`), we're the first to try to build and run OpenMM there. I don't expect there are other OpenMM users on Summit at the moment, and expecting us to somehow uncover any bugs through some manner of manual process distinct from running the OpenMM and openmmtools test suites seems unrealistic from my vantage point. 

Potentially more problematic, however, is that, by withholding the `ppc64le` support from a point release, this is implicitly communicating that you wouldn't trust the code enough for someone to publish a project using the code. That creates additional potential problems---what is the incentive (to us and others) to use a code for months with the suggestion that any work arising from its use is inherently unpublishable?

Perhaps this could be mitigated with at least _some_ manner of point release designation, even if it clearly indicates this code is some form of `alpha` or `beta` release for the `ppc64le` platform?

**Comment by jchodera** [comment]
> Just make sure they know it's beta code, not an officially supported release. Once we're confident it's working correctly, then we'll put it in an official release. Automated test cases are an important part of testing, but they're far from sufficient. There's no substitute for people actually working with the code.

Also, I fear that this idea comes far too close to "we don't need to find the bugs in our code---our users will find them for us". There must be a better way for us to be reasonably confident that the code is behaving similarly on all platforms than to have a policy of relying on users to bear the brunt of finding problems.

I do think users understand that there will inevitably be some rare bugs that slip through testing and that these will be addressed through bugfix releases. One way we can deal with this fact and still make rapid scientific progress is to very carefully document the scope and impact of each bug discovered and fixed in each point release, and to make sure that point releases still come out at a steady rate so that most published research can be reproduced from the corresponding point release in case there is any doubt as to whether a bugfix changes a published result.

**Comment by peastman** [comment]
> this is implicitly communicating that you wouldn't trust the code enough for someone to publish a project using the code.

It's more than implicit.  I would very explicitly warn them of that.  I simply don't have confidence that all the bugs have been flushed out of the PPC code yet.  This is true of *any* new feature, but especially one involving a lot of new code.  That's why beta testing is so important.  I'm not going to pretend the code has been thoroughly tested when in fact it hasn't been.

You will probably say, "Doesn't that just mean we should expand our test suite?"  But no matter how much we expand it, that's still not enough.  Automated testing is great, and a very important part of creating good quality software.  But it's not a substitute for real users working with the code, because those users will immediately do things it never occurred to you to test for.

Take a look at some of the bugs we're fixing in this release.  For example, #2241.  That error came up when you used the `cross()` function, and one of the arguments was itself calculated with the `cross()` function.  We already had tests for the `cross()` function, but nothing that happened to cover that specific combination of nested functions.

Or #2222.  That happened if you used the CHARMM36 force field, and there were two CYS residues next to each other that both formed disulfide bonds.  We already had tests for CHARMM36, including with disulfide bonds, but nothing with that specific configuration.

That's the problem with automated test suites.  They only catch the errors you specifically thought to check for.  Until a few real users have spent some time working with the code, you have to assume it probably still contains bugs.  That's why beta testing is also an essential part of creating good quality software.

**Comment by jchodera** [comment]
OK, how about this plan:

Include the following in 7.3.1:
* fixed Ewald energy inconsistencies (#2257)
* improved minimizer constraint behavior (#2255)
* tabulated CustomGBForce fixes (#2248) 
* fixed OBC GBSA constants (#2246)
* fixed lepton functions (#2241) 
* fixed 2D tabulated functions in CustomHBondForce (#2232)
* fixed parsing of PSF files with multiple segments (#2231)
* CPU LJPME (#2218)
* Eliminated use of a deprecated shuffle function (#2229)
* Improved logic for matching multi-residue patches (#2222)

Then we create a 7.3.2b1 (first beta release of 7.3.2) that includes #2212, keeping it on the `omnia-dev` channel so that it's clear that it's an experimental release intended to be tested, rather than used for production.

**Comment by peastman** [comment]
Sounds like a plan!

**Comment by jchodera** [comment]
I just realized there are a few updates we could make to the distributed force fields:
1. The provenance information for the Amber force fields listed the wrong AmberTools source version
2. The CHARMM files have been updated since we downloaded them for our builds (presumably with bugfixes):

http://mackerell.umaryland.edu/charmm_ff.shtml#charmm

I'd like to at least fix issue 1. What do you think about 2?

**Comment by peastman** [comment]
Can you run a diff on the files to see what's changed?

**Comment by jchodera** [comment]
Still working on that `diff`, but I wonder if we should worry about trying to address #2249 first too?

**Comment by peastman** [comment]
Any progress?

**Comment by jchodera** [comment]
Still plugging away at the forcefield stuff...

**Comment by peastman** [comment]
In that case, I suggest we move ahead with this.  Those don't seem like urgent fixes for anything, so there's no need to hold up the release for them.

**Comment by jchodera** [comment]
Sounds good, let's do that.

**Comment by peastman** [comment]
I think we're ready to build a release candidate.  It should be built from the head of `7.3_branch`.  Currently that's revision 42c89799181893a6e38562a16d08f83b95eaee21.

**Comment by peastman** [comment]
And *of course* I'm running into errors trying to build the Windows packages, and *of course* they're a different error than I've ever seen before, even though I'm using the *exact same VM* that I used last time.  Because that happens *every @#$%! time* I try to build Windows packages.

In this case Doxygen is reporting an error trying to parse the headers so we can generate the Python API:

```
docstring of OpenMM::TabulatedFunction:0: ERROR: Content block expected for the "admonition" directive; none found.
```

**Comment by jchodera** [comment]
Can you provide some more context around this? This sounds like a sphinx error, but I'm confused as to why it's coming from doxygen.

**Comment by peastman** [comment]
Ok, it looks like all the packages have been built!  Now we just need to test a few of them to make sure everything is looking ok, and then we can announce the RC.

And *of course* I'm running into problems testing them.  Not because of anything wrong with the packages, but because conda is being broken on my Mac and gets an error when I try to create an environment to test it in.

```
$ conda create --name test
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /Users/peastman/miniconda3/envs/test



Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: failed

RemoveError: 'setuptools' is a dependency of conda and cannot be removed from
conda's operating environment.
```

Nothing.  Ever.  Works.

Any idea what could be causing this?  In the mean time, I'll try testing on Linux.

**Comment by jchodera** [comment]
Does a fresh conda install make the problem go away for you?

**Comment by peastman** [comment]
It's looking like my whole conda install is totally broken, and I'll have to do that.  Pretty much anything I try to do with it—installing, removing, updating, etc. for any package—produces that error.

**Comment by peastman** [comment]
A lot of other people have reported the same problem: https://github.com/conda/conda/issues/8149.  Some people were able to fix it with `conda update conda`, but that fails for me with a different error related to Qt.  Looks like I'll need to start over with a fresh copy of conda and reinstall all my libraries and projects from scratch.  This will take a while.  In the mean time, could you test out one or two of the RC Mac builds?

**Comment by jchodera** [comment]
Will test as soon as grant is submitted tonight!

**Comment by peastman** [comment]
I finished the reinstallation and tested the mac build.  It looks ok.  I'm going to go ahead and post the announcement.

**Comment by peastman** [comment]
Announcement is posted: https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=10135&p=0&start=0&view=

**Comment by peastman** [comment]
I've received no feedback from anyone about the release candidate, but Anaconda reports 55 total downloads over the various packages, so it looks like people have been using it.  Is it time to declare it an official release?

**Comment by jchodera** [comment]
I've run YANK's hydration validation set with it, and it seems to give correct hydration free energies. I also ran the test suites for `openmmtools` and `yank` and didn't see any problems crop up due to the new OpenMM release.

So I'd suggest we go ahead and release it and see if anyone complains!

**Comment by peastman** [comment]
And it's now released!
