### ISSUE TITLE
How to get the distance of centroid in z axis between a protein and a ligand? 

### ISSUE THREAD

**Issue by hhh-water** [pandegroup/openmm#2267]
rest_force=mm.CustomCentroidBondForce(2,"0.5*k*(distance(g1,g2)-r0)^2")
rest_force.addPerBondParameter('r0')
rest_force.addPerBondParameter('k')
rest_force.addGroup(range(11361, 20864))
rest_force.addGroup([3,4,5,6])
system.addForce(rest_force)
rest_force.addBond([0,1],[dist_ref,force_constant])

I want to use OpenMM to run a umbrella sampling. However, i want to calculate the distance only in z axis in the centroid of two group. Is there any suggestions for this issue?

**Comment by peastman** [comment]
What about just using `abs(z1-z2)`?

**Comment by hhh-water** [comment]
It works, thanks.
