### ISSUE TITLE
Cross torsional terms

### ISSUE THREAD

**Issue by forcefield** [pandegroup/openmm#2268]
Is there a way to implement a cross-term between two torsions through custom force.  Namely, I would like to introduce a term like

<a href="https://www.codecogs.com/eqnedit.php?latex=E(r_i,&space;r_j,&space;r_k,&space;r_l,&space;r_a,&space;r_b,&space;r_c,&space;r_d)&space;=&space;k&space;\cdot&space;f(\theta(r_i,&space;r_j,&space;r_k,&space;r_l))&space;\cdot&space;f(\theta(r_a,&space;r_b,&space;r_c,&space;r_d))" target="_blank"><img src="https://latex.codecogs.com/gif.latex?E(r_i,&space;r_j,&space;r_k,&space;r_l,&space;r_a,&space;r_b,&space;r_c,&space;r_d)&space;=&space;k&space;\cdot&space;f(\theta(r_i,&space;r_j,&space;r_k,&space;r_l))&space;\cdot&space;f(\theta(r_a,&space;r_b,&space;r_c,&space;r_d))" title="E(r_i, r_j, r_k, r_l, r_a, r_b, r_c, r_d) = k \cdot f(\theta(r_i, r_j, r_k, r_l)) \cdot f(\theta(r_a, r_b, r_c, r_d))" /></a>

There may be overlap between the set (_i, j, k, l_) and the set (_a, b, c, d_).

What is an easy route to this?

Thanks!
Huafeng

**Comment by peastman** [comment]
Yes, you can do this very easily with a CustomCompoundBondForce.  See http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.CustomCompoundBondForce.html/

**Comment by forcefield** [comment]
@peastman The CustomCompoundBondForce worked as described in the documentation.  Thanks!
