### ISSUE TITLE
install.sh file

### ISSUE THREAD

**Issue by fabiotrovato** [pandegroup/openmm#2283]
I am trying to install openmm on a linux cluster. I do not have root privileges. The manual suggests to download openmm and then do sudo ./install.sh

I dowloaded openmm-7.3.1, which shows this content:
appveyor.yml  CMakeLists.txt  cmake_modules  CTestConfig.cmake  devtools  docs-source  examples  libraries  olla  openmmapi  platforms  plugins  README.md  serialization  tests  wrappers

1) Where is the script ./install.sh? (there are two in devtools/ci/jenkins and devtools/packaging)
2) Without sudo, how should I execute the install.sh script and be likely to succeed?

Thank you,
Fabio

**Comment by jchodera** [comment]
It's much easier to install OpenMM in userspace using `conda`:
http://docs.openmm.org/latest/userguide/application.html#installing-openmm

**Comment by fabiotrovato** [comment]
Thank you for the answer,

so far I tried also the conda installation. It has worked, but without the CUDA Platform (that is the reason why I wanted to try the install.sh script).

For the conda installation, if I run 
`python -m simtk.testInstallation`
I get:

```
There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 OpenCL - Error computing forces with OpenCL platform

OpenCL platform error: Error initializing context: clGetPlatformIDs (-1001)

Median difference in forces between platforms:

Reference vs. CPU: 6.31499e-06
```

If I further look into what the problem might be with:
`import simtk.openmm as m
print(m.Platform.getPluginLoadFailures())
`
I get the following:

```
('Error loading library /home/trovato/miniconda3/envs/openmm/lib/plugins/libOpenMMCUDA.so: libcuda.so.1: cannot open shared object file: No such file or directory', 'Error loading library /home/trovato/miniconda3/envs/openmm/lib/plugins/libOpenMMRPMDCUDA.so: libcuda.so.1: cannot open shared object file: No such file or directory', 'Error loading library /home/trovato/miniconda3/envs/openmm/lib/plugins/libOpenMMDrudeCUDA.so: libcuda.so.1: cannot open shared object file: No such file or directory', 'Error loading library /home/trovato/miniconda3/envs/openmm/lib/plugins/libOpenMMAmoebaCUDA.so: libcuda.so.1: cannot open shared object file: No such file or directory', 'Error loading library /home/trovato/miniconda3/envs/openmm/lib/plugins/libOpenMMCudaCompiler.so: libnvrtc.so.9.0: cannot open shared object file: No such file or directory')
```
Does this mean that something with the cuda installation of the cluster is wrong?

**Comment by jchodera** [comment]
> It has worked, but without the CUDA Platform (that is the reason why I wanted to try the install.sh script).

Which CUDA toolkit version do you have installed? 

We are now building OpenMM conda packages for all recent CUDA toolkit versions. If you have version X.Y, then you would use 
```bash
conda install -c omnia/label/cudaXY -c conda-forge openmm
```
So, for example, for CUDA 10.0,
```bash
conda install -c omnia/label/cuda100 -c conda-forge openmm
```

**Comment by fabiotrovato** [comment]
I also have checked my PATH, which contains: 
```
usr/local/cuda-9.0/bin:/home/trovato/miniconda3/envs/openmm/bin
```

 and LD_LIBRARY_PATH which contains:
```
/usr/local/cuda-9.0/lib:/import/ag_cmb/software/cudnn7/cuda/lib64:/usr/local/cuda-9.0/lib64
```
What I do not understand (and probably there's something wrong here) is that

```
ls usr/local/cuda-9.0/bin
ls: cannot access usr/local/cuda-9.0/bin: No such file or directory

ls /usr/local/cuda-9.0/lib
ls: cannot access /usr/local/cuda-9.0/lib: No such file or directory

ls /usr/local/cuda-9.0/lib64
ls: cannot access /usr/local/cuda-9.0/lib64: No such file or directory
```

The only non-empty folder is this:

```
ls /import/ag_cmb/software/cudnn7/cuda/lib64
libcudnn.so  libcudnn.so.7  libcudnn.so.7.0.3  libcudnn_static.a
```
Thank you in advance for any suggestions you might have.

**Comment by fabiotrovato** [comment]
I typed:

```
conda install -c omnia/label/cuda90 -c conda-forge openmm
```

**Comment by jchodera** [comment]
Do you have the CUDA Toolkit 9.0 installed? What is the output of 
```
nvcc --version
```?

**Comment by fabiotrovato** [comment]
I don't have nvcc, apparently, despite there was a cuda9.0 module. So I guess this is a problem...

**Comment by jchodera** [comment]
Whoops, I just saw your other post above!

It sounds like CUDA 9.0 is incorrectly installed, or not installed at the path above. We can't fix that for you---your sysadmin will have to install a working CUDA toolkit as root.

**Comment by fabiotrovato** [comment]
> Whoops, I just saw your other post above!
> 
> It sounds like CUDA 9.0 is incorrectly installed, or not installed at the path above. We can't fix that for you---your sysadmin will have to install a working CUDA toolkit as root.

That's correct. Thank you for helping and confirming :)

**Comment by jchodera** [comment]
There's one thing you can try in userspace, but we haven't yet tested this. `conda` has a [userspace package for the CUDA toolkit](https://anaconda.org/anaconda/cudatoolkit).

You could try
```
conda install -c anaconda cudatoolkit==9.0
```
Again, we haven't tested this yet, and it may require some path or `LD_LIBRARY_PATH` manipulations to ensure the dynamic library paths are found for you.

We're considering trying to link to these in the future to minimize exactly this sort of issue and allow everything in userspace.

**Comment by fabiotrovato** [comment]
I tried your suggestion, but when I type 
```
python -m simtk.testInstallation
```
I still don't get any CUDA (I unloaded the previously loaded cuda9.0 module). 
I am wondering if there's anything else I can do after cudatoolkit installation?  I am not sure where to find the cudatoolkit libraries. I just found two files with prefix cudatool:
```
find /home/trovato/miniconda3/envs/openmm/ | grep cudatool
/home/trovato/miniconda3/envs/openmm/conda-meta/cudatoolkit-9.0-h13b8566_0.json
/home/trovato/miniconda3/envs/openmm/lib/cudatoolkit_config.yaml
```

Below the output of the installation of cudatoolkit.

```
## Package Plan ##

  environment location: /home/trovato/miniconda3/envs/openmm

  added / updated specs: 
    - cudatoolkit==9.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2019.1.23  |                0         126 KB  anaconda
    certifi-2019.3.9           |           py37_0         155 KB  anaconda
    cudatoolkit-9.0            |       h13b8566_0       340.4 MB  anaconda
    openssl-1.1.1              |       h7b6447c_0         5.0 MB  anaconda
    ------------------------------------------------------------
                                           Total:       345.7 MB

The following NEW packages will be INSTALLED:

    cudatoolkit:     9.0-h13b8566_0      anaconda   

The following packages will be UPDATED:

    certifi:         2019.3.9-py37_0     conda-forge --> 2019.3.9-py37_0  anaconda
    openssl:         1.1.1b-h14c3975_1   conda-forge --> 1.1.1-h7b6447c_0 anaconda

The following packages will be DOWNGRADED:

    ca-certificates: 2019.3.9-hecc5488_0 conda-forge --> 2019.1.23-0      anaconda
```

**Comment by jchodera** [comment]
Here's what I did:
```bash
conda create --yes -c omnia/label/cuda90 -c omnia -c conda-forge -c anaconda -n openmm python=3.7 openmm=7.3.1 cudatoolkit=9.0
```
which seems to work:
```
[chodera@lilac:chodera]$ source activate openmm
(openmm) [chodera@lilac:chodera]$ python -m simtk.testInstallation
There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Successfully computed forces
4 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.29598e-06
Reference vs. CUDA: 6.72554e-06
CPU vs. CUDA: 7.77258e-07
Reference vs. OpenCL: 6.75426e-06
CPU vs. OpenCL: 8.24702e-07
CUDA vs. OpenCL: 2.23948e-07
```

**Comment by fabiotrovato** [comment]
Thanks for trying, this is very neat!

I think I understood the source of my problem. I'm using a hybrid cpu-gpu cluster. CUDA was not showing up as a platform when I tested the installation on the head node (a cpu). I wrapped the command in a slurm script so it could run on gpus (see below) and ... voilà, I had the CUDA platform. I apologize for all the work I made you do, probably I should have realized this sooner.
Anyways, here it is what worked in the end for me:
```
#!/bin/sh
#SBATCH -p gpu
#SBATCH --gres=gpu:4
#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH --time=48:00:00
#SBATCH --exclude=gpu[037]

python -m simtk.testInstallation
echo "CUDA_VISIBLE_DEVICES: $CUDA_VISIBLE_DEVICES"
```

```
There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Successfully computed forces
4 OpenCL - Error computing forces with OpenCL platform

OpenCL platform error: Error initializing context: clGetPlatformIDs (-1001)

Median difference in forces between platforms:

Reference vs. CPU: 6.3072e-06
Reference vs. CUDA: 6.73626e-06
CPU vs. CUDA: 7.70373e-07
CUDA_VISIBLE_DEVICES: 0,1,2,3
```

**Comment by jchodera** [comment]
Great! Can you close this issue if this is fixed for you?
