### ISSUE TITLE
conda installation

### ISSUE THREAD

**Issue by fabiotrovato** [pandegroup/openmm#2284]
For some reason

`
conda install -c omnia/label/cuda80 -c conda-forge openmm
`

fails with error:

```
PackagesNotFoundError: The following packages are not available from current channels:

  - openmm
  - fftw3f
```

whereas, executing first

`
conda install -c omnia -c conda-forge openmm
`

and then

`
conda install -c omnia/label/cuda80 -c conda-forge openmm
`

gives the desired result.

```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openmm-7.3.1               | py36_cuda80_rc_2        11.4 MB  omnia/label/cuda80

The following packages will be UPDATED:

    openmm: 7.3.1-py36_cuda92_rc_2 omnia --> 7.3.1-py36_cuda80_rc_2 omnia/label/cuda80
```

**Comment by jchodera** [comment]
You need both `omnia/label/cudaXY` and `omnia` channels:
```bash
conda install -c omnia/label/cuda80 -c omnia -c conda-forge openmm
```
will do it in one line.

Where in the docs did you see the incomplete one-liner? We should update that?

**Comment by fabiotrovato** [comment]
I saw it here: http://docs.openmm.org/latest/userguide/application.html#creating-force-fields

> conda install -c omnia/label/cuda92 -c conda-forge openmm
> where cuda92 should be replaced with the particular CUDA version installed on your computer. Supported values are cuda75, cuda80, cuda90, cuda91, cuda92, and cuda100. Because different CUDA releases are not binary compatible with each other, OpenMM can only work with the particular CUDA version it was compiled with.
>

**Comment by jchodera** [comment]
Thanks!

**Comment by peastman** [comment]
Is there any reason not to just add all the different labels to the FFTW package?  Then it would be found regardless.

**Comment by fabiotrovato** [comment]
Hi,

> Is there any reason not to just add all the different labels to the FFTW package? Then it would be found regardless.

no there isn't any specific reason. fftw might actually be useful. How do I include it?

**Comment by peastman** [comment]
This is something for us to do.  What I meant is that we would add the labels `cuda80`, `cuda90`, etc. to that package.  Then if you specified `-c omnia/label/cuda80`, it would get found.

This seems to me like a very easy solution, and less likely to cause problems than specifying two different labels in the omnia channel (which would mean that two different OpenMM packages would both be found).  @jchodera do you see any reason not to do this?

**Comment by jchodera** [comment]
Interesting idea, @peastman!

To make this work, we would need to:
* manually add any OpenMM dependencies (like `fftw`) over to the `cudaXY` labels
* update the recipes for any dependencies to also push to all these other labels
* update all the recipes (and likely do a lot of manual label addition) for every CUDA version released
* make sure to do this for any new dependency we ever add

On the one hand, it saves users from typing a few characters.

On the other hand, it creates a lot of complexity in a different direction from how we should be moving, which is to get OpenMM onto `conda-forge` (which would save even more typing) to significantly reduce the complexity of the infrastructure we have to maintain.

I'd recommend we instead focus on experimental builds using the `anaconda` provided `cudatoolkit` packages, which now seem to be complete up through CUDA 10.0:
https://anaconda.org/anaconda/cudatoolkit

I think this was one of the last major remaining hurdle to moving to `conda-forge`: If we can build OpenMM using these `cudatoolkit` packages as dependencies, and we're OK with forgoing building the PDF manual via latex as part of the conda packaging process, we're probably good to start this migration.

At that point, we can distribute the CUDA toolkit version of our choice along with the package as a dependency, which means that users will no longer have this problem.

If we wanted to allow flexibility in CUDA versions for testing, we can further explore the [conda feature](https://docs.conda.io/projects/conda-build/en/latest/concepts/features.html) capability, like pytorch does. But I imagine most users simply want a working CUDA install in a single line, without the need to bug their sysadmins.

**Comment by peastman** [comment]
Nope, FFTW is the only dependency we'd have to add.  You know how I'm always trying to keep the runtime dependencies to a minimum?  Well this is one of the places where it pays off.  FFTW is literally the only one.  And it was built by hand, not through the automated build system, so there's really nothing to change.  All we need to do is manually add a few tags to it (which will take about one minute) and we're done.  The only ongoing maintenance will be that when we add support for new CUDA versions, we'll need to add the corresponding tags to FFTW.

**Comment by jchodera** [comment]
Sounds like an easy win for now, then.

**Comment by peastman** [comment]
Done.
