### ISSUE TITLE
Question regarding CMMotionRemover()

### ISSUE THREAD

**Issue by JBGreisman** [pandegroup/openmm#2297]
The default behavior for `ForceField.createSystem()` is to add a CMMotionRemover() to the system, as described in the [documentation](http://docs.openmm.org/latest/userguide/application.html#removing-center-of-mass-motion).  When I inspect the forces that are generated by `CMMotionRemover`, it always seems to be `(0.0, 0.0, 0.0) kJ/(nm mol)`. 

On a test system, I can confirm that there is a center of mass motion (albeit a small one) using this [formula](http://docs.openmm.org/latest/userguide/theory.html#cmmotionremover). I'd be happy to add a minimal example that reproduces this behavior, but I first want to check whether this is surprising behavior. 

I came across this [line](https://github.com/pandegroup/openmm/blob/1eec1e155e41a7657296cd46e9eb81292a8147b8/openmmapi/include/openmm/internal/CMMotionRemoverImpl.h#L55) in one of the CMMotionRemover header files, but it is unclear to me whether this is relevant.

**Comment by peastman** [comment]
This is correct.  CMMotionRemover doesn't apply forces to particles.  Instead, it periodically modifies all the velocities to remove any CM motion.  See http://docs.openmm.org/latest/userguide/theory.html#cmmotionremover for details.

**Comment by JBGreisman** [comment]
Got it -- I hadn't appreciated that since it acts on the velocities directly it wouldn't report a force.
