### ISSUE TITLE
Debug symbols on device side CUDA code

### ISSUE THREAD

**Issue by samarjeet** [pandegroup/openmm#2302]
Hi, 
   I am trying to step into the device side but am unable to add debug symbols in the kernels. I tried adding "-G -g" at CudaContext.cpp at at line 651 but that doesn't help. I think I am missing something very obvious. What would be the right way of doing it? Thanks in advance !

**Comment by peastman** [comment]
Possibly it's using the runtime compiler instead of invoking nvcc?  If so, compilation flags go in the second argument at https://github.com/pandegroup/openmm/blob/master/platforms/cuda/src/CudaContext.cpp#L615.

**Comment by samarjeet** [comment]
It seems to be trying to invoke the compiler as earlier in CudaContext constructor it checks for nvcc compiler and sets isNvccAvailable. So at 614 it steps over to that portion.
 If I just force it to use the runtime compiler by switching the flags tested at 614, it seg faults.

**Comment by peastman** [comment]
If you've verified it's reaching the call to `system()` at line 652, then clearly it really is executing nvcc with the specified flags.  Can you describe more precisely what you're trying to do?  When you said adding those flags "doesn't help," what exactly did that mean?  What are you doing, what did you expect to happen, and what happens instead?

**Comment by samarjeet** [comment]
Yes, it does call the sytem() at 652. When I set breakpoint at kernel launch (set cuda break_on_launch all), debugger switched the focus to a cuda thread. After this,  I would expect it to show the lines in the kernel as I step through each line. However, at each line I get "..../openmmTempKernel{hex_pointer}_{pid}.cu" line numbers rather than the actual lines in the kernel code.

**Comment by samarjeet** [comment]
The hash coded cache files for the modules are present in the tempDir (_60_64 files, I am using compute capability 60 on a 64 bit architecture). I can't see the content as it is hashed but seems like it would have the hashed ptx code. 

So, is the debugger not able to read the lines because the .cu file is being deleted at https://github.com/pandegroup/openmm/blob/master/platforms/cuda/src/CudaContext.cpp#L678 ?

**Comment by peastman** [comment]
If you comment out line 678, it won't delete the .cu file.

**Comment by samarjeet** [comment]
Yes, that was the issue. It works after commenting out the line. Thanks!
