### ISSUE TITLE
Problems with installing openmm in native python env

### ISSUE THREAD

**Issue by yshen22** [pandegroup/openmm#2303]
I was trying to install openmm in native python env. However my installation fails at 
 make install in tuning build.sh file. Here is my slighted modified build.sh script
INSTALL=`pwd`/install
if [ -e $INSTALL ]; then
    rm -rf $INSTALL
fi

CMAKE_FLAGS="-DCMAKE_INSTALL_PREFIX=$INSTALL"

CMAKE_FLAGS+=" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++"
CMAKE_FLAGS+=" -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9"
CMAKE_FLAGS+=" -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk"
CMAKE_FLAGS+=" -DOPENMM_GENERATE_API_DOCS=ON"

PREFIX="$/usr/local"
CMAKE_FLAGS+=" -DFFTW_INCLUDES=$PREFIX/include"
CMAKE_FLAGS+=" -DFFTW_LIBRARY=$PREFIX/lib/libfftw3f.dylib"
CMAKE_FLAGS+=" -DFFTW_THREADS_LIBRARY=$PREFIX/lib/libfftw3f_threads.dylib"

if [ -e build ]; then
    rm -rf build
fi
mkdir build
cd build
cmake ../openmm $CMAKE_FLAGS
make -j4 all install
make -j4 PythonInstall C++ApiDocs PythonApiDocs sphinxpdf

make install

cd $WORKSPACE

And Here is the error messages when running make install:
  [ 62%] Building CXX object plugins/cpupme/CMakeFiles/OpenMMPME.dir/src/CpuPmeKernelFactory.cpp.o
In file included from /Volumes/Data1/pythonlib/openmm/plugins/cpupme/src/CpuPmeKernelFactory.cpp:28:
/Volumes/Data1/pythonlib/openmm/plugins/cpupme/src/CpuPmeKernels.h:41:10: fatal error: 
      'fftw3.h' file not found
#include <fftw3.h>
         ^~~~~~~~~
1 error generated.
make[2]: *** [plugins/cpupme/CMakeFiles/OpenMMPME.dir/src/CpuPmeKernelFactory.cpp.o] Error 1
make[1]: *** [plugins/cpupme/CMakeFiles/OpenMMPME.dir/all] Error 2
make: *** [all] Error 2

 Actually, the fftw3.h file exists in /usr/local/include directory. But the make file could not find it.

**Comment by peastman** [comment]
What's the output of this command:

```
grep FFTW CMakeCache.txt
```

That will tell us whether CMake has configured things correctly.

**Comment by yshen22** [comment]
FFTW_INCLUDES:PATH=/Volumes/Data1/pythonlib/build/$/usr/local/include
FFTW_LIBRARY:FILEPATH=/Volumes/Data1/pythonlib/build/$/usr/local/lib/libfftw3f.dylib
FFTW_THREADS_LIBRARY:FILEPATH=/Volumes/Data1/pythonlib/build/$/usr/local/lib/libfftw3f_threads.dylib
//ADVANCED property for variable: FFTW_INCLUDES
FFTW_INCLUDES-ADVANCED:INTERNAL=1
//ADVANCED property for variable: FFTW_LIBRARY
FFTW_LIBRARY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: FFTW_THREADS_LIBRARY
FFTW_THREADS_LIBRARY-ADVANCED:INTERNAL=1

> What's the output of this command:
> 
> ```
> grep FFTW CMakeCache.txt
> ```
> That will tell us whether CMake has configured things correctly.

**Comment by peastman** [comment]
That looks like your problem then.  The include path is set to /Volumes/Data1/pythonlib/build/$/usr/local/include, but the headers are actually in /usr/local/include.  Perhaps the line

```
PREFIX="$/usr/local"
```

in your script should actually be

```
PREFIX="/usr/local"
```

**Comment by yshen22** [comment]
I have change the PREFIX to PREFIX="/usr/local". And now the command output is 
FFTW_INCLUDES:PATH=/usr/local/include
FFTW_LIBRARY:FILEPATH=/usr/local/lib/libfftw3f.dylib
FFTW_THREADS_LIBRARY:FILEPATH=/usr/local/lib/libfftw3f_threads.dylib
//ADVANCED property for variable: FFTW_INCLUDES
FFTW_INCLUDES-ADVANCED:INTERNAL=1
//ADVANCED property for variable: FFTW_LIBRARY
FFTW_LIBRARY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: FFTW_THREADS_LIBRARY
FFTW_THREADS_LIBRARY-ADVANCED:INTERNAL=1

    However the 'fftw3.h' file not found error still exists. 
This is my changed build.sh script
export WORKSPACE=`pwd`

PATH=$/usr/local/bin:$PATH


INSTALL=`pwd`/install
if [ -e $INSTALL ]; then
    rm -rf $INSTALL
fi

CMAKE_FLAGS="-DCMAKE_INSTALL_PREFIX=$INSTALL"

# setting the rpath so that libOpenMMPME.so finds the right libfftw3
#CMAKE_FLAGS+=" -DCMAKE_INSTALL_RPATH=.."
CMAKE_FLAGS+=" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++"
CMAKE_FLAGS+=" -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9"
CMAKE_FLAGS+=" -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk"
CMAKE_FLAGS+=" -DOPENMM_GENERATE_API_DOCS=ON"

# Build in subdirectory.
# Set location for FFTW3
PREFIX="/usr/local"
CMAKE_FLAGS+=" -DFFTW_INCLUDES=$PREFIX/include"
CMAKE_FLAGS+=" -DFFTW_LIBRARY=$PREFIX/lib/libfftw3f.dylib"
CMAKE_FLAGS+=" -DFFTW_THREADS_LIBRARY=$PREFIX/lib/libfftw3f_threads.dylib"

if [ -e build ]; then
    rm -rf build
fi
mkdir build
cd build
cmake ../openmm $CMAKE_FLAGS
make -j4 all install
make -j4 PythonInstall C++ApiDocs PythonApiDocs sphinxpdf


make install

cd $WORKSPACE

Is there other things I need to make change? Thank you.
   
> That looks like your problem then. The include path is set to /Volumes/Data1/pythonlib/build/$/usr/local/include, but the headers are actually in /usr/local/include. Perhaps the line
> 
> ```
> PREFIX="$/usr/local"
> ```
> in your script should actually be
> 
> ```
> PREFIX="/usr/local"
> ```

**Comment by peastman** [comment]
Try executing this command:

```
make VERBOSE=1
```

That will print out the commands it's executing, so you can see exactly what command it's failing on and what all the options to it are.  For example, there ought to be an option `-I/usr/local/include` to tell it to search for headers in that location.  Also, just to be sure, can you execute

```
ls /usr/local/include/fftw3.h
```

to verify that the file really is there?

**Comment by yshen22** [comment]
Yes, I tried 
```
   ls /usr/local/include/fftw3.h
```
The file is there.
  Here is verbose output of the error part of the buildings:
```
  [ 62%] Building CXX object plugins/cpupme/CMakeFiles/OpenMMPME.dir/src/CpuPmeKernelFactory.cpp.o
cd /Volumes/Data1/pythonlib/build/plugins/cpupme && /usr/bin/clang++  -DOPENMM_BUILD_VERSION=0 -DOPENMM_LIBRARY_NAME=OpenMM -DOPENMM_MAJOR_VERSION=7 -DOPENMM_MINOR_VERSION=4 -DOpenMMPME_EXPORTS -I/Volumes/Data1/pythonlib/openmm/plugins/cpupme/src -I/Volumes/Data1/pythonlib/openmm/plugins/cpupme/./include -I/Volumes/Data1/pythonlib/openmm/src -I/Volumes/Data1/pythonlib/openmm/libraries/asmjit -I/Volumes/Data1/pythonlib/openmm/libraries/vecmath/include -I/Volumes/Data1/pythonlib/openmm/libraries/irrxml/include -I/Volumes/Data1/pythonlib/openmm/serialization/include -I/Volumes/Data1/pythonlib/openmm/platforms/reference/include -I/Volumes/Data1/pythonlib/openmm/libraries/csha1/include -I/Volumes/Data1/pythonlib/openmm/libraries/hilbert/include -I/Volumes/Data1/pythonlib/openmm/libraries/lbfgs/include -I/Volumes/Data1/pythonlib/openmm/libraries/sfmt/include -I/Volumes/Data1/pythonlib/openmm/libraries/lepton/include -I/Volumes/Data1/pythonlib/openmm/libraries/quern/include -I/Volumes/Data1/pythonlib/openmm/libraries/jama/include -I/Volumes/Data1/pythonlib/openmm/olla/include -I/Volumes/Data1/pythonlib/openmm/openmmapi/include -I/Volumes/Data1/pythonlib/openmm/./include -I/Volumes/Data1/pythonlib/openmm/tests  -O3 -DNDEBUG -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.9 -fPIC   -msse2 -stdlib=libc++ -DLEPTON_USE_JIT -DOPENMM_PME_BUILDING_SHARED_LIBRARY -std=gnu++11 -msse4.1 -o CMakeFiles/OpenMMPME.dir/src/CpuPmeKernelFactory.cpp.o -c /Volumes/Data1/pythonlib/openmm/plugins/cpupme/src/CpuPmeKernelFactory.cpp
In file included from /Volumes/Data1/pythonlib/openmm/plugins/cpupme/src/CpuPmeKernelFactory.cpp:28:
/Volumes/Data1/pythonlib/openmm/plugins/cpupme/src/CpuPmeKernels.h:41:10: fatal error: 
      'fftw3.h' file not found
#include <fftw3.h>
         ^~~~~~~~~
1 error generated.
```
Here I didn't see -I/usr/local/include 
Is there any solution for that? Thank you.
> Try executing this command:
> 
> ```
> make VERBOSE=1
> ```
> That will print out the commands it's executing, so you can see exactly what command it's failing on and what all the options to it are. For example, there ought to be an option `-I/usr/local/include` to tell it to search for headers in that location. Also, just to be sure, can you execute
> 
> ```
> ls /usr/local/include/fftw3.h
> ```
> to verify that the file really is there?

**Comment by yshen22** [comment]
I am manually change the flag.make file, and the include problem has been resolved
