### ISSUE TITLE
Differences between state files (XML) and binary checkpoints

### ISSUE THREAD

**Issue by JoaoRodrigues** [pandegroup/openmm#2306]
Hi all,

To avoid portability issues, I decided to stick to XML files to restart simulations from previous runs. Specifically, I am using this when equilibrating a system and changing the weights of the position restraints: e.g. run with say, restraints force constant k=100 ends and I want to start a new run with k=50. This avoid setting the velocities randomly according to the thermostat and should give a smoother equilibration.  I should mention that I am using dummy atoms (mass 0, element None) to enforce position restraints.

The problem I'm facing is that whenever I try to restart a simulation from an XML state file (saved with `simulation.saveState`), it gives me `particle is nan` errors right at the first step. When I use the binary checkpoint file, things run smoothly. I checked manually what are the positions/velocities in these files and they match to a precision of 1e-7.

From the documentation, both options seem roughly equivalent, except for the portability of XML files and reproducibility of the binary files. I would assume that they wouldn't be such a big difference in their content to have failures in one and not in the other. Should I not?

**Comment by peastman** [comment]
Clearly *something* isn't getting restored properly, so we need to figure out what.  In addition to positions and velocities there also are box vectors and context parameters.  All of those should be in the XML file.

Immediately after loading the file and before taking any steps, try calling `getState()` to check the forces and energy.  Do they match the values from the original simulation at the time you called `saveState()`?  Also check with different platforms to make sure they all agree.

**Comment by JoaoRodrigues** [comment]
What I have now is:

The last `StateDataReporter` entry (maybe I could write this more often to get more precise values):
`100.0%  2000000 9999.999999866193       -1016995.3759023417     241611.74834730406      311.8807772886685       911.5287742383  105     0:00`

Potential energy from binary checkpoint:
`-1017326.0159258377 kJ/mol`

Potential energy from XML file:
`313049678809946.94 kJ/mol`

Clearly the XML file is wrong. However, I am doing something before writing it that might cause this issue. I have restraints (CustomExternalForces) that set global parameters. If I save the state, these global params are stored in the XML file and then if I happen to want to drop those restraints, I have to edit the file manually to remove them. So, my workaround was to remove the forces from the system and reinitialize the context and re-setting the positions and velocities. I assumed this was enough .. guess not? Code below:

```# Run simulation
simulation.step(n_steps)

# Write state file (without restraining forces)
xml_fname = _utils.make_fname_serial(rootname + '.xml')
logging.info(f'Writing state file to \'{xml_fname}\'')
system = simulation.system
n_rest_forces = sum([cmd.restraint_heavy_atom, cmd.restraint_lipids])
while n_rest_forces:
    system.removeForce(system.getNumForces() - 1)
    n_rest_forces -= 1

# Reinitialize context. Keep velocities, positions.
state = simulation.context.getState(getPositions=True, getVelocities=True)
xyz, vel = state.getPositions(), state.getVelocities()
simulation.context.reinitialize(preserveState=False)
simulation.context.setPositions(xyz)
simulation.context.setVelocities(vel)

simulation.saveState(xml_fname)```

**Comment by JoaoRodrigues** [comment]
Dug into the `loadState` method and indeed, it seems to load only positions and velocities (and parameters):

```
void Context::setState(const State& state) {
    setTime(state.getTime());
    Vec3 a, b, c;
    state.getPeriodicBoxVectors(a, b, c);
    setPeriodicBoxVectors(a, b, c);
    if ((state.getDataTypes()&State::Positions) != 0)
        setPositions(state.getPositions());
    if ((state.getDataTypes()&State::Velocities) != 0)
        setVelocities(state.getVelocities());
    if ((state.getDataTypes()&State::Parameters) != 0)
        for (auto& param : state.getParameters())
            setParameter(param.first, param.second);
}```

In my XML file, I have only parameters for the pressure coupling, which are always the same anyway, so it should not make a difference?

**Comment by peastman** [comment]
What about periodic box vectors?  You need to be sure those get saved and restored too.  When you call `reinitialize(preserveState=False)` they'll get lost.

**Comment by JoaoRodrigues** [comment]
They are in the XML file and get restored:
`[Vec3(x=8.43821, y=0.0, z=0.0), Vec3(x=0.0, y=6.78616, z=0.0), Vec3(x=0.0, y=0.0, z=14.969890000000001)] nm`

But indeed, differ from the binary file:
`[Vec3(x=8.750779661001227, y=0.0, z=0.0), Vec3(x=0.0, y=7.037534133933715, z=0.0), Vec3(x=0.0, y=0.0, z=14.80141104888657)] nm`

I'll fix this in my code and see if it solves the problem. Thanks!

**Comment by peastman** [comment]
When you call `reinitialize()`, they get reset to the default box vectors specified in the System.  And you don't restore them before calling `saveState()`.  That's why they're different.

**Comment by JoaoRodrigues** [comment]
Thanks Peter. They are reset to the initial state that I used to create the system. Perfect. Thanks a ton!
