### ISSUE TITLE
Summit OpenMM version number

### ISSUE THREAD

**Issue by des2037** [pandegroup/openmm#2319]
Hi OpenMM contributors,

I followed a OpenMM installation recipe for Summit (ORNL), kindly provided by @jchodera. The  [recipe](https://github.com/inspiremd/conda-recipes-summit) to a development version of [openMM 7.4.0.](https://anaconda.org/omnia-dev/openmm).

When I follow the recipe, indeed conda reports that openMM 7.4.0 is installed:
```
# Name                    Version                   Build  Channel
blas                      1.0                    openblas  
...
openmm                    7.4.0           py36_cuda101_rc_1    local
```
However, when I run the installation test, it reports that I'm using openMM 7.3.0:
```
python -m simtk.testInstallation
OpenMM Version: 7.3
Git Revision: 81bad1bc142d4b1fc286473528b454a3a8e26197
```

Does anyone have any ideas as to what might be going on, and which version of openMM is really installed? (is 7.4 reporting the wrong version number, or have I really installed 7.3)

Best,
Derek

Derek M. Shore, Ph.D. 
Scientific Systems Administrator 
Scientific Computing Unit    

Weill Cornell Medicine 
Department of Physiology and Biophysics 
1300 York Avenue
New York, NY 10065

**Comment by peastman** [comment]
There's no such thing as OpenMM 7.4.  The most recent release is 7.3.1.  I think John probably used that label for his conda build to distinguish it from the latest official release (which doesn't support PPC, and hence doesn't run on Summit).

**Comment by des2037** [comment]
Hi @peastman,

Thanks for the fast response. That makes sense, especially given that in John's version I see this:

```
>>> Platform.getOpenMMVersion()
'7.3'
```
Best,
Derek
