### ISSUE TITLE
Simulation of large systems take a very long time to start (hours)

### ISSUE THREAD

**Issue by des2037** [pandegroup/openmm#2320]
Hi pandegroup/openMM contributors,

I'm running into an issue in which large systems (+400K atoms) take forever to start (many hours). `top` and `nvidia-smi` indicate that openMM is only running on a single CPU core (and not GPUs) while this apparent hang occurs. 

However, after many hours of just running on 1 CPU, the simulation finally starts running on GPUs and the log is updated frequently/normally, with good simulation performance. 

This very slow start does not occur with more modest systems (simulations with ~150K atoms starts within a few minutes of being started). 

I've witnessed this behavior on systems with Intel (x86_64)+CUDA , as well as IBM POWER9+CUDA. 

Any ideas on how to resolve the very slow simulation start time for large systems? Please let me know if any additional information would be helpful in diagnosing what's going on.

Thanks!
Derek

Derek M. Shore, Ph.D. 
Scientific Systems Administrator 
Scientific Computing Unit    

Weill Cornell Medicine 
Department of Physiology and Biophysics 
1300 York Avenue
New York, NY 10065

**Comment by peastman** [comment]
I take it you're using the CUDA platform?  What set of constraints does your simulation include?

#2279 optimized building constraint matrices, which sometimes caused the behavior you describe.  It tended to be more of a problem with the CPU platform than the CUDA platform, but if you have a lot of connected constraints it might be the cause of what you're seeing.  If so, the current code in the master branch should be a lot faster.

**Comment by des2037** [comment]
Hi @peastman 

The only constraint I have are all of the bonds:
```
constraints = AllBonds
system = psf.createSystem(params, nonbondedMethod=PME, nonbondedCutoff=nonbondedCutoff, constraints=constraints, rigidWater=rigidWater, ewaldErrorTolerance=ewaldErrorTolerance, switchDistance=switchDistance, hydrogenMass=4*amu)
```
(I'm also attaching the full input file: [input_py.txt](https://github.com/pandegroup/openmm/files/3277686/input_py.txt))

For a system of ~650K atoms, there is definitely a lot of bonds, but I don't really have a frame of reference for whether this is enough to cause major simulation start slowness. What do you think? 

Regarding #2279, I've been using conda to install openMM, but I can definitely take a stab at compiling the source code if you think this will resolve this slowness to start. Do you think this would be useful?

**Comment by peastman** [comment]
That would do it.  The CUDA platform uses three different algorithms for constraints.  Water molecules are handled with SETTLE.  Clusters of a single heavy atom and hydrogens bonded to it are handled with SHAKE.  Both of those are fast to initialize, and if you specify `constraints=HBonds` they'll cover everything.  But if you specify `constraints=AllBonds`, that produces large networks of connected constraints for which SHAKE is very inefficient, so instead we use CCMA.  That requires building and inverting a matrix as part of creating the Context, and we were doing part of that in an inefficient way.  It should be much faster in the current code.

**Comment by des2037** [comment]
Thanks @peastman , that makes sense. I'll try compiling openMM v7.3.1 and see how it goes.

**Comment by ljmartin** [comment]
For what it’s worth @des2037, anecdotally I’ve noticed allbonds aren’t always needed for hydrogen mass repartitioning (4fs timestep). So HBonds might be fine and should start earlier.

**Comment by peastman** [comment]
I wouldn't recommend it.  The period of oscillation for bonds connecting two heavy atoms is often on the order of 20 fs, so you can't simulate that accurately with a timestep longer than about 2 fs.  Also, hydrogen mass repartitioning will make the heavy atoms lighter, so those oscillations will actually get a bit faster.
