### ISSUE TITLE
CustomIntegrator force instability

### ISSUE THREAD

**Issue by lvotapka** [pandegroup/openmm#2329]
Hello All. I'm having some trouble using an intermediate "scaled forces" variable in CustomIntegrator.

For instance, I get a NaN error for particle coordinates with the following code:

```
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from sys import stdout

prmtop = AmberPrmtopFile('./data/dip.top') # alanine dipeptide
inpcrd = AmberInpcrdFile('./data/md-4ns.rst7')
system = prmtop.createSystem(nonbondedMethod=PME, nonbondedCutoff=1*nanometer, constraints=HBonds)

timestep = 0.002*picoseconds
integrator = CustomIntegrator(timestep)


integrator.addGlobalVariable("totalForceScalingFactor", 0)
integrator.addPerDofVariable("scalingForce", 0)
integrator.addPerDofVariable("oldx", 0)

integrator.addComputeGlobal("totalForceScalingFactor", "1.0")
integrator.addComputePerDof("scalingForce", "f*totalForceScalingFactor")
integrator.addUpdateContextState()
integrator.addComputePerDof("v", "v+0.5*dt*scalingForce/m")
integrator.addComputePerDof("x", "x+dt*v")
integrator.addComputePerDof("oldx", "x")
integrator.addConstrainPositions()
integrator.addComputePerDof("v", "v+(x-oldx)/dt+0.5*dt*scalingForce/m")
integrator.addConstrainVelocities();

simulation = Simulation(prmtop.topology, system, integrator)
simulation.context.setPositions(inpcrd.positions)
if inpcrd.boxVectors is not None:
    simulation.context.setPeriodicBoxVectors(*inpcrd.boxVectors)
simulation.minimizeEnergy()
simulation.context.setVelocitiesToTemperature(300*kelvin)
simulation.reporters.append(StateDataReporter(stdout, 100, step=True, potentialEnergy=True, temperature=True))
simulation.step(1000)
```

I'm setting the variable 'totalForceScalingFactor' to 1.0 for the purpose of this example, but will be a different value in the application. But the following code works fine (notice the change from scalingForce to f in the velocity compute steps)

```
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from sys import stdout

prmtop = AmberPrmtopFile('./data/dip.top') # alanine dipeptide
inpcrd = AmberInpcrdFile('./data/md-4ns.rst7')
system = prmtop.createSystem(nonbondedMethod=PME, nonbondedCutoff=1*nanometer, constraints=HBonds)

timestep = 0.002*picoseconds
integrator = CustomIntegrator(timestep)


integrator.addGlobalVariable("totalForceScalingFactor", 0)
integrator.addPerDofVariable("scalingForce", 0)
integrator.addPerDofVariable("oldx", 0)

integrator.addComputeGlobal("totalForceScalingFactor", "1.0")
integrator.addComputePerDof("scalingForce", "f*totalForceScalingFactor")
integrator.addUpdateContextState()
integrator.addComputePerDof("v", "v+0.5*dt*f/m")
integrator.addComputePerDof("x", "x+dt*v")
integrator.addComputePerDof("oldx", "x")
integrator.addConstrainPositions()
integrator.addComputePerDof("v", "v+(x-oldx)/dt+0.5*dt*f/m")
integrator.addConstrainVelocities();

simulation = Simulation(prmtop.topology, system, integrator)
simulation.context.setPositions(inpcrd.positions)
if inpcrd.boxVectors is not None:
    simulation.context.setPeriodicBoxVectors(*inpcrd.boxVectors)
simulation.minimizeEnergy()
simulation.context.setVelocitiesToTemperature(300*kelvin)
simulation.reporters.append(StateDataReporter(stdout, 100, step=True, potentialEnergy=True, temperature=True))
simulation.step(1000)
```

Is this because the intermediate variable "scalingForce" does not have the same precision as 'f'? If so, then I can put 'f' directly into the expression for velocity updates. But assuming that parentheses matter, which is likely to result in the greatest long term stability?

`integrator.addComputePerDof("v", "v+0.5*dt*f*totalForceScalingFactor/m")`

`integrator.addComputePerDof("v", "v+0.5*totalForceScalingFactor*(dt*f/m)")`
etc?

Lastly, should addUpdateContextState() exist above all points when the forces are evaluated? I move it around but I don't notice any discernible difference.

Here are the files:
[dip.top.zip](https://github.com/pandegroup/openmm/files/3322428/dip.top.zip)
[md-4ns.rst7.zip](https://github.com/pandegroup/openmm/files/3322430/md-4ns.rst7.zip)

**Comment by peastman** [comment]
Is it consistent that you always get a nan with the first version and never with the second?  I want to make sure that it isn't just a stochastic failure that can occur with either one.  Also, how quickly does it get the nan?  Does it happen on the first or second step, or only after you've simulated a bunch of steps?

> Is this because the intermediate variable "scalingForce" does not have the same precision as 'f'?

The precision will depend on which platform you're using and, for the CUDA or OpenCL platforms, which precision mode you choose.  But in most cases, both quantities will have the same precision.  Also, it shouldn't matter which of those two versions you use.  They only differ in what order you multiply a set of quantities, and the accuracy of multiplication isn't generally sensitive to order (in contrast to addition or subtraction, which can be very sensitive).

> Lastly, should addUpdateContextState() exist above all points when the forces are evaluated?

In the particular example you posted, I don't think updateContextState actually does anything.  Your system doesn't include a barostat or an AndersenThermostat or anything else that uses that mechanism.  But if you want to correctly support those, you need to think about how they'll affect your algorithm.  For example, consider these lines:

```python
integrator.addComputePerDof("scalingForce", "f*totalForceScalingFactor")
integrator.addUpdateContextState()
integrator.addComputePerDof("v", "v+0.5*dt*scalingForce/m")
```

You first compute `scalingForce` based on the current force, then call updateContextState, then make use of that scaled force.  If your system has a barostat, updateContextState might change the box size and move atoms around.  That will change the force on each atom.  But `scalingForce` will still be based on the previous forces that are now out of date.  So you should swap the first two lines.

**Comment by lvotapka** [comment]
After trying about 5 different times, the first script consistently failed with a particle coordinate NaN after 50 to 100 steps. The second one didn't fail, even after running 5 times at 1000 steps each.

I'm using CUDA btw. I'll keep that in mind what you said about how the order of multiplication or division doesn't really matter, thanks for the info.

Thanks also about the info regarding addUpdateContextState(). I'm not using a barostat or anything in this particular example. Would you say that it's best to put addUpdateContextState() before any other instructions for the customintegrator?

**Comment by peastman** [comment]
Ok, I'll try running it and see if I can reproduce the problem.

> Would you say that it's best to put addUpdateContextState() before any other instructions for the customintegrator?

That depends on your algorithm.  You need to ask, "If the positions or velocities were to suddenly change at this point, would the results still be correct?"  *Usually* integrators are written so that the start of the calculation is a safe place to do that.  After all, you never know when the user might call `setPositions()` in between time steps.

**Comment by lvotapka** [comment]
Gotcha, thanks Peter.

**Comment by peastman** [comment]
I see the problem.  Consider what happens at each step of your algorithm.

```python
integrator.addComputePerDof("scalingForce", "f*totalForceScalingFactor")
integrator.addUpdateContextState()
integrator.addComputePerDof("v", "v+0.5*dt*scalingForce/m")
integrator.addComputePerDof("x", "x+dt*v")
integrator.addComputePerDof("oldx", "x")
integrator.addConstrainPositions()
integrator.addComputePerDof("v", "v+(x-oldx)/dt+0.5*dt*scalingForce/m")
```

The first line computes `scalingForce` based on the current forces.  It will only be valid as long as nothing changes that could affect the force.  In principle the second line could do that (by moving particle positions), but in your case there's nothing in your system that uses updateContextState, so the forces are still valid in the third line.  But the fourth line definitely does change the particle positions.  `scalingForce` is now out of date.  It reflects old forces when the particles were in different positions.  So when you reach the seventh line and update the velocities based on them, you're no longer integrating correctly and the simulation becomes unstable.

If you replace `scalingForce` by `f*totalForceScalingFactor`, then it runs without problem.

**Comment by lvotapka** [comment]
Ah yes, I see exactly what you are saying. I can't believe that I didn't notice that before. Thanks again, Peter.
