### ISSUE TITLE
Allow TabulatedFunction data to be provided as a Numpy array

### ISSUE THREAD

**Issue by tristanic** [pandegroup/openmm#2337]
Creating a new `Discrete3DFunction` for MDFF from a 256x272x149 (10.38 million voxel) map stored as a Numpy array currently takes about 4 seconds (out of a total of about 26 seconds for this particular simulation - 5ftk - on a fresh build from today's OpenMM code): 1.9 seconds to convert it to a list so the constructor will accept it, and 2.1 seconds for the constructor itself. On the C++ side the constructor is just populating a vector - essentially all the time is going to the binding code, which runs `strip_units()` on every value in the array. Since `simtk.unit` already supports wrapping a Numpy array in a `Quantity` object, it would be great if the various flavours of `TabulatedFunction` could provide alternative bindings supporting both bare or `Quantity`-wrapped Numpy arrays. Should bring the time down into the tens of milliseconds for an array this size. Some preliminary testing:

```
import numpy
from simtk import unit

big_array = numpy.random.rand(10000000)
degrees = big_array * unit.degree
%timeit degrees.value_in_unit(unit.radian)
46 ms ± 5.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
... so about a 100-fold speedup available over the status quo.

**Comment by peastman** [comment]
Good idea.  I made a similar change to speed up `setPositions()` in #2305.  We should be able to handle this in roughly the same way.
