### ISSUE TITLE
Low CPU usage on macbook

### ISSUE THREAD

**Issue by daviddesancho** [pandegroup/openmm#2342]
I am running some test simulations in a Macbook Pro and I am surprised of the low CPU usage I find in my system monitor. I am launching 4 simulations using multiprocessing but CPU usage for each of my 4 cores on the CPU platform remains systematically low (typically <20%). The code I am running can be found [here](https://github.com/daviddesancho/openmm-recipes/blob/master/alaTB/AlaTB_gmx_amber03-star_tip3p_parallel.ipynb) but the basic setup of my simulation (starting from a previous either a state from an NPT run or coordinates that go into `npt`) is shown below 
    
    integrator = LangevinIntegrator(300*kelvin, \
                        10/picosecond, \
                        0.002*picoseconds)
    
    nvt = Simulation(top.topology, system, \
                        integrator)
    
    try:
        state = npt.context.getState(getPositions=True, \
                    getVelocities=True)   
        nvt.context.setState(state)
    except AttributeError as e:
        nvt.context.setPositions(npt)
        nvt.context.setVelocitiesToTemperature(300*kelvin)

    dcd_rep = DCDReporter('nvt%i.dcd'%ind, 1000)
    nvt.reporters.append(dcd_rep)
    state_rep = StateDataReporter("nvt%i.txt"%init[0], 100, \
                step=True, potentialEnergy=True, \
                temperature=True, volume=True, density=True)
    nvt.reporters.append(state_rep)

Could you please give any suggestions on what I may be doing wrong?

**Comment by peastman** [comment]
Since you don't specify a platform when you create the Simulation, it automatically picks whichever platform it thinks will be fastest.  In your case, that's probably OpenCL running on the GPU.  You won't see much happening on the CPU, because that isn't where most of the work is being done.

**Comment by daviddesancho** [comment]
Thanks, that took care of it
