### ISSUE TITLE
Add sampling scripts

### ISSUE THREAD

**Issue by peastman** [pandegroup/openmm#2344]
I'm thinking of merging the simulated tempering and metadynamics scripts into OpenMM.  My plan was always to add them in once they were sufficiently mature.  At this point they've both been available for a long time and have been widely used, so it seems appropriate to merge them in and make them standard features.  Sound reasonable?

**Comment by jchodera** [comment]
I'm 100% in favor of getting them into a revision-controlled home with unit tests and docs.
Where in the import path would they go? `simtk.unit.openmm.app.misc`? `.tools`? `.sampling`?

**Comment by peastman** [comment]
I'd think they could just go in `.app` with everything else.  In terms of documenting them, I'd group them with aMD since they're all sampling methods.

**Comment by jchodera** [comment]
Where do the docs for aMD end up?
http://docs.openmm.org/latest/api-python/app.html

And what were you thinking in terms of unit tests and examples?

**Comment by peastman** [comment]
http://docs.openmm.org/latest/api-python/generated/simtk.openmm.amd.AMDIntegrator.html#simtk.openmm.amd.AMDIntegrator, and in the manual at http://docs.openmm.org/latest/userguide/application.html#amd-integrator.  But we probably want to reorganize that.  It's currently grouped with the integrator because it is an integrator, but once we have multiple accelerated sampling methods it makes more sense to put those together.
