### ISSUE TITLE
non-integer residue ID in CHARMM PSF and CRD files

### ISSUE THREAD

**Issue by charmm-gui** [pandegroup/openmm#2348]
It seems like that current CharmmPsfFile and CharmmCrdFile are not able to handle non-integer residue ID.
It would be great if it can support non-integer residue ID for the PDB file containing insertion code.
The example CHARMM PSF and CRD files are attached.

[non_int_resid.zip](https://github.com/pandegroup/openmm/files/3411363/non_int_resid.zip)

**Comment by peastman** [comment]
By "non-integer residue ID", you mean a residue ID that includes an insertion code, right?  More specifically, https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/charmmpsffile.py#L713 should be changed to something like

```python
residue = topology.addResidue(atom.residue.resname, chain, str(atom.residue.idx), atom.residue.inscode)
```

That will record the insertion code correctly, but won't actually affect very many things.  Are there specific situations where it currently leads to incorrect behavior?

**Comment by charmm-gui** [comment]
Yes, it means a residue ID including an insertion code.
Below is the specific error message that I am getting:

> Traceback (most recent call last):
  File "/share/ceph/woi216group/shared/apps/openmm-cgenff/lib/python3.6/site-packages/simtk/openmm/app/charmmcrdfiles.py", line 117, in _parse
    self.resid.append(int(line[8]))
ValueError: invalid literal for int() with base 10: '169A'

**Comment by jchodera** [comment]
It looks like a few [pdbfixer](http://github.com/pandegroup/pdbfixer) issues may be related to this:
* Fail to find missing residues on PDB with insertion code: https://github.com/pandegroup/pdbfixer/issues/154
* Issue with insertion codes: https://github.com/pandegroup/pdbfixer/issues/153

**Comment by jchodera** [comment]
I'm not sure if it's helpful, but @swails recently overhauled the [parmed PDB parsers](https://github.com/ParmEd/ParmEd/pull/1039).

Insertion codes are fully compliant parts of the official [PDB format](http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM):
> Alphabet letters are commonly used for insertion code. The insertion code is used when two residues have the same numbering. The combination of residue numbering and insertion code defines the unique residue.

We would likely have to update the `Topology` object as well to preserve this information.

**Comment by swails** [comment]
This code was lifted directly from ParmEd long ago.  This particular bug was reported and fixed in ParmEd/ParmEd#1059 -- the same fix is applicable here.

**Comment by jchodera** [comment]
I wonder if it would make sense to have only one implementation that both projects could import and jointly maintain?

**Comment by swails** [comment]
They've diverged a bit at this point. But where would such a package live? Both OpenMM and parmed aim to minimize the number of external packages that are installed. 

If someone can find a solution amenable to both packages I think the idea has clear maintenance benefits. But I haven't been able to think of a good solution to this.

**Comment by peastman** [comment]
What about splitting up the residue number and insertion code and recording them both like in https://github.com/pandegroup/openmm/issues/2348#issuecomment-513243604?  The number is required to be an int (http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM), and that way we'd get a more complete/correct Topology.  That matters for tools like PDBFixer that process Topologies.

**Comment by swails** [comment]
For the CHARMM PSF file that would make sense, but for the coordinate file we might as well just not parse it at all. 

The quoted error is in the CHARMM coordinate file, not the PSF

**Comment by peastman** [comment]
It looks like this comes up in two different files.  #2350 removes it in CharmmCrdFile, but that doesn't actually fix this issue.  To do that, we also have to fix CharmmPsfFile.

**Comment by jchodera** [comment]
Don't forget these related issues where the same problem has nothing to do with Charmm*File:
* Fail to find missing residues on PDB with insertion code: https://github.com/pandegroup/pdbfixer/issues/154
* Issue with insertion codes: https://github.com/pandegroup/pdbfixer/issues/153
* More rigorous implementation of findMissingResidues needed (e.g., doesn't work for antibodies): https://github.com/pandegroup/pdbfixer/issues/170
