### ISSUE TITLE
Possible to build on OS X without XCode?

### ISSUE THREAD

**Issue by proteneer** [pandegroup/openmm#304]
I have only the command line tools installed (since Mavericks no longer requires X Code to be installed in its entirety):

http://www.computersnyou.com/2025/2013/06/install-command-line-tools-in-osx-10-9-mavericks-how-to/

However, I (obviously) don't have an SDK, and when trying to run cmake I get this message:

CMAKE_OSX_DEPLOYMENT_TARGET is '10.7' but CMAKE_OSX_SYSROOT:

   ""

  is not set to a MacOSX SDK with a recognized version.  Either set
  CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to
  empty.

Does setting CMAKE_OSX_DEPLOYMENT_TARGET actually have any repercussions? Does it limit the versions I can deploy on?

**Comment by swails** [comment]
This can be closed, I think.
