### ISSUE TITLE
Virtual sites on exact positions of atoms

### ISSUE THREAD

**Issue by leeping** [pandegroup/openmm#305]
I ran a calculation where I had virtual sites on the exact same positions as my atoms - it is a possibility when tweaking force field parameters.  More specifically, I had a TwoParticleAverageSite where one of the weights was 1.0 and the other was 0.0.  This led to the dynamics simulation blowing up, but I only need to modify the weights a little bit to restore the correct behavior (0.999 and 0.001).

I am curious, does this have something to do with dividing by zero or singular matrices?  Is it worth fixing, or should I make sure my virtual sites never sit on top of the atoms?

Thanks!

**Comment by jchodera** [comment]
@leeping: Is this still a bug?

**Comment by leeping** [comment]
I'm not sure.  Since I don't remember it being addressed, it probably is still a bug.

**Comment by jchodera** [comment]
Unfortunately, dropbox is banned here, so I can't easily check on your files.

**Comment by leeping** [comment]
I was trying to reproduce it this morning but had no time.  I'll try to get to it, today is a long string of meetings.

**Comment by leeping** [comment]
I just tried to reproduce this bug today but I could not.  It seems the bug is fixed in the latest version, so we can close it for now.

**Comment by jchodera** [comment]
Great!  Can you close?

**Comment by leeping** [comment]
Sure.
