### ISSUE TITLE
Proposed solution for building static libs

### ISSUE THREAD

**Issue by proteneer** [pandegroup/openmm#306]
I'm going to fix our CMakeLists.txt so that we can do finally static linking properly (it has been broken for a long time). I'd like some feedback on the proposed solution, with an example for the OpenCLPlatform (as very similar schemes follows CUDA, and CPU platforms.)

If the cmake option BUILDING_STATIC_LIB is set to ON:

- If OPENMM_BUILD_OPENCL_LIB is ON, then OPENMM_BUILDING_STATIC_LIBRARY is defined.
- In OpenCLPlatform.cpp file, the registerPlatforms entry is modified to:

```c
#ifdef OPENMM_BUILDING_STATIC_LIBRARY
extern "C" void registerStaticOpenCLPlatform() {
    Platform::registerPlatform(new OpenCLPlatform());
}
#else
extern "C" OPENMM_EXPORT_OPENCL void registerPlatforms() {
    Platform::registerPlatform(new OpenCLPlatform());
}
#endif
```

- The user must then explicitly call registerStaticOpenCLPlatform() in their code,  if linking against OpenMMOpenCL.

**Comment by peastman** [comment]
This was implemented a while ago.
