### ISSUE TITLE
Add build tests for multiple compilers to Jenkins builds

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#381]
Would be useful to test with multiple compilers.

@kyleabeauchamp and @pgrinaway can help with this

**Comment by jchodera** [comment]
I think we can actually use a [build matrix](http://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix) to test this quickly on travis-ci.

I've totally forgotten what compilers we might want to test, though.  Is `gcc` supported in addition to `clang`?

**Comment by rmcgibbo** [comment]
Currently the build matrix on travis only has two entries, and each takes about 15 minutes. I think the total amount of time they'll give you is around 1hr per commit across the matrix, so we might be able to add 1 or 2 more.

**Comment by rmcgibbo** [comment]
I really don't think that we'd get much information from testing against gcc and clang, beyond just one of them. They're basically the same.

**Comment by jchodera** [comment]
This may be no longer relevant.  I think we had an issue with some compilers at one point, but I haven't run into anything in a while.
