### ISSUE TITLE
OpenMM template script seg faults with this pdb file on CPU platform

### ISSUE THREAD

**Issue by jisraeli** [pandegroup/openmm#414]
When I run the openMM template code (https://github.com/jisraeli/GaussianCharges/blob/2Waters/temp.py) with a pdb file of 2 water molecules (https://github.com/jisraeli/GaussianCharges/blob/2Waters/TwoWaters.pdb) I get a segmentation fault on the CPU platform, but it works fine on Reference and CUDA. I was told it might have to do with the 2 molecules being too small of a system?

**Comment by peastman** [comment]
Does this problem still exist, or was it fixed by #343?
