### ISSUE TITLE
PDBFile should preserve resSeq

### ISSUE THREAD

**Issue by kyleabeauchamp** [pandegroup/openmm#449]
If we take a PDB, load it, and save it, it will destroy the resSeq information present in the original PDB:

```
import simtk.openmm.app as app
pdb = app.PDBFile("./pdb/1vii.pdb")
app.PDBFile.writeFile(pdb.topology, pdb.positions, open('1vii_2.pdb', 'w'))
```

This is particularly important for PDBFixer, where it's critical to have self-consistent PDBs across a project.  

I believe we have already fixed this issue in MDTraj, so we can backport the changes: https://github.com/rmcgibbo/mdtraj/blob/master/MDTraj/formats/pdb/pdbfile.py

**Comment by peastman** [comment]
PDBFile.writeFile() now has an optional keepIds argument that can be used to do this.
