### ISSUE TITLE
Set version to 6.1-dev?

### ISSUE THREAD

**Issue by rmcgibbo** [pandegroup/openmm#452]
The version string on master is set to 6.0.0: https://github.com/SimTk/openmm/blob/master/CMakeLists.txt#L151

Via the cmake/python build system, this translates to
```
In [1]: import simtk.openmm as mm

In [2]: mm.version.full_version 
Out[2]: '6.0.0.dev-0d61baa'
```

How do we want this to look? I think `6.1.0-dev-<git-hash>` would be the most appropriate..

**Comment by jchodera** [comment]
I think this can be closed.
