### ISSUE TITLE
Proofread documentation

### ISSUE THREAD

**Issue by peastman** [pandegroup/openmm#561]
I rebuilt the User Guide and Developer Guide based on the current version of the code and posted them online:

http://web.stanford.edu/~peastman/OpenMMUsersGuide.pdf
http://web.stanford.edu/~peastman/OpenMMDeveloperGuide.pdf

Kyle, how far did you get in proofreading?  Anything that hasn't been checked already needs to be checked.  So please, volunteer to take a section!

The goal is to make sure the conversion from MS Word was done correctly.  The documentation hasn't been fully updated for 6.1 yet, so don't worry about that.  Also if you come across things you think are badly written or in need of updating, feel free to mention it, but also don't feel like you need to specifically look for things like that.  This is really just about checking the conversion.  You'll probably want to have the old version open at the same time so you can directly compare them against each other.

Things to particularly look for (since, based on prior experience, they're especially likely to have come out wrong):

* Greek letters that have gotten replaced by Latin equivalents (e.g. alpha changed to a)

* math symbols in the wrong font (e.g. a vector written as italic rather than bold)

* missing backslashes in Windows paths

* spaces and/or blank lines that have gotten removed

* incorrect formatting of math expressions (including both equations on their own lines and inline symbols within the text).

**Comment by kyleabeauchamp** [comment]
@peastman I think this can be clsoed

**Comment by peastman** [comment]
Thanks!
