### ISSUE TITLE
SimTk -> pandegroup org. name change

### ISSUE THREAD

**Issue by mpiercy** [pandegroup/openmm#657]
We changed the organization name of SimTk to pandegroup today.

There are a few steps that need to be done after the org rename.

Two main steps.

Most important- you will need to update your local repositories to point to the new location.

Changing links on your Github Profile page

Info about this from GitHub-

https://help.github.com/articles/what-happens-when-i-change-my-organization-s-name

"Technically, you'll also be able to continue pushing your local repositories to the old remote tracking URL without updating it. However, we recommend you update all existing remote repository URLs after changing your organization name. Because your old organization name is available for use by anyone else after you change it, that person would be able to create repositories that override the redirect entries.

Your previous Git commits will also be correctly attributed to users within your organization.

Changes that aren't automatic-

"After changing your username, links to your previous profile page,
such as https://github.com/previoususername, will return a 404 error.
For this reason, you'll want to update your LinkedIn profile, Twitter
profile, or anywhere else you've added a link to your GitHub account.

GitHub also cannot set up a redirect for:

@mentions using your old username
Links to Gists with your old username"

Thanks,

Mark

**Comment by kyleabeauchamp** [comment]
This can be closed now IMHO.
