### ISSUE TITLE
Charmm36 

### ISSUE THREAD

**Issue by ChayaSt** [pandegroup/openmm#685]
I want to use the Charmm36 force fields. I can add it, I'm just making sure that no one has done it yet.

**Comment by ajasja** [comment]
Hi all!

Just wondering what is the current status of CHARMM 36 (or 22) support?

I'm guessing the psf/pdb combinations work fine (but one must then use/automate [`psfgen`](http://www.ks.uiuc.edu/Research/vmd/plugins/psfgen/)).

And to build the model system inside OpenMM, one needs the forcefield in the openMM xml format. But the (script for conversion)[https://github.com/pandegroup/openmm/blob/master/devtools/forcefield-scripts/processCharmmForceField.py] is not quite ready. (And there might be some NBFIX terms that also have to be accounted for).

Is this an accurate summary?

**Comment by jchodera** [comment]
> Just wondering what is the current status of CHARMM 36 (or 22) support?

We're stalled a bit as we decide how best to proceed with converting recent CHARMM forcefields.  It looks like we may be adopting [ParmEd](https://github.com/ParmEd/ParmEd) as a central tool for converting AMBER and CHARMM forcefields to OpenMM `ffxml` format, but this work has not yet started.

> I'm guessing the psf/pdb combinations work fine (but one must then use/automate psfgen).
> And to build the model system inside OpenMM, one needs the forcefield in the openMM xml format. But the (script for conversion)[https://github.com/pandegroup/openmm/blob/master/devtools/forcefield-scripts/processCharmmForceField.py] is not quite ready. (And there might be some NBFIX terms that also have to be accounted for).

If you have PDB and PSF files, as well as the CHARMM `.rtf` and `.prm` files (which you can get from [here](http://mackerell.umaryland.edu/charmm_ff.shtml)), you should be able to load these directly into OpenMM now without an issue.  See [this section](http://docs.openmm.org/6.3.0/userguide/application.html#using-charmm-files) of the OpenMM manual.

**Comment by ajasja** [comment]
@jchodera Thanks for the quick reply! 
Perhaps we will just switch to Amber forcefields for this part (choosing a forcefield is hard, but according to http://pubs.acs.org/doi/abs/10.1021/ct2007814 it seems that amber03 and charmm27 are quite comparable).

**Comment by jchodera** [comment]
CHARMM36 conversion (without Drude) is complete. @ChayaSt : Can you close this?
