### ISSUE TITLE
6.3(?) features

### ISSUE THREAD

**Issue by peastman** [pandegroup/openmm#745]
With 6.2 almost done, I'm starting to work on features for the next release.  We discussed this in the OpenMM meeting a couple of weeks ago, and the feature that came out as the top priority is triclinic boxes.  But since not everyone was at the meeting, I'd like to also open the discussion here.  What do you see as being the highest priority features you would most like to see in the next release?

**Comment by jchodera** [comment]
We can probably close this issue, since 6.3 is in beta.

Feature ideas that didn't make it into 6.3 can be created as separate issues and discussed separately.
