### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by rmcgibbo** [pandegroup/openmm#779]
This might be totally obvious, but I'm getting a little stuck, and figure I should write this down so I don't forget. Perhaps someone will have a good idea what's going on. I'm trying to compile OpenMM on win-32 using VC10. The goal is to figure out the proper patches for the conda recipe, so that the appropriate PATHs get set and the DLLs load correctly.

Currently, my issue is that, from python, calling `Platform.loadPluginsFromDirectory` leads to a segfault.
```
>>> Platform.loadPluginsFromDirectory("C:\openmm\lib\plugins")
[segfault, or actually "APPCRASH"]
```

To debug this, I've added some scattered print statements.

  1) Inside `OpenMMSwig.cxx`, I added a print statement to the python wrapper for `loadPluginsFromDirectory`, just before the call to the OpenMM C++ API function `OpenMM::Platform::loadPluginsFromDirectory`. That call now looks like
```
std::string const & qq = *arg1;
std::cout << "swig wrapper" << qq << std::endl;
result = OpenMM::Platform::loadPluginsFromDirectory((std::string const &)*arg1);
```
  2) Next, inside `Platform.cpp`, I added a couple print statements to the very begging of the function. It now looks like
```
vector<string> Platform::loadPluginsFromDirectory(const string& directory) {
    std::cout << "std::cout directory" << directory << std::endl;
    printf("printf directory: %s\n", directory);
    printf("printf directory: %s\n", directory.c_str());
    [rest of function]
```

When you run this code `Platform.loadPluginsFromDirectory("C:\openmm\lib\plugins")` from python, before crashing it prints:

```
swig wrapper C:\openmm\lib\plugins
std::cout directory╘φ' ┘*B⌠ΦªÆ☻         ☼
printf directory: C:\openmm\lib\plugins
printf directory: ╘φ'
```
HUH? (The funny characters are different every time.) The string looks just fine, according to `std::cout`, from inside the swig file. But then once we're in `Platform.cpp` it's nonsense according to `std::cout`? But looks fine if you `printf` it? But not if you call `.c_str()` on it? I really do not know what's going on.

**Comment by mpharrigan** [comment]
Shouldn't you escape your backslashes?

**Comment by peastman** [comment]
Sounds like what you really have is a char*, but something along the way has reinterpreted it as a string*?

**Comment by rmcgibbo** [comment]
> Sounds like what you really have is a char*, but something along the way has reinterpreted it as a string*?

That makes sense. Thanks.

**Comment by rmcgibbo** [comment]
This is fixed now. Thanks for the help, @peastman.
