### ISSUE TITLE
Strangeness with units

### ISSUE THREAD

**Issue by swails** [pandegroup/openmm#786]
So I was helping a colleague try OpenMM for the first time, and they got a weird segfault.  I took a look at their script, and saw:

```Python
import simtk.unit as u
import simtk.openmm as mm

...

integrator = mm.LangevinIntegrator(298.15*u.kelvin, 5.0/u.picoseconds,
                                   2.0/u.femtoseconds)

...
```

In the context of the whole python script, the `2.0/u.femtoseconds` (which should be `2.0*u.femtoseconds`) is understandably easy to miss.  But rather than throw up an exception (like I would have naively expected), `mm.LangevinIntegrator` did something a bit more startling:

```
time_step = time_step.value_in_unit(u.md_unit_system)
```

And then said "well, it must be picoseconds now".  Well, `(2/u.femtoseconds).value_in_unit(u.md_unit_system)` is, naturally, `2000/ps`, so this particular code assigns the time step of `integrator` to be 2 ns... more than enough to segfault.

This also leads to such strange behavior as:

```Python
In [6]: int2 = mm.LangevinIntegrator(298*u.kelvin, 5.0/u.picoseconds, 2/u.milligrams)

In [7]: int2.getStepSize()
Out[7]: Quantity(value=2000.0, unit=picosecond)
```

I think this "problem" arises from the naivete of `stripUnits`, but if it's possible to fix (probably by mucking with the SWIG code), it would probably be worthwhile to implement saner unit checking.  Obviously a timestep in milligrams^-1 is stupid, but 2/femtoseconds is an understandable oversight that may be tough to detect for new users.

**Comment by jchodera** [comment]
Good catch!

**Comment by peastman** [comment]
This is one of the weak points of units handling in general. The Python wrapper doesn't actually know what type of quantity any particular argument is supposed to be.  It just assumes you've picked the appropriate type, then converts that to the corresponding standard unit.  So if you give it angstroms, it will convert to nm.  But if that argument was actually supposed to be a time, not a distance, it doesn't know.

In principle this could be changed, but it would require documenting the type of every single argument to every single method in a machine readable way.

**Comment by jchodera** [comment]
> In principle this could be changed, but it would require documenting the type of every single argument to every single method in a machine readable way.

This may not be very hard.  We can use decorators to do this.  I was working on something like this in some experimental code:
https://github.com/choderalab/pyopenmm/blob/master/pyopenmm/decorators.py#L44-L70

Essentially, we'd just add a decorator to the swig additions that specify what, if any, units the arguments should be compatible with.  For example:
```
    @accepts_compatible_units(units.nanometer)
    def setCutoffDistance(self, cutoffDistance):
        """
        Set the cutoff distance (in nm) being used for nonbonded interactions.  If the NonbondedMethod in use
        is NoCutoff, this value will have no effect.
        
        """
```

**Comment by peastman** [comment]
You're talking about annotating Python code by hand, but that's not what we're doing here.  We're talking about Python code that is automatically generated based on C++ code.

**Comment by jchodera** [comment]
This information is already in the swig wrapper building framework:
https://github.com/pandegroup/openmm/blob/master/wrappers/python/src/swig_doxygen/swigInputConfig.py#L148-L211

We could have the wrapper-generation code also add appropriate decorators to each swig-wrapped method, could we not?

**Comment by peastman** [comment]
Except most of it isn't.  Many functions aren't documented there, and many of the ones that are there are missing their arguments.  Currently it's only used for return values.

**Comment by jchodera** [comment]
> Except most of it isn't. Many functions aren't documented there, and many of the ones that are there are missing their arguments. Currently it's only used for return values.

We could certainly compile that if there would be value in this (and it sounds like there might be!).

Or we could add this information to the documentation strings and have it automatically extracted (which would also have value).

**Comment by swails** [comment]
I can appreciate why offloading unit consistency to the user makes life much easier for the SWIG-generated wrappers.  I was just providing a real-world example of where this caused a problem with a new user.

I think it makes sense to consider this a problem worth trying to devise a solution to.  If I think of something, I'll work on a proof-of-principle PR (like I did with the random number seeds); I figured I'd open an issue here to see if others had ideas as well.

**Comment by swails** [comment]
So I was thinking about this some more, and it occurred to me that this problem *mostly* exists with integrators (at least for beginners).  They usually get their `System` object from one of the higher-level objects in the app layer (like the Amber, CHARMM, or GROMACS parsers, or the OpenMM modeler itself).

So this issue could probably be largely addressed by adding the stricter unit tests only to the main integrators (VerletIntegrator, LangevinIntegrator, VariableLangevinIntegrator, and BrownianIntegrator; and maybe the Drude and Amoeba integrators).  This should be easy enough to add in the SWIG headers (we already add `stripUnits` that way). Doing "correct" unit checking for custom forces would be *much* harder, given that we wouldn't have any real way of knowing what the units should be in the first place...

Just a thought...

**Comment by swails** [comment]
Closing this.  The problem has a narrower scope than I originally thought and doing it *correctly* for custom forces or integrators is going to be borderline impossible.

Way too much work for not nearly enough gain.  I've only seen one person have this problem (and it will usually manifest in a crash, not subtly wrong answers, so good enough).

**Comment by jchodera** [comment]
I've had this problem too.  I think it might be worthwhile to open an issue suggesting we "Add unit dimensionality checking to Python OpenMM API".  Even if it is hard to do this for Custom*Force classes, I don't believe it is impossible or even a lot of work to implement something like the existing Python wrapper framework for assigning units to the return values of current OpenMM classes to add dimensionality checking for input values to most classes.  This would certainly help prevent people (myself included) from making mistakes that can often lead to long debugging times.  There is much value in that.
