### ISSUE TITLE
Tinyxml deserialization uses too much memory

### ISSUE THREAD

**Issue by mpharrigan** [pandegroup/openmm#793]
I've spoken with @peastman and @VijayPande about this already, but I figured I'd make a note of it here. For my 175k atom system, deserializing system.xml peaks at 2.7GB of ram usage. This is because the naive xml parser essentially stores 3 complete copies of the data. This is a problem for FAH and I could imagine it becoming a general problem as system sizes continue to increase. @peastman has suggested switching to a streaming xml parser.

**Comment by mpharrigan** [comment]
It looks like even switching to tinyxml-2 might help:

http://www.grinninglizard.com/tinyxml2/index.html

**Comment by peastman** [comment]
Based on a fairly quick web search, both of these look like good candidates:

XmlInspector: http://www.codeproject.com/Articles/587488/Streaming-XML-parser-in-Cplusplus
irrXML: http://www.ambiera.com/irrxml

Anyone have experience with either of those, or have suggestions for others?

**Comment by mpharrigan** [comment]
It looks like the first one uses some c++11 features

**Comment by jchodera** [comment]
What about highly portable, well-supported XML library like [Xerces C++](http://xerces.apache.org/xerces-c/)?

**Comment by peastman** [comment]
Xerces is a very big library and a lot more cumbersome to work with.  It also is distributed under a more restrictive license than most parts of OpenMM.  And all it adds are a lot of features that we don't need.

**Comment by peastman** [comment]
This is fixed by #804.
