### ISSUE TITLE
Add get_by_atomic_number() method to elements

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#796]
It would be really convenient to be able to retrieve an element from the list of defined elements by atomic number.

**Comment by rmcgibbo** [comment]
https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/element.py#L90-L92?

**Comment by jchodera** [comment]
Thanks!  Was looking at an old version of the API ref:
https://simtk.org/api_docs/openmm/api6_0/python/namespacesimtk_1_1openmm_1_1app_1_1element.html#aba4dcb6967f40915e77fe036ac7bfbf0
