### ISSUE TITLE
`createExceptionsFromBonds` and virtual sites

### ISSUE THREAD

**Issue by swails** [pandegroup/openmm#811]
In Amber topology files, virtual sites are connected by bonds to their parent atom, but not connected to anything else.  However, they are supposed to inherit their parents' exception rules (the most complex case being when 1-4 partners *each* have virtual sites, then there are 3 distinct 1-4 interactions: VS1--VS2, A1--VS2, and VS1--A2.

However, `NonbondedForce::createExceptionsFromBonds` does not respect this.  It gets TIP4P and TIP5P correct by fortuitous accident, but it gets some other things wrong (e.g., the GLYCAM06-EP force field that puts EPs in lots of places).

I'm not sure if this is intentional (or even how it would nominally be "fixed", given that that method doesn't take a `System` as input).  I just thought I'd bring it up as @jchodera got me thinking about extra points.

**Comment by jchodera** [comment]
Thanks for pointing this out, @swails!

Would simply adding an optional argument to `createExceptionsFromBonds` entitled `inhereitNonbondedExceptions` be sufficient to rectify this?

**Comment by swails** [comment]
> Would simply adding an optional argument to `createExceptionsFromBonds` entitled `inhereitNonbondedExceptions` be sufficient to rectify this?

No.  `createExceptionsFromBonds` would need to know about _where_ each of the virtual sites is.  (i.e., it has to know _which_ particles need to "inherit" exceptions from which other particles). This can only be done by either:

1. Passing in a `System` (yuck)
2. Passing in a vector of `VirtualSite` indices in addition to the bonds (probably not easy to support backwards-compatibility)

@peastman may know better than me here, but I don't think it's going to be easy to support `createExceptionsFromBonds` "Doing the Right Thing (TM)" wrt virtual sites.  I never actually use that function, anyway, since it's too inflexible for the Amber force field even without virtual sites.

I suspect the best thing to do here is simply document this particular shortcoming with the method and move on (doxygen? User's guide? both?).

And before someone suggests just fiddling with the passed bonds arrays to get the exceptions right, this simply _cannot_ get the 1-4 terms correct if there are any.

**Comment by peastman** [comment]
> And before someone suggests just fiddling with the passed bonds arrays to get the exceptions right, this simply cannot get the 1-4 terms correct if there are any.

What is it you can't get right that way?  If the virtual site is supposed to share its parent atom's exceptions, that just means it needs to have an identical set of bonds.  Any atom the parent is bonded to, the virtual site also should be bonded to.

Knowing that a particle is a virtual site doesn't tell you anything about what exceptions it should have.  It all depends on what it's being used to represent.  Consider two common uses of virtual sites:

1. To represent a charge center that is displaced from the atom position, like in TIP4P.  In this case, it should be treated as part of the parent atom, so it should have an identical set of exceptions.

2. To represent an immobilized hydrogen atom.  (Gromacs does this extensively.)  In this case, the fact that it's a virtual site should have no effect on its exceptions.  The connection to its parent atom should be treated as an ordinary bond.

ForceField can handle both of these cases, and it does both of them with createExceptionsFromBonds().

**Comment by swails** [comment]
What about this case, which occurs in one Amber force field (that I know about), but quite possibly future ones as well:

```
E1          E4
|           |
A1--A2--A3--A4
```

In this case, E1 inherits the 1-4 partners of A1 -- in this diagram that includes A4 *and* E4.  So the 1-4 partners here are: `(A1-A4), (A1-E4), (E1-A4), (E1-E4)`.  I see no way to do this by giving E1 all the same bonds as A1 -- it will still miss E4 as a 1-4 partner (since it will be 5 bonds away).  If you add a bond to bring that in range, you make A4 a 1-3 partner to E1 and exclude it completely...  Same problem applies for E4 and A4.

Am I missing something?

Admittedly this is a narrower corner case than I originally thought.

**Comment by swails** [comment]
> Am I missing something?

Duh, I'm missing something.  E4 is bonded to A3 also, so E1 and E4 are 1-4 partners.

OK, I'm satisfied... I wouldn't have thought to do that, but it quite clearly works.
