### ISSUE TITLE
Issue sweep in preparation for OpenMM 6.3 release

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#818]
I think we should use the issue tracker facility to tag issues as `bug`, `enhancement`, `documentation`, `cleanup`, etc., as well as the ability to label issues as targets for specific releases.

**Comment by swails** [comment]
Who has the proper "permissions" to mark issues?

**Comment by jchodera** [comment]
I think we would need to be added to the developer list to do that.

**Comment by jchodera** [comment]
Seems like this is happening.
