### ISSUE TITLE
git_revision not being included in simtk.openmm.version correctly for openmm-dev

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#835]
The `openmm-dev` conda package is not picking up the git revision:
```
>>> from simtk.openmm import version
>>> print version.version
6.2.0.dev-Unknown
```
The `Unknown` should be the git hash if `version.py` is working properly:
https://github.com/pandegroup/openmm/blob/master/wrappers/python/setup.py#L94-L106

It would be really useful to get this to work, because debugging issues with conda builds and pushes and dependencies is really hard without an accurate way to determine which version of each tool we have installed.

**Comment by jchodera** [comment]
I've confirmed that a manual build of OpenMM does indeed generate a `version.py` file containing `git_revision`:
```
[LSKI1497:openmm/openmm.simtk/python] choderaj% cat simtk/openmm/version.py 
git_revision = 'f816d961426b17b5d083de6d300e61960c5d5a29'
```
So perhaps the issue is due to the logic in `version.py` not working as intended when build from [`openmm/devtools/conda-recipe`](https://github.com/pandegroup/openmm/tree/master/devtools/conda-recipe)?

**Comment by peastman** [comment]
The git revision gets looked up by wrappers/python/CMakeLists.txt.  It assumes you're inside an actual git repository and runs git to find the version.  I suspect that travis runs it on some sort of an "export", a copy of the repository content that isn't itself actually a repository.

**Comment by jchodera** [comment]
I'm guessing this part of the conda recipe in `devtools/conda-recipe/` might be the problem:
https://github.com/pandegroup/openmm/blob/master/devtools/conda-recipe/build.sh#L26-L27
```
# Copy source to current directory.
cp -r $RECIPE_DIR/../.. .
```
Wild guess: This doesn't grab the git `.*` files if I understand correctly, so no git status information would be picked up.  Since we're using `bash`, we could add
```
shopt -s dotglob # for considering dot files (turn on dot files)
```
to have the `.*` files copied too.

**Comment by jchodera** [comment]
This was fixed!
