### ISSUE TITLE
Issue with Modeller trying to solvate a pdbfixer-generated PDB file

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#838]
`pdbfixer` is generating a PDB file that `Modeller` is having trouble solvating:
```
No template found for residue 430 (LYS).  The set of atoms is similar to NLYS, but it is missing 1 hydrogen atoms.
```
The code causing the error is:
```
forcefield = app.ForceField(ff_name+'.xml', water_name+'.xml') 
modeller = app.Modeller(fixer.topology, fixer.positions)
modeller.addSolvent(forcefield, padding=padding, model=water_name)
```
where `fixer` is a `PDBFixer` object.

Reading the PDBFixer-generated PDB file into a `PDBFile` and passing that to `modeller` instead doesn't help.

The problematic PDBFixer-generated file is here:
https://gist.github.com/jchodera/40d4ad0223c6d6924ff4

**Comment by peastman** [comment]
Could you post the PDB file you generated it from?  It looks like that residue has an extra atom (HXT).

**Comment by jchodera** [comment]
Sure!  Here you go:
https://gist.github.com/jchodera/2c852051feb3964a90ff

**Comment by jchodera** [comment]
The source file has that `HXT` atom as well:
```
ATOM  17202  HXT TRP B2549     -15.349 -13.754 -55.304  1.00  0.00           H                                                                                                                                                                                                                                                                          
```

**Comment by jchodera** [comment]
I have no idea what these `HXT` atoms are, but there are 3 of them and all have corresponding `CONECT` entries.  Schrödinger's Maestro must have added them for some reason.

**Comment by jchodera** [comment]
For now, I'll just remove them manually, but it would be good to establish if these are consistent with the PDB 3.0 spec.

**Comment by peastman** [comment]
HXT is generally the hydrogen attached to a terminal oxygen.  It looks to me like Maestro has messed up this file.  The residue in question *isn't* a terminal residue, but the residue numbering suggests it originally came just before a gap in the chain.  In the source file, it's residue 1814.  And the one immediately after it is residue 1867.  Sounds like a gap - but the SEQRES records don't list anything in between.  It lists them as being contiguous.  So I think Maestro

1. Saw this residue was just before a gap and decided to add a terminator to it.

2. Changed the SEQRES to exactly match the list of residues it was writing, thus hiding the fact that there had originally been a gap there!

**Comment by jchodera** [comment]
Right you are!  Maestro appears to have just "capped" these residues with protons and left the loop absent, thus creating a file that actually has multiple chains in it (without TER records).  Thanks for catching this.

**Comment by peastman** [comment]
Can this be closed?

**Comment by jchodera** [comment]
Sure---we've concluded that these are capped residues, and that having an inconsistent `SEQRES` block along with capped internal loops makes no sense.
