### ISSUE TITLE
[OT] Scientific Python Survey

### ISSUE THREAD

**Issue by swails** [pandegroup/openmm#840]
As we develop Python code for regular consumption in the Python community, I think it may be of interest to us what versions of which packages people are actually *using* (including Python).

The guy carrying out the survey posted on some mailing lists, but for those of you that didn't see it, here's the original message:

Hi everyone,

If you use scientific Python packages for your research/work, I would
appreciate if you could take a few minutes to fill out the following
survey:

  http://goo.gl/PXzFAk

The aim of this survey is to find out what versions of Python and
various scientific Python packages people are using, and how people
typically install packages, in order to determine how developers can
better meet the needs of the Scientific Python community (for example,
a common question is which version of Numpy need to be supported by
packages).

This is a follow-up to a similar survey which I did back in 2012 and
which provided very interesting results that you can read about here:

  http://astrofrog.github.io/blog/2013/01/13/what-python-installations-are-scientists-using

Please feel free to forward this survey to people in your own
scientific Python communities!

I will publish the results online in a few weeks.

Thanks!
Tom

The survey doesn't take long for those interested, and you can be notified of the results in a couple weeks when the data is processed.

**Comment by swails** [comment]
This doesn't need to be open still.

**Comment by jchodera** [comment]
For the platform question:  Which one is our "primary platform"?  Do you count by how much interactive human time we spend with them, or the number of instances running at any one time, since the answer will be different for each one.

**Comment by swails** [comment]
I approached that one as "which is most important to my work".  But you can put multiple platforms -- I put both my Mac and Linux.
