### ISSUE TITLE
Integrator freezes after creating multiple instances of openmm (about 8-10)

### ISSUE THREAD

**Issue by jhprinz** [pandegroup/openmm#846]
I was wondering if anyone encountered something like this:
For our openpathsampling python project (which uses openmm) I wrote a test for the storage framework that was at first a little inefficient and created a complete openmm simulation to create some frames for an Alanine Dipeptide system. There are about 8-10 tests that each create the objects, then only run 2 frames and then these frames are used in the test. When running the test on travis-ci in about one third of the cases openmm freezes when calling `simulation.step(...)` and then travis times out.
This never happened on my personal MacBook. So I assume that I possibly do not shut down correctly and free memory, etc or the system breaks because of insufficient equilibration, etc...

Anyway there is no error or exception thrown and it would be good to figure out what is going wrong here.

The test is found in 

https://github.com/choderalab/openpathsampling/blob/master/openpathsampling/tests/teststorage.py#L36-L57

and it freezes in the last line which calls

https://github.com/choderalab/openpathsampling/blob/master/openpathsampling/openmm_engine.py#L267

Any suggestions or advice?

**Comment by jchodera** [comment]
This may be unrelated, but I generally need to explicitly `del context` when finished with a `Context` object rather than wait for the Python garbage collection to clean things up, or else I end up with too many open `Context` objects.  This is generally only a problem for GPU simulations though.

**Comment by peastman** [comment]
Did you try John's suggestion of explicitly deleting contexts when you're done with them?

What Platform is OpenMM using for the tests?

**Comment by jhprinz** [comment]
Sorry, missed your reply. As I said, this never occurred  under MAC so far and I use 6.2.0 installed from conda and installed it before from source which also worked fine. The error only occurred so far only on travis under Linux
```
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04 LTS
Release:	12.04
Codename:	precise
Linux Version
2.6.32-042stab090.5
```

I changed the test not to use about 8 instances and we did not see the error again. I was mostly curious what could be the reason for it. Maybe even a memory problem on the travis machine?!?

**Comment by jchodera** [comment]
On travis, it would be using the CPU platform. Have you ever tried testing
this on one of our linux dev boxes?  I wonder if the travis VMs have some
way of restricting the total number of threads that can run at once.

**Comment by swails** [comment]
Lots of us use the CPU platform for our tests (including OpenMM's Travis tests for the `CustomGBForce` tests, since they are *way* too slow on `Reference`).  Two of my projects also use it.  And since Travis VMs launch with 1 virtual core, OMM uses only one CPU.

I suspect it's a memory issue.  I was having trouble with ParmEd loading too much stuff into memory.  When I looked at it on my own machine, it was hovering right around 1 GB of used RAM, so I suspect those are the limits that are getting blown here.  Sometimes tests would finish, other times it would say "... killed".  As soon as I reduced the memory requirements, the tests stopped failing.

**Comment by jhprinz** [comment]
My first guess would have also been a memory issue or general limitations of the VM in travis. And of course it is my fault, when I do not dispose of old OMMs correctly and they clutter the memory or the garbage collection misses something. I was just concerned that I could create all objects of OMM like the integrator, forcefields, etc. It only freezes when calling the step function where I would assume already all memory is reserved. It also does not fail or exit, the command just freezes. 

One other thought I had was that it would for some reason use the `Reference` implementation and it is just extremely slow and travis times out, but in all cases it used the `CPU` one.

I will try to investigate this a little more and keep you posted. So far the error is gone and my time is a little limited. Maybe a test that outputs system ressources and adding more and more OMM instances could help to see what is happening. Will let you know.

**Comment by jchodera** [comment]
@jhprinz can this be closed?

**Comment by jchodera** [comment]
@jhprinz can this be closed?

**Comment by jchodera** [comment]
@jhprinz: Can this be closed?

**Comment by jhprinz** [comment]
Will close this. No longer had the problem although I never figured out what was the reason.
