### ISSUE TITLE
CMAPTorsionForce does not have updateParametersInContext method.

### ISSUE THREAD

**Issue by jlmaccal** [pandegroup/openmm#853]
It's not possible to update the CMAP parameters for a system because `CMAPTorsionForce` lacks an `updateParametersInContext` method.

**Comment by peastman** [comment]
What aspects of the force do you need to be able to update?  Would the following be acceptable?  You can update:

1. The array of energy values for a map (but *not* the size of the array).

2. The map index to use for a given torsion.

You would not be able to change the list of particles for a torsion.  You also could not add new torsions or new maps.

**Comment by jlmaccal** [comment]
> What aspects of the force do you need to be able to update? Would the following be acceptable? You can update:
> 
> The array of energy values for a map (but not the size of the array).
> 
> The map index to use for a given torsion.
> 
> You would not be able to change the list of particles for a torsion. You also could not add new torsions or new maps.
> 
> 

Ideally, you would be able to update all of that — similar to how you can update all of the parameters for HarmonicBondForce, as an example.

But, at a minimum, it should be possible to update the two things that you mention.

**Comment by peastman** [comment]
What I described is pretty similar to how HarmonicBondForce works.  It doesn't let you add new bonds, or change the set of particles in a bond.  This has to do with minimizing the set of data structures that need to be recomputed, and if at all possible avoiding having to do new memory allocation on the GPU.

Just to confirm: if I implement it as described above, that will satisfy your requirements?  The implementation can always be extended in the future if someone else has a need for more.

**Comment by jlmaccal** [comment]
Yes, that would be sufficient.

**Comment by peastman** [comment]
#854 adds this.
