### ISSUE TITLE
Behavior of app.HAngles for amber prmtop

### ISSUE THREAD

**Issue by kyleabeauchamp** [pandegroup/openmm#855]
I'm currently using an automated pipeline to simulate various neat liquids parameterized in GAFF.  I'm using the prmtop reader to set up these simulations.  

One of my target molecules is a GAFF-like water model.  Although such a model is not useful for predicting biophysical properties, it's still useful as a unit test for my pipeline code.  

My question is this: I would like to switch my GAFF water model into a rigid model.  From my reading of the OpenMM manual ("The lengths of all bonds are constrained. In addition, all angles of the form H-X-H or H-O-X (where X is an arbitrary atom) are constrained."), this is as simple as switching the constraint flag from HBonds to HAngles.  

As a test of this, consider the script below, which compares the system objects for the two different pipelines.  I would expect the number of angles and constraints to change when the constraint type is switched to HAngles, but no such change occurs.  

```
from simtk.openmm import app
import simtk.openmm as mm
from simtk import unit as u

for constraints in [app.HBonds, app.HAngles]:
    for prmtop_filename in ["./water-box-216.prmtop", "./14314-42-2_1000_303.2.prmtop"]:
        prmtop = app.AmberPrmtopFile(prmtop_filename)
        system = prmtop.createSystem(nonbondedMethod=app.PME, nonbondedCutoff=1.0 * u.nanometers, constraints=constraints)
        print("**********")
        print("filename = %(filename)s constraints = %(constraint_type)s" % dict(filename=prmtop_filename, constraint_type = constraints))
        for k, atom in enumerate(prmtop.topology.atoms()):
            if k < 3:
                print(atom.name, atom.element)        
        output = "particles = %(n_particles)d, bonds = %(n_bonds)d, angles = %(n_angles)d, constraints = %(n_constraints)d" % dict(
            n_particles = system.getNumParticles(),
            n_bonds = system.getForce(0).getNumBonds(),
            n_angles = system.getForce(1).getNumAngles(),
            n_constraints = system.getNumConstraints())
        print(output)
```

```
**********
filename = ./water-box-216.prmtop constraints = HBonds
('O', <Element oxygen>)
('H1', <Element hydrogen>)
('H2', <Element hydrogen>)
particles = 648, bonds = 0, angles = 0, constraints = 648
**********
filename = ./14314-42-2_1000_303.2.prmtop constraints = HBonds
('O1', <Element oxygen>)
('H1', <Element hydrogen>)
('H2', <Element hydrogen>)
particles = 3000, bonds = 0, angles = 1000, constraints = 2000
**********
filename = ./water-box-216.prmtop constraints = HAngles
('O', <Element oxygen>)
('H1', <Element hydrogen>)
('H2', <Element hydrogen>)
particles = 648, bonds = 0, angles = 0, constraints = 648
**********
filename = ./14314-42-2_1000_303.2.prmtop constraints = HAngles
('O1', <Element oxygen>)
('H1', <Element hydrogen>)
('H2', <Element hydrogen>)
particles = 3000, bonds = 0, angles = 1000, constraints = 2000
```

**Comment by peastman** [comment]
Are you sure it isn't already rigid?  That's the default behavior unless you specify rigidWater=False.  Also notice that for water-box-216, the number of constraints equals the number of particles.  That's what you expect for rigid water.

**Comment by kyleabeauchamp** [comment]
Look at the output for 14314-42-2_1000_303.2.prmtop constraints = HAngles.  The number of constraints does not equal the number of particles.

**Comment by swails** [comment]
Can you post the offending prmtop file in a gist somewhere that I can take a look?

**Comment by kyleabeauchamp** [comment]
https://github.com/kyleabeauchamp/openmm/blob/prmtop/wrappers/python/tests/systems/14314-42-2_1000_303.2.prmtop

https://github.com/kyleabeauchamp/openmm/blob/prmtop/wrappers/python/tests/systems/14314-42-2_1000_303.2_equil.pdb

**Comment by peastman** [comment]
The residue name is wrong.  Water is supposed to be called HOH, not MOL.

**Comment by kyleabeauchamp** [comment]
But that shouldn't matter, the elements are still HXH, right?

**Comment by swails** [comment]
HOH is really no different than MOL in an Amber prmtop file.  The main water name is `'WAT'` -- https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/internal/amber_file_parser.py#L742 with some other names working as well.

**Comment by jchodera** [comment]
What if we changed the logic to detect waters by elemental composition?

Also, something strikes me as weird: We generally want to use `app.HBonds` but with rigid waters (for SETTLE) if the `rigidWater` flag is specified.  But shouldn't `app.HBonds` always enforce any H-X-H angle constraints regardless of the residue name?

**Comment by swails** [comment]
> But shouldn't app.HBonds always enforce any H-X-H angle constraints regardless of the residue name?

It doesn't in Amber...

**Comment by jchodera** [comment]
Whoops, I meant `app.HAngles` for the second one.

**Comment by swails** [comment]
Oh.  Then yes.  And the code *should* be doing that.  See https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/internal/amber_file_parser.py#L769-L800 (it's a bit involved for something so seemingly 'simple').

I will look into what's happening tomorrow, because ParmEd is doing the same thing.

**Comment by swails** [comment]
I found the problem.  The line:

```
            numH = len([type for type in (type1, type3) if type.startswith('H')])
```
is what is used to determine how many hydrogens were in that angle.  However, it pulls the atom *type* name rather than the atom name itself.  Since you're using GAFF atom types, the atom type name is `'ho'`.  The lower-case 'h' does not match the upper-case 'H' in `startswith('H')`.

As a temporary workaround, you can change the above line to:

```
numH = len([type for type in (type1, type3) if type.upper().startswith('H')])
```

However, there are better ways of doing this (atom names are far more reliable than types, and the topology file typically has atomic number information stored inside it now, which is a far superior approach to finding the number of hydrogens than looking at atom names.

The bug in ParmEd that yielded the same behavior was easier to find and fix.  So you can either use the ParmEd `AmberParm` class in ~20 minutes when Travis finishes and I merge the PR, implement the quick fix above, or wait for my PR to OMM sometime tomorrow.

**Comment by kyleabeauchamp** [comment]
thanks!
