### ISSUE TITLE
Test failures on cuda 7?

### ISSUE THREAD

**Issue by kyleabeauchamp** [pandegroup/openmm#859]
I recently updated one of my Ubuntu 12.04 boxes to cuda 7, which was as simple as `sudo apt-get dist-upgrade`.  I'm finding some test failures, documented below.  I cannot guarantee that the tests were all working on this machine before the update, however.

```
make test

97% tests passed, 7 tests failed out of 245

Total Test time (real) = 3447.77 sec

The following tests FAILED:
        133 - TestCudaNonbondedForceSingle (Failed)
        134 - TestCudaNonbondedForceMixed (Failed)
        135 - TestCudaNonbondedForceDouble (Failed)
        136 - TestCudaEwaldSingle (Failed)
        137 - TestCudaEwaldMixed (Failed)
        138 - TestCudaEwaldDouble (Failed)
        195 - TestCudaRpmdSingle (Failed)
Errors while running CTest
make: *** [test] Error 8
kyleb@csk:~/src/openmm/omm-build$ ./TestCudaEwald
exception: Assertion failure at TestCudaEwald.cpp:148.   Expected [-198.058, -224.745, -102.259], found [2.14748e+09, 2.14748e+09, 2.14748e+09]
kyleb@csk:~/src/openmm/omm-build$ ./TestCudaRpmd 
Done
kyleb@csk:~/src/openmm/omm-build$ ./TestCudaNonbondedForce 
exception: Assertion failure at TestCudaNonbondedForce.cpp:851.  Expected 40209.4, found 40198.7
kyleb@csk:~/src/openmm/omm-build$ nvidia-smi 
Thu Mar 19 17:59:50 2015       
+------------------------------------------------------+                       
| NVIDIA-SMI 346.46     Driver Version: 346.46         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 780     Off  | 0000:03:00.0     N/A |                  N/A |
| 26%   41C    P0    N/A /  N/A |     11MiB /  3071MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TITAN   Off  | 0000:83:00.0     Off |                  N/A |
| 35%   45C    P0    26W / 250W |     15MiB /  6143MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0            C+G   Not Supported                                         |
+-----------------------------------------------------------------------------+
```

**Comment by jchodera** [comment]
I'm also having trouble with CUDA 7.0 with driver 346.46 on Linux CentOS (our cluster) with GTX-680s.

Trying to import `simtk.openmm` gives only three platforms:
```
[chodera@gpu-3-9 benchmark]$ setenv OPENMM_CUDA_COMPILER `which nvcc`
[chodera@gpu-3-9 benchmark]$ python
Python 2.7.9 |Continuum Analytics, Inc.| (default, Mar  9 2015, 16:20:48) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import simtk.openmm as mm
>>> print mm.Platform.getNumPlatforms()  
3
>>> platforms = [ mm.Platform.getPlatform(index).getName() for index in range(mm.Platform.getNumPlatforms()) ]
>>> print platforms
['Reference', 'CPU', 'OpenCL']
```
Here is the output of nvidia-smi:
```
[chodera@gpu-3-9 benchmark]$ nvidia-smi
Thu Mar 19 18:20:42 2015       
+------------------------------------------------------+                       
| NVIDIA-SMI 346.46     Driver Version: 346.46         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 680     Off  | 0000:03:00.0     N/A |                  N/A |
| 30%   31C    P8    N/A /  N/A |     10MiB /  4095MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 680     Off  | 0000:04:00.0     N/A |                  N/A |
| 30%   30C    P8    N/A /  N/A |     10MiB /  4095MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 680     Off  | 0000:83:00.0     N/A |                  N/A |
| 30%   33C    P8    N/A /  N/A |     10MiB /  4095MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 680     Off  | 0000:84:00.0     N/A |                  N/A |
| 30%   32C    P8    N/A /  N/A |     10MiB /  4095MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0            C+G   Not Supported                                         |
|    1            C+G   Not Supported                                         |
|    2            C+G   Not Supported                                         |
|    3            C+G   Not Supported                                         |
+-----------------------------------------------------------------------------+
```

**Comment by jchodera** [comment]
Doesn't appear to be the driver, but instead `nvcc`. When I switch back to `nvcc` 6.5 on this system (with driver 346.46) things work fine:
```
[chodera@gpu-3-9 ~]$ module remove cuda/7.0
[chodera@gpu-3-9 ~]$ module add cuda/6.5
[chodera@gpu-3-9 ~]$ python
Python 2.7.9 |Continuum Analytics, Inc.| (default, Mar  9 2015, 16:20:48) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import simtk.openmm as mm
>>> print mm.Platform.getNumPlatforms()
4
```

**Comment by swails** [comment]
@jchodera -- did you recompile?  If you switch CUDA installations and don't recompile OpenMM, it won't work (that's why the OpenMM binary installation instructions tell you a specific CUDA version you need to have installed).

I recently encountered the same thing when jumping from CUDA 5.5 to CUDA 6.5 -- recompiling OpenMM made the CUDA platform available again.

**Comment by swails** [comment]
@kyleabeauchamp -- is this *with* or *without* the CUDA Compiler plugin? (look for `OPENMM_BUILD_CUDA_COMPILER_PLUGIN` inside `CMakeCache.txt`)

**Comment by jchodera** [comment]
@swails: I used the conda release package that was built with CUDA 6.5, I believe.  The CUDA platform fails when using nvcc 7.0 with the new driver (required for CUDA 7.0) on linux, but works fine when nvcc 6.5 is used instead.  OpenCL works fine on both.

**Comment by kyleabeauchamp** [comment]
kyleb@csk:~/src/openmm/omm-build$ grep OPENMM_BUILD_CUDA_COMPILER_PLUGIN CMakeCache.txt 
OPENMM_BUILD_CUDA_COMPILER_PLUGIN:BOOL=ON

**Comment by swails** [comment]
@jchodera -- if you use precompiled binaries and *don't* use the CUDA compiler that built those libraries, I don't think the CUDA platform will ever be available.  This is unrelated to CUDA 7, specifically (you'd see the same thing if you tried using CUDA 6.0).

@kyleabeauchamp -- it would be interesting to know if the CUDA tests work when you set that to OFF.

**Comment by jchodera** [comment]
@swails: Maybe I'm misunderstanding, but the libraries are *not* built by the CUDA compiler.  The CUDA compiler is used *at runtime* to compile dynamically generated CUDA kernels.

**Comment by kyleabeauchamp** [comment]
Regardless, I still see failures regardless of the value of that cmake flagk.

**Comment by jchodera** [comment]
What I suspect is happening is that some of the libraries shipped with CUDA 7.0 are not compatible with the `plugins/libOpenMMCUDA.so` compiled against the libraries shipped with CUDA 6.5.

**Comment by swails** [comment]
> @swails: Maybe I'm misunderstanding, but the libraries are not built by the CUDA compiler. The CUDA compiler is used at runtime to compile dynamically generated CUDA kernels.

I think you're misunderstanding.  I believe that the libraries *are* built at compile-time.  The *kernels* are built at runtime, but there are still CUDA symbols in `libOpenMMCUDA.so`, so you still need to have that version of CUDA's lib directory visible to `ld` at runtime.

You can check this with `ldd`:

```
swails@batman /usr/local/openmm/6.1/openmm/lib/plugins $ ldd libOpenMMCUDA.so 
ldd: warning: you do not have execution permission for `./libOpenMMCUDA.so'
	linux-vdso.so.1 (0x00007fff1ece0000)
	libOpenMM.so => /usr/local/openmm/dev/openmm/lib/libOpenMM.so (0x00007f299fbe8000)
	libcuda.so.1 => /usr/lib64/libcuda.so.1 (0x00007f299ec30000)
	libcufft.so.6.0 => not found
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f299ea10000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f299e808000)
	libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.1/libstdc++.so.6 (0x00007f299e4f0000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f299e1e8000)
	libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.1/libgcc_s.so.1 (0x00007f299dfd0000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f299dc28000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f299da20000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f29a04a0000)
```

Note for this installation of OpenMM (which depends on `libcufft.so.6.0`, I won't be able to load this plugin since that lib can't be found).  Once I switch to CUDA 6.0:

```
swails@batman /usr/local/openmm/6.1/openmm/lib/plugins $ module swap cuda/6.5 cuda/6.0
swails@batman /usr/local/openmm/6.1/openmm/lib/plugins $ ldd libOpenMMCUDA.so
ldd: warning: you do not have execution permission for `./libOpenMMCUDA.so'
	linux-vdso.so.1 (0x00007fff4a160000)
	libOpenMM.so => /usr/local/openmm/dev/openmm/lib/libOpenMM.so (0x00007f8ae0380000)
	libcuda.so.1 => /usr/lib64/libcuda.so.1 (0x00007f8adf3c8000)
	libcufft.so.6.0 => /opt/cuda/6.0/lib64/libcufft.so.6.0 (0x00007f8add198000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f8adcf78000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f8adcd70000)
	libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.1/libstdc++.so.6 (0x00007f8adca58000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f8adc750000)
	libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.1/libgcc_s.so.1 (0x00007f8adc538000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f8adc190000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f8adbf88000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8ae0c38000)
```

Bam, `libcufft.so.6.0` is resolved (the CUDA 6.0 modulefile adds the CUDA libs to `LD_LIBRARY_PATH`) and that platform can be loaded.

**Comment by swails** [comment]
Also, the runtime build of the CUDA kernels is an implementation detail -- not something you can routinely rely on.  Indeed, as @peastman has said, once the runtime optimizer in the CUDA compiler is available in all "legacy" CUDA compilers we plan to support (several years from now?) the runtime compile step will likely be abandoned and the CUDA compiler plugin will be rolled into the core CUDA platform.

**Comment by swails** [comment]
@kyleabeauchamp -- I'm also seeing problems with CUDA 7.0 on my GTX 680 (Driver 340.76 -- the newest I can install while still supporting my display-driving, ancient GTS 250 :))

**Comment by jchodera** [comment]
> I think you're misunderstanding. I believe that the libraries are built at compile-time. The kernels are built at runtime, but there are still CUDA symbols in libOpenMMCUDA.so, so you still need to have that version of CUDA's lib directory visible to ld at runtime.

I believe that's correct, but it doesn't use the CUDA compiler (`nvcc`) to build those libraries.

**Comment by jchodera** [comment]
So I think we're all on the same page here.  To use the OpenMM distro (conda or binary) compiled against the CUDA 6.5 distribution, you need to have the CUDA 6.5 distribution installed.

The next questions are:
* What is going on with Kyle's recompilation of OpenMM against CUDA 7.0 where the tests fail?
* Would OpenMM compiled against CUDA 7.0 be backwards-compatible and work on machines with only CUDA 6.5 installed?

**Comment by swails** [comment]
> Would OpenMM compiled against CUDA 7.0 be backwards-compatible and work on machines with only CUDA 6.5 installed?

So I'll try to disentangle some things I think we're conflating here.  The problem is that `libOpenMMCUDA.so` links against several CUDA libraries -- `libcuda.so` and `libcufft.so`.  They link against specific versions of these libraries.  It really doesn't matter which *compiler* we use to build the kernels at runtime (nvcc 6? nvcc 7? clang++ 3.5? ... etc), or which compiler we used to build OpenMM to begin with, what *really* matters is whether or not the libraries that were used at link time are available at runtime (since they're shared libs, not static libs).

You can set up your environment to use the CUDA 7 compiler and link against the CUDA 6.5 libraries -- in this case you can get the 6.5-compiled OpenMM conda package to work with your CUDA 7 compiler (I think).  But each CUDA toolkit comes with a complete set of CUDA libs.  As a result, if you install CUDA 6, you can be *sure* that libcufft.so.6 will be available.  That doesn't *stop* you from linking against libcufft.so.7 (and @peastman did as much himself in #747 when he mixed-and-matched compiler and library versions in the tests he ran).

It's just easier to say "use the same CUDA we used" than all of that ^^^^

**Comment by swails** [comment]
> What is going on with Kyle's recompilation of OpenMM against CUDA 7.0 where the tests fail?

A bug of some sort.  I'm getting segfaults and failures myself with CUDA 7 -- I'll post the results when the tests are done (with both the CUDA compiler plugin on and off)

**Comment by peastman** [comment]
> You can set up your environment to use the CUDA 7 compiler and link against the CUDA 6.5 libraries -- in this case you can get the 6.5-compiled OpenMM conda package to work with your CUDA 7 compiler (I think).

It's possible that would work, but I wouldn't be surprised if it didn't.  The PTX instruction set evolves with time, and the CUDA 7 nvcc could easily generate instructions that CUDA 6.5 doesn't know how to interpret.

**Comment by swails** [comment]
> It's possible that would work, but I wouldn't be surprised if it didn't. The PTX instruction set evolves with time, and the CUDA 7 nvcc could easily generate instructions that CUDA 6.5 doesn't know how to interpret.

I thought that would be more hardware-defined than nvcc-defined (i.e., if you compile for SM 3.0, then nvcc only uses instructions supported by that architecture).  In any case, that's why I said "I think" :).

It's easier/safer to just talk about "CUDA" version requirements as encompassing both the libs and the compiler, but the actual requirements are imposed by libs linked to `libOpenMMCUDA.so`, not compiler versions (which are always from the same version as the compiler used to build OpenMM in the binaries we distribute because any other choice would be... well, crazy).

**Comment by jchodera** [comment]
Here's another idea: If `libOpenMMCUDA.so` is tied to a *specific* version of CUDA (6.5 or 7.0) and is not forwards- or backwards-compatible in any way, could we include multiple versions (`libOpenMMCUDA-6.5.so` and `libOpenMMCUDA-7.0.so`) in the binary and conda distributions?

**Comment by jchodera** [comment]
Alternatively, can we drop CUDA 6.5 support entirely (after figuring out bugs, if they exist)?

**Comment by swails** [comment]
Here's what I get on my machine with a GTX 680 using CUDA 7:

```
97% tests passed, 11 tests failed out of 374

Total Test time (real) = 4028.69 sec

The following tests FAILED:
	 70 - TestCudaNonbondedForceSingle (SEGFAULT)
	 71 - TestCudaNonbondedForceMixed (SEGFAULT)
	 72 - TestCudaNonbondedForceDouble (SEGFAULT)
	103 - TestCudaEwaldSingle (SEGFAULT)
	104 - TestCudaEwaldMixed (SEGFAULT)
	105 - TestCudaEwaldDouble (SEGFAULT)
	125 - TestCudaLocalEnergyMinimizerMixed (Failed)
	266 - TestCudaAmoebaMultipoleForceSingle (SEGFAULT)
	267 - TestCudaAmoebaMultipoleForceMixed (SEGFAULT)
	268 - TestCudaAmoebaMultipoleForceDouble (SEGFAULT)
	341 - TestCudaCompiler (Failed)
```

This is with the CUDA compiler plugin *on*.  I'll try with it off shortly

**Comment by peastman** [comment]
Sigh.  I just sent off a frantic email to NVIDIA.  If I've diagnosed the problem correctly, cufftSetStream() is broken in CUDA 7, which means that a whole lot of CUDA programs have just stopped working correctly.  I'll post back when I have more information.

**Comment by kyleabeauchamp** [comment]
Thanks Peter!

**Comment by jchodera** [comment]
Just wondering if @peastman has any updates on the potential CUDA 7 bug to share.

**Comment by peastman** [comment]
They say they have it fixed internally and it should be getting released soon.  But I have no insight on what "soon" means!

**Comment by jchodera** [comment]
Thanks for the heads-up!  Let us know as you find out more.

**Comment by ppxasjsm** [comment]
Wish I had read this before wasting 2 hours on CUDA 7. No news I guess?

**Comment by peastman** [comment]
Let me bug them again.

**Comment by rmcgibbo** [comment]
The notice is still being shown on https://developer.nvidia.com/cuda-downloads

**Comment by jchodera** [comment]
I hadn't seen that notice before.

I don't suppose there is a temporary workaround possible where FFT input less than the minimum size can be padded with zeros if CUDA7 is detected?

**Comment by peastman** [comment]
I'm about ready to give up on them.  We've been waiting over two months for them to fix the problem.  This is just getting ridiculous.  Even if they issued a fix today, we would still have to deal with tons of systems where people have installed the broken version over the past few months.

I suggest we 1) disable streams when using CUDA 7, 2) move forward with the 6.3 release, building against CUDA 6.5, and 3) very strongly try to discourage people from using CUDA 7.  This means that if anyone does use CUDA 7, there will be a significant performance hit.  It also means we can't include the new runtime compilation feature.  But we can't keep waiting around forever.

**Comment by kyleabeauchamp** [comment]
Sounds reasonable to me.

**Comment by jchodera** [comment]
Do any of us known Jen-Hsun well enough to push for at least an ETA?  I imagine that OpenMM isn't the only one with this PME problem---Ross Walker must have the same issues as well.

**Comment by swails** [comment]
I don't think pmemd.cuda uses FFT streams for the recip calc.

**Comment by jchodera** [comment]
Ah, got it.

**Comment by swails** [comment]
@peastman -- agreed.  There's still one or two commits I want to make to the Gromacs parsers before release, though.  Do you have a timeline for when I would need to get those PRs in by?

**Comment by peastman** [comment]
No fixed timeline.  How long do you need?

**Comment by swails** [comment]
To determine when unsupported features are hit and raise an exception, a day or two.  To actually add support for them, longer (not entirely sure).

**Comment by jchodera** [comment]
Maybe we can use this time to do a sweep of open PRs and open issues?

**Comment by swails** [comment]
I added a quick bandaid in #930.  That's better than nothing (Gromacs parsers were never handling virtual sites).  I think there's also the issue that the `[ nonbond_params ]` section is currently ignored, which contains NBFIX information, I *believe*.  This is quite a bit more subtle, but don't have an easy check for it yet.

**Comment by kyleabeauchamp** [comment]
So I think I can close this issue.  I installed the latest git OpenMM revision on our CUDA 7 box and all the CUDA tests are running fine now.  

Summary: there will be severe performance penalties on CUDA7 until NVIDIA fixes the streaming FFT bug, but things should at least be working for now.

**Comment by peastman** [comment]
Guess what?  They just posted their fix!  Unfortunately, it's a completely unsatisfactory fix.  First, they didn't actually update any of their installers.  They just posted a separate patch (that most people probably won't even see) that needs to be installed separately.  And second, as far as I can tell there's no way to determine programmatically whether the patch is installed.  Which is really upsetting given that I pointed this problem out to them several weeks ago when they first asked me to verify the fix, and emphasized at the time that they needed to update the version number.

Sigh.  This is depressing.

**Comment by swails** [comment]
Yuck.  My vote here is to keep the current approach (i.e., disable streams on CUDA 7), but add a note that shows people how to re-activate streams after they apply the patch for the 'power users' that want to get the most out of their CUDA 7.

And still build the binaries with CUDA 6.5.

At least that's my 2c
