### ISSUE TITLE
More unit strangeness

### ISSUE THREAD

**Issue by kyleabeauchamp** [pandegroup/openmm#862]
Here's a strange example where mixing numpy and python floats leads to some strange behavior IMHO:

```
import numpy as np
import simtk.unit as u

q = u.elementary_charge
tip3p_mu = q * np.float64(1.0)

empirical_conversion = 1.0 / tip3p_mu

x0 = float(1.0) * empirical_conversion
x1 = np.float64(1.0) * empirical_conversion

print x0
print x1
print type(x0)
print type(x1)

```

```
1.0 /e
1.0
<class 'simtk.unit.quantity.Quantity'>
<type 'numpy.float64'>
```

Anyone have any thoughts here?  The original use case for this involved some `np.sum()` operations that eventually led to units disappearing.

**Comment by rmcgibbo** [comment]
From http://stackoverflow.com/a/5182501/1079728, when you run `x0 = float(1.0) * empirical_conversion` or  `x1 = np.float64(1.0) * empirical_conversion`, the first thing that happens is that the left object's `__mull__()` gets called. If it doesn't have one, or it raise `NotImplemented`,  then the right object's `__rmull__()` gets called.

```
In [100]: np.float64(1.0).__mul__(u.Quantity(value=np.float64(1.0), unit=1/u.elementary_charge))
Out[100]: 1.0
```

```
In [101]: float(1.0).__mul__(u.Quantity(value=np.float64(1.0), unit=1/u.elementary_charge))
Out[101]: NotImplemented
```

**Comment by rmcgibbo** [comment]
All of this, in both cpython and numpy, is implemented in C, so it's a bit of a mess to figure out.

**Comment by peastman** [comment]
It's actually very simple, though I don't think there's any really good solution.  Numpy and OpenMM are both trying to overload the * operator.  When that happens, whichever object is on the left takes precedence.  If you multiply an ordinary float by a Quantity, the Quantity gets to perform the multiplication.  But if you multiply a Numpy float64 by a Quantity, the Quantity only gets to do it if it happens to be on the left.

**Comment by rmcgibbo** [comment]
That's true, but it's more complex than that because of the way that numpy implements `__mul__`.

```
In [283]: np.float64(1.0).__mul__(u.Quantity(value=np.float64(1.0), unit=1/u.elementary_charge))
Out[283]: 1.0

In [284]: np.float64(1.0).__mul__(u.Quantity(value=float(1.0), unit=1/u.elementary_charge))
Out[284]: Quantity(value=1.0, unit=/elementary charge)
```

**Comment by peastman** [comment]
I believe this was fixed by #972.  Can you confirm that?

**Comment by kyleabeauchamp** [comment]
Will check tonight after business hours

**Comment by kyleabeauchamp** [comment]
LGTM, below are results after latest git:

```
In [8]: print x0
1.0 /e

In [9]: print x1
1.0 /e

In [10]: print type(x0)
<class 'simtk.unit.quantity.Quantity'>

In [11]: print type(x1)
<class 'simtk.unit.quantity.Quantity'>
```
