### ISSUE TITLE
HAngles Constraints for Alanine Dipeptide on CPU?

### ISSUE THREAD

**Issue by kyleabeauchamp** [pandegroup/openmm#863]
I'm finding that the Alanine dipeptide example fails when the CPU platform is combined with HAngles constraints.  Things seem to work OK with CUDA.  Drive code below:

```
from __future__ import print_function
from simtk.openmm import app
import simtk.openmm as mm
from simtk import unit
from sys import stdout

pdb_filename = "/home/kyleb/src/openmm/openmm/wrappers/python/tests/systems/alanine-dipeptide-implicit.pdb"
prmtop_filename = "/home/kyleb/src/openmm/openmm/wrappers/python/tests/systems/alanine-dipeptide-implicit.prmtop"

pdb = app.PDBFile(pdb_filename)
prmtop = app.AmberPrmtopFile(prmtop_filename)

system = prmtop.createSystem(nonbondedMethod=app.NoCutoff, constraints=app.HAngles)
integrator = mm.LangevinIntegrator(300*unit.kelvin, 1.0/unit.picoseconds, 0.1*unit.femtoseconds)

platform = mm.Platform_getPlatformByName("CPU")
simulation = app.Simulation(pdb.topology, system, integrator, platform)
simulation.context.setPositions(pdb.positions)

print('Minimizing...')
simulation.minimizeEnergy()

simulation.context.setVelocitiesToTemperature(300*unit.kelvin)
print('Equilibrating...')
simulation.step(100)

simulation.reporters.append(app.PDBReporter('trajectory.pdb', 1000))
simulation.reporters.append(app.StateDataReporter(stdout, 1000, step=True, potentialEnergy=True, temperature=True, progress=True, remainingTime=True, speed=True, totalSteps=1000, separator='\t'))

print('Running Production...')
simulation.step(10000)
print('Done!')
```

Output:

```
In [16]: simulation.minimizeEnergy()
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-16-27daeb7478f1> in <module>()
----> 1 simulation.minimizeEnergy()

/home/kyleb/opt/lib/python2.7/site-packages/simtk/openmm/app/simulation.pyc in minimizeEnergy(self, tolerance, maxIterations)
     87            until the results converge without regard to how many iterations it takes.
     88         """
---> 89         mm.LocalEnergyMinimizer.minimize(self.context, tolerance, maxIterations)
     90 
     91     def step(self, steps):

/home/kyleb/opt/lib/python2.7/site-packages/simtk/openmm/openmm.pyc in minimize(*args)
   9042 
   9043 
-> 9044         return _openmm.LocalEnergyMinimizer_minimize(*args)
   9045 
   9046     if _newclass:minimize = staticmethod(minimize)

Exception: Particle coordinate is nan
```

**Comment by kyleabeauchamp** [comment]
One more piece of info: CPU platform works with HBonds or AllBonds, just not HAngles.

**Comment by swails** [comment]
Does it work with any of the other platforms?  Also, what if you use ParmEd's `AmberParm`?

**Comment by kyleabeauchamp** [comment]
Cudas works, reference is too slow to tell

**Comment by peastman** [comment]
I can't reproduce this.  It works fine for me.  There are a lot of potentially non-deterministic behaviors in energy minimization, so I suspect it's one of those that causes it to fail on some computers but not on others.

It general, constrained minimization is really hard, and the more constraints you have, the harder it becomes.  Some MD programs (e.g. Gromacs) won't even attempt it.  If you tell it to minimize a constrained system, it just fails with an error telling you to remove the constraints.  OpenMM takes its best shot at it, and often succeeds, but it's not robust.

**Comment by kyleabeauchamp** [comment]
I guess my concern is that this is a pretty "standard" pipeline--I copy pasted this script from the OpenMM builder and edited the input file to use the alanine dipeptide file from our test suite.  

I suppose we can wait to see whether other people can reproduce.  

@swails I see the same error when I swap out `chemistry.load_file()` for the prmtop reader.

**Comment by peastman** [comment]
I wouldn't describe HAngles constraints as "standard".  It's pretty rarely used, especially now that we support mass repartitioning which is usually a better way of accomplishing the same goals.

**Comment by kyleabeauchamp** [comment]
Well, I didn't know that and I would say I'm in the top 4% of OpenMM power users.

**Comment by swails** [comment]
To my knowledge, people still need constraints with HMR (to use, for instance, a 4 fs timestep).  I've never used `HAngles` myself because Amber really only has the equivalent of `HBonds`, but I wouldn't have intuitively expected it to be an exclusive option with HMR.

That said, the NaN is still suspicious to me...

**Comment by peastman** [comment]
You only need AllBonds constraints in that case, not HAngles.  That's somewhat easier on the minimizer.

I should explain how LocalEnergyMinimizer handles constraints.  It doesn't actually implement a constrained minimization algorithm.  Those tend to be very complicated and hard to make work reliably.  Instead, it adds harmonic restraints to all the constrained distances and does an ordinary minimization.  It then checks to see if all the constraints are satisfied to within the tolerance.  If they aren't, it increases the strength of the restraints and tries again.  This often works, but as I said it isn't robust.  For example, if the harmonic restraints get too strong, that could easily lead to the minimizer blowing up and producing nans.

**Comment by jchodera** [comment]
I can confirm that the `AllBonds` example works fine on my MacBook Air on `CPU`:
```
[LSKI1497:openmm/openmm-tests/hangles] choderaj% python test-hangles.py
Minimizing...
Equilibrating...
Running Production...
#"Progress (%)"	"Step"	"Potential Energy (kJ/mole)"	"Temperature (K)"	"Speed (ns/day)"	"Time Remaining"
100.0%	1000	-87.6284499396	151.191926313	0	--
200.0%	2000	-102.694225118	232.806706335	31.2	0:00
300.0%	3000	-92.0307012722	207.530134329	34.1	0:00
400.0%	4000	-82.4511037343	206.095385226	33.8	0:00
500.0%	5000	-92.6501318307	334.301311385	33.4	23:59:59
600.0%	6000	-83.5231287138	239.540229261	33.3	23:59:59
700.0%	7000	-84.8812550308	299.823101024	33.7	23:59:59
800.0%	8000	-90.3530217581	332.06163811	33.8	23:59:59
900.0%	9000	-84.5807460486	278.199794959	33.8	23:59:58
1000.0%	10000	-71.8241589653	181.063184869	33.5	23:59:58
Done!
```

**Comment by jchodera** [comment]
On the topic of HMR, is there a "canonical" way to do HMR with OpenMM?

**Comment by peastman** [comment]
Specify hydrogenMass when you call createSystem().

**Comment by jchodera** [comment]
Thanks!

**Comment by jchodera** [comment]
> You only need AllBonds constraints in that case, not HAngles. That's somewhat easier on the minimizer.

Hmm, why are `AllBonds` required when using HMR?  Isn't the point of HMR to slow the X-H bond vibrations down?  Or is it the angle vibrational periods that become the limiting factor once HMR has been used?

**Comment by peastman** [comment]
Bonds that don't involve hydrogen and angles that do both have approximately the same period (about 20 fs).  So it doesn't do any good to constrain or slow down just one of them.  You have to do both to get any benefit.

**Comment by swails** [comment]
> Hmm, why are AllBonds required when using HMR? Isn't the point of HMR to slow the X-H bond vibrations down? Or is it the angle vibrational periods that become the limiting factor once HMR has been used?

I think this comes down to the fact that the SHAKE constraint solver is approximate and iterative (as opposed to SETTLE, which is analytical).  If there is too much of a constraint deviation from one step to another, SHAKE fails.  As I understand it, HMR reduces these deviations, allowing you to take longer time steps without triggering SHAKE failures.

**Comment by swails** [comment]
> Bonds that don't involve hydrogen and angles that do both have approximately the same period (about 20 fs). So it doesn't do any good to constrain or slow down just one of them. You have to do both to get any benefit.

So then why is `HAngles` even an option?

**Comment by kyleabeauchamp** [comment]
Hangles constraints both all-bonds and angles with hydrogens.  E.g.

Hbonds < AllBonds < HAngle

**Comment by swails** [comment]
Oh yea. :)
