### ISSUE TITLE
6.2 does not install under MAC OSX 10.8.5

### ISSUE THREAD

**Issue by jhprinz** [pandegroup/openmm#881]
Had to reinstall openmm on an older machine while my laptop is repaired and first tried it to install using conda from the omnia binstar. This installs but importing raises the following exception:

```
[...]
  File "/[...]/anaconda/lib/python2.7/site-packages/simtk/openmm/__init__.py", line 14, in <module>
    from simtk.openmm import version
ImportError: cannot import name version
```

using the binary from simtk could also be installed but now the error is:
```
[…]
  File "/Users/[...]/Documents/git/openpathsampling/openpathsampling/topology.py", line 7, in <module>
    import simtk.openmm
  File "/Users/[...]/anaconda/lib/python2.7/site-packages/simtk/openmm/__init__.py", line 13, in <module>
    from simtk.openmm.openmm import *
  File "/Users/[...]/anaconda/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 40, in <module>
    _openmm = swig_import_helper()
  File "/Users/[...]/anaconda/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 36, in swig_import_helper
    _mod = imp.load_module('_openmm', fp, pathname, description)
ImportError: dlopen(/Users/[...]/anaconda/lib/python2.7/site-packages/simtk/openmm/_openmm.so, 2): Symbol not found: ___sincos_stret
  Referenced from: /usr/local/openmm/lib/libOpenMM.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/openmm/lib/libOpenMM.dylib
```

Some google search hints to it being compiled for 10.9? Is that possible? In simtk it still lists 10.7+. So that may have to be updated.

I tried to avoid installing from source so far. Will see if that fixes it.

**Comment by peastman** [comment]
For John and Kyle - which SDK are the Mac binaries being compiled against?  It's set by CMAKE_OSX_SYSROOT.  It won't run on any OS older than the SDK you used to compile.

**Comment by kyleabeauchamp** [comment]
I think this is it:

https://github.com/omnia-md/conda-recipes/blob/master/openmm/build.sh#L18

```
    CMAKE_FLAGS+=" -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk"
```

**Comment by jchodera** [comment]
That way my doing.  Sorry about that!

If you want us to change it to an earlier version, I'm happy to---you're just going to have to explain to us what to use instead and how to install the earlier SDK libraries, since the OpenMM default (which is I think the 10.6 SDK) isn't found on 10.9.

**Comment by jchodera** [comment]
Also, do we want to upgrade the build machine to Yosemite?  We are now able to do that if desired.

**Comment by peastman** [comment]
Apparently Apple makes it way more complicated to get old SDKs than they have any business doing!  This page explains how to do it:

http://stackoverflow.com/questions/11989007/where-to-get-macos-sdk-10-6-for-xcode

See if you can get it working with the 10.7 SDK.  There's no need to upgrade the OS.

**Comment by jchodera** [comment]
Working on this now!

**Comment by jchodera** [comment]
Those instructions don't seem to work.  I am unable to install XCode 4.1 because it complains "Xcode Install Assistant can't be installed on this disk. The version of OS X is too new."

**Comment by swails** [comment]
I think you need to extract the relevant files from the package -- it says how in the SO post, I think (I *just* read it, but my memory is not perfect :)).

**Comment by jchodera** [comment]
Ah! I see that now, thanks!

I think my brain is just conditioned to only see the posts with a green
check mark next to them. :)

**Comment by jchodera** [comment]
I chose XCode 4.3.3, mounted the `xcode_4.3.3_for_lion.dmg` disk image and archived the SDKs with `tar` to ensure I get all the symlinked files:
```
cd /Volumes/Xcode/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
tar zcf ~/MacOSX10.6.sdk.tgz MacOSX10.6.sdk
tar zcf ~/MacOSX10.7.sdk.tgz MacOSX10.7.sdk
```
I then unpacked these into the current Xcode SDK directory:
```
tar zcf ~/MacOSX10.6.sdk.tgz MacOSX10.6.sdk
tar zcf ~/MacOSX10.7.sdk.tgz MacOSX10.7.sdk
```
I've created a PR to switch to this SDK:
https://github.com/omnia-md/conda-recipes/pull/176

**Comment by jchodera** [comment]
I think this can be closed only once we include instructions in the manual about how users are supposed to find these files to compile OpenMM on `osx`.

**Comment by jchodera** [comment]
Can this be closed, @jhprinz?

**Comment by jchodera** [comment]
@jhprinz: Can this be closed?

**Comment by jhprinz** [comment]
Well, sometime ago. Will close this. No longer be an issue
