### ISSUE TITLE
Add a node or attribute to serialized State objects that reports on which version of OpenMM generated it

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#884]
We're debugging some issues with Folding@home projects using the OpenMM core, and it occurs to us that it would be super useful if serialized `State` objects in particular (and maybe all XML serialized objects?) included a node or attribute documenting which version of OpenMM generated them.

Other metadata, like a timestamp, might also be useful...

**Comment by peastman** [comment]
Good idea.  It would be easy to add an openmmVersion attribute to the top level tag or something like that.

**Comment by swails** [comment]
+1

Obviously won't work for existing files, but going forward this is a good idea.  Time stamp is probably something better left to an XML comment?
