### ISSUE TITLE
Bug in addExtraParticles

### ISSUE THREAD

**Issue by cxhernandez** [pandegroup/openmm#891]
I'm trying to add missing particles to my system with `Modeller`, but ran into this error:

```python
In [102]: modeller = Modeller(topology, positions)
In [103]: modeller.addExtraParticles(forcefield)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-103-4e7ac8c05839> in <module>()
----> 1 modeller.addExtraParticles(ff)

/home/cxh/anaconda/lib/python2.7/site-packages/simtk/openmm/app/modeller.pyc in addExtraParticles(self, forcefield)
    972
    973                                 knownPositions = [x for x in templateAtomPositions if x is not None]
--> 974                                 position = unit.sum(knownPositions)/len(knownPositions)
    975                             newPositions.append(position*nanometer)
    976         for bond in self.topology.bonds():

TypeError: unsupported operand type(s) for /: 'tuple' and 'int'
```

Is `unit.sum` supposed to be returning a tuple?

**Comment by peastman** [comment]
It should be returning a Vec3, which subclasses tuple but implements the / operator.  I just did a quick test of that, and it seems to work correctly:

```
>>> import simtk.unit as unit
>>> from simtk.openmm import *
>>> a = [Vec3(1.0,2.0,3.0), Vec3(3.0,4.0,5.0)]
>>> unit.sum(a)/len(a)
(2.0, 3.0, 4.0)
```

Can you provide instructions on how to reproduce this?

**Comment by cxhernandez** [comment]
I was using an OpenMM `topology` from a ParmEd `Structure` object, so it might be some sort of compatibility issue. I'll get back to you with an example.

**Comment by swails** [comment]
ParmEd uses `tuple`s instead of `Vec3` objects for the positions (since OpenMM is an optional dependency).

I can do the same thing there that I do with `unit`, though (i.e., duplicate the implementation, but import the one from `simtk` if it's available to make sure the class object is always the same one).

I suspect this is the case.  Let me try to fix it.

**Comment by cxhernandez** [comment]
Thanks @swails!

**Comment by swails** [comment]
Did ParmEd/ParmEd#134 fix it?

**Comment by cxhernandez** [comment]
yep!
