### ISSUE TITLE
Some CustomIntegrator questions

### ISSUE THREAD

**Issue by kyleabeauchamp** [pandegroup/openmm#895]
So I've been implementing several hamiltonian monte carlo techniques using the CustomIntegrator class.  I've encountered a couple of potential stumbling blocks that people might have some insight on.

1.  Dealing with nans
2.  Conditional Context updates or context caching.

Regarding (1), a common idiom for metropolized integrators is `addComputePerDof("x", "x*accept + xold*(1-accept)")`.  A similar idiom can be used for energy storage.  However, AFAIK this idiom only works in the event that positions and energies are finite, as otherwise we end up propagating NANs through the integrator.  Any clever (but fast) workarounds?

Regarding (2), I've implemented a method (Extra Chance HMC) that essentially requires multiple calls to `integrator.step()`  before a decision can be made whether to accept or reject.  The issue is that I'd like to avoid updating the context (e.g. box vectors) at this time, as context updating would disrupt my metropolization scheme.  

At this point, I'm mostly mentioning these things for the sake of discussion, as on my end I still have lots of refactoring and testing of my code.  It's possible that I'll rework thing to obviate these issues.

**Comment by jchodera** [comment]
Regarding `NaN`, see #333

**Comment by jchodera** [comment]
For point (2), we discussed the potential for a `CompositeIntegrator` in #763

**Comment by jchodera** [comment]
For extra chance HMC, a `CompositeIntegrator` where you could externally select which integrator to use (so that you could apply some control flow) could be very helpful.  

If you wanted to do this all within a `CustomIntegrator` efficiently, the lack of control flow is going to really hurt performance.  I wonder if some simple control flow commands could be incorporated into `CustomIntegrator` to support this without hurting performance much?

**Comment by kyleabeauchamp** [comment]
I think #333 provides part of what I need: nan checking:

```
    abs(step(x)-step(1-x))
```

I still need to figure out how I can use this to actually set the variables.  I believe there may be a way to do this by combining min and max.

Regarding the CompositionIntegrator: something like that might work here.  In the meantime, I think most of my integrators work fine for NVT, so I can roll those out for now.

**Comment by jchodera** [comment]
If `abs(step(x)-step(1-x))` works for `NaN` checking (you'll need to test it out!) it might be good to have Lepton accept `isnan(x)` as a shortcut for this.

**Comment by jchodera** [comment]
> I still need to figure out how I can use this to actually set the variables
Check out the [example in openmmtools where we use this](https://github.com/choderalab/openmmtools/blob/master/openmmtools/integrators.py#L172-L178).

I don't think this has been heavily tested in conditions where `NaN`s are generated---I think my issue in #333 was due to something else.

**Comment by kyleabeauchamp** [comment]
+1 for shortcut, as I really would love to keep readability

**Comment by kyleabeauchamp** [comment]
FWIW, seems like the step idea (with bugfix) can detect nans, at least on reference (example below).  However, I still haven't figured out how to use this to set a variable that has already become a NAN.

```
from simtk import unit as u
import simtk.openmm as mm
import openmmtools

testsystem = openmmtools.testsystems.WaterBox()
system, positions = testsystem.system, testsystem.positions

integrator = mm.CustomIntegrator(20.0 * u.femtoseconds)

temperature = 300 * u.kelvin

integrator.addPerDofVariable("x1", 0)
integrator.addPerDofVariable("x2", 0)
integrator.addPerDofVariable("x3", 0)

integrator.addUpdateContextState()
integrator.addComputePerDof("v", "v+0.5*dt*f/m")
integrator.addComputePerDof("x", "x+dt*v")
integrator.addComputePerDof("x1", "x")
integrator.addConstrainPositions()
integrator.addComputePerDof("v", "v+0.5*dt*f/m+(x-x1)/dt")
integrator.addConstrainVelocities()

integrator.addComputePerDof("x2", "x")
integrator.addComputePerDof("x3", "abs(step(x) - step(- x))")


context = mm.Context(system, integrator)
context.setPositions(positions)
context.setVelocitiesToTemperature(temperature)

integrator.step(1)

energy = context.getState(getEnergy=True).getPotentialEnergy()
x2 = integrator.getPerDofVariableByName("x2")
x3 = integrator.getPerDofVariableByName("x3")

energy
x2[0:3]
x3[0:3]

integrator.step(50)

energy = context.getState(getEnergy=True).getPotentialEnergy()
x2 = integrator.getPerDofVariableByName("x2")
x3 = integrator.getPerDofVariableByName("x3")

energy
x2[0:3]
x3[0:3]


In [28]: x2[0:3]
Out[28]: 
[(-0.8379363743587486, 0.12610600616283268, 0.13073316312551336),
 (-0.875991607226721, 0.17090730984257885, 0.20627759341744895),
 (-0.7918473409113432, 0.05098894475947849, 0.16809017839951826)]

In [29]: x3[0:3]
Out[29]: [(1.0, 1.0, 1.0), (1.0, 1.0, 1.0), (1.0, 1.0, 1.0)]
In [34]: 

In [34]: energy
Out[34]: Quantity(value=-115725.4709789985, unit=kilojoule/mole)

In [35]: x2[0:3]
Out[35]: [(nan, nan, nan), (nan, nan, nan), (nan, nan, nan)]

In [36]: x3[0:3]
Out[36]: [(0.0, 0.0, 0.0), (0.0, 0.0, 0.0), (0.0, 0.0, 0.0)]


```

**Comment by peastman** [comment]
I've never really thought about handling nans.  Generally you want to avoid them!  Once they appear, it's usually too late to recover.  But I guess Monte Carlo is a bit different: it just means you need to reject the step.

What about a function equivalent to the ternary operator?  Something like select(condition, value1, value2) that equals value1 if condition != 0, value2 if condition == 0.

For 2, can you formulate the whole process as a single composite step, like you would for a MTS integrator?  When step() returns, it really should be all done with the step.  Otherwise you're going to have a lot of problems, and not just ones related to CustomIntegrator.  For example, suppose you're running a simulation with a reporter that periodically saves states to a file.  A fraction of those states will be ones that later got rejected, and should never have been saved as part of the trajectory.

**Comment by jchodera** [comment]
Here's a first stab at a variant of the HMC integrator that tries to detect when the energy has turned `nan` and reject the proposal if that is the case:
https://gist.github.com/jchodera/e7aa1c51c949a44acb56

Unfortunately, I get different behaviors depending on which `Platform` I use:
* On `Reference` on `osx`, I get a bus error:
```
[LSKI1497:openmmtools.jchodera/examples/integrator-nans] choderaj% python integrator-nan-test.py
Creating context...
Taking 5 steps...
Bus error
```
* On `CPU` on `osx`, we get the behavior that @peastman introduced in #791 where an exception is thrown at some point:
```
[LSKI1497:openmmtools.jchodera/examples/integrator-nans] choderaj% python integrator-nan-test.py
Creating context...
Taking 5 steps...
Traceback (most recent call last):
  File "integrator-nan-test.py", line 181, in <module>
    integrator.step(nsteps)
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 8509, in step
    return _openmm.CustomIntegrator_step(self, *args)
Exception: Particle coordinate is nan
```
While this is very helpful in general, if we want to have the integrator deal with `nan`s, we're stuck---we would have to intercept the `nan`s earlier in the step before the checking is done, such as immediately after the position or velocity update overflows (if the check doesn't occur there).

**Comment by jchodera** [comment]
> What about a function equivalent to the ternary operator? Something like `select(condition, value1, value2)` that equals `value1` if `condition != 0`, `value2` if `condition == 0`.

In a sense, we already have this capability, e.g.:
```python
        self.addComputePerDof("x", "x*accept + xold*(1-accept)") 
```
where `accept` is either 1 or 0.  Of course, the `select` function would still be convenient, so I certainly support it!

It seems that we also need the ability to disable `nan` Exception checking if we want to handle `nan`s ourselves.

**Comment by jchodera** [comment]
> For 2, can you formulate the whole process as a single composite step, like you would for a MTS integrator? When step() returns, it really should be all done with the step. 

This is possible for standard HMC integrators, like [the gist I just posted](https://gist.github.com/jchodera/e7aa1c51c949a44acb56).

For extra chance HMC to be efficient, though, I think either an early termination check is needed or some way to skip energy evaluations.

The only other thing I can think of is to code up the extra chance as every "step" coding for an "attempt", where it attempts to integrate using auxiliary variables `xnew,vnew` and replaces `x,v` that step if MC acceptance succeeds, otherwise it just keeps integrating in `xnew,vnew` until a `nan` is encountered (where we have to start over) or it eventually succeeds.  But I worry that this could make it difficult to correctly count statistics since there is no guarantee that `integrator.step(nsteps)` wouldn't be returning in the middle of the step (though the positions and velocities would be correct) unless the user checks the number of accepted moves and see if it has increased?

**Comment by kyleabeauchamp** [comment]
Let's fix the NAN issue first.  I think the `select()` function will work better than the indicator variables, assuming it's easy to implement.  

Regarding "ending up in an intermediate state", I believe I can partially solve this by subclassing the `step()` member function and wrapping the dynamics in a `while` loop.  So IMHO that's not the problem so much as being able to control the context update. 

PS: here is a gist that uses John's HMC version and "blows up": https://gist.github.com/kyleabeauchamp/f65254af875e1d3cd7ec

**Comment by kyleabeauchamp** [comment]
PS: John, in your example I think you are assuming that we'll be OK as long as we can *detect* nans.  IMHO, it's not just a matter of detection, it's that our scheme for variable update only works when the value of `x` is finite.  

```
x = x * a + x0 * (1 - a)
```
In this case, I think that if `x = nan` and `a = 0`, we still set `x = nan`.  However, I think the ternary operator will do the trick here.

**Comment by peastman** [comment]
> self.addComputePerDof("x", "x\*accept + xold\*(1-accept)") 

That doesn't work with nans, because 0*nan = nan.  The point of the select() function is that if accept is 0, it will simply evaluate to xold, not any mathematical function involving x.

**Comment by jchodera** [comment]
You're both right!  I had naively assumed that `0*nan` would yield `0`, but you're absolutely right here.

**Comment by kyleabeauchamp** [comment]
It might be true that we need some sort of NAN error suppression, though.  The following link suggests that an exception is raised whenever the energy or force calculation detects a nan particle.  

https://github.com/pandegroup/openmm/blob/master/platforms/cpu/src/CpuKernels.cpp#L231

I suppose we might have to 

1.  Check particles for nans
2.  define an indicator for presence of nan
3.  restore coordinates to previous state *before* energy evaluation
4.  set energy to nan if (2) was True

It does seem like this behavior is platform dependent, though, so this may require some thougth.

**Comment by peastman** [comment]
True.  Though that only happens on the CPU platform, not CUDA or OpenCL.  But for CPU platform, suppressing the exception isn't enough.  Positions equal to nan can produce segfaults when calculating forces.

**Comment by kyleabeauchamp** [comment]
Ok.  I'm happy piloting things on cuda anyway, so the exception discussion
can wait.

**Comment by jchodera** [comment]
@peastman implemented the `select(condition, success, failure)` feature in #904.

Is there still utility in having some way to terminate the step early, or control when energies/forces are evaluated?

**Comment by kyleabeauchamp** [comment]
I'm currently doing some tests of correctness of my HMC codebase.  After those tests finish, we can re-visit the context update and performance questions.

**Comment by kyleabeauchamp** [comment]
The first half of this has been solved.  When I'm ready for discussion, I'll open a separate issue to discuss the context update questions.
