### ISSUE TITLE
Potential Issues with Nonbonded (LJ) force?

### ISSUE THREAD

**Issue by kyleabeauchamp** [pandegroup/openmm#906]
So I've been implementing and debugging various hamiltonian monte carlo methods.  For most systems, my methods seem to be working, as measured by comparing the expected value of the potential energy with a HMCIntegrator and a LangevinIntegrator (with small timestep).  However, I find that for a periodic system of Lennard Jones particles, HMC and Langevin are giving answers that are statistically different, with differences of several KJ / mol.  

This difference depends strongly on the cutoff.  For example, a cutoff of ~2.5 sigma (the LJ radius) gives errors of ~5 KJ / mol (relative error: 1E-3).  A cutoff of 3 sigma gives errors of ~2 KJ / mol (relative error 5E-4).  A cutoff of 3.5 sigma gives errors that are undetectable. 

Results for the three different cutoff lengths are below.   With the CUDA platform on a GTX Titan.  I've actually tried all three precision levels, with no major differences AFAIK.  The average potential energy is given in the column "mu".  

```
         sysname          integrator           mu    stderr           Neff  timestep
18         ljbox  LangevinIntegrator -3835.804623  0.070364    6263.192065     2.000
11         ljbox       HMCIntegrator -3837.672160  0.024726   50483.297078    16.000
2      longljbox  LangevinIntegrator -3916.681236  0.059387    8645.740209     2.000
0      longljbox       HMCIntegrator -3916.522774  0.022949   58144.505627    16.000
19    shortljbox  LangevinIntegrator -3613.987124  0.158612    1301.501161     1.333
20    shortljbox       HMCIntegrator -3619.623843  0.267620     428.535579    16.000
```

Given how HMC works, the two most obvious culprit is perhaps the force for periodic nonbonded forces is not exactly the the gradient of the energy.  However, I have not been able to quantify or support this claim, so I really have no idea what's actually going on.  There could also be a bug in my HMC code as well, or cosmic rays.  

PS: similar system with a non-periodic cluster of ~500 LJ particles in a harmonic restraining well does not exhibit the same energy differences---I tried with both no cutoff and a short cutoff.  

PS: this is all with NVT, although I did play with the dispersion correction which had no effect.

**Comment by jchodera** [comment]
By default, OpenMM does not use a Lennard-Jones switching function:
https://github.com/pandegroup/openmm/blob/master/openmmapi/include/openmm/NonbondedForce.h#L69-L73

Symplectic integrators like velocity Verlet (on which many of these schemes are based) are derived with the assumption that the potential energy is continuous through the first few derivatives so that the force is also continuous through several derivatives.  Without adding a switching function, this means a force impulse critical to energy conservation is missed.  The strong cutoff dependence of this effect suggests that this might be what you're seeing here.

The `openmmtools.testsystems.LennardJonesFluid` has a `switch` option that is actually off by default:
https://github.com/choderalab/openmmtools/blob/master/openmmtools/testsystems.py#L1475-L1476

Have you tried setting this to, say, some distance (e.g. `0.5*sigma`) below the cutoff distance?

**Comment by kyleabeauchamp** [comment]
I will look at the switching function behavior.  

My first intuition is that this shouldn't make a difference, as my control with a LJ cluster did not display any cutoff dependence.  If this is simply due to derivative discontinuities, I would have observed this with the non-periodic version of this test system.

**Comment by swails** [comment]
Have you computed any RDFs for your system?  If so, and your cutoff is at the range where the particle density reaches bulk, then the dispersion correction *should* correct the energy almost perfectly for a L-J liquid and the net force that you're ignoring beyond the cutoff should be zero (assuming an isotropic particle distribution).

**Comment by jchodera** [comment]
The LennardJonesCluster does not use a cutoff by default.  Did you run that
system with CutoffNonPeriodic?

**Comment by kyleabeauchamp** [comment]
I have modified it to allow either choice.

**Comment by kyleabeauchamp** [comment]
So adding a switching function was able to fix the problems for the LJ box with a short cutoff:

```
               sysname          integrator            mu    stderr           Neff  timestep
12  switchedshortljbox  LangevinIntegrator  -3518.906834  0.095767    3454.570259     1.333
6   switchedshortljbox       HMCIntegrator  -3518.956817  0.052832   11205.146304     4.0
```

I'm still confused about how PBC plays a role in this.  I'm now looking at a much larger LJ cluster with a short cutoff.

**Comment by jchodera** [comment]
My IBM integrator energy variance tests also indicated some problem with PBC, but I was never able to figure this out. Let us know what you find!

**Comment by jchodera** [comment]
@swails: Note that the anisotropic dispersion correction does not depend on
the instantaneous configuration of the particles, and hence cannot correct
for the potential and force discontinuities that give rise to neglected
impulses when particle pairs cross this boundary.

**Comment by kyleabeauchamp** [comment]
I've also done TIP3P water with a 0.9 nm cutoff with 0.05 nm switch, which gives raw errors of ~10 kJ / mol and relative errors of 4E-4 (data below).  

```
                    sysname          integrator            mu    stderr           Neff  timestep
26                  rfwater  LangevinIntegrator -42354.841155  4.089949    2333.474764     1.000
24                  rfwater       HMCIntegrator -42377.489841  2.084875    8885.607079     3.000
23                    water  LangevinIntegrator -42394.453644  3.603264    2836.983837     1.000
15                    water       HMCIntegrator -42408.378175  2.243199    7731.253317     3.000
```

**Comment by jchodera** [comment]
Just to make sure I understand where we are here: The LJ box is now working well, but TIP3P with PME or reaction field has large errors for HMC.  Is that right?

**Comment by kyleabeauchamp** [comment]
The lj box agrees in the case of large cutoff with a switch.

**Comment by jchodera** [comment]
> The lj box agrees in the case of large cutoff with a switch.

What about small cutoff with a switch?

**Comment by kyleabeauchamp** [comment]
I may have figured out the issue.  According to the manual, " If the NonbondedMethod in use is anything other than NoCutoff and r is greater than the cutoff distance, the energy and force are both set to zero. "

To me, this means that both the energy and the force are discontinuous, as observed in the attached plots.  I guess my assumption was that the force would be zero outside of the cutoff and the energy would be *constant*, not zero.  

![energy](https://cloud.githubusercontent.com/assets/1900459/7577073/56e86aba-f812-11e4-8a6d-34fb48b07baf.png)
![force](https://cloud.githubusercontent.com/assets/1900459/7577074/56eb901e-f812-11e4-9afd-5c942ef1926c.png)

**Comment by kyleabeauchamp** [comment]
Driver code for figures is here: https://github.com/kyleabeauchamp/HMCNotes/blob/master/sandbox/correctness/line_integral.py

**Comment by jchodera** [comment]
Setting the force to zero outside the cutoff and ensuring the energy is continuous is called a *shift*.  That still results in discontinuous force derivatives, though.

The better way to do this is the *switch*, which should result in continuous first force derivatives (and second derivatives if the proper order is used).

Could you try regenerating with the switch on?

**Comment by jchodera** [comment]
Might also be good to expand the domain to [0,8] instead of [0,4] to go through a couple of cycles.

**Comment by kyleabeauchamp** [comment]
Here are the same figures with a switch.  I think my key point here is that we probably don't want to be doing HMC without either a switch or a shift.  For the energy to be the integral of the force, we require at least a shift at the cutoff. 
![energy](https://cloud.githubusercontent.com/assets/1900459/7577693/64955de2-f819-11e4-89e4-5146b51a6b02.png)
![force](https://cloud.githubusercontent.com/assets/1900459/7577694/6497f552-f819-11e4-93ac-fde11abc9bf6.png)

**Comment by kyleabeauchamp** [comment]
And now, I've repeated the hard cutoff calculation but also overlayed a plot of the integral of the force.  Notice the disparity--with a hard cutoff, the force and the potential correspond to totally different hamiltonians.  Hence, my HMC code was sampling the one given by the potential, but the Langevin integrator was sampling the hamiltonian given by the forces.

![energy](https://cloud.githubusercontent.com/assets/1900459/7577721/bb5389a6-f819-11e4-8531-8f19ed88b46b.png)

**Comment by kyleabeauchamp** [comment]
PS: correct me if I'm wrong here, this work was done on a train after a glass of wine while negotiating with a SF landlord.

**Comment by jchodera** [comment]
> PS: correct me if I'm wrong here, this work was done on a train after a glass of wine while negotiating with a SF landlord.

Ha!

It's very close to being a correct analysis, I think!  

Velocity Verlet requires that the potential and force be continuous and have several continuous derivatives as well (though the exact number escapes me at the moment).  Failure to satisfy this means that there is a small delta-function contribution that is being missed at the cutoff, and this is likely the origin of your issues with the cutoff.

With a proper switch, things should be better behaved, provided the force doesn't change too rapidly.  It's possible that either the force is changing too rapidly near the cutoff, or---and it's just the shape of that force plot that has me guessing this---the derivative of the force is not continuous at the boundaries.

I'll check the functional form of the switch OpenMM uses...

**Comment by jchodera** [comment]
According to the OpenMM manual, the switching function applied to the potential is:
```
S = 1 - 6*x^5 + 15*x^4 - 10*x^3
```
where `x = (r-r_s) / (r_c - r_s)`.  This interpolates from 1 to 0 and has continuous first and second derivatives at both ends.  That means that the force should also be continuous and have continuous first derivative at both ends.

**Comment by jchodera** [comment]
Hm.  The force sure doesn't *look* like it has continuous first derivatives at both ends.

**Comment by jchodera** [comment]
Here is a [modified version of your script](https://gist.github.com/jchodera/7c98648bd366738568ca) that uses parameters appropriate for argon and a typical switch (0.5 A) and cutoff (3*sigma).

![potential](https://cloud.githubusercontent.com/assets/3656088/7579238/c3f2cf1c-f82e-11e4-8466-779ec29bf907.png)
![force](https://cloud.githubusercontent.com/assets/3656088/7579237/c3f0eeae-f82e-11e4-869a-dcfd2a621ff4.png)

It looks like a switch of 1*sigma is necessary to avoid significant-looking artifacts:

![potential](https://cloud.githubusercontent.com/assets/3656088/7579251/ef7fd09e-f82e-11e4-86e7-4b90ea8614c0.png)
![force](https://cloud.githubusercontent.com/assets/3656088/7579250/ef7dd37a-f82e-11e4-85fe-043f9a63a8a7.png)

**Comment by swails** [comment]
PME for L-J!

**Comment by jchodera** [comment]
> PME for L-J!

Would certainly not object to that.

**Comment by kyleabeauchamp** [comment]
Alright folks, I re-ran the LennardJonesFluid example with and without a (3.4 angstrom) switch, and as expected things look good with the switch.  In particular, with the switch enabled I get 1E6 relative agreement between Langevin and HMC.  Next I'll look at the waterbox example.  

```
         sysname          integrator           mu    stderr           Neff  timestep
3          ljbox  LangevinIntegrator -3847.817540  0.057564    9447.558793         2
1          ljbox       HMCIntegrator -3850.055240  0.018972   85706.125360        16
2  switchedljbox  LangevinIntegrator -3715.688076  0.046291   14318.040938         2
0  switchedljbox       HMCIntegrator -3715.732402  0.017437  100655.362768        16
```

**Comment by jchodera** [comment]
Well, the important thing is not the absolute discrepancy (1e6), but the number of standard errors that discrepancy represents.

In this case, it is 
```
abs(-3715.732402+3715.688076) / sqrt(0.017437^2 + 0.046291^2) = 0.896
```
so `0.9*sigma`, which is statistically indistinguishable from zero.

**Comment by kyleabeauchamp** [comment]
Correct, I'm saying that with a switch the differences are statistically indistinguishable from zero.  Without a switch, the distributions sampled by HMC and Langevin are statistically distinguishable.

**Comment by jchodera** [comment]
Here is a plot for two TIP3P water molecules in an arbitrary relative orientation passed near each other in a periodic box several times.  I am using `cutoff = 9*angstroms`, `switch_width = 1*angstrom`, and `PME`:
![potential](https://cloud.githubusercontent.com/assets/3656088/7601664/a6fde810-f8e7-11e4-8f4c-2ad84b05f919.png)
![force](https://cloud.githubusercontent.com/assets/3656088/7601666/a9bebe44-f8e7-11e4-95e0-acdf28746ff8.png)
On the other hand, when using `CutoffPeriodic`, the attenuated electrostatic cutoff is still visible as an artifact in the force:
![potential](https://cloud.githubusercontent.com/assets/3656088/7601682/d6eab6b6-f8e7-11e4-9d49-473f7d683a83.png)
![force](https://cloud.githubusercontent.com/assets/3656088/7601683/d925bb38-f8e7-11e4-9357-c74ec52bbca3.png)

**Comment by jchodera** [comment]
Code is here:
https://gist.github.com/jchodera/3a3fa7cec3c91f784542

**Comment by kyleabeauchamp** [comment]
While the "switching humps" are import to be aware of, for my purposes (debugging HMC code), I believe the most important consideration is whether the integral of the force is equal to the energy.  Have you checked this?  I believe the code I linked previously can do this.

For the case of rigid water, I believe this will require adding up the force on each of the three atoms.

**Comment by jchodera** [comment]
Hm.  Not quite sure how to do that.

**Comment by kyleabeauchamp** [comment]
As you were preparing your images, I made it halfway towards doing this: https://github.com/kyleabeauchamp/HMCNotes/blob/master/sandbox/correctness/line_integral_water.py

It's still not quite there, though, as I have to add up the forces...

**Comment by jchodera** [comment]
I'm still not sure it's really the integral that is causing problems here with HMC---I think it's the force derivative discontinuities that are causing problems with Langevin, even at small timesteps.

**Comment by kyleabeauchamp** [comment]
I suppose the way to test this would be a truncated force with an energy
shifted at the cutoff to match the force.

**Comment by jchodera** [comment]
Good idea!  We could add an option to LennardJonesFluid to implement this
using a CustomNonbondedForce. Let me know if you want me to give that a go.

**Comment by jchodera** [comment]
@kyleabeauchamp, I've added a `shift` boolean option to `openmmtools.testsystems.LennardJonesFluid`:
https://github.com/choderalab/openmmtools/pull/64

Note that the `SrcExplicit` failure means that an updated `openmmtools-dev` is not being pushed to binstar.

**Comment by kyleabeauchamp** [comment]
After looking at some results with John's shifted version of LennardJonesFluid, I have two observations.

1.  As I mentioned above, the missing energy in the non-shifted potential makes the force and energy correspond to two slightly different hamiltonians--e.g. different forcefields
2.  Because the force and the energy are different forcefields, using a hard cutoff hurts the acceptance rate and performance, as seen in the table below.  Note that each value corresponds to 20,000 MCMC iterations, so the error bars are mostly on the order of 0.003.  

The water system here is with a 9 angstrom cutoff and either no switch or a switch width of 3 angstroms.  The LJ box contains 2000 particles with a cutoff of 3 sigma and either no switch or a switch width of 1 sigma.  I'm still running more tests, will report back eventually...

```
    accept             sysname
0  0.73855               ljbox
1  0.99870       switchedljbox
2  0.99895        shiftedljbox
3  0.64790          shortwater
4  0.69190  shortswitchedwater
```

**Comment by jchodera** [comment]
These are just acceptance rates, right?

Do you have any data on whether the shifted potential with small-timestep Langevin dynamics fixes the discrepancy with Metropolized methods?

Though I realize now that I subtract a value *from* the potential so that the potential goes to zero (rather than a constant) at the cutoff, so the average potential will be different for the shifted system.  It should be simple to modify the testsystem code to add back `N(N-1)/2 * shift_potential` as a `CustomExternalForce` to have the potential go to a constant nonzero value, but that may also give a different average potential than the truncated system even if sampled correctly with Metropolis Monte Carlo.

**Comment by jchodera** [comment]
For reference, here is what the potential and force look like for the shifted potential:
![potential](https://cloud.githubusercontent.com/assets/3656088/7667817/75f71432-fbe7-11e4-84db-9f3b499d1fa4.png)
![force](https://cloud.githubusercontent.com/assets/3656088/7667818/78965676-fbe7-11e4-8e4a-595c4131e828.png)

**Comment by kyleabeauchamp** [comment]
I'm still re-running the correctness / discrepancy tests.  

Yes, those are just acceptance rates.

**Comment by kyleabeauchamp** [comment]
As I expected, both the shift and the switch allow HMC and Langevin to agree on the LennardJonesFluid system (output below).  

```
           integrator            mu precision      sigma    stderr        sysname  timestep      pval      tscore    relerr      error
3  LangevinIntegrator -14551.635149     mixed  10.174373  0.195817          ljbox       0.5  0.000000 -101.658326  0.001732 -25.161495
0       HMCIntegrator -14526.473654     mixed  10.369130  0.149157          ljbox       2.0  0.000000 -101.658326  0.001732 -25.161495
4  LangevinIntegrator -14032.373983     mixed  10.703197  0.262568   shiftedljbox       0.5  0.609574   -0.510747  0.000006  -0.077248
1       HMCIntegrator -14032.296735     mixed  10.618488  0.137272   shiftedljbox       2.0  0.609574   -0.510747  0.000006  -0.077248
2  LangevinIntegrator -14179.238514     mixed  10.745402  0.281899  switchedljbox       0.5  0.688689    0.400691 -0.000013   0.180630
5       HMCIntegrator -14179.419144     mixed  10.593399  0.123008  switchedljbox       2.0  0.688689    0.400691 -0.000013   0.180630
```

**Comment by jchodera** [comment]
What property are you computing here?  Potential energy?  Did you need to add the constant energy subtracted from the interatomic potentials *back* to get agreement between shifted and switched?

**Comment by kyleabeauchamp** [comment]
This is potential energy.  Presumably I would need to add back a constant to see agreement between the cutoff and shifted.  However, I don't think that exercise is really necessary right now as I'm only interested in whether I can get Langevin and HMC to give the same answer.

**Comment by jchodera** [comment]
> Presumably I would need to add back a constant to see agreement between the cutoff and shifted.

Also between cutoff and switched.  I'm really confused if cutoff and switched give agreement without that, since the particle-particle minimum energy should contribute substantially to the average and there are N*(N-1)/2 of those interactions that get subtracted off for the shifted system.

**Comment by jchodera** [comment]
Oh, nevermind!  You're comparing HMC and Langevin for the **SAME SYSTEM**, not between shifted and switched.

**Comment by jchodera** [comment]
Huh.  This is a really surprising result to me.  There's a force discontinuity with `switch` and `cutoff`, and I would have thought both would have caused problems.

Is it that with the cutoff, Langevin is producing the incorrect average, or HMC?

**Comment by kyleabeauchamp** [comment]
In summary: a LangevinIntegrator samples the forcefield that is given by the forces, while an HMCIntegrator samples the forcefield that is given by the energy.  

With a hard cutoff, the force and the energy correspond to *different* forcefields.  HMC samples the forcefield that is prescribed by the energy, while Langevin samples the forcefield that is specified by the force.  

Adding back the shift makes the force and energy self-consistent, so both integrators then are sampling the same forcefield.

**Comment by jchodera** [comment]
OK, I think that explanation actually meshes with the idea that the discontinuity means that the force would need to pick up an "impulse" every time it crossed the cutoff boundary in order to be simulating from the same kind of potential.  It's not easy to do that experiment with OpenMM (because we can't simply add/subtract a quantity from the force each time the boundary is crossed), but the concordance in the case of shift seems to make sense.

I'm still a little surprised that shift seems to work so well given the force is still discontinuous.  I was under the impression that this would still cause significant artifacts because the requirements for the existence of a shadow Hamiltonian (continuity of force derivatives) were violated.

This is only somewhat related, but there are actually several different shift schemes, including both potential shift (used in this example) and force shift.  Some of the more modern variants are reviewed and compared [in a nice paper by Chris Fennell](https://www.researchgate.net/profile/J_Gezelter/publication/6962946_Is_the_Ewald_summation_still_necessary_Pairwise_alternatives_to_the_accepted_standard_for_long-range_electrostatics/links/541860350cf2218008bf3ac8.pdf) that may have other good ideas for use with OpenMM.

**Comment by kyleabeauchamp** [comment]
Alright folks, I repeated the same calculation with a liquid of "slightly charged" particles, which are essentially the same LJ particles as before but with alternating charges of plus or minus 0.15.  With charges of this magnitude, both the LJ discontinuity and the PME error are factors to consider.  However, if I increase the PME accuracy by 10X (ewaldErrorTolerance=5E-5) and use a switch, I am able to get excellent agreement between Langevin and HMC.

```
            integrator            mu precision      sigma    stderr                       sysname  timestep      pval     tscore    relerr      error
0   LangevinIntegrator -27471.286026     mixed  10.266246  0.265360                  chargedljbox       0.5  0.000000 -51.630019  0.000840 -23.050189
8        HMCIntegrator -27448.235837     mixed   9.837196  0.341852                  chargedljbox       2.0  0.000000 -51.630019  0.000840 -23.050189
11  LangevinIntegrator -27102.656813     mixed  10.664984  0.210213  chargedswitchedaccurateljbox       0.5  0.529586  -0.628694  0.000010  -0.270396
2        HMCIntegrator -27102.386417     mixed  10.888210  0.102878  chargedswitchedaccurateljbox       2.0  0.529586  -0.628694  0.000010  -0.270396
5   LangevinIntegrator -27097.676690     mixed  10.486337  0.226072          chargedswitchedljbox       0.5  0.000021  -4.262511  0.000036  -0.971136
13       HMCIntegrator -27096.705555     mixed  10.489583  0.072879          chargedswitchedljbox       2.0  0.000021  -4.262511  0.000036  -0.971136
```

**Comment by rmcgibbo** [comment]
I've been following this thread on and off, but I'm not sure I'm up on all of the details. To what degree do you think your results imply that the default options in one or more of the OpenMM forces should be changed? Or should we add a section to chapter 19.6 of the manual? http://docs.openmm.org/6.2.0/userguide/theory.html#coulomb-interaction-with-cutoff

**Comment by kyleabeauchamp** [comment]
At the present, I think I would add a small sentence or two in 19.6.1 that mentions the implications of the strict cutoff versus the switch.  We might even add a plot of what the cutoff versus switch looks like.

**Comment by kyleabeauchamp** [comment]
I can't really say yet whether I have recommendations to change any defaults.  In truth, I think the right answer is generally "whatever they used when they designed the forcefield".

**Comment by kyleabeauchamp** [comment]
I'll probably have a better answer once I figure out whatever ingredients are necessary to get agreement on more complex systems, such as water and ethyl acrylate.

**Comment by jchodera** [comment]
I wonder what the issue is with PME.  My guess is that `alpha` is set based on the specified tolerance `tol`.  If you use a fixed `cutoff`, this means that the direct-space interaction energy, which goes as `erf(r)/r`, will have a larger discontinuity at the cutoff for cruder `tol`, which is similar to the LJ issue.  If you use a tighter tolerance, the different `alpha` causes a smaller energy discontinuity at the same cutoff.

You might try setting `alpha` manually using `NonbondedForce.setEwaldParameters()` to see if this is the case.  This is another issue where having a switch in the real-space Ewald interaction might help.

**Comment by kyleabeauchamp** [comment]
FWIW, I also played around a bit with the cutoff length and found the results not to be strongly sensitive to it--in my experience it really was `ewaldErrorTolerance` that did the trick.

**Comment by peastman** [comment]
> My guess is that alpha is set based on the specified tolerance tol.

Precisely.  See http://docs.openmm.org/6.2.0/userguide/theory.html#coulomb-interaction-with-particle-mesh-ewald.

> FWIW, I also played around a bit with the cutoff length and found the results not to be strongly sensitive to it--in my experience it really was ewaldErrorTolerance that did the trick.

The goal is that cutoff distance should have no effect at all.  The accuracy should be determined entirely by ewaldErrorTolerance.  The cutoff then determines how much work gets done in direct space and reciprocal space, which can affect performance.  It gives you a single parameter you can adjust to tune performance while keeping the accuracy constant.

Of course, that only applies to Coulomb.  Since the same cutoff is used for LJ as well, the accuracy will start to suffer if you make it too short.

**Comment by jchodera** [comment]
This sounds consistent with the idea that a sharp change in the direct space Coulomb at the cutoff, which is controlled by the tolerance, is what is causing trouble.  A shift or switch in the direct space Coulomb would help minimize these issues, though it introduces inexactness in the partitioning.  It may still be worth it, however.

I wonder if a switched direct space term is something that could be corrected for exactly in a CustomPMEForce...

**Comment by kyleabeauchamp** [comment]
I think the problem is mostly resolved though: use high accuracy pme.

**Comment by jchodera** [comment]
Any idea what the performance cost is?

Obviously, if the performance cost is low, this is the optimal solution.

**Comment by kyleabeauchamp** [comment]
No idea, but we can optimize performance later.  In principle we could use
a different tolerance for forces and energies using respa.

**Comment by jchodera** [comment]
> No idea, but we can optimize performance later.  In principle we could use a different tolerance for forces and energies using respa.

As long as dynamics is symplectic, HMC *should* be able to let you get away with lax tolerances for force integration provided you can compute accurate energies.  Maybe "the ability to compute forces and energies to different accuracies" is a feature we could add to the OpenMM wishlist?

**Comment by kyleabeauchamp** [comment]
I think this can already be done with a tiny modification to my existing HMC RESPA code:

1.  Make a copy of the nonbonded force
2.  Lower the accuracy of the copy
3.  Make the copy a separate force group
4.  Exclude the high-accuracy force group from the integration steps and exclude the low-accuracy force group from the energy calculation.

**Comment by jchodera** [comment]
Got it!  Very clever.

**Comment by swails** [comment]
> I think this can already be done with a tiny modification to my existing HMC RESPA code:
> 
> Make a copy of the nonbonded force
> Lower the accuracy of the copy
> Make the copy a separate force group
> Exclude the high-accuracy force group from the integration steps and exclude the low-accuracy force group from the energy calculation.

I don't think this is going to work.  For the GPU platforms, all nonbonded kernels are coalesced into the same nonbond loop, requiring that all forces have the same cutoff and same group ID.

IIRC, this limitation does *not* apply to the Reference (and by extension CPU) platform, but it'll hit you when you go to CUDA or OpenCL.

It's for reasons like this that I mentioned the FR of different nonbonded forces being allowed in different groups in the Omnia call yesterday.

**Comment by kyleabeauchamp** [comment]
Good catch, I haven't tested any of this yet but I'll take your word for it.

**Comment by jchodera** [comment]
Maybe more flexibility on this could be a feature worth looking into?

**Comment by kyleabeauchamp** [comment]
So I think this issue is mostly solved for now.  I think the take-home message is that for HMC applications, there are some subtle details that require attention.  In particular, the force and the energy may correspond to slightly different forcefields under certain approximations (hard cutoff, low-accuracy PME).  In such situations, it is useful to use a smooth switch and high-accuracy PME.
