### ISSUE TITLE
simtk.openmm.version for dev conda packages 

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#910]
Anybody have any ideas on how to get the `simtk.openmm.version` version strings to be more useful for the conda `openmm-dev` package?

This is all it says:
```
Help on module simtk.openmm.version in simtk.openmm:

NAME
    simtk.openmm.version - # THIS FILE IS GENERATED FROM OPENMM SETUP.PY

FILE
    /cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/simtk/openmm/version.py

DATA
    full_version = '6.3.0.dev-Unknown'
    git_revision = 'Unknown'
    openmm_library_path = '/cbio/jclab/home/chodera/miniconda/lib'
    release = False
    short_version = '6.3.0'
    version = '6.3.0.dev-Unknown'
```

**Comment by swails** [comment]
Where does this get built?

**Comment by swails** [comment]
With CMake, we do out-of-source building, correct?  If the build directory is not a subdirectory of the git repository wherever the `-dev` binaries are getting built, then git commit version queries in the build directory won't resolve to any commit (you'll just get the generic: `fatal: Not a git repository (or any of the parent directories): .git`)

**Comment by jchodera** [comment]
Jenkins is currently building this using the conda openmm-dev recipe:

https://jenkins.choderalab.org/job/conda-openmm-dev-linux-vagrant/

**Comment by jchodera** [comment]
A bit more information:

Jenkins uses the `conda-build-all` script to build the [`openmm-dev`](https://github.com/omnia-md/conda-recipes/tree/master/openmm-dev) conda recipe.

This recipe [currently retrieves `master.zip`](https://github.com/omnia-md/conda-recipes/blob/master/openmm-dev/meta.yaml#L6-L7) rather than checking out the git head.  I'll see if changing this to checking out the git head will help!
