### ISSUE TITLE
Fixed time simulations

### ISSUE THREAD

**Issue by peastman** [pandegroup/openmm#914]
A feature that's been requested a few times is the ability to have simulations run for a fixed amount of clock time, then write a checkpoint and exit.  I'd like to get feedback on a few potential designs.

1. A class called SimulationTimeLimiter.  You would add it to a Simulation's list of reporters, and give it either an amount of time to run, or a clock time at which to stop.  When the end time is reached, it would automatically write out a checkpoint (a binary checkpoint file, a serialized State, or both at your choice), then call exit().

2. A method on Simulation to run for a fixed amount of clock time.  You would then be responsible for writing out the checkpoint yourself.

3. Don't add any new features, and just give an example script for doing this.  The script generator could also provide this as an option.

**Comment by kyleabeauchamp** [comment]
So @jchodera and I have used both fixed time blocks and fixed step blocks to converge various properties to the desired accuracy.  Two examples below:

https://github.com/kyleabeauchamp/HMCNotes/blob/master/sandbox/lb_loader.py#L44

https://github.com/choderalab/LiquidBenchmark/blob/master/src/simulation/liquid_tools.py#L165

**Comment by jchodera** [comment]
I actually like suggestion 2, where the `Simulation` class has a method to run for a fixed amount of wall clock time (where it uses a user-settable step block size under the hood), e.g.
```
simulation.runForFixedTime(10 * unit.second, checkIntervalSteps=100)
```
Later, we could also add something like what we have used for `LiquidBenchmark` where the user sets a target statistical uncertainty.

**Comment by mpharrigan** [comment]
Can we do (2) with an auto-checkpoint at the end

```
def step_for(5 * unit.hour):
    while (time_isnt_up()):
        self.step(100)
    self.write_checkpoint()
```

**Comment by rmcgibbo** [comment]
I could imagine wanting to write a script like

```
if not exists('checkpoint.mm')
  [ ... set up simulation like I currently do ... ]
else:
   simulation.loadCheckpoint('checkpoint.mm')

simulation.runFor(12*hours)
simulation.writeCheckpoint('checkpoint.mm')
```

**Comment by jchodera** [comment]
What about adding an option for auto-checkpointing, allowing us to write either
```
simulation.runFor(12*hours)
simulation.writeCheckpoint('checkpoint.mm')
```
or
```
simulation.runFor(12*hours, checkpoint='checkpoint.mm')
```
We could even have it auto-checkpoint at various intervals:
```
simulation.runFor(12*hours, checkpoint='checkpoint.mm', checkpointInterval=1*hour)
```

**Comment by swails** [comment]
I vote for No. 2.  It's actually been on my to-do list for awhile, I just haven't gotten to it yet (and 2 is what I was going to give a proposed implementation for).

**Comment by rmcgibbo** [comment]
That would be fine. Overall I'm +1 on adding more convenience features to `Simulation` as methods, as opposed to reporters.

**Comment by swails** [comment]
> That would be fine. Overall I'm +1 on adding more convenience features to Simulation as methods, as opposed to reporters.

In this case I'm +1 as well.  I don't want to hack what *should* be a reporter (i.e., something performed in regular intervals that report information from the trajectory) into a method on `Simulation`.

**Comment by peastman** [comment]
Ok, sounds like there's agreement on option 2.

What about the checkpointing question?  There are two distinct types of checkpointing that have been mentioned: writing one at regular intervals, and writing one when the end time is reached.  (Those could of course overlap *if* the total time is exactly a multiple of the checkpoint interval.)  And we also have two distinct types of outputs we can write: a binary checkpoint, or a State serialized to XML.  Possibilities include:

1. Add arguments for all these things to the method on Simulation.

  ```Python
  simulation.runForClockTime(12*hours, checkpointFile='checkpoint', checkpointInterval=1*hour)
  ```

2. Have a CheckpointReporter that takes care of writing them at regular intervals.

  ```Python
  simulation.reporters.append(CheckpointReporter(checkpointFile='checkpoint', checkpointInterval=1*hour)
  simulation(runForClockTime(12*hours)
  ```

3. Just have convenience methods on Simulation to write checkpoints.

  ```Python
  for i in range(12):
      simulation.runForClockTime(1*hour)
      simulation.writeCheckpoint('checkpoint')
  ```

**Comment by swails** [comment]
I vote for 1.

**Comment by jchodera** [comment]
I vote for 1 and 3 (where 1 could be implemented internally via calls to the method for 3).

I think of `Reporter` objects as something that accumulate a (possibly multidimensional) timeseries of some properties of the trajectory, and the idea of a `CheckpointReporter` that generally overwrites its output doesn't seem consistent with that.

**Comment by mpharrigan** [comment]
It would be nice to implement regular, time-based checkpoints in such a way that they could be applied in the same way to a simulation run for a particular number of steps. A reporter probably makes sense here.

When we are running for a set amount of walltime, it wouldn't be amiss to assume that the user would like to continue that simulation from the very end (not just the last "interval"). As a convenience, we should write out a checkpoint at the end.

See gromacs's `mdrun` checkpointing (happens every 15 minutes by default) and the `-maxh` argument (stops after that many hours, writes a final checkpoint)

**Comment by swails** [comment]
I'm actually leaning a little more toward an input parameter on `SImulation`.  Its operational mode is quite a bit different than existing reporters (which all report on specific step intervals), and to me seems rather unique to a checkpoint task.

We'd have to change `Simulation` anyway to handle time-based reporters rather than step-based reporters (is this something of general interest?)
