### ISSUE TITLE
Implementing ambiguous distance restraints using OpenMM

### ISSUE THREAD

**Issue by BIORAK** [pandegroup/openmm#924]
I want to run a simulation by applying forces to group of atoms and pull them together using Ambiguous Distance Restraints as in NMR across two proteins. I would like to know how to add it in OpenMM.

**Comment by peastman** [comment]
I assume that by "ambiguous" restraints, you mean you want to apply a potential that keeps it close to the desired distance but lets it fluctuate a bit?  That should be easy to do with a custom force.  What function do you want to use for your restraints?

**Comment by jlmaccal** [comment]
Peter,  I suspect he means the 1/r^6 weighted restraints that are commonly used in NMR.

Rakesh, Something similar is implemented in my lab’s MELD package:

https://github.com/maccallumlab/meld <https://github.com/maccallumlab/meld>
https://github.com/maccallumlab/meld-openmm-plugin <https://github.com/maccallumlab/meld-openmm-plugin>

Specifically, the OpenMM plugin has a force class that can be added to any OpenMM simulation. It’s a holiday here and I’m just about to leave my office, but I can provide more detail tomorrow. Why don’t you post on issue on the meld-openmm-plugin repository with a few details about what you want to do and I can walk you through it.

**Comment by BIORAK** [comment]
Yes I want some thing like the 1/r^6 weighted restraints to restrain atomic distances as used in NMR. But this should be across two different proteins, so it should cause pulling of the proteins. This should be as shown in the paper http://www.tandfonline.com/doi/full/10.1080/00268976.2013.813594 for the case of collective variable (Class IV colvar components: based on multiple pairwise atomic distances, equation 9)

**Comment by BIORAK** [comment]
I was not able to post the issue on MELD package github page. I want some thing like the 1/r^6 weighted restraints to restrain atomic distances as used in NMR. But this should be across two different proteins, so it should cause pulling of the proteins. This should be as shown in the paper http://www.tandfonline.com/doi/full/10.1080/00268976.2013.813594 for the case of collective variable (Class IV colvar components: based on multiple pairwise atomic distances, equation 9)

**Comment by jlmaccal** [comment]
OK, I enabled issues on the MELD plugin repo. Can you post an issue and we'll move this discussion over there.

https://github.com/maccallumlab/meld-openmm-plugin

**Comment by jlmaccal** [comment]
This issue can be closed.
