### ISSUE TITLE
Additional GBn radius issues

### ISSUE THREAD

**Issue by pgrinaway** [pandegroup/openmm#928]
Hi,

After correcting the radii to be within [1.0, 2.0] A, I have found that some values in the range (>1.91113A, though I'm not sure exactly where the cutoff is) still produce an index out of range error. Code below:

```python
import simtk.openmm as openmm
import simtk.openmm.app.internal.customgbforces as customgbforces
import simtk.unit as units
import numpy as np


system = openmm.System()
system.addParticle(1)
system.addParticle(1)



gbnforce = customgbforces.GBSAGBnForce()
system.addForce(gbnforce)

#change to 1.91113 to avoid error
radius = 1.91114 * units.angstroms

gbnforce.addParticle([0.1, radius, 0.05])
gbnforce.addParticle([0.1, radius, 0.05])
positions = [[0.0,0.0,0.0],[1.0,1.0,1.0]]

timestep = 2*units.femtoseconds
collision_rate = 10 / units.picoseconds
temperature = 300*units.kelvin

integrator = openmm.LangevinIntegrator(temperature, collision_rate, timestep)
context = openmm.Context(system, integrator)
context.setPositions(positions)
state = context.getState(getEnergy=True)
print(state.getPotentialEnergy())
```

**Comment by jchodera** [comment]
Any ideas here?  Is it just a documentation issue, or a more sinister table computation error?

**Comment by peastman** [comment]
I've been pondering the code, and I think it may be cheating a little bit.  Here's how it computes the index into the lookup table:

    index = (radius2*200-20)*21 + (radius1*200-20)

Notice that it's continuous in both radius1 and radius2.  It really *ought* to be

    index = floor(radius2*200-20)*21 + floor(radius1*200-20)

or something like that.  But presumably it's relying on the fact that Amber also tabulates the parameters in exactly the same way, so the radii it outputs will always give exactly an integer when multiplied by 200.  And that saves having to compute the floor() functions.

**Comment by swails** [comment]
Actually, I think Amber *rounds* to the nearest grid index (rather than simply truncating it via `floor` or int-casting).  Here's the relevant source code from `sander`:

```Fortran
!+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!+ Initialize table of indexes for GB neck lookup table.
subroutine igb7_init(natom, rborn)

  implicit none
  integer, intent(in) :: natom

  integer i

  _REAL_, intent(in) :: rborn(*)

  do i=1,natom
     neckidx(i) = nint((rborn(i)-1.0d0)*20d0)
     if (neckidx(i) < 0 .or. neckidx(i) > 20) then
        write (6,*) "Atom ",i," has radius ",rborn(i), &
                    " outside of allowed range"
        write (6,*) "of 1.0 to 2.0 angstroms for igb=7. Regenerate &
                    &prmtop file with bondi radii."
        call mexit(6,1)
     end if
  end do

end subroutine igb7_init
```

Perhaps it should be something like:

```Python
index = floor((radius2*200-20)+0.5)*21 + floor((radius1*200-20)+0.5)
```

**Comment by peastman** [comment]
An even better solution would be to switch the functions to Discrete2DFunction.  Then it'll take care of all the index calculation automatically.

**Comment by swails** [comment]
Agreed.

I'll whip up a quick script that can validate against sander if you want to issue a PR for this (or you can wait for me to do it, but idk when that would be)

**Comment by peastman** [comment]
A test script would be great.  Send that, and then I'll implement the fix.

**Comment by swails** [comment]
My script is going to use the Python API for sander, which requires AmberTools 15 to be installed -- is that going to be a problem?

**Comment by swails** [comment]
Because if so, I can test your PR here -- just let me know what's easier for you.

**Comment by peastman** [comment]
Ok, I'll send a PR and let you check it against Amber.

**Comment by swails** [comment]
This should be fixed now, and can probably be closed.

**Comment by jchodera** [comment]
@pgrinaway can you close if fixed?
