### ISSUE TITLE
Brainstorm for HMC context update feature or workaround

### ISSUE THREAD

**Issue by kyleabeauchamp** [pandegroup/openmm#938]
So I've now got (hopefully) working implementations of several hamiltonian monte carlo integrators, including all possible combinations of (HMC / GHMC) with RESPA and extra chance hamiltonian monte carlo (XCHMC) (https://github.com/kyleabeauchamp/openmmtools/blob/hmc/openmmtools/hmc_integrators.py).      (references: C. M. Campos, J. M. Sanz-Serna, J. Comp. Phys. 281, (2015)
    J. Sohl-Dickstein, M. Mudigonda, M. DeWeese.  ICML (2014) )

However, at this point I need to figure out a way to handle barostats and other forms of context updates.  The basic issue is that one of the algorithms (XCHMC) works like this (for one step of of the MC chain):

-1.  Randomize velocities, completely (HMC) or partially (GHMC)
0.  for k in range(n_extra_chances) {
1.  Do L steps of hamiltonian dynamics
2.  Accept or reject based on a modified metropolis criterion
3.  If accept, break out of the for loop.  Otherwise, do another round of hamiltonian dynamics.
4.  End for.  If still haven't accepted the proposal, reject and flip momement

The complexity of this algorithm is that the termination can take place after any of {1, 2, ..., n_extra_chances + 1} rounds of hamiltonian dynamics.  This logic is a bit challenging to implement with the tools in CustomIntegrator.  My current implementation lumps the steps (2, 3, 4) into a single call to `integrator.step()` and controls the outer for loop using a global variable `k`.  Then, to prevent the integrator from stopping at an intermediate stage (e.g. when the current positions are neither rejected nor accepted), I subclassed `integrator.step()` and wrapped it with a `while` loop to keep running dynamics until the current state is either accepted or rejected.  

I've also considered an alternative implementation where one call to integrator.step actually does the entire sweep of steps (0, 1, 2, 3, 4).  However, this alternative implementation would require me to have some sort of `break` statement that allows me to jump to the next iteration of `step(1)` prematurely, without executing the remaining iterations of the for loop (0).  

Another way to handle the context updates would be to keep the implementation that I currently have, but allow some sort of "conditional" context update, where the context update is conditional on a global variable, similar to the `select()` function that we implemented recently. 

I'm curious if anyone has any cute ideas here for implementing this in the most straightforward manner.

**Comment by kyleabeauchamp** [comment]
PS: one reason this is interesting is that I've also built the machinery for tuning the various HMC hyperparameters (e.g. choice of RESPA groups, how many steps of hamiltonian dynamics, how many extra chances, timestep) to maximize the performance.  Thus, we'll be able to simultaneously achieve high performance sampling while still guaranteeing samples from the correct distribution, free from timestep error.

**Comment by leeping** [comment]
Hi Kyle,

That sounds like a really cool integrator.  If I understand correctly, a MC move starting from `x(t)` is computed by running a short segment of energy-conserving dynamics to `x(t+tau)`?  And if a MC move is rejected, you don't reject the computation right away, but you continue evolving with a chance of accepting the "larger" move.  What happens if you flip the momentum and it's also rejected in the other direction?

Thanks,

- Lee-Ping

**Comment by kyleabeauchamp** [comment]
So let's say we use XHMC with 1 extra chance.  Then the possible outcomes are:

L(x0, p0)
L^2(x0, p0)
F(x0, p0)

Here, L is the operator representing L steps of hamiltonian dynamics and F is the momentum flip operator.

**Comment by leeping** [comment]
Right.  If the momentum flip operator takes (x0,p0) to (x0, -p0), then the next possible outcomes are:

L(x0, -p0)
L^2(x0, -p0)
F(x0, -p0)

Does the third line take us back to the beginning (x0, p0)?

**Comment by kyleabeauchamp** [comment]
So the momentum flip is only done on rejection.  So it's only relevent on the last line.  I've updated my previous comment to look a bit more clear, hopefully.

**Comment by leeping** [comment]
Yes, I think I understand that the momentum flip is done only on rejection.  Suppose k = 1 is rejected which takes us to k = 2 (flipped momentum).  Then suppose it is rejected again at k = 2 and k = 3.  After these four rejections, do we circle back to the situation at k = 0?

**Comment by kyleabeauchamp** [comment]
So there's only the possibility of rejection at the final value of k.  In the current example, k resets to zero after k = 1.  There is no possibility of k = 2.

**Comment by kyleabeauchamp** [comment]
k is in the set {0, 1, 2, ..., extra_chances}.  Here, extra_chances is 1, so k is in {0, 1}.  Does that clarify?

**Comment by leeping** [comment]
Got it - thanks for the clarification.  Using your corrected notation, we have your three lines (copied from above):

accept on k = 0: L(x0, p0)
accept on k = 1: L^2(x0, p0)
reject on k = 1: F(x0, p0) = (x0, -p0)

Now suppose the move is rejected, and k resets to zero.  Following this we have the next three lines:

accept on k = 0: L(x0, -p0)
accept on k = 1: L^2(x0, -p0)
reject on k = 1: F(x0, -p0) = (x0, p0)

My question is whether the rejection at the sixth line brings us back to the first line.

**Comment by kyleabeauchamp** [comment]
Right, two rejections in a row will bring you back to the first line. 

Note that there's also the velocity thermalization going on here, so in practice the momenta would be refreshed each time k = 0.  This refresh can be either a total randomization (HMC) or a partial randomization (GHMC).

**Comment by leeping** [comment]
Got it.  That really helps, because I was wondering where the constant temperature was coming in.  If there were no velocity thermalization at all, that's probably not enough to sample from the constant-temperature ensemble.  Is that also when the MC barostat is applied?

**Comment by kyleabeauchamp** [comment]
Yes, I would like to apply the MC barostat *only* when k = 0 and before I thermalize the momenta.

**Comment by kyleabeauchamp** [comment]
PS: here is the (very preliminary) driver code for tuning the performance: https://github.com/kyleabeauchamp/HMCNotes/blob/master/sandbox/optimize/test_optimize_hyper_xhmc_respa.py

**Comment by leeping** [comment]
Thanks, I think I understand now.  I think your "global variable `k`" strategy sounds reasonable.  Are there any drawbacks to this approach?  You can add an `if (k==0) : then MCBarostat()` or something.

**Comment by kyleabeauchamp** [comment]
This is all implemented as a CustomIntegrator, so there's no way to do an if statement.

**Comment by peastman** [comment]
So in your current list of steps:

> 1. for k in range(n_extra_chances) {
> 2. Do L steps of hamiltonian dynamics
> 3. Accept or reject based on a modified metropolis criterion
> 4. If accept, break out of the for loop. Otherwise, do another round of hamiltonian dynamics.
> 5. End for. If still haven't accepted the proposal, reject and flip momement

We should insert:

1.5 Randomize velocities

**Comment by kyleabeauchamp** [comment]
Done, I added step `-1` in my above comment

**Comment by peastman** [comment]
Oh, I see.  It happens outside the loop.  Got it.

**Comment by leeping** [comment]
Hmm, you could hack `MonteCarloBarostatImpl::updateContextState` to take a step size parameter.  Then multiply the step size by `k == 0`.  That's quite ugly though.  :)  I haven't thought much about how to cleverly work around no `if` statements.

**Comment by kyleabeauchamp** [comment]
My current implementation has another issue worth considering: I've wrapped around the member function `integrator.step()` to ensure that users don't probe the state at an "intermediate" value.  However, a power user could very easily find ways around this.  For one, if you serialize my XHMC integrator and deserialize it, you've basically stripped out my python code and broken it.  That might be an argument for me doing more via the CustomIntegrator and less via python.  E.g. Python code would be used to construct the custom integrator, but not required for its execution.

**Comment by peastman** [comment]
I can think of a few options here.

1. Accept that HMC has outgrown CustomIntegrator, and create a plugin for it.  In the long term this might be the best solution, especially for performance.  If I recall, you had issues about forces or energies sometimes being recalculated more often than necessary?  Did you ever resolve that?  If not, a plugin could eliminate them.

2. Add support for "if" statements (and possibly loops) to CustomIntegrator.  That would be a big task and add a lot of complexity to the implementation, but it would also be very powerful.  It might be a nice feature for 6.4.

3. Try to hack something together using the existing tools.  We might be able to come up with something, but it will probably be ugly (like the way you're already having to override step()).

**Comment by kyleabeauchamp** [comment]
Regarding energies being recalculated: I think I have the ability to overcome that problem by being smart about how I organize things.  For example, if the energy calculation is rate-limiting, then my autotuner will automatically increase the number of hamiltonian steps between energy evaluations.

Regarding the plugin: that would require writing CUDA code, right?  

I guess one nice thing about my current implementation is that it's pretty much optimal in terms of code reuse--the RESPA code lives in a Mixin python class, the XMC code lives in a Mixin python class, and we can construct a XCHMCRESPAIntegrator by simply subclassing:

```
class XCHMCRESPAIntegrator(RESPAMixIn, XCHMCIntegrator):
```

**Comment by kyleabeauchamp** [comment]
One more thought: it sounds like the path forward involves a delicate balance of ease-of-implementation, feature completeness, and performance.  I might try to give you some benchmark numbers to help get a feel for the costs involved here.

**Comment by jchodera** [comment]
> If I recall, you had issues about forces or energies sometimes being recalculated more often than necessary? Did you ever resolve that?

For the CUDA platform, I do see a ~35% slowdown in `openmmtools.integrators.HMCIntegrator` when we compute the energy at the beginning and end of the HMC step, so this problem is indeed significant.

One way to simply eliminate the need for energies to be recomputed twice each time `integrator.step()` is called is to use a global integrator variable to cache the potential energy from the end of the last step.  Unfortunately, there is no way to easily (re)set this global variable each time the positions are reset or the context state is updated.

A simple way to handle this would be to extend the `CustomIntegrator` API to add a method
```
addInitializeGlobal(variablename, expression)
```
method.  This would only be computed initially or when the context state is changed.

Similarly, a method
```
addInitializePerDof(variablename, expression)
```
would also be useful in precomputing some other per-particle quantities and avoiding computing them every timestep, such as in `openmmtools.integrators.VVVRIntegrator`:
```
self.addComputePerDof("sigma", "sqrt(kT/m)")
```
I think this strategy could generally be used for Metropolized integrators.

**Comment by jchodera** [comment]
Instead of adding full conditional control, would simply adding the possibility of early termination be sufficient for XCHMC and related schemes?  For example, a method
```
self.addEndStepCondition(condition)
```
which would end the integration step early if `condition` was met?

**Comment by peastman** [comment]
Are you sure that's really the cause of the slowdown?  It does make efforts to reuse forces and energies across time steps.

**Comment by jchodera** [comment]
Here's the test code:
https://github.com/jchodera/openmmtools/blob/bitwise-reversible-integrator/benchmark-hmc.py

All I did was test whether commenting out a single line changed the timing:
https://github.com/jchodera/openmmtools/blob/bitwise-reversible-integrator/openmmtools/integrators.py#L674

It's possible some other phenomenon is at work here, such as universal acceptance or rejection.  Let me see if I can also test the caching of `Eold` like I describe.

**Comment by jchodera** [comment]
Yep, I can confirm:

With initial line commented out and `Eold` cached at end of HMC step:
```
[chodera@gpu-2-17 openmmtools.jchodera]$ python benchmark-hmc.py
0.624 s elapsed.
[chodera@gpu-2-17 openmmtools.jchodera]$ python benchmark-hmc.py
0.633 s elapsed.
[chodera@gpu-2-17 openmmtools.jchodera]$ python benchmark-hmc.py
0.644 s elapsed.
```
with original HMC version and energies computed twice:
```
[chodera@gpu-2-17 openmmtools.jchodera]$ python benchmark-hmc.py
0.864 s elapsed.
[chodera@gpu-2-17 openmmtools.jchodera]$ python benchmark-hmc.py
0.876 s elapsed.
[chodera@gpu-2-17 openmmtools.jchodera]$ python benchmark-hmc.py
0.848 s elapsed.
```

I am not using a barostat here, so the context update shouldn't be doing anything.

**Comment by jchodera** [comment]
The difference is smaller for OpenCL, but still present.

With initial energy eval commented out and `Eold` cached:
```
[chodera@gpu-2-17 openmmtools.jchodera]$ python benchmark-hmc.py
1.046 s elapsed.
[chodera@gpu-2-17 openmmtools.jchodera]$ python benchmark-hmc.py
1.038 s elapsed.
[chodera@gpu-2-17 openmmtools.jchodera]$ python benchmark-hmc.py
1.044 s elapsed.
```
with original HMC that computes energies twice:
```
[chodera@gpu-2-17 openmmtools.jchodera]$ python benchmark-hmc.py
1.280 s elapsed.
[chodera@gpu-2-17 openmmtools.jchodera]$ python benchmark-hmc.py
1.210 s elapsed.
[chodera@gpu-2-17 openmmtools.jchodera]$ python benchmark-hmc.py
1.170 s elapsed.
```
This is with the `openmm-dev` conda package.

**Comment by jchodera** [comment]
Also, another question: Should we be computing the kinetic energy through some alternative way for efficiency, instead of using
 ```
self.addComputeSum("ke", "0.5*m*v*v")
```
?  I think I was late to notice the `setKineticEnergyExpression(expression)` method in the `CustomIntegrator` API.

**Comment by kyleabeauchamp** [comment]
On my CUDA GTX 960, commenting out that line takes the speed from 0.48s to 0.36s

However, if I use a value of 20 for `nsteps`, the performance hit is totally negligable.  It goes from 2.1s to 1.97s.  I think that values on the order of 20 are very likely going to be optimal, so IMHO the performance cost of the energy evaluation here is not our biggest problem.

**Comment by jchodera** [comment]
Ah!  It sounds like it caches the energy *within* a call to `integrator.step(nsteps)`, but not between calls.  That sounds like a totally reasonable thing to do.

**Comment by kyleabeauchamp** [comment]
Hmm. I'm not actually sure how it works, I just think that we have a free parameter (nsteps) that can minimize the fraction of time consumed by the energy.

**Comment by peastman** [comment]
There's no way it could optimize away that particular energy calculation.  You have a call to addUpdateContextState() before it, which can potentially change the system, so any energy calculated during the previous step would have to be thrown out.  But it will never have an energy from the previous step, because after the very last energy calculation (line 692), it modifies the positions (line 694).  So that last energy gets invalidated before it even finishes the time step.

**Comment by peastman** [comment]
self.addComputeSum("ke", "0.5*m*v*v")

That's a fine way to do it.

**Comment by kyleabeauchamp** [comment]
OK, so back to the issue of updating the context, I think John's `addEndStepCondition(condition)` might be another reasonable way to do it, although Peter may have some reason for excluding it from his list.

**Comment by peastman** [comment]
That would be another way of doing it, though it would be less powerful than supporting general conditional blocks.

**Comment by kyleabeauchamp** [comment]
I'm happy with finding the fastest elegant way to make it work, as that would allow me to get something working for NPT.  Once I have something working, we can then start asking performance questions.

I'll start re-reading the customintegrator code to see if I understand what's going on.

**Comment by jchodera** [comment]
> There's no way it could optimize away that particular energy calculation. You have a call to addUpdateContextState() before it, which can potentially change the system, so any energy calculated during the previous step would have to be thrown out.
> 
Is there any logic to detect whether anything was actually updated, or does it just use the fact that something was potentially changed?
> But it will never have an energy from the previous step, because after the very last energy calculation (line 692), it modifies the positions (line 694). So that last energy gets invalidated before it even finishes the time step.
> 

Good point.  This is due to my use of an expression that involves the `accept` variable to select old or new positions.  We would have to add some sort of conditional update expression, like
```
setConditionalCompute(condition, variable, expression)
```
for it to be able to tell, I imagine.

**Comment by kyleabeauchamp** [comment]
I wonder if we should move the energy caching issue into a separate thread and discussion.  I think we have two really tough ideas being discussed here and they might be easier to follow if we have one thread per issue.

**Comment by jchodera** [comment]
I agree that general conditional blocks would be awesome, but I am not sure how involved that would be in comparison to a simple early termination criterion.  Perhaps it makes sense to flesh out both options?  It could be that they could both be implemented, but the easier one implemented first?

**Comment by peastman** [comment]
If you mean in terms of the API, I imagine it looking something like this:

```Python
integrator.beginIfBlock("accept", CustomIntegrator.EQUALS, "1") # Only execute the block if accept==1
# Insert more commands here
integrator.endBlock()
```

**Comment by jchodera** [comment]
Can this be closed now that conditional termination has been implemented?
