### ISSUE TITLE
Implementation of Wolf Method for coulombic potential

### ISSUE THREAD

**Issue by okpatil4u** [pandegroup/openmm#942]
Hello,

Has anyone tried to implement Wolf method to replace ewald sum in electrostatic interaction ? Is it possible to implement in using CustomNonbondedForce ?

Thanks,
Omkar

**Comment by jchodera** [comment]
Can you provide a citation for the exact method you are thinking of?

**Comment by okpatil4u** [comment]
I need to simulate a system which is periodic in only two dimensions and non periodic in one dimension. Ewald sum does not work in such case. Here are some papers explaining the wolf method.

http://www.researchgate.net/profile/J_Gezelter/publication/6962946_Is_the_Ewald_summation_still_necessary_Pairwise_alternatives_to_the_accepted_standard_for_long-range_electrostatics/links/541860350cf2218008bf3ac8.pdf
http://lammps.sandia.gov/threads/pdfLgpjDKlZS4.pdf

I haven't finalised the method for it's use yet. Do you know of any other method which can work with this kind of systems and implementable in openmm ?

**Comment by jchodera** [comment]
Eq. 4 of the [Fennell and Gezelter paper](https://www.researchgate.net/profile/J_Gezelter/publication/6962946_Is_the_Ewald_summation_still_necessary_Pairwise_alternatives_to_the_accepted_standard_for_long-range_electrostatics/links/541860350cf2218008bf3ac8.pdf) is something you should be able to easily implement with the [CustomNonbondedForce API](http://docs.openmm.org/6.2.0/api-python/classsimtk_1_1openmm_1_1openmm_1_1CustomNonbondedForce.html).  All of the functional operations (including `exp` and `erfc`) are available in custom forces.

**Comment by okpatil4u** [comment]
Thanks John, I will start working on this. On another note, I need to work with some rigid walls. This is kind of related to the bug I reported in May 2011 to <a href="https://simtk.org/forum/message.php?msg_id=6318" target="_blank">Openmm Forum</a>.

Is it possible to work with just x component of distance in CustomNonbondedForce API ? So that instead of wall of particles I could just use one particle and add force that interacts with just x distance of system particle to that of wall particle. 

And also, can I change positions of a group of molecules while simulation is running ?

**Comment by jchodera** [comment]
Have you checked out CustomExternalForce?  That would allow you to
implement soft walls, which may be a useful alternative.

Will check out the bug report and see if that has been addressed.

**Comment by okpatil4u** [comment]
John, the bug has already been fixed.

I am sorry if I am asking a lot of questions in a single thread. But I promise this is the last one for now. Can I use setPositions function after simulation has started to change positions ?

**Comment by swails** [comment]
> Is it possible to work with just x component of distance in CustomNonbondedForce API ? So that instead of wall of particles I could just use one particle and add force that interacts with just x distance of system particle to that of wall particle.

No.  As @jchodera said, `CustomExternalForce` is what you want here.

> And also, can I change positions of a group of molecules while simulation is running ?

Yes.

> Can I use setPositions function after simulation has started to change positions ?

Yes, this is how you change positions.

**Comment by okpatil4u** [comment]
Thank you @swails and @jchodera .

**Comment by okpatil4u** [comment]
@jchodera Also is it possible to delete and insert particles after simulation has started ?

**Comment by swails** [comment]
> @jchodera Also is it possible to delete and insert particles after simulation has started ?

No.  Once a `Context` is created, you can neither add nor delete particles.

**Comment by okpatil4u** [comment]
Okay. And if particle is moved out of periodic box using setpositions, does
it still interact with other particles in the system ?

**Comment by jchodera** [comment]
Yes, it uses periodic boundary conditions.

If you want to turn the interactions of specified particles on and off
during the simulation, you can do this if you specify the particle
interactions using a CustomNonbondedForce.  For example, you can introduce
an additional per-particle parameter that specifies whether that particle
interacts with other particles, and the use updateParametersInContext() to
change those parameters during the simulation without much overhead.

**Comment by okpatil4u** [comment]
So as you mentioned, the custom nonbonded force will take care of lj
interactions and periodic ewald interactions (possibly wolf potential). And
an additional parameter which will turn these forces to zero..
I am trying to implement DCV-GCMD with openmm. Do you think that it could
be done with above mentioned method ?

**Comment by jchodera** [comment]
Apologies for being unfamiliar with the abbreviation, but could you
elaborate on DCV-GCMD?  GCMD is usually "grand canonical molecular
dynamics", which is certainly possible to implement this way.  What is the
DCV part?

A reference could help too!

**Comment by swails** [comment]
> So as you mentioned, the custom nonbonded force will take care of lj
> interactions and periodic ewald interactions

`CustomNonbondedForce` takes periodic boundary conditions into account, but it does not do Ewald.  `NonbondedForce` *does* do Ewald/PME as well as taking PBC into account, so if you need PME you will need both a `NonbondedForce` and a `CustomNonbondedForce`.

> And
> an additional parameter which will turn these forces to zero..

What @jchodera was saying is that you can write code to change per-particle parameters in both the `CustomNonbondedForce` and `NonbondedForce`, and then use `updateParametersInContext` to flush those updates to an active `Context`.  There is no "parameter" that does this for you.  So you can imitate "removing" a particle by simply setting its nonbonded parameters to zero, and you can imitate "adding" a particle by changing nonbonded parameters from zero to a non-zero value.

> I am trying to implement DCV-GCMD with openmm. Do you think that it could
> be done with above mentioned method ?

I'm not sure what the DCV part is, but I think GCMD should be possible by having a reservoir of "inactive"  particles that you can make active (and vice versa).

**Comment by okpatil4u** [comment]
Thank you Jason, John. It was really helpful.

**Comment by jchodera** [comment]
I was under the impression that the Wolf method was being used, which CAN
be implemented as a CustomNonbondedForce.  PME cannot yet be implemented
this way, though you can instead update the charges on thr particles you
are disappearing.

**Comment by okpatil4u** [comment]
Okay. I will have to study the api carefully. Thanks for the tip John.

**Comment by jchodera** [comment]
You can find an example that does this in our (still in development) constant pH code:
https://github.com/choderalab/openmm-constph/blob/master/constph.py#L557-L597

**Comment by jchodera** [comment]
Can this be closed, since the Wolf method can be implemented as a `CustomNonbondedForce`?

**Comment by okpatil4u** [comment]
Yeah, sure.

**Comment by jchodera** [comment]
Great!  Can you click the 'close' button then?

**Comment by axelcournac** [comment]
Hi,
Has someone an example of code using the functions setBondParameters  and updateParametersInContext() to change a Bond parameter during a simulation?
Thanks,
a
