### ISSUE TITLE
How to do FFTs with CUDA?

### ISSUE THREAD

**Issue by peastman** [pandegroup/openmm#943]
As you know, I've had a lot of trouble relating to the CUDA FFT library's poor support for streams.  In OpenMM 6.2 I added the optimization for performing the PME reciprocal calculation on a separate stream so it could run in parallel with other calculations.  On a GTX Titan, this gave about a 15% overall speedup.  Unfortunately, I quickly started finding problems.  On a GTX 980 the stream made things slower, not faster, so I disabled it on all Maxwell devices.  We discovered that a bug in versions of the FFT library before 6.0 produced incorrect results, so I disabled it there.  Then we ran into problems with large systems, so I disabled it whenever the number of atoms is >130,000.  And most recently, CUDA 7 completely broke stream handling in the FFT library, so I disabled it on that as well.  It's really a mess.

Meanwhile, I've done a lot of optimization to the OpenCL FFT code in preparation of OpenMM 6.3.  It's now much faster than it was.  About a month ago I decided to try porting it to CUDA to see how my FFT implementation compared to Nvidia's.  My results at the time indicated it was still somewhat slower, so I put it aside.

Now that Nvidia has said they're not going to do a really proper fix for their bug until CUDA 7.5, I decided to get it back out and analyze the performance more carefully.  The results are... complicated.  Here is the speed of the PME benchmark, with each FFT library (mine and Nvidia's), with and without a separate stream enabled, on three different GPUs (Titan, 980, Titan X):

Titan:

Nvidia, no stream: 114.8
Mine, no stream: 108.4
Nvidia, stream: 125.8
Mine, stream: 116.8

980:

Nvidia, no stream: 121.0
Mine, no stream: 117.5
Nvidia, stream: 110.2
Mine, stream: 103.5

Titan X:

Nvidia, no stream: 161.5
Mine, no stream: 158.7
Nvidia, stream: 170.8
Mine, stream: 174.4

So on Titan and Titan X, using a separate stream makes it quite a bit faster, while on 980 the separate stream makes it significantly slower.  That's despite the fact that 980 and Titan X are very similar GPUs (Maxwell, compute capability 5.2).  I have no idea why, or how it might behave on any other GPU.

Nvidia's FFT library is faster than mine with one curious exception: in the single fastest configuration (Titan X with stream enabled), my FFT is faster.  Again, I have no idea why!  Also, on Titan my version with streams enabled is faster than Nvidia's version with streams disabled.  That's significant, since we have to disable streams on CUDA 7 or with large systems.

I'm really at a loss for what to do here.  Any suggestions?  I've thought about trying to do some sort of dynamic method selection, but that's could be pretty complicated.  Also, on 980 merely _creating_ the second stream produces a slowdown, even if you then never use it.  Initially it was a huge slowdown (about 3x), but it got much smaller in a recent driver update.  I suspect it may indicate a hardware bug they've since worked around.

**Comment by jchodera** [comment]
If there was a way to do dynamic method selection, the API could be
extended with a context.tune() method to do the tuning, with a sensible
default selected if tuning is not invoked.

Alternatively, a platform variable could select which method to use with
tuning left to the user.

If having multiple implementations is simply too complex, a single
reasonable implementation (such as your FFT) could be used universally.
The numbers here are all very respectable, honestly!

Also, is there a difference between the 980 and 980 Ti?

**Comment by kyleabeauchamp** [comment]
So IMHO those numbers look similar enough that you might as well go with whatever is easy to implement / maintain and easy to guarantee correct results as much as possible.  

Our most performance-critical application is Folding@Home, and there the performance hit is not about squeezing out the final 15% of performance, but rather having access to modern classes of GPUs, the latest versions of OpenMM, and the CUDA platform.  Those three things are facilitated by maintainability, rather than raw performance. 

FWIW, for users running a single simulation and driving it from python, you and I have both built various auto-tuning capabilities that can be used as necessary.

**Comment by peastman** [comment]
> Also, is there a difference between the 980 and 980 Ti?

No idea.  980 Ti was just released, and I don't have one.  If you have one, I'd certainly be interested to hear your results.

**Comment by jchodera** [comment]
It seems like someone has already run FAHBench on it:
http://www.anandtech.com/show/9306/the-nvidia-geforce-gtx-980-ti-review/15

We don't have one yet.

**Comment by peastman** [comment]
It looks like they were running OpenCL.

**Comment by swails** [comment]
> So IMHO those numbers look similar enough that you might as well go with whatever is easy to implement / maintain and easy to guarantee correct results as much as possible.

This is the equivalent of what I was going to say.  We're talking about, on average, a 10% speed difference between the various options (assuming streams always work with your FFT and never works with theirs).  What's the %age of time spent in FFTs on the GPU?  IIRC, the reciprocal space sum was ~20-30% of the total calculation (with the short-range stuff and everything else being the remaining 70-80%), and the FFT was perhaps a bit over half of that.

It would not be hard to believe that the GPU sucks at FFTs compared to the direct-space sum, shifting that split more toward the FFT (but we have the PME plugin for the super-performance obsessed).  But if we're talking about a 10% performance boost on 15% of the calculation (*sometimes*, depending on hardware), is this worth stressing over?

**Comment by peastman** [comment]
The numbers I posted were total simulation speed in ns/day for DHFR.  They aren't just the difference in FFT speed.

**Comment by swails** [comment]
> The numbers I posted were total simulation speed in ns/day for DHFR. They aren't just the difference in FFT speed.

Ah.  My mistake.  As a user of PME (rather than a maintainer or developer), I don't see how this measurably affects me, since there's no "clear winner" in terms of performance and reliability.  If it was me, I'd opt for one of the following:

1. Ditch streams. They're unreliable for cuFFT.
2. Turn streams off by default, allow a power-user to turn them on (with caveats) through a CUDA platform property.

cuFFT without streams is probably used so extensively that NVidia couldn't introduce a bug unnoticed in it.  And any problems with the FFT is NVidia's responsibility to fix.

But you probably know better than me the maintenance overhead of adding your own FFT.

**Comment by peastman** [comment]
Ok, I propose the following then:

- Switch to using my FFT.
- As a special case, disable the stream on GTX 980.  I wish I knew whether the same issue existed on any other GPUs (970? 980 Ti?), but 980 is likely a really common GPU for people to be using, so it's worth putting in a special case to make things faster on that.
- We can then use CUDA 7 for OpenMM 6.3, since we're no longer restricted by Nvidia's bug.

**Comment by kyleabeauchamp** [comment]
Sounds reasonable to me.  I'd even be happy with skipping the 980 special case to keep it simple--we might be switching back to cuFFT at 7.5, so simplicity might be golden here.

**Comment by jchodera** [comment]
Sounds like a great plan.  @kyleabeauchamp has excellent points about maximum GPU compatibility trumping performance for the FAH use case.

**Comment by peastman** [comment]
I'm not concerned with complexity in the special case for 980: it's basically one line.  And the performance problem exists with both CUDA 6.5 and 7.0, so it seems likely it will still be true with 7.5.

**Comment by rmcgibbo** [comment]
Given how rapidly this is all changing, and that it varies significantly between different GPUs, having more than one implementation available (and the ability to do a "live" tuning/benchmarking at run time) could be wise. It might turn out that for the next model released, whatever method we choose now becomes suboptimal.

**Comment by peastman** [comment]
I'd really like to be able to do tuning at runtime.  As I discussed above, though, that isn't currently practical.  Also, the issue isn't just optimizing performance, but also avoiding bugs (some of which are nondeterministic).

**Comment by swails** [comment]
Out of curiosity -- what does this picture look like for the Amoeba plugin?

**Comment by swails** [comment]
I imagine the same, but I'm just curious.

**Comment by peastman** [comment]
Amoeba doesn't use the separate stream.  The need to iterate induced dipoles tangles up the direct and reciprocal calculations with each other, so they aren't cleanly separated.

**Comment by swails** [comment]
So would you keep cuFFT for Amoeba?  It's not a huge performance difference, but it seems to me that all of your non-stream benchmarks put cuFFT above yours.

**Comment by peastman** [comment]
That's what I was figuring on.

**Comment by swails** [comment]
Sounds good to me.

**Comment by kyleabeauchamp** [comment]
Quick question: what version of cuda did you use on the benchmarks at the top of this post?  Was that the patched version of CUDA 7?  Or CUDA 6.5?  I ask because they claim 2-3X speedups going from 6.5 to 7.0, was curious if your benchmark considered that.  (http://devblogs.nvidia.com/parallelforall/cuda-7-release-candidate-feature-overview/)

**Comment by peastman** [comment]
I tried both 6.5 and the patched 7.0.  There was no significant difference between them.
