### ISSUE TITLE
Build 6.3 beta

### ISSUE THREAD

**Issue by peastman** [pandegroup/openmm#945]
I think we're finally ready to build the beta of 6.3.  I suggest we use the current revision for it: 97ebc35690c706424ae09f67e3d5be6abe7d0d5a.  It will be built against CUDA 7.  That means we have to use 64 bit binaries on all platforms.  That's a change from the last release, where we had 32 bit binaries for Windows, but 64 bit on all other platforms.

I assume I still need to do the Windows build by hand?

**Comment by swails** [comment]
I'm running the remaining tests for #936 now.

**Comment by peastman** [comment]
Ok, we can wait for that.  Though it probably isn't essential for that fix to be in the beta.

**Comment by jchodera** [comment]
Does anyone foresee issues with upgrading our Mac Mini (our Jenkins `osx` build platform) to CUDA 7.0?  This would mean that all Omnia packages would immediately start being built with CUDA 7.0 (though I can't think of any except OpenMM that use CUDA).  I'll separately create a new `linux` VM image for CUDA 7.

If so, I can start doing test builds of `6.3-beta` (what will the full version number be?) on `osx` and `linux`.

If there would be a problem, I could try to use the `osx` VM @rmcgibbo built some time ago.

**Comment by jchodera** [comment]
We don't yet have windows builds working through Jenkins, but I wonder if a modified version of the Appveyor scripts could build and package.  @rmcgibbo: Do you think this would be possible?

**Comment by kyleabeauchamp** [comment]
PS: I suspect the linux image might be as simple as re-provisioning our existing one.  In the past, NVIDIA has essentially done a forced upgrade whenever we run `yum update`

**Comment by jchodera** [comment]
This might also be a good opportunity for me to make a new image of the re-provisioned vagrant image, and cache it locally.  That would save a huge amount of time, and prevent unwanted upgrades from causing trouble in the future.

**Comment by peastman** [comment]
Ok, both of the bug fixes are merged.  So let's build them from revision 7fd8791aed02758fa2d6d53d4a60a28afe779122.

**Comment by kyleabeauchamp** [comment]
Maybe make a github beta release as the target?

**Comment by jchodera** [comment]
+1 for GitHub beta release target

**Comment by jchodera** [comment]
A versions beta number is also helpful in case we end up building more than one!

**Comment by rmcgibbo** [comment]
I'm not sure if we can do CUDA on Appveyor. I think it needs to be done by hand.

**Comment by peastman** [comment]
Is everyone agreed on that being the revision to use?

**Comment by swails** [comment]
Good for me.

**Comment by jchodera** [comment]
Should we also include some release notes with what has been updated since
6.2? Or is that a separate document that doesn't get packaged?

**Comment by peastman** [comment]
When I send out the announcement, I always include a discussion of new features.

**Comment by peastman** [comment]
Tag is created: 6.3beta1

**Comment by jchodera** [comment]
Source package: https://jenkins.choderalab.org/job/package-openmm-source/ws/packaging/

**Comment by jchodera** [comment]
`osx` package: https://jenkins.choderalab.org/job/package-openmm-osx/ws/packaging/

**Comment by jchodera** [comment]
`linux` package: https://jenkins.choderalab.org/job/package-openmm-linux-vagrant/ws/packaging/

I think all the draft packages from our end are ready for inspection, @peastman.  We may need to update the [manifest lists](https://github.com/pandegroup/openmm/tree/master/devtools/packaging/manifests), for example.

**Comment by peastman** [comment]
The Linux zip is missing the PDF manuals.  For the moment I'll just copy them over from the Mac build.  We should fix that before the release.

**Comment by peastman** [comment]
The builds are posted on the downloads page at simtk.org.  (Click "List all hidden releases" to see them.)  Can everyone try them out and make sure they work?  Just verify that installation goes correctly and testInstallation passes.  Then I'll send out an announcement.

**Comment by rmcgibbo** [comment]
The linux binary package works great for me on Ubuntu 14.04. All four platforms pass.

**Comment by rmcgibbo** [comment]
It might be a good idea to update the `install.sh` script to, if `nvcc` is in the `PATH`, check the CUDA version and give helpful instructions if it's less than 7.0. I suspect that many OpenMM users may not have yet upgraded to CUDA 7, and might miss the note on the download page.

**Comment by rmcgibbo** [comment]
Should update conda-recipes to build the 6.3beta1 tag for conda and put it on binstar?

**Comment by rmcgibbo** [comment]
The first time through, I got the following error on OS X. https://gist.github.com/rmcgibbo/7b8b7981597f136ae5be

The reason is that I was using a python that already had OpenMM 6.2.0 installed via conda, and the header 6.2 header files were being included over the 6.3 header files. Running `conda uninstall openmm` before running the installer fixed the issue, and `testInstallation` ran successfully on two platforms (no GPU on this laptop).

**Comment by peastman** [comment]
Anyone else?  And has anyone tried either of the other versions?

**Comment by jchodera** [comment]
What would be a good test?  I can automate some testing.

How about:
* grab and unpack tarballs
* set OPENMM environment variables
* run openmmtools `test_openmm_platforms`

**Comment by peastman** [comment]
Just do exactly what I described: install it by running the install.sh script (or for Windows, by following the instructions in the manual), then verify that testInstallation works.

**Comment by mpharrigan** [comment]
I don't have a "list hidden releases" button (simtk user: mpharrigan)

**Comment by peastman** [comment]
I just added you.

**Comment by mpharrigan** [comment]
Tried to install on win64

Issue 1:
![capture](https://cloud.githubusercontent.com/assets/4967059/8072432/a01ecc78-0eca-11e5-9ddc-852005ebf74e.PNG)

If you can fix that, it would probably be better :)

Issue 2:
Can we build against python 3.4? I'd imagine most people have moved to 3.4

**Comment by peastman** [comment]
Looks like you have overactive virus protection.  I've never heard of that screen before.

**Comment by mpharrigan** [comment]
It's windows 8

**Comment by mpharrigan** [comment]
ok I installed python 3.3 with conda, but the installer couldn't find it.

P.s. the author is Randall J. Radmer (might want to change)

**Comment by peastman** [comment]
Here are a couple of websites discussing this:

http://stackoverflow.com/questions/12311203/how-to-pass-the-smart-screen-on-win8-when-install-a-signed-application

http://www.askvg.com/how-to-disable-smartscreen-filter-in-windows-8/

As I understand it, here's the deal.  Microsoft really wants *all* Windows applications to be distributed through their app store.  That's the only sure way to get rid of this message.  Any other application downloaded from the internet will potentially display this message.  However, every time that happens, it reports back to Microsoft.  When enough people have run a particular application without anyone reporting it as malicious, they figure it probably isn't malicious and stop showing the message for it.

Anyway, that's my reading of it, though I might not have that exactly right.

**Comment by peastman** [comment]
Has anyone checked the Mac build?  I don't have a Mac with an Nvidia GPU.

**Comment by rmcgibbo** [comment]
I tried the CPU platform on my mac laptop, but I don't have a GPU mac either. Does anyone in PG?

**Comment by swails** [comment]
My Mac GPU is a 9400 or something.  compute capability 1.0 or 1.1, at most.  Doesn't work for OpenMM, so I can't say.  Only the Reference and CPU platforms exist (OS X 10.10.3).  I thought OpenCL was fixed for my OS X version?  Any reason it's not available?

On my Linux box (Gentoo), installation works and all but the CUDA platform are available (I am still on CUDA 6.5).  I'm installing CUDA 7 now to try.

**Comment by swails** [comment]
Upgrading to CUDA 7.0 worked.  CUDA platform available now.

**Comment by peastman** [comment]
The OpenCL libraries are missing from the Mac build.  John, can you look into that?

**Comment by jchodera** [comment]
I imagine you need to change the build scripts so that the OpenCL build is no longer disabled:
https://github.com/pandegroup/openmm/blob/master/devtools/packaging/scripts/osx/build.sh#L25-L29

**Comment by swails** [comment]
And the conda recipe:

```bash
elif [[ "$OSTYPE" == "darwin"* ]]; then
    CMAKE_FLAGS+=" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++"
    CMAKE_FLAGS+=" -DCMAKE_OSX_DEPLOYMENT_TARGET=10.7"
    CMAKE_FLAGS+=" -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk"
    CMAKE_FLAGS+=" -DOPENMM_BUILD_OPENCL_LIB=OFF -DOPENMM_BUILD_DRUDE_OPENCL_LIB=OFF -DOPENMM_BUILD_RPMD_OPENCL_LIB=OFF -DOPENMM_BUILD_OPENCL_TESTS=FALSE -DOPENMM_BUILD_OPENCL_DOUBLE_PRECISION_TESTS=FALSE" # Don't build OpenCL on OS X
fi
```

**Comment by jchodera** [comment]
Both the `openmm-dev` and `openmm` recipes, right?

**Comment by jchodera** [comment]
The `openmm` recipe is here:
https://github.com/omnia-md/conda-recipes/tree/master/openmm

At @rmcgibbo's request, the `openmm-dev` recipe is now here:
https://github.com/omnia-md/openmm-dev

**Comment by jchodera** [comment]
I'll create a PR for all of these changes shortly.

**Comment by peastman** [comment]
I just uploaded a new version of the Windows package.  I added a Python 3.4 installer (in addition to the 3.3 installer, which is still there).

**Comment by jchodera** [comment]
Updated Mac OS X packaged build to now include OpenCL libs:
https://jenkins.choderalab.org/job/package-openmm-osx/ws/packaging/

**Comment by peastman** [comment]
New Mac build is posted to the download page.

**Comment by jchodera** [comment]
I tried the new Mac build on our Jenkins Mac Mini (MacMini6,2 with OS 10.9.5 and Intel HD Graphics 4000):
```
mski1620:openmm-6.3 choderalab$ python -m simtk.testInstallation
There are 2 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 2.00787e-06
```

Only problem is that I am building from my branch because the changes are not merged into the release, which means that the version numbers are wrong:
```
>>> import simtk.openmm as mm
>>> print mm.version.full_version
6.3.0.dev-47d97e7
```
Can you cut a new

**Comment by swails** [comment]
Note you need at least 10.10.3 (I *think*) for the OpenCL fix...

**Comment by peastman** [comment]
Ok, I'm going to send out the announcement to the beta testers mailing list.

**Comment by jchodera** [comment]
Don't you want to hold off until we look into https://github.com/pandegroup/openmm/issues/962 ?

**Comment by peastman** [comment]
No, I don't think we need to delay the beta for that.  It can be fixed in the final release.

**Comment by jchodera** [comment]
How about using the issue tagging system to keep track of things that
remain to be fixed before final release?  That way, we at least know you
saw the issue and intend for it to be addressed before then.

**Comment by peastman** [comment]
Don't worry: the final release won't go out until everyone agrees it's ready.  The beta is about getting the new features in the hands of users as early as possible.  It doesn't need to be bug free.  The final release is a different matter.

**Comment by jchodera** [comment]
That's totally fine.  I just think tagging remaining issues will help with inter-developer communication.

**Comment by Zedonboy** [comment]
Hello, am using Intel HD graphics 4000, and i know CUDA is not for me. I want to build it from source.
I have passed all the requirement except CUDA-toolkit,  how do i go about it?

**Comment by jchodera** [comment]
There's an extensive section in the User Guide describing how to build from source (with or without CUDA):
http://docs.openmm.org/latest/userguide/library.html#compiling-openmm-from-source-code

**Comment by Zedonboy** [comment]
Thank You Sir, searched Google(Blind enough not to find it)

Sent from Mail for Windows 10
