### ISSUE TITLE
AMD GPU Windows performance finding

### ISSUE THREAD

**Issue by informatorius** [pandegroup/openmm#949]
I found when building OpenMM 6.2 on Windows with AMD APP SDK 2.9 instead of NVIDIA CUDA 6.5 then running FahBench 2.0.2 is 40% faster on AMD GPU R9 280.
see https://github.com/pandegroup/fahbench/issues/15
Is this a problem in OpenMM code?

**Comment by peastman** [comment]
How did you reach that conclusion?  It would be *very* strange if that actually made a difference.  It's a completely standardized C API, and we don't statically link to anything.

**Comment by informatorius** [comment]
When I build OpenMM in Windows I have to compile to a OpenCL.h and link to a OpenCL.lib and this is where I choose either from Nvidia CUDA SDK  or AMD APP SDK.

When I run FahBench using the OpenMMOpenCL.dll build with AMD then it 40% faster on my AMD GPU. When I replace it by OpenMMOpenCL.dll build with Nvidia then it is 40% slower on my AMD GPU.

I tested also with Nvidia GPU GTX 970 but there is no difference.
I had also expected that AMD GPU had no difference and this is why i made this issue.

(There is also this F@H forum discussion going on if this could be the reason why AMD GPUs are slow with FahCore_18 using OpenMM 6.1 https://foldingforum.org/viewtopic.php?f=66&t=27418&start=45)

**Comment by peastman** [comment]
I'm very skeptical, but we'll see.  Try building using the OpenCL.h from Nvidia and the OpenCL.lib from AMD.  What happens?  Now what if you reverse that?

**Comment by informatorius** [comment]
Visual Studio 2013 rebuild OpenMMOpenCL release 64bit with AMD APP SDK 2.9 and Nvidia Cuda 6.5 and copy OpenMMOpenCL.dll to FahBench\lib\plugins folder.

The mix AMD OpenCL.h and nvidia OpenCL.lib failed to link with unresolved external symbol clRetainDevice + clReleaseDevice.

Then run FahBench_cmd.exe on AMD GPU R9 280 with AMD 14.12 driver on Windows 7 64bit. 

amd_h_amd_lib 38 ns/day
nvidia_h_amd_lib 38 ns/day
amd_h_nvidia_lib unresolved external symbol clRetainDevice + clReleaseDevice
nvidia_h_nvidia_lib 27 ns/day

Maybe someone on your side can try it to see if the result is reproducable or which settings i use may be different.

**Comment by informatorius** [comment]
peastman could reproduce the issue, see
https://github.com/pandegroup/openmm/issues/969#issuecomment-114600569

**Comment by informatorius** [comment]
Maybe a hint could be presented on OpenMM download page that building OpenMM with AMD APP SDK will improve performance on AMD GPUs and not change performance on Nvidia GPUs.

**Comment by peastman** [comment]
For the precompiled binaries, we'll build all of them against AMD.  For people who are building OpenMM themselves, they'll presumably build against whatever OpenCL library they'll actually be running with.
