### ISSUE TITLE
Thoughts on MTS performance

### ISSUE THREAD

**Issue by kyleabeauchamp** [pandegroup/openmm#951]
Does anyone have any thoughts on how to make the MTS integrators go faster?  I find that there's a pretty substantial performance hit (15% - 40%) on DHFR even with the "simplest" force decomposition of bonded / nonbonded.  My driver script and benchmark timings (ns / day in the comments) are below:

```
import time
import simtk.openmm.app as app
import simtk.openmm as mm
from simtk import unit as u
from openmmtools import hmc_integrators, testsystems, integrators

#testsystem = testsystems.DHFRExplicit()
testsystem = testsystems.DHFRExplicit(rigid_water=False, constraints=None)

system, topology, positions = testsystem.system, testsystem.topology, testsystem.positions

platform = mm.Platform.getPlatformByName('CUDA')
#properties = {}
properties = {'CudaPrecision': "single"}

temperature = 1 * u.kelvin
timestep = 4.0 * u.femtoseconds
steps = 5000

#hmc_integrators.guess_force_groups(system, nonbonded=1, others=2, fft=0)
#groups = [(0, 1), (1, 2), (2, 4)]  # 59.3 ns / day

#hmc_integrators.guess_force_groups(system, nonbonded=0, others=1, fft=0)
#groups = [(0, 1), (1, 4)]  # 79.4 ns / day

#hmc_integrators.guess_force_groups(system, nonbonded=0, others=1, fft=0)
#groups = [(0, 1), (1, 2)]  # 98.5 ns / day

#hmc_integrators.guess_force_groups(system, nonbonded=0, others=0, fft=0)
#groups = [(0, 1), (1, 2)]  # 94.2

#hmc_integrators.guess_force_groups(system, nonbonded=0, others=0, fft=0)
#groups = [(0, 1), (1, 4)]  # 78.1 CUDA, 0.317 CPU

hmc_integrators.guess_force_groups(system, nonbonded=0, others=0, fft=0)
groups = [(1, 1)]  # Just update velocities and positions

#hmc_integrators.guess_force_groups(system, nonbonded=0, others=0, fft=0)
#groups = [(0, 1)]  # 111.6 ns / day CUDA, 1.065 CPU

integrator = mm.MTSIntegrator(timestep, groups)
simulation = app.Simulation(topology, system, integrator, platform=platform, platformProperties=properties)

simulation.context.setPositions(positions)
simulation.context.setVelocitiesToTemperature(temperature)

integrator.step(1)

t0 = time.time()
integrator.step(steps)
dt = time.time() - t0
outer_per_day = steps / dt * 60 * 60 * 24
outer_per_sec = steps / dt
inner_per_sec = outer_per_sec * groups[-1][1]
ns_per_day = (timestep / u.nanoseconds) * outer_per_day


dt, ns_per_day, outer_per_sec, inner_per_sec

```

**Comment by kyleabeauchamp** [comment]
This is CUDA 6.5, GTX 960, (nearly) latest git version of OpenMM.

**Comment by rmcgibbo** [comment]
Well it's "slower" because in each outer timestep, you're increasing the amount of work (calculating all the other forces twice or four times, and doing one or three extra updates to the positions and velocities.

**Comment by kyleabeauchamp** [comment]
Yeah, I guess I'm just surprised at the 40% performance loss due to recalculating the bonded forces, positions, and velocities.

**Comment by jchodera** [comment]
That does seem like a weird performance hit.  If you did this on the CPU or Reference platforms, for example, you'd expect the difference to be minimal. There must be something about the GPU kernels?

**Comment by rmcgibbo** [comment]
Yeah, that's fair. I don't have a good intuition for the breakdown in the work per timestep, and the overhead for kernel launches and stuff. You probably would have to look at this in the profiler.

**Comment by kyleabeauchamp** [comment]
OK, I did two more experiments, where everything has the same force group but I still do 2 or 4 "dummy" integration steps in the MTS.  This leads to exactly the same performance as when I do 2 or 4 steps of the bonded forces.  I have updated my above codeblock to include this data.  

I thus conclude that the additional position and velocity updates are the bottleneck.

**Comment by rmcgibbo** [comment]
Did you try by chance using the CPU platform? Does the difference go away there?

**Comment by kyleabeauchamp** [comment]
CPU numbers: 1.065 ns/day for `groups=[(0, 1)]`, 0.317 ns/day for `groups = [(0, 1), (1, 4)]` with an empty group 1.  Seems like the relative difference is even worse for CPU.

**Comment by jchodera** [comment]
I wonder if it's the constraint code.  Perhaps you could try again with DHFR created with `constraints=None` and `rigid_water=False` (with a smaller timestep)?

**Comment by swails** [comment]
The only force that has any expense of significant consequence is the nonbonded force. [1] Kernel launches are super cheap, and they're not performed inside some tight loop, so they won't have a noticeable affect.  I wonder if there is some GPU->CPU data transfer happening that is slowing things down.  For instance, the custom integrator caches forces that it has already computed to avoid computing them again (see [here](https://github.com/pandegroup/openmm/blob/master/platforms/cuda/src/CudaKernels.cpp#L6205-L6213)).  But if this involves communicating data, it could definitely result in a slowdown.

[1] Example (CPU) timings taken from one of my simulations with Amber:

```
|     Nonbond        2608.50
|     Bond              1.33 
|     Angle            11.81
|     Dihedral         43.85
|     Shake            24.64
```

That's 97% of the time spent in the nonbonded sum (I expect GPU breakdown to be similar, since the bonded computations lend themselves just fine to GPU parallelization).  Even SHAKE is basically negligible (although may be less-so on a GPU, probably not *that* much worse).

**Comment by kyleabeauchamp** [comment]
With no constraints and a 1 fs timestep (CUDA), I still see about a 30% slowdown when I do 4 iterations of dummy position updates.

In both numbers, group (1) is empty:
28.253705481121727 ns / day (groups = [(0, 1)])
20.84117421481621 ns / day (groups = [(0, 1), (1, 4)])

**Comment by peastman** [comment]
You aren't using the integrator in the way it's normally used.  Usually the goal is to compute the slow forces less often, while continuing to compute the fast forces at the same frequency  You're doing the opposite: computing the fast forces *more* often, while continuing to compute the slow ones at the same frequency.  So of course that's slower.  You're doing more work without getting any benefit from it.

Remember that even the "fast" forces aren't free, and there's also other parts to the calculation (integration, constraints).  Those have to be done for every innermost time step.

**Comment by rmcgibbo** [comment]
@peastman that was basically my question too, but I think Kyle's point is that, yes, he realized it would be slower by _some_ amount. He was surprised by the fact that that amount was 40%.

**Comment by jchodera** [comment]
Presumably, @kyleabeauchamp is also pointing this out because the overhead of using MTS at all is giving him very poor performance compared to standard integrators, and it is surprising that the overhead would be so large when the extra operations involved are generally negligible cost compared to the nonbonded force computation.

**Comment by kyleabeauchamp** [comment]
Yeah, my point here is that there's a pretty substantial overhead (>40%) as soon as the MTS splitting is anything more complicated than [(0, 1)] or [(0, 1), (1, 2)]).  This 40% overhead really eats into the potential performance gains, as we're really only expecting to be able to increase the outer timestep by 2 or 3 fold.

**Comment by peastman** [comment]
> With no constraints and a 1 fs timestep (CUDA), I still see about a 30% slowdown when I do 4 iterations of dummy position updates.

Let x be the cost of force calculations and y the cost of everything else (integration, miscellaneous overhead).

x+4y = 1.3(x+y)
2.7y = 0.3x
x = 9y

So with an ordinary integrator (not MTS), forces account for 90% of the time and "everything else" is about 10%.  That's about what I would have guessed.  It will, of course, depend strongly on the size of your system.  DHFR is pretty small by modern standards, and for a larger system the forces would probably be a larger fraction.

**Comment by kyleabeauchamp** [comment]
So my thought experiment with no constraints seems to suggest that the "everything else" that takes up 10% of the calculation is simply the velocities and position updates.  I guess that was surprising to me, but you obviously have the most intuition on these things.

**Comment by peastman** [comment]
There's a little more than that.  There are certain buffers that need to be cleared at the start of each time step.  You didn't mention whether you had a thermostat, but if so, there's random number generation.  Also, are you sure you really didn't have any constraints?  (You specified rigidWater=false, right?)

It also can depend on the type of device you're using and the precision mode.  If you're using mixed precision on a consumer level Nvidia GPU, the integration will be disproportionately expensive since that's one of the few things done in double precision, and those GPUs have absurdly bad double precision performance.

**Comment by kyleabeauchamp** [comment]
This is no thermostat, rigidWater=False.  I explicitly checked the number of constraints.  

I've tried both mixed and single precision with the same 40% overhead.

**Comment by kyleabeauchamp** [comment]
PS: I also think that DHFR is still a worthy target for performance tuning.  While it's definitely smaller than kinases, it's still the industry standard benchmark system.

**Comment by kyleabeauchamp** [comment]
I did one more thought experiment.  I set `groups = [(1, 1)]`, where force group 1 is *empty*.  This means I'm basically just repeatedly updating the positions and velocities.  With no constraints, I'm getting 880 ns / day at 4 fs.  I believe this amounts to 2500 position updates per second (single precision).  If I do a simple python script to increment the same size arrays, I get 15000 updates per second with double precision (code below).  

```
import time
import numpy as np

x = np.random.normal(size=(23358, 3))
v = np.random.normal(size=(23358, 3))

def update(x, v, n):
  for dt in np.linspace(0, 1, n):
    x += dt
    v += dt
  
n_iter = 100000
t0 = time.time()
update(x, v, n_iter)
dt = time.time() - t0

ips = n_iter / dt

```

**Comment by peastman** [comment]
#1056 should improve this somewhat.  When I add four empty steps for each real step, I now get a slowdown of about 15%.

**Comment by peastman** [comment]
With #1057, the overhead for adding four empty steps is down to about 12%.

**Comment by jchodera** [comment]
Great!  I'm just waiting for the `openmm-dev` package to build so I can test!

**Comment by kyleabeauchamp** [comment]
I ran the tests in below code block and see better performance as mentioned by @peastman.  Interestingly, CUDA 7.0 and OpenMM 6.3 seem to also give speedups over what I saw previously.  The numbers are on my GTX 960.

```
import time
import simtk.openmm.app as app
import simtk.openmm as mm
from simtk import unit as u
from openmmtools import hmc_integrators, testsystems, integrators

#testsystem = testsystems.DHFRExplicit()
testsystem = testsystems.DHFRExplicit(rigid_water=False, constraints=None)

system, topology, positions = testsystem.system, testsystem.topology, testsystem.positions

platform = mm.Platform.getPlatformByName('CUDA')
properties = {'CudaPrecision': "single"}

temperature = 1 * u.kelvin
timestep = 4.0 * u.femtoseconds
steps = 5000

#hmc_integrators.guess_force_groups(system, nonbonded=1, others=2, fft=0)
#groups = [(0, 1), (1, 2), (2, 4)]
# 6.3.0.dev-637de3d 24.6592772007 70.0750466421 202.763445145 811.05378058
# 6.3.0.dev-9b345f2 23.4379329681 73.7266380252 213.329392434 853.317569736

hmc_integrators.guess_force_groups(system, nonbonded=0, others=1, fft=0)
groups = [(0, 1), (1, 1)]
# 6.3.0.dev-637de3d 60.368131876 28.6243742568 82.8251569929 82.8251569929
# 6.3.0.dev-9b345f2 59.918735981 28.8390596315 83.4463531004 83.4463531004



integrator = mm.MTSIntegrator(timestep, groups)
simulation = app.Simulation(topology, system, integrator, platform=platform, platformProperties=properties)

simulation.context.setPositions(positions)
simulation.context.setVelocitiesToTemperature(temperature)

integrator.step(1)

t0 = time.time()
integrator.step(steps)
dt = time.time() - t0
outer_per_day = steps / dt * 60 * 60 * 24
outer_per_sec = steps / dt
inner_per_sec = outer_per_sec * groups[-1][1]
ns_per_day = (timestep / u.nanoseconds) * outer_per_day


print mm.version.full_version, dt, ns_per_day, outer_per_sec, inner_per_sec
```

**Comment by peastman** [comment]
I notice you specified

```
hmc_integrators.guess_force_groups(system, nonbonded=0, others=1, fft=0)
```

Does "others=1" mean that bonded forces are in group 1?  If so, does that mean when you specify [(0,1)], the bonded forces are being completely omitted?

**Comment by kyleabeauchamp** [comment]
Others=1 would mean that the bonded forces are in group 1.  

However, I only specify `groups=[(0, 1)]` with the other call to `guess_force_groups`.  So neither condition led to omitted bonded forces---the choice is either bonded forces once or bonded forces four times per outer timestep.

**Comment by peastman** [comment]
Just to be sure I'm clear: when you specified groups=[(0,1)], you also specified others=0, correct?  Because if you did specify others=1, and never told the integrator to evaluate group 1, then bonded forces would be skipped.

**Comment by kyleabeauchamp** [comment]
Correct.  The commented code blocks were grouped accordingly.

**Comment by mrinal-shekhar** [comment]
@kyleabeauchamp  was this issue ever solved?

**Comment by kyleabeauchamp** [comment]
I'm not sure.  I never identified a smoking gun, so it was never obvious that there was anything obvious to fix.  However, perhaps there have been various performance improvements over the past couple of years.
