### ISSUE TITLE
Check context before integrator.step()?

### ISSUE THREAD

**Issue by kyleabeauchamp** [pandegroup/openmm#957]
So the following code causes a segmentation fault.  According to the source (https://github.com/pandegroup/openmm/blob/master/openmmapi/src/VerletIntegrator.cpp#L72), shouldn't it be easy enough to check that the context pointer is non-null before the `for` loop?

```
import simtk.openmm as mm
integrator = mm.VerletIntegrator(1.0)
integrator.step(1)
```

**Comment by jchodera** [comment]
Good catch!

**Comment by jchodera** [comment]
I can confirm that this bug is present in `6.3.0.dev-13d366a`.

**Comment by kyleabeauchamp** [comment]
Ive also seen this with customintegrator
