### ISSUE TITLE
Cannot build OpenMM with out shared libs enabled

### ISSUE THREAD

**Issue by jcoffland** [pandegroup/openmm#965]
If I try to configure cmake to build with out shared libs I get this error:

```
 CMake Error at CMakeLists.txt:303 (ADD_DEPENDENCIES):
   Cannot add target-level dependencies to non-existent target "OpenMM".

   The add_dependencies works for top-level logical targets created by the
   add_executable, add_library, or add_custom_target commands.  If you want to
   add file-level dependencies see the DEPENDS option of the add_custom_target
   and add_custom_command commands.
```

**Comment by peastman** [comment]
How exactly are you running cmake?  And what version are you using?

**Comment by jcoffland** [comment]
I used ```ccmake -i``` and turned off shared libs.  I got this error both with v6.2 and the head of master branch.

**Comment by jchodera** [comment]
Can you give us a bit more info about what versions of tools you are using?
As you can see, Travis compiled with static libs just fine, it seems.
Maybe I can try to reproduce your issue locally?

**Comment by swails** [comment]
@jcoffland -- do you still see this to be the case?  (Also, the OS is probably important information -- Macs love them some shared libraries, so I don't know that static-only Mac builds will even work)

**Comment by jchodera** [comment]
Can this be closed?
