### ISSUE TITLE
CPU Plug-in fails to compile on MSVC2013

### ISSUE THREAD

**Issue by mpharrigan** [pandegroup/openmm#968]
Release, x64 without PME or fftw

```
Error	4807	error C2668: 'min' : ambiguous call to overloaded function	platforms\cpu\src\CpuNonbondedForceVec4.cpp	67	1	OpenMMCPU

Error	4813	error C2668: 'min' : ambiguous call to overloaded function	platforms\cpu\src\CpuNonbondedForceVec4.cpp	231	1	OpenMMCPU
```

many times.

Using the 6.3-beta1 tag

**Comment by peastman** [comment]
Try adding the following at line 29 of SimTKOpenMMRealType.h, immediately before the #include \<cmath>:

```C++
#ifdef _MSC_VER
    // Prevent Windows from defining macros that interfere with other code.
    #define NOMINMAX
#endif
```

Does that fix it?

**Comment by mpharrigan** [comment]
I'll check that this evening [windows desktop is at home]

**Comment by swails** [comment]
Perhaps a more permanent fix is to switch to Linux :).

**Comment by informatorius** [comment]
To fix the problem locally I add to CpuNonbondedForceVec4.cpp
include <algorithm>
