### ISSUE TITLE
Faster GPU-only LocalEnergyMinimizer

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#970]
It would be great if we could have a GPU-only local energy minimizer that was faster than the existing `LocalEnergyMinimizer` for an upcoming OpenMM version.

**Comment by rmcgibbo** [comment]
I wrote [Nesterov gradient descent](https://blogs.princeton.edu/imabandit/2013/04/01/acceleratedgradientdescent/) as a custom integrator before. The looping was a lot faster, but each iteration wasn't quite as good as BFGS. I didn't tweak it much. It's probably possible to squeeze more performance out of it.

**Comment by rmcgibbo** [comment]
I don't recall how I estimated the lipshitz constant, but I suspect that makes a big practical difference, since there's not line search.

**Comment by jchodera** [comment]
I imagine L-BFGS could be coded as a GPU kernel.  That would have both the advantage of faster looping and good minimization performance.

**Comment by jchodera** [comment]
I've also written a [`GradientDescentMinimizationIntegrator`](https://github.com/choderalab/openmmtools/blob/master/openmmtools/integrators.py#L120-L185) for [`openmmtools`](https://github.com/choderalab/openmmtools).

**Comment by rmcgibbo** [comment]
It probably _could_, but L-BFGS is awfully complicated. Like, a couple thousand lines of fortran. Perhaps e.g. https://github.com/jwetzl/CudaLBFGS, but this is not a trivial task.

**Comment by rmcgibbo** [comment]
You should use Nesterov. It's faster than standard gradient descent, essentially for free.

**Comment by jchodera** [comment]
Would you mind contributing your implementation of Nesterov to [`openmmtools`](https://github.com/choderalab/openmmtools)?

**Comment by jchodera** [comment]
[Nocedal's L-BFGS-B code](http://users.iems.northwestern.edu/~nocedal/lbfgsb.html) is definitely substantial, but I wasn't suggesting we implement L-BFGS-B with all the bells and whistles.  We just need a basic implementation of L-BFGS that is tuned to our problem domain.

**Comment by jchodera** [comment]
[Nocedal's L-BFGS code](http://users.iems.northwestern.edu/~nocedal/lbfgs.html) is maybe ~1000 lines of Fortran, half of which are comments.

**Comment by rmcgibbo** [comment]
Still pretty complex... All I can say is that I'm not volunteering.

Here's my source code for Neserov: https://github.com/rmcgibbo/openmm-cookbook/blob/master/02-nesterov-minimization.ipynb. I'll contribute it over there when I get some free time.

**Comment by rmcgibbo** [comment]
Also, I suspect that the most important part is properly handling the constraints. The penalty scheme used currently is probably not the only way -- someone might be able to come up with something faster.

**Comment by jchodera** [comment]
I wonder if even a low-temperature Langevin simulation with some adaptive step size would work just as well in most cases...

**Comment by jchodera** [comment]
Do you use constraints in your Nesterov implementation?

**Comment by rmcgibbo** [comment]
No, I didn't do constraints in that. But I think you can -- there is such thing as a projected nesterov with provable convergence stuff.

**Comment by jchodera** [comment]
This seems to be redundant with #1237 now.
