### ISSUE TITLE
openmm-dev has not been recently updated

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#971]
Just a heads-up that I just realized the Linux openmm-dev hasn't recently been updating automatically:
https://binstar.org/omnia/openmm-dev/files

Working on fixing that now.

**Comment by jchodera** [comment]
Fixed!

**Comment by jchodera** [comment]
Actually, I realize we are only building `openmm-dev` for python 2.7 on Jenkins, but there are older versions on binstar for python 3.3 and 3.4:
https://binstar.org/omnia/openmm-dev/files

We presumably want to build all variants, yes?

Unfortunately, my attempt to do this with Jenkins by doing `conda build` inside conda environments doesn't seem to be working.  See:
https://jenkins.choderalab.org/job/conda-openmm-dev-osx-2/

All environments seem to build the same python 2.7 version of OpenMM.

I wonder if I have to do something more like the completely distinct build matrix environments of travis.

Or, we could re-enable `openmm-dev` builds on travis...?

**Comment by rmcgibbo** [comment]
To change the version of python that `conda build` uses, you either set the CONDA_PY environment variable. See the conda docs: http://conda.pydata.org/docs/building/recipe.html#environment-variables-that-affect-the-build-process You can also equivalently pass `--python` to `conda build`.

Changing the version of python in the current active env, as you appear to be doing https://jenkins.choderalab.org/job/conda-openmm-dev-osx-2/configure, doesn't do anything.

**Comment by jchodera** [comment]
Thanks, @rmcgibbo!  I think I've fixed this for `osx` now, and am working on fixing it for `linux`:
https://jenkins.choderalab.org/job/conda-openmm-dev-osx-2/configure

**Comment by jchodera** [comment]
I'm not sure if you've seen this warning in the conda builds before, but it seems to crop up all the time:
```
dev-post-link.sh: line 32: /Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/envs/_test/bin/python: No such file or directory
```

**Comment by jchodera** [comment]
I had neglected to update the [`openmm-dev` conda recipe](https://github.com/omnia-md/openmm-dev) to match the 6.3 beta binary release, so I've done that now:
https://github.com/omnia-md/openmm-dev/pull/2

Rebuilding all `openmm-dev` packages.

**Comment by jchodera** [comment]
This should be working now.
