### ISSUE TITLE
Allow different force groups for nonbonded forces in GPU platforms

### ISSUE THREAD

**Issue by swails** [pandegroup/openmm#974]
As a proposed enhancement, it would be great to allow different nonbonded forces to be assigned to different force groups, which is currently possible only in the CPU and Reference platforms.

This feature is going to be necessary to introduce some of the resonance-free, isokinetic multiple time stepping integrators that Mark Tuckerman's group has been working on.  (@peastman -- you can add the enhancement label to this if we want to start using labels for our issues)

**Comment by peastman** [comment]
I have an idea in mind for how to implement this and #975.  It will involve relaxing but not completely eliminating the various restrictions on nonbonded forces in the CUDA and OpenCL platforms.  Would the following be acceptable for everyone?

1. Nonbonded forces will no longer be required to all be in the same force group.

2. All nonbonded forces *in a particular force group* must have the same cutoff, but different force groups can have different cutoffs.

3. All nonbonded forces will still be required to have identical exclusions, just as they do now.

**Comment by swails** [comment]
+1.  Completely covers my use-cases.

For the third point, I believe that a clever use of `CustomBondForce` will be sufficient to completely work around any real restriction that institutes, if someone *needs* different exclusions.

**Comment by swails** [comment]
cc #975.  @peastman mentioned a fix to #975 in his second point.  So refer to that thread for the second part of this request.

**Comment by jchodera** [comment]
This sounds great!  Would definitely use this feature.

**Comment by Lnaden** [comment]
+1 on this. 

One question though, does the identical exclusions requirement mean that all molecules with exclusions must appear in all `NonbondedForce` objects, or simply that if a molecule with exclusions appears in `NonbondedForce` 1, it must have the same exclusions (and atoms) if it also appears in `NonbondedForce` 2?

**Comment by peastman** [comment]
It means that all nonbonded forces (NonbondedForce, CustomNonbondedForce, etc.) must have precisely identical lists of exclusions.  If the interaction between two atoms is excluded in one, it must be excluded in all of them.  That's because it only stores one list of exclusions that needs to be shared by all of them.

**Comment by jchodera** [comment]
What about interaction groups?  Can these continue to be different in different forces?

**Comment by peastman** [comment]
Interaction groups are strictly internal to a CustomForce object.   If you have two of those, there's no requirement the interaction groups be the same.  The restrictions only apply to forces computed by CudaNonbondedUtilities and OpenCLNonbondedUtilities.

**Comment by peastman** [comment]
This is implemented by #1030.
