### ISSUE TITLE
Allow multiple cutoffs to be used in different nonbonded forces

### ISSUE THREAD

**Issue by swails** [pandegroup/openmm#975]
This is closely related to #974, and only applies to the GPU platforms (CPU platforms already allow this).  The reason this is not currently possible is that the GPU platforms coalesce all of the nonbonded forces into the same nonbonded loop and computes all of the energies and forces in one go.

This is good for performance in most cases, but there are some use cases associated with some advanced multiple time-stepping integrators in which you'd want to be able to compute long-range and short-range forces with different frequencies.  This is currently possible using a `CustomNonbondedForce` and using the `step` function in the Lepton expression to implement whatever cutoff you want.  But then you end up computing 0 a lot, which loses efficiency.

The reason this is a separate issue from #974 is because it will require far more changes internally, and it can currently be worked around (#974 cannot).

**Comment by peastman** [comment]
Can we combine this with #974?  They really are just different aspects of the same feature.  And both of them apply only to the GPU platforms.

**Comment by swails** [comment]
I put them separate because based on our discussions I thought it would be easier to get #974 in first, and then bang this one out later.  Because after all, only #974 is really *needed* to start playing with these integrators.

But based on your proposal there, I agree they can be combined.
