### ISSUE TITLE
new GPU MD code paper of interest

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#976]
This may interest some folks:
http://arxiv.org/abs/1506.05094

**Comment by peastman** [comment]
What they're doing is *extremely* primitive.  Much less sophisticated than most existing codes.  As for the claim that, "It has a performance that is comparable to other GPU-MD codes at large system sizes and substantially better at smaller sizes," well, the only code they actually compare it to is LAMMPS, and the way they did the benchmarking makes it nearly meaningless.  For example, they only ran the benchmark simulations of their code for 1000 time steps, and they didn't actually run any simulations with LAMMPS at all.  They just copied numbers from the LAMMPS website, which might or might not really be comparable.

**Comment by VijayPande** [comment]
wow.  that’s annoying.

**Comment by VijayPande** [comment]
PS There’s also this
http://arxiv.org/pdf/1506.05094.pdf

**Comment by jchodera** [comment]
I think those are the same paper!

Closing this, since I mainly wanted people to just be aware of it.
