### ISSUE TITLE
Proposal to make use of issue tagging

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#977]
We're up to 127 issues here.  I propose we finally make use of GitHub's powerful issue tagging system.

To keep us from getting lost in a sea of issues, we can tag issues using a few basic tags, like:
* bug report
* feature request
* question
* documentation
* request for comments
* build issue

This would help us easily sort whether there are bugs remaining to be fixed, or identify all of the feature requests to separate them from other general usage questions.

We can also make use of the release planning system, where release targets could be enumerated (e.g. 6.4, 6.5, 7.0) and feature requests could be associated with release targets.  That way, the roadmap for features would be clear to everyone.

I think this would really help streamline things.

**Comment by VijayPande** [comment]
+1

**Comment by swails** [comment]
+1.  I think only @peastman can do this (maybe @rmcgibbo, too), but I'd be happy to help if people were comfortable giving me permissions to do that (not sure what kind of permissions need to be granted for applying labels).

**Comment by peastman** [comment]
Sounds like a good plan.

**Comment by jchodera** [comment]
Tagging in progress!
