### ISSUE TITLE
Update devtools/conda-recipe

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#978]
This is just a reminder for me to update [`devtools/conda-recipe`](https://github.com/pandegroup/openmm/tree/master/devtools/conda-recipe) to reflect changes to [`openmm-dev`](https://github.com/omnia-md/openmm-dev).  This isn't used currently, but it wouldn't be a good idea to let them get out of sync and forget about it.

**Comment by jchodera** [comment]
Actually, it looks like [`devtools/conda-recipe`](https://github.com/pandegroup/openmm/tree/master/devtools/conda-recipe) and the [`openmm-dev`](https://github.com/omnia-md/openmm-dev) conda recipe are rather divergent already, and it's not clear to me that we want to eradicate the [`devtools/conda-recipe`](https://github.com/pandegroup/openmm/tree/master/devtools/conda-recipe) in favor of [`openmm-dev`](https://github.com/omnia-md/openmm-dev).

* `devtools/conda-recipe` has a [`plugin-dir.patch`](https://github.com/pandegroup/openmm/blob/master/devtools/conda-recipe/plugin-dir.patch) not found in  [`openmm-dev`](https://github.com/omnia-md/openmm-dev)
*  the [`build.sh`](https://github.com/omnia-md/openmm-dev/blob/master/build.sh) in [`openmm-dev`](https://github.com/omnia-md/openmm-dev) seems to be more up to date than the [`build.sh`](https://github.com/pandegroup/openmm/blob/master/devtools/conda-recipe/build.sh) in [`devtools/conda-recipe`](https://github.com/pandegroup/openmm/tree/master/devtools/conda-recipe) 
* [`openmm-dev`](https://github.com/omnia-md/openmm-dev) has a [`post-link.sh`](https://github.com/omnia-md/openmm-dev/blob/master/post-link.sh) that seems to be doing something about the library paths

Do we just want to trash the [`devtools/conda-recipe`](https://github.com/pandegroup/openmm/tree/master/devtools/conda-recipe) in favor of the more recent [`openmm-dev`](https://github.com/omnia-md/openmm-dev)?

**Comment by rmcgibbo** [comment]
+1 to trashing it, if we're not using it actively inside this repo. we also have a copy in omnia-md/conda-recipes, so it's getting a bit complex already.

**Comment by jchodera** [comment]
OK, submitted PR #990.
