### ISSUE TITLE
CustomExternalForce and periodic boundary conditions

### ISSUE THREAD

**Issue by swails** [pandegroup/openmm#988]
I was having a very difficult time using `CustomExternalForce` to impose positional restraints for an Amoeba simulation recently.  What I tried basically was this:

```Python
force = mm.CustomExternalForce('k*((x-x0)^2+(y-y0)^2+(z-z0)^2)")
force.addGlobalParameter('k', 10*u.kilocalories_per_mole/u.angstrom**2)
force.addPerParticleParameter('x0')
force.addPerParticleParameter('y0')
force.addPerParticleParameter('z0')
force.setForceGroup(1)
for atom in pdb.atoms:
    if atom.residue.name in AMINO_ACIDS:
        force.addParticle(atom.idx, [atom.xx/10, atom.xy/10, atom.xz/10])
system.addForce(force)
# Create the context
context.setPositions(pdb.positions)
```

The simulation would almost immediately blow up.  I dug some more into what was happening and found that the particles seem to be getting reimaged before being applied to the `CustomExternalForce`.  In particular, I found the following:

```Python
context.getState(getPositions=True).getPositions()
context.getState(getPositions=True, enforcePeriodicBox=True).getPositions()
```

These two functions return different coordinates, since some of the coordinates are translated by a box length.  Based on the coordinates obtained in the first line, the CustomExternalForce should return a net force very close to 0 (since those were the coordinates used both to seed the context as well as to set the CustomExternalForce per-particle parameters).  But the forces are very much *not* zero for many particles.  The forces in fact match (almost exactly) what I calculate by hand using the positions I get from the second line of the above example.

Which leads me to the conclusion that the `CustomExternalForce` is using the imaged coordinates in its energy expression.

Is this intended?  Is this only true for Amoeba?  I don't recall having this problem before with `NonbondedForce`, but this system is rather atypical (crystal simulation with *far* more protein atoms than solvent).

**Comment by peastman** [comment]
Using a CustomExternalForce with periodic boundary conditions is complicated, because the positions are really only defined up to a periodic translation.  The best option is to write your expression to be periodic relative to the box size.

This was discussed a while back at https://simtk.org/forums/viewtopic.php?f=161&t=5248, and in fact that was what prompted adding the floor() and ceil() functions in 6.3.  It's still not ideal, though, since if you have a barostat then the box size will be changing.

**Comment by jlmaccal** [comment]
Should we consider suppling a built-in that can compute distances along each dimension subject to the minimum image convention? This could eliminate quite a bit of boilerplate in custom expressions.

**Comment by swails** [comment]
> Using a CustomExternalForce with periodic boundary conditions is complicated, because the positions are really only defined up to a periodic translation. The best option is to write your expression to be periodic relative to the box size.

I realize that, I was just surprised that the coordinates used by the `CustomExternalForce` differed from what I set via `context.setPositions`.  It was also surprising (to me) that `context.getState(enforcePeriodicBox=False)` returned the exact same coordinates I fed it via `context.setPositions`, but that the positions used by `CustomExternalForce` corresponded to the ones I got setting `enforcePeriodicBox=True`.

> This was discussed a while back at https://simtk.org/forums/viewtopic.php?f=161&t=5248, and in fact that was what prompted adding the floor() and ceil() functions in 6.3. It's still not ideal, though, since if you have a barostat then the box size will be changing.

True.  That's not an immediate concern, as I'm just trying to do positional restraints in NVT (although the ability to do positional restraints in NpT in which the restraint coordinates get scaled with the box would be nice).  This is still tougher to do when you have a triclinic cell, I think.  Your expression is a bit more complicated than just dividing by the length of the a-, b-, and c-vectors for the x, y, and z dimensions, respectively when working in Cartesian rather than scaled coordinates, right?

For the time being, I'm just going to use the hack in which I basically get the coordinates from `context.getState(enforcePeriodicBox=True)` and set the restraint positions based on that.  Not ideal, but I can get my simulation working immediately that way.  Looking forward it would be nice to have a `CustomExternalForce` that is easier to work with in the context of PBC.

**Comment by jchodera** [comment]
I agree that this behavior is surprising! I had thought it worked the other
way around.

A mode that operates on the original unimaged coordinates would be great,
but maybe we could make the current behavior support clear in the current
docs?

**Comment by peastman** [comment]
I think @jlmaccal's idea is probably the best approach.  If you're using periodic boundary conditions, particle positions *are only defined* up to a translation by periodic box vectors.  We really can't make any guarantee at all about which periodic copy the force will be given.  So a "periodic distance" function you can use in your expression would let you describe the calculation you really intend to do.

To make John happy, I therefore am tagging this issue as an enhancement. :)

**Comment by swails** [comment]
> If you're using periodic boundary conditions, particle positions are only defined up to a translation by periodic box vectors.

Yes, I'm aware of this ;).  I was simply expressing surprise that OpenMM clearly stores multiple representations of each particle somewhere, since `context.getState(getPositions=True).getPositions()` yields the positions I put in, while `context.getState(getPositions=True, enforcePeriodicBox=True).getPositions()` yielded another set of (imaged) coordinates, and the representation that `CustomExternalForce` used was not the one I put in, but another one that is admittedly equivalent under PBC.

> So a "periodic distance" function you can use in your expression would let you describe the calculation you really intend to do.

+1.  In the meantime, I have a (hacky) workaround that should work in hopefully most cases.  At least where it fails the forces will be so large that the simulation will immediately blow up :).

**Comment by jchodera** [comment]
> To make John happy, I therefore am tagging this issue as an enhancement. :)

Molto grazie!

**Comment by peastman** [comment]
That's done for accuracy.  When working in single precision, it's important not to let the particle positions get too big.  So it translates all of them into a single periodic box, but also remembers the (integer) number of box widths it was translated by, so when you query the positions it can translate them back.

However, there are some complications.

1. That only applies to the CUDA and OpenCL platforms.  The Reference platform stores everything in double, and hence doesn't worry about translating them for accuracy.  The CPU platform creates a translated, single precision version of the positions at each time step, but only uses them for nonbonded forces, not for CustomExternalForce.

2. If you have a barostat in your system, that will translate everything into a single periodic box each time it attempts a step.

**Comment by swails** [comment]
> That's done for accuracy. When working in single precision, it's important not to let the particle positions get too big.

True -- I've actually made similar arguments in the past telling people why they should use `iwrap=1` in Amber simulations (for precisely this reason).

> So it translates all of them into a single periodic box, but also remembers the (integer) number of box widths it was translated by, so when you query the positions it can translate them back.

Useful.  There are times when it's easier not to wrap images back to a 'primary' unit cell.

> However, there are some complications.

Good to know.  All told, it will be useful for `CustomExternalForce` to be able to deal with PBCs unambiguously.  The workaround I have now will work for the time being, but something less awkward (and compatible with barostat scaling) would be nice.

**Comment by jchodera** [comment]
Allowing the user control over whether `CustomExternalForce` should operate on wrapped or unwrapped coordinates would be ideal.  Perhaps a method `CustomExternalForce.useImagedCoordinates(bool)` that would be set to `True` to capture the current behavior as default?

**Comment by peastman** [comment]
"Wrapped" and "unwrapped" coordinates aren't uniquely defined.  For example, do you define coordinates from -boxsize/2 to boxsize/2, or from 0 to boxsize?  Perhaps you provided coordinates based on the former, but if you have a barostat on the system, it will transform them to the later.  Also, translations are performed by molecule, not by atom, so some atoms may be outside the "primary" box.  To make sure this is done correctly, you really need to apply the periodic boundary conditions to *differences* between coordinates, not to individual coordinates.

**Comment by ctk3b** [comment]
I happened to run into exactly this problem today when trying to fix positions of a crystal the [way you did](https://github.com/ParmEd/ParmEd/wiki/OpenMM-Tricks-and-Recipes#fixing-atomic-positions), @swails. Would you be willing to share your workaround for the time being?

**Comment by swails** [comment]
Sure.  It's hacktastically ugly :).  See @peastman's caveats, though.  This is only appropriate for the GPU platforms, and is largely heuristic, but it works in my hands.  On the CPU platforms, the trick on my wiki should work.

This code is taken from one of my scripts, if it's unclear, let me know.

```Python
# Add cartesian restraints if desired
if opt.restraints:
    print('Adding restraints (k=%s kcal/mol/A^2) from %s' %
            (opt.force_constant, opt.restraints))
    sel = pmd.amber.AmberMask(pdb, opt.restraints).Selection() # True if selected, False if not
    const = opt.force_constant * u.kilocalories_per_mole/u.angstroms**2
    const = const.value_in_unit_system(u.md_unit_system)
    force = mm.CustomExternalForce('k*((x-x0)^2+(y-y0)^2+(z-z0)^2)')
    force.addGlobalParameter('k', const)
    force.addPerParticleParameter('x0')
    force.addPerParticleParameter('y0')
    force.addPerParticleParameter('z0')
    for i, atom_crd in enumerate(pdb.positions):
        if sel[i]:
            force.addParticle(i, atom_crd.value_in_unit(u.nanometers))
    system.addForce(force)

# Create the simulation
integrator = mm.LangevinIntegrator(298*u.kelvin, 1.0/u.picosecond,
                                   1*u.femtoseconds)
sim = app.Simulation(pdb.topology, system, integrator,
                     mm.Platform.getPlatformByName('CUDA'))

if opt.state is not None:
    print('Setting coordinates and velocities from state file %s' % opt.state)
    with open(opt.state, 'r') as f:
        sim.context.setState(mm.XmlSerializer.deserialize(f.read()))
else:
    print('Setting coordinates from PDB file %s' % opt.pdb)
    sim.context.setPositions(pdb.positions)
    sim.context.setVelocitiesToTemperature(298)

if opt.restraints:
    positions = sim.context.getState(getPositions=True,
            enforcePeriodicBox=True).getPositions()
    for i in range(force.getNumParticles()):
        j, params = force.getParticleParameters(i)
        force.setParticleParameters(i, j, positions[j])
    force.updateParametersInContext(sim.context)
```

Basically, what I do is create the force as per my ParmEd wiki, create the `Context`, set the positions, then get those positions *back* from a `State` by setting `enforcePeriodicBox=True`.  This will give the same "wrapped" coordinates that `CustomExternalForce` will use.  So then I re-set the per-particle x, y, and z reference positions from this new state, update the parameters in context, and go.

**Comment by ctk3b** [comment]
Many thanks!

**Comment by peastman** [comment]
I'm trying to decide how to implement this feature.  I can think of several possibilities.  On option is to have a single `periodicDistance` function:

    dr = periodicDistance(x1,y1,z1,x2,y2,z2)

Or we could have a separate function for each axis:

    dx = periodicDistanceX(x1, x2); dy = periodicDistanceY(y1, y2); dz = periodicDistanceZ(z1, z2)

Or we could have functions that take a displacement and apply periodic boundary conditions to it:

    dx = periodicx(x1-x2); dy = periodicy(y1-y2); dz = periodicz(z1-z2)

I can see arguments for all of those.  Anyone have preferences?

Also, what forces should support this feature?  Obviously CustomExternalForce, but any others?

**Comment by swails** [comment]
Maybe `CustomBondForce`, `CustomAngleForce`, and `CustomTorsionForce` for doing surfaces where bonds can cross periodic boundaries? Or just `CustomCompoundBondForce`, which can generalize to the rest of them.

**Comment by swails** [comment]
As for the API, I like the second one the best (separate `periodicDistance` for each axis).  Maximal flexibility and easiest for me to wrap my head around.

**Comment by peastman** [comment]
All of these are equally flexible.  Given any one of them, you can reproduce the others.  `periodicDistanceX(x1, x2) = periodicx(x1-x2) = periodicDistance(x1,0,0,x2,0,0)`.  It's just a question of which will be most convenient.

This is only relevant to forces that actually expose the coordinates of individual particles.  For example, the energy expression in `CustomBondForce` can't depend on particle coordinates, only on distances.  Also, if you add a bond between two particles, they'll be treated as part of the same molecule and always kept together when translating them, so this isn't relevant.  The only cases where it does matter are when you're calculating the energy based on the absolute position of a particle or group of particles.  `CustomCompoundBondForce`, `CustomGBForce`, and `CustomCentroidBondForce` all have that ability, though it isn't the main use of all of them.  `CustomIntegrator` could also conceivably have something like this, though it would have to be written a little differently, since expressions there are applied per-DOF rather than per-particle.  It also would probably mean you were abusing `CustomIntegrator` to do something that really should be done in a force instead!

**Comment by swails** [comment]
> All of these are equally flexible. Given any one of them, you can reproduce the others. periodicDistanceX(x1, x2) = periodicx(x1-x2) = periodicDistance(x1,0,0,x2,0,0). It's just a question of which will be most convenient.

Ah, right, fill the others with zeros... hadn't thought about that.  `periodicDistance[XYZ](a, b)` still fits my brain the best and seems most straightforward if you want to do stuff like periodic cylindrical or planar restraints.  Not sure what it is for other people, though.

**Comment by peastman** [comment]
Actually, it's more complicated than that.  If the periodic box isn't rectangular, you can't just apply PBC separately to each axis.  You really need a `periodicdistance()` function that considers all three axes at once.

**Comment by jlmaccal** [comment]
I'm working on implementing explicit solvent support in MELD, and this issue has come up.

Three questions:

1. Is this function only available for CustomExternalForces, or is it available everywhere?

2. It would be great if this function could "do the right thing" depending on the type of cutoff / periodic scheme. When PBC is being used, it should use the minimum image convention. When PBC is not being used, it should simply compute the distance as normal, ignoring the box vectors, which are probably nonsense. I can, of course, create different versions of a custom force depending on the status of PBC, but it would be nice if this could be avoided.

3. Is there similar support available when writing a plugin rather than using a `Custom*Force`? It would be great if there was a system-wide way to compute distances that always did the right thing.

**Comment by peastman** [comment]
This function is only in CustomExternalForce.  However, I recently added support for periodic boundary conditions to all the bonded forces as well.  Just call `setUsesPeriodicBoundaryConditions(True)` on them.

CustomExternalForce is kind of different from all the others.  Periodic boundary conditions really apply to displacements between particles, not to the positions of individual particles.  With most bonded or nonbonded forces, it calculates the displacements for you, and then you just tell it what to do with them.  But CustomExternalForce only applies to one particle at a time.  There are no displacements involved.  But sometimes you want to manually compute a displacement as part of your energy expression, and that's where the `periodicdistance()` function is relevant.

When writing a plugin, all the platforms provide mechanisms for applying periodic boundary conditions to displacements.  Those mechanisms are specific to each platform though.

**Comment by jlmaccal** [comment]
Thanks for the info. A few more questions...

> This function is only in CustomExternalForce. However, I recently added support for periodic boundary conditions to all the bonded forces as well. Just call setUsesPeriodicBoundaryConditions(True) on them.

Could you elaborate a bit on this? If I wanted to add a custom bond between two different molecules, what would I need to do in order to get correct distances with periodic boundary conditions? What about if I only wanted the individual xyz components? Would the same CustomForce work for both PBC and non-PBC cases?

> When writing a plugin, all the platforms provide mechanisms for applying periodic boundary conditions to displacements. Those mechanisms are specific to each platform though.

Are these mechanisms documented? Do we need to write separate code for systems with and without periodic boundaries? Is there anything `#defined` when PBCs are active, or will the plugin need to implement somthing like `setUsePeriodicBoundaries`?

**Comment by peastman** [comment]
> If I wanted to add a custom bond between two different molecules, what would I need to do in order to get correct distances with periodic boundary conditions?

Call `setUsesPeriodicBoundaryConditions(True)` on the CustomBondForce.

> What about if I only wanted the individual xyz components?

Not sure what you mean.  CustomBondForce only depends on the distance, not individual components.

> Would the same CustomForce work for both PBC and non-PBC cases?

It will use whichever behavior you request with `setUsesPeriodicBoundaryConditions()`.

> Do we need to write separate code for systems with and without periodic boundaries?

Describe what you want to do and which platform you want to do it in, and I can describe how to do it.

**Comment by jlmaccal** [comment]
> On May 18, 2016, at 11:56 AM, peastman <notifications@github.com> wrote:
> 
> Describe what you want to do and which platform you want to do it in, and I can describe how to do it.
> 
> 

In my case, it would be for Cuda.

**Comment by peastman** [comment]
The CUDA platform defines some macros for use in kernels that apply periodic boundary conditions:

https://github.com/pandegroup/openmm/blob/master/platforms/cuda/src/CudaContext.cpp#L255-L306

It's up to you to decide whether to call those macros or not.  Typically forces define a symbol to indicate whether periodic boundary conditions should be applied.  For example, at https://github.com/pandegroup/openmm/blob/master/platforms/cuda/src/kernels/nonbonded.cu#L157-L160:

```C++
real3 delta = make_real3(posq2.x-posq1.x, posq2.y-posq1.y, posq2.z-posq1.z);
#ifdef USE_PERIODIC
APPLY_PERIODIC_TO_DELTA(delta)
#endif
```

**Comment by jlmaccal** [comment]
Thanks!

> Not sure what you mean. CustomBondForce only depends on the distance, not individual components

Maybe that was a bad example. As a better one, consider I want to add a COM restraint along just the x-axis using `CustomCentroidBondForce`. I might have something like this:
```
cf = CustomCentroidBondForce(
    '0.5 * k * delta^2;'
    'delta = x2 - x1;')
```

Is there a way to compute `delta` the respects PBC?

**Comment by peastman** [comment]
No, for that we'd need to add `periodicdistance()` to CustomCentroidBondForce as well.  If that would be useful to you, go ahead and open a separate issue as a feature request for it.

**Comment by swails** [comment]
Speaking of `CustomCentroidBondForce`, how are the COMs going to be computed?  Do you apply PBC transformations to *all* parts of the calculation?  There are an infinite number of ways to image the atoms *before* computing the COM (including no imaging at all), and for groups of atoms that may be dispersed, or that may have migrated close to the edge of the box, you may find yourself in a situation with very abrupt and pronounced changes in where the COM may be for some groups of atoms.

**Comment by peastman** [comment]
Actually, I just looked to see how I'd implemented this.  For purposes of wrapping atoms to the periodic box, it treats all atoms involved in each bond as a single molecule.  So if you have two groups, and the centroids of those groups are connect by a bond, it will treat all of that as a single unit.  It will never wrap some of those atoms but not others.

This means you will never get a discontinuous change in the displacement between the two centroids.  But it doesn't guarantee that displacement is the shortest of all possible periodic copies.

**Comment by swails** [comment]
That's probably the most sensible approach, but when you apply PBC to bonds, angles, etc. it would be surprising behavior.

Basically what this means is that `CustomCentroidBondForce` doesn't have an analogous `setUsesPeriodicBoundaryConditions` (like you recently added to the other bonded terms).

**Comment by peastman** [comment]
All bonded forces work that way: it only translates whole molecules, never pieces of molecules.

When you call `setUsesPeriodicBoundaryConditions(True)`, then whenever you say `distance(g1,g2)` in your expression it guarantees that will return the shortest distance between any two periodic copies of those two groups, which I think is exactly what you'd expect.  It's only when you write out the displacement explicitly as `x2-x1` that it doesn't guarantee that.

**Comment by swails** [comment]
My point was that if you use `setUsesPeriodicBoundaryConditions` on a `BondForce`, the distances you get out are the shortest possible distances.  The analogy I see with the centroid forces is that the centroid would be defined by the point with a minimum "sum of squares" distances to all atoms in the group for the images of those atoms that minimizes that objective function (if that makes sense).

So if imaging one or more atoms in the group to another unit cell will result in a centroid that is closer to all of the atoms, then that imaging is performed on those atoms.  So it's possible that the distance between two atoms used in a bond will be different than that same distance used in a COM (or COG) calculation for a centroid force.
