### ISSUE TITLE
Infinite energy

### ISSUE THREAD

**Issue by alexW432** [pandegroup/openmm#989]
Hi,
I'm trying to implement a custom non bonded force, with help I got the code to run however for certain forces I get, ValueError: energy is infinite. This is the python I am running:
```Python
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from sys import stdout

pdb = PDBFile('Water2.pdb')
forcefield = ForceField('amber99sb.xml', 'tip3p.xml')
system = forcefield.createSystem(pdb.topology,nonbondedMethod=app.CutoffPeriodic, nonbondedCutoff=0.5*nanometer, constraints=HBonds)

force = CustomNonbondedForce('A*((B*exp(gamma*(1-(r/C))))-((C/r)^6)); r=sqrt(x*x+y*y+z*z)')
force.addGlobalParameter('A', 3*pow(10,-21))
force.addGlobalParameter('C', 3.5*pow(10,-10))
force.addGlobalParameter('B', 0.47)
force.addGlobalParameter('gamma', 12.75)
print(system.getNumParticles())
for i in range(system.getNumParticles()):
     force.addParticle(())
system.addForce(force)

integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
simulation = Simulation(pdb.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
simulation.minimizeEnergy(10, 100)
simulation.reporters.append(PDBReporter('output.pdb', 10))
simulation.reporters.append(StateDataReporter(stdout, 10, step=True, potentialEnergy=True, temperature=True))
simulation.step(1000)
```

If I change the custom force around it seems to work for positive powers of r and exponentials however not for negative powers of r. Any help would be greatly appreciated. 
Many Thanks,
Alex

**Comment by alexW432** [comment]
This is the pdb I used:
CRYST1   10.163   10.981   10.869  90.00  90.00  90.00 P 1           1
MODEL        0
ATOM    585  OW  HOH    38       4.690   3.950   8.530  1.00  0.00
ATOM    586  HW1 HOH    38       3.750   4.120   8.550  1.00  0.00
ATOM    587  HW2 HOH    38       4.890   3.660   9.420  1.00  0.00
ATOM    588  OW  HOH    39       2.030   3.230   8.140  1.00  0.00
ATOM    589  HW1 HOH    39       2.710   2.960   8.750  1.00  0.00
ATOM    590  HW2 HOH    39       1.240   2.790   8.450  1.00  0.00
TER
ENDMDL

Again Thanks,
Alex

**Comment by swails** [comment]
Github does weird things with Markup.  Can you edit your comments to put your Python code between "\`\`\`Python" and "\`\`\`" blocks?  Like so:

\`\`\`Python
put your python code here
\`\`\`

It will make things much easier to read for us.

**Comment by peastman** [comment]
Shouldn't the coefficient of (c/r)^6 be positive instead of negative?  Your energy will go to negative infinity as r goes to 0.  For atoms that already have a Lennard-Jones term on them, that will prevent them from getting too close.  But tip3p doesn't include an LJ term on the hydrogens.

By the way, it understands exponential notation for numbers.  So instead of "3*pow(10,-21)", you can just write "3e-21".

**Comment by alexW432** [comment]
I have now tried with both negative and positive coefficients on the r^-6, unfortunately I can seem to get this to work. I have also tried changing the force field to add a custom non bonded force. With the new xml here:
```Python
-<ForceField>
-<AtomTypes>
<Type mass="15.99943" element="O" class="OW" name="tip3p-O"/>
<Type mass="1.007947" element="H" class="HW" name="tip3p-H"/>
</AtomTypes>
-<Residues>
-<Residue name="HOH">
<Atom name="O" type="tip3p-O"/>
<Atom name="H1" type="tip3p-H"/>
<Atom name="H2" type="tip3p-H"/>
<Bond to="1" from="0"/>
<Bond to="2" from="0"/>
</Residue>
</Residues>
-<HarmonicBondForce>
<Bond k="462750.4" length="0.09572" class2="HW" class1="OW"/>
</HarmonicBondForce>
-<HarmonicAngleForce>
<Angle k="836.8" class2="OW" class1="HW" angle="1.82421813418" class3="HW"/>
</HarmonicAngleForce>
-<NonbondedForce lj14scale="0.5" coulomb14scale="0.833333">
<Atom type="tip3p-O" epsilon="0.635968" sigma="0.31507524065751241" charge="-0.834"/>
<Atom type="tip3p-H" epsilon="0" sigma="1" charge="0.417"/>
</NonbondedForce>
-<CustomNonbondedForce bondCutoff="0" energy="4*B*((0.31507524065751241/7)^12-(0.31507524065751241/r)^6); r=sqrt(x*x+y*y+z*z)">
<PerParticleParameter name="B"/>
<Atom type="tip3p-O" B="0.635968"/>
<Atom type="tip3p-H" B="0"/>
</CustomNonbondedForce>
</ForceField>
```
I tried to add a LJ as I thought this would be the simplest however adding the force like this still does not work and gives energy NaN instead of infinite. Is there a way to look at the output of the minimisation to see what is going on?

**Comment by peastman** [comment]
Ok, I feel silly for not having spotted the problem right away.  But CustomNonbondedForce should have caught it too, and I need to figure out why it didn't.  The problem is this part of your expression: "r=sqrt(x\*x+y\*y+z\*z)".  You don't need to define r.  CustomNonbondedForce expects to be given the energy as a function of r.  Instead, you've redefined it in terms of x, y, and z.  But x, y, and z are undefined variables, so it *should* have complained about them.  I'll look into that.

Anyway, just remove that part from your expression and it works fine.

**Comment by alexW432** [comment]
Thank you this was very helpful it now seems to be working great.Sorry ask so many questions but I think this is my last. Do CustomNonbonded forces replace the Lennard Jones potential or just add to it? I wish to replace it entirely, so should I set the eps and sig for oxygen to 0 and 1 in the forcefeild.xml I use?

**Comment by swails** [comment]
All forces you add to a `System` are additive.  So if you have both a `NonbondedForce` and a `CustomNonbondedForce`, the total energy and force is a sum of both.

If you want `CustomNonbondedForce` to replace the `NonbondedForce` L-J terms, you need to make sure that the epsilon parameters are zero for the relevant atoms.

**Comment by alexW432** [comment]
Thank you both, really appreciate your help.
Alex
