### ISSUE TITLE
Plugin load order undefined

### ISSUE THREAD

**Issue by rmcgibbo** [pandegroup/openmm#996]
I've observed an issue where the OpenCL Drude plugin fails to load when openmm is initially imported from python. To test it out, try running the script here https://gist.github.com/rmcgibbo/f5ca495d9f121833f1dc, and then try running it again passing the `--reload` flag, and see if you get an error in one case that the platform doesn't support all the required kernels.

The problem is that the load order of the plugins in loadPluginsFromDirectory is undefined, and, on my machine, happens to be (libOpenMMCPU.so, libOpenMMAmoebaReference.so, libOpenMMRPMDReference.so, libOpenMMDrudeOpenCL.so, libOpenMMPME.so, libOpenMMOpenCL.so, libOpenMMRPMDOpenCL.so, libOpenMMDrudeReference.so). For whatever reason, libOpenMMDrudeOpenCL is loaded before libOpenMMOpenCL.

Since libOpenMMDrudeOpenCL refers to symbols in libOpenMMOpenCL, but libOpenMMOpenCL is neither in the LD_LIBRARY_PATH nor currently loaded into the process, the dlopen call fails.

**Comment by peastman** [comment]
How about if you add the plugins directory to your LD_LIBRARY_PATH?

Ideally it shouldn't matter, and the library should just be found by a relative path.  But I'm not certain how to make that work on Linux.

**Comment by rmcgibbo** [comment]
Yeah, that makes it work. But not ideal -- we got away from requiring that with the latest releases, and it's not possible with conda. #997 is kind of a poor heuristic, but it does work.

**Comment by swails** [comment]
Fixed by #997, right?
